:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[account_address]]
= Address

[[account_address_contracts]]
== Contracts
[[account_contracts_addresscontactrelationrepositorycontract]]
=== AddressContactRelationRepositoryContract

The AddressContactRelationRepositoryContract is the interface for the address contact relation repository.



==== Namespace

`Plenty\Modules\Account\Address\Contracts`






==== Methods

[source%nowrap, php]
----

public createAddressContactRelation($data):array

----

    





Creates address contact relations.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The address data as associative array
|===


[source%nowrap, php]
----

public updateAddressContactRelation($data):array

----

    





Updates address contact relations.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The data as associative array
|===


[source%nowrap, php]
----

public findAddressContactRelation($addressContactRelationId):Plenty\Modules\Account\Address\Models\AddressContactRelation

----

    


===== *Return type:*        xref:Account.adoc#account_models_addresscontactrelation[`AddressContactRelation`]


Gets address contact relation by ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressContactRelationId`
a|The ID of the address contact relation
|===


[source%nowrap, php]
----

public deleteAddressContactRelation($addressContactRelationId):bool

----

    





Deletes an address contact relation.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressContactRelationId`
a|The ID of the address contact relation
|===


[source%nowrap, php]
----

public listAddressContactRelations($filter = [], $with = [], $columns = [], $page = 1, $itemsPerPage = 50):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Lists address contact relations.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filter`
a|Filter that restricts the search result

|link:http://php.net/array[array^]
a|`$with`
a|An array with child instances to be loaded

|link:http://php.net/array[array^]
a|`$columns`
a|The columns to retrieve

|link:http://php.net/int[int^]
a|`$page`
a|The page of results to search for

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items to list per page
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.


[[account_contracts_addressparamconfigurationrepositorycontract]]
=== AddressParamConfigurationRepositoryContract

The AddressParamConfigurationRepositoryContract is the interface for the address param configuration repository. This interface allows to create, update, delete, list and get address relation types and address option types.



==== Namespace

`Plenty\Modules\Account\Address\Contracts`






==== Methods

[source%nowrap, php]
----

public createAddressRelationType($data):Plenty\Modules\Account\Address\Models\AddressRelationType

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressrelationtype[`AddressRelationType`]


Creates a new address relation type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public updateAddressRelationType($data, $addressRelationTypeId):Plenty\Modules\Account\Address\Models\AddressRelationType

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressrelationtype[`AddressRelationType`]


Updates an existing address relation type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The address relation data as associative array

|link:http://php.net/int[int^]
a|`$addressRelationTypeId`
a|
|===


[source%nowrap, php]
----

public deleteAddressRelationType($addressRelationTypeId):bool

----

    





Deletes an address relation type by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressRelationTypeId`
a|The ID of the address relation type
|===


[source%nowrap, php]
----

public findAddressRelationTypeById($addressRelationTypeId):Plenty\Modules\Account\Address\Models\AddressRelationType

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressrelationtype[`AddressRelationType`]


Gets an existing address relation type by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressRelationTypeId`
a|The ID of the address relation type
|===


[source%nowrap, php]
----

public allAddressRelationTypes($columns = [], $perPage = 50):void

----

    





Gets a list of address relation types.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|The columns to retrieve

|link:http://php.net/int[int^]
a|`$perPage`
a|The number of items to list per page
|===


[source%nowrap, php]
----

public createAddressOptionType($data):Plenty\Modules\Account\Address\Models\AddressOptionType

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressoptiontype[`AddressOptionType`]


Creates an address option type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public updateAddressOptionType($data, $addressOptionTypeId):Plenty\Modules\Account\Address\Models\AddressOptionType

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressoptiontype[`AddressOptionType`]


Updates an existing address option type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|

|link:http://php.net/int[int^]
a|`$addressOptionTypeId`
a|The ID of the address option type
|===


[source%nowrap, php]
----

public deleteAddressOptionType($addressOptionTypeId):bool

----

    





Deletes an address option type by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressOptionTypeId`
a|The ID of the address option type
|===


[source%nowrap, php]
----

public findAddressOptionTypeById($addressOptionTypeId):Plenty\Modules\Account\Address\Models\AddressOptionType

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressoptiontype[`AddressOptionType`]


Finds an existing address option type by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressOptionTypeId`
a|The ID of the address option type
|===


[source%nowrap, php]
----

public allAddressOptionType($columns = [], $perPage = 50):void

----

    





Gets a list of address option types.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|The columns to retrieve

|link:http://php.net/int[int^]
a|`$perPage`
a|The number of items to list per page
|===



[[account_contracts_addressposrelationrepositorycontract]]
=== AddressPosRelationRepositoryContract

The AddressPosRelationRepositoryContract is the interface for the address POS relation repository.



==== Namespace

`Plenty\Modules\Account\Address\Contracts`






==== Methods

[source%nowrap, php]
----

public createAddressPosRelation($data):Plenty\Modules\Account\Address\Models\AddressPosRelation

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressposrelation[`AddressPosRelation`]


Creates an address POS relation.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The address data as associative array
|===


[source%nowrap, php]
----

public updateAddressPosRelation($addressPosRelationId, $data):Plenty\Modules\Account\Address\Models\AddressPosRelation

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressposrelation[`AddressPosRelation`]


Updates an address POS relation.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressPosRelationId`
a|The ID of the address POS relation

|link:http://php.net/array[array^]
a|`$data`
a|The data as associative array
|===


[source%nowrap, php]
----

public findAddressPosRelation($addressPosRelationId):Plenty\Modules\Account\Address\Models\AddressPosRelation

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressposrelation[`AddressPosRelation`]


Lists address POS relations.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressPosRelationId`
a|The ID of the address POS relation
|===


[source%nowrap, php]
----

public deleteAddressPosRelation($addressPosRelationId):void

----

    





Deletes an address POS relation.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressPosRelationId`
a|The ID of the address POS relation
|===


[source%nowrap, php]
----

public listAddressPosRelations($filter = [], $with = [], $columns = [], $page = 1, $itemsPerPage = 50):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Lists address POS relations.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filter`
a|Filter that restricts the search result

|link:http://php.net/array[array^]
a|`$with`
a|An array with child instances to be loaded

|link:http://php.net/array[array^]
a|`$columns`
a|The columns to retrieve

|link:http://php.net/int[int^]
a|`$page`
a|The page of results to search for

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items to list per page
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.


[[account_contracts_addressrepositorycontract]]
=== AddressRepositoryContract

The AddressRepositoryContract is the interface for the address repository contract. This interface allows to get, update, create and delete addresses and address options.



==== Namespace

`Plenty\Modules\Account\Address\Contracts`






==== Methods

[source%nowrap, php]
----

public findAddressById($addressId):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Gets an address. The ID of the address must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address
|===


[source%nowrap, php]
----

public updateAddress($data, $addressId):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Updates an address. The ID of the address must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The address data as associative array

|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address
|===


[source%nowrap, php]
----

public createAddress($data):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Creates an address.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The address data as associative array
|===


[source%nowrap, php]
----

public deleteAddress($addressId):bool

----

    





Deletes an address. The ID of the address must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address
|===


[source%nowrap, php]
----

public getAddressesOfWarehouse($warehouseId, $relationTypeId = null, $columns = [], $perPage = 50):Illuminate\Database\Eloquent\Collection

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Returns a collection of addresses linked with a warehouse.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|The ID of the warehouse

|link:http://php.net/int[int^]
a|`$relationTypeId`
a|The ID of the relation type

|link:http://php.net/array[array^]
a|`$columns`
a|The columns to retrieve

|link:http://php.net/int[int^]
a|`$perPage`
a|The quantity of the result
|===


[source%nowrap, php]
----

public createAddressOfWarehouse($data):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Creates an address and immediately links it with a warehouse.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The data to save
|===


[source%nowrap, php]
----

public findAddressOptions($addressId, $typeId):Illuminate\Database\Eloquent\Collection

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Returns a collection of address options of an address.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address

|link:http://php.net/int[int^]
a|`$typeId`
a|(Optional) The ID of an address option type
|===


[source%nowrap, php]
----

public createAddressOptions($addressData, $addressId):Illuminate\Database\Eloquent\Collection

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Creates address options for an address and returns all options of the address.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$addressData`
a|The address option data as associative array. Multiple options are possible.

|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address
|===


[source%nowrap, php]
----

public updateAddressOptions($addressData, $addressId):Illuminate\Database\Eloquent\Collection

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Updates address options for an address and returns all options of the address.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$addressData`
a|The address option data as associative array. Multiple options are possible.

|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address
|===


[source%nowrap, php]
----

public deleteAddressOptions($addressId):void

----

    





Deletes all address options of an address. The ID of the address must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address
|===


[source%nowrap, php]
----

public getAddressOption($optionId):Plenty\Modules\Account\Address\Models\AddressOption

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressoption[`AddressOption`]


Gets an address option. The ID of the option must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$optionId`
a|The ID of the address option
|===


[source%nowrap, php]
----

public updateAddressOption($optionData, $optionId):Plenty\Modules\Account\Address\Models\AddressOption

----

    


===== *Return type:*        xref:Account.adoc#account_models_addressoption[`AddressOption`]


Updates an address option. The ID of the address option must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$optionData`
a|The option data as associative array

|link:http://php.net/int[int^]
a|`$optionId`
a|The ID of the address option
|===


[source%nowrap, php]
----

public deleteAddressOption($optionId):bool

----

    





Deletes an address option. The ID of the option must be specified. Returns `true` if deletion was successful. Returns `false` if deletion was not successful.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$optionId`
a|The ID of the address option
|===


[source%nowrap, php]
----

public findAddressRelationTypes($application, $lang):Illuminate\Database\Eloquent\Collection

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Returns a collection of address relation types by a specific application and language. The collection may be empty.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$application`
a|The application type

|link:http://php.net/string[string^]
a|`$lang`
a|The language as ISO 639-1 code (e.g. `en` for english).
|===


[source%nowrap, php]
----

public findAddressDataByAddressId($addressId, $orderIds):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Find address data by address id

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|

|link:http://php.net/string[string^]
a|`$orderIds`
a|
|===


[source%nowrap, php]
----

public findExistingAddress($addressData):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Find an existing address

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$addressData`
a|The address data as associative array
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[[account_address_models]]
== Models
[[account_models_address]]
=== Address

The address model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address
|link:http://php.net/string[string^]
    a|gender
    a|The gender ("female", "male" or "diverse")
|link:http://php.net/string[string^]
    a|name1
    a|The name 1 field (defaults to: company name)
|link:http://php.net/string[string^]
    a|name2
    a|The name 2 field (defaults to: first name)
|link:http://php.net/string[string^]
    a|name3
    a|The name 3 field (defaults to: last name)
|link:http://php.net/string[string^]
    a|name4
    a|The name 4 field (defaults to: c/o)
|link:http://php.net/string[string^]
    a|address1
    a|The address 1 field (defaults to: street|'PACKSTATION'|'POSTFILIALE')
|link:http://php.net/string[string^]
    a|address2
    a|The address 2 field (defaults to: houseNumber|packstationNo)
|link:http://php.net/string[string^]
    a|address3
    a|The address 3 field (defaults to: additional)
|link:http://php.net/string[string^]
    a|address4
    a|The address 4 field is currently undefined and can be freely used.
|link:http://php.net/string[string^]
    a|postalCode
    a|The postcode
|link:http://php.net/string[string^]
    a|town
    a|The town
|link:http://php.net/int[int^]
    a|countryId
    a|The ID of the country
|link:http://php.net/int[int^]
    a|stateId
    a|The ID of the state
|link:http://php.net/bool[bool^]
    a|readOnly
    a|Flag that indicates if the data record is read only
|link:http://php.net/string[string^]
    a|companyName
    a|The company name (alias for name1, <i>read only</i>)
|link:http://php.net/string[string^]
    a|firstName
    a|The first name (alias for name2, <i>read only</i>)
|link:http://php.net/string[string^]
    a|lastName
    a|The last name (alias for name3, <i>read only</i>)
|link:http://php.net/string[string^]
    a|careOf
    a|The c/o (alias for name4, <i>read only</i>)
|link:http://php.net/string[string^]
    a|street
    a|The street (alias for address1, <i>read only</i>)
|link:http://php.net/string[string^]
    a|houseNumber
    a|The house number (alias for address2, <i>read only</i>)
|link:http://php.net/string[string^]
    a|additional
    a|The additional address information (alias for address3, <i>read only</i>)
|
    a|checkedAt
    a|The time the address was checked as unix timestamp
|
    a|createdAt
    a|The time the address was created as unix timestamp
|
    a|updatedAt
    a|The time the address was last updated as unix timestamp
|link:http://php.net/string[string^]
    a|taxIdNumber
    a|The taxIdNumber option (alias for option with typeId 1, <i>read only</i>)
|link:http://php.net/string[string^]
    a|externalId
    a|The externalId option (alias for option with typeId 2, <i>read only</i>)
|link:http://php.net/bool[bool^]
    a|entryCertificate
    a|The entryCertificate option (alias for option with typeId 3, <i>read only</i>)
|link:http://php.net/string[string^]
    a|phone
    a|The phone option (alias for option with typeId 4, <i>read only</i>)
|link:http://php.net/string[string^]
    a|email
    a|The email option (alias for option with typeId 5, <i>read only</i>)
|link:http://php.net/string[string^]
    a|postident
    a|The PostIdent option (alias for option with typeId 6, <i>read only</i>)
|link:http://php.net/string[string^]
    a|personalNumber
    a|The personal number option (alias for option with typeId 7, <i>read only</i>)
|link:http://php.net/string[string^]
    a|fsk
    a|The age rating option (alias for option with typeId 8, <i>read only</i>)
|link:http://php.net/string[string^]
    a|birthday
    a|The birthday option (alias for option with typeId 9, <i>read only</i>)
|link:http://php.net/string[string^]
    a|title
    a|The title option (alias for option with typeId 11, <i>read only</i>)
|link:http://php.net/string[string^]
    a|sessionId
    a|The fronetnd session ID that was used when the address was created (alias for option with typeId 10, <i>read only</i>)
|link:http://php.net/string[string^]
    a|contactPerson
    a|The contact person option (alias for option with typeId 12, <i>read only</i>)
|link:http://php.net/string[string^]
    a|externalCustomerId
    a|The external customer ID option (alias for option with typeId 13, <i>read only</i>)
|link:http://php.net/string[string^]
    a|packstationNo
    a|The packstation number (alias for houseNumber and address2, <i>read only</i>)
|link:http://php.net/bool[bool^]
    a|isPackstation
    a|Flag that indicates if the address is a packstation
|link:http://php.net/bool[bool^]
    a|isPostfiliale
    a|Flag that indicates if the address is a postfiliale (post office)
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|options
    a|A collection of address options. Standard plentymarkets address option types:
<ul>
<li>1: tax id number (VAT number)</li>
<li>2: external ID</li>
<li>3: entry certificate (bool)</li>
<li>4: phone number</li>
<li>5: email</li>
<li>6: post number</li>
<li>7: personal ID</li>
<li>8: BBFC/FSK</li>
<li>9: birthday</li>
<li>10: frontend session ID</li>
<li>11: title (salutation)</li>
<li>12: contact person</li>
<li>13: external customer ID</li>
</ul>
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|contacts
    a|A collection of contacts that are linked with the address record
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|orders
    a|A collection of orders that are linked with the address record
|        xref:Order.adoc#order_models_country[`Country`]
    a|country
    a|The address country
|        xref:Order.adoc#order_models_countrystate[`CountryState`]
    a|state
    a|The address state
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|contactRelations
    a|A collection of relations to linked contacts
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|orderRelations
    a|A collection of relations to linked orders
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|warehouseRelations
    a|A collection of relations to linked warehouses
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|reorderRelations
    a|A collection of relations to linked reorders
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|schedulerRelations
    a|A collection of relations to linked schedulers
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addresscontactrelation]]
=== AddressContactRelation

The address contact relation model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address contact relation
|link:http://php.net/int[int^]
    a|contactId
    a|The ID of the contact
|link:http://php.net/int[int^]
    a|typeId
    a|The type ID of the address. Possible values:
<ul>
<li>Invoice address = 1</li>
<li>Delivery address = 2</li>
</ul>
|link:http://php.net/int[int^]
    a|addressId
    a|The ID of the address
|link:http://php.net/bool[bool^]
    a|isPrimary
    a|Flag that indicates if the address is primary
|        xref:Account.adoc#account_models_address[`Address`]
    a|address
    a|The address of the relation
|        xref:Account.adoc#account_models_contact[`Contact`]
    a|contact
    a|The contact of the relation
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addressoption]]
=== AddressOption

The address options model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address option
|link:http://php.net/int[int^]
    a|addressId
    a|The ID of the address
|link:http://php.net/int[int^]
    a|typeId
    a|The ID of the address option type
|link:http://php.net/string[string^]
    a|value
    a|The option value
|link:http://php.net/int[int^]
    a|position
    a|The position for sorting
|
    a|createdAt
    a|The time the option was created as unix timestamp
|
    a|updatedAt
    a|The time the option was last updated as unix timestamp
|        xref:Account.adoc#account_models_address[`Address`]
    a|address
    a|The address the option belongs to
|        xref:Account.adoc#account_models_addressoptiontype[`AddressOptionType`]
    a|type
    a|The option type of the address option
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addressoptiontype]]
=== AddressOptionType

The AddressOptionType model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address option type. It is possible to define individual types. The following types are available by default:
<ul>
<li>1 = VAT number</li>
<li>2 = External address ID</li>
<li>3 = Entry certificate</li>
<li>4 = Telephone</li>
<li>5 = Email</li>
<li>6 = Post number</li>
<li>7 = Personal id</li>
<li>8 = BBFC (age rating)</li>
<li>9 = Birthday</li>
<li>10 = Session ID</li>
<li>11 = Title</li>
<li>12 = Contact person</li>
<li>13 = External customer ID</li>
</ul>
|link:http://php.net/int[int^]
    a|position
    a|The position for sorting
|link:http://php.net/int[int^]
    a|nonErasable
    a|Flag that indicates if the type can be deleted
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|names
    a|A collection of address option type names
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|options
    a|A collection of all address options of the type
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addressoptiontypename]]
=== AddressOptionTypeName

The AddressOptionTypeName model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address option type name
|link:http://php.net/int[int^]
    a|typeId
    a|The ID of the address option type
|link:http://php.net/string[string^]
    a|lang
    a|The language of the name
|link:http://php.net/string[string^]
    a|name
    a|The name
|        xref:Account.adoc#account_models_addressoptiontype[`AddressOptionType`]
    a|type
    a|The address option type that belongs to the name
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addressorderrelation]]
=== AddressOrderRelation

address order relation model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address order relation
|link:http://php.net/int[int^]
    a|orderId
    a|The ID of the order
|link:http://php.net/int[int^]
    a|typeId
    a|The ID of the address type
<ul>
		<li>Billing address = 1</li>
		<li>Delivery address = 2</li>
		<li>Sender address = 3</li>
		<li>Return address = 4</li>
		<li>Client address = 5</li>
		<li>Contractor address = 6</li>
		<li>Warehouse address = 7</li>
	</ul>
|link:http://php.net/int[int^]
    a|addressId
    a|The ID of the address
|        xref:Account.adoc#account_models_address[`Address`]
    a|address
    a|The address of the relation
|        xref:Order.adoc#order_models_order[`Order`]
    a|order
    a|The order of the relation
|        xref:Account.adoc#account_models_addressrelationtype[`AddressRelationType`]
    a|type
    a|The address relation type
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addressposrelation]]
=== AddressPosRelation

The address POS relation model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address POS relation
|link:http://php.net/string[string^]
    a|posBaseId
    a|The ID of the POS base
|link:http://php.net/string[string^]
    a|addressId
    a|The ID of the address
|link:http://php.net/int[int^]
    a|typeId
    a|The ID of the relation type
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addressrelationtype]]
=== AddressRelationType

The contact address type model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address relation type. The following types are available by default and cannot be deleted:
<ul>
<li>1 = Billing address</li>
<li>2 = Delivery address</li>
<li>3 = Sender address</li>
<li>4 = Return address</li>
<li>5 = Client address</li>
<li>6 = Contractor address</li>
<li>7 = Warehouse address</li>
<li>8 = POS address</li>
</ul>
|link:http://php.net/int[int^]
    a|position
    a|The position for sorting
|link:http://php.net/int[int^]
    a|nonErasable
    a|Flag that indicates if the type can be deleted
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|names
    a|A collection of AddressRelationTypeName objects
|        xref:Account.adoc#account_models_addressrelationtypeapplication[`AddressRelationTypeApplication`]
    a|application
    a|The address relation type application
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addressrelationtypeapplication]]
=== AddressRelationTypeApplication

The AddressRelationTypeApplication model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address relation type name
|link:http://php.net/int[int^]
    a|typeId
    a|The ID of the relation type
|link:http://php.net/string[string^]
    a|application
    a|The application type. Allowed values: contact, order, warehouse.
|link:http://php.net/int[int^]
    a|position
    a|The position for sorting
|        xref:Account.adoc#account_models_addressrelationtype[`AddressRelationType`]
    a|type
    a|The type of the address relation
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addressrelationtypename]]
=== AddressRelationTypeName

The AddressRelationTypeName model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address relation type name
|link:http://php.net/int[int^]
    a|typeId
    a|The ID of the relation type
|link:http://php.net/string[string^]
    a|lang
    a|The language of the name
|link:http://php.net/string[string^]
    a|name
    a|The name
|        xref:Account.adoc#account_models_addressrelationtype[`AddressRelationType`]
    a|type
    a|The type of the address relation
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addressschedulerrelation]]
=== AddressSchedulerRelation

The AddressSchedulerRelation model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address order relation
|link:http://php.net/int[int^]
    a|schedulerId
    a|The ID of the scheduler
|link:http://php.net/int[int^]
    a|typeId
    a|The ID of the address type
|link:http://php.net/int[int^]
    a|addressId
    a|The ID of the address
|        xref:Order.adoc#order_models_orderscheduler[`OrderScheduler`]
    a|scheduler
    a|The scheduler of the order
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_addresswarehouserelation]]
=== AddressWarehouseRelation

The AddressWarehouseRelation model



==== Namespace

`Plenty\Modules\Account\Address\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the address warehouse relation
|link:http://php.net/int[int^]
    a|warehouseId
    a|The ID of the warehouse
|link:http://php.net/int[int^]
    a|typeId
    a|The ID of the type
|link:http://php.net/int[int^]
    a|addressId
    a|The ID of the address
|        xref:Account.adoc#account_models_address[`Address`]
    a|address
    a|The address of the relation
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[account_contactevent]]
= ContactEvent

[[account_contactevent_contracts]]
== Contracts
[[account_contracts_contacteventrepositorycontract]]
=== ContactEventRepositoryContract

The ContactEventRepositoryContract is the interface for the contact event repository. This interface allows to list contact events.



==== Namespace

`Plenty\Modules\Account\Contact\ContactEvent\Contracts`






==== Methods

[source%nowrap, php]
----

public listEvents($columns = [], $page = 1, $itemsPerPage = 50):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Lists contact events identified by the contact that is currently logged into the system.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|The columns to retrieve

|link:http://php.net/int[int^]
a|`$page`
a|The page of results to search for

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items to list per page
|===


[source%nowrap, php]
----

public listEventsByContactId($contactId, $columns = [], $page = 1, $itemsPerPage = 50):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Lists contact events by the contact ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/array[array^]
a|`$columns`
a|The columns to retrieve

|link:http://php.net/int[int^]
a|`$page`
a|The page of results to search for

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items to list per page
|===


[source%nowrap, php]
----

public createEvent($data):Plenty\Modules\Account\Contact\ContactEvent\Models\ContactEvent

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactevent[`ContactEvent`]


Adds an entry to the table customer events by the contact ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public updateEvent($contactEventId, $data):Plenty\Modules\Account\Contact\ContactEvent\Models\ContactEvent

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactevent[`ContactEvent`]


Updates an entry of the table customer events by the contact event ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactEventId`
a|The ID of the contact event

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public deleteEvent($contactEventId):void

----

    





Deletes an entry of the table customer events by the contact event ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactEventId`
a|The ID of the contact event
|===


[source%nowrap, php]
----

public getEventTypesPreview():array

----

    





Get the contact event types as key/pair array

[[account_contactevent_models]]
== Models
[[account_models_contactevent]]
=== ContactEvent

The contact event model.



==== Namespace

`Plenty\Modules\Account\Contact\ContactEvent\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|eventId
    a|The ID of the event
|link:http://php.net/int[int^]
    a|contactId
    a|The ID of the contact this event belongs to
|link:http://php.net/int[int^]
    a|userId
    a|The ID of the user this event belongs to
|link:http://php.net/int[int^]
    a|eventDuration
    a|The duration of the event in seconds
|link:http://php.net/string[string^]
    a|eventType
    a|The type of the event. Possible values are call, ticket, email, meeting, webinar, development and design.
|link:http://php.net/int[int^]
    a|orderRowId
    a|
|link:http://php.net/string[string^]
    a|eventInfo
    a|Informational text about the event
|link:http://php.net/bool[bool^]
    a|billable
    a|Billable if set to 1
|link:http://php.net/string[string^]
    a|eventInsertedAt
    a|The date the event was created at as unix timestamp
|link:http://php.net/string[string^]
    a|eventBilledAt
    a|The date the event was billed at as unix timestamp
|link:http://php.net/string[string^]
    a|eventProvisionPaidAt
    a|The date the provision was paid at as unix timestamp
|link:http://php.net/float[float^]
    a|eventCreditValue
    a|The credit value of the event
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[account_contact]]
= Contact

[[account_contact_contracts]]
== Contracts
[[account_contracts_contactaccessdatarepositorycontract]]
=== ContactAccessDataRepositoryContract

The ContactAccessDataRepositoryContract is the interface for the contact access data repository. This interface allows to reset and change contact password, get a login URL and unblock users.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public updatePassword($contactId, $data):void

----

    





Updates the password for a contact.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/array[array^]
a|`$data`
a|The data as associative array
|===


[source%nowrap, php]
----

public sendNewCustomerPassword($contactId):void

----

    





Sends a new password to the contact.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public unblockUser($contactId):void

----

    





Unblocks the user.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public getLoginURL($contactId):void

----

    





Gets the login URL.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===



[[account_contracts_contactaccountrepositorycontract]]
=== ContactAccountRepositoryContract

The ContactAccountRepositoryContract is the interface for the contact account repository. This interface allows to get, create, update and delete accounts. An account contains company-related data.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public findAccount($accountId, $contactId):Plenty\Modules\Account\Models\Account

----

    


===== *Return type:*        xref:Account.adoc#account_models_account[`Account`]


Returns an account by an ID only if it is associated with the given contact ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountId`
a|The ID of the account

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public createAccount($data, $contactId):Plenty\Modules\Account\Models\Account

----

    


===== *Return type:*        xref:Account.adoc#account_models_account[`Account`]


Creates an account and associates it immediately with the given ID of the contact.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The account data as associative array

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact to associate this to
|===


[source%nowrap, php]
----

public updateAccount($data, $accountId, $contactId):Plenty\Modules\Account\Models\Account

----

    


===== *Return type:*        xref:Account.adoc#account_models_account[`Account`]


Updates an account. If not already associated, it will associate the account with the given contact ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The account data as associative array

|link:http://php.net/int[int^]
a|`$accountId`
a|The ID of the account

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public deleteAccount($accountId, $contactId):bool

----

    





Deletes the given account of the given contact ID. Returns `true` if the deletion was successful. Returns `false` if the deletion was not successful.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountId`
a|The ID of the account

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===



[[account_contracts_contactaddressrepositorycontract]]
=== ContactAddressRepositoryContract

The ContactAddressRepositoryContract is the interface for the contact address repository. This interface allows to list, get, create, update, add and delete addresses of the contact.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public getPrimaryOrLastCreatedContactAddresses($contactId):array

----

    





Returns primary or last created contact addresses

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public findContactAddressByTypeId($contactId, $typeId, $last = true):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Returns an address of a given contact for the given type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$typeId`
a|The ID of the address type

|link:http://php.net/bool[bool^]
a|`$last`
a|Return the last created billing address
|===


[source%nowrap, php]
----

public createAddress($data, $contactId, $typeId):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Creates an address, associates it immediately with the given contact ID with the given type and returns the new address.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The address data as associative array

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$typeId`
a|The ID of the address type
|===


[source%nowrap, php]
----

public updateAddress($data, $addressId, $contactId, $typeId):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Updates the existing address of a given contact and type and returns it.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The address data as associative array

|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address to update

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$typeId`
a|The ID of the address type
|===


[source%nowrap, php]
----

public getAddress($addressId, $contactId, $typeId):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Returns the address of a given contact and type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$typeId`
a|The ID of the address type
|===


[source%nowrap, php]
----

public getAddresses($contactId, $typeId = null):array

----

    





Gets all addresses for the given contact of the given type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$typeId`
a|The address type (default: all / null)
|===


[source%nowrap, php]
----

public addAddress($addressId, $contactId, $typeId):Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Adds the address to the given contact as the given type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$typeId`
a|The ID of the address type
|===


[source%nowrap, php]
----

public setPrimaryAddress($addressId, $contactId, $addressTypeId):Plenty\Modules\Account\Address\Models\AddressContactRelation

----

    


===== *Return type:*        xref:Account.adoc#account_models_addresscontactrelation[`AddressContactRelation`]


Sets a contact address per address type as the primary address.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$addressTypeId`
a|The ID of the address type
|===


[source%nowrap, php]
----

public resetPrimaryAddress($addressId, $contactId, $addressTypeId):Plenty\Modules\Account\Address\Models\AddressContactRelation

----

    


===== *Return type:*        xref:Account.adoc#account_models_addresscontactrelation[`AddressContactRelation`]


Resets a contact primary address.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$addressTypeId`
a|The ID of the address type
|===


[source%nowrap, php]
----

public deleteAddress($addressId, $contactId, $typeId):bool

----

    





Deletes an existing address of a given contact and type. Returns `true` if deletion was successful. Returns `false` if deletion was not successful.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$typeId`
a|The ID of the address type
|===



[[account_contracts_contactclassrepositorycontract]]
=== ContactClassRepositoryContract

The ContactClassRepositoryContract is the interface for the contact class repository. This interface allows to list all contact classes or to get a contact class by the ID.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public findContactClassById($contactClassId):string

----

    





Gets a contact class. The ID of the contact class must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactClassId`
a|The ID of the contact class
|===


[source%nowrap, php]
----

public findContactClassDataById($contactClassId):array

----

    





Gets the data of a contact class. The ID of the contact class must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactClassId`
a|The ID of the contact class
|===


[source%nowrap, php]
----

public allContactClasses():array

----

    





Lists contact classes.


[[account_contracts_contactdocumentcontract]]
=== ContactDocumentContract

The ContactDocumentContract is the interface for contact documents.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public listDocuments($continuationToken, $contactId):Plenty\Modules\Cloud\Storage\Models\StorageObjectList

----

    


===== *Return type:*        xref:Cloud.adoc#cloud_models_storageobjectlist[`StorageObjectList`]


List documents of a contact

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$continuationToken`
a|The contnuation token

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public getDocument($key, $contactId):Plenty\Modules\Cloud\Storage\Models\StorageObject

----

    


===== *Return type:*        xref:Cloud.adoc#cloud_models_storageobject[`StorageObject`]


Get storage object from contact documents

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|The key for the file

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public getDocumentUrl($key, $contactId):string

----

    





Get temporary url for document

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|The key for the file

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public uploadDocument($key, $content, $contactId):Plenty\Modules\Cloud\Storage\Models\StorageObject

----

    


===== *Return type:*        xref:Cloud.adoc#cloud_models_storageobject[`StorageObject`]


Upload document to contact directory

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|The key for the file

|link:http://php.net/string[string^]
a|`$content`
a|The content of the file

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public deleteDocuments($keyList, $contactId):bool

----

    





Delete files from contact documents

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$keyList`
a|The array of the key list

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===



[[account_contracts_contactgroupfunctionsrepositorycontract]]
=== ContactGroupFunctionsRepositoryContract

The ContactGroupFunctionsRepositoryContract is the interface for the contact account group function repository. This interface allows to execute a group function call and get group function related data.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public loadGroupFunctions():array

----

    







[source%nowrap, php]
----

public executeGroupFunction($contactList = [], $addressLabelTemplate = null, $emailTemplate = null, $newsletter = null):array

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$contactList`
a|The list of the contacts

|link:http://php.net/int[int^]
a|`$addressLabelTemplate`
a|The address label template

|link:http://php.net/int[int^]
a|`$emailTemplate`
a|The email templates

|link:http://php.net/int[int^]
a|`$newsletter`
a|The newsletter
|===


[source%nowrap, php]
----

public executeGroupFunctionV2($data = []):array

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The data as associative array
|===



[[account_contracts_contactlookuprepositorycontract]]
=== ContactLookupRepositoryContract

lookup repository for contacts



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public hasId($contactId):Plenty\Modules\Account\Contact\Contracts\ContactLookupRepositoryContract

----

    


===== *Return type:*        xref:Account.adoc#account_contracts_contactlookuprepositorycontract[`ContactLookupRepositoryContract`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public hasEmail($emailAddress):Plenty\Modules\Account\Contact\Contracts\ContactLookupRepositoryContract

----

    


===== *Return type:*        xref:Account.adoc#account_contracts_contactlookuprepositorycontract[`ContactLookupRepositoryContract`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$emailAddress`
a|The email address of the contact
|===


[source%nowrap, php]
----

public hasBillingAddress($billingAddressId):Plenty\Modules\Account\Contact\Contracts\ContactLookupRepositoryContract

----

    


===== *Return type:*        xref:Account.adoc#account_contracts_contactlookuprepositorycontract[`ContactLookupRepositoryContract`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$billingAddressId`
a|The ID of the billing address
|===


[source%nowrap, php]
----

public hasDeliveryAddress($deliveryAddressId):Plenty\Modules\Account\Contact\Contracts\ContactLookupRepositoryContract

----

    


===== *Return type:*        xref:Account.adoc#account_contracts_contactlookuprepositorycontract[`ContactLookupRepositoryContract`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$deliveryAddressId`
a|The ID of the delivery address
|===


[source%nowrap, php]
----

public lookup():array

----

    








[[account_contracts_contactoptionrepositorycontract]]
=== ContactOptionRepositoryContract

The ContactOptionRepositoryContract is the interface for the contact option repository. This interface allows to get, create, update and delete contact options.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public findContactOptions($contactId, $typeId, $subTypeId):Illuminate\Database\Eloquent\Collection

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Lists options of the contact. The ID of the contact must be specified. The ID of the option type and the ID of the option sub-type can be optionally used.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$typeId`
a|Optional: The ID of the option type (default: 0)

|link:http://php.net/int[int^]
a|`$subTypeId`
a|Optional: The ID of the option sub-type (default: 0)
|===


[source%nowrap, php]
----

public createContactOptions($optionData, $contactId):array

----

    





Creates an option for the given contact and returns them.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$optionData`
a|The option data as associative array

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public updateContactOptions($optionData, $contactId):array

----

    





Updates options of the given contact and returns them. The ID of the contact must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$optionData`
a|The option data as associative array

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public deleteContactOptionsByContactId($contactId):bool

----

    





Deletes all options of the given contact. The ID of the contact must be specified. Returns `true` if deletion was successful. Returns `false` if deletion was not successful.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public findContactOption($optionId):Plenty\Modules\Account\Contact\Models\ContactOption

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactoption[`ContactOption`]


Gets a contact option. The ID of the option must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$optionId`
a|The ID of the option
|===


[source%nowrap, php]
----

public updateContactOption($optionData, $optionId):Plenty\Modules\Account\Contact\Models\ContactOption

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactoption[`ContactOption`]


Updates an option with the given id and returns it.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$optionData`
a|The option data as associative array

|link:http://php.net/int[int^]
a|`$optionId`
a|The ID of the option
|===


[source%nowrap, php]
----

public deleteContactOption($optionId):bool

----

    





Deletes a contact option. The ID of the option must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$optionId`
a|The ID of the option
|===


[source%nowrap, php]
----

public validateValue($contactId, $typeId, $subTypeId, $value):bool

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|

|link:http://php.net/int[int^]
a|`$typeId`
a|

|link:http://php.net/int[int^]
a|`$subTypeId`
a|

|link:http://php.net/string[string^]
a|`$value`
a|
|===



[[account_contracts_contactparamconfigurationcontract]]
=== ContactParamConfigurationContract

The ContactParamConfigurationContract is the interface for the contact param configuration repository. This interface allows to create, update, delete, list and get contact positions, contact departments, contact option types and and contact option sub-types.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public createContactPosition($data):Plenty\Modules\Account\Contact\Models\ContactPosition

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactposition[`ContactPosition`]


Creates a contact position.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public updateContactPosition($data, $contactPositionId):Plenty\Modules\Account\Contact\Models\ContactPosition

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactposition[`ContactPosition`]


Updates an existing contact position.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|

|link:http://php.net/int[int^]
a|`$contactPositionId`
a|The ID of the contact position
|===


[source%nowrap, php]
----

public deleteContactPosition($contactPositionId):bool

----

    





Deletes a contact position by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactPositionId`
a|The ID of the contact position
|===


[source%nowrap, php]
----

public findContactPositionById($contactPositionId):Plenty\Modules\Account\Contact\Models\ContactPosition

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactposition[`ContactPosition`]


Finds an existing contact position by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactPositionId`
a|The ID of the contact position
|===


[source%nowrap, php]
----

public allContactPositions($columns = [], $perPage = 50):void

----

    





Gets a list of contact positions.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|

|link:http://php.net/int[int^]
a|`$perPage`
a|
|===


[source%nowrap, php]
----

public createContactDepartment($data):Plenty\Modules\Account\Contact\Models\ContactDepartment

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactdepartment[`ContactDepartment`]


Creates a contact department.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public updateContactDepartment($data, $contactDepartmentId):Plenty\Modules\Account\Contact\Models\ContactDepartment

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactdepartment[`ContactDepartment`]


Updates an existing contact department.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|

|link:http://php.net/int[int^]
a|`$contactDepartmentId`
a|The ID of the contact department
|===


[source%nowrap, php]
----

public deleteContactDepartment($contactDepartmentId):bool

----

    





Deletes a contact department by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactDepartmentId`
a|The ID of the contact department
|===


[source%nowrap, php]
----

public findContactDepartmentById($contactDepartmentId):Plenty\Modules\Account\Contact\Models\ContactDepartment

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactdepartment[`ContactDepartment`]


Finds an existing contact department by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactDepartmentId`
a|The ID of the contact department
|===


[source%nowrap, php]
----

public allContactDepartments($columns = [], $perPage = 50):void

----

    





Gets a list of contact departments.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|

|link:http://php.net/int[int^]
a|`$perPage`
a|
|===


[source%nowrap, php]
----

public createContactOptionType($data):Plenty\Modules\Account\Contact\Models\ContactOptionType

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactoptiontype[`ContactOptionType`]


Creates a contact option type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public updateContactOptionType($data, $contactOptionTypeId):Plenty\Modules\Account\Contact\Models\ContactOptionType

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactoptiontype[`ContactOptionType`]


Updates an existing contact option type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|

|link:http://php.net/int[int^]
a|`$contactOptionTypeId`
a|The ID of the contact option type
|===


[source%nowrap, php]
----

public deleteContactOptionType($contactOptionTypeId):bool

----

    





Deletes a contact option type by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactOptionTypeId`
a|The ID of the contact option type
|===


[source%nowrap, php]
----

public findContactOptionTypeById($contactOptionTypeId):Plenty\Modules\Account\Contact\Models\ContactOptionType

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactoptiontype[`ContactOptionType`]


Finds an existing contact option type by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactOptionTypeId`
a|The ID of the contact option type
|===


[source%nowrap, php]
----

public allContactOptionType($columns = [], $perPage = 50, $with = []):void

----

    





Gets a list of contact option types.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|

|link:http://php.net/int[int^]
a|`$perPage`
a|

|link:http://php.net/array[array^]
a|`$with`
a|
|===


[source%nowrap, php]
----

public createContactOptionSubType($data):Plenty\Modules\Account\Contact\Models\ContactOptionSubType

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactoptionsubtype[`ContactOptionSubType`]


Creates a contact option sub-type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public updateContactOptionSubType($data, $contactOptionSubTypeId):Plenty\Modules\Account\Contact\Models\ContactOptionSubType

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactoptionsubtype[`ContactOptionSubType`]


Updates an existing contact option sub-type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|

|link:http://php.net/int[int^]
a|`$contactOptionSubTypeId`
a|The ID of the contact option sub-type
|===


[source%nowrap, php]
----

public deleteContactOptionSubType($contactOptionSubTypeId):bool

----

    





Deletes a contact option sub-type by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactOptionSubTypeId`
a|The ID of the contact option sub-type
|===


[source%nowrap, php]
----

public findContactOptionSubTypeById($contactOptionSubTypeId):Plenty\Modules\Account\Contact\Models\ContactOptionSubType

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactoptionsubtype[`ContactOptionSubType`]


Finds an existing contact option sub-type by the given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactOptionSubTypeId`
a|The ID contact option sub-type
|===


[source%nowrap, php]
----

public allContactOptionSubType($columns = [], $perPage = 50):void

----

    





Gets a list of contact option sub-types.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|

|link:http://php.net/int[int^]
a|`$perPage`
a|
|===



[[account_contracts_contactpaymentrepositorycontract]]
=== ContactPaymentRepositoryContract

The ContactPaymentRepositoryContract is the interface for the contact payment repository. This interface allows to list, get, create, update and delete bank details of the contact.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public getBanksOfContact($contactId, $columns = [], $perPage = 50):array

----

    





Gets a collection of bank accounts of a contact. The ID of the contact must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/array[array^]
a|`$columns`
a|Optional: The columns to retrieve (Default: '[*]')

|link:http://php.net/int[int^]
a|`$perPage`
a|Optional: The number of bank accounts per page (Default: 50)
|===


[source%nowrap, php]
----

public getBankByOrderId($orderId, $columns = []):Plenty\Modules\Account\Contact\Models\ContactBank

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactbank[`ContactBank`]


Returns bank details of an order. The ID of the order must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
a|The ID of the order

|link:http://php.net/array[array^]
a|`$columns`
a|Optional: The columns to retrieve (Default: '[*]')
|===


[source%nowrap, php]
----

public createContactBank($data):Plenty\Modules\Account\Contact\Models\ContactBank

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactbank[`ContactBank`]


Creates a bank account for a contact and returns it.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The bank account data as associative array
|===


[source%nowrap, php]
----

public updateContactBank($data, $contactBankId):Plenty\Modules\Account\Contact\Models\ContactBank

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactbank[`ContactBank`]


Updates a bank account. The ID of the bank account must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The bank data as associative array

|link:http://php.net/int[int^]
a|`$contactBankId`
a|The ID of the bank account entry
|===


[source%nowrap, php]
----

public deleteContactBank($contactBankId):bool

----

    





Deletes a bank account. The ID of the bank account must be specified. Returns `true` if deletion was successful. Returns `false` if deletion was not successful.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactBankId`
a|The ID of the bank account entry
|===


[source%nowrap, php]
----

public findContactBankById($contactBankId):Plenty\Modules\Account\Contact\Models\ContactBank

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactbank[`ContactBank`]


Gets a bank account. The ID of the bank account must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactBankId`
a|The ID of the bank account entry
|===



[[account_contracts_contactrepositorycontract]]
=== ContactRepositoryContract

The ContactRepositoryContract is the interface for the contact repository. This interface allows to list, get, create, update and delete contacts. A contact is equivalent to a person.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public createContact($data):Plenty\Modules\Account\Contact\Models\Contact

----

    


===== *Return type:*        xref:Account.adoc#account_models_contact[`Contact`]


Creates a contact and returns it.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The contact data as associative array
|===


[source%nowrap, php]
----

public updateContact($data, $contactId):Plenty\Modules\Account\Contact\Models\Contact

----

    


===== *Return type:*        xref:Account.adoc#account_models_contact[`Contact`]


Updates a contact and returns it. The ID of the contact must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The contact data as associative array

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public deleteContact($contactId, $checkExistingOrders = null):bool

----

    





Deletes a contact. The ID of the contact must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact. Returns `true` if deletion was successful. Returns `false` if deletion was not successful.

|link:http://php.net/bool[bool^]
a|`$checkExistingOrders`
a|Flag that checks if the contact is linked to orders. If the contact is linked to orders, CustomerDeleteException is thrown and the contact will not be deleted.
|===


[source%nowrap, php]
----

public findContactById($contactId, $with = []):Plenty\Modules\Account\Contact\Models\Contact

----

    


===== *Return type:*        xref:Account.adoc#account_models_contact[`Contact`]


Gets a contact. The ID of the contact must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/array[array^]
a|`$with`
a|The relationships that should be eager loaded
|===


[source%nowrap, php]
----

public getContactList($filter = [], $with = [], $columns = [], $page = 1, $itemsPerPage = 50, $sortBy = &quot;id&quot;, $sortOrder = &quot;desc&quot;):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List contacts

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filter`
a|Filter that restrict the search result

|link:http://php.net/array[array^]
a|`$with`
a|The relationships that should be eager loaded

|link:http://php.net/array[array^]
a|`$columns`
a|The columns to retrieve

|link:http://php.net/int[int^]
a|`$page`
a|The page of results to search for

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items to list per page

|link:http://php.net/string[string^]
a|`$sortBy`
a|[optional, default=id]

|link:http://php.net/string[string^]
a|`$sortOrder`
a|[optional, default=desc]
|===


[source%nowrap, php]
----

public getContactByOptionValue($value, $typeId, $subTypeId):Plenty\Modules\Account\Contact\Models\Contact

----

    


===== *Return type:*        xref:Account.adoc#account_models_contact[`Contact`]


Returns an existing contact by a contact option information.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$value`
a|The value of the contact option

|link:http://php.net/int[int^]
a|`$typeId`
a|The type ID of the contact option

|link:http://php.net/int[int^]
a|`$subTypeId`
a|The sub-type ID of the contact option
|===


[source%nowrap, php]
----

public getContactIdByEmail($email):int

----

    





Returns a contact id by email. The email must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$email`
a|
|===


[source%nowrap, php]
----

public findContactDataByContactId($contactId):Plenty\Modules\Account\Contact\Models\Contact

----

    


===== *Return type:*        xref:Account.adoc#account_models_contact[`Contact`]


Returns all contact related data.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[source%nowrap, php]
----

public getDataHistory($referenceType, $referenceId):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$referenceType`
a|

|link:http://php.net/int[int^]
a|`$referenceId`
a|
|===



[[account_contracts_contacttyperepositorycontract]]
=== ContactTypeRepositoryContract

The ContactTypeRepositoryContract is the interface for the contact type repository. This interface allows to list, get, create, update and delete contact types.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public createContactType($data):Plenty\Modules\Account\Contact\Models\ContactType

----

    


===== *Return type:*        xref:Account.adoc#account_models_contacttype[`ContactType`]


Creates a contact type and returns it.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The contact type data as associative array
|===


[source%nowrap, php]
----

public updateContactType($data, $contactTypeId):Plenty\Modules\Account\Contact\Models\ContactType

----

    


===== *Return type:*        xref:Account.adoc#account_models_contacttype[`ContactType`]


Updates a contact type and returns it. The ID of the contact type must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The contact type data as associative array

|link:http://php.net/int[int^]
a|`$contactTypeId`
a|The ID of the contact type
|===


[source%nowrap, php]
----

public deleteContactType($contactTypeId):bool

----

    





Deletes a contact type. The ID of the contact type must be specified. Returns `true` if deletion was successful. Returns `false` if deletion was not successful.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactTypeId`
a|The ID of the contact type
|===


[source%nowrap, php]
----

public findContactTypeById($contactTypeId):Plenty\Modules\Account\Contact\Models\ContactType

----

    


===== *Return type:*        xref:Account.adoc#account_models_contacttype[`ContactType`]


Gets a contact type. The ID of the contact type must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactTypeId`
a|The ID of the contact type
|===


[source%nowrap, php]
----

public allContactTypes($columns = []):array

----

    





Returns a collection of contact types.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|Optional: The columns to return as an array (Default: '[*]')
|===



[[account_contracts_contactvcardrepositorycontract]]
=== ContactVCardRepositoryContract

The ContractVCardRepositoryContract is the interface for the vcard repository. The interface allows you to return a vcard filestream.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public getVCard($contactId):array

----

    





Gets a filestream of the vcard of a contact.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===



[[account_contracts_internalcontactpaymentrepositorycontract]]
=== InternalContactPaymentRepositoryContract

The contract for the contact payment repository.



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public getBanksOfContact($contactId, $columns = [], $perPage = 50):array

----

    





Gets a collection of bank accounts of a contact. The ID of the contact must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/array[array^]
a|`$columns`
a|Optional: The columns to retrieve (Default: '[*]')

|link:http://php.net/int[int^]
a|`$perPage`
a|Optional: The number of bank accounts per page (Default: 50)
|===


[source%nowrap, php]
----

public getBankByOrderId($orderId, $columns = []):Plenty\Modules\Account\Contact\Models\ContactBank

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactbank[`ContactBank`]


Returns bank details of an order. The ID of the order must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
a|The ID of the order

|link:http://php.net/array[array^]
a|`$columns`
a|Optional: The columns to retrieve (Default: '[*]')
|===


[source%nowrap, php]
----

public createContactBank($data):Plenty\Modules\Account\Contact\Models\ContactBank

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactbank[`ContactBank`]


Creates a bank account for a contact and returns it.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The bank account data as associative array
|===


[source%nowrap, php]
----

public updateContactBank($data, $contactBankId):Plenty\Modules\Account\Contact\Models\ContactBank

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactbank[`ContactBank`]


Updates a bank account. The ID of the bank account must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The bank data as associative array

|link:http://php.net/int[int^]
a|`$contactBankId`
a|The ID of the bank account entry
|===


[source%nowrap, php]
----

public deleteContactBank($contactBankId):bool

----

    





Deletes a bank account. The ID of the bank account must be specified. Returns `true` if deletion was successful. Returns `false` if deletion was not successful.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactBankId`
a|The ID of the bank account entry
|===


[source%nowrap, php]
----

public findContactBankById($contactBankId):Plenty\Modules\Account\Contact\Models\ContactBank

----

    


===== *Return type:*        xref:Account.adoc#account_models_contactbank[`ContactBank`]


Gets a bank account. The ID of the bank account must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactBankId`
a|The ID of the bank account entry
|===



[[account_contracts_salesrepresentativeregionrepositorycontract]]
=== SalesRepresentativeRegionRepositoryContract

Sales representatives region repository



==== Namespace

`Plenty\Modules\Account\Contact\Contracts`






==== Methods

[source%nowrap, php]
----

public createRegion($data, $contactId = null, $accountId = null):Plenty\Modules\Account\Models\SalesRepresentativeRegion

----

    


===== *Return type:*        xref:Account.adoc#account_models_salesrepresentativeregion[`SalesRepresentativeRegion`]


Create a region for the sales representative

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The data as associative array

|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$accountId`
a|The ID of the account
|===


[source%nowrap, php]
----

public find($page = 1, $itemsPerPage = 50, $columns = [], $with = []):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|

|link:http://php.net/array[array^]
a|`$columns`
a|

|link:http://php.net/array[array^]
a|`$with`
a|
|===


[source%nowrap, php]
----

public getRegionById($accountContactRelationId):Plenty\Modules\Account\Models\SalesRepresentativeRegion

----

    


===== *Return type:*        xref:Account.adoc#account_models_salesrepresentativeregion[`SalesRepresentativeRegion`]


Get a region by the ID

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountContactRelationId`
a|The ID of the account contact relation
|===


[source%nowrap, php]
----

public deleteRegionById($accountContactRelationId):bool

----

    





Delete a region by the ID

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountContactRelationId`
a|The ID of the account contact relation
|===


[source%nowrap, php]
----

public updateRegionById($accountContactRelationId, $data):Plenty\Modules\Account\Models\SalesRepresentativeRegion

----

    


===== *Return type:*        xref:Account.adoc#account_models_salesrepresentativeregion[`SalesRepresentativeRegion`]


Update an existing region by the ID

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountContactRelationId`
a|The ID of the account contact relation

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public getRegionByContactAndAccountId($contactId, $accountId):Plenty\Modules\Account\Models\SalesRepresentativeRegion

----

    


===== *Return type:*        xref:Account.adoc#account_models_salesrepresentativeregion[`SalesRepresentativeRegion`]


Get a region by contact ID and account ID

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact

|link:http://php.net/int[int^]
a|`$accountId`
a|The ID of the account
|===


[source%nowrap, php]
----

public getRegionsByContactId($contactId):Illuminate\Support\Collection

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Get a region by the contact ID

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[[account_contact_models]]
== Models
[[account_models_contact]]
=== Contact

The contact model.



==== Namespace

`Plenty\Modules\Account\Contact\Models`

==== Referenceable
id




.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact
|link:http://php.net/string[string^]
    a|externalId
    a|The external ID of the contact
|link:http://php.net/string[string^]
    a|number
    a|The number of the contact (previous customer number)
|link:http://php.net/int[int^]
    a|typeId
    a|The ID of the contact type
|link:http://php.net/string[string^]
    a|firstName
    a|The first name of the contact
|link:http://php.net/string[string^]
    a|lastName
    a|The last name of the contact
|link:http://php.net/string[string^]
    a|fullName
    a|The full name of the contact. A concatenation of first and last name.
|link:http://php.net/string[string^]
    a|email
    a|The private email address of the contact
|link:http://php.net/string[string^]
    a|secondaryEmail
    a|The secondary private email address of the contact
|link:http://php.net/string[string^]
    a|gender
    a|The gender of the contact ("female", "male" or "diverse")
|link:http://php.net/string[string^]
    a|title
    a|The title of the contact, e.g. a doctorate
|link:http://php.net/string[string^]
    a|formOfAddress
    a|The form of address for the contact
|
    a|newsletterAllowanceAt
    a|The time the contact registered for the newsletter as unix timestamp
|link:http://php.net/int[int^]
    a|classId
    a|The ID of the contact class
|link:http://php.net/int[int^]
    a|blocked
    a|The blocked status of the contact. Contacts can be blocked for a specific client (store). Possible values:
<ul>
<li> 0 = not blocked</li>
<li> 1 = blocked</li>
</ul>
|link:http://php.net/int[int^]
    a|rating
    a|The rating of the contact. This rating is for internal use only. 5 red stars are for the worst and 5 yellow stars for the best rating. Possible values:
<ul>
<li>-5 = 5 red stars (worst rating)</li>
<li>-4 = 4 red stars</li>
<li>-3 = 3 red stars</li>
<li>-2 = 2 red stars</li>
<li>-1 = 1 red star</li>
<li>0 = 5 grey stars, no rating saved for the contact</li>
<li>1 = 1 yellow star</li>
<li>2 = 2 yellow stars</li>
<li>3 = 3 yellow stars</li>
<li>4 = 4 yellow stars</li>
<li>5 = 5 yellow stars (best rating)</li>
</ul>
|link:http://php.net/string[string^]
    a|bookAccount
    a|The book account (debtor account) of the contact. An additional, separate number that generally corresponds to the customer number or the debtor number in your financial accounting.
|link:http://php.net/string[string^]
    a|lang
    a|The language of the contact
|link:http://php.net/float[float^]
    a|referrerId
    a|The origin of the contact
|link:http://php.net/int[int^]
    a|plentyId
    a|The client (store) that is assigned to the contact
|link:http://php.net/int[int^]
    a|userId
    a|The owner ID of the contact
|
    a|birthdayAt
    a|The date of birth of the contact
|
    a|lastLoginAt
    a|The date of the last login of the contact
|
    a|lastLoginAtTimestamp
    a|The date of the last login of the contact
|
    a|lastOrderAt
    a|The date of the last order
|
    a|createdAt
    a|The date the contact was created
|
    a|updatedAt
    a|The date the contact was last updated
|link:http://php.net/string[string^]
    a|privatePhone
    a|The private phone number of the contact
|link:http://php.net/string[string^]
    a|privateFax
    a|The private fax number of the contact
|link:http://php.net/string[string^]
    a|privateMobile
    a|The private mobile phone number of the contact
|link:http://php.net/string[string^]
    a|ebayName
    a|The eBay account name of the contact
|link:http://php.net/string[string^]
    a|paypalEmail
    a|The email address of the PayPal account of the contact
|link:http://php.net/string[string^]
    a|paypalPayerId
    a|The PayPal payer id of the contact
|link:http://php.net/string[string^]
    a|klarnaPersonalId
    a|The Klarna personal id of the contact
|link:http://php.net/string[string^]
    a|dhlPostIdent
    a|The DHL PostIdent of the contact
|link:http://php.net/string[string^]
    a|forumUsername
    a|The user name of the contact in the forum
|link:http://php.net/string[string^]
    a|forumGroupId
    a|The ID of the forum group that is assigned to the contact
|link:http://php.net/string[string^]
    a|singleAccess
    a|The access type of the contact
|link:http://php.net/string[string^]
    a|contactPerson
    a|The contact person of the contact
|link:http://php.net/string[string^]
    a|marketplacePartner
    a|The marketplace partner status of the contact
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|addresses
    a|A collection of linked addresses
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|primaryBillingAddress
    a|A collection of linked primary billing addresses
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|accounts
    a|A collection of linked accounts. An ID or a company name must be specified. When the ID is used, a relation will be created. When the company name without an ID is used, a new account with the given data will be created.
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|orders
    a|A collection of orders of the contact. Deprecated.
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|contactOrders
    a|A collection of orders of the contact
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|banks
    a|A collection of bank accounts of the contact
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|reorders
    a|A collection of reorders of the contact
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|orderSchedulers
    a|A collection of order schedulers of the contact
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|options
    a|A collection of options of the contact
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|salesRepresentativeRegions
    a|A collection of sales representative regions of the contact
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|allowedMethodsOfPayment
    a|A collection of allowed payment methods for the contact.*
|        xref:Account.adoc#account_models_contacttype[`ContactType`]
    a|type
    a|The type of the contact
|        xref:Account.adoc#account_models_ordersummary[`OrderSummary`]
    a|orderSummary
    a|The order summary of the contact
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|tagRelationships
    a|The tag relations of the contact
|link:http://php.net/int[int^]
    a|valuta
    a|The foreign currency of the contact
|link:http://php.net/int[int^]
    a|discountDays
    a|The early payment discount period in days specified for the account
|link:http://php.net/float[float^]
    a|discountPercent
    a|The early payment discount in percent specified for the account
|link:http://php.net/int[int^]
    a|timeForPaymentAllowedDays
    a|The payment due date in days specified for the account
|link:http://php.net/int[int^]
    a|salesRepresentativeContactId
    a|The salesRepresentative ID of the contact
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactallowedmethodofpayment]]
=== ContactAllowedMethodOfPayment

The model of the allowed payment method for the contact



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the payment method allowed for the contact
|link:http://php.net/int[int^]
    a|contactId
    a|The ID of the contact
|link:http://php.net/int[int^]
    a|methodOfPaymentId
    a|The ID of the payment method
|link:http://php.net/int[int^]
    a|allowed
    a|Allowed payment method for the contact. Possible values are:
<ul>
<li>0 = not allowed</li>
<li>1 = allowed</li>
</ul>
|link:http://php.net/string[string^]
    a|createdAt
    a|Timestamp when the payment method was created
|link:http://php.net/string[string^]
    a|updatedAt
    a|Timestamp when the payment method was last updated
|link:http://php.net/bool[bool^]
    a|isPaymentActive
    a|Flag that indicates if the current payment method is active
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactbank]]
=== ContactBank

The contact bank model.



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the bank account
|link:http://php.net/int[int^]
    a|contactId
    a|The ID of the contact the bank account belongs to
|link:http://php.net/int[int^]
    a|orderId
    a|The ID of the order the bank account belongs to
|link:http://php.net/string[string^]
    a|accountOwner
    a|The owner of the bank account
|link:http://php.net/string[string^]
    a|bankName
    a|The name of the bank
|link:http://php.net/string[string^]
    a|bankAddress
    a|The address of the bank
|link:http://php.net/string[string^]
    a|bankPostalCodeTown
    a|The postcode and town of the bank
|link:http://php.net/string[string^]
    a|bankCountry
    a|The country of the bank
|link:http://php.net/string[string^]
    a|iban
    a|The IBAN of the bank account
|link:http://php.net/string[string^]
    a|bic
    a|The BIC of the bank account
|link:http://php.net/string[string^]
    a|accountNumber
    a|The account number of the bank account
|link:http://php.net/string[string^]
    a|sortCode
    a|The sort code of the bank account
|link:http://php.net/string[string^]
    a|lastUpdateBy
    a|The source of the last change (possible values: `customer`, `backend`, `import`)
|link:http://php.net/int[int^]
    a|directDebitMandateAvailable
    a|Flag that indicates if a direct debit mandate is available
|link:http://php.net/string[string^]
    a|directDebitMandateAt
    a|The time the direct debit mandate was created as unix timestamp
|link:http://php.net/string[string^]
    a|directDebitMethod
    a|The direct debit method (possible values: `sepaDirectDebit`, `sepaB2bDirectDebit`)
|link:http://php.net/string[string^]
    a|directDebitType
    a|The direct debit type (possible values: `first`, `next`)
|link:http://php.net/string[string^]
    a|paymentMethod
    a|The payment method (possible values: `recurrent`, `onOff`)
|link:http://php.net/string[string^]
    a|createdAt
    a|The time the bank account was created as  unix timestamp
|link:http://php.net/string[string^]
    a|updatedAt
    a|The time the bank account was last updated as  unix timestamp
|        xref:Account.adoc#account_models_contact[`Contact`]
    a|contact
    a|The contact the bank account belongs to
|        xref:Order.adoc#order_legacy_order[`Order`]
    a|order
    a|The order the bank account belongs to
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactdepartment]]
=== ContactDepartment

contact department model



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact department. It is possible to define individual departments. The following departments are available by default.
<ul>
<li>1 = Management</li>
<li>2 = Purchasing Department</li>
<li>3 = Sales Department</li>
<li>4 = Research & Development Team</li>
<li>5 = Production</li>
<li>6 = Quality Assurance</li>
<li>7 = Public Relations</li>
<li>8 = Marketing Department</li>
<li>9 = IT Department</li>
<li>10 = EDP Team</li>
<li>11 = Logistics</li>
<li>12 = Warehousing Department</li>
<li>13 = Export Department</li>
<li>14 = Import Department</li>
<li>15 = Customer Service</li>
<li>16 = Technical Support Team</li>
<li>17 = Human Resources</li>
<li>18 = Accounting Department</li>
<li>19 = Financial Department</li>
<li>20 = Legal Department</li>
<li>21 = Secretary's Office</li>
</ul>
|link:http://php.net/int[int^]
    a|position
    a|The position for sorting
|link:http://php.net/array[array^]
    a|names
    a|List of contact department names
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactdepartmentname]]
=== ContactDepartmentName

contact department name model



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact department name
|link:http://php.net/int[int^]
    a|departmentId
    a|The ID of the department
|link:http://php.net/string[string^]
    a|lang
    a|The language
|link:http://php.net/string[string^]
    a|name
    a|The name
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactoption]]
=== ContactOption

The contact options model.



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact option
|link:http://php.net/int[int^]
    a|contactId
    a|The ID of the contact the option belongs to
|link:http://php.net/int[int^]
    a|typeId
    a|The type ID of the contact option. It is possible to define individual contact option types. The following types are available by default and cannot be deleted:
<ul>
<li>1 = Telephone</li>
<li>2 = Email</li>
<li>3 = Telefax</li>
<li>4 = Web page</li>
<li>5 = Marketplace</li>
<li>6 = Identification number</li>
<li>7 = Payment</li>
<li>8 = User name</li>
<li>9 = Group</li>
<li>10 = Access</li>
<li>11 = Additional</li>
</ul>
|link:http://php.net/int[int^]
    a|subTypeId
    a|The sub-type ID of the contact option. It is possible to define individual contact option sub-types. The following types are available by default and cannot be deleted:
<ul>
<li>1 = Work</li>
<li>2 = Mobile private</li>
<li>3 = Mobile work</li>
<li>4 = Private</li>
<li>5 = PayPal</li>
<li>6 = Ebay</li>
<li>7 = Amazon</li>
<li>8 = Klarna</li>
<li>9 = DHL</li>
<li>10 = Forum</li>
<li>11 = Guest</li>
<li>12 = Contact person</li>
<li>13 = Marketplace partner</li>
</ul>
|link:http://php.net/string[string^]
    a|value
    a|The value of the option. Depends on the type/sub-type.
|link:http://php.net/int[int^]
    a|priority
    a|The priority for sorting
|link:http://php.net/string[string^]
    a|createdAt
    a|The time the option was created as unix timestamp
|link:http://php.net/string[string^]
    a|updatedAt
    a|The time the option was last updated as unix timestamp
|        xref:Account.adoc#account_models_contact[`Contact`]
    a|contact
    a|The contact the option belongs to
|        xref:Account.adoc#account_models_contactoptiontype[`ContactOptionType`]
    a|type
    a|The type of the option
|        xref:Account.adoc#account_models_contactoptionsubtype[`ContactOptionSubType`]
    a|subType
    a|The sub-type of the option
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactoptionsubtype]]
=== ContactOptionSubType

contact options sub type model



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact option sub-type. It is possible to define individual option sub-types. The following types are available by default and cannot be deleted.
<ul>
<li>1 = Work</li>
<li>2 = Mobile private</li>
<li>3 = Mobile work</li>
<li>4 = Private</li>
<li>5 = PayPal</li>
<li>6 = Ebay</li>
<li>7 = Amazon</li>
<li>8 = Klarna</li>
<li>9 = DHL</li>
<li>10 = Forum</li>
<li>11 = Guest</li>
<li>12 = Contact person</li>
<li>13 = Marketplace partner</li>
</ul>
|link:http://php.net/int[int^]
    a|position
    a|The position for sorting
|link:http://php.net/int[int^]
    a|nonErasable
    a|Flag that indicates if the option sub-type can be deleted
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|names
    a|A collection of names in different languages for the option sub-type.
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactoptionsubtypename]]
=== ContactOptionSubTypeName

contact options sub type name model



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact option sub type name entry
|link:http://php.net/int[int^]
    a|subTypeId
    a|The ID of the option sub-type the name entry belongs to
|link:http://php.net/string[string^]
    a|lang
    a|lang      The language of the sub-type name
|link:http://php.net/string[string^]
    a|name
    a|name      The name of the sub-type
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactoptiontype]]
=== ContactOptionType

contact options type model



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact option type. It is possible to define individual option types. The following types are available by default and cannot be deleted.
<ul>
<li>1 = Telephone</li>
<li>2 = Email</li>
<li>3 = Telefax</li>
<li>4 = Web page</li>
<li>5 = Marketplace</li>
<li>6 = Identification number</li>
<li>7 = Payment</li>
<li>8 = User name</li>
<li>9 = Group</li>
<li>10 = Access</li>
<li>11 = Additional</li>
</ul>
|link:http://php.net/int[int^]
    a|position
    a|The position for sorting
|link:http://php.net/int[int^]
    a|nonErasable
    a|Flag that indicates if the option type can be deleted
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|names
    a|A collection of names in different languages for the option type
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactoptiontypename]]
=== ContactOptionTypeName

The ContactOptionTypeName model



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact option type name
|link:http://php.net/int[int^]
    a|typeId
    a|The ID of the option type the name belongs to
|link:http://php.net/string[string^]
    a|lang
    a|The language of the option type name
|link:http://php.net/string[string^]
    a|name
    a|The name of the option type
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactposition]]
=== ContactPosition

The ContactPosition model



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact position. It is possible to define individual contact positions. The following positions are available by default:
<ul>
<li>1 = Analyst</li>
<li>2 = Director of Boards</li>
<li>3 = CEO</li>
<li>4 = Buyer</li>
<li>5 = Purchasing Manager</li>
<li>6 = CFO</li>
<li>7 = Director General</li>
<li>8 = Managing Director</li>
<li>9 = Codirector</li>
<li>10 = Commercial Agent</li>
<li>11 = Assistant</li>
<li>12 = Service Engineer</li>
<li>13 = Warehouse Manager</li>
<li>14 = Warehouse Worker</li>
<li>15 = Senior Executive</li>
<li>16 = Assistent</li>
<li>17 = Purchasing Assistent</li>
<li>18 = Software Developer</li>
<li>19 = Sales Representative</li>
<li>20 = Sales Manager</li>
<li>21 = Export Sales Manager</li>
<li>22 = Wholesale Distributing Manager</li>
<li>23 = Secretary</li>
<li>24 = Economist</li>
<li>25 = Management Board</li>
</ul>
|link:http://php.net/int[int^]
    a|position
    a|The position for sorting
|link:http://php.net/array[array^]
    a|names
    a|The list of contact position names
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contactpositionname]]
=== ContactPositionName

The ContactPositionName model



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact position name
|link:http://php.net/int[int^]
    a|positionId
    a|The ID of the position
|link:http://php.net/string[string^]
    a|lang
    a|The language
|link:http://php.net/string[string^]
    a|name
    a|The name
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contacttype]]
=== ContactType

The ContactType model



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact type. It is possible to define individual contact types. The following types are available by default and cannot be deleted.
<ul>
<li>1 = Customer</li>
<li>2 = Sales lead/Interested party</li>
<li>3 = Sales representative</li>
<li>4 = Supplier</li>
<li>5 = Producer/Manufacturer</li>
<li>6 = Partner</li>
</ul>
|link:http://php.net/int[int^]
    a|position
    a|The position for sorting
|link:http://php.net/int[int^]
    a|nonErasable
    a|Flag that indicates if the type can be deleted
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|names
    a|A collection of contact type names in different languages
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|contacts
    a|A collection of contacts with the type
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_contacttypename]]
=== ContactTypeName

contact type name model



==== Namespace

`Plenty\Modules\Account\Contact\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the contact type name
|link:http://php.net/int[int^]
    a|typeId
    a|The contact type ID. See also {@link ContactType::id}.
|link:http://php.net/string[string^]
    a|lang
    a|The language ot the contact type name
|link:http://php.net/string[string^]
    a|name
    a|The contact type name
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[account_search]]
= Search

[[account_search_contracts]]
== Contracts
[[account_contracts_contactelasticsearchavailibilityrepositorycontract]]
=== ContactElasticSearchAvailibilityRepositoryContract

ContactElasticSearchAvailibilityRepositoryContract



==== Namespace

`Plenty\Modules\Account\Contact\Search\Contracts`






==== Methods

[source%nowrap, php]
----

public isReady():bool

----

    







[source%nowrap, php]
----

public isAvailable():bool

----

    








[[account_contracts_contactelasticsearchscrollrepositorycontract]]
=== ContactElasticSearchScrollRepositoryContract

kommt noch



==== Namespace

`Plenty\Modules\Account\Contact\Search\Contracts`






==== Methods

[source%nowrap, php]
----

public hasNext():bool

----

    







[source%nowrap, php]
----

public setNumberOfDocumentsPerShard($size):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$size`
a|
|===


[source%nowrap, php]
----

public setIndex($index):Plenty\Modules\Cloud\ElasticSearch\Contracts\ElasticSearchSearchRepositoryContract

----

    


===== *Return type:*        xref:Cloud.adoc#cloud_contracts_elasticsearchsearchrepositorycontract[`ElasticSearchSearchRepositoryContract`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_index_indexinterface[`IndexInterface`]
a|`$index`
a|
|===


[source%nowrap, php]
----

public addSearch($search):Plenty\Modules\Cloud\ElasticSearch\Contracts\ElasticSearchSearchRepositoryContract

----

    


===== *Return type:*        xref:Cloud.adoc#cloud_contracts_elasticsearchsearchrepositorycontract[`ElasticSearchSearchRepositoryContract`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$search`
a|
|===


[source%nowrap, php]
----

public execute():array

----

    








[[account_contracts_contactelasticsearchsearchrepositorycontract]]
=== ContactElasticSearchSearchRepositoryContract

Contract for search contacts



==== Namespace

`Plenty\Modules\Account\Contact\Search\Contracts`






==== Methods

[source%nowrap, php]
----

public search($page = 1, $itemsPerPage = 50, $filters = [], $sortBy = &quot;contactId&quot;, $sortOrder = &quot;desc&quot;, $with = &quot;&quot;):Plenty\Repositories\Models\FilteredPaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_filteredpaginatedresult[`FilteredPaginatedResult`]


Search contacts with the given filters.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|

|link:http://php.net/array[array^]
a|`$filters`
a|

|link:http://php.net/string[string^]
a|`$sortBy`
a|

|link:http://php.net/string[string^]
a|`$sortOrder`
a|

|link:http://php.net/string[string^]
a|`$with`
a|
|===



[[account_contracts_indexcontactrepositorycontract]]
=== IndexContactRepositoryContract

The contract for the search repository



==== Namespace

`Plenty\Modules\Account\Contact\Search\Contracts`






==== Methods

[source%nowrap, php]
----

public index($contactId):array

----

    





Index a contact

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|
|===


[source%nowrap, php]
----

public delete($contactIds):array

----

    





Delete contact from index

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$contactIds`
a|
|===


[source%nowrap, php]
----

public bulk($contactIds):array

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$contactIds`
a|
|===


[source%nowrap, php]
----

public setOutput($output):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_output_outputinterface[`OutputInterface`]
a|`$output`
a|
|===


[source%nowrap, php]
----

public execute():void

----

    







[[account_account]]
= Account

[[account_account_contracts]]
== Contracts
[[account_contracts_accountcontactrelationrepositorycontract]]
=== AccountContactRelationRepositoryContract

The AccountContactRelationRepositoryContract is the interface for the account contact relation repository. This interface allows to find and delete an account contact relation.



==== Namespace

`Plenty\Modules\Account\Contracts`






==== Methods

[source%nowrap, php]
----

public findAccountContactRelationById($accountContactRelation):Plenty\Modules\Account\Models\AccountContactRelation

----

    


===== *Return type:*        xref:Account.adoc#account_models_accountcontactrelation[`AccountContactRelation`]


Gets an account contact releation. The ID of the account contact relation must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountContactRelation`
a|The ID of the account contact relation
|===


[source%nowrap, php]
----

public deleteAccountContactRelation($accountContactRelationId):bool

----

    





Deletes an account contact relation. The ID of the account contact relation must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountContactRelationId`
a|The ID of the account contact relation
|===



[[account_contracts_accountrepositorycontract]]
=== AccountRepositoryContract

The AccountRepositoryContract is the interface for the account repository. This interface allows to list, get, create, update and delete accounts. An account contains company-related data. It is also possible to list all contacts of an account.



==== Namespace

`Plenty\Modules\Account\Contracts`






==== Methods

[source%nowrap, php]
----

public createAccount($data):Plenty\Modules\Account\Models\Account

----

    


===== *Return type:*        xref:Account.adoc#account_models_account[`Account`]


Creates a new account and returns it.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The account data as associative array
|===


[source%nowrap, php]
----

public updateAccount($data, $accountId):Plenty\Modules\Account\Models\Account

----

    


===== *Return type:*        xref:Account.adoc#account_models_account[`Account`]


Updates an existing account and returns it. The ID of the account must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The account data as associative array

|link:http://php.net/int[int^]
a|`$accountId`
a|The ID of the account
|===


[source%nowrap, php]
----

public deleteAccount($accountId):bool

----

    





Deletes an account. The ID of the account must be specified. Returns `true` if deletion was successful. Returns `false` if deletion was not successful.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountId`
a|The ID of the account
|===


[source%nowrap, php]
----

public findAccountById($accountId):Plenty\Modules\Account\Models\Account

----

    


===== *Return type:*        xref:Account.adoc#account_models_account[`Account`]


Gets an account. The ID of the account must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountId`
a|The ID of the account
|===


[source%nowrap, php]
----

public allAccounts($columns = [], $perPage = 50):Illuminate\Database\Eloquent\Collection

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Returns a collection of all accounts.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|Optional: The columns to retrieve (Default: '[*]').

|link:http://php.net/int[int^]
a|`$perPage`
a|Optional: The number of objects per page (Default: 50).
|===


[source%nowrap, php]
----

public allAccountsPaginated($columns = [], $page = 1, $itemsPerPage = 50, $with = []):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Returns a collection of all accounts.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|Optional: The columns to retrieve (Default: '[*]').

|link:http://php.net/int[int^]
a|`$page`
a|Optional: The number of the page (Default: 1).

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|Optional: The number of objects per page (Default: 50).

|link:http://php.net/array[array^]
a|`$with`
a|Optional: The relationships that should be eager loaded.
|===


[source%nowrap, php]
----

public getContactsOfAccount($accountId):Illuminate\Database\Eloquent\Collection

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Returns a collection of contacts that belong to the account.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountId`
a|The ID of the account
|===


[source%nowrap, php]
----

public saveAccount($data = []):void

----

    





Creates a new or updates an existing account.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The account data as associative array
|===


[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[[account_account_events]]
== Events
[[account_events_frontendupdatecustomersettings]]
=== FrontendUpdateCustomerSettings

frontend customer settings event



==== Namespace

`Plenty\Modules\Account\Events`






==== Methods

[source%nowrap, php]
----

public getDeliveryCountryId():int

----

    







[source%nowrap, php]
----

public setDeliveryCountryId($deliveryCountryId):Plenty\Modules\Account\Events\FrontendUpdateCustomerSettings

----

    


===== *Return type:*        xref:Account.adoc#account_events_frontendupdatecustomersettings[`FrontendUpdateCustomerSettings`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$deliveryCountryId`
a|
|===


[source%nowrap, php]
----

public getShowNetPrice():bool

----

    







[source%nowrap, php]
----

public setShowNetPrice($showNetPrice):Plenty\Modules\Account\Events\FrontendUpdateCustomerSettings

----

    


===== *Return type:*        xref:Account.adoc#account_events_frontendupdatecustomersettings[`FrontendUpdateCustomerSettings`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$showNetPrice`
a|
|===


[source%nowrap, php]
----

public getEbaySellerAccount():string

----

    







[source%nowrap, php]
----

public setEbaySellerAccount($ebaySellerAccount):Plenty\Modules\Account\Events\FrontendUpdateCustomerSettings

----

    


===== *Return type:*        xref:Account.adoc#account_events_frontendupdatecustomersettings[`FrontendUpdateCustomerSettings`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$ebaySellerAccount`
a|
|===


[source%nowrap, php]
----

public getAccountContactSign():string

----

    







[source%nowrap, php]
----

public setAccountContactSign($accountContactSign):Plenty\Modules\Account\Events\FrontendUpdateCustomerSettings

----

    


===== *Return type:*        xref:Account.adoc#account_events_frontendupdatecustomersettings[`FrontendUpdateCustomerSettings`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$accountContactSign`
a|
|===


[source%nowrap, php]
----

public getAccountContactClassId():int

----

    







[source%nowrap, php]
----

public setAccountContactClassId($accountContactClassId):Plenty\Modules\Account\Events\FrontendUpdateCustomerSettings

----

    


===== *Return type:*        xref:Account.adoc#account_events_frontendupdatecustomersettings[`FrontendUpdateCustomerSettings`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountContactClassId`
a|
|===


[source%nowrap, php]
----

public getSalesAgent():string

----

    







[source%nowrap, php]
----

public setSalesAgent($salesAgent):Plenty\Modules\Account\Events\FrontendUpdateCustomerSettings

----

    


===== *Return type:*        xref:Account.adoc#account_events_frontendupdatecustomersettings[`FrontendUpdateCustomerSettings`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$salesAgent`
a|
|===


[source%nowrap, php]
----

public getAccountContractClassId():int

----

    







[source%nowrap, php]
----

public setAccountContractClassId($accountContractClassId):Plenty\Modules\Account\Events\FrontendUpdateCustomerSettings

----

    


===== *Return type:*        xref:Account.adoc#account_events_frontendupdatecustomersettings[`FrontendUpdateCustomerSettings`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$accountContractClassId`
a|
|===



[[account_events_newsletterrecipientcreatedevent]]
=== NewsletterRecipientCreatedEvent

This event will be triggered, after a recipient was created.



==== Namespace

`Plenty\Modules\Account\Events`






==== Methods

[source%nowrap, php]
----

public getRecipient():Plenty\Modules\Account\Newsletter\Models\Recipient

----

    


===== *Return type:*        xref:Account.adoc#account_models_recipient[`Recipient`]


returns recipient.


[[account_events_newsletterrecipientdeletedevent]]
=== NewsletterRecipientDeletedEvent

This event will be triggered, after a recipient was deleted.



==== Namespace

`Plenty\Modules\Account\Events`






==== Methods

[source%nowrap, php]
----

public getRecipient():Plenty\Modules\Account\Newsletter\Models\Recipient

----

    


===== *Return type:*        xref:Account.adoc#account_models_recipient[`Recipient`]


returns recipient.


[[account_events_newsletterrecipientmovedtonewfolderevent]]
=== NewsletterRecipientMovedToNewFolderEvent

This event will be triggered, after a recipient was moved to a new folder.



==== Namespace

`Plenty\Modules\Account\Events`






==== Methods

[source%nowrap, php]
----

public getOldFolder():int

----

    





returns old folder id.

[source%nowrap, php]
----

public getRecipient():Plenty\Modules\Account\Newsletter\Models\Recipient

----

    


===== *Return type:*        xref:Account.adoc#account_models_recipient[`Recipient`]


returns recipient.

[[account_account_models]]
== Models
[[account_models_account]]
=== Account

the account model.



==== Namespace

`Plenty\Modules\Account\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the account
|link:http://php.net/string[string^]
    a|number
    a|The number of the account
|link:http://php.net/string[string^]
    a|companyName
    a|The company name
|link:http://php.net/string[string^]
    a|taxIdNumber
    a|The ID of the tax number
|link:http://php.net/int[int^]
    a|valuta
    a|The valuta date in days specified for the account
|link:http://php.net/int[int^]
    a|discountDays
    a|The early payment discount period in days specified for the account
|link:http://php.net/float[float^]
    a|discountPercent
    a|The early payment discount in percent specified for the account
|link:http://php.net/int[int^]
    a|timeForPaymentAllowedDays
    a|The payment due date in days specified for the account
|link:http://php.net/int[int^]
    a|salesRepresentativeContactId
    a|The contact ID of the sales representative
|link:http://php.net/int[int^]
    a|userId
    a|The ID of the account owner
|link:http://php.net/int[int^]
    a|deliveryTime
    a|The delivery time for the supplier
|link:http://php.net/float[float^]
    a|dealerMinOrderValue
    a|The minimum order value for the supplier
|link:http://php.net/string[string^]
    a|supplierCurrency
    a|The currency used by a supplier
|
    a|createdAt
    a|The time the account was created as unix timestamp
|
    a|updatedAt
    a|The time the account was last updated as unix timestamp
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|contacts
    a|A list of contacts that belong to the account
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|contactRelations
    a|A list with contact relations to the account
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|salesRepresentativeRegions
    a|A list with sales representative regions related to the account
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_accountcontactrelation]]
=== AccountContactRelation

account contact relation model



==== Namespace

`Plenty\Modules\Account\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the account contact relation
|link:http://php.net/int[int^]
    a|accountId
    a|The ID of the foreign key account
|link:http://php.net/int[int^]
    a|contactId
    a|The ID of the foreign key contact
|        xref:Account.adoc#account_models_account[`Account`]
    a|account
    a|The account of the relation
|        xref:Account.adoc#account_models_contact[`Contact`]
    a|contact
    a|The contact of the relation
|        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|accountContactSalesRepresentativeRelations
    a|
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_salesrepresentativeregion]]
=== SalesRepresentativeRegion

Sales representative region model



==== Namespace

`Plenty\Modules\Account\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the account contact sales representative relation
|link:http://php.net/int[int^]
    a|accountContactRelationId
    a|The ID of the foreign key account contact relation
|link:http://php.net/string[string^]
    a|postalCodeArea
    a|
|link:http://php.net/int[int^]
    a|countryId
    a|
|        xref:Miscellaneous.adoc#miscellaneous_carbon_carbon[`Carbon`]
    a|createdAt
    a|
|        xref:Miscellaneous.adoc#miscellaneous_carbon_carbon[`Carbon`]
    a|updatedAt
    a|
|
    a|contacts
    a|
|
    a|accounts
    a|
|        xref:Account.adoc#account_models_accountcontactrelation[`AccountContactRelation`]
    a|accountContactRelation
    a|
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[account_newsletter]]
= Newsletter

[[account_newsletter_contracts]]
== Contracts
[[account_contracts_newsletterrepositorycontract]]
=== NewsletterRepositoryContract

The NewsletterRepositoryContract is the interface for the newsletter repository. This interface allows to assign email addresses of recipients to email folders. Depending on the settings selected for each email folder, different newsletters can be sent to different target groups.



==== Namespace

`Plenty\Modules\Account\Newsletter\Contracts`






==== Methods

[source%nowrap, php]
----

public createEntry($data = []):Plenty\Modules\Account\Newsletter\Models\Entry

----

    


===== *Return type:*        xref:Account.adoc#account_models_entry[`Entry`]


Creates an entry.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public createRecipient($data = []):array

----

    





Creates a recipient for an existing folder.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public createFolder($data = []):Plenty\Modules\Account\Newsletter\Models\Folder

----

    


===== *Return type:*        xref:Account.adoc#account_models_folder[`Folder`]


Creates a folder.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public deleteAllEntries():array

----

    





Deletes all entries.

[source%nowrap, php]
----

public deleteAllFolders():array

----

    





Deletes all folders.

[source%nowrap, php]
----

public deleteAllRecipients():array

----

    





Deletes all recipients.

[source%nowrap, php]
----

public deleteEntryById($entryId):Plenty\Modules\Account\Newsletter\Models\Entry

----

    


===== *Return type:*        xref:Account.adoc#account_models_entry[`Entry`]


Deletes an entry. The ID of the entry must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$entryId`
a|The ID of the entry
|===


[source%nowrap, php]
----

public deleteFolderById($folderId):Plenty\Modules\Account\Newsletter\Models\Folder

----

    


===== *Return type:*        xref:Account.adoc#account_models_folder[`Folder`]


Deletes a folder. The ID of the folder must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$folderId`
a|The ID of the folder
|===


[source%nowrap, php]
----

public deleteRecipientById($recipientId):Plenty\Modules\Account\Newsletter\Models\Recipient

----

    


===== *Return type:*        xref:Account.adoc#account_models_recipient[`Recipient`]


Deletes a recipient. The ID of the recipient must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$recipientId`
a|The ID of the recipient
|===


[source%nowrap, php]
----

public listAllEntries():array

----

    





Lists all newsletter entries.

[source%nowrap, php]
----

public listAllFolders():array

----

    





Lists all newsletter folders.

[source%nowrap, php]
----

public listAllRecipients($data = []):array

----

    





Lists all recipients.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public getRecipientsByEMail($email):array

----

    





Returns recipients by the email address.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$email`
a|The email address of the recipient
|===


[source%nowrap, php]
----

public listRecipients($columns, $page, $itemsPerPage, $filter, $with):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Lists all recipients.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|The columns to retrieve

|link:http://php.net/int[int^]
a|`$page`
a|The page of results to search for

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items to list per page

|link:http://php.net/array[array^]
a|`$filter`
a|Filter that restricts the search result

|link:http://php.net/array[array^]
a|`$with`
a|An array with child instances to be loaded
|===


[source%nowrap, php]
----

public listEntryById($entryId):Plenty\Modules\Account\Newsletter\Models\Entry

----

    


===== *Return type:*        xref:Account.adoc#account_models_entry[`Entry`]


Gets details by the entry ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$entryId`
a|The ID of the entry
|===


[source%nowrap, php]
----

public listFolderById($folderId):Plenty\Modules\Account\Newsletter\Models\Folder

----

    


===== *Return type:*        xref:Account.adoc#account_models_folder[`Folder`]


Gets details by the folder ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$folderId`
a|The ID of the folder
|===


[source%nowrap, php]
----

public listRecipientById($recipientId):Plenty\Modules\Account\Newsletter\Models\Recipient

----

    


===== *Return type:*        xref:Account.adoc#account_models_recipient[`Recipient`]


Gets details by the recipient ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$recipientId`
a|The ID of the recipient
|===


[source%nowrap, php]
----

public updateEntryById($entryId, $data = []):Plenty\Modules\Account\Newsletter\Models\Entry

----

    


===== *Return type:*        xref:Account.adoc#account_models_entry[`Entry`]


Updates an existing entry. The ID of the entry must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$entryId`
a|The ID of the entry

|link:http://php.net/array[array^]
a|`$data`
a|The data as associative array
|===


[source%nowrap, php]
----

public updateFolderById($folderId, $data = []):Plenty\Modules\Account\Newsletter\Models\Folder

----

    


===== *Return type:*        xref:Account.adoc#account_models_folder[`Folder`]


Updates an existing folder. The ID of the folder must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$folderId`
a|The ID of the folder

|link:http://php.net/array[array^]
a|`$data`
a|The data as associative array
|===


[source%nowrap, php]
----

public updateRecipientById($recipientId, $data = []):Plenty\Modules\Account\Newsletter\Models\Recipient

----

    


===== *Return type:*        xref:Account.adoc#account_models_recipient[`Recipient`]


Updates an existing recipient. The ID of the recipient must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$recipientId`
a|The ID of the recipient

|link:http://php.net/array[array^]
a|`$data`
a|The data as associative array
|===


[source%nowrap, php]
----

public addToNewsletterList($email, $forename = &quot;&quot;, $surname = &quot;&quot;, $emailDirIds = []):void

----

[WARNING]
.Deprecated! 
====

This method will not be supported in the future. Please refrain from using it as soon as possible.

====
    





Adds the email address of a contact or an interested party to an email folder for the newsletter list.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$email`
a|The email address of the contact or interested party who subscribed to the newsletter

|link:http://php.net/string[string^]
a|`$forename`
a|The first name of the contact or interested party

|link:http://php.net/string[string^]
a|`$surname`
a|The last name of the contact or interested party

|link:http://php.net/array[array^]
a|`$emailDirIds`
a|The IDs of the email folders. The email addresses of the contacts and interested parties must be saved in the folders. This will allow to send different newsletters to different target groups.
|===


[[account_newsletter_models]]
== Models
[[account_models_entry]]
=== Entry

The newsletter entry model.



==== Namespace

`Plenty\Modules\Account\Newsletter\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|subject
    a|The subject of the newsletter entry
|link:http://php.net/string[string^]
    a|body
    a|The body of the newsletter entry
|link:http://php.net/string[string^]
    a|kind
    a|The type of the newsletter entry
|link:http://php.net/string[string^]
    a|log
    a|The log of the newsletter entry
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_folder]]
=== Folder

The newsletter folder model.



==== Namespace

`Plenty\Modules\Account\Newsletter\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the newsletter folder
|link:http://php.net/string[string^]
    a|name
    a|The name of the newsletter folder
|link:http://php.net/bool[bool^]
    a|isDeletable
    a|Flag that indicates if the newsletter folder can be deleted. The folders 'Customers' and 'Interested parties' are available by default and cannot be deleted.
|link:http://php.net/int[int^]
    a|position
    a|The position of the newsletter folder
|link:http://php.net/bool[bool^]
    a|isSelectable
    a|Flag that indicates if the newsletter folder can be selected by customers in the online store. If this is allowed, the folder will be displayed in the My account area of the online store. Customers will then be able to subscribe to the newsletters that are included in this folder.
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_newsletteremail]]
=== NewsletterEmail

NewsletterEmail



==== Namespace

`Plenty\Modules\Account\Newsletter\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the newsletter email
|link:http://php.net/int[int^]
    a|directory
    a|The ID of the directory
|link:http://php.net/int[int^]
    a|customerId
    a|The ID of the contact
|link:http://php.net/string[string^]
    a|forename
    a|The first name of the contact or interested party
|link:http://php.net/string[string^]
    a|surname
    a|The last name of the contact or interested party
|link:http://php.net/string[string^]
    a|email
    a|The email address The email address of the contact or interested party
|link:http://php.net/string[string^]
    a|gender
    a|The gender of the contact or interested party
|link:http://php.net/string[string^]
    a|birthday
    a|The birthday of the contact or interested party
|link:http://php.net/int[int^]
    a|timestamp
    a|The timestamp when the newsletter email was sent to the contact or interested party
|link:http://php.net/string[string^]
    a|templateLang
    a|The language of the newsletter's email template
|link:http://php.net/int[int^]
    a|confirmedTimestamp
    a|The timestamp when the contact or interested party confirmed the newsletter subscription
|link:http://php.net/string[string^]
    a|confirmAuthString
    a|The key that is automatically generated by the system. This key recognises the user regardless whether the user is logged in to the system and will then set the confirmation timestamp.
|link:http://php.net/string[string^]
    a|ipAddress
    a|The ip address of the client
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[account_models_recipient]]
=== Recipient

The newsletter recipient



==== Namespace

`Plenty\Modules\Account\Newsletter\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the newsletter recipient
|link:http://php.net/int[int^]
    a|folderId
    a|The ID of the newsletter folder
|link:http://php.net/int[int^]
    a|contactId
    a|The ID of the contact
|link:http://php.net/string[string^]
    a|firstName
    a|The first name of the recipient
|link:http://php.net/string[string^]
    a|lastName
    a|The last name of the recipient
|link:http://php.net/string[string^]
    a|email
    a|The email address of the recipient
|link:http://php.net/string[string^]
    a|gender
    a|The gender of the recipient
|link:http://php.net/string[string^]
    a|birthday
    a|The birthday of the recipient
|link:http://php.net/int[int^]
    a|timestamp
    a|The timestamp when the newsletter email was sent to the recipient
|link:http://php.net/string[string^]
    a|templateLang
    a|The language of the newsletter email template
|link:http://php.net/int[int^]
    a|confirmedTimestamp
    a|The timestamp when the recipient confirmed the newsletter subscription
|link:http://php.net/string[string^]
    a|confirmAuthString
    a|The key that is automatically generated by the system. This key recognises the user regardless whether the user is logged in to the system and will then set the confirmation timestamp.
|link:http://php.net/string[string^]
    a|ipAddress
    a|The IP address from where the customer has confirmed the newsletter
|link:http://php.net/string[string^]
    a|confirmationURL
    a|The url with which the customer has confirmed the newsletter
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[account_ordersummary]]
= OrderSummary

[[account_ordersummary_contracts]]
== Contracts
[[account_contracts_ordersummaryrepositorycontract]]
=== OrderSummaryRepositoryContract

The OrderSummaryRepositoryContract is the interface for the order summary repository. This interface allows to list, get, update, create and delete order summaries.



==== Namespace

`Plenty\Modules\Account\OrderSummary\Contracts`






==== Methods

[source%nowrap, php]
----

public findOrderSummaryById($orderSummaryId):Plenty\Modules\Account\OrderSummary\Models\OrderSummary

----

    


===== *Return type:*        xref:Account.adoc#account_models_ordersummary[`OrderSummary`]


Gets an order summary. The ID of the order summary must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderSummaryId`
a|The ID of the order summary
|===


[source%nowrap, php]
----

public updateOrderSummary($data, $orderSummaryId):Plenty\Modules\Account\OrderSummary\Models\OrderSummary

----

    


===== *Return type:*        xref:Account.adoc#account_models_ordersummary[`OrderSummary`]


Updates an order summary. The ID of the order summary must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The order summary data as associative array

|link:http://php.net/int[int^]
a|`$orderSummaryId`
a|The ID of the order summary
|===


[source%nowrap, php]
----

public createOrderSummary($data):Plenty\Modules\Account\OrderSummary\Models\OrderSummary

----

    


===== *Return type:*        xref:Account.adoc#account_models_ordersummary[`OrderSummary`]


Creates an order summary.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The order summary data as associative array
|===


[source%nowrap, php]
----

public deleteOrderSummary($orderSummaryId):bool

----

    





Deletes an order summary. The ID of the order summary must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderSummaryId`
a|The ID of the order summary
|===


[source%nowrap, php]
----

public allOrderSummaries($columns = [], $perPage = 50):Illuminate\Database\Eloquent\Collection

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Returns a collection of all order summaries.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|Optional: The columns to retrieve (Default: '[*]').

|link:http://php.net/int[int^]
a|`$perPage`
a|Optional: The number of objects per page (Default: 50).
|===


[source%nowrap, php]
----

public findOrderSummaryByContactId($contactId):Plenty\Modules\Account\OrderSummary\Models\OrderSummary

----

    


===== *Return type:*        xref:Account.adoc#account_models_ordersummary[`OrderSummary`]


Gets an order summary. The ID of the contact must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactId`
a|The ID of the contact
|===


[source%nowrap, php]
----

public findOrderSummaryByAddressId($addressId):Plenty\Modules\Account\OrderSummary\Models\OrderSummary

----

    


===== *Return type:*        xref:Account.adoc#account_models_ordersummary[`OrderSummary`]


Gets an order summary. The ID of the address must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$addressId`
a|The ID of the address
|===


[[account_ordersummary_models]]
== Models
[[account_models_ordersummary]]
=== OrderSummary

The order summary model.



==== Namespace

`Plenty\Modules\Account\OrderSummary\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the order summary
|link:http://php.net/int[int^]
    a|addressId
    a|The address ID of the order summary
|link:http://php.net/int[int^]
    a|contactId
    a|The ID of the contact
|link:http://php.net/int[int^]
    a|unpaidOrdersCount
    a|The number of unpaid orders
|link:http://php.net/float[float^]
    a|unpaidOrderTotalAmount
    a|The total amount of unpaid orders
|link:http://php.net/int[int^]
    a|orderCount
    a|The number of all orders of the associated model
|link:http://php.net/string[string^]
    a|createdAt
    a|The time the order summary was created as unix timestamp
|link:http://php.net/string[string^]
    a|updatedAt
    a|The time the order summary was last updated as unix timestamp
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

