:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[amazon_amazon]]
== Amazon

[[amazon_amazon_contracts]]
===  Contracts
[[amazon_contracts_amazonclient]]
==== AmazonClient

The amazon client

[WARNING]
.Deprecated! 
====

This interface is based on the MWS API which will be deprecated in steps from 31.07.2022 till 31.12.2022. We will not provide a new interface for the SP-API.

====


===== Namespace

`Plenty\Modules\Amazon\Contracts`






===== Methods

[source%nowrap, php]
[#sendrequest]
----

public sendRequest($request, $serviceVersion):Plenty\Modules\Amazon\Contracts\AmazonClientResponse

----




====== *Return type:*        xref:Amazon.adoc#amazon_contracts_amazonclientresponse[`AmazonClientResponse`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$request`
|        xref:Amazon.adoc#amazon_contracts_amazonclientrequest[`AmazonClientRequest`]
a|

a|`$serviceVersion`
|link:http://php.net/string[string^]
a|
|===



[[amazon_contracts_amazonclientfactory]]
==== AmazonClientFactory



[WARNING]
.Deprecated! 
====

This interface is based on the MWS API which will be deprecated in steps from 31.07.2022 till 31.12.2022. We will not provide a new interface for the SP-API.

====


===== Namespace

`Plenty\Modules\Amazon\Contracts`






===== Methods

[source%nowrap, php]
[#getclient]
----

public getClient($accountId, $endpointPath):Plenty\Modules\Amazon\Contracts\AmazonClient

----




====== *Return type:*        xref:Amazon.adoc#amazon_contracts_amazonclient[`AmazonClient`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$accountId`
|link:http://php.net/int[int^]
a|

a|`$endpointPath`
|link:http://php.net/string[string^]
a|
|===



[[amazon_contracts_amazonclientrequest]]
==== AmazonClientRequest



[WARNING]
.Deprecated! 
====

This interface is based on the MWS API which will be deprecated in steps from 31.07.2022 till 31.12.2022. We will not provide a new interface for the SP-API.

====


===== Namespace

`Plenty\Modules\Amazon\Contracts`






===== Methods

[source%nowrap, php]
[#getrequestdata]
----

public getRequestData():array

----









[source%nowrap, php]
[#requiressellerid]
----

public requiresSellerId():bool

----









[source%nowrap, php]
[#getselleridfieldname]
----

public getSellerIdFieldName():string

----









[source%nowrap, php]
[#getaction]
----

public getAction():string

----










[[amazon_contracts_amazonclientrequestpayload]]
==== AmazonClientRequestPayload



[WARNING]
.Deprecated! 
====

This interface is based on the MWS API which will be deprecated in steps from 31.07.2022 till 31.12.2022. We will not provide a new interface for the SP-API.

====


===== Namespace

`Plenty\Modules\Amazon\Contracts`






===== Methods

[source%nowrap, php]
[#getpayload]
----

public getPayload():void

----










[[amazon_contracts_amazonclientresponse]]
==== AmazonClientResponse



[WARNING]
.Deprecated! 
====

This interface is based on the MWS API which will be deprecated in steps from 31.07.2022 till 31.12.2022. We will not provide a new interface for the SP-API.

====


===== Namespace

`Plenty\Modules\Amazon\Contracts`






===== Methods

[source%nowrap, php]
[#getresponsecontent]
----

public getResponseContent():void

----









[source%nowrap, php]
[#getresponsemetadata]
----

public getResponseMetaData():array

----










[[amazon_contracts_amazonfulfillmentcenterrepositorycontract]]
==== AmazonFulfillmentCenterRepositoryContract

AmazonFulfillmentCenterRepository



===== Namespace

`Plenty\Modules\Amazon\Contracts`






===== Methods

[source%nowrap, php]
[#getdeliveryaddresses]
----

public getDeliveryAddresses():array

----







Lists amazon fulfilment centers delivery addresses.

[source%nowrap, php]
[#getdeliveryaddressbyfulfillmentcenterid]
----

public getDeliveryAddressByFulfillmentCenterId($amazonFulfillmentCenterId):Plenty\Modules\Account\Address\Models\Address

----




====== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Get the delivery address by fulfillment center ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$amazonFulfillmentCenterId`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getdeliveryaddressbygln]
----

public getDeliveryAddressByGLN($GLN):Plenty\Modules\Account\Address\Models\Address

----




====== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Get the delivery address by GLN.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$GLN`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getinvoiceaddressbygln]
----

public getInvoiceAddressByGLN($GLN):Plenty\Modules\Account\Address\Models\Address

----




====== *Return type:*        xref:Account.adoc#account_models_address[`Address`]


Get the invoice address by GLN.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$GLN`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getcontactid]
----

public getContactId():int

----









[[amazon_amazon_exceptions]]
===  Exceptions
[[amazon_exceptions_amazonclientexception]]
==== AmazonClientException

Created by ptopczewski, 01.02.18 11:41
Class AmazonClientException



===== Namespace

`Plenty\Modules\Amazon\Exceptions`






[[amazon_exceptions_amazonclientrequestexception]]
==== AmazonClientRequestException

Created by ptopczewski, 07.02.18 10:34
Class AmazonClientRequestException



===== Namespace

`Plenty\Modules\Amazon\Exceptions`






===== Methods

[source%nowrap, php]
[#gettype]
----

public getType():string

----









[source%nowrap, php]
[#getrequestid]
----

public getRequestId():string

----









[source%nowrap, php]
[#geterrorcode]
----

public getErrorCode():string

----









