:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[basket_basket]]
= Basket

[[basket_basket_contracts]]
== Contracts
[[basket_contracts_basketitemrepositorycontract]]
=== BasketItemRepositoryContract

The BasketItemRepositoryContract is the interface for the basket item repository. This interface allows to list, add, update and delete items from the shopping cart of the current customer session.



==== Namespace

`Plenty\Modules\Basket\Contracts`






==== Methods

[source%nowrap, php]
----

public findOneById($basketRowId):Plenty\Modules\Basket\Models\BasketItem

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]


Gets an existing item by ID in the shopping cart of the current customer session.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$basketRowId`
a|The ID of the basket row
|===


[source%nowrap, php]
----

public findExistingOneByData($data):Plenty\Modules\Basket\Models\BasketItem

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]


Gets an existing item by item data in the shopping cart of the current customer session.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The item's data
|===


[source%nowrap, php]
----

public all():array

----

    





Lists all items in the shopping cart of the current customer session.

[source%nowrap, php]
----

public addBasketItem($data):Plenty\Modules\Basket\Models\BasketItem

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]


Creates an item with the specified item data in the shopping cart.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The item's data
|===


[source%nowrap, php]
----

public updateBasketItem($basketItemId, $data):void

----

    





Updates an existing item in the shopping cart. The ID of the item and the data to be updated must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$basketItemId`
a|The ID of the item in the shopping cart

|link:http://php.net/array[array^]
a|`$data`
a|The item's data
|===


[source%nowrap, php]
----

public removeBasketItem($basketItemId, $dispatchAfterBasketChangedEvent = true):void

----

    





Deletes an item from the shopping cart. The ID of the item must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$basketItemId`
a|The ID of the item in the shopping cart

|link:http://php.net/bool[bool^]
a|`$dispatchAfterBasketChangedEvent`
a|The information if the AfterBasketChanged event should be dispatched
|===



[[basket_contracts_basketrepositorycontract]]
=== BasketRepositoryContract

The BasketRepositoryContract is the interface for the basket repository. This interface allows to get the shopping cart of the current customer session.



==== Namespace

`Plenty\Modules\Basket\Contracts`






==== Methods

[source%nowrap, php]
----

public load():Plenty\Modules\Basket\Models\Basket

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]


Gets the shopping cart from current customer session.

[source%nowrap, php]
----

public save($data):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public setCouponCode($couponCode):Plenty\Modules\Basket\Models\Basket

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$couponCode`
a|
|===


[source%nowrap, php]
----

public removeCouponCode():Plenty\Modules\Basket\Models\Basket

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]




[[basket_basket_exceptions]]
== Exceptions
[[basket_exceptions_basketcheckexception]]
=== BasketCheckException

Class BasketCheckException



==== Namespace

`Plenty\Modules\Basket\Exceptions`






==== Methods

[source%nowrap, php]
----

public __construct($code, $message = &quot;&quot;, $previous = null):void

----

    





BasketCheckException constructor.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$code`
a|

|link:http://php.net/string[string^]
a|`$message`
a|

|
a|`$previous`
a|
|===



[[basket_exceptions_basketitemcheckexception]]
=== BasketItemCheckException

Created by ptopczewski, 12.05.16 09:03
Class BasketItemCheckException



==== Namespace

`Plenty\Modules\Basket\Exceptions`






==== Methods

[source%nowrap, php]
----

public __construct($code = 404, $message = &quot;&quot;, $previous = null, $itemId, $variationId, $stockNet = 0.0, $additionalData = []):void

----

    





BasketItemCheckException constructor.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$code`
a|

|link:http://php.net/string[string^]
a|`$message`
a|

|
a|`$previous`
a|

|link:http://php.net/int[int^]
a|`$itemId`
a|

|link:http://php.net/int[int^]
a|`$variationId`
a|

|link:http://php.net/float[float^]
a|`$stockNet`
a|

|link:http://php.net/array[array^]
a|`$additionalData`
a|
|===


[source%nowrap, php]
----

public getItemId():int

----

    







[source%nowrap, php]
----

public getVariationId():int

----

    







[source%nowrap, php]
----

public getStockNet():float

----

    







[source%nowrap, php]
----

public getAdditionalData():array

----

    








[[basket_exceptions_basketitemquantitycheckexception]]
=== BasketItemQuantityCheckException

Created by ptopczewski, 17.05.16 09:37
Class BasketItemQuantityCheckException



==== Namespace

`Plenty\Modules\Basket\Exceptions`






==== Methods

[source%nowrap, php]
----

public __construct($code, $message = &quot;&quot;, $previous = null, $itemId, $variationId, $requestedQuantity = 0.0, $specifiedQuantity = 0.0):void

----

    





BasketItemQuantityCheckException constructor.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$code`
a|

|link:http://php.net/string[string^]
a|`$message`
a|

|
a|`$previous`
a|

|link:http://php.net/int[int^]
a|`$itemId`
a|

|link:http://php.net/int[int^]
a|`$variationId`
a|

|link:http://php.net/float[float^]
a|`$requestedQuantity`
a|

|link:http://php.net/float[float^]
a|`$specifiedQuantity`
a|
|===


[source%nowrap, php]
----

public getRequestedQuantity():float

----

    







[source%nowrap, php]
----

public getSpecifiedQuantity():float

----

    







[[basket_basket_models]]
== Models
[[basket_models_basket]]
=== Basket

The basket model



==== Namespace

`Plenty\Modules\Basket\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the shopping cart. The ID increases by 1 when a new customer enters the online store and adds an item to the shopping cart.
|link:http://php.net/string[string^]
    a|sessionId
    a|The ID of the current customer session
|link:http://php.net/int[int^]
    a|orderId
    a|The ID of the order
|link:http://php.net/int[int^]
    a|customerId
    a|The ID of the customer
|link:http://php.net/int[int^]
    a|customerInvoiceAddressId
    a|The ID of the customer's invoice address
|link:http://php.net/int[int^]
    a|customerShippingAddressId
    a|The ID of the customer's shipping address
|link:http://php.net/string[string^]
    a|currency
    a|The currency
|link:http://php.net/float[float^]
    a|referrerId
    a|The ID of the order referrer
|link:http://php.net/int[int^]
    a|shippingCountryId
    a|The ID of the shipping country
|link:http://php.net/int[int^]
    a|methodOfPaymentId
    a|The ID of the payment method
|link:http://php.net/int[int^]
    a|shippingProviderId
    a|The ID of the shipping provider
|link:http://php.net/int[int^]
    a|shippingProfileId
    a|The ID of the shipping profile
|link:http://php.net/float[float^]
    a|itemSum
    a|The gross value of items in the shopping cart
|link:http://php.net/float[float^]
    a|itemSumNet
    a|The net value of items in the shopping cart
|link:http://php.net/float[float^]
    a|basketAmount
    a|The total gross value of the shopping cart
|link:http://php.net/float[float^]
    a|basketAmountNet
    a|The total net value of the shopping cart
|link:http://php.net/float[float^]
    a|shippingAmount
    a|The gross shipping costs
|link:http://php.net/float[float^]
    a|shippingAmountNet
    a|The net shipping costs
|link:http://php.net/float[float^]
    a|paymentAmount
    a|The amount of the payment
|link:http://php.net/string[string^]
    a|couponCode
    a|The entered coupon code
|link:http://php.net/float[float^]
    a|couponDiscount
    a|The received discount due to the coupon code
|link:http://php.net/bool[bool^]
    a|shippingDeleteByCoupon
    a|Shows whether the shipping costs are subtracted due to a coupon code. Shopping carts that are free of shipping costs have the value true.
|link:http://php.net/float[float^]
    a|basketRebate
    a|The discount to the shopping cart value. The discount can either be set as a discount scale for items, as a customer class discount or as a discount based on the payment method.
|link:http://php.net/int[int^]
    a|basketRebateType
    a|The discount type. The following types are available:
<ul>
    <li>Discount scale based on net value of items = 4</li>
    <li>    Discount based on method of payment = 5</li>
</ul>
|link:http://php.net/int[int^]
    a|maxFsk
    a|The age rating
|link:http://php.net/int[int^]
    a|orderTimestamp
    a|The timestamp of the order
|link:http://php.net/string[string^]
    a|createdAt
    a|The date that the shopping cart was created.
|link:http://php.net/string[string^]
    a|updatedAt
    a|The date that the shopping cart was updated last.
|
    a|basketItems
    a|
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[basket_models_basketitem]]
=== BasketItem

The basket item model



==== Namespace

`Plenty\Modules\Basket\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the item in the shopping cart
|link:http://php.net/int[int^]
    a|basketId
    a|The ID of the shopping cart. The ID increases by 1 when a new customer enters the online store and adds an item to the shopping cart.
|link:http://php.net/string[string^]
    a|sessionId
    a|The ID of the current customer session
|link:http://php.net/int[int^]
    a|orderRowId
    a|
|link:http://php.net/float[float^]
    a|quantity
    a|The current quantity of the item
|link:http://php.net/float[float^]
    a|quantityOriginally
    a|The initial quantity of the item
|link:http://php.net/int[int^]
    a|itemId
    a|The ID of the item
|link:http://php.net/int[int^]
    a|priceId
    a|The ID of the item price
|link:http://php.net/int[int^]
    a|attributeValueSetId
    a|The ID of the attribute value set
|link:http://php.net/int[int^]
    a|rebate
    a|The discount on the item
|link:http://php.net/float[float^]
    a|vat
    a|The VAT
|link:http://php.net/float[float^]
    a|price
    a|The item price
|link:http://php.net/float[float^]
    a|givenPrice
    a|
|link:http://php.net/bool[bool^]
    a|useGivenPrice
    a|
|link:http://php.net/int[int^]
    a|inputWidth
    a|The width of the item
|link:http://php.net/int[int^]
    a|inputLength
    a|The length of the item
|link:http://php.net/int[int^]
    a|inputHeight
    a|The height of the item
|link:http://php.net/int[int^]
    a|itemType
    a|The item type
|link:http://php.net/string[string^]
    a|externalItemId
    a|The external variation ID
|link:http://php.net/bool[bool^]
    a|noEditByCustomer
    a|Shows whether the item was edited by the customer
|link:http://php.net/int[int^]
    a|costCenterId
    a|
|link:http://php.net/int[int^]
    a|giftPackageForRowId
    a|
|link:http://php.net/int[int^]
    a|position
    a|The item position
|link:http://php.net/string[string^]
    a|size
    a|The item size
|link:http://php.net/int[int^]
    a|shippingProfileId
    a|The ID of the shipping profile
|link:http://php.net/float[float^]
    a|referrerId
    a|The ID of the order referrer
|link:http://php.net/string[string^]
    a|deliveryDate
    a|The delivery date
|link:http://php.net/int[int^]
    a|categoryId
    a|The ID of the item category
|link:http://php.net/int[int^]
    a|reservationDatetime
    a|
|link:http://php.net/int[int^]
    a|variationId
    a|The ID of the item variation
|link:http://php.net/int[int^]
    a|bundleVariationId
    a|The ID of the item bundle type
|link:http://php.net/string[string^]
    a|createdAt
    a|The date that the shopping cart was created
|link:http://php.net/string[string^]
    a|updatedAt
    a|The date that the shopping cart was updated last
|link:http://php.net/float[float^]
    a|attributeTotalMarkup
    a|attribute total markup
|link:http://php.net/array[array^]
    a|basketItemOrderParams
    a|Array of BasketItemParams
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[basket_models_basketitemparams]]
=== BasketItemParams

The basket item params model



==== Namespace

`Plenty\Modules\Basket\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|type
    a|
|link:http://php.net/string[string^]
    a|name
    a|
|link:http://php.net/string[string^]
    a|value
    a|
|link:http://php.net/int[int^]
    a|basketItemId
    a|
|link:http://php.net/int[int^]
    a|propertyId
    a|
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[basket_events]]
= Events

[[basket_events_basket]]
== Basket
[[basket_basket_afterbasketchanged]]
=== AfterBasketChanged

The event is triggered after the shopping cart is changed.



==== Namespace

`Plenty\Modules\Basket\Events\Basket`






==== Methods

[source%nowrap, php]
----

public hasValidCoupon():bool

----

    







[source%nowrap, php]
----

public getCouponValidationError():void

----

    







[source%nowrap, php]
----

public setHasValidCoupon($hasValidCoupon, $couponValidationError = null):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$hasValidCoupon`
a|Flag that indicates if a valid coupon has been used.

|        xref:Miscellaneous.adoc#miscellaneous_exceptions_validationexception[`ValidationException`]
a|`$couponValidationError`
a|Validation errors indicating the reasons for an invalid coupon.
|===


[source%nowrap, php]
----

public getBasket():Plenty\Modules\Basket\Models\Basket

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]




[source%nowrap, php]
----

public getLocationId():int

----

    







[source%nowrap, php]
----

public setLocationId($locationId):Plenty\Modules\Basket\Events\Basket

----

    


===== *Return type:*        xref:Basket.adoc#basket_events_basket[`Basket`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$locationId`
a|The ID of the location
|===


[source%nowrap, php]
----

public getInvoiceAddress():Plenty\Modules\Account\Address\Models\Address

----

    


===== *Return type:*        xref:Account.adoc#account_models_address[`Address`]




[source%nowrap, php]
----

public setInvoiceAddress($invoiceAddress):Plenty\Modules\Basket\Events\Basket

----

    


===== *Return type:*        xref:Basket.adoc#basket_events_basket[`Basket`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Account.adoc#account_models_address[`Address`]
a|`$invoiceAddress`
a|The invoice address
|===


[source%nowrap, php]
----

public getMaxFsk():int

----

    







[source%nowrap, php]
----

public setMaxFsk($maxFsk):Plenty\Modules\Basket\Events\Basket

----

    


===== *Return type:*        xref:Basket.adoc#basket_events_basket[`Basket`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$maxFsk`
a|The highest value for age restriction of an item in the shopping cart
|===


[source%nowrap, php]
----

public getShippingCosts():float

----

    







[source%nowrap, php]
----

public setShippingCosts($shippingCosts):Plenty\Modules\Basket\Events\Basket

----

    


===== *Return type:*        xref:Basket.adoc#basket_events_basket[`Basket`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/float[float^]
a|`$shippingCosts`
a|The shipping costs of the shopping cart
|===



[[basket_basket_afterbasketcreate]]
=== AfterBasketCreate

The event is triggered after the shopping cart is created.



==== Namespace

`Plenty\Modules\Basket\Events\Basket`






==== Methods

[source%nowrap, php]
----

public getBasket():Plenty\Modules\Basket\Models\Basket

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]




[[basket_events_basketitem]]
== BasketItem
[[basket_basketitem_afterbasketitemadd]]
=== AfterBasketItemAdd

The event is triggered after an item is added to the shopping cart.



==== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






==== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]





[[basket_basketitem_afterbasketitemremove]]
=== AfterBasketItemRemove

The event is triggered after an item is deleted from the shopping cart.



==== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






[[basket_basketitem_afterbasketitemupdate]]
=== AfterBasketItemUpdate

The event is triggered after an item in the shopping cart is updated.



==== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






==== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]





[[basket_basketitem_basketitemevent]]
=== BasketItemEvent

BasketItemEvent



==== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






==== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]





[[basket_basketitem_beforebasketitemadd]]
=== BeforeBasketItemAdd

The event is triggered before an item is created in the shopping cart.



==== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






==== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]





[[basket_basketitem_beforebasketitemremove]]
=== BeforeBasketItemRemove

The event is triggered before an item is deleted from the shopping cart.



==== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






[[basket_basketitem_beforebasketitemupdate]]
=== BeforeBasketItemUpdate

The event is triggered before an item in the shopping cart is updated.



==== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






==== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----

    


===== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]




