:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[basket_basket]]
== Basket

[[basket_basket_contracts]]
===  Contracts
[[basket_contracts_basketitemrepositorycontract]]
==== BasketItemRepositoryContract

The BasketItemRepositoryContract is the interface for the basket item repository. This interface allows to list, add, update and delete items from the shopping cart of the current customer session.



===== Namespace

`Plenty\Modules\Basket\Contracts`






===== Methods

[source%nowrap, php]
----

public findOneById($basketRowId):Plenty\Modules\Basket\Models\BasketItem

----




====== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]


Gets an existing item by ID in the shopping cart of the current customer session.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$basketRowId`
|link:http://php.net/int[int^]
a|The ID of the basket row
|===


[source%nowrap, php]
----

public findExistingOneByData($data):Plenty\Modules\Basket\Models\BasketItem

----




====== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]


Gets an existing item by item data in the shopping cart of the current customer session.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The item's data
|===


[source%nowrap, php]
----

public all():array

----







Lists all items in the shopping cart of the current customer session.

[source%nowrap, php]
----

public addBasketItem($data, $fireEvents = true):Plenty\Modules\Basket\Models\BasketItem

----




====== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]


Creates an item with the specified item data in the shopping cart.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The item's data

a|`$fireEvents`
|link:http://php.net/bool[bool^]
a|Set to false to skip change events and calculation of basket totals.
|===


[source%nowrap, php]
----

public updateBasketItem($basketItemId, $data, $fireEvents = true):void

----







Updates an existing item in the shopping cart. The ID of the item and the data to be updated must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$basketItemId`
|link:http://php.net/int[int^]
a|The ID of the item in the shopping cart

a|`$data`
|link:http://php.net/array[array^]
a|The item's data

a|`$fireEvents`
|link:http://php.net/bool[bool^]
a|Set to false to skip change events and calculation of basket totals.
|===


[source%nowrap, php]
----

public removeBasketItem($basketItemId, $dispatchAfterBasketChangedEvent = true):void

----







Deletes an item from the shopping cart. The ID of the item must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$basketItemId`
|link:http://php.net/int[int^]
a|The ID of the item in the shopping cart

a|`$dispatchAfterBasketChangedEvent`
|link:http://php.net/bool[bool^]
a|The information if the AfterBasketChanged event should be dispatched
|===



[[basket_contracts_basketrepositorycontract]]
==== BasketRepositoryContract

The BasketRepositoryContract is the interface for the basket repository. This interface allows to get the shopping cart of the current customer session.



===== Namespace

`Plenty\Modules\Basket\Contracts`






===== Methods

[source%nowrap, php]
----

public load():Plenty\Modules\Basket\Models\Basket

----




====== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]


Gets the shopping cart from current customer session.

[source%nowrap, php]
----

public save($data):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
----

public setCouponCode($couponCode):Plenty\Modules\Basket\Models\Basket

----




====== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$couponCode`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
----

public removeCouponCode():Plenty\Modules\Basket\Models\Basket

----




====== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]




[source%nowrap, php]
----

public deleteBasket():Plenty\Modules\Basket\Models\Basket

----




====== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]


Delete the basket for current session

[[basket_basket_exceptions]]
===  Exceptions
[[basket_exceptions_basketcheckexception]]
==== BasketCheckException

Class BasketCheckException



===== Namespace

`Plenty\Modules\Basket\Exceptions`






===== Methods

[source%nowrap, php]
----

public __construct($code, $message = &quot;&quot;, $previous = null):void

----







BasketCheckException constructor.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$code`
|link:http://php.net/string[string^]
a|

a|`$message`
|link:http://php.net/string[string^]
a|

a|`$previous`
|
a|
|===



[[basket_exceptions_basketitemcheckexception]]
==== BasketItemCheckException

Created by ptopczewski, 12.05.16 09:03
Class BasketItemCheckException



===== Namespace

`Plenty\Modules\Basket\Exceptions`






===== Methods

[source%nowrap, php]
----

public __construct($code = 404, $message = &quot;&quot;, $previous = null, $itemId, $variationId, $stockNet = 0.0, $additionalData = []):void

----







BasketItemCheckException constructor.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$code`
|link:http://php.net/int[int^]
a|

a|`$message`
|link:http://php.net/string[string^]
a|

a|`$previous`
|
a|

a|`$itemId`
|link:http://php.net/int[int^]
a|

a|`$variationId`
|link:http://php.net/int[int^]
a|

a|`$stockNet`
|link:http://php.net/float[float^]
a|

a|`$additionalData`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
----

public getItemId():int

----









[source%nowrap, php]
----

public getVariationId():int

----









[source%nowrap, php]
----

public getStockNet():float

----









[source%nowrap, php]
----

public getAdditionalData():array

----










[[basket_exceptions_basketitemquantitycheckexception]]
==== BasketItemQuantityCheckException

Created by ptopczewski, 17.05.16 09:37
Class BasketItemQuantityCheckException



===== Namespace

`Plenty\Modules\Basket\Exceptions`






===== Methods

[source%nowrap, php]
----

public __construct($code, $message = &quot;&quot;, $previous = null, $itemId, $variationId, $requestedQuantity = 0.0, $specifiedQuantity = 0.0):void

----







BasketItemQuantityCheckException constructor.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$code`
|link:http://php.net/int[int^]
a|

a|`$message`
|link:http://php.net/string[string^]
a|

a|`$previous`
|
a|

a|`$itemId`
|link:http://php.net/int[int^]
a|

a|`$variationId`
|link:http://php.net/int[int^]
a|

a|`$requestedQuantity`
|link:http://php.net/float[float^]
a|

a|`$specifiedQuantity`
|link:http://php.net/float[float^]
a|
|===


[source%nowrap, php]
----

public getRequestedQuantity():float

----









[source%nowrap, php]
----

public getSpecifiedQuantity():float

----









[[basket_basket_models]]
===  Models
[[basket_models_basket]]
==== Basket

The basket model



===== Namespace

`Plenty\Modules\Basket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the shopping cart. The ID increases by 1 when a new customer enters the online store and adds an item to the shopping cart.
|sessionId
    |link:http://php.net/string[string^]
    a|The ID of the current customer session
|orderId
    |link:http://php.net/int[int^]
    a|The ID of the order
|customerId
    |link:http://php.net/int[int^]
    a|The ID of the customer
|customerInvoiceAddressId
    |link:http://php.net/int[int^]
    a|The ID of the customer's invoice address
|customerShippingAddressId
    |link:http://php.net/int[int^]
    a|The ID of the customer's shipping address
|currency
    |link:http://php.net/string[string^]
    a|The currency
|referrerId
    |link:http://php.net/float[float^]
    a|The ID of the order referrer
|shippingCountryId
    |link:http://php.net/int[int^]
    a|The ID of the shipping country
|methodOfPaymentId
    |link:http://php.net/int[int^]
    a|The ID of the payment method
|shippingProviderId
    |link:http://php.net/int[int^]
    a|The ID of the shipping provider
|shippingProfileId
    |link:http://php.net/int[int^]
    a|The ID of the shipping profile
|itemSum
    |link:http://php.net/float[float^]
    a|The gross value of items in the shopping cart
|itemSumNet
    |link:http://php.net/float[float^]
    a|The net value of items in the shopping cart
|basketAmount
    |link:http://php.net/float[float^]
    a|The total gross value of the shopping cart
|basketAmountNet
    |link:http://php.net/float[float^]
    a|The total net value of the shopping cart
|shippingAmount
    |link:http://php.net/float[float^]
    a|The gross shipping costs
|shippingAmountNet
    |link:http://php.net/float[float^]
    a|The net shipping costs
|paymentAmount
    |link:http://php.net/float[float^]
    a|The amount of the payment
|couponCode
    |link:http://php.net/string[string^]
    a|The entered coupon code
|couponDiscount
    |link:http://php.net/float[float^]
    a|The received discount due to the coupon code
|shippingDeleteByCoupon
    |link:http://php.net/bool[bool^]
    a|Shows whether the shipping costs are subtracted due to a coupon code. Shopping carts that are free of shipping costs have the value true.
|basketRebate
    |link:http://php.net/float[float^]
    a|The discount to the shopping cart value. The discount can either be set as a discount scale for items, as a customer class discount or as a discount based on the payment method.
|basketRebateType
    |link:http://php.net/int[int^]
    a|The discount type. The following types are available:
<ul>
    <li>Discount scale based on net value of items = 4</li>
    <li>    Discount based on method of payment = 5</li>
</ul>
|maxFsk
    |link:http://php.net/int[int^]
    a|The age rating
|orderTimestamp
    |link:http://php.net/int[int^]
    a|The timestamp of the order
|createdAt
    |link:http://php.net/string[string^]
    a|The date that the shopping cart was created.
|updatedAt
    |link:http://php.net/string[string^]
    a|The date that the shopping cart was updated last.
|basketItems
    |
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[basket_models_basketitem]]
==== BasketItem

The basket item model



===== Namespace

`Plenty\Modules\Basket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the item in the shopping cart
|basketId
    |link:http://php.net/int[int^]
    a|The ID of the shopping cart. The ID increases by 1 when a new customer enters the online store and adds an item to the shopping cart.
|sessionId
    |link:http://php.net/string[string^]
    a|The ID of the current customer session
|orderRowId
    |link:http://php.net/int[int^]
    a|
|quantity
    |link:http://php.net/float[float^]
    a|The current quantity of the item
|quantityOriginally
    |link:http://php.net/float[float^]
    a|The initial quantity of the item
|itemId
    |link:http://php.net/int[int^]
    a|The ID of the item
|priceId
    |link:http://php.net/int[int^]
    a|The ID of the item price
|attributeValueSetId
    |link:http://php.net/int[int^]
    a|The ID of the attribute value set
|rebate
    |link:http://php.net/int[int^]
    a|The discount on the item
|vat
    |link:http://php.net/float[float^]
    a|The VAT
|price
    |link:http://php.net/float[float^]
    a|The item price
|givenPrice
    |link:http://php.net/float[float^]
    a|
|useGivenPrice
    |link:http://php.net/bool[bool^]
    a|
|inputWidth
    |link:http://php.net/int[int^]
    a|The width of the item
|inputLength
    |link:http://php.net/int[int^]
    a|The length of the item
|inputHeight
    |link:http://php.net/int[int^]
    a|The height of the item
|itemType
    |link:http://php.net/int[int^]
    a|The item type
|externalItemId
    |link:http://php.net/string[string^]
    a|The external variation ID
|noEditByCustomer
    |link:http://php.net/bool[bool^]
    a|Shows whether the item was edited by the customer
|costCenterId
    |link:http://php.net/int[int^]
    a|
|giftPackageForRowId
    |link:http://php.net/int[int^]
    a|
|position
    |link:http://php.net/int[int^]
    a|The item position
|size
    |link:http://php.net/string[string^]
    a|The item size
|shippingProfileId
    |link:http://php.net/int[int^]
    a|The ID of the shipping profile
|referrerId
    |link:http://php.net/float[float^]
    a|The ID of the order referrer
|deliveryDate
    |link:http://php.net/string[string^]
    a|The delivery date
|categoryId
    |link:http://php.net/int[int^]
    a|The ID of the item category
|reservationDatetime
    |link:http://php.net/int[int^]
    a|
|variationId
    |link:http://php.net/int[int^]
    a|The ID of the item variation
|bundleVariationId
    |link:http://php.net/int[int^]
    a|The ID of the item bundle type
|createdAt
    |link:http://php.net/string[string^]
    a|The date that the shopping cart was created
|updatedAt
    |link:http://php.net/string[string^]
    a|The date that the shopping cart was updated last
|attributeTotalMarkup
    |link:http://php.net/float[float^]
    a|attribute total markup
|basketItemOrderParams
    |link:http://php.net/array[array^]
    a|Array of BasketItemParams
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[basket_models_basketitemparams]]
==== BasketItemParams

The basket item params model



===== Namespace

`Plenty\Modules\Basket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|type
    |link:http://php.net/string[string^]
    a|
|name
    |link:http://php.net/string[string^]
    a|
|value
    |link:http://php.net/string[string^]
    a|
|basketItemId
    |link:http://php.net/int[int^]
    a|
|propertyId
    |link:http://php.net/int[int^]
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.

[[basket_events]]
== Events

[[basket_events_basket]]
===  Basket
[[basket_basket_afterbasketchanged]]
==== AfterBasketChanged

The event is triggered after the shopping cart is changed.



===== Namespace

`Plenty\Modules\Basket\Events\Basket`






===== Methods

[source%nowrap, php]
----

public hasValidCoupon():bool

----









[source%nowrap, php]
----

public getCouponValidationError():void

----









[source%nowrap, php]
----

public setHasValidCoupon($hasValidCoupon, $couponValidationError = null):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$hasValidCoupon`
|link:http://php.net/bool[bool^]
a|Flag that indicates if a valid coupon has been used.

a|`$couponValidationError`
|        xref:Miscellaneous.adoc#miscellaneous_exceptions_validationexception[`ValidationException`]
a|Validation errors indicating the reasons for an invalid coupon.
|===


[source%nowrap, php]
----

public getBasket():Plenty\Modules\Basket\Models\Basket

----




====== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]




[source%nowrap, php]
----

public getLocationId():int

----









[source%nowrap, php]
----

public setLocationId($locationId):Plenty\Modules\Basket\Events\Basket

----




====== *Return type:*        xref:Basket.adoc#basket_events_basket[`Basket`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$locationId`
|link:http://php.net/int[int^]
a|The ID of the location
|===


[source%nowrap, php]
----

public getInvoiceAddress():Plenty\Modules\Account\Address\Models\Address

----




====== *Return type:*        xref:Account.adoc#account_models_address[`Address`]




[source%nowrap, php]
----

public setInvoiceAddress($invoiceAddress):Plenty\Modules\Basket\Events\Basket

----




====== *Return type:*        xref:Basket.adoc#basket_events_basket[`Basket`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$invoiceAddress`
|        xref:Account.adoc#account_models_address[`Address`]
a|The invoice address
|===


[source%nowrap, php]
----

public getMaxFsk():int

----









[source%nowrap, php]
----

public setMaxFsk($maxFsk):Plenty\Modules\Basket\Events\Basket

----




====== *Return type:*        xref:Basket.adoc#basket_events_basket[`Basket`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$maxFsk`
|link:http://php.net/int[int^]
a|The highest value for age restriction of an item in the shopping cart
|===


[source%nowrap, php]
----

public getShippingCosts():float

----









[source%nowrap, php]
----

public setShippingCosts($shippingCosts):Plenty\Modules\Basket\Events\Basket

----




====== *Return type:*        xref:Basket.adoc#basket_events_basket[`Basket`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$shippingCosts`
|link:http://php.net/float[float^]
a|The shipping costs of the shopping cart
|===



[[basket_basket_afterbasketcreate]]
==== AfterBasketCreate

The event is triggered after the shopping cart is created.



===== Namespace

`Plenty\Modules\Basket\Events\Basket`






===== Methods

[source%nowrap, php]
----

public getBasket():Plenty\Modules\Basket\Models\Basket

----




====== *Return type:*        xref:Basket.adoc#basket_models_basket[`Basket`]




[[basket_events_basketitem]]
===  BasketItem
[[basket_basketitem_afterbasketitemadd]]
==== AfterBasketItemAdd

The event is triggered after an item is added to the shopping cart.



===== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






===== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----




====== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]





[[basket_basketitem_afterbasketitemremove]]
==== AfterBasketItemRemove

The event is triggered after an item is deleted from the shopping cart.



===== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






===== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----




====== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]





[[basket_basketitem_afterbasketitemupdate]]
==== AfterBasketItemUpdate

The event is triggered after an item in the shopping cart is updated.



===== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






===== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----




====== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]





[[basket_basketitem_basketitemevent]]
==== BasketItemEvent

BasketItemEvent



===== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






===== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----




====== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]





[[basket_basketitem_beforebasketitemadd]]
==== BeforeBasketItemAdd

The event is triggered before an item is created in the shopping cart.



===== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






===== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----




====== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]





[[basket_basketitem_beforebasketitemremove]]
==== BeforeBasketItemRemove

The event is triggered before an item is deleted from the shopping cart.



===== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






===== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----




====== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]





[[basket_basketitem_beforebasketitemupdate]]
==== BeforeBasketItemUpdate

The event is triggered before an item in the shopping cart is updated.



===== Namespace

`Plenty\Modules\Basket\Events\BasketItem`






===== Methods

[source%nowrap, php]
----

public getBasketItem():Plenty\Modules\Basket\Models\BasketItem

----




====== *Return type:*        xref:Basket.adoc#basket_models_basketitem[`BasketItem`]




