

[[bi_keyfigure]]
== KeyFigure

[[bi_keyfigure_contracts]]
===  Contracts
[[bi_contracts_keyfigureresultrepositorycontract]]
==== KeyFigureResultRepositoryContract

This interface allows you to search for key figures results.



===== Namespace

`Plenty\Modules\BI\KeyFigure\Contracts`






===== Methods

[source%nowrap, php]
----

public searchKeyFigureResults($searchRequests):Plenty\Modules\BI\KeyFigure\Models\KeyFigureResultSearchResponse

----

    


====== *Return type:*        xref:Bi.adoc#bi_models_keyfigureresultsearchresponse[`KeyFigureResultSearchResponse`]


Search for key figure calculation results

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Bi.adoc#bi_models_keyfiguresearchrequests[`KeyFigureSearchRequests`]
a|`$searchRequests`
a|Several key figure search requests
|===


[[bi_keyfigure_models]]
===  Models
[[bi_models_keyfigureconfig]]
==== KeyFigureConfig

The key figure config model represents the configuration of a key figure.



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|id
    a|Id of this configuration
|link:http://php.net/string[string^]
    a|plentyIdHash
    a|The plentymarkets system id hash
|link:http://php.net/string[string^]
    a|keyFigure
    a|Key figure identifier
|link:http://php.net/string[string^]
    a|keyFigureCaption
    a|Key figure caption
|link:http://php.net/string[string^]
    a|keyFigureName
    a|User defined name
|        xref:Bi.adoc#bi_models_keyfigurefilter[`KeyFigureFilter`]
    a|filter
    a|Filter for calculating this key figure
|        xref:Bi.adoc#bi_models_keyfiguretarget[`KeyFigureTarget`]
    a|target
    a|Contains the target figures
|        xref:Bi.adoc#bi_models_keyfiguremeta[`KeyFigureMeta`]
    a|meta
    a|Additional data
|link:http://php.net/string[string^]
    a|updatedAt
    a|Time of last change
|link:http://php.net/string[string^]
    a|createdAt
    a|Time of creation
|link:http://php.net/string[string^]
    a|externalId
    a|Identifier to assign the model
|link:http://php.net/array[array^]
    a|dimensions
    a|List of existing dimensions
|link:http://php.net/array[array^]
    a|dimensionValues
    a|List of dimension values
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_keyfigurefilter]]
==== KeyFigureFilter

The key figure filter holds configured filters for a key figure calculation.



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/array[array^]
    a|dataFilters
    a|Filters in notation ['filterName' => ['operator' => 'eq', 'value' => 123]]
|link:http://php.net/string[string^]
    a|calculation
    a|Selected calculation method
|link:http://php.net/string[string^]
    a|dimension
    a|Data group to group the result
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_keyfiguremeta]]
==== KeyFigureMeta

The key figure meta holds additional data.



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|comment
    a|User comment
|link:http://php.net/int[int^]
    a|creatorUserId
    a|Id of the user who created this key figure
|link:http://php.net/string[string^]
    a|creatorRealName
    a|Real name of the user who created this key figure
|link:http://php.net/bool[bool^]
    a|isLimitEditing
    a|If true, then the key figure may only be edited by the creator
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_keyfigureresult]]
==== KeyFigureResult

Represents a key figure result



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|id
    a|Primary key
|link:http://php.net/string[string^]
    a|plentyIdHash
    a|System ID hash
|link:http://php.net/string[string^]
    a|configId
    a|Id of the configuration of the key figure, followed by the calculation interval and  The usage should be the exception, so this field usually resembles the content of idInterval.
|link:http://php.net/string[string^]
    a|scaleBasis
    a|Time reference value of the key figure result.
|link:http://php.net/string[string^]
    a|dimension
    a|The name of the dimension.
|link:http://php.net/string[string^]
    a|interval
    a|Calculation interval.
|link:http://php.net/float[float^]
    a|primaryResult
    a|The actual calculation result of the primary result data field.
|link:http://php.net/string[string^]
    a|furtherResult
    a|If further results were calculated in addition to the primary result, these are included in this field as a JSON object. The fields are defined in the KeyFigure class.
|link:http://php.net/string[string^]
    a|calculatedAt
    a|Date of calculation.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_keyfigureresultresponse]]
==== KeyFigureResultResponse

The model represent a key figure result in condensed form to the presentation.



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|scaleBasis
    a|Time reference value of the key figure result. The structure of scaleBasis depends on the time interval of the key figure. At the interval day is the structure: YYYYMMDD. For the interval month: YYYYMMM. In the case of year: YYYYY.
|link:http://php.net/string[string^]
    a|dimension
    a|The name of the dimension.
|link:http://php.net/float[float^]
    a|primaryResult
    a|The actual calculation result of the primary result data field.
|link:http://php.net/string[string^]
    a|furtherResult
    a|If further results were calculated in addition to the primary result, these are included in this field as a JSON object. The fields are defined in the KeyFigure class.
|link:http://php.net/string[string^]
    a|resultUnit
    a|Unit of the primary result.
|link:http://php.net/float[float^]
    a|target
    a|Key figure target figure.
|link:http://php.net/string[string^]
    a|calculatedAt
    a|Date of calculation.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_keyfigureresultsearchresponse]]
==== KeyFigureResultSearchResponse

The model represent search result of key figure result search.



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/array[array^]
    a|searchResultList
    a|The list of found key figure result search result
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_keyfigureresultsearchresult]]
==== KeyFigureResultSearchResult

The key figure result search result model combine key figure information with key figure search result.



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/array[array^]
    a|keyFigureResults
    a|Key figure result list
|link:http://php.net/string[string^]
    a|interval
    a|Calculation interval.
|link:http://php.net/string[string^]
    a|searchId
    a|Identification string to assign the result
|link:http://php.net/string[string^]
    a|keyFigure
    a|Key figure identifier
|link:http://php.net/array[array^]
    a|error
    a|Error occurred
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_keyfiguresearchrequest]]
==== KeyFigureSearchRequest

The model holds filter information for a search query for key figures.



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|configId
    a|Filter that restricts the search result to key figure results of key figure configuration id. The id of the key figure configuration is mandatory and must be specified, if no value is passed for id.
|link:http://php.net/string[string^]
    a|interval
    a|Time interval in which the result was calculated: day, week, month, quarter, year.
|link:http://php.net/string[string^]
    a|dimension
    a|This field will be removed until 11.2020
|link:http://php.net/array[array^]
    a|dimensions
    a|Filter that restricts the search result to key figure results of one data group. The dimension must be specified.
|link:http://php.net/string[string^]
    a|scaleBasis
    a|Filter restricts the list of results to items with a scale base time during the specified period. For the time interval day, a date or comma separated two dates (format: YYYYMMDD) can be specified. For the time interval week, several comma-separated days (YYYYMMDD) of different weeks can be specified. For the interval month, a comma separated list of months is expected e.g. 2020-01, 2020-02.
|link:http://php.net/bool[bool^]
    a|resultUnit
    a|Return unit of the primary result.
|link:http://php.net/bool[bool^]
    a|target
    a|Return key figure target figure.
|link:http://php.net/bool[bool^]
    a|groupByDimension
    a|Groups the results by dimension
|link:http://php.net/string[string^]
    a|aggregateFunction
    a|Define aggregate (group) function that will operate on key figure results. Default function: sum. Allowed values: sum, avg, count, max, min
|link:http://php.net/int[int^]
    a|itemsPerPage
    a|Limits the number of results listed per page to a specific number. The number of variations to be listed per page must be specified. The default number of results is 12 and the maximum is 100.
|link:http://php.net/int[int^]
    a|page
    a|Number of the requested page, default value: 1
|link:http://php.net/string[string^]
    a|scaleBasisSortOrder
    a|Sort the results using scaleBasis if a sort order has been defined, possible values are: asc, desc.
|link:http://php.net/string[string^]
    a|primaryResultSortOrder
    a|Sort the results using primaryResult if a sort order has been defined, possible values are: asc, desc.
|link:http://php.net/string[string^]
    a|searchId
    a|Identification string to assign the result
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_keyfiguresearchrequests]]
==== KeyFigureSearchRequests

The model represent several key figure search requests.



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/array[array^]
    a|searchRequests
    a|The list of key figure search requests
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_keyfiguretarget]]
==== KeyFigureTarget

The key figure target day model contains the target figures for each weekday, week, month, quarter and year, which were stored for a key figure configuration



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/float[float^]
    a|d1
    a|Target value for Monday
|link:http://php.net/float[float^]
    a|d2
    a|Target value for Tuesday
|link:http://php.net/float[float^]
    a|d3
    a|Target value for Wednesday
|link:http://php.net/float[float^]
    a|d4
    a|Target value for Thursday
|link:http://php.net/float[float^]
    a|d5
    a|Target value for Friday
|link:http://php.net/float[float^]
    a|d6
    a|Target value for Saturday
|link:http://php.net/float[float^]
    a|d7
    a|Target value for Sunday
|link:http://php.net/float[float^]
    a|w
    a|Target value for weeks
|link:http://php.net/float[float^]
    a|m1
    a|Target value for January
|link:http://php.net/float[float^]
    a|m2
    a|Target value for February
|link:http://php.net/float[float^]
    a|m3
    a|Target value for March
|link:http://php.net/float[float^]
    a|m4
    a|Target value for April
|link:http://php.net/float[float^]
    a|m5
    a|Target value for May
|link:http://php.net/float[float^]
    a|m6
    a|Target value for June
|link:http://php.net/float[float^]
    a|m7
    a|Target value for July
|link:http://php.net/float[float^]
    a|m8
    a|Target value for August
|link:http://php.net/float[float^]
    a|m9
    a|Target value for September
|link:http://php.net/float[float^]
    a|m10
    a|Target value for October
|link:http://php.net/float[float^]
    a|m11
    a|Target value for November
|link:http://php.net/float[float^]
    a|m12
    a|Target value for December
|link:http://php.net/float[float^]
    a|q1
    a|Target value for first quarter
|link:http://php.net/float[float^]
    a|q2
    a|Target value for second quarter
|link:http://php.net/float[float^]
    a|q3
    a|Target value for third quarter
|link:http://php.net/float[float^]
    a|q4
    a|Target value for fourth quarter
|link:http://php.net/float[float^]
    a|yl
    a|Target value for last year
|link:http://php.net/float[float^]
    a|y
    a|Target value for this year
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_keyfiguretemplate]]
==== KeyFigureTemplate

The key figure template model contains preview data of a key figure template



===== Namespace

`Plenty\Modules\BI\KeyFigure\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|keyFigureName
    a|User defined name
|link:http://php.net/string[string^]
    a|keyFigure
    a|Key figure identifier
|link:http://php.net/string[string^]
    a|className
    a|Template class name
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[bi_rawdata]]
== RawData

[[bi_rawdata_contracts]]
===  Contracts
[[bi_contracts_rawdatarepositorycontract]]
==== RawDataRepositoryContract

This interface allows you to get a list of generated raw data files



===== Namespace

`Plenty\Modules\BI\RawData\Contracts`






===== Methods

[source%nowrap, php]
----

public searchRawData($dataName, $createdAtTimestamp, $processStatus, $itemsPerPage = 20, $sortOrder = &quot;asc&quot;, $page = 1):Plenty\Modules\BI\RawData\Models\RawDataSearchResult

----

    


====== *Return type:*        xref:Bi.adoc#bi_models_rawdatasearchresult[`RawDataSearchResult`]


Get list of raw data. Valid filter combinations: (dataName), (dataName &amp; processStatus), (createdAtTimestamp)

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$dataName`
a|Filter that restricts the search result to raw data files.

|link:http://php.net/int[int^]
a|`$createdAtTimestamp`
a|Timestamp from when daily generated raw data are to be filtered. The maximum distance may not exceed one year.

|link:http://php.net/string[string^]
a|`$processStatus`
a|Process status after which filtering is to take place

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of raw data files to be returned. The default number of files is 20 and the maximum is 100.

|link:http://php.net/string[string^]
a|`$sortOrder`
a|Defines the sort order, possible values are: asc, desc. With simultaneous filtering to dataName, only the current result is sorted.

|link:http://php.net/int[int^]
a|`$page`
a|
|===


[source%nowrap, php]
----

public getRawDataFile($path):void

----

    





Get a raw data file from the storage, the storage path of the file must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$path`
a|The raw data file path
|===


[source%nowrap, php]
----

public deleteRawData($dataName, $primaryIds):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$dataName`
a|

|link:http://php.net/array[array^]
a|`$primaryIds`
a|
|===


[source%nowrap, php]
----

public getRawDataCreatorModels():array

----

    





Get list of all raw data creators

[source%nowrap, php]
----

public getRawDataConfigs():Plenty\Modules\BI\RawData\Models\RawDataConfigs

----

    


====== *Return type:*        xref:Bi.adoc#bi_models_rawdataconfigs[`RawDataConfigs`]


Returns list of all saved configurations

[source%nowrap, php]
----

public updateRawDataConfigs($data):Plenty\Modules\BI\RawData\Models\RawDataConfigs

----

    


====== *Return type:*        xref:Bi.adoc#bi_models_rawdataconfigs[`RawDataConfigs`]


Resets all saved raw data configurations with given data

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The configs data
|===


[[bi_rawdata_models]]
===  Models
[[bi_models_rawdataconfig]]
==== RawDataConfig

The BI raw data config model



===== Namespace

`Plenty\Modules\BI\RawData\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|dataName
    a|The raw data name
|link:http://php.net/int[int^]
    a|active
    a|If active, raw data is generated daily
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_rawdataconfigs]]
==== RawDataConfigs

List of all saved raw data configurations



===== Namespace

`Plenty\Modules\BI\RawData\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|plentyIdHash
    a|The plentymarkets system id hash
|link:http://php.net/array[array^]
    a|configs
    a|List of all saved configurations
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_rawdatacreator]]
==== RawDataCreator

The BI raw data creator model



===== Namespace

`Plenty\Modules\BI\RawData\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|dataName
    a|Exclusive identifier for this raw data.
|link:http://php.net/string[string^]
    a|fileFormat
    a|File format
|link:http://php.net/int[int^]
    a|limitPage
    a|Number of data rows to be queried maximum per request.
|link:http://php.net/int[int^]
    a|limitDay
    a|Number of data rows to be queried maximum per day.
|link:http://php.net/string[string^]
    a|earliestPossibleDataDate
    a|Earliest possible date from which data should be requested.
|link:http://php.net/int[int^]
    a|deleteRawDataAfterDaysMinimum
    a|Minimum number of days after the generated raw data is deleted
|link:http://php.net/int[int^]
    a|deleteRawDataAfterDaysMaximum
    a|Maximum number of days after the generated raw data is deleted
|link:http://php.net/string[string^]
    a|filterType
    a|Defines how this raw data is filtered.
|link:http://php.net/string[string^]
    a|dataUpdatedAtColumnName
    a|Name of the column that contains the date of the last change to a data row.
|link:http://php.net/bool[bool^]
    a|defaultActive
    a|If true, then these raw data are collected independently of the user configuration.
|link:http://php.net/string[string^]
    a|interval
    a|Interval in which this creator runs through
|link:http://php.net/bool[bool^]
    a|shouldProcess
    a|Internal value, indicates whether this data should be transferred to the data warehouse database
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_rawdatafile]]
==== RawDataFile

The BI raw model



===== Namespace

`Plenty\Modules\BI\RawData\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|id
    a|The raw data id
|link:http://php.net/string[string^]
    a|plentyIdHash
    a|The plentymarkets system id hash
|link:http://php.net/string[string^]
    a|dataName
    a|The raw data name
|link:http://php.net/string[string^]
    a|processStatus
    a|Status of data warehouse processing
|link:http://php.net/int[int^]
    a|shouldProcess
    a|Specifies whether this file should be transferred to the data warehouse
|link:http://php.net/string[string^]
    a|path
    a|Storage path to raw data file
|link:http://php.net/string[string^]
    a|createdAt
    a|Creation time of this raw data file
|link:http://php.net/string[string^]
    a|dataCreatedAt
    a|Creation date of the data
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[bi_models_rawdatasearchresult]]
==== RawDataSearchResult

The BI raw data search result model



===== Namespace

`Plenty\Modules\BI\RawData\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|after
    a|The last evaluated key as base64, provide that as the starting point for the next query (pagination).
|link:http://php.net/array[array^]
    a|searchResult
    a|The raw data search result
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

