:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[blog_blog]]
== Blog

[[blog_blog_contracts]]
===  Contracts
[[blog_contracts_blogpostrepositorycontract]]
==== BlogPostRepositoryContract

This interface provides methods to create, read, list, update and delete blog posts



===== Namespace

`Plenty\Modules\Blog\Contracts`






===== Methods

[source%nowrap, php]
----

public createPost($data):Plenty\Modules\Blog\Models\BlogPost // <1>

----


    
Creates a new blog post.


===== Return type
    
<1> link:blog#blog_models_blogpost[BlogPost^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|Blog post data
|===


[source%nowrap, php]
----

public getPost($blogPostId):Plenty\Modules\Blog\Models\BlogPost // <1>

----


    
Get a single blog post by its ID


===== Return type
    
<1> link:blog#blog_models_blogpost[BlogPost^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$blogPostId`
|
|===


[source%nowrap, php]
----

public listPosts($page = 1, $itemsPerPage = 50, $filters = []):array // <1>

----


    
Lists all blog posts for current plenty ID.


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
|

|link:http://php.net/array[array^]
a|`$filters`
|
|===


[source%nowrap, php]
----

public updatePost($data, $blogPostId):Plenty\Modules\Blog\Models\BlogPost // <1>

----


    
Update data for a post


===== Return type
    
<1> link:blog#blog_models_blogpost[BlogPost^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|

|link:http://php.net/string[string^]
a|`$blogPostId`
|
|===


[source%nowrap, php]
----

public deletePost($blogPostId):void // <1>

----


    
Delete a single blog post by its ID


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$blogPostId`
|
|===


[source%nowrap, php]
----

public migratePosts($data = []):void // <1>

----


    
Migrate old posts to new


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getOldPostById($id):void // <1>

----


    
Get old blog post by its ID


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
|
|===


[source%nowrap, php]
----

public clearCriteria():void // <1>

----


    
Resets all Criteria filters by creating a new instance of the builder object.


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public applyCriteriaFromFilters():void // <1>

----


    
Applies criteria classes to the current repository.


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public setFilters($filters = []):void // <1>

----


    
Sets the filter array.


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
|
|===


[source%nowrap, php]
----

public getFilters():void // <1>

----


    
Returns the filter array.


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getConditions():void // <1>

----


    
Returns a collection of parsed filters as Condition object


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public clearFilters():void // <1>

----


    
Clears the filter array.


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[[blog_blog_models]]
===  Models
[[blog_models_blogpost]]
==== BlogPost

The blog post model.



===== Namespace

`Plenty\Modules\Blog\Models`





.Properties
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    |id
    |
|link:http://php.net/string[string^]
    |plentyIdHash
    |
|link:http://php.net/string[string^]
    |data
    |
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----


    
Returns this model as an array.



[[blog_blog_services]]
===  Services
[[blog_services_blogpluginservice]]
==== BlogPluginService

Blog plugin service



===== Namespace

`Plenty\Modules\Blog\Services`






===== Methods

[source%nowrap, php]
----

public getPluginSetIdFromConfig():void // <1>

----


    
Get plugin set ID


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public findCategoryByUrl($level1, $level2 = null, $level3 = null, $level4 = null, $level5 = null, $level6 = null, $webstoreId = null, $lang = null):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$level1`
|

|link:http://php.net/string[string^]
a|`$level2`
|

|link:http://php.net/string[string^]
a|`$level3`
|

|link:http://php.net/string[string^]
a|`$level4`
|

|link:http://php.net/string[string^]
a|`$level5`
|

|link:http://php.net/string[string^]
a|`$level6`
|

|link:http://php.net/int[int^]
a|`$webstoreId`
|

|link:http://php.net/string[string^]
a|`$lang`
|
|===


