:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[board_board]]
== Board

[[board_board_contracts]]
===  Contracts
[[board_contracts_boardcolumnrepositorycontract]]
==== BoardColumnRepositoryContract

The BoardColumnRepositoryContract is the interface for the board column repository. This interface provides methods to access, create, update or delete columns.



===== Namespace

`Plenty\Modules\Board\Contracts`






===== Methods

[source%nowrap, php]
[#list]
----

public list($boardId):Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Lists all columns assigned to a specific board.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board to get columns for
|===


[source%nowrap, php]
[#create]
----

public create($boardId, $data):Plenty\Modules\Board\Models\BoardColumn

----




====== *Return type:*        xref:Board.adoc#board_models_boardcolumn[`BoardColumn`]


Creates a new column and assigns it to a specific board.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board to assign the new column to

a|`$data`
|link:http://php.net/array[array^]
a|The data of the new column
|===


[source%nowrap, php]
[#update]
----

public update($boardId, $columnId, $data):Plenty\Modules\Board\Models\BoardColumn

----




====== *Return type:*        xref:Board.adoc#board_models_boardcolumn[`BoardColumn`]


Updates a specific column.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board the column belongs to

a|`$columnId`
|link:http://php.net/string[string^]
a|The ID of the column to be updated

a|`$data`
|link:http://php.net/array[array^]
a|The data to assign to the specified column
|===


[source%nowrap, php]
[#copy]
----

public copy($boardId, $columnId):Plenty\Modules\Board\Models\BoardColumn

----




====== *Return type:*        xref:Board.adoc#board_models_boardcolumn[`BoardColumn`]


Copies a column and all its tasks.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board the column belongs to

a|`$columnId`
|link:http://php.net/string[string^]
a|The ID of the column to be copied
|===


[source%nowrap, php]
[#updateposition]
----

public updatePosition($boardId, $columnId, $newPosition):bool

----







Updates the position of a specified column. This will update the position of all affected columns on the same board too.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board the column belongs to

a|`$columnId`
|link:http://php.net/string[string^]
a|The ID of the column to update the position for

a|`$newPosition`
|link:http://php.net/int[int^]
a|The new position
|===


[source%nowrap, php]
[#delete]
----

public delete($boardId, $columnId):bool

----







Deletes a specific column.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board the column belongs to

a|`$columnId`
|link:http://php.net/string[string^]
a|The ID of the column to be deleted
|===



[[board_contracts_boardrepositorycontract]]
==== BoardRepositoryContract

The BoardRepositoryContract is the interface for the board repository. This interface provides all methods to access, create, update or delete boards.



===== Namespace

`Plenty\Modules\Board\Contracts`






===== Methods

[source%nowrap, php]
[#list]
----

public list($columns = []):Illuminate\Database\Eloquent\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Lists all boards.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$columns`
|link:http://php.net/array[array^]
a|Fields to load for each board
|===


[source%nowrap, php]
[#get]
----

public get($boardId, $tasksPerPage = 20):Plenty\Modules\Board\Models\Board

----




====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]


Returns a single board.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board to get

a|`$tasksPerPage`
|link:http://php.net/int[int^]
a|The maximum number of tasks to load for each column
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Board\Models\Board

----




====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]


Creates a new board.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The data of the new board
|===


[source%nowrap, php]
[#update]
----

public update($boardId, $data):Plenty\Modules\Board\Models\Board

----




====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]


Updates a board.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board to be updated

a|`$data`
|link:http://php.net/array[array^]
a|New data to be assigned to the board if it exists
|===


[source%nowrap, php]
[#copy]
----

public copy($boardId):Plenty\Modules\Board\Models\Board

----




====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]


Copies a board and all its columns.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board to be copied
|===


[source%nowrap, php]
[#updatetaskscount]
----

public updateTasksCount($boardId):bool

----







Updates the tasks count value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board to update the tasks count
|===


[source%nowrap, php]
[#delete]
----

public delete($boardId):bool

----







Deletes a board. Returns `true` if the deletion was successful.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board to be deleted
|===



[[board_contracts_boardtaskreferencerepositorycontract]]
==== BoardTaskReferenceRepositoryContract

The BoardTaskReferenceRepositoryContract is the interface for the board task reference repository. This interface provides methods to create or delete references from tasks to contacts or tickets.



===== Namespace

`Plenty\Modules\Board\Contracts`






===== Methods

[source%nowrap, php]
[#create]
----

public create($taskId, $referenceValue):Plenty\Modules\Board\Models\BoardTaskReference

----




====== *Return type:*        xref:Board.adoc#board_models_boardtaskreference[`BoardTaskReference`]


Creates a new reference to a given task. A reference may either point to a contact or to a ticket.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$taskId`
|link:http://php.net/string[string^]
a|The ID of the task to create a reference for

a|`$referenceValue`
|link:http://php.net/string[string^]
a|Reference type followed by foreign ID of the referenced object. Syntax: TYPE-ID Example: user-123456 Types: user,ticket,contact,order,item
|===


[source%nowrap, php]
[#delete]
----

public delete($referenceId):bool

----







Deletes a specific reference.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$referenceId`
|link:http://php.net/string[string^]
a|The ID of the reference
|===


[source%nowrap, php]
[#checkreferencekey]
----

public checkReferenceKey($referenceType, $referenceKey):bool

----







Checks whether the reference key for the given reference type exists or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$referenceType`
|link:http://php.net/string[string^]
a|The reference type (one of 'contact', 'order', 'item', 'ticket' or 'user')

a|`$referenceKey`
|link:http://php.net/int[int^]
a|The ID of the corresponding reference type
|===



[[board_contracts_boardtaskrepositorycontract]]
==== BoardTaskRepositoryContract

The BoardTaskRepositoryContract is the interface for the board task repository. This interface provides methods to access, create, update or delete tasks.



===== Namespace

`Plenty\Modules\Board\Contracts`






===== Methods

[source%nowrap, php]
[#list]
----

public list($columnId, $startAt, $tasksPerPage = 20, $columns = []):Illuminate\Database\Eloquent\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Lists tasks for a specific column. Will return at most 20 tasks starting at defined task.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$columnId`
|link:http://php.net/string[string^]
a|The ID of the column to get tasks for

a|`$startAt`
|link:http://php.net/int[int^]
a|The position of a task to start listing at

a|`$tasksPerPage`
|link:http://php.net/int[int^]
a|The number of tasks to get per page

a|`$columns`
|link:http://php.net/array[array^]
a|Fields to load for each task
|===


[source%nowrap, php]
[#create]
----

public create($boardId, $columnId, $data):Plenty\Modules\Board\Models\BoardTask

----




====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]


Creates a new task and assigns it to a specified column.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board the column belongs to

a|`$columnId`
|link:http://php.net/string[string^]
a|The ID of the column to assign the created task to

a|`$data`
|link:http://php.net/array[array^]
a|The data of the new task
|===


[source%nowrap, php]
[#copy]
----

public copy($boardId, $columnId, $taskId):Plenty\Modules\Board\Models\BoardTask

----




====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]


Copies the task with all references.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board the column belongs to

a|`$columnId`
|link:http://php.net/string[string^]
a|The ID of the column to assign the copied task to

a|`$taskId`
|link:http://php.net/string[string^]
a|The ID of the task to be copied
|===


[source%nowrap, php]
[#get]
----

public get($taskId):Plenty\Modules\Board\Models\BoardTask

----




====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]


Returns a task for a given ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$taskId`
|link:http://php.net/string[string^]
a|The ID of the task
|===


[source%nowrap, php]
[#update]
----

public update($boardId, $columnId, $taskId, $data):Plenty\Modules\Board\Models\BoardTask

----




====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]


Updates a specified task.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board the column belongs to

a|`$columnId`
|link:http://php.net/string[string^]
a|The ID of the column the task belongs to

a|`$taskId`
|link:http://php.net/string[string^]
a|The ID of the task to be updated

a|`$data`
|link:http://php.net/array[array^]
a|Data to set at the task
|===


[source%nowrap, php]
[#addreference]
----

public addReference($boardTaskReference):bool

----







Adds a task reference to a task object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardTaskReference`
|        xref:Board.adoc#board_models_boardtaskreference[`BoardTaskReference`]
a|The board task reference
|===


[source%nowrap, php]
[#removereference]
----

public removeReference($boardTaskReference):bool

----







Removes a task reference from a task object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardTaskReference`
|        xref:Board.adoc#board_models_boardtaskreference[`BoardTaskReference`]
a|The board task reference
|===


[source%nowrap, php]
[#updateposition]
----

public updatePosition($taskId, $newColumnId, $newPosition):int

----







Updates the position of a specified task. Will also update the position of all following tasks in the same column.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$taskId`
|link:http://php.net/string[string^]
a|The ID of the task to update the position for

a|`$newColumnId`
|link:http://php.net/string[string^]
a|The ID of the column the task now belongs to

a|`$newPosition`
|link:http://php.net/int[int^]
a|The new position
|===


[source%nowrap, php]
[#delete]
----

public delete($taskId):bool

----







Deletes a specified task.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$taskId`
|link:http://php.net/string[string^]
a|The ID of the task to be deleted
|===


[source%nowrap, php]
[#deletebycolumn]
----

public deleteByColumn($boardId, $columnId):bool

----







Deletes all tasks of a column.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board the column belongs to

a|`$columnId`
|link:http://php.net/string[string^]
a|The ID of the column the task belongs to
|===


[source%nowrap, php]
[#allbycolumnid]
----

public allByColumnId($columnId, $referenceValue = null, $columns = []):void

----







Gets all tasks for the given column ID having a reference with the given reference value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$columnId`
|link:http://php.net/string[string^]
a|The ID of the column

a|`$referenceValue`
|link:http://php.net/string[string^]
a|The reference value that has to be contained in the task. Can be NULL.

a|`$columns`
|link:http://php.net/array[array^]
a|The attributes of the task to load
|===


[source%nowrap, php]
[#allbyboardid]
----

public allByBoardId($boardId, $referenceValue = null, $columns = []):void

----







Gets all tasks for the given column ID having a reference with the given reference value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$boardId`
|link:http://php.net/string[string^]
a|The ID of the board

a|`$referenceValue`
|link:http://php.net/string[string^]
a|The reference value that has to be contained in the task. Can be NULL.

a|`$columns`
|link:http://php.net/array[array^]
a|The attributes of the task to load
|===


[[board_board_events]]
===  Events
[[board_events_afterboardcolumntasksdeleted]]
==== AfterBoardColumnTasksDeleted

This event will be triggered, after all tasks of a column were deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
[#getboardid]
----

public getBoardId():string

----









[source%nowrap, php]
[#getcolumnid]
----

public getColumnId():string

----









[source%nowrap, php]
[#getdeletedtaskidlist]
----

public getDeletedTaskIdList():array

----










[[board_events_afterboardtaskcreated]]
==== AfterBoardTaskCreated

This event will be triggered, when a board task was created.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
[#getboardtask]
----

public getBoardTask():Plenty\Modules\Board\Models\BoardTask

----




====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]





[[board_events_afterboardtaskdeleted]]
==== AfterBoardTaskDeleted

This event will be triggered, when a single board task was deleted. It won&#039;t be triggered, if a board column was deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
[#getboardtask]
----

public getBoardTask():Plenty\Modules\Board\Models\BoardTask

----




====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]





[[board_events_afterboardtaskreferencecreated]]
==== AfterBoardTaskReferenceCreated

This event will be triggered, after a task reference was created.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
[#getboardtaskreference]
----

public getBoardTaskReference():Plenty\Modules\Board\Models\BoardTaskReference

----




====== *Return type:*        xref:Board.adoc#board_models_boardtaskreference[`BoardTaskReference`]





[[board_events_afterboardtaskreferencedeleted]]
==== AfterBoardTaskReferenceDeleted

This event will be triggered, after a task reference was deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
[#getboardtaskreference]
----

public getBoardTaskReference():Plenty\Modules\Board\Models\BoardTaskReference

----




====== *Return type:*        xref:Board.adoc#board_models_boardtaskreference[`BoardTaskReference`]





[[board_events_beforeboardcolumndeleted]]
==== BeforeBoardColumnDeleted

This event will be triggered, before a board column will be deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
[#getboard]
----

public getBoard():Plenty\Modules\Board\Models\Board

----




====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]




[source%nowrap, php]
[#getcolumnid]
----

public getColumnId():string

----










[[board_events_beforeboarddeleted]]
==== BeforeBoardDeleted

This event will be triggered, before a board will be deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
[#getboard]
----

public getBoard():Plenty\Modules\Board\Models\Board

----




====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]





[[board_events_beforeboardtaskdeleted]]
==== BeforeBoardTaskDeleted

This event will be triggered, before a single board task was deleted. It won&#039;t be triggered, if a board column will be deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
[#getboardtask]
----

public getBoardTask():Plenty\Modules\Board\Models\BoardTask

----




====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]




[[board_board_models]]
===  Models
[[board_models_board]]
==== Board

The board model.



===== Namespace

`Plenty\Modules\Board\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/string[string^]
    a|The ID of the board
|boardName
    |link:http://php.net/string[string^]
    a|The name of the board
|boardColumns
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|The columns of the board
|columnsCount
    |link:http://php.net/int[int^]
    a|The number of columns
|tasksCount
    |link:http://php.net/int[int^]
    a|The number of tasks
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[board_models_boardcolumn]]
==== BoardColumn

The board column model.



===== Namespace

`Plenty\Modules\Board\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/string[string^]
    a|The ID of the board column
|boardId
    |link:http://php.net/string[string^]
    a|The ID of the board
|columnName
    |link:http://php.net/string[string^]
    a|The name of the column
|position
    |link:http://php.net/int[int^]
    a|The position
|tasks
    |
    a|The tasks
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[board_models_boardtask]]
==== BoardTask

The board task model.



===== Namespace

`Plenty\Modules\Board\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/string[string^]
    a|The ID of the board task
|taskName
    |link:http://php.net/string[string^]
    a|The name of the task
|description
    |link:http://php.net/string[string^]
    a|The description of the task
|position
    |link:http://php.net/int[int^]
    a|The position of the task
|columnId
    |link:http://php.net/string[string^]
    a|The ID of the column
|boardId
    |link:http://php.net/string[string^]
    a|The ID of the board
|tags
    |
    a|
|references
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[board_models_boardtaskreference]]
==== BoardTaskReference

The task reference model.



===== Namespace

`Plenty\Modules\Board\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/string[string^]
    a|The ID of the board task reference
|taskId
    |link:http://php.net/string[string^]
    a|The ID of the task to create a reference for
|referenceValue
    |link:http://php.net/string[string^]
    a|Reference type followed by foreign ID of the referenced object. Syntax: TYPE-ID Example: user-123456 Types: user,ticket,contact,order,item
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

