

[[board_board]]
== Board

[[board_board_contracts]]
===  Contracts
[[board_contracts_boardcolumnrepositorycontract]]
==== BoardColumnRepositoryContract

The BoardColumnRepositoryContract is the interface for the board column repository. This interface provides methods to access, create, update or delete columns.



===== Namespace

`Plenty\Modules\Board\Contracts`






===== Methods

[source%nowrap, php]
----

public list($boardId):Illuminate\Support\Collection

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Lists all columns assigned to a specific board.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board to get columns for
|===


[source%nowrap, php]
----

public create($boardId, $data):Plenty\Modules\Board\Models\BoardColumn

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardcolumn[`BoardColumn`]


Creates a new column and assigns it to a specific board.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board to assign the new column to

|link:http://php.net/array[array^]
a|`$data`
a|The data of the new column
|===


[source%nowrap, php]
----

public update($boardId, $columnId, $data):Plenty\Modules\Board\Models\BoardColumn

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardcolumn[`BoardColumn`]


Updates a specific column.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board the column belongs to

|link:http://php.net/string[string^]
a|`$columnId`
a|The ID of the column to be updated

|link:http://php.net/array[array^]
a|`$data`
a|The data to assign to the specified column
|===


[source%nowrap, php]
----

public copy($boardId, $columnId):Plenty\Modules\Board\Models\BoardColumn

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardcolumn[`BoardColumn`]


Copies a column and all its tasks.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board the column belongs to

|link:http://php.net/string[string^]
a|`$columnId`
a|The ID of the column to be copied
|===


[source%nowrap, php]
----

public updatePosition($boardId, $columnId, $newPosition):bool

----

    





Updates the position of a specified column. This will update the position of all affected columns on the same board too.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board the column belongs to

|link:http://php.net/string[string^]
a|`$columnId`
a|The ID of the column to update the position for

|link:http://php.net/int[int^]
a|`$newPosition`
a|The new position
|===


[source%nowrap, php]
----

public delete($boardId, $columnId):bool

----

    





Deletes a specific column.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board the column belongs to

|link:http://php.net/string[string^]
a|`$columnId`
a|The ID of the column to be deleted
|===



[[board_contracts_boardrepositorycontract]]
==== BoardRepositoryContract

The BoardRepositoryContract is the interface for the board repository. This interface provides all methods to access, create, update or delete boards.



===== Namespace

`Plenty\Modules\Board\Contracts`






===== Methods

[source%nowrap, php]
----

public list($columns = []):Illuminate\Database\Eloquent\Collection

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Lists all boards.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|Fields to load for each board
|===


[source%nowrap, php]
----

public get($boardId, $tasksPerPage = 20):Plenty\Modules\Board\Models\Board

----

    


====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]


Returns a single board.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board to get

|link:http://php.net/int[int^]
a|`$tasksPerPage`
a|The maximum number of tasks to load for each column
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\Board\Models\Board

----

    


====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]


Creates a new board.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The data of the new board
|===


[source%nowrap, php]
----

public update($boardId, $data):Plenty\Modules\Board\Models\Board

----

    


====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]


Updates a board.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board to be updated

|link:http://php.net/array[array^]
a|`$data`
a|New data to be assigned to the board if it exists
|===


[source%nowrap, php]
----

public copy($boardId):Plenty\Modules\Board\Models\Board

----

    


====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]


Copies a board and all its columns.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board to be copied
|===


[source%nowrap, php]
----

public updateTasksCount($boardId):bool

----

    





Updates the tasks count value.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board to update the tasks count
|===


[source%nowrap, php]
----

public delete($boardId):bool

----

    





Deletes a board. Returns `true` if the deletion was successful.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board to be deleted
|===



[[board_contracts_boardtaskreferencerepositorycontract]]
==== BoardTaskReferenceRepositoryContract

The BoardTaskReferenceRepositoryContract is the interface for the board task reference repository. This interface provides methods to create or delete references from tasks to contacts or tickets.



===== Namespace

`Plenty\Modules\Board\Contracts`






===== Methods

[source%nowrap, php]
----

public create($taskId, $referenceValue):Plenty\Modules\Board\Models\BoardTaskReference

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardtaskreference[`BoardTaskReference`]


Creates a new reference to a given task. A reference may either point to a contact or to a ticket.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$taskId`
a|The ID of the task to create a reference for

|link:http://php.net/string[string^]
a|`$referenceValue`
a|Reference type followed by foreign ID of the referenced object. Syntax: TYPE-ID Example: user-123456 Types: user,ticket,contact,order,item
|===


[source%nowrap, php]
----

public delete($referenceId):bool

----

    





Deletes a specific reference.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$referenceId`
a|The ID of the reference
|===


[source%nowrap, php]
----

public checkReferenceKey($referenceType, $referenceKey):bool

----

    





Checks whether the reference key for the given reference type exists or not.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$referenceType`
a|The reference type (one of 'contact', 'order', 'item', 'ticket' or 'user')

|link:http://php.net/int[int^]
a|`$referenceKey`
a|The ID of the corresponding reference type
|===



[[board_contracts_boardtaskrepositorycontract]]
==== BoardTaskRepositoryContract

The BoardTaskRepositoryContract is the interface for the board task repository. This interface provides methods to access, create, update or delete tasks.



===== Namespace

`Plenty\Modules\Board\Contracts`






===== Methods

[source%nowrap, php]
----

public list($columnId, $startAt, $tasksPerPage = 20, $columns = []):Illuminate\Database\Eloquent\Collection

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Lists tasks for a specific column. Will return at most 20 tasks starting at defined task.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$columnId`
a|The ID of the column to get tasks for

|link:http://php.net/int[int^]
a|`$startAt`
a|The position of a task to start listing at

|link:http://php.net/int[int^]
a|`$tasksPerPage`
a|The number of tasks to get per page

|link:http://php.net/array[array^]
a|`$columns`
a|Fields to load for each task
|===


[source%nowrap, php]
----

public create($boardId, $columnId, $data):Plenty\Modules\Board\Models\BoardTask

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]


Creates a new task and assigns it to a specified column.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board the column belongs to

|link:http://php.net/string[string^]
a|`$columnId`
a|The ID of the column to assign the created task to

|link:http://php.net/array[array^]
a|`$data`
a|The data of the new task
|===


[source%nowrap, php]
----

public copy($boardId, $columnId, $taskId):Plenty\Modules\Board\Models\BoardTask

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]


Copies the task with all references.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board the column belongs to

|link:http://php.net/string[string^]
a|`$columnId`
a|The ID of the column to assign the copied task to

|link:http://php.net/string[string^]
a|`$taskId`
a|The ID of the task to be copied
|===


[source%nowrap, php]
----

public get($taskId):Plenty\Modules\Board\Models\BoardTask

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]


Returns a task for a given ID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$taskId`
a|The ID of the task
|===


[source%nowrap, php]
----

public update($boardId, $columnId, $taskId, $data):Plenty\Modules\Board\Models\BoardTask

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]


Updates a specified task.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board the column belongs to

|link:http://php.net/string[string^]
a|`$columnId`
a|The ID of the column the task belongs to

|link:http://php.net/string[string^]
a|`$taskId`
a|The ID of the task to be updated

|link:http://php.net/array[array^]
a|`$data`
a|Data to set at the task
|===


[source%nowrap, php]
----

public addReference($boardTaskReference):bool

----

    





Adds a task reference to a task object.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Board.adoc#board_models_boardtaskreference[`BoardTaskReference`]
a|`$boardTaskReference`
a|The board task reference
|===


[source%nowrap, php]
----

public removeReference($boardTaskReference):bool

----

    





Removes a task reference from a task object.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Board.adoc#board_models_boardtaskreference[`BoardTaskReference`]
a|`$boardTaskReference`
a|The board task reference
|===


[source%nowrap, php]
----

public updatePosition($taskId, $newColumnId, $newPosition):int

----

    





Updates the position of a specified task. Will also update the position of all following tasks in the same column.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$taskId`
a|The ID of the task to update the position for

|link:http://php.net/string[string^]
a|`$newColumnId`
a|The ID of the column the task now belongs to

|link:http://php.net/int[int^]
a|`$newPosition`
a|The new position
|===


[source%nowrap, php]
----

public delete($taskId):bool

----

    





Deletes a specified task.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$taskId`
a|The ID of the task to be deleted
|===


[source%nowrap, php]
----

public deleteByColumn($boardId, $columnId):bool

----

    





Deletes all tasks of a column.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board the column belongs to

|link:http://php.net/string[string^]
a|`$columnId`
a|The ID of the column the task belongs to
|===


[source%nowrap, php]
----

public allByColumnId($columnId, $referenceValue = null, $columns = []):void

----

    





Gets all tasks for the given column ID having a reference with the given reference value.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$columnId`
a|The ID of the column

|link:http://php.net/string[string^]
a|`$referenceValue`
a|The reference value that has to be contained in the task. Can be NULL.

|link:http://php.net/array[array^]
a|`$columns`
a|The attributes of the task to load
|===


[source%nowrap, php]
----

public allByBoardId($boardId, $referenceValue = null, $columns = []):void

----

    





Gets all tasks for the given column ID having a reference with the given reference value.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$boardId`
a|The ID of the board

|link:http://php.net/string[string^]
a|`$referenceValue`
a|The reference value that has to be contained in the task. Can be NULL.

|link:http://php.net/array[array^]
a|`$columns`
a|The attributes of the task to load
|===


[[board_board_events]]
===  Events
[[board_events_afterboardcolumntasksdeleted]]
==== AfterBoardColumnTasksDeleted

This event will be triggered, after all tasks of a column were deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
----

public getBoardId():string

----

    







[source%nowrap, php]
----

public getColumnId():string

----

    







[source%nowrap, php]
----

public getDeletedTaskIdList():array

----

    








[[board_events_afterboardtaskcreated]]
==== AfterBoardTaskCreated

This event will be triggered, when a board task was created.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
----

public getBoardTask():Plenty\Modules\Board\Models\BoardTask

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]





[[board_events_afterboardtaskdeleted]]
==== AfterBoardTaskDeleted

This event will be triggered, when a single board task was deleted. It won&#039;t be triggered, if a board column was deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
----

public getBoardTask():Plenty\Modules\Board\Models\BoardTask

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]





[[board_events_afterboardtaskreferencecreated]]
==== AfterBoardTaskReferenceCreated

This event will be triggered, after a task reference was created.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
----

public getBoardTaskReference():Plenty\Modules\Board\Models\BoardTaskReference

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardtaskreference[`BoardTaskReference`]





[[board_events_afterboardtaskreferencedeleted]]
==== AfterBoardTaskReferenceDeleted

This event will be triggered, after a task reference was deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
----

public getBoardTaskReference():Plenty\Modules\Board\Models\BoardTaskReference

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardtaskreference[`BoardTaskReference`]





[[board_events_beforeboardcolumndeleted]]
==== BeforeBoardColumnDeleted

This event will be triggered, before a board column will be deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
----

public getBoard():Plenty\Modules\Board\Models\Board

----

    


====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]




[source%nowrap, php]
----

public getColumnId():string

----

    








[[board_events_beforeboarddeleted]]
==== BeforeBoardDeleted

This event will be triggered, before a board will be deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
----

public getBoard():Plenty\Modules\Board\Models\Board

----

    


====== *Return type:*        xref:Board.adoc#board_models_board[`Board`]





[[board_events_beforeboardtaskdeleted]]
==== BeforeBoardTaskDeleted

This event will be triggered, before a single board task was deleted. It won&#039;t be triggered, if a board column will be deleted.



===== Namespace

`Plenty\Modules\Board\Events`






===== Methods

[source%nowrap, php]
----

public getBoardTask():Plenty\Modules\Board\Models\BoardTask

----

    


====== *Return type:*        xref:Board.adoc#board_models_boardtask[`BoardTask`]




[[board_board_models]]
===  Models
[[board_models_board]]
==== Board

The board model.



===== Namespace

`Plenty\Modules\Board\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|id
    a|The ID of the board
|link:http://php.net/string[string^]
    a|boardName
    a|The name of the board
|        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|boardColumns
    a|The columns of the board
|link:http://php.net/int[int^]
    a|columnsCount
    a|The number of columns
|link:http://php.net/int[int^]
    a|tasksCount
    a|The number of tasks
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[board_models_boardcolumn]]
==== BoardColumn

The board column model.



===== Namespace

`Plenty\Modules\Board\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|id
    a|The ID of the board column
|link:http://php.net/string[string^]
    a|boardId
    a|The ID of the board
|link:http://php.net/string[string^]
    a|columnName
    a|The name of the column
|link:http://php.net/int[int^]
    a|position
    a|The position
|
    a|tasks
    a|The tasks
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[board_models_boardtask]]
==== BoardTask

The board task model.



===== Namespace

`Plenty\Modules\Board\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|id
    a|The ID of the board task
|link:http://php.net/string[string^]
    a|taskName
    a|The name of the task
|link:http://php.net/string[string^]
    a|description
    a|The description of the task
|link:http://php.net/int[int^]
    a|position
    a|The position of the task
|link:http://php.net/string[string^]
    a|columnId
    a|The ID of the column
|link:http://php.net/string[string^]
    a|boardId
    a|The ID of the board
|
    a|tags
    a|
|
    a|references
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[board_models_boardtaskreference]]
==== BoardTaskReference

The task reference model.



===== Namespace

`Plenty\Modules\Board\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|id
    a|The ID of the board task reference
|link:http://php.net/string[string^]
    a|taskId
    a|The ID of the task to create a reference for
|link:http://php.net/string[string^]
    a|referenceValue
    a|Reference type followed by foreign ID of the referenced object. Syntax: TYPE-ID Example: user-123456 Types: user,ticket,contact,order,item
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

