:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[catalog_catalog]]
== Catalog

[[catalog_catalog_contracts]]
===  Contracts
[[catalog_contracts_catalogcontentrepositorycontract]]
==== CatalogContentRepositoryContract

The CatalogContentRepositoryContract is the interface for the catalogue content repository. This interface allows to read and update a catalogue&#039;s content. The content contains the specific catalogue data that is used in the exports.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id):array

----







Returns the content of the catalogue.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|The id of the catalogue
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):array

----







Updates the content of the catalogue.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|The id of the catalogue

a|`$data`
|link:http://php.net/array[array^]
a|The content that should be inserted into the catalogue
|===



[[catalog_contracts_catalogexportfilterservicecontract]]
==== CatalogExportFilterServiceContract

To be written



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#applyfilters]
----

public applyFilters($documentSearch, $config):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$documentSearch`
|        xref:Cloud.adoc#cloud_document_documentsearch[`DocumentSearch`]
a|

a|`$config`
|link:http://php.net/array[array^]
a|
|===



[[catalog_contracts_catalogexportrepositorycontract]]
==== CatalogExportRepositoryContract

The CatalogExportRepositoryContract is the interface for the catalogue export repository. It allows to receive an instance of CatalogExportServiceContract to export a specific catalogue.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#exportbyid]
----

public exportById($id):Plenty\Modules\Catalog\Contracts\CatalogExportServiceContract

----




====== *Return type:*        xref:Catalog.adoc#catalog_contracts_catalogexportservicecontract[`CatalogExportServiceContract`]


Returns an instance of CatalogExportServiceContract to export a specific catalogue.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|The id of the catalogue
|===


[source%nowrap, php]
[#initiatequeue]
----

public initiateQueue($id):void

----







Initiates the queue which exports a specific catalogue.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#download]
----

public download($id, $hash = &quot;&quot;, $extension = &quot;csv&quot;, $public = false, $token = &quot;&quot;):array

----







Provides the response with file attachment to download in browser

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$hash`
|link:http://php.net/string[string^]
a|

a|`$extension`
|link:http://php.net/string[string^]
a|

a|`$public`
|link:http://php.net/bool[bool^]
a|

a|`$token`
|link:http://php.net/string[string^]
a|
|===



[[catalog_contracts_catalogexportservicecontract]]
==== CatalogExportServiceContract

The CatalogExportServiceContract is the interface for the catalogue export service. It allows you to configure and start the export of a catalogue.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#setadditionalfields]
----

public setAdditionalFields($additionalFields):void

----

[WARNING]
.Deprecated! 
====

Use fields with the attribute &#039;hidden&#039; and &#039;default&#039; in Plenty\Modules\Catalog\Contracts\DataProviderContract::getData instead

====






Specifies fields that should be exported in addition to the mappings configured in the catalogue.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$additionalFields`
|link:http://php.net/array[array^]
a|The fields that should be exported additionally. Each field will be specified by an entry in the array, while the key of that entry determines the key that the field will have in the exported item.
|===


[source%nowrap, php]
[#addmutator]
----

public addMutator($mutator):void

----

[WARNING]
.Deprecated! 
====

Use Plenty\Modules\Catalog\Contracts\TemplateContract::getPreMutators or Plenty\Modules\Catalog\Contracts\TemplateContract::getPostMutators instead.

====








.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mutator`
|link:http://php.net/callable[callable^]
a|
|===


[source%nowrap, php]
[#setsettings]
----

public setSettings($settings):void

----







Defines the settings that are used in the mappings and for filtering.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$settings`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#setnumberofdocumentspershard]
----

public setNumberOfDocumentsPerShard($numberOfDocumentsPerShard):void

----

[WARNING]
.Deprecated! 
====

Use Plenty\Modules\Catalog\Contracts\CatalogExportServiceContract::setItemsPerPage instead.

====








.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$numberOfDocumentsPerShard`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#setitemsperpage]
----

public setItemsPerPage($itemsPerPage):void

----







Defines the amount of items that will be returned in each iteration of the export. In specific formats such as variation, it can have more results e.g. if items per page is set to 500, but variations 500 and 501 belong to the same item. In this case, variation 501 will also be returned.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The amount of items per page
|===


[source%nowrap, php]
[#setupdatedsince]
----

public setUpdatedSince($timestamp):void

----







Limits the results of items to only those that were updated after the given timestamp.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$timestamp`
|        xref:Miscellaneous.adoc#miscellaneous_carbon_carbon[`Carbon`]
a|
|===


[source%nowrap, php]
[#getresult]
----

public getResult():Plenty\Modules\Catalog\Models\CatalogExportResult

----




====== *Return type:*        xref:Catalog.adoc#catalog_models_catalogexportresult[`CatalogExportResult`]


Returns an instance of CatalogExportResult, which can be iterated to receive the different pages of the exported data.

[source%nowrap, php]
[#getpreview]
----

public getPreview():void

----










[[catalog_contracts_catalogrepositorycontract]]
==== CatalogRepositoryContract

The CatalogRepositoryContract is the interface for the catalogue repository. It allows you to create, read, update and delete catalogues.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Catalog\Models\Catalog

----




====== *Return type:*        xref:Catalog.adoc#catalog_models_catalog[`Catalog`]


Create a catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Catalog\Models\Catalog

----




====== *Return type:*        xref:Catalog.adoc#catalog_models_catalog[`Catalog`]


Update a catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Catalog\Models\Catalog

----




====== *Return type:*        xref:Catalog.adoc#catalog_models_catalog[`Catalog`]


Get the latest version of a catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getbyversion]
----

public getByVersion($id, $version = &quot;&quot;):Plenty\Modules\Catalog\Models\Catalog

----




====== *Return type:*        xref:Catalog.adoc#catalog_models_catalog[`Catalog`]


Get a specific version of a catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$version`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#restoreversion]
----

public restoreVersion($id, $version = &quot;&quot;):Plenty\Modules\Catalog\Models\Catalog

----




====== *Return type:*        xref:Catalog.adoc#catalog_models_catalog[`Catalog`]


Restore a past version of a catalog to become latest

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$version`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#listversions]
----

public listVersions($id):Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Lists catalog versions

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|Catalog ID
|===


[source%nowrap, php]
[#getarchive]
----

public getArchive():array

----







Gets the archive

[source%nowrap, php]
[#restorearchived]
----

public restoreArchived($id):Plenty\Modules\Catalog\Models\Catalog

----




====== *Return type:*        xref:Catalog.adoc#catalog_models_catalog[`Catalog`]


Restores an archived catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Delete a catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|Catalog ID
|===


[source%nowrap, php]
[#copy]
----

public copy($data):array

----







Copy a catalog or multiple catalogs

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#copycatalog]
----

public copyCatalog($id, $modifiedAttributes):Plenty\Modules\Catalog\Models\Catalog

----




====== *Return type:*        xref:Catalog.adoc#catalog_models_catalog[`Catalog`]


Copy a single catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|Catalog ID

a|`$modifiedAttributes`
|link:http://php.net/array[array^]
a|Attributes to add or modify
|===


[source%nowrap, php]
[#copycatalogformat]
----

public copyCatalogFormat($catalogId, $data):array

----







Copy a catalog format

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$catalogId`
|link:http://php.net/string[string^]
a|Catalog ID

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#all]
----

public all($page = 1, $perPage = 25):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Get list of all catalogs

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$perPage`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#activate]
----

public activate($id, $active):array

----







Activate a catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$active`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#getcatalogpreview]
----

public getCatalogPreview($id):array

----







Gets the preview for an export with a specific catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#migrate]
----

public migrate():bool

----







Migrates catalogs from Dynamo DB to S3

[source%nowrap, php]
[#generatetoken]
----

public generateToken():string

----







Generates an alphanumeric token

[source%nowrap, php]
[#builddownloadpublicurl]
----

public buildDownloadPublicURL($id, $data):string

----







Builds the catalog&#039;s public download url

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#builddownloadprivateurl]
----

public buildDownloadPrivateURL($id, $data):string

----







Builds the catalog&#039;s private download url

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#exportcatalog]
----

public exportCatalog($id):array

----







Exports the catalog. The catalog ID is required.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#importcatalog]
----

public importCatalog($content):Plenty\Modules\Catalog\Models\Catalog

----




====== *Return type:*        xref:Catalog.adoc#catalog_models_catalog[`Catalog`]


Imports the catalog. The catalog ID is required.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$content`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[catalog_contracts_catalogresultconvertercontract]]
==== CatalogResultConverterContract

To be written



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#adddata]
----

public addData($data):void

----







Through this a single entry of a catalog result should be added

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#getconvertedresult]
----

public getConvertedResult():string

----







Converts the data that was inserted into the specific output format

[source%nowrap, php]
[#gettype]
----

public getType():string

----







Returns the type of the converted result

[source%nowrap, php]
[#clear]
----

public clear():void

----










[[catalog_contracts_catalogruntimeconfigcontract]]
==== CatalogRuntimeConfigContract

To be written



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#applyruntimeconfig]
----

public applyRuntimeConfig($template, $catalog):void

----







Will be run before every export and is meant to provide filters on the template
which can&#039;t be defined before the runtime of the export

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$template`
|        xref:Catalog.adoc#catalog_contracts_templatecontract[`TemplateContract`]
a|

a|`$catalog`
|        xref:Catalog.adoc#catalog_models_catalog[`Catalog`]
a|
|===


[source%nowrap, php]
[#applypreviewruntimeconfig]
----

public applyPreviewRuntimeConfig($template, $catalog):void

----







Will be run before every preview and is meant to provide filters on the template
which can&#039;t be defined before the runtime of the preview

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$template`
|        xref:Catalog.adoc#catalog_contracts_templatecontract[`TemplateContract`]
a|

a|`$catalog`
|        xref:Catalog.adoc#catalog_models_catalog[`Catalog`]
a|
|===



[[catalog_contracts_catalogruntimeconfigprovidercontract]]
==== CatalogRuntimeConfigProviderContract

To be written



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#ispreviewable]
----

public isPreviewable():bool

----







Determines if a preview can be exported through catalogs that use the specific template

[source%nowrap, php]
[#getruntimeconfigclass]
----

public getRuntimeConfigClass():string

----







Returns a class name through which the export can be configured with information that isn&#039;t known before
the export runtime

[source%nowrap, php]
[#getresultconverterclass]
----

public getResultConverterClass():string

----







Returns a class name through which the export result can be converted into the necessary format (e.g. json or csv)


[[catalog_contracts_catalogtemplateprovidercontract]]
==== CatalogTemplateProviderContract

The CatalogTemplateProviderContract is the interface that has to be implemented by the catalogue template providers. Each registered template should have a catalogue template provider (multiple templates can use the same one) to avoid booting them if they are not necessary. A catalogue template provider fills a template with data at the moment the template gets booted. Whenever it is possible, use the abstract class Plenty\Modules\Catalog\Templates\BaseTemplateProvider.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#getmappings]
----

public getMappings():array

----







Returns the different mapping sections including the information which data provider fills them. Each entry in the array represents a section of the catalogue UI.

[source%nowrap, php]
[#getfilter]
----

public getFilter():array

----







Returns the filters that will be applied in each export of templates that will be booted by this provider.

[source%nowrap, php]
[#getpremutators]
----

public getPreMutators():array

----







Returns the callback functions that will be applied to the raw data (so before the mapping occurs) of each item in the export. Every callback function will receive an array of the raw item data and should return this array with the changes that should be applied (e.g. function (array $item){ --your code-- return $item}).

[source%nowrap, php]
[#getpostmutators]
----

public getPostMutators():array

----







Returns the callback functions that will be applied to the mapped data of each item in the export. Every callback function will receive an array of the mapped item data und should return this array with the changes that should be applied (e.g. function (array $item){ --your code-- return $item}).

[source%nowrap, php]
[#getskucallback]
----

public getSkuCallback():callable

----







Returns a callback function that is called if a field with the specific key &quot;sku&quot; got mapped. The function will receive the value that got mapped, the raw data array of this item and the type of the mapped source. It should return the new value (e.g. function ($value, array $item, $mappingType){ --your code-- return $value})).

[source%nowrap, php]
[#getsettings]
----

public getSettings():array

----







Returns an array of settings that will be displayed in the UI of each catalogue with a template that uses this provider. The selected values for all those settings can then be used in the export.

[source%nowrap, php]
[#getmetainfo]
----

public getMetaInfo():array

----







Returns an array of meta information which can be used to forward information to the export which could otherwise not be received.


[[catalog_contracts_dataprovidercontract]]
==== DataProviderContract

The DataProviderContract is the interface for data providers. Data providers provide the available fields that can be mapped in a template to create a catalogue. Whenever it is possible, use one of the concrete implementations Plenty\Modules\Catalog\DataProviders\BaseDataProvider, Plenty\Modules\Catalog\DataProviders\KeyDataProvider or Plenty\Modules\Catalog\DataProviders\NestedKeyDataProvider.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#getdata]
----

public getData($query = &quot;&quot;):array

----







Returns the data that should be provided.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#settemplate]
----

public setTemplate($template):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$template`
|        xref:Catalog.adoc#catalog_contracts_templatecontract[`TemplateContract`]
a|
|===


[source%nowrap, php]
[#setmapping]
----

public setMapping($mapping):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mapping`
|link:http://php.net/array[array^]
a|
|===



[[catalog_contracts_fieldgrouprepositorycontract]]
==== FieldGroupRepositoryContract

The FieldGroupRepositoryContract is the contract for the field group repository. It allows to retrieve fields of a field group. Field groups represent the different groups of available sources that can be seen in the data picker component in the catalogue UI. Each field represents a mappable source.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#getfields]
----

public getFields($id, $page, $itemsPerPage, $parentId = null):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Get list of fields

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|

a|`$parentId`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getsearchfields]
----

public getSearchFields($id, $hidden = []):array

----







Get list of fields for search

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$hidden`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfieldbyid]
----

public getFieldById($id, $fieldId):array

----







Get field by id

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$fieldId`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getfieldsbycatalogid]
----

public getFieldsByCatalogId($id, $catalogId):array

----







Get Fields by id of the catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$catalogId`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#fieldvaluestree]
----

public fieldValuesTree($id, $page, $itemsPerPage):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|
|===



[[catalog_contracts_nesteddataprovidercontract]]
==== NestedDataProviderContract

The NestedDataProviderContract is the interface for nested data providers. Nested data providers are used to provide nested options that can be selected for export. E.g. a list of categories of a specific marketplace. Whenever it is possible, use the concrete implementation Plenty\Modules\Catalog\DataProviders\NestedKeyDataProvider.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#getnesteddata]
----

public getNestedData($parentId, $query = &quot;&quot;, $meta = []):array

----







Returns the data of a specific level, which is determined via the id of a parent value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$parentId`
|link:http://php.net/string[string^]
a|

a|`$query`
|link:http://php.net/string[string^]
a|

a|`$meta`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getdatabyvalue]
----

public getDataByValue($id):array

----







Returns a specific value of the nested data determined by its id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getdata]
----

public getData($query = &quot;&quot;):array

----







Returns the data that should be provided.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#settemplate]
----

public setTemplate($template):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$template`
|        xref:Catalog.adoc#catalog_contracts_templatecontract[`TemplateContract`]
a|
|===


[source%nowrap, php]
[#setmapping]
----

public setMapping($mapping):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mapping`
|link:http://php.net/array[array^]
a|
|===



[[catalog_contracts_templatecontainercontract]]
==== TemplateContainerContract

The TemplateContainerContract is the interface of the template container. The template container is a singleton, which allows to register and retrieve templates.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#register]
----

public register($name, $type, $providerClass = &quot;&quot;, $exportType = &quot;Plenty\Modules\Catalog\Dummy\VariationCatalogExportType&quot;):Plenty\Modules\Catalog\Contracts\TemplateContract

----




====== *Return type:*        xref:Catalog.adoc#catalog_contracts_templatecontract[`TemplateContract`]


Registers a new template that can be used to create a catalogue.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The specific name of the template

a|`$type`
|link:http://php.net/string[string^]
a|The type of the template. Multiple templates can be grouped in one type

a|`$providerClass`
|link:http://php.net/string[string^]
a|Class name of the provider that boots the template

a|`$exportType`
|link:http://php.net/string[string^]
a|Determines which data is available for mappings in the export. The default is variation data. (Currently only variation data can be exported via catalogues.)
|===


[source%nowrap, php]
[#gettemplates]
----

public getTemplates():array

----







Returns all registered templates.

[source%nowrap, php]
[#gettemplate]
----

public getTemplate($identifier):Plenty\Modules\Catalog\Contracts\TemplateContract

----




====== *Return type:*        xref:Catalog.adoc#catalog_contracts_templatecontract[`TemplateContract`]


Returns a specific template by its identifier.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$identifier`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#gettemplatewithoutbootingit]
----

public getTemplateWithoutBootingIt($identifier):Plenty\Modules\Catalog\Contracts\TemplateContract

----




====== *Return type:*        xref:Catalog.adoc#catalog_contracts_templatecontract[`TemplateContract`]


Returns a specific template by its identifier without booting it.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$identifier`
|link:http://php.net/string[string^]
a|
|===



[[catalog_contracts_templatecontract]]
==== TemplateContract

The TemplateContract is the interface for templates. Templates are used to define a specific schema that can be used to create and configure a catalogue.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#getname]
----

public getName():string

----







Returns the name of the template.

[source%nowrap, php]
[#gettype]
----

public getType():string

----







Returns the type of the template.

[source%nowrap, php]
[#getexporttype]
----

public getExportType():string

----







Returns the export type of the template.

[source%nowrap, php]
[#getmappings]
----

public getMappings():array

----







Returns the mappings of a template.

[source%nowrap, php]
[#addmapping]
----

public addMapping($mapping):void

----







Adds a mapping to the template. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mapping`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#addmutator]
----

public addMutator($callback):void

----

[WARNING]
.Deprecated! 
====

Use Plenty\Modules\Catalog\Contracts\TemplateContract::addPreMutator or Plenty\Modules\Catalog\Contracts\TemplateContract::addPreMutator instead.

====








.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$callback`
|link:http://php.net/callable[callable^]
a|
|===


[source%nowrap, php]
[#addpremutator]
----

public addPreMutator($callback):void

----







Adds a pre mutator to the template. Pre mutators are applied to the export data before the mapping occurs. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$callback`
|link:http://php.net/callable[callable^]
a|
|===


[source%nowrap, php]
[#addpostmutator]
----

public addPostMutator($callback):void

----







Adds a post mutator to the template. Post mutators are applied to the export data once the mapping occurred. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$callback`
|link:http://php.net/callable[callable^]
a|
|===


[source%nowrap, php]
[#getfilter]
----

public getFilter():array

----







Returns the filters of the template.

[source%nowrap, php]
[#addfilter]
----

public addFilter($filter):void

----







Adds a filter to the template. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filter`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getidentifier]
----

public getIdentifier():string

----







Returns the unique identifier of the template.

[source%nowrap, php]
[#getmutators]
----

public getMutators():array

----

[WARNING]
.Deprecated! 
====

Use Plenty\Modules\Catalog\Contracts\TemplateContract::getPreMutators or Plenty\Modules\Catalog\Contracts\TemplateContract::getPostMutators instead.

====








[source%nowrap, php]
[#getpremutators]
----

public getPreMutators():array

----







Returns the pre mutators of the template.

[source%nowrap, php]
[#getpostmutators]
----

public getPostMutators():array

----







Returns the post mutators of the template.

[source%nowrap, php]
[#setskucallback]
----

public setSkuCallback($callback):void

----







Defines the callback function that will be called after the mapping is done for a field with the key &quot;sku&quot;.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$callback`
|link:http://php.net/callable[callable^]
a|
|===


[source%nowrap, php]
[#getskucallback]
----

public getSkuCallback():callable

----







Retrieves the callback function that will be called after the mapping is done for a field with the key &quot;sku&quot;.

[source%nowrap, php]
[#addsetting]
----

public addSetting($setting):void

----







Adds a setting to the templates. Settings create components in the UI of catalogues which use this template. The components will provide data for the export in accordance with the user input in the catalogue. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setting`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getsettings]
----

public getSettings():array

----







Returns the settings of a template.

[source%nowrap, php]
[#setmetainfo]
----

public setMetaInfo($meta):void

----







Sets the meta info for a template. Meta info is used to provide data which has to be known when working with the template. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$meta`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getmetainfo]
----

public getMetaInfo():array

----







Returns the meta info of a template.

[source%nowrap, php]
[#ispreviewable]
----

public isPreviewable():bool

----







Determines if this template supports preview exports

[source%nowrap, php]
[#allowpreview]
----

public allowPreview($isPreviewable):void

----







Used to activate / deactivate the possibility to export previews through this template

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isPreviewable`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#hasruntimeconfig]
----

public hasRuntimeConfig():bool

----









[source%nowrap, php]
[#hasresultconverter]
----

public hasResultConverter():bool

----









[source%nowrap, php]
[#getruntimeconfig]
----

public getRuntimeConfig():Plenty\Modules\Catalog\Contracts\CatalogRuntimeConfigContract

----




====== *Return type:*        xref:Catalog.adoc#catalog_contracts_catalogruntimeconfigcontract[`CatalogRuntimeConfigContract`]




[source%nowrap, php]
[#getresultconverter]
----

public getResultConverter():Plenty\Modules\Catalog\Contracts\CatalogResultConverterContract

----




====== *Return type:*        xref:Catalog.adoc#catalog_contracts_catalogresultconvertercontract[`CatalogResultConverterContract`]




[source%nowrap, php]
[#isbooted]
----

public isBooted():bool

----







Returns the current boot state of the template.

[source%nowrap, php]
[#translatedtoarray]
----

public translatedToArray($language):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$language`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get the instance as an array.

[source%nowrap, php]
[#jsonserialize]
----

public jsonSerialize():void

----










[[catalog_contracts_templaterepositorycontract]]
==== TemplateRepositoryContract

The TemplateRepositoryContract is the interface for the template repository. It allows to retrieve templates and their mappings.



===== Namespace

`Plenty\Modules\Catalog\Contracts`






===== Methods

[source%nowrap, php]
[#gettemplates]
----

public getTemplates():array

----







Get list of templates

[source%nowrap, php]
[#gettemplate]
----

public getTemplate($id, $data):array

----







Get template

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$data`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getmappings]
----

public getMappings($id):array

----







Get list of mappings

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getmapping]
----

public getMapping($id, $mappingId):array

----







Get mapping

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$mappingId`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getmappingdata]
----

public getMappingData($id, $mappingId, $parentId = null):array

----







Get mapping data

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$mappingId`
|link:http://php.net/string[string^]
a|

a|`$parentId`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getmappingdatabyid]
----

public getMappingDataById($id, $mappingId, $dataId):array

----







Get mapping data by id

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|

a|`$mappingId`
|link:http://php.net/string[string^]
a|

a|`$dataId`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#test]
----

public test($id):void

----







Test export of a catalog

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getallmappings]
----

public getAllMappings($id):array

----







Get all mappings

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|
|===


[[catalog_catalog_dataproviders]]
===  DataProviders
[[catalog_dataproviders_basedataprovider]]
==== BaseDataProvider

The BaseDataProvider is used to define a section of simple mappings in the catalogue. A simple mapping refers to the assignment of a value in the plentymarkets system or a manually predefined value to a specific key. E.g. mapping the value of a specific text property to the key &#039;description&#039;.



===== Namespace

`Plenty\Modules\Catalog\DataProviders`






===== Methods

[source%nowrap, php]
[#getrows]
----

public getRows():array

----









[source%nowrap, php]
[#settemplate]
----

public setTemplate($template):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$template`
|        xref:Catalog.adoc#catalog_contracts_templatecontract[`TemplateContract`]
a|
|===


[source%nowrap, php]
[#setmapping]
----

public setMapping($mapping):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mapping`
|link:http://php.net/array[array^]
a|
|===



[[catalog_dataproviders_keydataprovider]]
==== KeyDataProvider

The KeyDataProvider is used to define a section of a complex mapping in the catalogue. A complex mapping refers to the assignment of a value from a predefined list of possible values to a key if a specific requirement is met. E.g. put the value &#039;awesomeBrand&#039; into the key &#039;brand&#039;, if manufacturer &#039;awesomeManufacturer&#039; is linked to a variation.



===== Namespace

`Plenty\Modules\Catalog\DataProviders`






===== Methods

[source%nowrap, php]
[#getkey]
----

public getKey():string

----









[source%nowrap, php]
[#getrows]
----

public getRows():array

----









[source%nowrap, php]
[#settemplate]
----

public setTemplate($template):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$template`
|        xref:Catalog.adoc#catalog_contracts_templatecontract[`TemplateContract`]
a|
|===


[source%nowrap, php]
[#setmapping]
----

public setMapping($mapping):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mapping`
|link:http://php.net/array[array^]
a|
|===



[[catalog_dataproviders_nestedkeydataprovider]]
==== NestedKeyDataProvider

The NestedKeyDataProvider is used to define a section of a complex mapping in the catalogue. It is specifically used if the list of available values contains nested values. E.g. a list of categories with sub-categories.



===== Namespace

`Plenty\Modules\Catalog\DataProviders`






===== Methods

[source%nowrap, php]
[#getkey]
----

public getKey():string

----









[source%nowrap, php]
[#getnestedrows]
----

public getNestedRows($parentId):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$parentId`
|
a|
|===


[source%nowrap, php]
[#getmetadata]
----

public getMetaData():void

----









[source%nowrap, php]
[#getnesteddata]
----

public getNestedData($parentId, $query = &quot;&quot;, $meta = []):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$parentId`
|link:http://php.net/string[string^]
a|

a|`$query`
|link:http://php.net/string[string^]
a|

a|`$meta`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getrows]
----

public getRows():array

----









[source%nowrap, php]
[#settemplate]
----

public setTemplate($template):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$template`
|        xref:Catalog.adoc#catalog_contracts_templatecontract[`TemplateContract`]
a|
|===


[source%nowrap, php]
[#setmapping]
----

public setMapping($mapping):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mapping`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getdatabyvalue]
----

public getDataByValue($id):array

----







Returns a specific value of the nested data determined by its id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|
|===


[[catalog_catalog_helpers]]
===  Helpers
[[catalog_helpers_contenttypehelper]]
==== ContentTypeHelper

Provides a list of valid content types that can be returned in a CatalogResultConverter



===== Namespace

`Plenty\Modules\Catalog\Helpers`






===== Methods

[source%nowrap, php]
[#isvalidtype]
----

public static isValidType($type):bool

----







Checks wether a given type is valid as return type in a CatalogResultConverter

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[[catalog_catalog_models]]
===  Models
[[catalog_models_catalog]]
==== Catalog

The catalog model - stores on S3



===== Namespace

`Plenty\Modules\Catalog\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|data
    |link:http://php.net/array[array^]
    a|Contains the mappings and template settings
|settings
    |link:http://php.net/array[array^]
    a|Contains the settings
|name
    |link:http://php.net/string[string^]
    a|The name of the catalogue
|template
    |link:http://php.net/string[string^]
    a|The id of the template that was used to create the catalogue
|id
    |link:http://php.net/string[string^]
    a|The id of the catalogue
|active
    |link:http://php.net/bool[bool^]
    a|Determines whether a catalogue can be exported
|showMandatoryFields
    |link:http://php.net/bool[bool^]
    a|Determines if only the mandatory fields should be displayed in the catalogue UI
|updatedAt
    |link:http://php.net/string[string^]
    a|The updated at date in W3C
|createdAt
    |link:http://php.net/string[string^]
    a|The created at date in W3C
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[catalog_models_catalogexportresult]]
==== CatalogExportResult

The CatalogExportResult represents the exported data in a specific catalogue export. It implements the Iterator interface and can therefore be used in a foreach loop to retrieve the different pages of the export data.



===== Namespace

`Plenty\Modules\Catalog\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[catalog_catalog_templates]]
===  Templates
[[catalog_templates_basetemplateprovider]]
==== BaseTemplateProvider

The BaseTemplateProvider is the abstract class that should be used to implement a template provider.



===== Namespace

`Plenty\Modules\Catalog\Templates`






===== Methods

[source%nowrap, php]
[#getmappings]
----

public getMappings():array

----







Returns the different mapping sections including the information which data provider fills them. Each entry in the array represents a section of the catalogue UI.

[source%nowrap, php]
[#getfilter]
----

public getFilter():array

----







Returns the filters that will be applied in each export of templates that will be booted by this provider.

[source%nowrap, php]
[#getpremutators]
----

public getPreMutators():array

----







Returns the callback functions that will be applied to the raw data (so before the mapping occurs) of each item in the export. Every callback function will receive an array of the raw item data and should return this array with the changes that should be applied (e.g. function (array $item){ --your code-- return $item}).

[source%nowrap, php]
[#getpostmutators]
----

public getPostMutators():array

----







Returns the callback functions that will be applied to the mapped data of each item in the export. Every callback function will receive an array of the mapped item data und should return this array with the changes that should be applied (e.g. function (array $item){ --your code-- return $item}).

[source%nowrap, php]
[#getskucallback]
----

public getSkuCallback():callable

----







Returns a callback function that is called if a field with the specific key &quot;sku&quot; got mapped. The function will receive the value that got mapped, the raw data array of this item and the type of the mapped source. It should return the new value (e.g. function ($value, array $item, $mappingType){ --your code-- return $value})).

[source%nowrap, php]
[#getsettings]
----

public getSettings():array

----







Returns an array of settings that will be displayed in the UI of each catalogue with a template that uses this provider. The selected values for all those settings can then be used in the export.

[source%nowrap, php]
[#getmetainfo]
----

public getMetaInfo():array

----







Returns an array of meta information which can be used to forward information to the export which could otherwise not be received.


[[catalog_templates_template]]
==== Template

Templates are used to define a schema for the creation of catalogues.



===== Namespace

`Plenty\Modules\Catalog\Templates`






===== Methods

[source%nowrap, php]
[#getmappings]
----

public getMappings():array

----







Returns the mappings of a template.

[source%nowrap, php]
[#addmapping]
----

public addMapping($section):void

----







Adds a mapping to the template. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$section`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#addmutator]
----

public addMutator($callback):void

----

[WARNING]
.Deprecated! 
====

Use Plenty\Modules\Catalog\Contracts\TemplateContract::addPreMutator or Plenty\Modules\Catalog\Contracts\TemplateContract::addPreMutator instead.

====








.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$callback`
|link:http://php.net/callable[callable^]
a|
|===


[source%nowrap, php]
[#getmutators]
----

public getMutators():array

----

[WARNING]
.Deprecated! 
====

Use Plenty\Modules\Catalog\Contracts\TemplateContract::getPreMutators or Plenty\Modules\Catalog\Contracts\TemplateContract::getPostMutators instead.

====








[source%nowrap, php]
[#addpremutator]
----

public addPreMutator($callback):void

----







Adds a pre mutator to the template. Pre mutators are applied to the export data before the mapping occurs. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$callback`
|link:http://php.net/callable[callable^]
a|
|===


[source%nowrap, php]
[#addpostmutator]
----

public addPostMutator($callback):void

----







Adds a post mutator to the template. Post mutators are applied to the export data once the mapping occurred. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$callback`
|link:http://php.net/callable[callable^]
a|
|===


[source%nowrap, php]
[#getfilter]
----

public getFilter():array

----







Returns the filters of the template.

[source%nowrap, php]
[#addfilter]
----

public addFilter($filter):void

----







Adds a filter to the template. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filter`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getpremutators]
----

public getPreMutators():array

----







Returns the pre mutators of the template.

[source%nowrap, php]
[#getpostmutators]
----

public getPostMutators():array

----







Returns the post mutators of the template.

[source%nowrap, php]
[#setskucallback]
----

public setSkuCallback($callback):void

----







Defines the callback function that will be called after the mapping is done for a field with the key &quot;sku&quot;.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$callback`
|link:http://php.net/callable[callable^]
a|
|===


[source%nowrap, php]
[#getskucallback]
----

public getSkuCallback():callable

----







Returns the callback function that will be called after the mapping is done for a field with the key &quot;sku&quot;

[source%nowrap, php]
[#addsetting]
----

public addSetting($setting):void

----







Adds a setting to the templates. Settings create components in the UI of catalogues which use this template. The components will provide data for the export in accordance with the user input in the catalogue. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setting`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getsettings]
----

public getSettings():array

----







Returns the settings of a template.

[source%nowrap, php]
[#setmetainfo]
----

public setMetaInfo($meta):void

----







Sets the meta info for a template. Meta info is used to provide data which has to be known when working with the template. If possible, don&#039;t use this directly and let it be handled by the catalogue template provider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$meta`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getmetainfo]
----

public getMetaInfo():void

----









[source%nowrap, php]
[#getname]
----

public getName():string

----









[source%nowrap, php]
[#getexporttype]
----

public getExportType():string

----









[source%nowrap, php]
[#gettype]
----

public getType():string

----









[source%nowrap, php]
[#translatedtoarray]
----

public translatedToArray($language):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$language`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----









[source%nowrap, php]
[#jsonserialize]
----

public jsonSerialize():void

----









[source%nowrap, php]
[#getidentifier]
----

public getIdentifier():string

----









[source%nowrap, php]
[#getformatsettings]
----

public getFormatSettings():array

----









[source%nowrap, php]
[#getexportsettings]
----

public getExportSettings():array

----









[source%nowrap, php]
[#ispreviewable]
----

public isPreviewable():bool

----









[source%nowrap, php]
[#allowpreview]
----

public allowPreview($isPreviewable):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isPreviewable`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#getruntimeconfig]
----

public getRuntimeConfig():Plenty\Modules\Catalog\Contracts\CatalogRuntimeConfigContract

----




====== *Return type:*        xref:Catalog.adoc#catalog_contracts_catalogruntimeconfigcontract[`CatalogRuntimeConfigContract`]




[source%nowrap, php]
[#getresultconverter]
----

public getResultConverter():Plenty\Modules\Catalog\Contracts\CatalogResultConverterContract

----




====== *Return type:*        xref:Catalog.adoc#catalog_contracts_catalogresultconvertercontract[`CatalogResultConverterContract`]




[source%nowrap, php]
[#hasruntimeconfig]
----

public hasRuntimeConfig():bool

----









[source%nowrap, php]
[#hasresultconverter]
----

public hasResultConverter():bool

----









[source%nowrap, php]
[#isbooted]
----

public isBooted():bool

----









