

[[category_category]]
== Category

[[category_category_contracts]]
===  Contracts
[[category_contracts_categorybranchmarketplacerepositorycontract]]
==== CategoryBranchMarketplaceRepositoryContract

Repository for CategoryBranchMarketplace



===== Namespace

`Plenty\Modules\Category\Contracts`






===== Methods

[source%nowrap, php]
----

public findCategoryBranchMarketplace($branchId, $webstoreId, $marketplaceId, $marketplaceSubId = 0.0):Plenty\Modules\Category\Models\CategoryBranchMarketplace

----

    


====== *Return type:*        xref:Category.adoc#category_models_categorybranchmarketplace[`CategoryBranchMarketplace`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$branchId`
a|

|link:http://php.net/int[int^]
a|`$webstoreId`
a|

|link:http://php.net/int[int^]
a|`$marketplaceId`
a|

|link:http://php.net/float[float^]
a|`$marketplaceSubId`
a|
|===



[[category_contracts_categorybranchrepositorycontract]]
==== CategoryBranchRepositoryContract

Repository Contract for CategoryBranch



===== Namespace

`Plenty\Modules\Category\Contracts`






===== Methods

[source%nowrap, php]
----

public find($id):Plenty\Modules\Category\Models\CategoryBranch

----

    


====== *Return type:*        xref:Category.adoc#category_models_categorybranch[`CategoryBranch`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
a|
|===


[source%nowrap, php]
----

public get($page = 1, $itemsPerPage = 50, $filters = []):Plenty\Repositories\Contracts\PaginationResponseContract

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_contracts_paginationresponsecontract[`PaginationResponseContract`]


Get category trees

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|

|link:http://php.net/array[array^]
a|`$filters`
a|Filters restrict the list of results. Results can be filtered by the following parameters: 'type' - the category type. Available values: item, container, content, blog
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[category_contracts_categorypropertyrepositorycontract]]
==== CategoryPropertyRepositoryContract

Repository Contract for CategoryProperty



===== Namespace

`Plenty\Modules\Category\Contracts`






===== Methods

[source%nowrap, php]
----

public create($data):Plenty\Modules\Category\Models\CategoryProperty

----

    


====== *Return type:*        xref:Category.adoc#category_models_categoryproperty[`CategoryProperty`]


Link a category to an Elmar category

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public update($categoryId, $marketId, $plentyId, $data):Plenty\Modules\Category\Models\CategoryProperty

----

    


====== *Return type:*        xref:Category.adoc#category_models_categoryproperty[`CategoryProperty`]


Update a link between a category and an Elmar category

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|

|link:http://php.net/float[float^]
a|`$marketId`
a|

|link:http://php.net/int[int^]
a|`$plentyId`
a|

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public delete($categoryId, $marketId, $plentyId):Plenty\Repositories\Models\DeleteResponse

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Delete the link between a category and an Elmar category

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|

|link:http://php.net/float[float^]
a|`$marketId`
a|

|link:http://php.net/int[int^]
a|`$plentyId`
a|
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[category_contracts_categoryrepositorycontract]]
==== CategoryRepositoryContract

Repository for categories



===== Namespace

`Plenty\Modules\Category\Contracts`






===== Methods

[source%nowrap, php]
----

public get($categoryId, $lang = &quot;de&quot;, $webstoreId = null):Plenty\Modules\Category\Models\Category

----

    


====== *Return type:*        xref:Category.adoc#category_models_category[`Category`]


Returns one category by id.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|The id of the category.

|link:http://php.net/string[string^]
a|`$lang`
a|Optional language of details.

|link:http://php.net/int[int^]
a|`$webstoreId`
a|Optional webstore id of details.
|===


[source%nowrap, php]
----

public getLinklistTree($type = &quot;all&quot;, $lang = &quot;de&quot;, $clientId = null, $maxLevel = 6, $customerClassId):array

----

    





Returns all linklist categories as tree.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$type`
a|'all','item','container','content' or 'blog'

|link:http://php.net/string[string^]
a|`$lang`
a|Optional language of details.

|link:http://php.net/int[int^]
a|`$clientId`
a|The unique ID of the client (store)

|link:http://php.net/int[int^]
a|`$maxLevel`
a|The deepest category level to load

|link:http://php.net/int[int^]
a|`$customerClassId`
a|The customer class id
|===


[source%nowrap, php]
----

public getArrayTree($type = &quot;all&quot;, $lang = &quot;de&quot;, $clientId = null, $maxLevel = 6, $customerClassId, $filter = null):array

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$type`
a|'all','item','container','content' or 'blog'

|link:http://php.net/string[string^]
a|`$lang`
a|Optional language of details.

|link:http://php.net/int[int^]
a|`$clientId`
a|The unique ID of the client (store)

|link:http://php.net/int[int^]
a|`$maxLevel`
a|The deepest category level to load

|link:http://php.net/int[int^]
a|`$customerClassId`
a|The customer class id

|link:http://php.net/callable[callable^]
a|`$filter`
a|
|===


[source%nowrap, php]
----

public findCategoryByUrl($level1, $level2 = null, $level3 = null, $level4 = null, $level5 = null, $level6 = null, $webstoreId = null, $lang = null):Plenty\Modules\Category\Models\Category

----

    


====== *Return type:*        xref:Category.adoc#category_models_category[`Category`]


Get the category by url.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$level1`
a|First level of the url.

|link:http://php.net/string[string^]
a|`$level2`
a|Second level of the url.

|link:http://php.net/string[string^]
a|`$level3`
a|Third level of the url.

|link:http://php.net/string[string^]
a|`$level4`
a|Fourth level of the url.

|link:http://php.net/string[string^]
a|`$level5`
a|Fifth level of the url.

|link:http://php.net/string[string^]
a|`$level6`
a|Sixth level of the url.

|link:http://php.net/int[int^]
a|`$webstoreId`
a|Id of current webstore.

|link:http://php.net/string[string^]
a|`$lang`
a|Language
|===


[source%nowrap, php]
----

public buildCache($type = &quot;all&quot;, $lang = &quot;de&quot;, $clientId, $customerClassId):void

----

    





Rebuild the category tree cache

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$type`
a|'all','item','container','content' or 'blog'

|link:http://php.net/string[string^]
a|`$lang`
a|Optional language of details.

|link:http://php.net/int[int^]
a|`$clientId`
a|The unique ID of the client (store)

|link:http://php.net/int[int^]
a|`$customerClassId`
a|The customer class id
|===


[source%nowrap, php]
----

public getLinklistList($type = &quot;all&quot;, $lang = &quot;de&quot;, $clientId = null, $maxLevel = 6):array

----

    





Returns all linklist categories as list.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$type`
a|'all','item','container','content' or 'blog'

|link:http://php.net/string[string^]
a|`$lang`
a|Optional language of details.

|link:http://php.net/int[int^]
a|`$clientId`
a|The unique ID of the client (store)

|link:http://php.net/int[int^]
a|`$maxLevel`
a|The deepest category level to load
|===


[source%nowrap, php]
----

public hasChildren($categoryId, $onlySiteMapped = false, $onlyLinkListed = false):bool

----

    





Returns true if category has children.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|The id of the category.

|link:http://php.net/bool[bool^]
a|`$onlySiteMapped`
a|Determines if the result has only sitemaps or all visible categories.

|link:http://php.net/bool[bool^]
a|`$onlyLinkListed`
a|Determines if the result has only linklists or all visible categories.
|===


[source%nowrap, php]
----

public getChildren($categoryId, $lang = &quot;de&quot;):array

----

    





Returns children of the category.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|The id of the category.

|link:http://php.net/string[string^]
a|`$lang`
a|Optional language of details.
|===


[source%nowrap, php]
----

public getUrl($categoryId, $lang = &quot;de&quot;, $onlySitemaps = false, $webstoreId = null):string

----

    





Retrieves the url for a category.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|The id of the category.

|link:http://php.net/string[string^]
a|`$lang`
a|Optional language of details.

|link:http://php.net/bool[bool^]
a|`$onlySitemaps`
a|Whether or not to only include categories with 'sitemaps' = 'Y'. Default false.

|link:http://php.net/bool[bool^]
a|`$webstoreId`
a|webstoreId of details
|===


[source%nowrap, php]
----

public search($categoryId = null, $page, $itemsPerPage = 50, $with = [], $filters = []):Plenty\Repositories\Models\PaginatedResult

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Search for categories

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|The id of the category.

|link:http://php.net/int[int^]
a|`$page`
a|The requested page.

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|Number of items per page.

|link:http://php.net/array[array^]
a|`$with`
a|The relations to be loaded.

|link:http://php.net/array[array^]
a|`$filters`
a|Filters restrict the list of results. Results can be filtered by the following parameters: 'type','lang','parentId', 'plentyId', 'linklist'
|===


[source%nowrap, php]
----

public createCategories($data):array

----

    





Creates new categories, including CategoryDetails. At least one CategoryDetails object for the default language is required. The data fields &#039;plentyId&#039;,&#039;lang&#039; and &#039;name&#039; are required. Client objects can also be specified to activate visibility for a client.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The data fields for the new Categories, including the details data fields
|===


[source%nowrap, php]
----

public updateCategories($data):array

----

    





Update categories, including optional CategoryDetails. The data fields &#039;plentyId&#039;,&#039;lang&#039; are required for the CategoryDetails object. Client objects can also be specified to change visibility for a client.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The data fields for the Categories, including the details and client data fields
|===


[source%nowrap, php]
----

public createCategory($data):Plenty\Modules\Category\Models\Category

----

    


====== *Return type:*        xref:Category.adoc#category_models_category[`Category`]


Creates a new category

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public delete($categoryId):Plenty\Repositories\Models\DeleteResponse

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes a category. The ID of the category must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|
|===


[source%nowrap, php]
----

public deleteCategoryDetails($categoryId, $data):Plenty\Repositories\Models\DeleteResponse

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Delete the category details for the languages specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public deleteCategoryClients($categoryId, $data):Plenty\Repositories\Models\DeleteResponse

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deactivate availability for clients

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[category_contracts_categorytemplaterepositorycontract]]
==== CategoryTemplateRepositoryContract

Repository for category templates



===== Namespace

`Plenty\Modules\Category\Contracts`






===== Methods

[source%nowrap, php]
----

public find($params):Plenty\Modules\Category\Models\CategoryTemplate

----

    


====== *Return type:*        xref:Category.adoc#category_models_categorytemplate[`CategoryTemplate`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$params`
a|
|===


[source%nowrap, php]
----

public put($data):Plenty\Modules\Category\Models\CategoryTemplate

----

    


====== *Return type:*        xref:Category.adoc#category_models_categorytemplate[`CategoryTemplate`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public delete($data):Plenty\Modules\Category\Models\CategoryTemplate

----

    


====== *Return type:*        xref:Category.adoc#category_models_categorytemplate[`CategoryTemplate`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[[category_category_models]]
===  Models
[[category_models_category]]
==== Category

Category



===== Namespace

`Plenty\Modules\Category\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The unique ID of the category
|link:http://php.net/int[int^]
    a|parentCategoryId
    a|The ID of the category's parent category. Value is <strong>null</strong> if category level is 1.
|link:http://php.net/int[int^]
    a|level
    a|The category level of this category. This information is used for the sitemap.
|link:http://php.net/string[string^]
    a|type
    a|The category type of the category
|link:http://php.net/string[string^]
    a|linklist
    a|Flag that indicates if the category will be displayed in the online store's navigation.
|link:http://php.net/string[string^]
    a|right
    a|Flag that indicates who can see this category. <ul><li>all = Category is
visible to all visitors of the online store.</li><li>customer = Category and all of its subcategories are visible to
visitors of the online store that have logged in only. Visitors that are not logged in are redirected to the login page.</li></ul>
|link:http://php.net/string[string^]
    a|sitemap
    a|Flag that indicates if the category will be included in the sitemap.
|link:http://php.net/string[string^]
    a|updatedAt
    a|The updated at timestamp of the category.
|link:http://php.net/array[array^]
    a|clients
    a|Collection of the clients (stores) that belong to this category
|link:http://php.net/array[array^]
    a|details
    a|Collection of the category details that belong to this category
|link:http://php.net/array[array^]
    a|elmarCategories
    a|The linked elmar
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[category_models_categorybranch]]
==== CategoryBranch

Category Branch



===== Namespace

`Plenty\Modules\Category\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|categoryId
    a|The ID of the category
|link:http://php.net/int[int^]
    a|category1Id
    a|The ID of the category tree's 1st level. If 1st value is identical to category ID, category is of this level.
|link:http://php.net/int[int^]
    a|category2Id
    a|The ID of the category tree's 2nd level. If 2nd level value is identical to category ID, category is of this level. If 2nd level value is <strong>null</strong>, category is of a higher level.
|link:http://php.net/int[int^]
    a|category3Id
    a|The ID of the category tree's 3rd level. If 3rd level value is identical to category ID, category is of this level. If 2nd level value is <strong>null</strong>, category is of a higher level.
|link:http://php.net/int[int^]
    a|category4Id
    a|The ID of the category tree's 4th level. If 4th level value is identical to category ID, category is of this level. If 2nd level value is <strong>null</strong>, category is of a higher level.
|link:http://php.net/int[int^]
    a|category5Id
    a|The ID of the category tree's 5th level. If 5th level value is identical to category ID, category is of this level. If 2nd level value is <strong>null</strong>, category is of a higher level.
|link:http://php.net/int[int^]
    a|category6Id
    a|The ID of the category tree's 6th level. If 6th level value is identical to category ID, category is of this level. If 2nd level value is <strong>null</strong>, category is of a higher level.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[category_models_categorybranchmarketplace]]
==== CategoryBranchMarketplace

The CategoryBranchMarketplace model



===== Namespace

`Plenty\Modules\Category\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|plenty_category_branch_marketplace_branch_id
    a|
|link:http://php.net/int[int^]
    a|plenty_category_branch_marketplace_webstore_id
    a|
|link:http://php.net/float[float^]
    a|plenty_category_branch_marketplace_marketplace_id
    a|
|link:http://php.net/float[float^]
    a|plenty_category_branch_marketplace_marketplace_sub_id
    a|
|link:http://php.net/string[string^]
    a|plenty_category_branch_marketplace_delimiter
    a|
|link:http://php.net/string[string^]
    a|plenty_category_branch_marketplace_value1
    a|
|link:http://php.net/string[string^]
    a|plenty_category_branch_marketplace_value2
    a|
|link:http://php.net/string[string^]
    a|plenty_category_branch_marketplace_last_update
    a|
|        xref:Category.adoc#category_models_categorybranch[`CategoryBranch`]
    a|branch
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[category_models_categoryclient]]
==== CategoryClient

The Category Client



===== Namespace

`Plenty\Modules\Category\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|plentyId
    a|The unique plenty ID of the client (store) in which the category is visible. Several IDs can be separated by commas. If a subcategory is linked to a client, its parent categories will be linked to this client as well.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[category_models_categorydetails]]
==== CategoryDetails

CategoryDetails



===== Namespace

`Plenty\Modules\Category\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|categoryId
    a|The unique ID of the category these category details belong to
|link:http://php.net/int[int^]
    a|plentyId
    a|The unique plenty ID of the client (store) in which the category is visible. If a subcategory is linked to a client, its parent categories will be linked to this client as well.
|link:http://php.net/string[string^]
    a|lang
    a|The <a href="https://developers.plentymarkets.com/rest-doc/introduction#languages" target="_blank">language</a> of the category
|link:http://php.net/string[string^]
    a|name
    a|The name of the category. The same category name can be used more than once in different categories or on different category levels. However, category names must be unique within the same category or level.
|link:http://php.net/string[string^]
    a|description
    a|The category text. The description is inserted into the online store using template variables.
|link:http://php.net/string[string^]
    a|description2
    a|The category text 2. The description 2 is inserted into the online store using template variables.
|link:http://php.net/string[string^]
    a|shortDescription
    a|The short description of the category. The short description can be inserted into the store's design using template variables.
|link:http://php.net/string[string^]
    a|metaKeywords
    a|HTML meta keywords to tag the category for search engines. More than one keyword can be separated by commas.
|link:http://php.net/string[string^]
    a|metaDescription
    a|The meta description of the category. This description is analysed by search engines and displayed in search results. This text should be treated as an advertising text to maximise click-through from search engine result pages. Current recommended limit is 156 characters.
|link:http://php.net/string[string^]
    a|nameUrl
    a|The category name to be used for the category's URL. The same URL name can be used more than once in different categories or on different category levels. However, URL names must be unique within the same category or level. The URL name should not be changed once the category is indexed by search engines. If no URL name is specified, the name will automatically be used as the URL name when the category is created.<br />Important: Name should contain ASCII code only and no special characters. The following character strings may not be used as prefixes to URL names: a-, b-, c-, f-, fa-, p-, t-. These prefixes will be removed automatically. For instance, a-class will be changed to class automatically. However, the URL name aclass can be used for a category named A-class.
|link:http://php.net/string[string^]
    a|metaTitle
    a|This will be displayed as the title of a tab in the web browser and as a search result in search engines. If this is left blank, the category name will be used as the title. Current recommended limit is 50 characters. Longer titles will be cut off.
|link:http://php.net/string[string^]
    a|image
    a|The ID to the image1 of the category.
|link:http://php.net/string[string^]
    a|image2
    a|The ID to the image2 of the category.
|link:http://php.net/string[string^]
    a|imagePath
    a|The path to the image1 of the category.
|link:http://php.net/string[string^]
    a|image2Path
    a|The path to the image2 of the category.
|link:http://php.net/string[string^]
    a|previewUrl
    a|The category's URL.
|link:http://php.net/int[int^]
    a|position
    a|The position of the category within a category level.
|link:http://php.net/string[string^]
    a|itemListView
    a|The template the category is linked to for the category overview. The template determines what the category overview will look like for this category. This option is available for categories of the type <strong>Item</strong> only. Possible values: ItemViewCategoriesList, ItemViewCategoriesList2 to ItemViewCategoriesList10.
|link:http://php.net/string[string^]
    a|singleItemView
    a|The template the category is linked to for the single item view. The template determines the appearance of the single item design for this category. This option is available for categories of the type <strong>Item</strong> only. Possible values: ItemViewSingleItem, ItemViewSingleItem2 to ItemViewSingleItem5.
|link:http://php.net/string[string^]
    a|pageView
    a|
|link:http://php.net/bool[bool^]
    a|fulltext
    a|Flag that indicates if the complete category text, i.e. the complete description, will be searched.<ul><li>Y = Complete text will be searched.</li><li>N = Text will not be searched completely.</li></ul>
|link:http://php.net/string[string^]
    a|metaRobots
    a|Values from the meta element Robots are analyzed by Web crawlers. These values tell the crawler what it should do with the page and with the links on the page.<ul><li>all = Include this category in the search engine index and follow the links on the page.</li><li>index = Include in the search engine index.</li><li>nofollow = Do not follow the links on the page.</li><li>noindex = Do not include in the search engine index.</li><li>nofollow, noindex = Do not follow the links and do not include the category in the search engine index.</li></ul>
|link:http://php.net/string[string^]
    a|canonicalLink
    a|The URL of any category that contains the same content. This
will avoid duplicate content.
|link:http://php.net/string[string^]
    a|updatedAt
    a|The time the category details were last updated
|link:http://php.net/string[string^]
    a|updatedBy
    a|The user who last updated the category details
|        xref:Category.adoc#category_models_category[`Category`]
    a|category
    a|The category these category details are associated with.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[category_models_categoryitemcount]]
==== CategoryItemCount

CategoryItemCount



===== Namespace

`Plenty\Modules\Category\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|categoryId
    a|The unique ID of the category
|link:http://php.net/int[int^]
    a|webstoreId
    a|The ID of the client (store)
|link:http://php.net/int[int^]
    a|count
    a|The count of items
|link:http://php.net/string[string^]
    a|createdAt
    a|The date that the category item count was created.
|link:http://php.net/string[string^]
    a|updatedAt
    a|The date that the category item count was updated last.
|link:http://php.net/int[int^]
    a|variationCount
    a|The count of variations
|link:http://php.net/int[int^]
    a|customerClassId
    a|The ID of the customer class
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[category_models_categoryproperty]]
==== CategoryProperty

The Category Property



===== Namespace

`Plenty\Modules\Category\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|categoryId
    a|The unique ID of the category
|link:http://php.net/float[float^]
    a|marketId
    a|The unique ID of the referrer
|link:http://php.net/int[int^]
    a|plentyId
    a|The unique plenty ID of the client (store)
|link:http://php.net/string[string^]
    a|value
    a|The category of the referrer
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[category_models_categorytemplate]]
==== CategoryTemplate

Category Template



===== Namespace

`Plenty\Modules\Category\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|categoryId
    a|The unique ID of the category
|link:http://php.net/int[int^]
    a|plentyId
    a|The unique plenty ID of the client (store)
|link:http://php.net/string[string^]
    a|lang
    a|The language of the template
|link:http://php.net/string[string^]
    a|content
    a|The content of the template
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

