:table-caption!:
:example-caption!:
:source-highlighter: prettify
= Plentymarkets interface documentation


[[cloud_elasticsearch]]
== ElasticSearch

[[cloud_elasticsearch_contracts]]
===  Contracts
==== ElasticSearchMultiSearchRepositoryContract

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Contracts`






===== Methods

[source%nowrap, php]
----

public setIndex($index):Plenty\Modules\Cloud\ElasticSearch\Contracts\ElasticSearchMultiSearchRepositoryContract // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_contracts_elasticsearchmultisearchrepositorycontract[ElasticSearchMultiSearchRepositoryContract^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_index_indexinterface[IndexInterface^]

a|`$index`
|
|===


[source%nowrap, php]
----

public addSearch($search):Plenty\Modules\Cloud\ElasticSearch\Contracts\ElasticSearchMultiSearchRepositoryContract // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_contracts_elasticsearchmultisearchrepositorycontract[ElasticSearchMultiSearchRepositoryContract^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$search`
|
|===


[source%nowrap, php]
----

public execute():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    


==== ElasticSearchSearchRepositoryContract

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Contracts`






===== Methods

[source%nowrap, php]
----

public setIndex($index):Plenty\Modules\Cloud\ElasticSearch\Contracts\ElasticSearchSearchRepositoryContract // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_contracts_elasticsearchsearchrepositorycontract[ElasticSearchSearchRepositoryContract^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_index_indexinterface[IndexInterface^]

a|`$index`
|
|===


[source%nowrap, php]
----

public addSearch($search):Plenty\Modules\Cloud\ElasticSearch\Contracts\ElasticSearchSearchRepositoryContract // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_contracts_elasticsearchsearchrepositorycontract[ElasticSearchSearchRepositoryContract^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$search`
|
|===


[source%nowrap, php]
----

public execute():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_elasticsearch_lib]]
===  Lib
==== ElasticSearch

elastic search constants



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib`






===== Methods

[source%nowrap, php]
----

public static getKeyByLanguage($language):string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$language`
|
|===


[[cloud_lib]]
== Lib

[[cloud_lib_collapse]]
===  Collapse
==== BaseCollapse

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Collapse`






===== Methods

[source%nowrap, php]
----

public addInnerHit($innerHit):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_innerhit_innerhitinterface[InnerHitInterface^]

a|`$innerHit`
|
|===


[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    


==== CollapseInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Collapse`






===== Methods

[source%nowrap, php]
----

public addInnerHit($innerHit):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_innerhit_innerhitinterface[InnerHitInterface^]

a|`$innerHit`
|
|===


[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_lib_index]]
===  Index
==== IndexInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Index`






===== Methods

[source%nowrap, php]
----

public getType():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getPlentyId():int // <1>

----


    



===== Return type
    
<1> link:http://php.net/int[int^]
    

[source%nowrap, php]
----

public getVersion():int // <1>

----


    



===== Return type
    
<1> link:http://php.net/int[int^]
    

[source%nowrap, php]
----

public getDomain():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getIdentifier():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public isAvailable():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public isReady():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public getSettingsClassName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getMappingClassName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getDynamicTemplateClassName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getMeta():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getInfo():Plenty\Modules\Cloud\ElasticSearch\Lib\Index\Info\InfoInterface // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_info_infointerface[InfoInterface^]

    

[source%nowrap, php]
----

public resetAvailibilityStatus():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public hasUpdatedAt():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public hasAllField():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public getNext():Plenty\Modules\Cloud\ElasticSearch\Lib\Index\NextIndex // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_index_nextindex[NextIndex^]

    

[source%nowrap, php]
----

public getScrollRepositoryClassName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public refresh():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public getElasticSearchVersion():float // <1>

----


    



===== Return type
    
<1> link:http://php.net/float[float^]
    


==== NextIndex

to bew written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Index`






===== Methods

[source%nowrap, php]
----

public getType():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getVersion():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getDomain():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getSettingsClassName():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getMappingClassName():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getDynamicTemplateClassName():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getNext():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getScrollRepositoryClassName():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getElasticSearchVersion():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public hasUpdatedAt():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public isReady():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public maySynchronize():bool // <1>

----


    
Vorrübergehender Cheat - alles was noch keine Version hat,
darf nicht über die &quot;neuen&quot; Prozesse befüllt werden!


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public getPlentyId():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getIdentifier():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public isAvailable():bool // <1>

----


    
Checks whether ElasticSearch is generally available,
and whether the index has already been created.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public setRefreshInterval($value):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$value`
|
|===


[source%nowrap, php]
----

public resetAvailibilityStatus():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getMeta():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getInfo():Plenty\Modules\Cloud\ElasticSearch\Lib\Index\Info\BaseInfo // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_info_baseinfo[BaseInfo^]

    

[source%nowrap, php]
----

public mayBeQueuedForCreation():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public hasAllField():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public refresh():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    


==== ReindexIndex

to bew written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Index`






===== Methods

[source%nowrap, php]
----

public getType():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getVersion():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getDomain():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getMeta():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getSettingsClassName():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getMappingClassName():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getDynamicTemplateClassName():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getNext():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getScrollRepositoryClassName():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public hasUpdatedAt():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public isReady():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public maySynchronize():bool // <1>

----


    
Vorrübergehender Cheat - alles was noch keine Version hat,
darf nicht über die &quot;neuen&quot; Prozesse befüllt werden!


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public getPlentyId():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getIdentifier():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public isAvailable():bool // <1>

----


    
Checks whether ElasticSearch is generally available,
and whether the index has already been created.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public setRefreshInterval($value):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$value`
|
|===


[source%nowrap, php]
----

public resetAvailibilityStatus():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getInfo():Plenty\Modules\Cloud\ElasticSearch\Lib\Index\Info\BaseInfo // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_info_baseinfo[BaseInfo^]

    

[source%nowrap, php]
----

public mayBeQueuedForCreation():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public hasAllField():bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public refresh():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getElasticSearchVersion():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[[cloud_lib_output]]
===  Output
==== DevNullOutput

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Output`






===== Methods

[source%nowrap, php]
----

public write($message):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$message`
|
|===


[source%nowrap, php]
----

public info($message):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$message`
|
|===


[source%nowrap, php]
----

public error($message):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$message`
|
|===



==== OutputInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Output`






===== Methods

[source%nowrap, php]
----

public write($message):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$message`
|
|===


[source%nowrap, php]
----

public info($message):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$message`
|
|===


[source%nowrap, php]
----

public error($message):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$message`
|
|===


[[cloud_lib_processor]]
===  Processor
==== BaseProcessor

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Processor`






===== Methods

[source%nowrap, php]
----

public addMutator($mutator):Plenty\Modules\Cloud\ElasticSearch\Lib\Processor // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_processor[Processor^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_mutator_mutatorinterface[MutatorInterface^]

a|`$mutator`
|
|===


[source%nowrap, php]
----

public addCondition($conditions):Plenty\Modules\Cloud\ElasticSearch\Lib\Processor // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_processor[Processor^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_condition_conditioninterface[ConditionInterface^]

a|`$conditions`
|
|===


[source%nowrap, php]
----

public process($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getDependencies():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    


==== DocumentInnerHitsToRootProcessor

DocumentInnerHitsToRootProcessor



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Processor`






===== Methods

[source%nowrap, php]
----

public process($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getDependencies():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public addMutator($mutator):Plenty\Modules\Cloud\ElasticSearch\Lib\Processor // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_processor[Processor^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_mutator_mutatorinterface[MutatorInterface^]

a|`$mutator`
|
|===


[source%nowrap, php]
----

public addCondition($conditions):Plenty\Modules\Cloud\ElasticSearch\Lib\Processor // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_processor[Processor^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_condition_conditioninterface[ConditionInterface^]

a|`$conditions`
|
|===



==== DocumentProcessor

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Processor`






===== Methods

[source%nowrap, php]
----

public process($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getDependencies():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public addMutator($mutator):Plenty\Modules\Cloud\ElasticSearch\Lib\Processor // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_processor[Processor^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_mutator_mutatorinterface[MutatorInterface^]

a|`$mutator`
|
|===


[source%nowrap, php]
----

public addCondition($conditions):Plenty\Modules\Cloud\ElasticSearch\Lib\Processor // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_processor[Processor^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_condition_conditioninterface[ConditionInterface^]

a|`$conditions`
|
|===



==== ProcessorInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Processor`






===== Methods

[source%nowrap, php]
----

public process($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getDependencies():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    


==== SuggestionProcessor

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Processor`






===== Methods

[source%nowrap, php]
----

public getDependencies():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public addMutator($mutator):Plenty\Modules\Cloud\ElasticSearch\Lib\Processor // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_processor[Processor^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_mutator_mutatorinterface[MutatorInterface^]

a|`$mutator`
|
|===


[source%nowrap, php]
----

public addCondition($conditions):Plenty\Modules\Cloud\ElasticSearch\Lib\Processor // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_processor[Processor^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_condition_conditioninterface[ConditionInterface^]

a|`$conditions`
|
|===


[source%nowrap, php]
----

public process($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[[cloud_lib_search]]
===  Search
==== BaseSearch

Base class for different Search classes



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Search`






===== Methods

[source%nowrap, php]
----

public setIsSourceDisabled($isSourceDisabled):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$isSourceDisabled`
|
|===


[source%nowrap, php]
----

public addFilter($filter):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_type_typeinterface[TypeInterface^]

a|`$filter`
|
|===


[source%nowrap, php]
----

public addPostFilter($filter):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_type_typeinterface[TypeInterface^]

a|`$filter`
|
|===


[source%nowrap, php]
----

public addQuery($query):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_type_typeinterface[TypeInterface^]

a|`$query`
|
|===


[source%nowrap, php]
----

public addSource($source):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_source_sourceinterface[SourceInterface^]

a|`$source`
|
|===


[source%nowrap, php]
----

public setSorting($sorting):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_sorting_sortinginterface[SortingInterface^]

a|`$sorting`
|
|===


[source%nowrap, php]
----

public addAggregation($aggregation):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_aggregation_aggregationinterface[AggregationInterface^]

a|`$aggregation`
|
|===


[source%nowrap, php]
----

public addSuggestion($suggestion):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_suggestion_suggestioninterface[SuggestionInterface^]

a|`$suggestion`
|
|===


[source%nowrap, php]
----

public setPage($page, $rowsPerPage):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
|

|link:http://php.net/int[int^]
a|`$rowsPerPage`
|
|===


[source%nowrap, php]
----

public setPagination($pagination):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$pagination`
|
|===


[source%nowrap, php]
----

public setCollapse($collapse):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_collapse_collapseinterface[CollapseInterface^]

a|`$collapse`
|
|===


[source%nowrap, php]
----

public getSources():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public setScoreModifier($scoreModifier):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_scoremodifier_scoremodifierinterface[ScoreModifierInterface^]

a|`$scoreModifier`
|
|===


[source%nowrap, php]
----

public setMaxResultWindow($maxResults = 10000):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$maxResults`
|
|===


[source%nowrap, php]
----

public setIndex($index):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$index`
|
|===


[source%nowrap, php]
----

public isSearchAfter():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getFilterRaw():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getQueriesRaw():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getAggregationsRaw():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getSorting():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getScoreModifier():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public process($data):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    


==== SearchGroup

To be written...



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Search`






===== Methods

[source%nowrap, php]
----

public addSearch($search):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_search_searchinterface[SearchInterface^]

a|`$search`
|
|===


[source%nowrap, php]
----

public addFilter($filter):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_type_typeinterface[TypeInterface^]

a|`$filter`
|
|===


[source%nowrap, php]
----

public addQuery($query):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_type_typeinterface[TypeInterface^]

a|`$query`
|
|===



==== SearchInterface

To be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Search`






===== Methods

[source%nowrap, php]
----

public addFilter($filter):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_type_typeinterface[TypeInterface^]

a|`$filter`
|
|===


[source%nowrap, php]
----

public addQuery($query):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_type_typeinterface[TypeInterface^]

a|`$query`
|
|===


[source%nowrap, php]
----

public addSource($source):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_source_sourceinterface[SourceInterface^]

a|`$source`
|
|===


[source%nowrap, php]
----

public setSorting($sorting):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_sorting_sortinginterface[SortingInterface^]

a|`$sorting`
|
|===


[source%nowrap, php]
----

public addAggregation($aggregation):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_aggregation_aggregationinterface[AggregationInterface^]

a|`$aggregation`
|
|===


[source%nowrap, php]
----

public addSuggestion($suggestion):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_suggestion_suggestioninterface[SuggestionInterface^]

a|`$suggestion`
|
|===


[source%nowrap, php]
----

public process($data):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public setMaxResultWindow($maxResults = 10000):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$maxResults`
|
|===


[source%nowrap, php]
----

public setPagination($pagination):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$pagination`
|
|===


[source%nowrap, php]
----

public isSearchAfter():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_lib_sorting]]
===  Sorting
==== MultipleSorting

To be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Sorting`






===== Methods

[source%nowrap, php]
----

public addSorting($sorting):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_sorting_sortinginterface[SortingInterface^]

a|`$sorting`
|
|===


[source%nowrap, php]
----

public add($path, $order = \Plenty\Modules\Cloud\ElasticSearch\Lib\ElasticSearch::SORTING_ORDER_ASC):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$path`
|

|link:http://php.net/string[string^]
a|`$order`
|
|===


[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    


==== SingleNestedSorting

To be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Sorting`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    


==== SingleSorting

To be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Sorting`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    


==== SortingInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Sorting`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_lib_source]]
===  Source
==== ExcludeSource

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Source`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getPrefix():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public activateAll():Plenty\Modules\Cloud\ElasticSearch\Lib\Source\SourceInterface // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_source_sourceinterface[SourceInterface^]

    

[source%nowrap, php]
----

public activate():Plenty\Modules\Cloud\ElasticSearch\Lib\Source\SourceInterface // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_source_sourceinterface[SourceInterface^]

    

[source%nowrap, php]
----

public activateList($fields):Plenty\Modules\Cloud\ElasticSearch\Lib\Source // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_source[Source^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$fields`
|
|===



==== IncludeSource

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Source`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getPrefix():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public activateAll():Plenty\Modules\Cloud\ElasticSearch\Lib\Source\SourceInterface // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_source_sourceinterface[SourceInterface^]

    

[source%nowrap, php]
----

public activate():Plenty\Modules\Cloud\ElasticSearch\Lib\Source\SourceInterface // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_source_sourceinterface[SourceInterface^]

    

[source%nowrap, php]
----

public activateList($fields):Plenty\Modules\Cloud\ElasticSearch\Lib\Source // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_source[Source^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$fields`
|
|===



==== IndependentSource

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Source`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getPrefix():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public activateAll():Plenty\Modules\Cloud\ElasticSearch\Lib\Source\SourceInterface // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_source_sourceinterface[SourceInterface^]

    

[source%nowrap, php]
----

public activate():Plenty\Modules\Cloud\ElasticSearch\Lib\Source\SourceInterface // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_source_sourceinterface[SourceInterface^]

    

[source%nowrap, php]
----

public activateList($fields):Plenty\Modules\Cloud\ElasticSearch\Lib\Source // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_source[Source^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$fields`
|
|===



==== SourceInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Source`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_collapse]]
== Collapse

[[cloud_collapse_innerhit]]
===  InnerHit
==== BaseInnerHit

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Collapse\InnerHit`






===== Methods

[source%nowrap, php]
----

public setSorting($sorting):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_sorting_sortinginterface[SortingInterface^]

a|`$sorting`
|
|===


[source%nowrap, php]
----

public setSource($source):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_source_sourceinterface[SourceInterface^]

a|`$source`
|
|===


[source%nowrap, php]
----

public getName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    


==== InnerHitInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Collapse\InnerHit`






===== Methods

[source%nowrap, php]
----

public getName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_data]]
== Data

[[cloud_data_document]]
===  Document
==== DocumentInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Data\Document`






===== Methods

[source%nowrap, php]
----

public getIndex():Plenty\Modules\Cloud\ElasticSearch\Lib\Index\IndexInterface // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_index_indexinterface[IndexInterface^]

    

[source%nowrap, php]
----

public getSize():int // <1>

----


    



===== Return type
    
<1> link:http://php.net/int[int^]
    

[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_index]]
== Index

[[cloud_index_info]]
===  Info
==== BaseInfo

to bew written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Index\Info`






===== Methods

[source%nowrap, php]
----

public get($key, $default = null):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|

|link:miscellaneous#miscellaneous__[^]

a|`$default`
|
|===


[source%nowrap, php]
----

public set($key, $value):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|

|link:miscellaneous#miscellaneous__[^]

a|`$value`
|
|===


[source%nowrap, php]
----

public remove($key):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===



==== InfoInterface

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Index\Info`






===== Methods

[source%nowrap, php]
----

public get($key, $default = null):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|

|link:miscellaneous#miscellaneous__[^]

a|`$default`
|
|===


[source%nowrap, php]
----

public set($key, $value):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|

|link:miscellaneous#miscellaneous__[^]

a|`$value`
|
|===


[source%nowrap, php]
----

public remove($key):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===


[[cloud_index_settings]]
===  Settings
==== SettingsInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Index\Settings`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_mapping]]
== Mapping

[[cloud_mapping_property]]
===  Property
==== PropertyInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Index\Mapping\Property`






===== Methods

[source%nowrap, php]
----

public setIndex($index):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_index_indexinterface[IndexInterface^]

a|`$index`
|
|===


[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_type]]
== Type

[[cloud_type_complex]]
===  Complex
==== ComplexPropertyInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Index\Mapping\Property\Type\Complex`






===== Methods

[source%nowrap, php]
----

public getProperties():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public addProperty($property):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_property_propertyinterface[PropertyInterface^]

a|`$property`
|
|===


[source%nowrap, php]
----

public setIndex($index):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_index_indexinterface[IndexInterface^]

a|`$index`
|
|===


[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_type_query]]
===  Query
==== MultiMatchQuery

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Type\Query`






===== Methods

[source%nowrap, php]
----

public addField($field, $boost):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|

|link:http://php.net/int[int^]
a|`$boost`
|
|===


[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public setType($type):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$type`
|
|===


[source%nowrap, php]
----

public setOperator($operator):Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Type\Query\MultiMatchQuery // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_query_multimatchquery[MultiMatchQuery^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$operator`
|
|===


[source%nowrap, php]
----

public setFuzzy($fuzzy):Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Type\Query\MultiMatchQuery // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_query_multimatchquery[MultiMatchQuery^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$fuzzy`
|
|===


[[cloud_type_scoremodifier]]
===  ScoreModifier
==== RandomScore

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Type\ScoreModifier`






===== Methods

[source%nowrap, php]
----

public getFunction():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getBoostMode():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getSeed():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public setSeed($seed):Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Type\ScoreModifier\RandomScore // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_scoremodifier_randomscore[RandomScore^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$seed`
|
|===


[source%nowrap, php]
----

public setQuery($query):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$query`
|
|===


[source%nowrap, php]
----

public toArray():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    


==== ScoreModifierInterface

To be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Type\ScoreModifier`






===== Methods

[source%nowrap, php]
----

public setQuery($query):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$query`
|
|===


[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_statement]]
== Statement

[[cloud_statement_filter]]
===  Filter
==== MultiMatchFilter

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Statement\Filter`






===== Methods

[source%nowrap, php]
----

public addField($field, $boost):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|

|link:http://php.net/int[int^]
a|`$boost`
|
|===


[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public setType($type):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$type`
|
|===


[source%nowrap, php]
----

public setOperator($operator):Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Statement\Filter\MultiMatchFilter // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_filter_multimatchfilter[MultiMatchFilter^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$operator`
|
|===


[source%nowrap, php]
----

public setFuzzy($fuzzy):Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Statement\Filter\MultiMatchFilter // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_filter_multimatchfilter[MultiMatchFilter^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$fuzzy`
|
|===


[[cloud_query]]
== Query

[[cloud_query_statement]]
===  Statement
==== StatementInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Statement`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_query_type]]
===  Type
==== TypeInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Query\Type`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_search]]
== Search

[[cloud_search_aggregation]]
===  Aggregation
==== AggregationInterface

To be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Search\Aggregation`






===== Methods

[source%nowrap, php]
----

public addSource($source):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_source_sourceinterface[SourceInterface^]

a|`$source`
|
|===


[source%nowrap, php]
----

public process($data):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_search_document]]
===  Document
==== DocumentSearch

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Search\Document`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public process($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getFilter():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getPostFilter():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getQuery():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getAggregations():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getSuggestions():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getSources():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public addDependenciesToSource($sources):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$sources`
|
|===


[source%nowrap, php]
----

public getName():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public setName($name):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$name`
|
|===


[source%nowrap, php]
----

public setIsSourceDisabled($isSourceDisabled):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$isSourceDisabled`
|
|===


[source%nowrap, php]
----

public addFilter($filter):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_type_typeinterface[TypeInterface^]

a|`$filter`
|
|===


[source%nowrap, php]
----

public addPostFilter($filter):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_type_typeinterface[TypeInterface^]

a|`$filter`
|
|===


[source%nowrap, php]
----

public addQuery($query):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_type_typeinterface[TypeInterface^]

a|`$query`
|
|===


[source%nowrap, php]
----

public addSource($source):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_source_sourceinterface[SourceInterface^]

a|`$source`
|
|===


[source%nowrap, php]
----

public setSorting($sorting):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_sorting_sortinginterface[SortingInterface^]

a|`$sorting`
|
|===


[source%nowrap, php]
----

public addAggregation($aggregation):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_aggregation_aggregationinterface[AggregationInterface^]

a|`$aggregation`
|
|===


[source%nowrap, php]
----

public addSuggestion($suggestion):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_suggestion_suggestioninterface[SuggestionInterface^]

a|`$suggestion`
|
|===


[source%nowrap, php]
----

public setPage($page, $rowsPerPage):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
|

|link:http://php.net/int[int^]
a|`$rowsPerPage`
|
|===


[source%nowrap, php]
----

public setPagination($pagination):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$pagination`
|
|===


[source%nowrap, php]
----

public setCollapse($collapse):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_collapse_collapseinterface[CollapseInterface^]

a|`$collapse`
|
|===


[source%nowrap, php]
----

public setScoreModifier($scoreModifier):Plenty\Modules\Cloud\ElasticSearch\Lib\Search // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_lib_search[Search^]

    

.*Parameters*
|===
|Type |Name |Description
|link:cloud#cloud_scoremodifier_scoremodifierinterface[ScoreModifierInterface^]

a|`$scoreModifier`
|
|===


[source%nowrap, php]
----

public setMaxResultWindow($maxResults = 10000):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$maxResults`
|
|===


[source%nowrap, php]
----

public setIndex($index):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$index`
|
|===


[source%nowrap, php]
----

public isSearchAfter():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getFilterRaw():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getQueriesRaw():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getAggregationsRaw():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getSorting():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getScoreModifier():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[[cloud_search_suggestion]]
===  Suggestion
==== SuggestionInterface

To be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Search\Suggestion`






===== Methods

[source%nowrap, php]
----

public setText($text):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\Suggestion // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_search_suggestion[Suggestion^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$text`
|
|===


[source%nowrap, php]
----

public process($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public toArray():array // <1>

----


    
Get the instance as an array.


===== Return type
    
<1> link:http://php.net/array[array^]
    


==== TermSuggestion

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Search\Suggestion`






===== Methods

[source%nowrap, php]
----

public toArray():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public process($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public setText($text):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\Suggestion // <1>

----


    



===== Return type
    
<1> link:cloud#cloud_search_suggestion[Suggestion^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$text`
|
|===


[source%nowrap, php]
----

public getName():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getField():string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

[[cloud_source]]
== Source

[[cloud_source_condition]]
===  Condition
==== ConditionInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Source\Condition`






===== Methods

[source%nowrap, php]
----

public isValid($document):bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$document`
|
|===


[[cloud_source_mutator]]
===  Mutator
==== BaseMutator

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Source\Mutator`






===== Methods

[source%nowrap, php]
----

public getDependencies():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public mutate($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===



==== MutatorInterface

to be written



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Source\Mutator`






===== Methods

[source%nowrap, php]
----

public mutate($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public getDependencies():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_mutator]]
== Mutator

[[cloud_mutator_builtin]]
===  BuiltIn
==== LanguageMutator

foo



===== Namespace

`Plenty\Modules\Cloud\ElasticSearch\Lib\Source\Mutator\BuiltIn`






===== Methods

[source%nowrap, php]
----

public mutate($data):array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public addLanguage($language):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$language`
|
|===


[source%nowrap, php]
----

public setLanguages($languages):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$languages`
|
|===


[source%nowrap, php]
----

public setSetLanguageAsIndex($setLanguageAsIndex):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$setLanguageAsIndex`
|
|===


[source%nowrap, php]
----

public static isSeqArray($array):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:miscellaneous#miscellaneous__[^]

a|`$array`
|
|===


[source%nowrap, php]
----

public getDependencies():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[[cloud_storage]]
== Storage

[[cloud_storage_models]]
===  Models
==== StorageObject

Represent a storage object



===== Namespace

`Plenty\Modules\Cloud\Storage\Models`





.Properties
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    |key
    |
|link:http://php.net/string[string^]
    |lastModified
    |
|link:http://php.net/array[array^]
    |metaData
    |
|link:http://php.net/string[string^]
    |eTag
    |
|link:http://php.net/int[int^]
    |size
    |
|link:http://php.net/string[string^]
    |storageClass
    |
|link:http://php.net/string[string^]
    |body
    |
|link:http://php.net/string[string^]
    |contentType
    |
|link:http://php.net/string[string^]
    |contentLength
    |
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----


    
Returns this model as an array.




==== StorageObjectList

Represent a list of storage objects



===== Namespace

`Plenty\Modules\Cloud\Storage\Models`





.Properties
|===
|Type |Name |Description

|link:http://php.net/bool[bool^]
    |isTruncated
    |
|link:http://php.net/string[string^]
    |nextContinuationToken
    |
|link:http://php.net/array[array^]
    |objects
    |
|link:http://php.net/array[array^]
    |commonPrefixes
    |
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----


    
Returns this model as an array.



