

[[comment_comment]]
== Comment

[[comment_comment_contracts]]
===  Contracts
[[comment_contracts_commentrepositorycontract]]
==== CommentRepositoryContract

Get, create, update and delete comments.



===== Namespace

`Plenty\Modules\Comment\Contracts`






===== Methods

[source%nowrap, php]
----

public getComment($commentId):Plenty\Modules\Comment\Models\Comment

----

    


====== *Return type:*        xref:Comment.adoc#comment_models_comment[`Comment`]


Get a comment

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$commentId`
a|The ID of the comment
|===


[source%nowrap, php]
----

public listComments():Illuminate\Support\Collection

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


List comments

[source%nowrap, php]
----

public createComment($data, $suppressEvent = false):Plenty\Modules\Comment\Models\Comment

----

    


====== *Return type:*        xref:Comment.adoc#comment_models_comment[`Comment`]


Create a comment

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data

|link:http://php.net/bool[bool^]
a|`$suppressEvent`
a|Whether to suppress the created event or not.
|===


[source%nowrap, php]
----

public deleteComment($commentId):void

----

    





Delete a comment

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$commentId`
a|The ID of the comment
|===


[source%nowrap, php]
----

public updateComment($data, $commentId):Plenty\Modules\Comment\Models\Comment

----

    


====== *Return type:*        xref:Comment.adoc#comment_models_comment[`Comment`]


Update a comment

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|

|link:http://php.net/int[int^]
a|`$commentId`
a|
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[[comment_comment_models]]
===  Models
[[comment_models_comment]]
==== Comment

The comment model can be one of the following types: category, contact, order, item_variation, order_item, specified by the referenceType.



===== Namespace

`Plenty\Modules\Comment\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the comment
|link:http://php.net/string[string^]
    a|referenceType
    a|The reference type. Valid types are:
<ul>
	<li>category</li>
	<li>contact</li>
	<li>order</li>
 <li>item_variation</li>
 <li>order_item</li>
	</ul>
|link:http://php.net/int[int^]
    a|referenceValue
    a|The reference value
|link:http://php.net/int[int^]
    a|userId
    a|The ID of the user
|
    a|createdAt
    a|The date when the comment was created
|link:http://php.net/string[string^]
    a|text
    a|The comment text
|link:http://php.net/bool[bool^]
    a|isVisibleForContact
    a|If true, the comment is visible for the associated contact.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

