:table-caption!:
:example-caption!:
:source-highlighter: prettify
= Plentymarkets interface documentation


[[contentcache_contentcachelink]]
== ContentCacheLink

[[contentcache_contentcachelink_models]]
===  Models
==== ContentCacheLink

Eloquent model representing a Content Cache Link.



===== Namespace

`Plenty\Modules\ContentCache\ContentCacheLink\Models`





.Properties
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    |id
    |
|link:http://php.net/int[int^]
    |plentyId
    |
|link:http://php.net/string[string^]
    |linkType
    |
|link:http://php.net/string[string^]
    |cacheKey
    |
|link:http://php.net/int[int^]
    |linkId
    |
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----


    
Returns this model as an array.



[[contentcache_contentcache]]
== ContentCache

[[contentcache_contentcache_contentcachesettings]]
===  ContentCacheSettings
==== ContentCacheSettings

Eloquent model representing the Content Cache Settings.



===== Namespace

`Plenty\Modules\ContentCache\ContentCacheSettings`





.Properties
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    |plentyId
    |
|link:http://php.net/bool[bool^]
    |contentCacheActive
    |
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----


    
Returns this model as an array.



[[contentcache_contentcache_contracts]]
===  Contracts
==== ContentCacheInvalidationRepositoryContract

Interface for content cache invalidation



===== Namespace

`Plenty\Modules\ContentCache\Contracts`






===== Methods

[source%nowrap, php]
----

public invalidateVariationIds($variationIds, $plentyId = null):void // <1>

----


    
Invalidate all cache entries related to given variation ids.


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$variationIds`
|Ids of the variation to invalidate cache entries for

|link:http://php.net/int[int^]
a|`$plentyId`
|
|===


[source%nowrap, php]
----

public invalidateItemIds($itemIds, $plentyId = null):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$itemIds`
|

|link:http://php.net/int[int^]
a|`$plentyId`
|
|===


[source%nowrap, php]
----

public invalidateAll($plentyId = null):void // <1>

----


    
Invalidate all cache entries related to given plenty id.


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$plentyId`
|
|===


[source%nowrap, php]
----

public invalidateUri($uri):void // <1>

----


    
Invalidate cache entries by URI


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$uri`
|
|===


[source%nowrap, php]
----

public storeInvalidationStacks():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    


==== ContentCacheRepositoryContract

Save and retrieve values to or from the content cache



===== Namespace

`Plenty\Modules\ContentCache\Contracts`






===== Methods

[source%nowrap, php]
----

public enableCacheForResponse():void // <1>

----


    
Enable content caching for current response so next request on this resource will be delivered from content cache.


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public linkVariationsToResponse($variationIds):void // <1>

----


    
Link variations to current response.


===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$variationIds`
|Ids of variations referenced by the current response.
|===



==== ContentCacheSettingsRepositoryContract

Interface for content cache settings



===== Namespace

`Plenty\Modules\ContentCache\Contracts`






===== Methods

[source%nowrap, php]
----

public getSettings($plentyId):Plenty\Modules\ContentCache\ContentCacheSettings\ContentCacheSettings // <1>

----


    



===== Return type
    
<1> link:contentcache#contentcache_contentcachesettings_contentcachesettings[ContentCacheSettings^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$plentyId`
|
|===


[source%nowrap, php]
----

public getSettingsMultiple($plentyIds):void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$plentyIds`
|
|===


[source%nowrap, php]
----

public saveSettings($plentyId, $contentCacheActive):Plenty\Modules\ContentCache\ContentCacheSettings\ContentCacheSettings // <1>

----


    



===== Return type
    
<1> link:contentcache#contentcache_contentcachesettings_contentcachesettings[ContentCacheSettings^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$plentyId`
|

|link:http://php.net/bool[bool^]
a|`$contentCacheActive`
|
|===


