:table-caption!:
:example-caption!:
:source-highlighter: prettify

[[contentbuilder_contentbuilder]]
= ContentBuilder

[[contentbuilder_contentbuilder_contracts]]
==  Contracts
=== ContentLinkRepositoryContract

This module is deprecated. Use module &#039;Shop Builder&#039; instead.


==== Namespace

`Plenty\Modules\ContentBuilder\Contracts`






==== Methods

[source%nowrap, php]
----

public listContentsLinks($page = 1, $itemsPerPage = 50, $with = [], $filters = []):Plenty\Repositories\Models\PaginatedResult // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous_models_paginatedresult[PaginatedResult^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
|

|link:http://php.net/array[array^]
a|`$with`
|

|link:http://php.net/array[array^]
a|`$filters`
|
|===


[source%nowrap, php]
----

public getContentLink($contentLinkId):void // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentLinkId`
|
|===


[source%nowrap, php]
----

public createContentLink($data):void // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|
|===


[source%nowrap, php]
----

public updateContentLink($data, $contentLinkId):void // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|Request data

|link:http://php.net/int[int^]
a|`$contentLinkId`
|The ID of the content link
|===


[source%nowrap, php]
----

public getContentLinksForContainer($container, $setId = null):void // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$container`
|

|link:http://php.net/int[int^]
a|`$setId`
|
|===


[source%nowrap, php]
----

public clearCriteria():void // <1>

----


    
Resets all Criteria filters by creating a new instance of the builder object.


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public applyCriteriaFromFilters():void // <1>

----


    
Applies criteria classes to the current repository.


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public setFilters($filters = []):void // <1>

----


    
Sets the filter array.


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
|
|===


[source%nowrap, php]
----

public getFilters():void // <1>

----


    
Returns the filter array.


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getConditions():void // <1>

----


    
Returns a collection of parsed filters as Condition object


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public clearFilters():void // <1>

----


    
Clears the filter array.


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    


=== ContentRepositoryContract

This module is deprecated. Use module &#039;Shop Builder&#039; instead.


==== Namespace

`Plenty\Modules\ContentBuilder\Contracts`






==== Methods

[source%nowrap, php]
----

public listContents($page = 1, $itemsPerPage = 50, $with = [], $filters = []):Plenty\Repositories\Models\PaginatedResult // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous_models_paginatedresult[PaginatedResult^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
|

|link:http://php.net/array[array^]
a|`$with`
|

|link:http://php.net/array[array^]
a|`$filters`
|
|===


[source%nowrap, php]
----

public listAllContents():array // <1>

----


    



==== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getContent($contentId):void // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentId`
|
|===


[source%nowrap, php]
----

public getContentsByPage($pageIdentifier):Illuminate\Support\Collection // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous_support_collection[Collection^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$pageIdentifier`
|
|===


[source%nowrap, php]
----

public createContent($dataProviderName):void // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$dataProviderName`
|
|===


[source%nowrap, php]
----

public updateContent($data, $contentId):void // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
|Request data

|link:http://php.net/int[int^]
a|`$contentId`
|The ID of the content
|===


[source%nowrap, php]
----

public clearCriteria():void // <1>

----


    
Resets all Criteria filters by creating a new instance of the builder object.


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public applyCriteriaFromFilters():void // <1>

----


    
Applies criteria classes to the current repository.


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public setFilters($filters = []):void // <1>

----


    
Sets the filter array.


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
|
|===


[source%nowrap, php]
----

public getFilters():void // <1>

----


    
Returns the filter array.


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public getConditions():void // <1>

----


    
Returns a collection of parsed filters as Condition object


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

[source%nowrap, php]
----

public clearFilters():void // <1>

----


    
Clears the filter array.


==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    


=== ContentStorageRepositoryContract

This module is deprecated. Use module &#039;Shop Builder&#039; instead.


==== Namespace

`Plenty\Modules\ContentBuilder\Contracts`






==== Methods

[source%nowrap, php]
----

public createContentData($contentId, $widgetData):void // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentId`
|

|link:http://php.net/array[array^]
a|`$widgetData`
|
|===


[source%nowrap, php]
----

public getContentData($contentId):void // <1>

----


    



==== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentId`
|
|===



=== Widget

This module is deprecated. Use module &#039;Shop Builder&#039; instead.


==== Namespace

`Plenty\Modules\ContentBuilder\Contracts`






==== Methods

[source%nowrap, php]
----

public getPreview($widgetSettings = [], $children = []):string // <1>

----


    
Get the html representation of the widget


==== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$widgetSettings`
|

|link:http://php.net/array[array^]
a|`$children`
|
|===


[source%nowrap, php]
----

public render($widgetSettings = [], $children = []):string // <1>

----


    
Render the widget


==== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$widgetSettings`
|

|link:http://php.net/array[array^]
a|`$children`
|
|===


[[contentbuilder_contentbuilder_models]]
==  Models
=== Content

This module is deprecated. Use module &#039;Shop Builder&#039; instead.


==== Namespace

`Plenty\Modules\ContentBuilder\Models`





.Properties
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    |id
    |The ID of the content
|link:http://php.net/string[string^]
    |dataProviderName
    |The name of the data provider
|link:http://php.net/string[string^]
    |contentData
    |The data of the content
|link:miscellaneous#miscellaneous__[^]

    |createdAt
    |The date when the content was created
|link:miscellaneous#miscellaneous__[^]

    |updatedAt
    |The date when the content was last updated
|link:http://php.net/string[string^]
    |type
    |The type of the content
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----


    
Returns this model as an array.




=== ContentLink

This module is deprecated. Use module &#039;Shop Builder&#039; instead.


==== Namespace

`Plenty\Modules\ContentBuilder\Models`





.Properties
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    |id
    |The ID of the content link
|link:http://php.net/int[int^]
    |contentId
    |The ID of the content
|link:http://php.net/string[string^]
    |containerName
    |The name of the container
|link:http://php.net/int[int^]
    |pluginSetId
    |The Id of the plugin set
|link:miscellaneous#miscellaneous__[^]

    |createdAt
    |The date when the content was created
|link:miscellaneous#miscellaneous__[^]

    |updatedAt
    |The date when the content was last updated
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----


    
Returns this model as an array.



