:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[contentcache_cacheblocks]]
== CacheBlocks

[[contentcache_cacheblocks_contracts]]
===  Contracts
[[contentcache_contracts_cachetagrepositorycontract]]
==== CacheTagRepositoryContract

Add tags to content cache entries for tag based invalidation.



===== Namespace

`Plenty\Modules\ContentCache\CacheBlocks\Contracts`






===== Methods

[source%nowrap, php]
[#maketaggable]
----

public makeTaggable($variableName, $factory, $dataType = &quot;&quot;):void

----







Watch for accesses on a global twig variable and add all related cache tags on use.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$variableName`
|link:http://php.net/string[string^]
a|

a|`$factory`
|link:http://php.net/callable[callable^]
a|

a|`$dataType`
|link:http://php.net/string[string^]
a|
|===


[[contentcache_contentcachelink]]
== ContentCacheLink

[[contentcache_contentcachelink_models]]
===  Models
[[contentcache_models_contentcachelink]]
==== ContentCacheLink

Eloquent model representing a Content Cache Link.



===== Namespace

`Plenty\Modules\ContentCache\ContentCacheLink\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|
|plentyId
    |link:http://php.net/int[int^]
    a|
|linkType
    |link:http://php.net/string[string^]
    a|
|cacheKey
    |link:http://php.net/string[string^]
    a|
|linkId
    |link:http://php.net/int[int^]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[contentcache_contentcache]]
== ContentCache

[[contentcache_contentcache_contentcachesettings]]
===  ContentCacheSettings
[[contentcache_contentcachesettings_contentcachesettings]]
==== ContentCacheSettings

Eloquent model representing the Content Cache Settings.



===== Namespace

`Plenty\Modules\ContentCache\ContentCacheSettings`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|plentyId
    |link:http://php.net/int[int^]
    a|
|contentCacheActive
    |link:http://php.net/bool[bool^]
    a|
|version
    |link:http://php.net/int[int^]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[contentcache_contentcache_contracts]]
===  Contracts
[[contentcache_contracts_contentcacheinvalidationrepositorycontract]]
==== ContentCacheInvalidationRepositoryContract

Interface for content cache invalidation



===== Namespace

`Plenty\Modules\ContentCache\Contracts`






===== Methods

[source%nowrap, php]
[#invalidatevariationids]
----

public invalidateVariationIds($variationIds, $plentyId = null):void

----







Invalidate all cache entries related to given variation IDs.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$variationIds`
|link:http://php.net/array[array^]
a|IDs of the variation to invalidate cache entries for

a|`$plentyId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#invalidateitemids]
----

public invalidateItemIds($itemIds, $plentyId = null):void

----







Invalidate cache entries for specified item IDs.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemIds`
|link:http://php.net/array[array^]
a|

a|`$plentyId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#invalidateall]
----

public invalidateAll($plentyId = null, $bypassActiveCheck = false):void

----







Invalidate all cache entries related to given plenty ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyId`
|link:http://php.net/int[int^]
a|

a|`$bypassActiveCheck`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#invalidateuri]
----

public invalidateUri($uri):void

----







Invalidate cache entries by URI.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uri`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#storeinvalidationstacks]
----

public storeInvalidationStacks():void

----







Store all collected invalidation entries in the database.


[[contentcache_contracts_contentcachequeryparamsrepositorycontract]]
==== ContentCacheQueryParamsRepositoryContract

Interface for registering request query parameters which should be handled by the content cache



===== Namespace

`Plenty\Modules\ContentCache\Contracts`






===== Methods

[source%nowrap, php]
[#registerexcluded]
----

public registerExcluded($queryParams):void

----







Register an array of query parameters to be excluded from the content cache.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$queryParams`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#registerincluded]
----

public registerIncluded($queryParams):void

----







Register an array of query params to be considered when determining the requested cache entry.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$queryParams`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getregistered]
----

public getRegistered($key = &quot;&quot;):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|'included' or 'excluded'
|===



[[contentcache_contracts_contentcacherepositorycontract]]
==== ContentCacheRepositoryContract

Save and retrieve values to or from the content cache



===== Namespace

`Plenty\Modules\ContentCache\Contracts`






===== Methods

[source%nowrap, php]
[#enablecacheforresponse]
----

public enableCacheForResponse($options = []):void

----







Enable content caching for current response so next request on this resource will be delivered from content cache.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Additional options to be considered when handling cache entries. Possible options are:
- enableQueryParams: boolean Set to true to enable caching pages having query params.
|===


[source%nowrap, php]
[#disablecacheforresponse]
----

public disableCacheForResponse($reason = &quot;&quot;):void

----







Disable caching for current response because of any unwanted behavior.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$reason`
|link:http://php.net/string[string^]
a|Reason why the response is not cached.
|===


[source%nowrap, php]
[#linkvariationstoresponse]
----

public linkVariationsToResponse($variationIds):void

----







Link variations to current response.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$variationIds`
|link:http://php.net/array[array^]
a|Ids of variations referenced by the current response.
|===



[[contentcache_contracts_contentcachesettingsrepositorycontract]]
==== ContentCacheSettingsRepositoryContract

Interface for content cache settings



===== Namespace

`Plenty\Modules\ContentCache\Contracts`






===== Methods

[source%nowrap, php]
[#getsettings]
----

public getSettings($plentyId):Plenty\Modules\ContentCache\ContentCacheSettings\ContentCacheSettings

----




====== *Return type:*        xref:Contentcache.adoc#contentcache_contentcachesettings_contentcachesettings[`ContentCacheSettings`]


Get the content cache settings for the specified client.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyId`
|link:http://php.net/int[int^]
a|The plenty id of the client.
|===


[source%nowrap, php]
[#getsettingsmultiple]
----

public getSettingsMultiple($plentyIds):void

----







Get the content cache settings for multiple clients.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyIds`
|link:http://php.net/array[array^]
a|The plenty ids of the clients.
|===


[source%nowrap, php]
[#savesettings]
----

public saveSettings($plentyId, $contentCacheActive):Plenty\Modules\ContentCache\ContentCacheSettings\ContentCacheSettings

----




====== *Return type:*        xref:Contentcache.adoc#contentcache_contentcachesettings_contentcachesettings[`ContentCacheSettings`]


Save the content cache settings for the specified client.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyId`
|link:http://php.net/int[int^]
a|The plenty id of the client.

a|`$contentCacheActive`
|link:http://php.net/bool[bool^]
a|Flag that indicates the content cache active state.
|===


[source%nowrap, php]
[#getinvalidationdate]
----

public getInvalidationDate($plentyId):string

----







Get the date until when the content cache invalidation is deactivated.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyId`
|link:http://php.net/int[int^]
a|The plenty id of the client.
|===


[source%nowrap, php]
[#saveinvalidationdate]
----

public saveInvalidationDate($plentyId, $invalidationDate):void

----







Save the date until when the content cache invalidation is deactivated.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyId`
|link:http://php.net/int[int^]
a|The plenty id of the client.

a|`$invalidationDate`
|link:http://php.net/string[string^]
a|The date until when the invalidation is deactivated.
|===


[source%nowrap, php]
[#isinvalidationactive]
----

public isInvalidationActive($plentyId):bool

----







Check if the content cache invalidation is currently active.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyId`
|link:http://php.net/int[int^]
a|The plenty id of the client.
|===


[source%nowrap, php]
[#getinstantinvalidationcount]
----

public getInstantInvalidationCount($plentyId):int

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyId`
|link:http://php.net/int[int^]
a|The plenty id of the client.
|===


[source%nowrap, php]
[#invalidateinstantly]
----

public invalidateInstantly($plentyId):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyId`
|link:http://php.net/int[int^]
a|The plenty id of the client.
|===


