:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[cron_cron]]
== Cron

[[cron_cron_contracts]]
===  Contracts
[[cron_contracts_cronhandler]]
==== CronHandler

CronHandler interface for extending cron handlers.



===== Namespace

`Plenty\Modules\Cron\Contracts`





[[cron_cron_services]]
===  Services
[[cron_services_croncontainer]]
==== CronContainer

Register cron jobs



===== Namespace

`Plenty\Modules\Cron\Services`






===== Methods

[source%nowrap, php]
[#add]
----

public add($schedule, $handlerClass, $position):void

----







Use this method to add a handler class and a schedule time for your desired cron event. The action will then be
triggered according to the given schedule.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$schedule`
|link:http://php.net/int[int^]
a|The number of minutes for which the cron action should be scheduled.
Currently allowed are: 15, 20, 60 and 3600. You can also use constants like
`CronContainer::EVERY_FIFTEEN_MINUTES`, `CronContainer::EVERY_TWENTY_MINUTES`, `CronContainer::HOURLY`,
`CronContainer::DAILY`;

a|`$handlerClass`
|link:http://php.net/string[string^]
a|The handler class that should be triggered when the cron event is launched.
This class has to extend the CronHandler interface and implement the `handle()` method.

a|`$position`
|link:http://php.net/int[int^]
a|
|===


