

[[deletelog_deletelog]]
== DeleteLog

[[deletelog_deletelog_contracts]]
===  Contracts
[[deletelog_contracts_deletelogrepositorycontract]]
==== DeleteLogRepositoryContract

List delete log entries.



===== Namespace

`Plenty\Modules\DeleteLog\Contracts`






===== Methods

[source%nowrap, php]
----

public search($page, $itemsPerPage):Plenty\Repositories\Models\PaginatedResult

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List delete log entries

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|
|===


[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[[deletelog_deletelog_models]]
===  Models
[[deletelog_models_deletelog]]
==== DeleteLog

The delete log model



===== Namespace

`Plenty\Modules\DeleteLog\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|referenceType
    a|The type of the deleted record<ul><li>1 = Category</li><li>2 = Payment</li><li>3 = Order</li><li>4 = Customer</li><li>5 = Item</li><li>6 = Facet of the type Attribute</li><li>7 = Facet of the type Property</li><li>8 = Facet of the type Manufacturer</li><li>9 = Facet of the type Availability</li><li>10 = Unit</li><li>11 = Sales price</li><li>12 = Sales price link to variation</li><li>13 = Item variation</li></ul>
|link:http://php.net/int[int^]
    a|referenceValue
    a|The ID of the deleted record
|link:http://php.net/string[string^]
    a|userRealName
    a|The real name of the user who deleted the record
|link:http://php.net/string[string^]
    a|updatedAt
    a|The date and time that the record was deleted
|link:http://php.net/int[int^]
    a|userId
    a|The ID of the user who deleted the record
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

