:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[deletelog_deletelog]]
== DeleteLog

[[deletelog_deletelog_contracts]]
===  Contracts
[[deletelog_contracts_deletelogrepositorycontract]]
==== DeleteLogRepositoryContract

List delete log entries.



===== Namespace

`Plenty\Modules\DeleteLog\Contracts`






===== Methods

[source%nowrap, php]
[#search]
----

public search($page, $itemsPerPage):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List delete log entries

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[[deletelog_deletelog_models]]
===  Models
[[deletelog_models_deletelog]]
==== DeleteLog

The delete log model



===== Namespace

`Plenty\Modules\DeleteLog\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|referenceType
    |link:http://php.net/int[int^]
    a|The type of the deleted record<ul><li>1 = Category</li><li>2 = Payment</li><li>3 = Order</li><li>4 = Customer</li><li>5 = Item</li><li>6 = Facet of the type Attribute</li><li>7 = Facet of the type Property</li><li>8 = Facet of the type Manufacturer</li><li>9 = Facet of the type Availability</li><li>10 = Unit</li><li>11 = Sales price</li><li>12 = Sales price link to variation</li><li>13 = Item variation</li></ul>13 = Order item</li></ul>
|referenceValue
    |link:http://php.net/int[int^]
    a|The ID of the deleted record
|userRealName
    |link:http://php.net/string[string^]
    a|The real name of the user who deleted the record
|updatedAt
    |link:http://php.net/string[string^]
    a|The date and time that the record was deleted
|userId
    |link:http://php.net/int[int^]
    a|The ID of the user who deleted the record
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

