

[[document_document]]
== Document

[[document_document_contracts]]
===  Contracts
[[document_contracts_documentrepositorycontract]]
==== DocumentRepositoryContract

Download and list order documents as well as download, list, upload and delete category documents.



===== Namespace

`Plenty\Modules\Document\Contracts`






===== Methods

[source%nowrap, php]
----

public getDocumentPath($id):void

----

    





Get the path to a document

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
a|The ID of the document
|===


[source%nowrap, php]
----

public findById($id, $columns = []):Plenty\Modules\Document\Models\Document

----

    


====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Get a document

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
a|The ID of the document

|link:http://php.net/array[array^]
a|`$columns`
a|The columns to be loaded
|===


[source%nowrap, php]
----

public find($page = 1, $itemsPerPage = 50, $columns = [], $with = []):Plenty\Repositories\Models\PaginatedResult

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List documents

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|The page to get. The default page that will be returned is page 1.

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of orders to be displayed per page. The default number of orders per page is 50.

|link:http://php.net/array[array^]
a|`$columns`
a|The columns to be loaded

|link:http://php.net/array[array^]
a|`$with`
a|The relations to be loaded. Possible value is "references".
|===


[source%nowrap, php]
----

public uploadOrderDocuments($orderId, $type, $data):array

----

    





Upload order documents

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
a|The ID of the order

|link:http://php.net/string[string^]
a|`$type`
a|The document type. Supported types are 'invoiceExternal', 'deliveryNote', 'poDeliveryNote', 'orderConfirmation', 'offer', 'dunningLetter', 'returnNote', 'successConfirmation', 'correction', 'creditNoteExternal', 'reorder', 'uploaded'.

|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public deleteOrderDocument($orderId, $documentId):bool

----

    





Delete order document

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
a|The ID of the order

|link:http://php.net/int[int^]
a|`$documentId`
a|The ID of the document
|===


[source%nowrap, php]
----

public archiveOrderDocument($orderId, $documentId):void

----

    





Archive order document

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
a|The ID of the order

|link:http://php.net/int[int^]
a|`$documentId`
a|The ID of the document
|===


[source%nowrap, php]
----

public uploadCategoryDocuments($categoryId, $data):array

----

    





Upload category documents

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|The ID of the category

|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public deleteCategoryDocument($categoryId, $documentId):bool

----

    





Delete a category document.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
a|The ID of the category

|link:http://php.net/int[int^]
a|`$documentId`
a|The ID of the document
|===


[source%nowrap, php]
----

public uploadOrderShippingPackageDocuments($packageId, $type, $document):array

----

    





Uploads documents

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$packageId`
a|

|link:http://php.net/string[string^]
a|`$type`
a|

|link:http://php.net/string[string^]
a|`$document`
a|base64 encoded document
|===


[source%nowrap, php]
----

public findOrderShippingPackageDocuments($packageId, $type):array

----

    





Find documents

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$packageId`
a|

|link:http://php.net/string[string^]
a|`$type`
a|
|===


[source%nowrap, php]
----

public findCurrentOrderDocument($orderId, $type):Plenty\Modules\Document\Models\Document

----

    


====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Finds the current order document

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
a|

|link:http://php.net/string[string^]
a|`$type`
a|
|===


[source%nowrap, php]
----

public findRecentOrderDocument($orderId, $type):Plenty\Modules\Document\Models\Document

----

    


====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Finds order document.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
a|

|link:http://php.net/string[string^]
a|`$type`
a|
|===


[source%nowrap, php]
----

public deleteOrderShippingPackageDocuments($packageId):bool

----

    





Delets a document.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$packageId`
a|
|===


[source%nowrap, php]
----

public getDocumentStorageObject($key):void

----

    





Gets a document storage object.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$key`
a|
|===


[source%nowrap, php]
----

public uploadOrderReturnsDocuments($returnsId, $document):Plenty\Modules\Document\Models\Document

----

    


====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Uploads a specific document.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$returnsId`
a|

|link:http://php.net/string[string^]
a|`$document`
a|
|===


[source%nowrap, php]
----

public getOrderReturnsDocumentById($returnsId, $withLabel = false):Plenty\Modules\Document\Models\Document

----

    


====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Finds a document.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$returnsId`
a|

|link:http://php.net/bool[bool^]
a|`$withLabel`
a|
|===


[source%nowrap, php]
----

public generateOrderDocument($orderId, $type, $data):bool

----

    





Generate order document

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
a|The ID of the order

|link:http://php.net/int[int^]
a|`$type`
a|The document type

|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[[document_document_models]]
===  Models
[[document_models_document]]
==== Document

The document model contains information about actual documents.



===== Namespace

`Plenty\Modules\Document\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the document
|link:http://php.net/string[string^]
    a|type
    a|The type of the document. The following types are available:
                           <ul>
    <li>admin</li>
    <li>blog</li>
 <li>category</li>
 <li>correction_document</li>
 <li>credit_note</li>
    <li>credit_note_external</li>
       <li>customer</li>
 <li>delivery_note</li>
    <li>dunning_letter</li>
       <li>ebics_hash</li>
    <li>facet</li>
    <li>invoice</li>
    <li>invoice_external</li>
                               <li>pos_invoice</li>
                               <li>pos_invoice_cancellation</li>
 <li>item</li>
 <li>multi_credit_note</li>
    <li>multi_invoice</li>
       <li>offer</li>
    <li>order_confirmation</li>
       <li>pickup_delivery</li>
    <li>receipt</li>
                               <li>refund_reversal</li>
    <li>reorder</li>
    <li>repair_bill</li>
    <li>return_note</li>
       <li>reversal_document</li>
       <li>settlement_report</li>
    <li>success_confirmation</li>
    <li>ticket</li>
    <li>webshop</li>
  <li>webshop_customer</li>
    <li>z_report</li>
    <li>shipping_label</li>
    <li>shipping_export_label</li>
    <li>returns_label</li>
                               <li>reversal_dunning_letter</l>
</ul>
|link:http://php.net/int[int^]
    a|number
    a|The document number
|link:http://php.net/string[string^]
    a|numberWithPrefix
    a|The document number with prefix
|link:http://php.net/string[string^]
    a|path
    a|The path to the document
|link:http://php.net/int[int^]
    a|userId
    a|The ID of the user
|link:http://php.net/string[string^]
    a|source
    a|The source where the document was generated. Possible sources are 'klarna', 'soap', 'admin', 'hitmeister', 'paypal' and 'rest'.
|link:http://php.net/string[string^]
    a|displayDate
    a|The date displayed on the document
|link:http://php.net/string[string^]
    a|content
    a|The base64 encodedcontent of the document.
|
    a|createdAt
    a|The time the document was created
|
    a|updatedAt
    a|The time the document was last updated
|        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|references
    a|Collection of document references. The references available are:
<ul>
    <li>contacts</li>
    <li>orders</li>
    <li>webstores = refers to clients</li>
    <li>categories</li>
</ul>
|        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|contacts
    a|Collection of contacts that are associated with the document
|        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|orders
    a|Collection of orders that are associated with the document
|        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|webstores
    a|Collection of webstores that are associated with the document
|        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|categories
    a|Collection of categories that are associated with the document
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[document_models_documentreference]]
==== DocumentReference

The document reference model. A document reference allows you to assign a document to other models.



===== Namespace

`Plenty\Modules\Document\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|documentId
    a|The ID of the document
|link:http://php.net/string[string^]
    a|type
    a|The reference type. The following reference types are available:
                            <ul>
    <li>blog</li>
                               <li>cash_register</li>
                               <li>category</li>
    <li>customer</li>
 <li>facet</li>
    <li>facet_value</li>
    <li>item</li>
 <li>multishop</li>
    <li>order</li>
    <li>reorder</li>
 <li>ticket</li>
                               <li>warehouse</li>
                               <li>order_shipping_package</li>
</ul>
|link:http://php.net/string[string^]
    a|value
    a|The reference value (e.g. the ID of another model)
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

