:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[document_document]]
== Document

[[document_document_contracts]]
===  Contracts
[[document_contracts_documentrepositorycontract]]
==== DocumentRepositoryContract

Download and list order documents as well as download, list, upload and delete category documents.



===== Namespace

`Plenty\Modules\Document\Contracts`






===== Methods

[source%nowrap, php]
[#getdocumentpath]
----

public getDocumentPath($id):void

----







Get the path to a document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the document
|===


[source%nowrap, php]
[#findbyid]
----

public findById($id, $columns = [], $with = []):Plenty\Modules\Document\Models\Document

----




====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Get a document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the document

a|`$columns`
|link:http://php.net/array[array^]
a|The columns to be loaded

a|`$with`
|link:http://php.net/array[array^]
a|The relations to be loaded. Possible value is "references".
|===


[source%nowrap, php]
[#find]
----

public find($page = 1, $itemsPerPage = 50, $columns = [], $with = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List documents

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of orders to be displayed per page. The default number of orders per page is 50.

a|`$columns`
|link:http://php.net/array[array^]
a|The columns to be loaded

a|`$with`
|link:http://php.net/array[array^]
a|The relations to be loaded. Possible value is "references".
|===


[source%nowrap, php]
[#uploadorderdocuments]
----

public uploadOrderDocuments($orderId, $type, $data):array

----







Upload order documents

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order

a|`$type`
|link:http://php.net/string[string^]
a|The document type. Supported types are 'invoiceExternal', 'deliveryNote', 'poDeliveryNote', 'orderConfirmation', 'offer', 'dunningLetter', 'returnNote', 'successConfirmation', 'correction', 'creditNoteExternal', 'reorder', 'uploaded'.

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#deleteorderdocument]
----

public deleteOrderDocument($orderId, $documentId):bool

----







Delete order document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order

a|`$documentId`
|link:http://php.net/int[int^]
a|The ID of the document
|===


[source%nowrap, php]
[#archiveorderdocument]
----

public archiveOrderDocument($orderId, $documentId):void

----







Archive order document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order

a|`$documentId`
|link:http://php.net/int[int^]
a|The ID of the document
|===


[source%nowrap, php]
[#uploadcategorydocuments]
----

public uploadCategoryDocuments($categoryId, $data):array

----







Upload category documents

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$categoryId`
|link:http://php.net/int[int^]
a|The ID of the category

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#deletecategorydocument]
----

public deleteCategoryDocument($categoryId, $documentId):bool

----







Delete a category document.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$categoryId`
|link:http://php.net/int[int^]
a|The ID of the category

a|`$documentId`
|link:http://php.net/int[int^]
a|The ID of the document
|===


[source%nowrap, php]
[#uploadordershippingpackagedocuments]
----

public uploadOrderShippingPackageDocuments($packageId, $type, $document):array

----







Uploads documents

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$packageId`
|link:http://php.net/int[int^]
a|

a|`$type`
|link:http://php.net/string[string^]
a|

a|`$document`
|link:http://php.net/string[string^]
a|base64 encoded document
|===


[source%nowrap, php]
[#findordershippingpackagedocuments]
----

public findOrderShippingPackageDocuments($packageId, $type):array

----







Find documents

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$packageId`
|link:http://php.net/int[int^]
a|

a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#findcurrentorderdocument]
----

public findCurrentOrderDocument($orderId, $type, $includePending = false):Plenty\Modules\Document\Models\Document

----




====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Finds the current order document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|

a|`$type`
|link:http://php.net/string[string^]
a|

a|`$includePending`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#findrecentorderdocument]
----

public findRecentOrderDocument($orderId, $type, $includePending = false):Plenty\Modules\Document\Models\Document

----




====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Finds order document.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|

a|`$type`
|link:http://php.net/string[string^]
a|

a|`$includePending`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#deleteordershippingpackagedocuments]
----

public deleteOrderShippingPackageDocuments($packageId):bool

----







Delets a document.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$packageId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getdocumentstorageobject]
----

public getDocumentStorageObject($key):void

----







Gets a document storage object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|
a|
|===


[source%nowrap, php]
[#uploadorderreturnsdocuments]
----

public uploadOrderReturnsDocuments($returnsId, $document):Plenty\Modules\Document\Models\Document

----




====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Uploads a specific document.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$returnsId`
|link:http://php.net/int[int^]
a|

a|`$document`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getorderreturnsdocumentbyid]
----

public getOrderReturnsDocumentById($returnsId, $withLabel = false):Plenty\Modules\Document\Models\Document

----




====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Finds a document.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$returnsId`
|link:http://php.net/int[int^]
a|

a|`$withLabel`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#generateorderdocument]
----

public generateOrderDocument($orderId, $type, $data):bool

----







Generate order document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order

a|`$type`
|link:http://php.net/string[string^]
a|The document type

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[document_document_models]]
===  Models
[[document_models_document]]
==== Document

The document model contains information about actual documents.



===== Namespace

`Plenty\Modules\Document\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the document
|type
    |link:http://php.net/string[string^]
    a|The type of the document. The following types are available:
                           <ul>
    <li>admin</li>
    <li>blog</li>
 <li>category</li>
 <li>correction_document</li>
 <li>credit_note</li>
    <li>credit_note_external</li>
       <li>customer</li>
 <li>delivery_note</li>
    <li>dunning_letter</li>
       <li>ebics_hash</li>
    <li>facet</li>
    <li>invoice</li>
    <li>invoice_external</li>
                               <li>pos_invoice</li>
                               <li>pos_invoice_cancellation</li>
 <li>item</li>
 <li>multi_credit_note</li>
    <li>multi_invoice</li>
       <li>offer</li>
    <li>order_confirmation</li>
       <li>pickup_delivery</li>
    <li>receipt</li>
                               <li>refund_reversal</li>
    <li>reorder</li>
    <li>repair_bill</li>
    <li>return_note</li>
       <li>reversal_document</li>
       <li>settlement_report</li>
    <li>success_confirmation</li>
    <li>ticket</li>
    <li>webshop</li>
  <li>webshop_customer</li>
    <li>z_report</li>
    <li>shipping_label</li>
    <li>shipping_export_label</li>
    <li>returns_label</li>
                               <li>reversal_dunning_letter</l>
</ul>
|number
    |link:http://php.net/int[int^]
    a|The document number
|numberWithPrefix
    |link:http://php.net/string[string^]
    a|The document number with prefix
|path
    |link:http://php.net/string[string^]
    a|The path to the document
|userId
    |link:http://php.net/int[int^]
    a|The ID of the user
|source
    |link:http://php.net/string[string^]
    a|The source where the document was generated. Possible sources are 'klarna', 'soap', 'admin', 'hitmeister', 'paypal' and 'rest'.
|displayDate
    |link:http://php.net/string[string^]
    a|The date displayed on the document
|status
    |link:http://php.net/string[string^]
    a|The generation status of the document ("pending", "faulty" or "done"
|content
    |link:http://php.net/string[string^]
    a|The base64 encoded content of the document.
|createdAt
    |
    a|The time the document was created
|updatedAt
    |
    a|The time the document was last updated
|references
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|Collection of document references. The references available are:
<ul>
    <li>contacts</li>
    <li>orders</li>
    <li>webstores = refers to clients</li>
    <li>categories</li>
</ul>
|comment
    |        xref:Document.adoc#document_models_documentcomment[`DocumentComment`]
    a|The manual comment
|cancelledBy
    |        xref:Document.adoc#document_models_document[`Document`]
    a|The reference document that cancelled the current document, if any
|cancels
    |        xref:Document.adoc#document_models_document[`Document`]
    a|The reference document that is cancelled by the current document, if any
|contacts
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|Collection of contacts that are associated with the document
|orders
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|Collection of orders that are associated with the document
|webstores
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|Collection of webstores that are associated with the document
|categories
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|Collection of categories that are associated with the document
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_models_documentcomment]]
==== DocumentComment

The manual comment model for the document model .



===== Namespace

`Plenty\Modules\Document\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|documentId
    |link:http://php.net/int[int^]
    a|The id of the document.
|type
    |link:http://php.net/string[string^]
    a|The type of the text (comment).
|value
    |link:http://php.net/string[string^]
    a|The text value
|document
    |        xref:Document.adoc#document_models_document[`Document`]
    a|The related document.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_models_documentreference]]
==== DocumentReference

The document reference model. A document reference allows you to assign a document to other models.



===== Namespace

`Plenty\Modules\Document\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|documentId
    |link:http://php.net/int[int^]
    a|The ID of the document
|type
    |link:http://php.net/string[string^]
    a|The reference type. The following reference types are available:
                            <ul>
    <li>blog</li>
                               <li>cash_register</li>
                               <li>category</li>
    <li>customer</li>
 <li>facet</li>
    <li>facet_value</li>
    <li>item</li>
 <li>multishop</li>
    <li>order</li>
    <li>reorder</li>
 <li>ticket</li>
                               <li>warehouse</li>
                               <li>order_shipping_package</li>
</ul>
|value
    |link:http://php.net/string[string^]
    a|The reference value (e.g. the ID of another model)
|document
    |        xref:Document.adoc#document_models_document[`Document`]
    a|The document this reference belongs to
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

