:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[document_variables]]
== Variables

[[document_variables_contracts]]
===  Contracts
[[document_contracts_documentbuildervariablescontainercontract]]
==== DocumentBuilderVariablesContainerContract

A container service for DocumentBuilder variables and variable groups registration



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Contracts`






===== Methods

[source%nowrap, php]
[#registervariablegroup]
----

public registerVariableGroup($group):void

----







Register a variable group.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$group`
|        xref:Document.adoc#document_models_variablegroup[`VariableGroup`]
a|
|===


[source%nowrap, php]
[#registervariable]
----

public registerVariable($variable):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$variable`
|        xref:Document.adoc#document_models_variable[`Variable`]
a|
|===


[[document_variables_enums]]
===  Enums
[[document_enums_variablesobjecttypeenum]]
==== VariablesObjectTypeEnum

An enum type with all objects available for variables.



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Enums`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[document_variables_events]]
===  Events
[[document_events_documentbuildervariablesregistering]]
==== DocumentBuilderVariablesRegistering

An event class, which will be triggered, when the DocumentBuilder variables are registered.



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Events`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[document_variables_models]]
===  Models
[[document_models_dynamicvariable]]
==== DynamicVariable

The base class for dynamically detected variables.



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_models_dynamicvariablegroup]]
==== DynamicVariableGroup

A variable group that can be used to register dynamically determined variables.



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_models_variable]]
==== Variable

The base class for DocumentBuilder variables.



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_models_variablegroup]]
==== VariableGroup

The base class for DocumentBuilder variable groups.



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[document_variables_addressgroup]]
===  AddressGroup
[[document_addressgroup_address1variable]]
==== Address1Variable

The address address1 variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_address2variable]]
==== Address2Variable

The address address2 variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_address3variable]]
==== Address3Variable

The address address3 variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_address4variable]]
==== Address4Variable

The address address4 variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_addressbasevariable]]
==== AddressBaseVariable

The base class for all address variables



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_bbfcvariable]]
==== BBFCVariable

The BBFC address option variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_contactpersonvariable]]
==== ContactPersonVariable

The contact person address option variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_countryidvariable]]
==== CountryIDVariable

The address country id variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_countryisovariable]]
==== CountryISOVariable

The address country ISO code variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_countrynamevariable]]
==== CountryNameVariable

The address country name variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_emailvariable]]
==== EmailVariable

The email address option variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_externaladdressidvariable]]
==== ExternalAddressIDVariable

The external address ID address option variable (only for invoice and delivery address)



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_externalcustomeridvariable]]
==== ExternalCustomerIDVariable

The external customer ID address option variable (only for invoice and delivery address)



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_formofaddressvariable]]
==== FormOfAddressVariable

The address form of address variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_gendervariable]]
==== GenderVariable

The address gender variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_hasentrycertificatevariable]]
==== HasEntryCertificateVariable

The address option variable, that indicates if an entry certificate is available



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_ispackstationvariable]]
==== IsPackstationVariable

The address option variable, that indicates if the address is packstation



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_ispostofficevariable]]
==== IsPostOfficeVariable

The address option variable, that indicates if the address is post office



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_name1variable]]
==== Name1Variable

The address name1 variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_name2variable]]
==== Name2Variable

The address name2 variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_name3variable]]
==== Name3Variable

The address name3 variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_name4variable]]
==== Name4Variable

The address name4 variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_packstationnovariable]]
==== PackstationNoVariable

The packstation number address option variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_personalnumbervariable]]
==== PersonalNumberVariable

The phone address option variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_phonevariable]]
==== PhoneVariable

The phone address option variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_postalcodevariable]]
==== PostalCodeVariable

The address postal code variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_postidentvariable]]
==== PostidentVariable

The postident address option variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_stateisovariable]]
==== StateISOVariable

The address state ISO variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_statenamevariable]]
==== StateNameVariable

The address state name variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_taxidnumbervariable]]
==== TaxIDNumberVariable

The tax id number address option variable (only for invoice and delivery address)



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_titlevariable]]
==== TitleVariable

The title address option variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_addressgroup_townvariable]]
==== TownVariable

The address town variable



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Variables\AddressGroup`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[document_variables_services]]
===  Services
[[document_services_variablesresolutionservice]]
==== VariablesResolutionService

The service for variables resolution



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Services`






===== Methods

[source%nowrap, php]
[#setlanguage]
----

public setLanguage($language):Plenty\Modules\Document\Builder\Variables\Services\VariablesResolutionService

----




====== *Return type:*        xref:Document.adoc#document_services_variablesresolutionservice[`VariablesResolutionService`]


Set the language to be used by the variables resolution.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$language`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#setorder]
----

public setOrder($order):Plenty\Modules\Document\Builder\Variables\Services\VariablesResolutionService

----




====== *Return type:*        xref:Document.adoc#document_services_variablesresolutionservice[`VariablesResolutionService`]


Set the order into the variables context

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#setdocument]
----

public setDocument($document):Plenty\Modules\Document\Builder\Variables\Services\VariablesResolutionService

----




====== *Return type:*        xref:Document.adoc#document_services_variablesresolutionservice[`VariablesResolutionService`]


Set the document into the variables context

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$document`
|        xref:Document.adoc#document_models_document[`Document`]
a|
|===


[source%nowrap, php]
[#setmetadata]
----

public setMetaData($metaData):Plenty\Modules\Document\Builder\Variables\Services\VariablesResolutionService

----




====== *Return type:*        xref:Document.adoc#document_services_variablesresolutionservice[`VariablesResolutionService`]


Set the meta data of the template into the variables context

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$metaData`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#setcontact]
----

public setContact($contact):Plenty\Modules\Document\Builder\Variables\Services\VariablesResolutionService

----




====== *Return type:*        xref:Document.adoc#document_services_variablesresolutionservice[`VariablesResolutionService`]


Set the contact into the variables context

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$contact`
|        xref:Account.adoc#account_models_contact[`Contact`]
a|
|===


[source%nowrap, php]
[#setobject]
----

public setObject($typeEnum, $object):Plenty\Modules\Document\Builder\Variables\Services\VariablesResolutionService

----




====== *Return type:*        xref:Document.adoc#document_services_variablesresolutionservice[`VariablesResolutionService`]


Set an object into the variables context.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$typeEnum`
|link:http://php.net/string[string^]
a|A VariablesObjectTypeEnum constant

a|`$object`
|
a|
|===


[[document_models]]
== Models

[[document_models_context]]
===  Context
[[document_context_objectentry]]
==== ObjectEntry

This class represents an object entry with the object type and the object itself.



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Context`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|objectType
    |link:http://php.net/string[string^]
    a|A VariablesObjectTypeEnum constant
|object
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_context_plugincontext]]
==== PluginContext

Informations about plugin entries for the plugin variables (old logic).



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Context`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_context_variablescontext]]
==== VariablesContext

This class is a container for all available object entries



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Context`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_context_variablesresolution]]
==== VariablesResolution

This class can be used by variables to get the needed objects and to push resolved variable content.



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Context`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[document_models_groups]]
===  Groups
[[document_groups_addressgroup]]
==== AddressGroup

The order address variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_addresstypebasegroup]]
==== AddressTypeBaseGroup

The order address type variable group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_bankdatagroup]]
==== BankDataGroup

The BankData variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_companygroup]]
==== CompanyGroup

The Company variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_contactbankdatagroup]]
==== ContactBankDataGroup

The ContactBankData variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_contactgroup]]
==== ContactGroup

The contact variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_documentgroup]]
==== DocumentGroup

The Document variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_headerfootergroup]]
==== HeaderFooterGroup

The HeaderFooter variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_messengergroup]]
==== MessengerGroup

The Messenger variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_orderforeignamountgroup]]
==== OrderForeignAmountGroup

The OrderForeignAmount variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_ordergroup]]
==== OrderGroup

The Order variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_orderitemdategroup]]
==== OrderItemDateGroup

The OrderItemDate variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_orderitemforeignamountgroup]]
==== OrderItemForeignAmountGroup

The OrderItemForeignAmount variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_orderitemgroup]]
==== OrderItemGroup

The OrderItem variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_orderitempropertygroup]]
==== OrderItemPropertyGroup

The OrderItemProperty variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_orderitemsystemamountgroup]]
==== OrderItemSystemAmountGroup

The OrderItemSystemAmount variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_orderpropertygroup]]
==== OrderPropertyGroup

The OrderPropety variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_ordersystemamountgroup]]
==== OrderSystemAmountGroup

The OrderSystemAmount variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_paymentgroup]]
==== PaymentGroup

The Order Payment variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_plugingroup]]
==== PluginGroup

The Plugin variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_shipmentgroup]]
==== ShipmentGroup

The Shipment variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_groups_variationgroup]]
==== VariationGroup

The order item Variation variables group



===== Namespace

`Plenty\Modules\Document\Builder\Variables\Models\Groups`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[document_document]]
== Document

[[document_document_contracts]]
===  Contracts
[[document_contracts_documentrepositorycontract]]
==== DocumentRepositoryContract

Download and list order documents as well as download, list, upload and delete category documents.



===== Namespace

`Plenty\Modules\Document\Contracts`






===== Methods

[source%nowrap, php]
[#getdocumentpath]
----

public getDocumentPath($id):void

----







Get the path to a document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the document
|===


[source%nowrap, php]
[#findbyid]
----

public findById($id, $columns = [], $with = []):Plenty\Modules\Document\Models\Document

----




====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Get a document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the document

a|`$columns`
|link:http://php.net/array[array^]
a|The columns to be loaded

a|`$with`
|link:http://php.net/array[array^]
a|The relations to be loaded. Possible value is "references".
|===


[source%nowrap, php]
[#find]
----

public find($page = 1, $itemsPerPage = 50, $columns = [], $with = [], $sortBy = &quot;id&quot;, $sortOrder = &quot;desc&quot;):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List documents

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of orders to be displayed per page. The default number of orders per page is 50.

a|`$columns`
|link:http://php.net/array[array^]
a|The columns to be loaded

a|`$with`
|link:http://php.net/array[array^]
a|The relations to be loaded. Possible value is "references".

a|`$sortBy`
|link:http://php.net/string[string^]
a|This field is used for sorting. Default is 'id'. Possible values are 'id', 'type', 'number', 'createdAt', 'displayDate', 'updatedAt'

a|`$sortOrder`
|link:http://php.net/string[string^]
a|The order to sort by. Possible values are 'asc' and 'desc'.
|===


[source%nowrap, php]
[#uploadorderdocuments]
----

public uploadOrderDocuments($orderId, $type, $data):array

----







Upload order documents

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order

a|`$type`
|link:http://php.net/string[string^]
a|The document type. Supported types are 'invoiceExternal', 'deliveryNote', 'poDeliveryNote', 'orderConfirmation', 'offer', 'dunningLetter', 'returnNote', 'successConfirmation', 'correction', 'creditNoteExternal', 'reorder', 'uploaded'.

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#deleteorderdocument]
----

public deleteOrderDocument($orderId, $documentId):bool

----







Delete order document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order

a|`$documentId`
|link:http://php.net/int[int^]
a|The ID of the document
|===


[source%nowrap, php]
[#deleteorderdocumentwithoutorderrelation]
----

public deleteOrderDocumentWithoutOrderRelation($documentId):bool

----







Delete a document without an order relation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$documentId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#archiveorderdocument]
----

public archiveOrderDocument($orderId, $documentId):void

----







Archive order document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order

a|`$documentId`
|link:http://php.net/int[int^]
a|The ID of the document
|===


[source%nowrap, php]
[#uploadcategorydocuments]
----

public uploadCategoryDocuments($categoryId, $data):array

----







Upload category documents

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$categoryId`
|link:http://php.net/int[int^]
a|The ID of the category

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#deletecategorydocument]
----

public deleteCategoryDocument($categoryId, $documentId):bool

----







Delete a category document.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$categoryId`
|link:http://php.net/int[int^]
a|The ID of the category

a|`$documentId`
|link:http://php.net/int[int^]
a|The ID of the document
|===


[source%nowrap, php]
[#uploadordershippingpackagedocuments]
----

public uploadOrderShippingPackageDocuments($packageId, $type, $document):array

----







Uploads documents

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$packageId`
|link:http://php.net/int[int^]
a|

a|`$type`
|link:http://php.net/string[string^]
a|

a|`$document`
|link:http://php.net/string[string^]
a|base64 encoded document
|===


[source%nowrap, php]
[#findordershippingpackagedocuments]
----

public findOrderShippingPackageDocuments($packageId, $type):array

----







Find documents

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$packageId`
|link:http://php.net/int[int^]
a|

a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#findcurrentorderdocument]
----

public findCurrentOrderDocument($orderId, $type, $includePending = false):Plenty\Modules\Document\Models\Document

----




====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Finds the current order document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|

a|`$type`
|link:http://php.net/string[string^]
a|

a|`$includePending`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#findrecentorderdocument]
----

public findRecentOrderDocument($orderId, $type, $includePending = false):Plenty\Modules\Document\Models\Document

----




====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Finds order document.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|

a|`$type`
|link:http://php.net/string[string^]
a|

a|`$includePending`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#deleteordershippingpackagedocuments]
----

public deleteOrderShippingPackageDocuments($packageId):bool

----







Delets a document.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$packageId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getdocumentstorageobject]
----

public getDocumentStorageObject($key):void

----







Gets a document storage object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|
a|
|===


[source%nowrap, php]
[#uploadorderreturnsdocuments]
----

public uploadOrderReturnsDocuments($returnsId, $document):Plenty\Modules\Document\Models\Document

----




====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Uploads a specific document.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$returnsId`
|link:http://php.net/int[int^]
a|

a|`$document`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getorderreturnsdocumentbyid]
----

public getOrderReturnsDocumentById($returnsId, $withLabel = false):Plenty\Modules\Document\Models\Document

----




====== *Return type:*        xref:Document.adoc#document_models_document[`Document`]


Finds a document.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$returnsId`
|link:http://php.net/int[int^]
a|

a|`$withLabel`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#generateorderdocument]
----

public generateOrderDocument($orderId, $type, $data):bool

----







Generate order document

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order

a|`$type`
|link:http://php.net/string[string^]
a|The document type

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#documentwithoutreversaldocumentexists]
----

public documentWithoutReversalDocumentExists($orderId, $documentTypes):bool

----







Check if there is a document without a reversed counter part

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order

a|`$documentTypes`
|link:http://php.net/array[array^]
a|The document types
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[document_document_enums]]
===  Enums
[[document_enums_documentgrouptypeenum]]
==== DocumentGroupTypeEnum

A list of document type groups



===== Namespace

`Plenty\Modules\Document\Enums`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_enums_documenttypeenum]]
==== DocumentTypeEnum

A list of document types



===== Namespace

`Plenty\Modules\Document\Enums`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[document_document_models]]
===  Models
[[document_models_document]]
==== Document

The document model contains information about actual documents.



===== Namespace

`Plenty\Modules\Document\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the document
|type
    |link:http://php.net/string[string^]
    a|The type of the document. The following types are available:
                           <ul>
    <li>admin</li>
    <li>blog</li>
 <li>category</li>
 <li>correction_document</li>
 <li>credit_note</li>
    <li>credit_note_external</li>
       <li>customer</li>
 <li>delivery_note</li>
    <li>dunning_letter</li>
       <li>ebics_hash</li>
    <li>facet</li>
    <li>invoice</li>
    <li>invoice_external</li>
                               <li>pos_invoice</li>
                               <li>pos_invoice_cancellation</li>
 <li>item</li>
 <li>multi_credit_note</li>
    <li>multi_invoice</li>
       <li>offer</li>
    <li>order_confirmation</li>
       <li>pickup_delivery</li>
    <li>receipt</li>
                               <li>refund_reversal</li>
    <li>reorder</li>
    <li>repair_bill</li>
    <li>return_note</li>
       <li>reversal_document</li>
       <li>settlement_report</li>
    <li>success_confirmation</li>
    <li>ticket</li>
    <li>webshop</li>
  <li>webshop_customer</li>
    <li>z_report</li>
    <li>shipping_label</li>
    <li>shipping_export_label</li>
    <li>returns_label</li>
                               <li>reversal_dunning_letter</l>
</ul>
|number
    |link:http://php.net/int[int^]
    a|The document number
|numberWithPrefix
    |link:http://php.net/string[string^]
    a|The document number with prefix
|path
    |link:http://php.net/string[string^]
    a|The path to the document
|userId
    |link:http://php.net/int[int^]
    a|The ID of the user
|source
    |link:http://php.net/string[string^]
    a|The source where the document was generated. Possible sources are 'klarna', 'soap', 'admin', 'hitmeister', 'paypal' and 'rest'.
|displayDate
    |link:http://php.net/string[string^]
    a|The date displayed on the document
|status
    |link:http://php.net/string[string^]
    a|The generation status of the document ("pending", "faulty" or "done"
|content
    |link:http://php.net/string[string^]
    a|The base64 encoded content of the document.
|createdAt
    |
    a|The time the document was created
|updatedAt
    |
    a|The time the document was last updated
|references
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|Collection of document references. The references available are:
<ul>
    <li>contacts</li>
    <li>orders</li>
    <li>webstores = refers to clients</li>
    <li>categories</li>
</ul>
|comment
    |        xref:Document.adoc#document_models_documentcomment[`DocumentComment`]
    a|The manual comment
|cancelledBy
    |        xref:Document.adoc#document_models_document[`Document`]
    a|The reference document that cancelled the current document, if any
|cancels
    |        xref:Document.adoc#document_models_document[`Document`]
    a|The reference document that is cancelled by the current document, if any
|contacts
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|Collection of contacts that are associated with the document
|orders
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|Collection of orders that are associated with the document
|webstores
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|Collection of webstores that are associated with the document
|categories
    |        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]
    a|Collection of categories that are associated with the document
|tags
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_models_documentcomment]]
==== DocumentComment

The manual comment model for the document model .



===== Namespace

`Plenty\Modules\Document\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|documentId
    |link:http://php.net/int[int^]
    a|The id of the document.
|type
    |link:http://php.net/string[string^]
    a|The type of the text (comment).
|value
    |link:http://php.net/string[string^]
    a|The text value
|document
    |        xref:Document.adoc#document_models_document[`Document`]
    a|The related document.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_models_documentreference]]
==== DocumentReference

The document reference model. A document reference allows you to assign a document to other models.



===== Namespace

`Plenty\Modules\Document\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|documentId
    |link:http://php.net/int[int^]
    a|The ID of the document
|type
    |link:http://php.net/string[string^]
    a|The reference type. The following reference types are available:
                            <ul>
    <li>blog</li>
                               <li>cash_register</li>
                               <li>category</li>
    <li>customer</li>
 <li>facet</li>
    <li>facet_value</li>
    <li>item</li>
 <li>multishop</li>
    <li>order</li>
    <li>reorder</li>
 <li>ticket</li>
                               <li>warehouse</li>
                               <li>order_shipping_package</li>
</ul>
|value
    |link:http://php.net/string[string^]
    a|The reference value (e.g. the ID of another model)
|document
    |        xref:Document.adoc#document_models_document[`Document`]
    a|The document this reference belongs to
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[document_generation]]
== Generation

[[document_generation_contracts]]
===  Contracts
[[document_contracts_documentbuildergenerationrestrictioncontainercontract]]
==== DocumentBuilderGenerationRestrictionContainerContract

A container service for DocumentBuilder document generation restrictions registration



===== Namespace

`Plenty\Modules\Document\Generation\Contracts`






===== Methods

[source%nowrap, php]
[#registergenerationrestriction]
----

public registerGenerationRestriction($restriction, $descriptions):void

----







Register a document generation restriction.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$restriction`
|
a|The Closure should have the signature
<pre>function(Order $order, string $documentType): bool</pre>

a|`$descriptions`
|
a|The messages in case of restriction. At least the keys 'de' and 'en' are required.
|===


[source%nowrap, php]
[#checkgenerationrestrictions]
----

public checkGenerationRestrictions($order, $documentType):void

----







Check for restrictions of the generation of the given document type for the given order.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|The order for which the document is to be generated

a|`$documentType`
|link:http://php.net/string[string^]
a|The document type of the document to be generated
|===


[[document_templatesetting]]
== TemplateSetting

[[document_templatesetting_models]]
===  Models
[[document_models_documenttemplateoutputsetting]]
==== DocumentTemplateOutputSetting

The DocumentBuilder template output setting model



===== Namespace

`Plenty\Modules\Document\TemplateSetting\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|
|templateId
    |link:http://php.net/int[int^]
    a|
|pageWidth
    |link:http://php.net/float[float^]
    a|
|pageHeight
    |link:http://php.net/float[float^]
    a|
|marginTop
    |link:http://php.net/float[float^]
    a|
|marginBottom
    |link:http://php.net/float[float^]
    a|
|marginLeft
    |link:http://php.net/float[float^]
    a|
|marginRight
    |link:http://php.net/float[float^]
    a|
|header
    |link:http://php.net/string[string^]
    a|
|footer
    |link:http://php.net/string[string^]
    a|
|createdAt
    |
    a|
|updatedAt
    |
    a|
|fontFamily
    |link:http://php.net/string[string^]
    a|
|fontSize
    |link:http://php.net/int[int^]
    a|
|amountFormat
    |link:http://php.net/string[string^]
    a|
|currencyFormat
    |link:http://php.net/string[string^]
    a|
|dateFormat
    |link:http://php.net/string[string^]
    a|
|pdfBackground
    |
    a|
|outputType
    |link:http://php.net/string[string^]
    a|
|xmlFormat
    |link:http://php.net/string[string^]
    a|
|repeatPdfBackground
    |link:http://php.net/string[string^]
    a|
|unitFormat
    |link:http://php.net/string[string^]
    a|
|reorderItemSort
    |link:http://php.net/string[string^]
    a|
|integrateInvoices
    |link:http://php.net/bool[bool^]
    a|
|documentTemplateSetting
    |        xref:Document.adoc#document_models_documenttemplatesetting[`DocumentTemplateSetting`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_models_documenttemplatereference]]
==== DocumentTemplateReference

The DocumentBuilder template reference model



===== Namespace

`Plenty\Modules\Document\TemplateSetting\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|templateId
    |link:http://php.net/int[int^]
    a|
|type
    |link:http://php.net/int[int^]
    a|
|referenceTemplateId
    |link:http://php.net/int[int^]
    a|
|documentTemplateSetting
    |        xref:Document.adoc#document_models_documenttemplatesetting[`DocumentTemplateSetting`]
    a|
|referenceDocumentTemplateSetting
    |        xref:Document.adoc#document_models_documenttemplatesetting[`DocumentTemplateSetting`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[document_models_documenttemplatesetting]]
==== DocumentTemplateSetting

The DocumentBuilder template setting model



===== Namespace

`Plenty\Modules\Document\TemplateSetting\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|
|defaultTemplate
    |link:http://php.net/bool[bool^]
    a|
|referenceId
    |link:http://php.net/string[string^]
    a|
|active
    |link:http://php.net/bool[bool^]
    a|
|documentType
    |link:http://php.net/string[string^]
    a|
|templateName
    |link:http://php.net/string[string^]
    a|
|metaData
    |link:http://php.net/array[array^]
    a|
|fileName
    |link:http://php.net/string[string^]
    a|
|stateChangeDate
    |        xref:Miscellaneous.adoc#miscellaneous_carbon_carbon[`Carbon`]
    a|
|createdAt
    |
    a|
|updatedAt
    |
    a|
|tags
    |
    a|
|outputSetting
    |        xref:Document.adoc#document_models_documenttemplateoutputsetting[`DocumentTemplateOutputSetting`]
    a|
|references
    |
    a|
|headerReference
    |        xref:Document.adoc#document_models_documenttemplatereference[`DocumentTemplateReference`]
    a|
|footerReference
    |        xref:Document.adoc#document_models_documenttemplatereference[`DocumentTemplateReference`]
    a|
|referencedBy
    |
    a|
|headerReferencedBy
    |
    a|
|footerReferencedBy
    |
    a|
|typeSettings
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

