:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[eventprocedures_eventprocedures]]
== EventProcedures

[[eventprocedures_eventprocedures_events]]
===  Events
[[eventprocedures_events_eventprocedurestriggered]]
==== EventProceduresTriggered

plentymarkets event procedures triggered



===== Namespace

`Plenty\Modules\EventProcedures\Events`






===== Methods

[source%nowrap, php]
[#getticket]
----

public getTicket():Plenty\Modules\Ticket\Models\Ticket

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticket[`Ticket`]


Gets the ticket.

[source%nowrap, php]
[#getorder]
----

public getOrder():Plenty\Modules\Order\Models\Order

----




====== *Return type:*        xref:Order.adoc#order_models_order[`Order`]


Gets the order

[[eventprocedures_eventprocedures_services]]
===  Services
[[eventprocedures_services_eventproceduresservice]]
==== EventProceduresService

The EventProcedureService class offers the possibility to register a procedure class and method that can be called by plentymarkets event procedures.



===== Namespace

`Plenty\Modules\EventProcedures\Services`






===== Methods

[source%nowrap, php]
[#registerprocedure]
----

public registerProcedure($moduleName, $eventType, $procedureNames, $procedureClass, $procedureGroup = \Plenty\Modules\EventProcedures\Services\Entries\ProcedureEntry::PROCEDURE_GROUP_ORDER):bool

----







Register a procedure class

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$moduleName`
|link:http://php.net/string[string^]
a|The name of the module. The name of the module can be choosen freely.

a|`$eventType`
|link:http://php.net/string[string^]
a|The name of the event type. The event types are determined and can be one of the following:
<ul>
<li> {@see \ProcedureEntry::EVENT_TYPE_ORDER}, </li>
<li> {@see \ProcedureEntry::EVENT_TYPE_REORDER} or </li>
<li> {@see \ProcedureEntry::EVENT_TYPE_TICKET} </li>
</ul>

a|`$procedureNames`
|link:http://php.net/array[array^]
a|The name for the procedure that will be shown in the event procedure UI. The name is unique and will be used for German and English.

a|`$procedureClass`
|link:http://php.net/string[string^]
a|The fully qualified name of the procedure class to be called by event procedures.
Each procedure class must either contain the execute method defined by plentymarkets or can contain an individual method. The individual method has to be provided along with procedure class.
The method is separated from the class by an "@" sign. The part following the "@" will be interpreted as method name. The part in front of the "@" is the name of the procedure class.

a|`$procedureGroup`
|link:http://php.net/string[string^]
a|The name of the procedure group. The procedure groups are determined and can be one of the following:
<ul>
<li> {@see \ProcedureEntry::PROCEDURE_GROUP_ORDER}, </li>
<li> {@see \ProcedureEntry::PROCEDURE_GROUP_ITEM}, </li>
<li> {@see \ProcedureEntry::PROCEDURE_GROUP_DOCUMENT}, </li>
<li> {@see \ProcedureEntry::PROCEDURE_GROUP_CONTACT}, </li>
<li> {@see \ProcedureEntry::PROCEDURE_GROUP_SHIPPING}, </li>
<li> {@see \ProcedureEntry::PROCEDURE_GROUP_PAYMENT}, </li>
<li> {@see \ProcedureEntry::PROCEDURE_GROUP_RETURN} or </li>
<li> {@see \ProcedureEntry::PROCEDURE_GROUP_LISTING} </li>
<li> [optional, default={@see \ProcedureEntry::PROCEDURE_GROUP_ORDER}] </li>
</ul>
|===


[source%nowrap, php]
[#registerfilter]
----

public registerFilter($moduleName, $eventType, $filterNames, $filterClass):bool

----







Register a filter class

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$moduleName`
|link:http://php.net/string[string^]
a|The name of the module. The name of the module can be choosen freely.

a|`$eventType`
|link:http://php.net/string[string^]
a|The name of the event type. The event types are determined and can be one of the following:
<ul>
<li>order</li>
<li>ticket</li>
</ul>

a|`$filterNames`
|link:http://php.net/array[array^]
a|The name for the filter that will be shown in the event procedure UI. The name is unique and will be used for German and English.

a|`$filterClass`
|link:http://php.net/string[string^]
a|The fully qualified name of the filter class to be called by event procedures.
Each procedure class must either contain the accept method defined by plentymarkets or can contain an individual method. The individual method has to be provided along with procedure class.
The method is separated from the class by an "@" sign. The part following the "@" will be interpreted as method name. The part in front of the "@" is the name of the procedure class.
The method must return a boolean.
|===


[source%nowrap, php]
[#registertrigger]
----

public registerTrigger($moduleName, $eventType, $triggerIdentifier, $triggerNames):bool

----







Register a trigger

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$moduleName`
|link:http://php.net/string[string^]
a|The name of the module. The name of the module can be choosen freely.

a|`$eventType`
|link:http://php.net/string[string^]
a|The name of the event type. The event types are determined and can be one of the following:
<ul>
    <li> order </li>
</ul>

a|`$triggerIdentifier`
|link:http://php.net/string[string^]
a|The identifier for the trigger that will be used to identify the trigger on fire. The identifier of the trigger can be choosen freely.

a|`$triggerNames`
|link:http://php.net/array[array^]
a|The name for the trigger that will be shown in the event procedure UI. The name is unique and will be used for German and English.
|===


[source%nowrap, php]
[#firetrigger]
----

public fireTrigger($orderId, $moduleName, $triggerIdentifier):void

----







Fire a trigger

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The id of the order for which the trigger is fired.

a|`$moduleName`
|link:http://php.net/string[string^]
a|The name of the module. The name of the module given on register the trigger.

a|`$triggerIdentifier`
|link:http://php.net/string[string^]
a|The identifier for the trigger given on register the trigger.
|===


[[eventprocedures_services]]
== Services

[[eventprocedures_services_entries]]
===  Entries
[[eventprocedures_entries_filterentry]]
==== FilterEntry

The filter entry contains all information needed to use module filters in plentymarkets event procedures.



===== Namespace

`Plenty\Modules\EventProcedures\Services\Entries`






===== Methods

[source%nowrap, php]
[#getmodulename]
----

public getModuleName():string

----







Gets the module name.

[source%nowrap, php]
[#setmodulename]
----

public setModuleName($moduleName):Plenty\Modules\EventProcedures\Services\Entries\FilterEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_filterentry[`FilterEntry`]


Sets the module name

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$moduleName`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#geteventtype]
----

public getEventType():string

----







Gets the type of event for the current filter entry.

[source%nowrap, php]
[#seteventtype]
----

public setEventType($eventType):Plenty\Modules\EventProcedures\Services\Entries\FilterEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_filterentry[`FilterEntry`]


Sets the event type

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$eventType`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getfilternames]
----

public getFilterNames():array

----







Gets the filter names

[source%nowrap, php]
[#setfilternames]
----

public setFilterNames($filterNames):Plenty\Modules\EventProcedures\Services\Entries\FilterEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_filterentry[`FilterEntry`]


Sets the filter names

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filterNames`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilterclass]
----

public getFilterClass():string

----







Gets the filter class

[source%nowrap, php]
[#setfilterclass]
----

public setFilterClass($filterClass):Plenty\Modules\EventProcedures\Services\Entries\FilterEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_filterentry[`FilterEntry`]


Sets the filter class

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filterClass`
|link:http://php.net/string[string^]
a|
|===



[[eventprocedures_entries_procedureentry]]
==== ProcedureEntry

The procedure entry contains all information needed to use module procedures in plentymarkets event procedures.



===== Namespace

`Plenty\Modules\EventProcedures\Services\Entries`






===== Methods

[source%nowrap, php]
[#getmodulename]
----

public getModuleName():string

----







Gets the module name

[source%nowrap, php]
[#setmodulename]
----

public setModuleName($moduleName):Plenty\Modules\EventProcedures\Services\Entries\ProcedureEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_procedureentry[`ProcedureEntry`]


Sets the module name

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$moduleName`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#geteventtype]
----

public getEventType():string

----







Gets the event type

[source%nowrap, php]
[#seteventtype]
----

public setEventType($eventType):Plenty\Modules\EventProcedures\Services\Entries\ProcedureEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_procedureentry[`ProcedureEntry`]


Sets the event type

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$eventType`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getprocedurenames]
----

public getProcedureNames():array

----







Gets the procedure names

[source%nowrap, php]
[#setprocedurenames]
----

public setProcedureNames($procedureNames):Plenty\Modules\EventProcedures\Services\Entries\ProcedureEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_procedureentry[`ProcedureEntry`]


Sets the procedure names

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$procedureNames`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getproceduregroup]
----

public getProcedureGroup():string

----







Gets the procedure group

[source%nowrap, php]
[#setproceduregroup]
----

public setProcedureGroup($procedureGroup):Plenty\Modules\EventProcedures\Services\Entries\ProcedureEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_procedureentry[`ProcedureEntry`]


Sets the procedure group

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$procedureGroup`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getprocedureclass]
----

public getProcedureClass():string

----







Gets the procedure class

[source%nowrap, php]
[#setprocedureclass]
----

public setProcedureClass($procedureClass):Plenty\Modules\EventProcedures\Services\Entries\ProcedureEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_procedureentry[`ProcedureEntry`]


Sets the procedure class

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$procedureClass`
|link:http://php.net/string[string^]
a|
|===



[[eventprocedures_entries_triggerentry]]
==== TriggerEntry

The trigger entry contains all information needed to use module triggers in plentymarkets event procedures.



===== Namespace

`Plenty\Modules\EventProcedures\Services\Entries`






===== Methods

[source%nowrap, php]
[#getmodulename]
----

public getModuleName():string

----







Gets the module name

[source%nowrap, php]
[#setmodulename]
----

public setModuleName($moduleName):Plenty\Modules\EventProcedures\Services\Entries\TriggerEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_triggerentry[`TriggerEntry`]


Sets the module name

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$moduleName`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#geteventtype]
----

public getEventType():string

----







Gets the event type

[source%nowrap, php]
[#seteventtype]
----

public setEventType($eventType):Plenty\Modules\EventProcedures\Services\Entries\TriggerEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_triggerentry[`TriggerEntry`]


Sets the event type

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$eventType`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#gettriggeridentifier]
----

public getTriggerIdentifier():string

----







Gets the trigger identifier

[source%nowrap, php]
[#settriggeridentifier]
----

public setTriggerIdentifier($triggerIdentifier):Plenty\Modules\EventProcedures\Services\Entries\TriggerEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_triggerentry[`TriggerEntry`]


Sets the trigger identifier

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$triggerIdentifier`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#gettriggernames]
----

public getTriggerNames():array

----







Gets the trigger names

[source%nowrap, php]
[#settriggernames]
----

public setTriggerNames($triggerNames):Plenty\Modules\EventProcedures\Services\Entries\TriggerEntry

----




====== *Return type:*        xref:Eventprocedures.adoc#eventprocedures_entries_triggerentry[`TriggerEntry`]


Sets the trigger names

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$triggerNames`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#gettrigger]
----

public getTrigger():int

----







Gets the trigger

