

[[feedback_feedback]]
== Feedback

[[feedback_feedback_contracts]]
===  Contracts
[[feedback_contracts_feedbackaveragerepositorycontract]]
==== FeedbackAverageRepositoryContract

Get the feedback average.



===== Namespace

`Plenty\Modules\Feedback\Contracts`






===== Methods

[source%nowrap, php]
----

public getFeedbackAverage($feedbackRelationTargetId):void

----

    





Gets the feedback average

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$feedbackRelationTargetId`
a|
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[feedback_contracts_feedbackcommentrepositorycontract]]
==== FeedbackCommentRepositoryContract

Get, create and delete feedback comments.



===== Namespace

`Plenty\Modules\Feedback\Contracts`






===== Methods

[source%nowrap, php]
----

public getFeedbackComment($feedbackCommentId):Plenty\Modules\Feedback\Models\FeedbackComment

----

    


====== *Return type:*        xref:Feedback.adoc#feedback_models_feedbackcomment[`FeedbackComment`]


Get a feedback comment

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$feedbackCommentId`
a|The ID of the feedback comment
|===


[source%nowrap, php]
----

public listFeedbackComments():Illuminate\Support\Collection

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


List feedback comments

[source%nowrap, php]
----

public createFeedbackComment($data):Plenty\Modules\Feedback\Models\FeedbackComment

----

    


====== *Return type:*        xref:Feedback.adoc#feedback_models_feedbackcomment[`FeedbackComment`]


Create a feedback comment

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public deleteFeedbackComment($feedbackCommentId):void

----

    





Delete a feedback comment

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$feedbackCommentId`
a|The ID of the feedback comment
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[feedback_contracts_feedbackratingrepositorycontract]]
==== FeedbackRatingRepositoryContract

Get, create and delete feedback ratings.



===== Namespace

`Plenty\Modules\Feedback\Contracts`






===== Methods

[source%nowrap, php]
----

public getFeedbackRating($feedbackRatingId):Plenty\Modules\Feedback\Models\FeedbackRating

----

    


====== *Return type:*        xref:Feedback.adoc#feedback_models_feedbackrating[`FeedbackRating`]


Get a feedback rating

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$feedbackRatingId`
a|The ID of the feedback rating
|===


[source%nowrap, php]
----

public listFeedbackRatings():Illuminate\Support\Collection

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


List feedback ratings

[source%nowrap, php]
----

public createFeedbackRating($data):Plenty\Modules\Feedback\Models\FeedbackRating

----

    


====== *Return type:*        xref:Feedback.adoc#feedback_models_feedbackrating[`FeedbackRating`]


Create a feedback rating

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public deleteFeedbackRating($feedbackRatingId):void

----

    





Delete a feedback rating

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$feedbackRatingId`
a|The ID of the feedback rating
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[feedback_contracts_feedbackrepositorycontract]]
==== FeedbackRepositoryContract

Get, create and delete feedbacks.



===== Namespace

`Plenty\Modules\Feedback\Contracts`






===== Methods

[source%nowrap, php]
----

public getFeedback($feedbackId):void

----

    





Get a feedback

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$feedbackId`
a|The ID of the feedback
|===


[source%nowrap, php]
----

public listFeedbacks($page = 1, $itemsPerPage = 50, $with = [], $filters = []):Plenty\Repositories\Models\PaginatedResult

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|

|link:http://php.net/array[array^]
a|`$with`
a|

|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public createFeedback($data):void

----

    





Create a feedback

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public deleteFeedback($feedbackId):void

----

    





Delete a feedback

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$feedbackId`
a|The ID of the feedback
|===


[source%nowrap, php]
----

public updateFeedback($data, $feedbackId):void

----

    





Update a feedback

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|Request data

|link:http://php.net/int[int^]
a|`$feedbackId`
a|The ID of the feedback
|===


[source%nowrap, php]
----

public updateFeedbacksVisibility($feedbackIds, $isVisible):void

----

    





Update the visibility of multiple feedbacks

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$feedbackIds`
a|

|link:http://php.net/bool[bool^]
a|`$isVisible`
a|
|===


[source%nowrap, php]
----

public deleteFeedbacks($feedbackIds):void

----

    





Delete multiple feedbacks

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$feedbackIds`
a|
|===


[source%nowrap, php]
----

public listFeedbackReplies($feedbackId, $page = 1, $itemsPerPage = 50, $with = [], $filters = []):void

----

    





Lists feedback replies

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$feedbackId`
a|

|link:http://php.net/int[int^]
a|`$page`
a|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|

|link:http://php.net/array[array^]
a|`$with`
a|

|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public migrateLegacyFeedbacks():void

----

    





Migrate legacy feedbacks

[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[[feedback_feedback_models]]
===  Models
[[feedback_models_feedback]]
==== Feedback

The feedback model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the feedback
|link:http://php.net/string[string^]
    a|title
    a|The title of the feedback
|link:http://php.net/string[string^]
    a|authorName
    a|The name of the feedback's author
|link:http://php.net/bool[bool^]
    a|isVisible
    a|If true, the feedback is visible
|
    a|createdAt
    a|The date when the feedback was created
|
    a|updatedAt
    a|The date when the feedback was last updated
|        xref:Feedback.adoc#feedback_models_feedbacksourcerelation[`FeedbackSourceRelation`]
    a|sourceRelation
    a|The feedback source relation
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbackaverage]]
==== FeedbackAverage

The feedback average model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the feedback average
|link:http://php.net/string[string^]
    a|feedbackRelationType
    a|The feedback relation type
|link:http://php.net/int[int^]
    a|feedbackRelationTargetId
    a|The feedback relation target ID
|link:http://php.net/float[float^]
    a|averageValue
    a|The average value of the feedback
|link:http://php.net/int[int^]
    a|ratingsCountTotal
    a|The total count of ratings for this target
|link:http://php.net/int[int^]
    a|ratingsCountOf1
    a|Number of ratings of 1 for this target
|link:http://php.net/int[int^]
    a|ratingsCountOf2
    a|Number of ratings of 2 for this target
|link:http://php.net/int[int^]
    a|ratingsCountOf3
    a|Number of ratings of 3 for this target
|link:http://php.net/int[int^]
    a|ratingsCountOf4
    a|Number of ratings of 4 for this target
|link:http://php.net/int[int^]
    a|ratingsCountOf5
    a|Number of ratings of 5 for this target
|
    a|createdAt
    a|The date when the feedback average was created
|
    a|updatedAt
    a|The date when the feedback average was last updated
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbackcomment]]
==== FeedbackComment

The feedback comment model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the comment
|link:http://php.net/string[string^]
    a|message
    a|The message of the comment
|link:http://php.net/bool[bool^]
    a|isVisible
    a|If true, the comment is visible
|
    a|createdAt
    a|The date when the feedback relation type name was created
|
    a|updatedAt
    a|The date when the feedback relation type name was last updated
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbackcommentsourcerelation]]
==== FeedbackCommentSourceRelation

The feedback comment source relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|commentId
    a|The ID of the feedback comment
|link:http://php.net/string[string^]
    a|commentRelationType
    a|The relation comment relation type
|link:http://php.net/int[int^]
    a|commentRelationSourceId
    a|The relation comment relation source ID
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbackcommenttargetrelation]]
==== FeedbackCommentTargetRelation

The feedback comment target relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|commentId
    a|The ID of the feedback comment
|link:http://php.net/string[string^]
    a|commentRelationType
    a|The relation comment relation type
|link:http://php.net/int[int^]
    a|commentRelationTargetId
    a|The relation comment relation target ID
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbacklegacy]]
==== FeedbackLegacy

The feedback legacy model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|feedbackId
    a|The ID of the new feedback
|link:http://php.net/int[int^]
    a|legacyFeedbackId
    a|The ID of the legacy feedback
|
    a|createdAt
    a|The date when the legacy feedback was created
|
    a|updatedAt
    a|The date when the legacy feedback was last updated
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbackrating]]
==== FeedbackRating

The feedback rating model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the rating
|link:http://php.net/string[string^]
    a|ratingValue
    a|The value of the rating
|link:http://php.net/bool[bool^]
    a|isVisible
    a|If true, the rating is visible
|
    a|createdAt
    a|The date when the feedback rating relation type name was created
|
    a|updatedAt
    a|The date when the feedback rating relation type name was last updated
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbackratingaverage]]
==== FeedbackRatingAverage

The feedback rating average model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the feedback rating average
|link:http://php.net/string[string^]
    a|ratingRelationType
    a|The feedback rating relation type
|link:http://php.net/int[int^]
    a|ratingRelationTargetId
    a|The feedback rating relation target ID
|link:http://php.net/float[float^]
    a|averageValue
    a|The average value of the feedback rating
|link:http://php.net/int[int^]
    a|averageCount
    a|The average count of the feedback rating
|
    a|createdAt
    a|The date when the feedback rating average was created
|
    a|updatedAt
    a|The date when the feedback rating average was last updated
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbackratingsourcerelation]]
==== FeedbackRatingSourceRelation

The feedback rating source relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|ratingId
    a|The ID of the feedback rating
|link:http://php.net/string[string^]
    a|ratingRelationType
    a|The rating relation type
|link:http://php.net/int[int^]
    a|ratingRelationSourceId
    a|The rating relation source ID
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbackratingtargetrelation]]
==== FeedbackRatingTargetRelation

The feedback rating target relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|ratingId
    a|The ID of the feedback rating
|link:http://php.net/string[string^]
    a|ratingRelationType
    a|The relation rating relation type
|link:http://php.net/int[int^]
    a|ratingRelationTargetId
    a|The relation rating relation target ID
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbacksourcerelation]]
==== FeedbackSourceRelation

The feedback source relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|feedbackId
    a|The ID of the feedback
|link:http://php.net/string[string^]
    a|feedbackRelationType
    a|The relation type
|link:http://php.net/int[int^]
    a|feedbackRelationSourceId
    a|The relation source ID
|link:http://php.net/string[string^]
    a|sourceRelationLabel
    a|The source relation label
|link:http://php.net/string[string^]
    a|sourceRelationTypeLabel
    a|The source relation type label
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[feedback_models_feedbacktargetrelation]]
==== FeedbackTargetRelation

The feedback target relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|feedbackId
    a|The ID of the feedback
|link:http://php.net/string[string^]
    a|feedbackRelationType
    a|The relation type
|link:http://php.net/int[int^]
    a|feedbackRelationSourceId
    a|The relation source ID
|link:http://php.net/string[string^]
    a|targetRelationLabel
    a|The target relation label
|link:http://php.net/string[string^]
    a|targetRelationName
    a|The target relation name
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

