:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[feedback_feedback]]
== Feedback

[[feedback_feedback_contracts]]
===  Contracts
[[feedback_contracts_feedbackaveragerepositorycontract]]
==== FeedbackAverageRepositoryContract

Get the feedback average.



===== Namespace

`Plenty\Modules\Feedback\Contracts`






===== Methods

[source%nowrap, php]
----

public getFeedbackAverage($feedbackRelationTargetId):void

----







Gets the feedback average

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$feedbackRelationTargetId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----







Clears the filter array.


[[feedback_contracts_feedbackcommentrepositorycontract]]
==== FeedbackCommentRepositoryContract

Get, create and delete feedback comments.



===== Namespace

`Plenty\Modules\Feedback\Contracts`






===== Methods

[source%nowrap, php]
----

public getFeedbackComment($feedbackCommentId):Plenty\Modules\Feedback\Models\FeedbackComment

----




====== *Return type:*        xref:Feedback.adoc#feedback_models_feedbackcomment[`FeedbackComment`]


Get a feedback comment

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$feedbackCommentId`
|link:http://php.net/int[int^]
a|The ID of the feedback comment
|===


[source%nowrap, php]
----

public listFeedbackComments():Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


List feedback comments

[source%nowrap, php]
----

public createFeedbackComment($data):Plenty\Modules\Feedback\Models\FeedbackComment

----




====== *Return type:*        xref:Feedback.adoc#feedback_models_feedbackcomment[`FeedbackComment`]


Create a feedback comment

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
----

public deleteFeedbackComment($feedbackCommentId):void

----







Delete a feedback comment

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$feedbackCommentId`
|link:http://php.net/int[int^]
a|The ID of the feedback comment
|===


[source%nowrap, php]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----







Clears the filter array.


[[feedback_contracts_feedbackratingrepositorycontract]]
==== FeedbackRatingRepositoryContract

Get, create and delete feedback ratings.



===== Namespace

`Plenty\Modules\Feedback\Contracts`






===== Methods

[source%nowrap, php]
----

public getFeedbackRating($feedbackRatingId):Plenty\Modules\Feedback\Models\FeedbackRating

----




====== *Return type:*        xref:Feedback.adoc#feedback_models_feedbackrating[`FeedbackRating`]


Get a feedback rating

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$feedbackRatingId`
|link:http://php.net/int[int^]
a|The ID of the feedback rating
|===


[source%nowrap, php]
----

public listFeedbackRatings():Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


List feedback ratings

[source%nowrap, php]
----

public createFeedbackRating($data):Plenty\Modules\Feedback\Models\FeedbackRating

----




====== *Return type:*        xref:Feedback.adoc#feedback_models_feedbackrating[`FeedbackRating`]


Create a feedback rating

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
----

public deleteFeedbackRating($feedbackRatingId):void

----







Delete a feedback rating

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$feedbackRatingId`
|link:http://php.net/int[int^]
a|The ID of the feedback rating
|===


[source%nowrap, php]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----







Clears the filter array.


[[feedback_contracts_feedbackrepositorycontract]]
==== FeedbackRepositoryContract

Get, create and delete feedbacks.



===== Namespace

`Plenty\Modules\Feedback\Contracts`






===== Methods

[source%nowrap, php]
----

public getFeedback($feedbackId):void

----







Get a feedback

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$feedbackId`
|link:http://php.net/int[int^]
a|The ID of the feedback
|===


[source%nowrap, php]
----

public listFeedbacks($page = 1, $itemsPerPage = 50, $with = [], $filters = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|

a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
----

public createFeedback($data):void

----







Create a feedback

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
----

public deleteFeedback($feedbackId):void

----







Delete a feedback

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$feedbackId`
|link:http://php.net/int[int^]
a|The ID of the feedback
|===


[source%nowrap, php]
----

public updateFeedback($data, $feedbackId):void

----







Update a feedback

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|Request data

a|`$feedbackId`
|link:http://php.net/int[int^]
a|The ID of the feedback
|===


[source%nowrap, php]
----

public updateFeedbacksVisibility($feedbackIds, $isVisible):void

----







Update the visibility of multiple feedbacks

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$feedbackIds`
|link:http://php.net/array[array^]
a|

a|`$isVisible`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
----

public deleteFeedbacks($feedbackIds):void

----







Delete multiple feedbacks

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$feedbackIds`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
----

public listFeedbackReplies($feedbackId, $page = 1, $itemsPerPage = 50, $with = [], $filters = []):void

----







Lists feedback replies

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$feedbackId`
|link:http://php.net/int[int^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|

a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
----

public migrateLegacyFeedbacks():void

----







Migrate legacy feedbacks

[source%nowrap, php]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----







Clears the filter array.

[[feedback_feedback_models]]
===  Models
[[feedback_models_feedback]]
==== Feedback

The feedback model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the feedback
|title
    |link:http://php.net/string[string^]
    a|The title of the feedback
|authorName
    |link:http://php.net/string[string^]
    a|The name of the feedback's author
|isVisible
    |link:http://php.net/bool[bool^]
    a|If true, the feedback is visible
|createdAt
    |
    a|The date when the feedback was created
|updatedAt
    |
    a|The date when the feedback was last updated
|sourceRelation
    |        xref:Feedback.adoc#feedback_models_feedbacksourcerelation[`FeedbackSourceRelation`]
    a|The feedback source relation
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbackaverage]]
==== FeedbackAverage

The feedback average model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the feedback average
|feedbackRelationType
    |link:http://php.net/string[string^]
    a|The feedback relation type
|feedbackRelationTargetId
    |link:http://php.net/int[int^]
    a|The feedback relation target ID
|averageValue
    |link:http://php.net/float[float^]
    a|The average value of the feedback
|ratingsCountTotal
    |link:http://php.net/int[int^]
    a|The total count of ratings for this target
|ratingsCountOf1
    |link:http://php.net/int[int^]
    a|Number of ratings of 1 for this target
|ratingsCountOf2
    |link:http://php.net/int[int^]
    a|Number of ratings of 2 for this target
|ratingsCountOf3
    |link:http://php.net/int[int^]
    a|Number of ratings of 3 for this target
|ratingsCountOf4
    |link:http://php.net/int[int^]
    a|Number of ratings of 4 for this target
|ratingsCountOf5
    |link:http://php.net/int[int^]
    a|Number of ratings of 5 for this target
|createdAt
    |
    a|The date when the feedback average was created
|updatedAt
    |
    a|The date when the feedback average was last updated
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbackcomment]]
==== FeedbackComment

The feedback comment model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the comment
|message
    |link:http://php.net/string[string^]
    a|The message of the comment
|isVisible
    |link:http://php.net/bool[bool^]
    a|If true, the comment is visible
|createdAt
    |
    a|The date when the feedback relation type name was created
|updatedAt
    |
    a|The date when the feedback relation type name was last updated
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbackcommentsourcerelation]]
==== FeedbackCommentSourceRelation

The feedback comment source relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|commentId
    |link:http://php.net/int[int^]
    a|The ID of the feedback comment
|commentRelationType
    |link:http://php.net/string[string^]
    a|The relation comment relation type
|commentRelationSourceId
    |link:http://php.net/int[int^]
    a|The relation comment relation source ID
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbackcommenttargetrelation]]
==== FeedbackCommentTargetRelation

The feedback comment target relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|commentId
    |link:http://php.net/int[int^]
    a|The ID of the feedback comment
|commentRelationType
    |link:http://php.net/string[string^]
    a|The relation comment relation type
|commentRelationTargetId
    |link:http://php.net/int[int^]
    a|The relation comment relation target ID
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbacklegacy]]
==== FeedbackLegacy

The feedback legacy model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|feedbackId
    |link:http://php.net/int[int^]
    a|The ID of the new feedback
|legacyFeedbackId
    |link:http://php.net/int[int^]
    a|The ID of the legacy feedback
|createdAt
    |
    a|The date when the legacy feedback was created
|updatedAt
    |
    a|The date when the legacy feedback was last updated
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbackrating]]
==== FeedbackRating

The feedback rating model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the rating
|ratingValue
    |link:http://php.net/string[string^]
    a|The value of the rating
|isVisible
    |link:http://php.net/bool[bool^]
    a|If true, the rating is visible
|createdAt
    |
    a|The date when the feedback rating relation type name was created
|updatedAt
    |
    a|The date when the feedback rating relation type name was last updated
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbackratingaverage]]
==== FeedbackRatingAverage

The feedback rating average model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the feedback rating average
|ratingRelationType
    |link:http://php.net/string[string^]
    a|The feedback rating relation type
|ratingRelationTargetId
    |link:http://php.net/int[int^]
    a|The feedback rating relation target ID
|averageValue
    |link:http://php.net/float[float^]
    a|The average value of the feedback rating
|averageCount
    |link:http://php.net/int[int^]
    a|The average count of the feedback rating
|createdAt
    |
    a|The date when the feedback rating average was created
|updatedAt
    |
    a|The date when the feedback rating average was last updated
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbackratingsourcerelation]]
==== FeedbackRatingSourceRelation

The feedback rating source relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|ratingId
    |link:http://php.net/int[int^]
    a|The ID of the feedback rating
|ratingRelationType
    |link:http://php.net/string[string^]
    a|The rating relation type
|ratingRelationSourceId
    |link:http://php.net/int[int^]
    a|The rating relation source ID
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbackratingtargetrelation]]
==== FeedbackRatingTargetRelation

The feedback rating target relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|ratingId
    |link:http://php.net/int[int^]
    a|The ID of the feedback rating
|ratingRelationType
    |link:http://php.net/string[string^]
    a|The relation rating relation type
|ratingRelationTargetId
    |link:http://php.net/int[int^]
    a|The relation rating relation target ID
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbacksourcerelation]]
==== FeedbackSourceRelation

The feedback source relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|feedbackId
    |link:http://php.net/int[int^]
    a|The ID of the feedback
|feedbackRelationType
    |link:http://php.net/string[string^]
    a|The relation type
|feedbackRelationSourceId
    |link:http://php.net/int[int^]
    a|The relation source ID
|sourceRelationLabel
    |link:http://php.net/string[string^]
    a|The source relation label
|sourceRelationTypeLabel
    |link:http://php.net/string[string^]
    a|The source relation type label
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[feedback_models_feedbacktargetrelation]]
==== FeedbackTargetRelation

The feedback target relation model.



===== Namespace

`Plenty\Modules\Feedback\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|feedbackId
    |link:http://php.net/int[int^]
    a|The ID of the feedback
|feedbackRelationType
    |link:http://php.net/string[string^]
    a|The relation type
|feedbackRelationSourceId
    |link:http://php.net/int[int^]
    a|The relation source ID
|targetRelationLabel
    |link:http://php.net/string[string^]
    a|The target relation label
|targetRelationName
    |link:http://php.net/string[string^]
    a|The target relation name
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.

