:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[frontend_frontend]]
= Frontend

[[frontend_frontend_contracts]]
== Contracts
[[frontend_contracts_checkout]]
=== Checkout

The CheckoutContract is the interface for the checkout repository. This interface allows to set the shipping country ID, the payment method ID, the shipping profile ID and the currency in the checkout.



==== Namespace

`Plenty\Modules\Frontend\Contracts`






==== Methods

[source%nowrap, php]
----

public getShippingCountryId():int

----

    





Gets the shipping country ID.

[source%nowrap, php]
----

public setShippingCountryId($shippingCountryId):void

----

    





Updates the ID of the shipping country. The ID must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$shippingCountryId`
a|The ID of the shipping country
|===


[source%nowrap, php]
----

public getPaymentMethodId():int

----

    





Gets the payment method id of the current shopping cart.

[source%nowrap, php]
----

public setPaymentMethodId($paymentMethodId):void

----

    





Updates the ID of the payment method. The ID must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$paymentMethodId`
a|The ID of the payment method
|===


[source%nowrap, php]
----

public getShippingProfileId():int

----

    





Gets the shipping profile id of the current shopping cart.

[source%nowrap, php]
----

public setShippingProfileId($shippingProfileId):void

----

    





Updates the ID of the shipping profile. The ID must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$shippingProfileId`
a|The ID of the shipping profile
|===


[source%nowrap, php]
----

public setCurrency($currency):void

----

    





Updates the currency. The currency must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$currency`
a|The currency
|===


[source%nowrap, php]
----

public setBasketReferrerId($referrerId):void

----

    





Updates the ID of the order referrer. The ID must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$referrerId`
a|The ID of the order referrer. The <a href="https://www.plentymarkets.co.uk/manual/settings/orders/order-referrer/" target="_blank">order referrer</a> settings can be changed in the plentymarkets back end.
|===


[source%nowrap, php]
----

public getCustomerInvoiceAddressId():int

----

    





Gets the invoice address id of the current shopping cart.

[source%nowrap, php]
----

public setCustomerInvoiceAddressId($invoiceAddressId):void

----

    





Sets the invoice address id for the current shopping cart.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$invoiceAddressId`
a|
|===


[source%nowrap, php]
----

public getCustomerShippingAddressId():int

----

    





Gets the shipping address id of the current shopping cart.

[source%nowrap, php]
----

public setCustomerShippingAddressId($shippingAddressId):void

----

    





Sets the shipping address id for the current shopping cart.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$shippingAddressId`
a|
|===


[source%nowrap, php]
----

public validateCheckout():Plenty\Modules\Frontend\Events\ValidateCheckoutEvent

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_events_validatecheckoutevent[`ValidateCheckoutEvent`]





[[frontend_contracts_currencyexchangerepositorycontract]]
=== CurrencyExchangeRepositoryContract

The CurrencyExchangeRatioRepositoryContract is the interface for the currency exchange repository. This interface allows you to get the default system currency, to get exchange ratios for every currency and to convert an amount from the default currency into a given currency or from a given currency into the default currency.



==== Namespace

`Plenty\Modules\Frontend\Contracts`






==== Methods

[source%nowrap, php]
----

public getExchangeRatioByCurrency($currency):float

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$currency`
a|
|===


[source%nowrap, php]
----

public getDefaultCurrency():string

----

    





Get the default currency.

[source%nowrap, php]
----

public convertFromDefaultCurrency($currency, $amount, $exchangeRatio = 0.0):float

----

    





Converts the given value from the default currency to the given currency.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$currency`
a|

|link:http://php.net/float[float^]
a|`$amount`
a|

|link:http://php.net/float[float^]
a|`$exchangeRatio`
a|
|===


[source%nowrap, php]
----

public convertToDefaultCurrency($currency, $amount, $exchangeRatio = 0.0):float

----

    





Converts the given value to the default currency from the given currency.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$currency`
a|

|link:http://php.net/float[float^]
a|`$amount`
a|

|link:http://php.net/float[float^]
a|`$exchangeRatio`
a|
|===


[[frontend_frontend_events]]
== Events
[[frontend_events_frontendcurrencychanged]]
=== FrontendCurrencyChanged

The event is triggered when the currency is changed in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getCurrency():string

----

    





Gets the currency.

[source%nowrap, php]
----

public getCurrencyExchangeRatio():float

----

    





Gets the exchange rate used for converting the currency.


[[frontend_events_frontendcustomeraddresschanged]]
=== FrontendCustomerAddressChanged

The event is triggered when a customer address is changed in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






[[frontend_events_frontendlanguagechanged]]
=== FrontendLanguageChanged

The event is triggered when the language is changed in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getLanguage():string

----

    





Gets the language of the online store.


[[frontend_events_frontendpaymentmethodchanged]]
=== FrontendPaymentMethodChanged

The event is triggered when the payment method is changed in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getPaymentMethodId():void

----

    





Gets the ID of the payment method.

[source%nowrap, php]
----

public setPaymentMethodId($paymentMethodId):void

----

    





Updates the ID of the payment method. The ID must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$paymentMethodId`
a|
|===



[[frontend_events_frontendreferrerchanged]]
=== FrontendReferrerChanged

The event is triggered when the referrer id  is changed in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getReferrerId():void

----

    







[source%nowrap, php]
----

public setReferrerId($referrerId):Plenty\Modules\Frontend\Events\FrontendReferrerChanged

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_events_frontendreferrerchanged[`FrontendReferrerChanged`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$referrerId`
a|
|===



[[frontend_events_frontendshippingcountrychanged]]
=== FrontendShippingCountryChanged

The event is triggered when the shipping country is changed in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getShippingCountryId():int

----

    





Gets the ID of the shipping country.

[source%nowrap, php]
----

public setShippingCountryId($shippingCountryId):Plenty\Modules\Frontend\Events\FrontendShippingCountryChanged

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_events_frontendshippingcountrychanged[`FrontendShippingCountryChanged`]


Updates the ID of the shipping country. The ID must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$shippingCountryId`
a|The ID of the shipping country
|===



[[frontend_events_frontendshippingprofilechanged]]
=== FrontendShippingProfileChanged

The event is triggered when the shipping profile is changed in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getShippingProfileId():void

----

    





Gets the ID of the shipping profile.

[source%nowrap, php]
----

public setShippingProfileId($shippingProfileId):void

----

    





Updates the ID of the shipping profile. The ID must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$shippingProfileId`
a|
|===



[[frontend_events_frontendupdatedeliveryaddress]]
=== FrontendUpdateDeliveryAddress

The event is triggered when the delivery address is changed in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getAccountAddressId():int

----

    





Gets the ID of the address saved for the account.


[[frontend_events_frontendupdateinvoiceaddress]]
=== FrontendUpdateInvoiceAddress

The event is triggered when the invoice address is changed in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getAccountAddressId():int

----

    





Gets the ID of the address saved for the account.


[[frontend_events_frontendupdatepaymentsettings]]
=== FrontendUpdatePaymentSettings

The event is triggered when the payment method is changed in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getPaymentMethodId():int

----

    





Gets the ID of the payment method.


[[frontend_events_frontendupdateshippingsettings]]
=== FrontendUpdateShippingSettings

The event is triggered when the shipping method is updated in the online store.



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getShippingCosts():float

----

    





Gets the shipping costs.

[source%nowrap, php]
----

public getParcelServiceId():int

----

    





Gets the ID of the shipping service provider.

[source%nowrap, php]
----

public getParcelServicePresetId():int

----

    





Gets the preset ID of the shipping service provider.


[[frontend_events_validatecheckoutevent]]
=== ValidateCheckoutEvent

validation event



==== Namespace

`Plenty\Modules\Frontend\Events`






==== Methods

[source%nowrap, php]
----

public getErrorKeysList():array

----

    







[source%nowrap, php]
----

public addErrorKey($errorKey):Plenty\Modules\Frontend\Events

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_frontend_events[`Events`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$errorKey`
a|
|===


[[frontend_frontend_factories]]
== Factories
[[frontend_factories_frontendfactory]]
=== FrontendFactory

Frontend-Factory



==== Namespace

`Plenty\Modules\Frontend\Factories`






==== Methods

[source%nowrap, php]
----

public getLocale():Plenty\Modules\Frontend\Services\LocaleService

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_services_localeservice[`LocaleService`]




[source%nowrap, php]
----

public getAgent():Plenty\Modules\Frontend\Services\AgentService

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_services_agentservice[`AgentService`]




[source%nowrap, php]
----

public getSystem():Plenty\Modules\Frontend\Services\SystemService

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_services_systemservice[`SystemService`]




[source%nowrap, php]
----

public getAccount():Plenty\Modules\Frontend\Services\AccountService

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_services_accountservice[`AccountService`]




[source%nowrap, php]
----

public getFile():Plenty\Modules\Frontend\Services\FileService

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_services_fileservice[`FileService`]




[[frontend_frontend_models]]
== Models
[[frontend_models_totalvat]]
=== TotalVat

frontend total vat model



==== Namespace

`Plenty\Modules\Frontend\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|vatId
    a|
|link:http://php.net/float[float^]
    a|vatAmount
    a|
|link:http://php.net/float[float^]
    a|vatValue
    a|
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[frontend_frontend_services]]
== Services
[[frontend_services_accountservice]]
=== AccountService

Frontend-service for customer information



==== Namespace

`Plenty\Modules\Frontend\Services`






==== Methods

[source%nowrap, php]
----

public getIsAccountLoggedIn():bool

----

    







[source%nowrap, php]
----

public getAccountContactId():int

----

    








[[frontend_services_agentservice]]
=== AgentService

Frontend-Service for agent information



==== Namespace

`Plenty\Modules\Frontend\Services`






==== Methods

[source%nowrap, php]
----

public getLanguages():array

----

    







[source%nowrap, php]
----

public getBrowser():string

----

    







[source%nowrap, php]
----

public getPlatform():string

----

    







[source%nowrap, php]
----

public getDevice():string

----

    







[source%nowrap, php]
----

public getIsDesktop():bool

----

    







[source%nowrap, php]
----

public getRobotName():string

----

    







[source%nowrap, php]
----

public getIsRobot():bool

----

    







[source%nowrap, php]
----

public getHttpHeaders():array

----

    







[source%nowrap, php]
----

public getIsMobile():bool

----

    







[source%nowrap, php]
----

public getIsTablet():bool

----

    








[[frontend_services_fileservice]]
=== FileService

Frontend-service for file information



==== Namespace

`Plenty\Modules\Frontend\Services`






==== Methods

[source%nowrap, php]
----

public addJsFile($jsFile):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$jsFile`
a|
|===


[source%nowrap, php]
----

public get($key):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|
|===


[source%nowrap, php]
----

public hasGetMutator($key):bool

----

    





Determine if a get mutator exists for an attribute.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|
|===


[source%nowrap, php]
----

public setAttributes($attributes):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$attributes`
a|
|===


[source%nowrap, php]
----

public setAttribute($key, $value):Plenty\Repositories\Models

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_repositories_models[`Models`]


Set a given attribute on the model.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|

|
a|`$value`
a|
|===


[source%nowrap, php]
----

public hasSetMutator($key):bool

----

    





Determine if a set mutator exists for an attribute.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|
|===


[source%nowrap, php]
----

public changeValue($key, $callback):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|

|link:http://php.net/callable[callable^]
a|`$callback`
a|
|===


[source%nowrap, php]
----

public offsetExists($offset):bool

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$offset`
a|
|===


[source%nowrap, php]
----

public offsetGet($offset):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$offset`
a|
|===


[source%nowrap, php]
----

public offsetSet($offset, $value):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$offset`
a|

|
a|`$value`
a|
|===


[source%nowrap, php]
----

public offsetUnset($offset):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$offset`
a|
|===


[source%nowrap, php]
----

public toArray($translate = false):array

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$translate`
a|Flag indicating if values should be translated.
|===


[source%nowrap, php]
----

public toJson($options):string

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$options`
a|
|===


[source%nowrap, php]
----

public jsonSerialize():void

----

    







[source%nowrap, php]
----

public fill($attributes):Plenty\Repositories\Models

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_repositories_models[`Models`]


Fill the model with an array of attributes.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$attributes`
a|
|===


[source%nowrap, php]
----

public isFillable($key):bool

----

    





Determine if the given attribute may be mass assigned.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|
|===


[source%nowrap, php]
----

public getFillable():array

----

    





Get the fillable attributes for the model.

[source%nowrap, php]
----

public fillable($fillable):Plenty\Repositories\Models

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_repositories_models[`Models`]


Set the fillable attributes for the model.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$fillable`
a|
|===


[source%nowrap, php]
----

public hasCast($key, $types = null):bool

----

    





Determine whether an attribute should be cast to a native type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|

|
a|`$types`
a|
|===


[source%nowrap, php]
----

public fromJson($value, $asObject = false):void

----

    





Decode the given JSON back into an array or object.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$value`
a|

|link:http://php.net/bool[bool^]
a|`$asObject`
a|
|===



[[frontend_services_localeservice]]
=== LocaleService

frontend service for changing current language



==== Namespace

`Plenty\Modules\Frontend\Services`






==== Methods

[source%nowrap, php]
----

public setLanguage($newLanguage, $fireEvents = true):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$newLanguage`
a|

|link:http://php.net/bool[bool^]
a|`$fireEvents`
a|
|===



[[frontend_services_orderpropertyfileservice]]
=== OrderPropertyFileService

Frontend-service for customer information



==== Namespace

`Plenty\Modules\Frontend\Services`






==== Methods

[source%nowrap, php]
----

public uploadFile($fileData):string

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$fileData`
a|
|===


[source%nowrap, php]
----

public getFileURL($key):string

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|
|===


[source%nowrap, php]
----

public getFile($key):Plenty\Modules\Cloud\Storage\Models\StorageObject

----

    


===== *Return type:*        xref:Cloud.adoc#cloud_models_storageobject[`StorageObject`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|
|===


[source%nowrap, php]
----

public copyBasketFileToOrder($filename):string

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$filename`
a|
|===


[source%nowrap, php]
----

public deleteFile($filename):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$filename`
a|
|===



[[frontend_services_systemservice]]
=== SystemService

Frontend-service for system information



==== Namespace

`Plenty\Modules\Frontend\Services`






==== Methods

[source%nowrap, php]
----

public getPlentyId():int

----

    







[source%nowrap, php]
----

public getWebstoreId():int

----

    








[[frontend_services_vatservice]]
=== VatService

Frontend-service for vat information



==== Namespace

`Plenty\Modules\Frontend\Services`






==== Methods

[source%nowrap, php]
----

public getCountryVatId():int

----

    







[source%nowrap, php]
----

public getCurrentTotalVats():array

----

    







[source%nowrap, php]
----

public getVat($taxIdNumber = &quot;&quot;):Plenty\Modules\Accounting\Vat\Models\Vat

----

    


===== *Return type:*        xref:Accounting.adoc#accounting_models_vat[`Vat`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$taxIdNumber`
a|
|===


[source%nowrap, php]
----

public getLocationId($countryId = null):int

----

    





Get the ID of the location

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$countryId`
a|
|===


[[frontend_legalinformation]]
= LegalInformation

[[frontend_legalinformation_contracts]]
== Contracts
[[frontend_contracts_legalinformationrepositorycontract]]
=== LegalInformationRepositoryContract

Repository contract for LegalInformation model.



==== Namespace

`Plenty\Modules\Frontend\LegalInformation\Contracts`






==== Methods

[source%nowrap, php]
----

public find($plentyId, $lang, $type):Plenty\Modules\Frontend\LegalInformation\Models\LegalInformation

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_models_legalinformation[`LegalInformation`]


Get legal information of an online store

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$plentyId`
a|The ID of the online store

|link:http://php.net/string[string^]
a|`$lang`
a|The language of the legal information text as ISO 639-1 code, e.g. e.g. en for English

|link:http://php.net/string[string^]
a|`$type`
a|The type of the legal information text. The types available are:
<ul>
<li>TermsConditions</li>
<li>CancellationRights</li>
<li>PrivacyPolicy</li>
<li>LegalDisclosure</li>
<li>WithdrawalForm</li>
</ul>
|===


[source%nowrap, php]
----

public save($data, $plentyId, $lang, $type):Plenty\Modules\Frontend\LegalInformation\Models\LegalInformation

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_models_legalinformation[`LegalInformation`]


Save legal information for an online store

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|Array of data for 'plainText' and 'htmlText'

|link:http://php.net/int[int^]
a|`$plentyId`
a|The plenty ID of the online store

|link:http://php.net/string[string^]
a|`$lang`
a|The language of the legal information text as ISO 639-1 code, e.g. en for English

|link:http://php.net/string[string^]
a|`$type`
a|The type of the legal information text. The types available are:
<ul>
<li>TermsConditions</li>
<li>CancellationRights</li>
<li>PrivacyPolicy</li>
<li>LegalDisclosure</li>
<li>WithdrawalForm</li>
</ul>
|===


[[frontend_legalinformation_models]]
== Models
[[frontend_models_legalinformation]]
=== LegalInformation

The legal information model.



==== Namespace

`Plenty\Modules\Frontend\LegalInformation\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|plentyId
    a|The unique identifier of the plenty client
|link:http://php.net/string[string^]
    a|lang
    a|The language of the legal information text
|link:http://php.net/string[string^]
    a|type
    a|The type of the legal information text. The types available are:
<ul>
<li>TermsConditions</li>
<li>CancellationRights</li>
<li>PrivacyPolicy</li>
<li>LegalDisclosure</li>
<li>WithdrawalForm</li>
</ul>
|link:http://php.net/string[string^]
    a|plainText
    a|The text value of the legal information text
|link:http://php.net/string[string^]
    a|htmlText
    a|The html value of the legal information text
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[frontend_paymentmethod]]
= PaymentMethod

[[frontend_paymentmethod_contracts]]
== Contracts
[[frontend_contracts_frontendpaymentmethodrepositorycontract]]
=== FrontendPaymentMethodRepositoryContract

The FrontendPaymentMethodRepositoryContract is the interface for the front end payment method repository. Get the payment method information to be displayed in the online store.



==== Namespace

`Plenty\Modules\Frontend\PaymentMethod\Contracts`






==== Methods

[source%nowrap, php]
----

public getCurrentPaymentMethodsList():array

----

    





Lists all payment methods of the current customer session.

[source%nowrap, php]
----

public getCurrentPaymentMethodsListForSwitch($currentPaymentMethodId, $orderId = null, $lang = &quot;de&quot;):array

----

    





Lists all payment methods for switch.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$currentPaymentMethodId`
a|

|link:http://php.net/int[int^]
a|`$orderId`
a|

|link:http://php.net/string[string^]
a|`$lang`
a|
|===


[source%nowrap, php]
----

public getCurrentPaymentMethodsForExpressCheckout():array

----

    





Lists all payment methods if express checkout is available

[source%nowrap, php]
----

public getPaymentMethodName($paymentMethod, $lang):string

----

    





Gets the name of the payment method in the specified language.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|`$paymentMethod`
a|The payment method

|link:http://php.net/string[string^]
a|`$lang`
a|The language
|===


[source%nowrap, php]
----

public getPaymentMethodFee($paymentMethod):float

----

    





Gets additional costs for the payment method. Additional costs can be entered in the config.json.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|`$paymentMethod`
a|The payment method
|===


[source%nowrap, php]
----

public getPaymentMethodIcon($paymentMethod, $lang):string

----

    





Gets the icon of the payment method. The path of the icon can be entered in the config.json.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|`$paymentMethod`
a|The payment method

|link:http://php.net/string[string^]
a|`$lang`
a|The language
|===


[source%nowrap, php]
----

public getPaymentMethodDescription($paymentMethod, $lang):string

----

    





Gets the description of the payment method. The description can be entered in the config.json.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|`$paymentMethod`
a|

|link:http://php.net/string[string^]
a|`$lang`
a|
|===


[source%nowrap, php]
----

public getPaymentMethodSourceUrl($paymentMethod):string

----

    





Gets the detail link of the payment method. The detail link can be entered in the config.json.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|`$paymentMethod`
a|
|===


[source%nowrap, php]
----

public getIsSwitchableTo($paymentMethod):bool

----

    





Gets the detail link of the payment method. The detail link can be entered in the config.json.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|`$paymentMethod`
a|
|===


[source%nowrap, php]
----

public getIsSwitchableFrom($paymentMethod):bool

----

    





Gets the detail link of the payment method. The detail link can be entered in the config.json.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|`$paymentMethod`
a|
|===


[source%nowrap, php]
----

public getPaymentMethodIsSelectable($paymentMethod):bool

----

    





Get true if the payment method can be selected in the payment method list

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|`$paymentMethod`
a|
|===


[source%nowrap, php]
----

public getPaymentMethodNameById($paymentMethodId, $lang):string

----

    





Gets the name of the payment method by ID and language. The ID of the payment method and the language must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$paymentMethodId`
a|The ID of the payment method

|link:http://php.net/string[string^]
a|`$lang`
a|The language
|===


[source%nowrap, php]
----

public getPaymentMethodFeeById($paymentMethodId):float

----

    





Gets additional costs for the payment method by ID. The ID of the payment method must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$paymentMethodId`
a|The ID of the payment method
|===


[source%nowrap, php]
----

public getPaymentMethodIconById($paymentMethodId, $lang):string

----

    





Gets the icon of the payment method by ID and language. The ID of the payment method and the language must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$paymentMethodId`
a|The ID of the payment method

|link:http://php.net/string[string^]
a|`$lang`
a|The language
|===


[source%nowrap, php]
----

public getPaymentMethodDescriptionById($paymentMethodId, $lang):string

----

    





Gets the description of the payment method by ID and language. The ID of the payment method and the language must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$paymentMethodId`
a|The ID of the payment method

|link:http://php.net/string[string^]
a|`$lang`
a|The language
|===


[source%nowrap, php]
----

public getPaymentMethodSwitchToById($paymentMethodId, $orderId = null):bool

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$paymentMethodId`
a|

|link:http://php.net/int[int^]
a|`$orderId`
a|
|===


[source%nowrap, php]
----

public getPaymentMethodSwitchFromById($paymentMethodId, $orderId = null):bool

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$paymentMethodId`
a|

|link:http://php.net/int[int^]
a|`$orderId`
a|
|===


[source%nowrap, php]
----

public getPaymentMethodSwitchableToById($paymentMethodId, $orderId = null):bool

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$paymentMethodId`
a|

|link:http://php.net/int[int^]
a|`$orderId`
a|
|===


[source%nowrap, php]
----

public getPaymentMethodSwitchableFromById($paymentMethodId, $orderId = null):bool

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$paymentMethodId`
a|

|link:http://php.net/int[int^]
a|`$orderId`
a|
|===


[source%nowrap, php]
----

public getAllowedPaymentMethodListForContact():void

----

    







[[frontend_session]]
= Session

[[frontend_session_events]]
== Events
[[frontend_events_aftersessioncreate]]
=== AfterSessionCreate

The event is triggered after a session is created.



==== Namespace

`Plenty\Modules\Frontend\Session\Events`





[[frontend_storage]]
= Storage

[[frontend_storage_contracts]]
== Contracts
[[frontend_contracts_frontendsessionstoragefactorycontract]]
=== FrontendSessionStorageFactoryContract

The FrontendSessionStorageFactoryContract is the interface for the front end session storage repository. This interface allows to get information about the locale, the customer, the order, the plugin and the forum from the session.



==== Namespace

`Plenty\Modules\Frontend\Session\Storage\Contracts`






==== Methods

[source%nowrap, php]
----

public getLocaleSettings():Plenty\Modules\Frontend\Session\Storage\Models\LocaleSettings

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_models_localesettings[`LocaleSettings`]


Get the locale settings from the session storage.

[source%nowrap, php]
----

public getCustomer():Plenty\Modules\Frontend\Session\Storage\Models\Customer

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_models_customer[`Customer`]


Get the customer data from the session storage.

[source%nowrap, php]
----

public getOrder():Plenty\Modules\Frontend\Session\Storage\Models\Order

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_models_order[`Order`]


Get the order data from the session storage.

[source%nowrap, php]
----

public getPlugin():Plenty\Modules\Frontend\Session\Storage\Models\Plugin

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_models_plugin[`Plugin`]


Get the plugin data from the session storage.

[source%nowrap, php]
----

public getForum():Plenty\Modules\Frontend\Session\Storage\Models\Forum

----

    


===== *Return type:*        xref:Frontend.adoc#frontend_models_forum[`Forum`]


Get the forum data from the session storage.

[[frontend_storage_models]]
== Models
[[frontend_models_customer]]
=== Customer

The session storage model for customer data.



==== Namespace

`Plenty\Modules\Frontend\Session\Storage\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|deliveryCountryId
    a|The ID of the country of delivery
|link:http://php.net/bool[bool^]
    a|showNetPrice
    a|Flag that indicates if the shown price is the net price
|link:http://php.net/string[string^]
    a|ebaySellerAccount
    a|The eBay seller account
|link:http://php.net/string[string^]
    a|accountContactSign
    a|The reference sign specified by the contact
|link:http://php.net/int[int^]
    a|accountContactClassId
    a|The ID of the contact class
|link:http://php.net/int[int^]
    a|sourceItemWishListAccountContactId
    a|The ID of the contact that created the wish list
|link:http://php.net/int[int^]
    a|sourceItemWishListAccountAddressId
    a|The ID of the address that created the wish list
|link:http://php.net/string[string^]
    a|salesAgent
    a|The sales representative
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[frontend_models_forum]]
=== Forum

The session storage model for forum data.



==== Namespace

`Plenty\Modules\Frontend\Session\Storage\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|forumGroupId
    a|The ID of the forum group
|link:http://php.net/string[string^]
    a|forumUsername
    a|The name of the user in the forum
|link:http://php.net/array[array^]
    a|forumConfig
    a|The forum configuration
|link:http://php.net/array[array^]
    a|forumPermissions
    a|The forum permissions
|link:http://php.net/int[int^]
    a|forumLastVisitTime
    a|The time the forum was visited last
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[frontend_models_localesettings]]
=== LocaleSettings

The session storage model for locale settings.



==== Namespace

`Plenty\Modules\Frontend\Session\Storage\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|currency
    a|The currency
|link:http://php.net/float[float^]
    a|currencyExchange
    a|The exchange rate for the currency
|link:http://php.net/string[string^]
    a|language
    a|The language
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[frontend_models_order]]
=== Order

The session storage model for order data.



==== Namespace

`Plenty\Modules\Frontend\Session\Storage\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|deliveryAddressId
    a|The ID of the delivery address
|link:http://php.net/int[int^]
    a|invoiceAddressId
    a|The ID of the invoice address
|link:http://php.net/int[int^]
    a|parcelServiceId
    a|The ID of the parcel service
|link:http://php.net/int[int^]
    a|parcelServicePresetId
    a|The preset ID of the parcel service
|link:http://php.net/int[int^]
    a|methodOfPayment
    a|The payment method
|link:http://php.net/bool[bool^]
    a|isNet
    a|Flag that indicates if the shown price is the net price
|link:http://php.net/int[int^]
    a|shippingCosts
    a|The shipping costs
|link:http://php.net/string[string^]
    a|orderinfoText
    a|Additional information specified by the customer in the order
|link:http://php.net/int[int^]
    a|payDataComplete
    a|
|link:http://php.net/array[array^]
    a|itemOrderParams
    a|The parameters of the order
|link:http://php.net/array[array^]
    a|uploadedFileStack
    a|
|link:http://php.net/array[array^]
    a|trustedShopBuyerProtection
    a|
|link:http://php.net/string[string^]
    a|trustedShopApplicationId
    a|
|link:http://php.net/string[string^]
    a|coupon
    a|The coupon code
|link:http://php.net/string[string^]
    a|couponDisplay
    a|
|        xref:Order.adoc#order_models_couponcodevalidation[`CouponCodeValidation`]
    a|couponCodeValidation
    a|
|link:http://php.net/array[array^]
    a|activePaymentMethodsList
    a|A list of active payment methods
|link:http://php.net/int[int^]
    a|referrerId
    a|The ID of the order referrer
|link:http://php.net/int[int^]
    a|referrerPriceColumn
    a|The price column for the order referrer
|link:http://php.net/int[int^]
    a|referrerItemId
    a|The ID of the item referrer
|link:http://php.net/int[int^]
    a|schedulerId
    a|The ID of the subscription
|link:http://php.net/int[int^]
    a|schedulerIntervalId
    a|The ID of the interval of a subscription
|link:http://php.net/int[int^]
    a|schedulerOrderExecutionId
    a|The ID for the execution of the order
|link:http://php.net/int[int^]
    a|schedulerFirstDeliveryDate
    a|The date for the first delivery of a subscription
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[frontend_models_plugin]]
=== Plugin

The session storage model for plugins.



==== Namespace

`Plenty\Modules\Frontend\Session\Storage\Models`






==== Methods

[source%nowrap, php]
----

public setValue($key, $value):void

----

    





Updates the value of a key. The key and the new value must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|

|
a|`$value`
a|
|===


[source%nowrap, php]
----

public getValue($key):void

----

    





Gets a value for a key. The key must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|
|===


[source%nowrap, php]
----

public unsetKey($key):void

----

    





Unsets a key. The key must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|
|===


