:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[frontend_frontend]]
== Frontend

[[frontend_frontend_contracts]]
===  Contracts
[[frontend_contracts_checkout]]
==== Checkout

The CheckoutContract is the interface for the checkout repository. This interface allows to set the shipping country ID, the payment method ID, the shipping profile ID and the currency in the checkout.



===== Namespace

`Plenty\Modules\Frontend\Contracts`






===== Methods

[source%nowrap, php]
[#getshippingcountryid]
----

public getShippingCountryId():int

----







Gets the shipping country ID.

[source%nowrap, php]
[#setshippingcountryid]
----

public setShippingCountryId($shippingCountryId):void

----







Updates the ID of the shipping country. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$shippingCountryId`
|link:http://php.net/int[int^]
a|The ID of the shipping country
|===


[source%nowrap, php]
[#getpaymentmethodid]
----

public getPaymentMethodId():int

----







Gets the payment method id of the current shopping cart.

[source%nowrap, php]
[#setpaymentmethodid]
----

public setPaymentMethodId($paymentMethodId):void

----







Updates the ID of the payment method. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|link:http://php.net/int[int^]
a|The ID of the payment method
|===


[source%nowrap, php]
[#getshippingprofileid]
----

public getShippingProfileId():int

----







Gets the shipping profile id of the current shopping cart.

[source%nowrap, php]
[#setshippingprofileid]
----

public setShippingProfileId($shippingProfileId):void

----







Updates the ID of the shipping profile. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$shippingProfileId`
|link:http://php.net/int[int^]
a|The ID of the shipping profile
|===


[source%nowrap, php]
[#getcurrency]
----

public getCurrency():string

----







Get the currency of the current shopping cart.

[source%nowrap, php]
[#setcurrency]
----

public setCurrency($currency):void

----







Updates the currency. The currency must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$currency`
|link:http://php.net/string[string^]
a|The currency
|===


[source%nowrap, php]
[#getbasketreferrerid]
----

public getBasketReferrerId():float

----







Get the referrer ID from the current shopping cart.

[source%nowrap, php]
[#setbasketreferrerid]
----

public setBasketReferrerId($referrerId):void

----







Updates the ID of the order referrer. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$referrerId`
|link:http://php.net/int[int^]
a|The ID of the order referrer. The <a href="https://www.plentymarkets.co.uk/manual/settings/orders/order-referrer/" target="_blank">order referrer</a> settings can be changed in the plentymarkets back end.
|===


[source%nowrap, php]
[#getcustomerinvoiceaddressid]
----

public getCustomerInvoiceAddressId():int

----







Gets the invoice address id of the current shopping cart.

[source%nowrap, php]
[#setcustomerinvoiceaddressid]
----

public setCustomerInvoiceAddressId($invoiceAddressId):void

----







Sets the invoice address id for the current shopping cart.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$invoiceAddressId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getcustomershippingaddressid]
----

public getCustomerShippingAddressId():int

----







Gets the shipping address id of the current shopping cart.

[source%nowrap, php]
[#setcustomershippingaddressid]
----

public setCustomerShippingAddressId($shippingAddressId):void

----







Sets the shipping address id for the current shopping cart.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$shippingAddressId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#validatecheckout]
----

public validateCheckout():Plenty\Modules\Frontend\Events\ValidateCheckoutEvent

----




====== *Return type:*        xref:Frontend.adoc#frontend_events_validatecheckoutevent[`ValidateCheckoutEvent`]


Validate all data of the checkout


[[frontend_contracts_currencyexchangerepositorycontract]]
==== CurrencyExchangeRepositoryContract

The CurrencyExchangeRatioRepositoryContract is the interface for the currency exchange repository. This interface allows you to get the default system currency, to get exchange ratios for every currency and to convert an amount from the default currency into a given currency or from a given currency into the default currency.



===== Namespace

`Plenty\Modules\Frontend\Contracts`






===== Methods

[source%nowrap, php]
[#getexchangeratiobycurrency]
----

public getExchangeRatioByCurrency($currency):float

----







Get the exchange rate for the given currency

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$currency`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getdefaultcurrency]
----

public getDefaultCurrency():string

----







Get the default currency.

[source%nowrap, php]
[#convertfromdefaultcurrency]
----

public convertFromDefaultCurrency($currency, $amount, $exchangeRatio = 0.0):float

----







Converts the given value from the default currency to the given currency.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$currency`
|link:http://php.net/string[string^]
a|

a|`$amount`
|link:http://php.net/float[float^]
a|

a|`$exchangeRatio`
|link:http://php.net/float[float^]
a|
|===


[source%nowrap, php]
[#converttodefaultcurrency]
----

public convertToDefaultCurrency($currency, $amount, $exchangeRatio = 0.0):float

----







Converts the given value to the default currency from the given currency.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$currency`
|link:http://php.net/string[string^]
a|

a|`$amount`
|link:http://php.net/float[float^]
a|

a|`$exchangeRatio`
|link:http://php.net/float[float^]
a|
|===


[[frontend_frontend_events]]
===  Events
[[frontend_events_frontendcurrencychanged]]
==== FrontendCurrencyChanged

The event is triggered when the currency is changed in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#getcurrency]
----

public getCurrency():string

----







Gets the changed currency.

[source%nowrap, php]
[#getcurrencyexchangeratio]
----

public getCurrencyExchangeRatio():float

----







Gets the exchange rate used for converting the currency.


[[frontend_events_frontendcustomeraddresschanged]]
==== FrontendCustomerAddressChanged

The event is triggered when a customer address is changed in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






[[frontend_events_frontendlanguagechanged]]
==== FrontendLanguageChanged

The event is triggered when the language is changed in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#getlanguage]
----

public getLanguage():string

----







Gets the language of the online store.

[source%nowrap, php]
[#isdetectedbybrowserlanguage]
----

public isDetectedByBrowserLanguage():bool

----







Get the flag for detection by browser language.


[[frontend_events_frontendpaymentmethodchanged]]
==== FrontendPaymentMethodChanged

The event is triggered when the payment method is changed in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#getpaymentmethodid]
----

public getPaymentMethodId():void

----







Gets the ID of the payment method.

[source%nowrap, php]
[#setpaymentmethodid]
----

public setPaymentMethodId($paymentMethodId):void

----







Updates the ID of the payment method. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|
a|
|===



[[frontend_events_frontendreferrerchanged]]
==== FrontendReferrerChanged

The event is triggered when the referrer id  is changed in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#getreferrerid]
----

public getReferrerId():void

----







Get the ID of the changed referrer

[source%nowrap, php]
[#setreferrerid]
----

public setReferrerId($referrerId):Plenty\Modules\Frontend\Events\FrontendReferrerChanged

----




====== *Return type:*        xref:Frontend.adoc#frontend_events_frontendreferrerchanged[`FrontendReferrerChanged`]


Set the ID of the changed referrer

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$referrerId`
|
a|
|===



[[frontend_events_frontendshippingcountrychanged]]
==== FrontendShippingCountryChanged

The event is triggered when the shipping country is changed in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#getshippingcountryid]
----

public getShippingCountryId():int

----







Gets the ID of the shipping country.

[source%nowrap, php]
[#setshippingcountryid]
----

public setShippingCountryId($shippingCountryId):Plenty\Modules\Frontend\Events\FrontendShippingCountryChanged

----




====== *Return type:*        xref:Frontend.adoc#frontend_events_frontendshippingcountrychanged[`FrontendShippingCountryChanged`]


Updates the ID of the shipping country. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$shippingCountryId`
|link:http://php.net/int[int^]
a|The ID of the shipping country
|===



[[frontend_events_frontendshippingprofilechanged]]
==== FrontendShippingProfileChanged

The event is triggered when the shipping profile is changed in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#getshippingprofileid]
----

public getShippingProfileId():void

----







Gets the ID of the shipping profile.

[source%nowrap, php]
[#setshippingprofileid]
----

public setShippingProfileId($shippingProfileId):void

----







Updates the ID of the shipping profile. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$shippingProfileId`
|
a|
|===



[[frontend_events_frontendupdatedeliveryaddress]]
==== FrontendUpdateDeliveryAddress

The event is triggered when the delivery address is changed in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#getaccountaddressid]
----

public getAccountAddressId():int

----







Gets the ID of the address saved for the account.


[[frontend_events_frontendupdateinvoiceaddress]]
==== FrontendUpdateInvoiceAddress

The event is triggered when the invoice address is changed in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#getaccountaddressid]
----

public getAccountAddressId():int

----







Gets the ID of the address saved for the account.


[[frontend_events_frontendupdatepaymentsettings]]
==== FrontendUpdatePaymentSettings

The event is triggered when the payment method is changed in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#getpaymentmethodid]
----

public getPaymentMethodId():int

----







Gets the ID of the payment method.


[[frontend_events_frontendupdateshippingsettings]]
==== FrontendUpdateShippingSettings

The event is triggered when the shipping method is updated in the online store.



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#getshippingcosts]
----

public getShippingCosts():float

----







Gets the shipping costs.

[source%nowrap, php]
[#getparcelserviceid]
----

public getParcelServiceId():int

----







Gets the ID of the shipping service provider.

[source%nowrap, php]
[#getparcelservicepresetid]
----

public getParcelServicePresetId():int

----







Gets the preset ID of the shipping service provider.


[[frontend_events_validatecheckoutevent]]
==== ValidateCheckoutEvent

Event to validate the complete checkout



===== Namespace

`Plenty\Modules\Frontend\Events`






===== Methods

[source%nowrap, php]
[#geterrorkeyslist]
----

public getErrorKeysList():array

----







Get a list of error keys.

[source%nowrap, php]
[#adderrorkey]
----

public addErrorKey($errorKey):Plenty\Modules\Frontend\Events

----




====== *Return type:*        xref:Frontend.adoc#frontend_frontend_events[`Events`]


Add an error key to the list.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$errorKey`
|link:http://php.net/string[string^]
a|
|===


[[frontend_frontend_factories]]
===  Factories
[[frontend_factories_frontendfactory]]
==== FrontendFactory

Factory to get information regarding the frontend



===== Namespace

`Plenty\Modules\Frontend\Factories`






===== Methods

[source%nowrap, php]
[#getlocale]
----

public getLocale():Plenty\Modules\Frontend\Services\LocaleService

----




====== *Return type:*        xref:Frontend.adoc#frontend_services_localeservice[`LocaleService`]


Get the locale service.

[source%nowrap, php]
[#getagent]
----

public getAgent():Plenty\Modules\Frontend\Services\AgentService

----




====== *Return type:*        xref:Frontend.adoc#frontend_services_agentservice[`AgentService`]


Get the agent service.

[source%nowrap, php]
[#getsystem]
----

public getSystem():Plenty\Modules\Frontend\Services\SystemService

----




====== *Return type:*        xref:Frontend.adoc#frontend_services_systemservice[`SystemService`]


Get the system service.

[source%nowrap, php]
[#getaccount]
----

public getAccount():Plenty\Modules\Frontend\Services\AccountService

----




====== *Return type:*        xref:Frontend.adoc#frontend_services_accountservice[`AccountService`]


Get the account service.

[source%nowrap, php]
[#getfile]
----

public getFile():Plenty\Modules\Frontend\Services\FileService

----




====== *Return type:*        xref:Frontend.adoc#frontend_services_fileservice[`FileService`]


Get the file service.

[[frontend_frontend_models]]
===  Models
[[frontend_models_totalvat]]
==== TotalVat

frontend total vat model



===== Namespace

`Plenty\Modules\Frontend\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|vatId
    |link:http://php.net/int[int^]
    a|
|vatAmount
    |link:http://php.net/float[float^]
    a|
|vatValue
    |link:http://php.net/float[float^]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[frontend_frontend_services]]
===  Services
[[frontend_services_accountservice]]
==== AccountService

Frontend-service for customer information



===== Namespace

`Plenty\Modules\Frontend\Services`






===== Methods

[source%nowrap, php]
[#getisaccountloggedin]
----

public getIsAccountLoggedIn():bool

----







Get the information if an account is currently logged in.

[source%nowrap, php]
[#getaccountcontactid]
----

public getAccountContactId():int

----







Get the ID of the currently logged in account.


[[frontend_services_agentservice]]
==== AgentService

Frontend-Service for agent information



===== Namespace

`Plenty\Modules\Frontend\Services`






===== Methods

[source%nowrap, php]
[#getlanguages]
----

public getLanguages():array

----







Get the current language.

[source%nowrap, php]
[#getbrowser]
----

public getBrowser():string

----







Get the current browser.

[source%nowrap, php]
[#getplatform]
----

public getPlatform():string

----







Get the current platform.

[source%nowrap, php]
[#getdevice]
----

public getDevice():string

----







Get the current device.

[source%nowrap, php]
[#getisdesktop]
----

public getIsDesktop():bool

----







Get information if the device is a desktop.

[source%nowrap, php]
[#getrobotname]
----

public getRobotName():string

----







Get the name of the robot.

[source%nowrap, php]
[#getisrobot]
----

public getIsRobot():bool

----







Get information if the visitor is a robot.

[source%nowrap, php]
[#gethttpheaders]
----

public getHttpHeaders():array

----







Get the http headers of the agent.

[source%nowrap, php]
[#getismobile]
----

public getIsMobile():bool

----







Get the information if the device is mobile.

[source%nowrap, php]
[#getistablet]
----

public getIsTablet():bool

----







Get the information if the device is a tablet.


[[frontend_services_fileservice]]
==== FileService

Frontend-service for file information



===== Namespace

`Plenty\Modules\Frontend\Services`






===== Methods

[source%nowrap, php]
[#addjsfile]
----

public addJsFile($jsFile):void

----







Add a js file to the list.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$jsFile`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($key):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#hasgetmutator]
----

public hasGetMutator($key):bool

----







Determine if a get mutator exists for an attribute.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#setattributes]
----

public setAttributes($attributes):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$attributes`
|
a|
|===


[source%nowrap, php]
[#setattribute]
----

public setAttribute($key, $value):Plenty\Repositories\Models

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_repositories_models[`Models`]


Set a given attribute on the model.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|

a|`$value`
|
a|
|===


[source%nowrap, php]
[#hassetmutator]
----

public hasSetMutator($key):bool

----







Determine if a set mutator exists for an attribute.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#changevalue]
----

public changeValue($key, $callback):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|

a|`$callback`
|link:http://php.net/callable[callable^]
a|
|===


[source%nowrap, php]
[#offsetexists]
----

public offsetExists($offset):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$offset`
|
a|
|===


[source%nowrap, php]
[#offsetget]
----

public offsetGet($offset):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$offset`
|
a|
|===


[source%nowrap, php]
[#offsetset]
----

public offsetSet($offset, $value):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$offset`
|
a|

a|`$value`
|
a|
|===


[source%nowrap, php]
[#offsetunset]
----

public offsetUnset($offset):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$offset`
|
a|
|===


[source%nowrap, php]
[#toarray]
----

public toArray($translate = false):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$translate`
|link:http://php.net/bool[bool^]
a|Flag indicating if values should be translated.
|===


[source%nowrap, php]
[#tojson]
----

public toJson($options):string

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#jsonserialize]
----

public jsonSerialize():void

----









[source%nowrap, php]
[#fill]
----

public fill($attributes):Plenty\Repositories\Models

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_repositories_models[`Models`]


Fill the model with an array of attributes.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$attributes`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#isfillable]
----

public isFillable($key):bool

----







Determine if the given attribute may be mass assigned.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getfillable]
----

public getFillable():array

----







Get the fillable attributes for the model.

[source%nowrap, php]
[#fillable]
----

public fillable($fillable):Plenty\Repositories\Models

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_repositories_models[`Models`]


Set the fillable attributes for the model.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fillable`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#hascast]
----

public hasCast($key, $types = null):bool

----







Determine whether an attribute should be cast to a native type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|

a|`$types`
|
a|
|===


[source%nowrap, php]
[#fromjson]
----

public fromJson($value, $asObject = false):void

----







Decode the given JSON back into an array or object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$value`
|link:http://php.net/string[string^]
a|

a|`$asObject`
|link:http://php.net/bool[bool^]
a|
|===



[[frontend_services_localeservice]]
==== LocaleService

frontend service for changing current language



===== Namespace

`Plenty\Modules\Frontend\Services`






===== Methods

[source%nowrap, php]
[#setlanguage]
----

public setLanguage($newLanguage, $fireEvents = true):void

----







Set the current language of the shop.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$newLanguage`
|link:http://php.net/string[string^]
a|

a|`$fireEvents`
|link:http://php.net/bool[bool^]
a|
|===



[[frontend_services_orderpropertyfileservice]]
==== OrderPropertyFileService

Frontend-service for order property files



===== Namespace

`Plenty\Modules\Frontend\Services`






===== Methods

[source%nowrap, php]
[#uploadfile]
----

public uploadFile($fileData):string

----







Upload an order property file.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fileData`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfileurl]
----

public getFileURL($key):string

----







Get the URL for the specified key.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getfile]
----

public getFile($key):Plenty\Modules\Cloud\Storage\Models\StorageObject

----




====== *Return type:*        xref:Cloud.adoc#cloud_models_storageobject[`StorageObject`]


Get the file for a specified key.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#copybasketfiletoorder]
----

public copyBasketFileToOrder($filename):string

----







Copy the uploaded file to the order.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filename`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#deletefile]
----

public deleteFile($filename):void

----







Delete the specified file.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filename`
|link:http://php.net/string[string^]
a|
|===



[[frontend_services_systemservice]]
==== SystemService

Frontend-service for system information



===== Namespace

`Plenty\Modules\Frontend\Services`






===== Methods

[source%nowrap, php]
[#getplentyid]
----

public getPlentyId():int

----







Get the plenty ID of the current client.

[source%nowrap, php]
[#getwebstoreid]
----

public getWebstoreId():int

----







get the webstore ID of the current client.


[[frontend_services_vatservice]]
==== VatService

Frontend-service for vat information



===== Namespace

`Plenty\Modules\Frontend\Services`






===== Methods

[source%nowrap, php]
[#getcountryvatid]
----

public getCountryVatId():int

----







Get the VAT ID of the specified country.

[source%nowrap, php]
[#getcurrenttotalvats]
----

public getCurrentTotalVats():array

----







Get the current total VAT.

[source%nowrap, php]
[#getvat]
----

public getVat($taxIdNumber = &quot;&quot;):Plenty\Modules\Accounting\Vat\Models\Vat

----




====== *Return type:*        xref:Accounting.adoc#accounting_models_vat[`Vat`]


Get VAT for the specified tax ID number

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$taxIdNumber`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getlocationid]
----

public getLocationId($countryId = null):int

----







Get the ID of the location.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$countryId`
|link:http://php.net/int[int^]
a|
|===


[[frontend_legalinformation]]
== LegalInformation

[[frontend_legalinformation_contracts]]
===  Contracts
[[frontend_contracts_legalinformationrepositorycontract]]
==== LegalInformationRepositoryContract

Repository contract for LegalInformation model.



===== Namespace

`Plenty\Modules\Frontend\LegalInformation\Contracts`






===== Methods

[source%nowrap, php]
[#find]
----

public find($plentyId, $lang, $type):Plenty\Modules\Frontend\LegalInformation\Models\LegalInformation

----




====== *Return type:*        xref:Frontend.adoc#frontend_models_legalinformation[`LegalInformation`]


Get legal information of an online store

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyId`
|link:http://php.net/int[int^]
a|The ID of the online store

a|`$lang`
|link:http://php.net/string[string^]
a|The language of the legal information text as ISO 639-1 code, e.g. e.g. en for English

a|`$type`
|link:http://php.net/string[string^]
a|The type of the legal information text. The types available are:
<ul>
<li>TermsConditions</li>
<li>CancellationRights</li>
<li>PrivacyPolicy</li>
<li>LegalDisclosure</li>
<li>WithdrawalForm</li>
</ul>
|===


[source%nowrap, php]
[#save]
----

public save($data, $plentyId, $lang, $type):Plenty\Modules\Frontend\LegalInformation\Models\LegalInformation

----




====== *Return type:*        xref:Frontend.adoc#frontend_models_legalinformation[`LegalInformation`]


Save legal information for an online store

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|Array of data for 'plainText' and 'htmlText'

a|`$plentyId`
|link:http://php.net/int[int^]
a|The plenty ID of the online store

a|`$lang`
|link:http://php.net/string[string^]
a|The language of the legal information text as ISO 639-1 code, e.g. en for English

a|`$type`
|link:http://php.net/string[string^]
a|The type of the legal information text. The types available are:
<ul>
<li>TermsConditions</li>
<li>CancellationRights</li>
<li>PrivacyPolicy</li>
<li>LegalDisclosure</li>
<li>WithdrawalForm</li>
</ul>
|===


[[frontend_legalinformation_models]]
===  Models
[[frontend_models_legalinformation]]
==== LegalInformation

The legal information model.



===== Namespace

`Plenty\Modules\Frontend\LegalInformation\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|plentyId
    |link:http://php.net/int[int^]
    a|The unique identifier of the plenty client
|lang
    |link:http://php.net/string[string^]
    a|The language of the legal information text
|type
    |link:http://php.net/string[string^]
    a|The type of the legal information text. The types available are:
<ul>
<li>TermsConditions</li>
<li>CancellationRights</li>
<li>PrivacyPolicy</li>
<li>LegalDisclosure</li>
<li>WithdrawalForm</li>
</ul>
|plainText
    |link:http://php.net/string[string^]
    a|The text value of the legal information text
|htmlText
    |link:http://php.net/string[string^]
    a|The html value of the legal information text
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[frontend_paymentmethod]]
== PaymentMethod

[[frontend_paymentmethod_contracts]]
===  Contracts
[[frontend_contracts_frontendpaymentmethodrepositorycontract]]
==== FrontendPaymentMethodRepositoryContract

The FrontendPaymentMethodRepositoryContract is the interface for the front end payment method repository. Get the payment method information to be displayed in the online store.



===== Namespace

`Plenty\Modules\Frontend\PaymentMethod\Contracts`






===== Methods

[source%nowrap, php]
[#getcurrentpaymentmethodslist]
----

public getCurrentPaymentMethodsList():array

----







Lists all payment methods of the current customer session.

[source%nowrap, php]
[#getcurrentpaymentmethodslistforswitch]
----

public getCurrentPaymentMethodsListForSwitch($currentPaymentMethodId, $orderId = null, $lang = &quot;de&quot;):array

----







Lists all payment methods for switch.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$currentPaymentMethodId`
|link:http://php.net/int[int^]
a|

a|`$orderId`
|link:http://php.net/int[int^]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getcurrentpaymentmethodsforexpresscheckout]
----

public getCurrentPaymentMethodsForExpressCheckout():array

----







Lists all payment methods if express checkout is available

[source%nowrap, php]
[#getpaymentmethodname]
----

public getPaymentMethodName($paymentMethod, $lang):string

----







Gets the name of the payment method in the specified language.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethod`
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|The payment method

a|`$lang`
|link:http://php.net/string[string^]
a|The language
|===


[source%nowrap, php]
[#getpaymentmethodfee]
----

public getPaymentMethodFee($paymentMethod):float

----







Gets additional costs for the payment method. Additional costs can be entered in the config.json.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethod`
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|The payment method
|===


[source%nowrap, php]
[#getpaymentmethodicon]
----

public getPaymentMethodIcon($paymentMethod, $lang):string

----







Gets the icon of the payment method. The path of the icon can be entered in the config.json.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethod`
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|The payment method

a|`$lang`
|link:http://php.net/string[string^]
a|The language
|===


[source%nowrap, php]
[#getpaymentmethoddescription]
----

public getPaymentMethodDescription($paymentMethod, $lang):string

----







Gets the description of the payment method. The description can be entered in the config.json.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethod`
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getpaymentmethodsourceurl]
----

public getPaymentMethodSourceUrl($paymentMethod):string

----







Gets the detail link of the payment method. The detail link can be entered in the config.json.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethod`
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|
|===


[source%nowrap, php]
[#getisswitchableto]
----

public getIsSwitchableTo($paymentMethod, $orderId = null):bool

----







Gets the detail link of the payment method. The detail link can be entered in the config.json.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethod`
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|

a|`$orderId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getisswitchablefrom]
----

public getIsSwitchableFrom($paymentMethod, $orderId = null):bool

----







Gets the detail link of the payment method. The detail link can be entered in the config.json.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethod`
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|

a|`$orderId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getpaymentmethodisselectable]
----

public getPaymentMethodIsSelectable($paymentMethod):bool

----







Get true if the payment method can be selected in the payment method list

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethod`
|        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
a|
|===


[source%nowrap, php]
[#getpaymentmethodnamebyid]
----

public getPaymentMethodNameById($paymentMethodId, $lang):string

----







Gets the name of the payment method by ID and language. The ID of the payment method and the language must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|link:http://php.net/int[int^]
a|The ID of the payment method

a|`$lang`
|link:http://php.net/string[string^]
a|The language
|===


[source%nowrap, php]
[#getpaymentmethodfeebyid]
----

public getPaymentMethodFeeById($paymentMethodId):float

----







Gets additional costs for the payment method by ID. The ID of the payment method must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|link:http://php.net/int[int^]
a|The ID of the payment method
|===


[source%nowrap, php]
[#getpaymentmethodiconbyid]
----

public getPaymentMethodIconById($paymentMethodId, $lang):string

----







Gets the icon of the payment method by ID and language. The ID of the payment method and the language must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|link:http://php.net/int[int^]
a|The ID of the payment method

a|`$lang`
|link:http://php.net/string[string^]
a|The language
|===


[source%nowrap, php]
[#getpaymentmethoddescriptionbyid]
----

public getPaymentMethodDescriptionById($paymentMethodId, $lang):string

----







Gets the description of the payment method by ID and language. The ID of the payment method and the language must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|link:http://php.net/int[int^]
a|The ID of the payment method

a|`$lang`
|link:http://php.net/string[string^]
a|The language
|===


[source%nowrap, php]
[#getpaymentmethodswitchtobyid]
----

public getPaymentMethodSwitchToById($paymentMethodId, $orderId = null):bool

----







Get all payment methods to which switching is allowed for the current payment method.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|link:http://php.net/int[int^]
a|

a|`$orderId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getpaymentmethodswitchfrombyid]
----

public getPaymentMethodSwitchFromById($paymentMethodId, $orderId = null):bool

----







Get all payment methods from which switching is allowed for the current payment method.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|link:http://php.net/int[int^]
a|

a|`$orderId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getpaymentmethodswitchabletobyid]
----

public getPaymentMethodSwitchableToById($paymentMethodId, $orderId = null):bool

----







Get information if switching to the payment method is allowed.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|link:http://php.net/int[int^]
a|

a|`$orderId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getpaymentmethodswitchablefrombyid]
----

public getPaymentMethodSwitchableFromById($paymentMethodId, $orderId = null):bool

----







Get information if switching from the payment method is allowed.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|link:http://php.net/int[int^]
a|

a|`$orderId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getallowedpaymentmethodlistforcontact]
----

public getAllowedPaymentMethodListForContact():void

----







Get all allowed payment methods for the current contact.

[[frontend_session]]
== Session

[[frontend_session_events]]
===  Events
[[frontend_events_aftersessioncreate]]
==== AfterSessionCreate

The event is triggered after a session is created.



===== Namespace

`Plenty\Modules\Frontend\Session\Events`





[[frontend_storage]]
== Storage

[[frontend_storage_contracts]]
===  Contracts
[[frontend_contracts_frontendsessionstoragefactorycontract]]
==== FrontendSessionStorageFactoryContract

The FrontendSessionStorageFactoryContract is the interface for the front end session storage repository. This interface allows to get information about the locale, the customer, the order, the plugin and the forum from the session.



===== Namespace

`Plenty\Modules\Frontend\Session\Storage\Contracts`






===== Methods

[source%nowrap, php]
[#getlocalesettings]
----

public getLocaleSettings():Plenty\Modules\Frontend\Session\Storage\Models\LocaleSettings

----




====== *Return type:*        xref:Frontend.adoc#frontend_models_localesettings[`LocaleSettings`]


Get the locale settings from the session storage.

[source%nowrap, php]
[#getcustomer]
----

public getCustomer():Plenty\Modules\Frontend\Session\Storage\Models\Customer

----




====== *Return type:*        xref:Frontend.adoc#frontend_models_customer[`Customer`]


Get the customer data from the session storage.

[source%nowrap, php]
[#getorder]
----

public getOrder():Plenty\Modules\Frontend\Session\Storage\Models\Order

----




====== *Return type:*        xref:Frontend.adoc#frontend_models_order[`Order`]


Get the order data from the session storage.

[source%nowrap, php]
[#getplugin]
----

public getPlugin():Plenty\Modules\Frontend\Session\Storage\Models\Plugin

----




====== *Return type:*        xref:Frontend.adoc#frontend_models_plugin[`Plugin`]


Get the plugin data from the session storage.

[source%nowrap, php]
[#getforum]
----

public getForum():Plenty\Modules\Frontend\Session\Storage\Models\Forum

----




====== *Return type:*        xref:Frontend.adoc#frontend_models_forum[`Forum`]


Get the forum data from the session storage.

[[frontend_storage_models]]
===  Models
[[frontend_models_customer]]
==== Customer

The session storage model for customer data.



===== Namespace

`Plenty\Modules\Frontend\Session\Storage\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|deliveryCountryId
    |link:http://php.net/int[int^]
    a|The ID of the country of delivery
|showNetPrice
    |link:http://php.net/bool[bool^]
    a|Flag that indicates if the shown price is the net price
|ebaySellerAccount
    |link:http://php.net/string[string^]
    a|The eBay seller account
|accountContactSign
    |link:http://php.net/string[string^]
    a|The reference sign specified by the contact
|accountContactClassId
    |link:http://php.net/int[int^]
    a|The ID of the contact class
|sourceItemWishListAccountContactId
    |link:http://php.net/int[int^]
    a|The ID of the contact that created the wish list
|sourceItemWishListAccountAddressId
    |link:http://php.net/int[int^]
    a|The ID of the address that created the wish list
|salesAgent
    |link:http://php.net/string[string^]
    a|The sales representative
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[frontend_models_forum]]
==== Forum

The session storage model for forum data.



===== Namespace

`Plenty\Modules\Frontend\Session\Storage\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|forumGroupId
    |link:http://php.net/int[int^]
    a|The ID of the forum group
|forumUsername
    |link:http://php.net/string[string^]
    a|The name of the user in the forum
|forumConfig
    |link:http://php.net/array[array^]
    a|The forum configuration
|forumPermissions
    |link:http://php.net/array[array^]
    a|The forum permissions
|forumLastVisitTime
    |link:http://php.net/int[int^]
    a|The time the forum was visited last
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[frontend_models_localesettings]]
==== LocaleSettings

The session storage model for locale settings.



===== Namespace

`Plenty\Modules\Frontend\Session\Storage\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|currency
    |link:http://php.net/string[string^]
    a|The currency
|currencyExchange
    |link:http://php.net/float[float^]
    a|The exchange rate for the currency
|language
    |link:http://php.net/string[string^]
    a|The language
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[frontend_models_order]]
==== Order

The session storage model for order data.



===== Namespace

`Plenty\Modules\Frontend\Session\Storage\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|deliveryAddressId
    |link:http://php.net/int[int^]
    a|The ID of the delivery address
|invoiceAddressId
    |link:http://php.net/int[int^]
    a|The ID of the invoice address
|parcelServiceId
    |link:http://php.net/int[int^]
    a|The ID of the parcel service
|parcelServicePresetId
    |link:http://php.net/int[int^]
    a|The preset ID of the parcel service
|methodOfPayment
    |link:http://php.net/int[int^]
    a|The payment method
|isNet
    |link:http://php.net/bool[bool^]
    a|Flag that indicates if the shown price is the net price
|shippingCosts
    |link:http://php.net/int[int^]
    a|The shipping costs
|orderinfoText
    |link:http://php.net/string[string^]
    a|Additional information specified by the customer in the order
|payDataComplete
    |link:http://php.net/int[int^]
    a|
|itemOrderParams
    |link:http://php.net/array[array^]
    a|The parameters of the order
|uploadedFileStack
    |link:http://php.net/array[array^]
    a|
|trustedShopBuyerProtection
    |link:http://php.net/array[array^]
    a|
|trustedShopApplicationId
    |link:http://php.net/string[string^]
    a|
|coupon
    |link:http://php.net/string[string^]
    a|The coupon code
|couponDisplay
    |link:http://php.net/string[string^]
    a|
|couponCodeValidation
    |        xref:Order.adoc#order_models_couponcodevalidation[`CouponCodeValidation`]
    a|
|activePaymentMethodsList
    |link:http://php.net/array[array^]
    a|A list of active payment methods
|referrerId
    |link:http://php.net/int[int^]
    a|The ID of the order referrer
|referrerPriceColumn
    |link:http://php.net/int[int^]
    a|The price column for the order referrer
|referrerItemId
    |link:http://php.net/int[int^]
    a|The ID of the item referrer
|schedulerId
    |link:http://php.net/int[int^]
    a|The ID of the subscription
|schedulerIntervalId
    |link:http://php.net/int[int^]
    a|The ID of the interval of a subscription
|schedulerOrderExecutionId
    |link:http://php.net/int[int^]
    a|The ID for the execution of the order
|schedulerFirstDeliveryDate
    |link:http://php.net/int[int^]
    a|The date for the first delivery of a subscription
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[frontend_models_plugin]]
==== Plugin

The session storage model for plugins.



===== Namespace

`Plenty\Modules\Frontend\Session\Storage\Models`






===== Methods

[source%nowrap, php]
[#setvalue]
----

public setValue($key, $value):void

----







Updates the value of a key. The key and the new value must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|

a|`$value`
|
a|
|===


[source%nowrap, php]
[#getvalue]
----

public getValue($key):void

----







Gets a value for a key. The key must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#unsetkey]
----

public unsetKey($key):void

----







Unsets a key. The key must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|
|===


