:table-caption!:
:example-caption!:
:source-highlighter: prettify
= Plentymarkets interface documentation


[[fulfillment_picklist]]
== Picklist

[[fulfillment_picklist_contracts]]
===  Contracts
==== PickingOrderItemRepositoryContract

The PickingOrderItemRepositoryContract



===== Namespace

`Plenty\Modules\Fulfillment\Picklist\Contracts`






===== Methods

[source%nowrap, php]
----

public getAll():Illuminate\Database\Eloquent\Collection // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous_eloquent_collection[Collection^]

    

[source%nowrap, php]
----

public getPickingOrderItemById($pickingOrderItemId):Plenty\Modules\Fulfillment\Picklist\Models\PickingOrderItem // <1>

----


    



===== Return type
    
<1> link:fulfillment#fulfillment_models_pickingorderitem[PickingOrderItem^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$pickingOrderItemId`
|
|===


[[fulfillment_picklist_events]]
===  Events
==== GetPickingItemConfig

This event will be triggered, when an item is picked



===== Namespace

`Plenty\Modules\Fulfillment\Picklist\Events`






===== Methods

[source%nowrap, php]
----

public getPickingOrderItemId():int // <1>

----


    



===== Return type
    
<1> link:http://php.net/int[int^]
    

[source%nowrap, php]
----

public getProcessUserId():int // <1>

----


    



===== Return type
    
<1> link:http://php.net/int[int^]
    

[source%nowrap, php]
----

public addPluginConfig($identifier, $pluginConfig):Plenty\Modules\Fulfillment\Picklist\Events // <1>

----


    



===== Return type
    
<1> link:fulfillment#fulfillment_picklist_events[Events^]

    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$identifier`
|

|link:miscellaneous#miscellaneous__[^]

a|`$pluginConfig`
|
|===


[source%nowrap, php]
----

public getPluginConfigs():array // <1>

----


    



===== Return type
    
<1> link:http://php.net/array[array^]
    

[[fulfillment_picklist_models]]
===  Models
==== PickingOrderItem

PickingOrderItem



===== Namespace

`Plenty\Modules\Fulfillment\Picklist\Models`





.Properties
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    |id
    |
|link:http://php.net/int[int^]
    |pickingOrderId
    |
|link:http://php.net/int[int^]
    |orderItemId
    |
|link:http://php.net/string[string^]
    |processState
    |
|link:miscellaneous#miscellaneous__[^]

    |processDate
    |
|link:http://php.net/int[int^]
    |processUserId
    |
|link:http://php.net/string[string^]
    |comment
    |
|link:http://php.net/float[float^]
    |quantity
    |
|link:http://php.net/int[int^]
    |itemId
    |
|link:http://php.net/int[int^]
    |holdingArea
    |
|link:http://php.net/int[int^]
    |warehouseId
    |
|link:http://php.net/string[string^]
    |orderIdList
    |
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----


    
Returns this model as an array.



[[fulfillment_fulfillment]]
== Fulfillment

[[fulfillment_fulfillment_services]]
===  Services
==== FulfillmentReturnService

The FulfillmentReturnService is the service for return shipments of an order.



===== Namespace

`Plenty\Modules\Fulfillment\Services`






===== Methods

[source%nowrap, php]
----

public registerReturns($orderId):bool // <1>

----


    
Register the return of an order.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
|The ID of the order
|===


[source%nowrap, php]
----

public registerReturn($orderId, $returnProvider):bool // <1>

----


    
Register the return of an order


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
|

|link:http://php.net/string[string^]
a|`$returnProvider`
|
|===



==== FulfillmentShipmentService

The FulfillmentShipmentService is the service for registering and cancelling shipments of an order.



===== Namespace

`Plenty\Modules\Fulfillment\Services`






===== Methods

[source%nowrap, php]
----

public cancelShipment($orderId):bool // <1>

----


    
Cancel the shipment of an order.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
|The ID of the order
|===


[source%nowrap, php]
----

public registerShipment($orderId):bool // <1>

----


    
Register the shipment of an order.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
|The ID of the order
|===



==== GetDhlRetoureOnlineDataService

The GetDhlRetoureOnlineDataService is the service that retrieves old DHL Retoure Online data.



===== Namespace

`Plenty\Modules\Fulfillment\Services`






===== Methods

[source%nowrap, php]
----

public getDhlRetoureOnlineData():void // <1>

----


    



===== Return type
    
<1> link:miscellaneous#miscellaneous__void[void^]

    

