:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[helper_automaticemail]]
== AutomaticEmail

[[helper_automaticemail_contracts]]
===  Contracts
[[helper_contracts_automaticemailcontract]]
==== AutomaticEmailContract

This service provides a method to initiate the automatic email delivery.



===== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Contracts`






===== Methods

[source%nowrap, php]
[#sendautomatic]
----

public sendAutomatic($email):bool

----







Send the automatic email.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$email`
|        xref:Helper.adoc#helper_models_automaticemail[`AutomaticEmail`]
a|
|===


[[helper_automaticemail_models]]
===  Models
[[helper_models_automaticemail]]
==== AutomaticEmail

A container with all needed data to initiate the automatic email delivery.



===== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[helper_models_automaticemailcontact]]
==== AutomaticEmailContact

The automatic email data for contact type emails.



===== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[helper_models_automaticemaildata]]
==== AutomaticEmailData

The abstract base class for all automatic email data. Provides constants for the email type to be used.



===== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[helper_models_automaticemailnewsletter]]
==== AutomaticEmailNewsletter

The automatic email data for newsletter type emails.



===== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[helper_models_automaticemailorder]]
==== AutomaticEmailOrder

The automatic email data for order type emails.



===== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[helper_models_automaticemailtemplate]]
==== AutomaticEmailTemplate

Provides constants for the automatic email template names.



===== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[helper_helper]]
== Helper

[[helper_helper_configuration]]
===  Configuration
[[helper_configuration_getapicalllimits]]
==== GetApiCallLimits

GetApiCallLimits reads the values for the API call limits from the config and returns them as an array.



===== Namespace

`Plenty\Modules\Helper\Configuration`






===== Methods

[source%nowrap, php]
[#get]
----

public get():array

----









[[helper_helper_contracts]]
===  Contracts
[[helper_contracts_urlbuilderrepositorycontract]]
==== UrlBuilderRepositoryContract

Repository Contract for retrieving image and item URLs



===== Namespace

`Plenty\Modules\Helper\Contracts`






===== Methods

[source%nowrap, php]
[#getimageurl]
----

public getImageUrl($path, $plentyId = null, $size = &quot;&quot;, $fileType = &quot;&quot;, $isExternalImage = false):string

----







Get the URL of an image.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$path`
|link:http://php.net/string[string^]
a|

a|`$plentyId`
|link:http://php.net/int[int^]
a|

a|`$size`
|link:http://php.net/string[string^]
a|

a|`$fileType`
|link:http://php.net/string[string^]
a|

a|`$isExternalImage`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#getitemurl]
----

public getItemUrl($itemId, $plentyId, $urlContent = &quot;&quot;, $lang = &quot;de&quot;, $useHttpsDomain = true):string

----







Get the URL of an item.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|

a|`$plentyId`
|link:http://php.net/int[int^]
a|

a|`$urlContent`
|link:http://php.net/string[string^]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|

a|`$useHttpsDomain`
|link:http://php.net/bool[bool^]
a|
|===


[[helper_helper_exceptions]]
===  Exceptions
[[helper_exceptions_encryptionexception]]
==== EncryptionException

Class EncryptionException



===== Namespace

`Plenty\Modules\Helper\Exceptions`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($message, $code):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$message`
|link:http://php.net/string[string^]
a|

a|`$code`
|link:http://php.net/int[int^]
a|
|===


[[helper_helper_models]]
===  Models
[[helper_models_keyvalue]]
==== KeyValue

key value data



===== Namespace

`Plenty\Modules\Helper\Models`






===== Methods

[source%nowrap, php]
[#get]
----

public get($key, $default = null):mixed

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|

a|`$default`
|
a|
|===


[[helper_helper_services]]
===  Services
[[helper_services_arrayhelper]]
==== ArrayHelper

Helper class for arrays



===== Namespace

`Plenty\Modules\Helper\Services`






===== Methods

[source%nowrap, php]
[#buildmapfromobjectlist]
----

public buildMapFromObjectList($list, $keyField, $valueField):Plenty\Modules\Helper\Models\KeyValue

----




====== *Return type:*        xref:Helper.adoc#helper_models_keyvalue[`KeyValue`]


Build an array out of the specified object list.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$list`
|
a|

a|`$keyField`
|link:http://php.net/string[string^]
a|

a|`$valueField`
|link:http://php.net/string[string^]
a|
|===



[[helper_services_stringencodingservice]]
==== StringEncodingService

Service for encoding strings



===== Namespace

`Plenty\Modules\Helper\Services`






===== Methods

[source%nowrap, php]
[#todatabase]
----

public toDatabase($sString):string

----







Method converts a string to self::DATABASE_ENCODING coding

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sString`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#toemail]
----

public toEmail($sString):string

----







Method converts a string to self::EMAIL_ENCODING coding

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sString`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#towebshop]
----

public toWebshop($sString, $sTargetEncoding = self::WEBSHOP_ENCODING):string

----







Method converts a string to self::WEBSHOP_ENCODING coding

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sString`
|link:http://php.net/string[string^]
a|

a|`$sTargetEncoding`
|link:http://php.net/string[string^]
a|[optional default=PlentyCoding::WEBSHOP_ENCODING]
|===


[source%nowrap, php]
[#toadmin]
----

public toAdmin($sString, $sTargetEncoding = self::ADMIN_ENCODING):string

----







Method converts a string to the sended coding. Default will be self::ADMIN_ENCODING coding used

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sString`
|link:http://php.net/string[string^]
a|

a|`$sTargetEncoding`
|link:http://php.net/string[string^]
a|[optional default=PlentyCoding::ADMIN_ENCODING]
|===


[source%nowrap, php]
[#togwt]
----

public toGwt($sString):string

----







Method converts a string to the sended coding

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sString`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#toexport]
----

public toExport($sString, $sTargetEncoding = self::EXPORT_ENCODING):string

----







Method converts a string to the sended coding. Default will be self::EXPORT_ENCODING coding used

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sString`
|link:http://php.net/string[string^]
a|

a|`$sTargetEncoding`
|link:http://php.net/string[string^]
a|[optional default=PlentyCoding::EXPORT_ENCODING]
|===


[source%nowrap, php]
[#tolegacy]
----

public toLegacy($sString):string

----







Method converts a string to self::LEGACY_ENCODING coding

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sString`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#topdf]
----

public toPDF($sString, $sTargetEncoding = self::PDF_ENCODING):string

----







Method converts a string to self::PDF_ENCODING coding

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sString`
|link:http://php.net/string[string^]
a|The string to be encoded.

a|`$sTargetEncoding`
|link:http://php.net/string[string^]
a|The target encoding (since plentymarkets version 5.100). [optional, default=PlentyCoding::PDF_ENCODING]
|===


[source%nowrap, php]
[#toxml]
----

public toXML($string, $targetEncoding = self::XML_ENCODING):string

----







Method converts a string to self::XML_ENCODING coding.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$string`
|link:http://php.net/string[string^]
a|The string to be encoded.

a|`$targetEncoding`
|link:http://php.net/string[string^]
a|The target encoding (since plentymarkets version 5.100). [optional, default=PlentyCoding::XML_ENCODING]
|===


[source%nowrap, php]
[#detect_encoding]
----

public detect_encoding($sString):string

----







Method returns the encoding of one string

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sString`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#convertarray]
----

public convertArray($array, $sTargetEncoding = self::UTF8_ENCODING, $convertKey = false):array

----







Method converts a multidimensional array to the desired coding

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$array`
|link:http://php.net/array[array^]
a|

a|`$sTargetEncoding`
|link:http://php.net/string[string^]
a|[optional, default=PlentyCoding::UTF8_ENCODING]

a|`$convertKey`
|link:http://php.net/bool[bool^]
a|[optional, default=false]
|===


[source%nowrap, php]
[#cuttextfordb]
----

public cutTextForDB($text, $lenghtIntoDB):string

----







cut the given text to fit for db insert.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$text`
|link:http://php.net/string[string^]
a|

a|`$lenghtIntoDB`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#isvalidutf8]
----

public isValidUtf8($string):int

----







Checks whether the given string is valid utf-8.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$string`
|link:http://php.net/string[string^]
a|
|===



[[helper_services_webstorehelper]]
==== WebstoreHelper

Webstore Helper Service



===== Namespace

`Plenty\Modules\Helper\Services`






===== Methods

[source%nowrap, php]
[#getcurrentwebstoreconfiguration]
----

public getCurrentWebstoreConfiguration():Plenty\Modules\System\Models\WebstoreConfiguration

----




====== *Return type:*        xref:System.adoc#system_models_webstoreconfiguration[`WebstoreConfiguration`]


Get the configuration of the current webstore.

