:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[helper_automaticemail]]
= AutomaticEmail

[[helper_automaticemail_contracts]]
== Contracts
[[helper_contracts_automaticemailcontract]]
=== AutomaticEmailContract

This service provides a method to initiate the automatic email delivery.



==== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Contracts`






==== Methods

[source%nowrap, php]
----

public sendAutomatic($email):bool

----

    





Send the automatic email.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Helper.adoc#helper_models_automaticemail[`AutomaticEmail`]
a|`$email`
a|
|===


[[helper_automaticemail_models]]
== Models
[[helper_models_automaticemail]]
=== AutomaticEmail

A container with all needed data to initiate the automatic email delivery.



==== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[helper_models_automaticemailcontact]]
=== AutomaticEmailContact

The automatic email data for contact type emails.



==== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[helper_models_automaticemaildata]]
=== AutomaticEmailData

The abstract base class for all automatic email data. Provides constants for the email type to be used.



==== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[helper_models_automaticemailnewsletter]]
=== AutomaticEmailNewsletter

The automatic email data for newsletter type emails.



==== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[helper_models_automaticemailorder]]
=== AutomaticEmailOrder

The automatic email data for order type emails.



==== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[helper_models_automaticemailtemplate]]
=== AutomaticEmailTemplate

Provides constants for the automatic email template names.



==== Namespace

`Plenty\Modules\Helper\AutomaticEmail\Models`






==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[helper_helper]]
= Helper

[[helper_helper_configuration]]
== Configuration
[[helper_configuration_getapicalllimits]]
=== GetApiCallLimits

GetApiCallLimits reads the values for the API call limits from the config and returns them as an array.



==== Namespace

`Plenty\Modules\Helper\Configuration`






==== Methods

[source%nowrap, php]
----

public get():array

----

    







[[helper_helper_contracts]]
== Contracts
[[helper_contracts_urlbuilderrepositorycontract]]
=== UrlBuilderRepositoryContract

Repository Contract for UrlBuilder



==== Namespace

`Plenty\Modules\Helper\Contracts`






==== Methods

[source%nowrap, php]
----

public getImageUrl($path, $plentyId = null, $size = &quot;&quot;, $fileType = &quot;&quot;, $isExternalImage = false):string

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$path`
a|

|link:http://php.net/int[int^]
a|`$plentyId`
a|

|link:http://php.net/string[string^]
a|`$size`
a|

|link:http://php.net/string[string^]
a|`$fileType`
a|

|link:http://php.net/bool[bool^]
a|`$isExternalImage`
a|
|===


[source%nowrap, php]
----

public getItemUrl($itemId, $plentyId, $urlContent = &quot;&quot;, $lang = &quot;de&quot;, $useHttpsDomain = true):string

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
a|

|link:http://php.net/int[int^]
a|`$plentyId`
a|

|link:http://php.net/string[string^]
a|`$urlContent`
a|

|link:http://php.net/string[string^]
a|`$lang`
a|

|link:http://php.net/bool[bool^]
a|`$useHttpsDomain`
a|
|===


[[helper_helper_exceptions]]
== Exceptions
[[helper_exceptions_encryptionexception]]
=== EncryptionException

Class EncryptionException



==== Namespace

`Plenty\Modules\Helper\Exceptions`






==== Methods

[source%nowrap, php]
----

public __construct($message, $code):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$message`
a|

|link:http://php.net/int[int^]
a|`$code`
a|
|===


[[helper_helper_models]]
== Models
[[helper_models_keyvalue]]
=== KeyValue

key value data



==== Namespace

`Plenty\Modules\Helper\Models`






==== Methods

[source%nowrap, php]
----

public get($key, $default = null):mixed

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
a|

|
a|`$default`
a|
|===


[[helper_helper_services]]
== Services
[[helper_services_arrayhelper]]
=== ArrayHelper

helper class for arrays



==== Namespace

`Plenty\Modules\Helper\Services`






==== Methods

[source%nowrap, php]
----

public buildMapFromObjectList($list, $keyField, $valueField):Plenty\Modules\Helper\Models\KeyValue

----

    


===== *Return type:*        xref:Helper.adoc#helper_models_keyvalue[`KeyValue`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$list`
a|

|link:http://php.net/string[string^]
a|`$keyField`
a|

|link:http://php.net/string[string^]
a|`$valueField`
a|
|===



[[helper_services_stringencodingservice]]
=== StringEncodingService

Service for encoding strings



==== Namespace

`Plenty\Modules\Helper\Services`






==== Methods

[source%nowrap, php]
----

public toDatabase($sString):string

----

    





Method converts a string to self::DATABASE_ENCODING coding

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sString`
a|
|===


[source%nowrap, php]
----

public toEmail($sString):string

----

    





Method converts a string to self::EMAIL_ENCODING coding

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sString`
a|
|===


[source%nowrap, php]
----

public toWebshop($sString, $sTargetEncoding = self::WEBSHOP_ENCODING):string

----

    





Method converts a string to self::WEBSHOP_ENCODING coding

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sString`
a|

|link:http://php.net/string[string^]
a|`$sTargetEncoding`
a|[optional default=PlentyCoding::WEBSHOP_ENCODING]
|===


[source%nowrap, php]
----

public toAdmin($sString, $sTargetEncoding = self::ADMIN_ENCODING):string

----

    





Method converts a string to the sended coding. Default will be self::ADMIN_ENCODING coding used

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sString`
a|

|link:http://php.net/string[string^]
a|`$sTargetEncoding`
a|[optional default=PlentyCoding::ADMIN_ENCODING]
|===


[source%nowrap, php]
----

public toGwt($sString):string

----

    





Method converts a string to the sended coding

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sString`
a|
|===


[source%nowrap, php]
----

public toExport($sString, $sTargetEncoding = self::EXPORT_ENCODING):string

----

    





Method converts a string to the sended coding. Default will be self::EXPORT_ENCODING coding used

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sString`
a|

|link:http://php.net/string[string^]
a|`$sTargetEncoding`
a|[optional default=PlentyCoding::EXPORT_ENCODING]
|===


[source%nowrap, php]
----

public toLegacy($sString):string

----

    





Method converts a string to self::LEGACY_ENCODING coding

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sString`
a|
|===


[source%nowrap, php]
----

public toPDF($sString, $sTargetEncoding = self::PDF_ENCODING):string

----

    





Method converts a string to self::PDF_ENCODING coding

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sString`
a|The string to be encoded.

|link:http://php.net/string[string^]
a|`$sTargetEncoding`
a|The target encoding (since plentymarkets version 5.100). [optional, default=PlentyCoding::PDF_ENCODING]
|===


[source%nowrap, php]
----

public toXML($string, $targetEncoding = self::XML_ENCODING):string

----

    





Method converts a string to self::XML_ENCODING coding.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$string`
a|The string to be encoded.

|link:http://php.net/string[string^]
a|`$targetEncoding`
a|The target encoding (since plentymarkets version 5.100). [optional, default=PlentyCoding::XML_ENCODING]
|===


[source%nowrap, php]
----

public detect_encoding($sString):string

----

    





Method returns the encoding of one string

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sString`
a|
|===


[source%nowrap, php]
----

public convertArray($array, $sTargetEncoding = self::UTF8_ENCODING, $convertKey = false):array

----

    





Method converts a multidimensional array to the desired coding

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$array`
a|

|link:http://php.net/string[string^]
a|`$sTargetEncoding`
a|[optional, default=PlentyCoding::UTF8_ENCODING]

|link:http://php.net/bool[bool^]
a|`$convertKey`
a|[optional, default=false]
|===


[source%nowrap, php]
----

public cutTextForDB($text, $lenghtIntoDB):string

----

    





cut the given text to fit for db insert.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$text`
a|

|link:http://php.net/int[int^]
a|`$lenghtIntoDB`
a|
|===


[source%nowrap, php]
----

public isValidUtf8($string):int

----

    





Checks whether the given string is valid utf-8.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$string`
a|
|===



[[helper_services_webstorehelper]]
=== WebstoreHelper

Webstore Helper Service



==== Namespace

`Plenty\Modules\Helper\Services`






==== Methods

[source%nowrap, php]
----

public getCurrentWebstoreConfiguration():Plenty\Modules\System\Models\WebstoreConfiguration

----

    


===== *Return type:*        xref:System.adoc#system_models_webstoreconfiguration[`WebstoreConfiguration`]




