:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[itemset_itemset]]
== ItemSet

[[itemset_itemset_contracts]]
===  Contracts
[[itemset_contracts_itemsetcomponentrepositorycontract]]
==== ItemSetComponentRepositoryContract

The contract for the item set component repository



===== Namespace

`Plenty\Modules\ItemSet\Contracts`






===== Methods

[source%nowrap, php]
[#show]
----

public show($id, $with):Plenty\Modules\ItemSet\Models\ItemSetComponent

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Gets an item set component. The ID of the item set component must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The unique ID of the item set component

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($setId, $id):Plenty\Modules\ItemSet\Models\ItemSetComponent

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Gets an item set component. The item ID of the item set and the component ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setId`
|link:http://php.net/int[int^]
a|The unique item ID of the item set

a|`$id`
|link:http://php.net/int[int^]
a|The unique ID of the item set component
|===


[source%nowrap, php]
[#create]
----

public create($setConfigId, $data):Plenty\Modules\ItemSet\Models\ItemSetComponent

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Creates an item set component.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setConfigId`
|link:http://php.net/int[int^]
a|The unique ID of the item set configuration

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#createcomponents]
----

public createComponents($setId, $data):Plenty\Modules\ItemSet\Models\ItemSetComponent

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Creates a link between an item and a set item and adds the item as a set component.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setId`
|link:http://php.net/int[int^]
a|The unique item ID of the item set

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#updatecomponents]
----

public updateComponents($setId, $data):Plenty\Modules\ItemSet\Models\ItemSetComponent

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Updates the item set components of a set item.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setId`
|link:http://php.net/int[int^]
a|The unique item ID of the item set

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($setId, $id, $data):Plenty\Modules\ItemSet\Models\ItemSetComponent

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Updates an item set component. The item ID of the set and the ID of the set component must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setId`
|link:http://php.net/int[int^]
a|The unique item ID of the item set

a|`$id`
|link:http://php.net/int[int^]
a|The unique ID of the item set component

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deletecomponents]
----

public deleteComponents($setId, $data):Plenty\Repositories\Models\DeleteResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Removes all item set components from an item set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setId`
|link:http://php.net/int[int^]
a|The unique item ID of the item set

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($setId, $id):Plenty\Repositories\Models\DeleteResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes the link between an item set component and an item set. The item ID of the set and the ID of the set component must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setId`
|link:http://php.net/int[int^]
a|The unique item ID of the item set

a|`$id`
|link:http://php.net/int[int^]
a|The unique ID of the item set component
|===


[source%nowrap, php]
[#all]
----

public all():array

----







Lists all item set components.

[source%nowrap, php]
[#findbysetid]
----

public findBySetId($setId, $with):array

----







Lists the item set components of a set. The item ID of the item set must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setId`
|link:http://php.net/int[int^]
a|The unique item ID of the item set

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#findbyitemid]
----

public findByItemId($itemId):array

----







Lists the item set components of a set. The item ID of the item set component must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|The unique item ID of the item set component
|===


[source%nowrap, php]
[#deleteone]
----

public deleteOne($setConfigId, $itemId):Plenty\Repositories\Models\DeleteResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Delete an item set component. The item ID of the item set component and the set config ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setConfigId`
|link:http://php.net/int[int^]
a|

a|`$itemId`
|link:http://php.net/int[int^]
a|
|===



[[itemset_contracts_itemsetconfigrepositorycontract]]
==== ItemSetConfigRepositoryContract

The contract for the item set configuration repository



===== Namespace

`Plenty\Modules\ItemSet\Contracts`






===== Methods

[source%nowrap, php]
[#show]
----

public show($id):Plenty\Modules\ItemSet\Models\ItemSetConfig

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetconfig[`ItemSetConfig`]


Gets an item set. The ID of the item set configuration must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The unique ID of the item set configuration
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\ItemSet\Models\ItemSetConfig

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetconfig[`ItemSetConfig`]


Creates an item set configuration.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\ItemSet\Models\ItemSetConfig

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetconfig[`ItemSetConfig`]


Updates an item set configuration. The ID of the item set configuration must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):Plenty\Repositories\Models\DeleteResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes an item set configuration. The ID of the item set configuration must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The unique ID of the item set configuration
|===


[source%nowrap, php]
[#get]
----

public get($setId, $setConfigId):Plenty\Modules\ItemSet\Models\ItemSetConfig

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetconfig[`ItemSetConfig`]


Gets the item set configuration of an item set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setId`
|link:http://php.net/int[int^]
a|The unique item ID of the item set

a|`$setConfigId`
|link:http://php.net/int[int^]
a|The unique ID of the item set configuration
|===


[source%nowrap, php]
[#findbysetid]
----

public findBySetId($setId):Plenty\Modules\ItemSet\Models\ItemSetConfig

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetconfig[`ItemSetConfig`]


Gets the item set configuration of an item set. The item ID of the set item must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setId`
|link:http://php.net/int[int^]
a|The unique item ID of the item set
|===


[source%nowrap, php]
[#calculatesetprice]
----

public calculateSetPrice($setId):void

----







Trigger a sales price calculation for an item set

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$setId`
|link:http://php.net/int[int^]
a|
|===



[[itemset_contracts_itemsetrepositorycontract]]
==== ItemSetRepositoryContract

The contract for the item set repository



===== Namespace

`Plenty\Modules\ItemSet\Contracts`






===== Methods

[source%nowrap, php]
[#show]
----

public show($id):Plenty\Modules\ItemSet\Models\ItemSet

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemset[`ItemSet`]


Gets an item set. The item ID of the set must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The unique item ID of the set
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\ItemSet\Models\ItemSet

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemset[`ItemSet`]


Creates an item set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#createsets]
----

public createSets($data):Plenty\Modules\ItemSet\Models\ItemSet

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemset[`ItemSet`]


Creates item sets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#updatesets]
----

public updateSets($data):array

----







Updates item sets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\ItemSet\Models\ItemSet

----




====== *Return type:*        xref:Itemset.adoc#itemset_models_itemset[`ItemSet`]


Updates an item set. The item ID of the set must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The unique item ID of the set.

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deletesets]
----

public deleteSets($data):Plenty\Repositories\Models\DeleteResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes item sets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):Plenty\Repositories\Models\DeleteResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes an item set configuration. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#all]
----

public all():array

----







Lists all item set configurations.

[[itemset_itemset_models]]
===  Models
[[itemset_models_itemset]]
==== ItemSet

The ItemSet model.



===== Namespace

`Plenty\Modules\ItemSet\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The item ID of the item set. The ID must be unique.
|name
    |link:http://php.net/string[string^]
    a|The name of the item set. The default language of the system is used.
|categories
    |link:http://php.net/array[array^]
    a|The array with categories of the item set. The category ID key  "categoryId" must be specified. Example for JSON Object:  "categories":[{"categoryId":"34"},{"categoryId":"35"}]}]
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[itemset_models_itemsetcomponent]]
==== ItemSetComponent

The ItemSetComponent model.



===== Namespace

`Plenty\Modules\ItemSet\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The item set component ID. The ID must be unique.
|setId
    |link:http://php.net/int[int^]
    a|The item ID of the item set. The ID must be unique.
|itemId
    |link:http://php.net/int[int^]
    a|The item ID of the set component
|minimalOrderQuantity
    |link:http://php.net/float[float^]
    a|Minimum order quantity.
|maximumOrderQuantity
    |link:http://php.net/float[float^]
    a|Maximum order quantity.
|orderQuantityPossible
    |link:http://php.net/bool[bool^]
    a|Order quantities possible.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[itemset_models_itemsetconfig]]
==== ItemSetConfig

The ItemSetConfig model.



===== Namespace

`Plenty\Modules\ItemSet\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|setId
    |link:http://php.net/int[int^]
    a|set id The item ID of the item set. The ID must be unique.
|rebate
    |link:http://php.net/float[float^]
    a|The discount in percent to be subtracted from the sum of the prices of the selected set components.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

