:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[itemset_itemset]]
= ItemSet

[[itemset_itemset_contracts]]
== Contracts
[[itemset_contracts_itemsetcomponentrepositorycontract]]
=== ItemSetComponentRepositoryContract

The contract for the item set component repository



==== Namespace

`Plenty\Modules\ItemSet\Contracts`






==== Methods

[source%nowrap, php]
----

public show($id, $with):Plenty\Modules\ItemSet\Models\ItemSetComponent

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Gets an item set component. The ID of the item set component must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
a|The unique ID of the item set component

|link:http://php.net/array[array^]
a|`$with`
a|
|===


[source%nowrap, php]
----

public get($setId, $id):Plenty\Modules\ItemSet\Models\ItemSetComponent

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Gets an item set component. The item ID of the item set and the component ID must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setId`
a|The unique item ID of the item set

|link:http://php.net/int[int^]
a|`$id`
a|The unique ID of the item set component
|===


[source%nowrap, php]
----

public create($setConfigId, $data):Plenty\Modules\ItemSet\Models\ItemSetComponent

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Creates an item set component.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setConfigId`
a|The unique ID of the item set configuration

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public createComponents($setId, $data):Plenty\Modules\ItemSet\Models\ItemSetComponent

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Creates a link between an item and a set item and adds the item as a set component.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setId`
a|The unique item ID of the item set

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public updateComponents($setId, $data):Plenty\Modules\ItemSet\Models\ItemSetComponent

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Updates the item set components of a set item.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setId`
a|The unique item ID of the item set

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public update($setId, $id, $data):Plenty\Modules\ItemSet\Models\ItemSetComponent

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetcomponent[`ItemSetComponent`]


Updates an item set component. The item ID of the set and the ID of the set component must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setId`
a|The unique item ID of the item set

|link:http://php.net/int[int^]
a|`$id`
a|The unique ID of the item set component

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public deleteComponents($setId, $data):Plenty\Repositories\Models\DeleteResponse

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Removes all item set components from an item set.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setId`
a|The unique item ID of the item set

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public delete($setId, $id):Plenty\Repositories\Models\DeleteResponse

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes the link between an item set component and an item set. The item ID of the set and the ID of the set component must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setId`
a|The unique item ID of the item set

|link:http://php.net/int[int^]
a|`$id`
a|The unique ID of the item set component
|===


[source%nowrap, php]
----

public all():array

----

    





Lists all item set components.

[source%nowrap, php]
----

public findBySetId($setId, $with):array

----

    





Lists the item set components of a set. The item ID of the item set must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setId`
a|The unique item ID of the item set

|link:http://php.net/array[array^]
a|`$with`
a|
|===


[source%nowrap, php]
----

public findByItemId($itemId):array

----

    





Lists the item set components of a set. The item ID of the item set component must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
a|The unique item ID of the item set component
|===


[source%nowrap, php]
----

public deleteOne($setConfigId, $itemId):Plenty\Repositories\Models\DeleteResponse

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Delete an item set component. The item ID of the item set component and the set config ID must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setConfigId`
a|

|link:http://php.net/int[int^]
a|`$itemId`
a|
|===



[[itemset_contracts_itemsetconfigrepositorycontract]]
=== ItemSetConfigRepositoryContract

The contract for the item set configuration repository



==== Namespace

`Plenty\Modules\ItemSet\Contracts`






==== Methods

[source%nowrap, php]
----

public show($id):Plenty\Modules\ItemSet\Models\ItemSetConfig

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetconfig[`ItemSetConfig`]


Gets an item set. The ID of the item set configuration must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
a|The unique ID of the item set configuration
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\ItemSet\Models\ItemSetConfig

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetconfig[`ItemSetConfig`]


Creates an item set configuration.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public update($id, $data):Plenty\Modules\ItemSet\Models\ItemSetConfig

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetconfig[`ItemSetConfig`]


Updates an item set configuration. The ID of the item set configuration must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
a|

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public delete($id):Plenty\Repositories\Models\DeleteResponse

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes an item set configuration. The ID of the item set configuration must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
a|The unique ID of the item set configuration
|===


[source%nowrap, php]
----

public get($setId, $setConfigId):Plenty\Modules\ItemSet\Models\ItemSetConfig

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetconfig[`ItemSetConfig`]


Gets the item set configuration of an item set.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setId`
a|The unique item ID of the item set

|link:http://php.net/int[int^]
a|`$setConfigId`
a|The unique ID of the item set configuration
|===


[source%nowrap, php]
----

public findBySetId($setId):Plenty\Modules\ItemSet\Models\ItemSetConfig

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemsetconfig[`ItemSetConfig`]


Gets the item set configuration of an item set. The item ID of the set item must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$setId`
a|The unique item ID of the item set
|===



[[itemset_contracts_itemsetrepositorycontract]]
=== ItemSetRepositoryContract

The contract for the item set repository



==== Namespace

`Plenty\Modules\ItemSet\Contracts`






==== Methods

[source%nowrap, php]
----

public show($id):Plenty\Modules\ItemSet\Models\ItemSet

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemset[`ItemSet`]


Gets an item set. The item ID of the set must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
a|The unique item ID of the set
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\ItemSet\Models\ItemSet

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemset[`ItemSet`]


Creates an item set.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public createSets($data):Plenty\Modules\ItemSet\Models\ItemSet

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemset[`ItemSet`]


Creates item sets.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public updateSets($data):array

----

    





Updates item sets.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public update($id, $data):Plenty\Modules\ItemSet\Models\ItemSet

----

    


===== *Return type:*        xref:Itemset.adoc#itemset_models_itemset[`ItemSet`]


Updates an item set. The item ID of the set must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
a|The unique item ID of the set.

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public deleteSets($data):Plenty\Repositories\Models\DeleteResponse

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes item sets.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public delete($id):Plenty\Repositories\Models\DeleteResponse

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes an item set configuration. The ID must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$id`
a|
|===


[source%nowrap, php]
----

public all():array

----

    





Lists all item set configurations.

[[itemset_itemset_models]]
== Models
[[itemset_models_itemset]]
=== ItemSet

The ItemSet model.



==== Namespace

`Plenty\Modules\ItemSet\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The item ID of the item set. The ID must be unique.
|link:http://php.net/string[string^]
    a|name
    a|The name of the item set. The default language of the system is used.
|link:http://php.net/array[array^]
    a|categories
    a|The array with categories of the item set. The category ID key  "categoryId" must be specified. Example for JSON Object:  "categories":[{"categoryId":"34"},{"categoryId":"35"}]}]
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[itemset_models_itemsetcomponent]]
=== ItemSetComponent

The ItemSetComponent model.



==== Namespace

`Plenty\Modules\ItemSet\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The item set component ID. The ID must be unique.
|link:http://php.net/int[int^]
    a|setId
    a|The item ID of the item set. The ID must be unique.
|link:http://php.net/int[int^]
    a|itemId
    a|The item ID of the set component
|link:http://php.net/float[float^]
    a|minimalOrderQuantity
    a|Minimum order quantity.
|link:http://php.net/float[float^]
    a|maximumOrderQuantity
    a|Maximum order quantity.
|link:http://php.net/bool[bool^]
    a|orderQuantityPossible
    a|Order quantities possible.
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[itemset_models_itemsetconfig]]
=== ItemSetConfig

The ItemSetConfig model.



==== Namespace

`Plenty\Modules\ItemSet\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|setId
    a|set id The item ID of the item set. The ID must be unique.
|link:http://php.net/float[float^]
    a|rebate
    a|The discount in percent to be subtracted from the sum of the prices of the selected set components.
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

