:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[listing_listing]]
== Listing

[[listing_listing_contracts]]
===  Contracts
[[listing_contracts_listingrepositorycontract]]
==== ListingRepositoryContract

The contract for the listing repository.



===== Namespace

`Plenty\Modules\Listing\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Listing\Models\Listing

----




====== *Return type:*        xref:Listing.adoc#listing_models_listing[`Listing`]


Get a listing by a given ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the listing instance, one of "markets", "type", "stockDependenceType", "properties".
|===


[source%nowrap, php]
[#search]
----

public search($page = 1, $itemsPerPage = 50, $with = [], $filters = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List listing

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarket instance. The relations available are 'type', 'stockDependenceType' and 'markets'.

a|`$filters`
|link:http://php.net/array[array^]
a|The filters that could be applied: 'id', 'itemId', 'typeId', 'stockDependenceTypeId', 'unitCombinationId'
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Listing\Models\Listing

----




====== *Return type:*        xref:Listing.adoc#listing_models_listing[`Listing`]


Create new listing

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The listing data as associative array.
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Listing\Models\Listing

----




====== *Return type:*        xref:Listing.adoc#listing_models_listing[`Listing`]


Update listing

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing.

a|`$data`
|link:http://php.net/array[array^]
a|The listing data as associative array.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Delete listing

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing.
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[listing_listing_models]]
===  Models
[[listing_models_listing]]
==== Listing

The listing model.



===== Namespace

`Plenty\Modules\Listing\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing.
|itemId
    |link:http://php.net/int[int^]
    a|The ID of the item.
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing type. Possible types are:
<ul>
    <li>1 = Auction</li>
    <li>2 = Fixed</li>
    <li>3 = Shop item</li>
</ul>
|stockDependenceTypeId
    |link:http://php.net/int[int^]
    a|The ID of the listing stock dependence. Possible stock dependence types are:
<ul>
    <li>1 = Unlimited with sync</li>
    <li>2 = Limited with reservation</li>
    <li>3 = Limited without reservation</li>
    <li>4 = Unlimited without sync</li>
</ul>
|unitCombinationId
    |link:http://php.net/int[int^]
    a|The ID of the unit combination.
|properties
    |
    a|The listing properties of the listing.
|type
    |        xref:Listing.adoc#listing_models_listingtype[`ListingType`]
    a|The type of the listing.
|stockDependenceType
    |        xref:Listing.adoc#listing_models_stockdependencetype[`StockDependenceType`]
    a|The stock dependence type of the listing.
|markets
    |        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
    a|The listing markets of the listing
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingproperty]]
==== ListingProperty

The listing properties model. Each listing property has a type.



===== Namespace

`Plenty\Modules\Listing\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing property.
|listingId
    |link:http://php.net/int[int^]
    a|The ID of the listing that the property belongs to.
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing property type. The following types are available:
<ul>
<li>10 = Use item price</li>
<li>11 = Number per lot</li>
<li>12 = Transmit item number type</li>
</ul>
|value
    |
    a|The value of the listing property. The value depends on the type.
|createdAt
    |
    a|The date that the property was created.
|updatedAt
    |
    a|The date that the property was last updated.
|listing
    |        xref:Listing.adoc#listing_models_listing[`Listing`]
    a|The listing that the property belongs to.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_date]]
== Date

[[listing_date_models]]
===  Models
[[listing_models_listingdatetype]]
==== ListingDateType

The listing date type model. Each listing date type can have multiple names.



===== Namespace

`Plenty\Modules\Listing\Date\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing date type. The following date types are available:
<ul>
<li>1 = Last price update</li>
<li>2 = Last listing attempt</li>
<li>3 = Start time</li>
<li>4 = End time</li>
<li>5 = Last market update</li>
<li>6 = Last sale</li>
</ul>
|isErasable
    |link:http://php.net/bool[bool^]
    a|Flag that indicates if this type can be deleted or not.
|names
    |link:http://php.net/array[array^]
    a|The listing date type names.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingdatetypename]]
==== ListingDateTypeName

The listing date type name model.



===== Namespace

`Plenty\Modules\Listing\Date\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing date type name.
|typeId
    |link:http://php.net/int[int^]
    a|The listing date type ID that the current name belongs to.
|name
    |link:http://php.net/int[int^]
    a|The name of the listing date type.
|lang
    |link:http://php.net/int[int^]
    a|The language of the listing date type name.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_layouttemplate]]
== LayoutTemplate

[[listing_layouttemplate_contracts]]
===  Contracts
[[listing_contracts_layouttemplaterepositorycontract]]
==== LayoutTemplateRepositoryContract

The LayoutTemplateRepositoryContract is the interface for the layout template repository. This interface allows you to get a single layout template or lists of layout templates as well as to create, update or delete a layout tempalte.



===== Namespace

`Plenty\Modules\Listing\LayoutTemplate\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Listing\LayoutTemplate\Models\LayoutTemplate

----




====== *Return type:*        xref:Listing.adoc#listing_models_layouttemplate[`LayoutTemplate`]


Get a layout template.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the layout template.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the LayoutTemplate instance, one of "additional".
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Listing\LayoutTemplate\Models\LayoutTemplate

----




====== *Return type:*        xref:Listing.adoc#listing_models_layouttemplate[`LayoutTemplate`]


Create a layout template.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The layout template data.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Delete layout template

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the layout template.
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[listing_layouttemplate_models]]
===  Models
[[listing_models_layouttemplate]]
==== LayoutTemplate

The layout template model.



===== Namespace

`Plenty\Modules\Listing\LayoutTemplate\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the layout template.
|name
    |link:http://php.net/string[string^]
    a|The name of the layout template.
|css
    |link:http://php.net/string[string^]
    a|The css of the layout template.
|htmlStructure
    |link:http://php.net/string[string^]
    a|The html structure of the layout template.
|mainFrame
    |link:http://php.net/string[string^]
    a|The main frame of the layout template.
|additionalContent
    |link:http://php.net/array[array^]
    a|The additional content of the layout template.
|appendixType
    |link:http://php.net/string[string^]
    a|The appendix type of the layout template.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_market]]
== Market

[[listing_market_contracts]]
===  Contracts
[[listing_contracts_listingmarketrepositorycontract]]
==== ListingMarketRepositoryContract

The ListingMarketRepositoryContract is the interface for the listing market repository. This interface allows you to get a single listing market or lists of listing markets as well as to create a listing market.



===== Namespace

`Plenty\Modules\Listing\Market\Contracts`


[NOTE, caption=]
.Repository can be extended!
====
It is possible to extend this repository with own search criteria.
====




===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Listing\Market\Models\ListingMarket

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]


Get a listing market

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing market.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarket instance, one of "listing", "prices", "dates", "properties", "texts", "infos".
|===


[source%nowrap, php]
[#search]
----

public search($page = 1, $itemsPerPage = 50, $with = [], $filters = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List listing markets

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarket instance, one of "listing", "prices", "dates", "properties", "texts", "infos".

a|`$filters`
|link:http://php.net/array[array^]
a|The filters that should be applied. The filters that could be applied: 'id', 'variationId', 'allVariations', 'referrerId', 'credentialsId', 'directoryId', 'verified', 'duration', 'listingId', 'itemId', 'listingTypeId', 'stockDependenceTypeId', 'status', 'stockCondition', 'shippingProfileId', .
|===


[source%nowrap, php]
[#find]
----

public find($page = 1, $itemsPerPage = 50, $with = [], $filters = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Find listing markets

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarket instance, one of "listing", "prices", "dates", "properties", "texts", "infos".

a|`$filters`
|link:http://php.net/array[array^]
a|The filters that should be applied. The filters that could be applied: 'id', 'variationId', 'allVariations', 'referrerId', 'credentialsId', 'directoryId', 'verified', 'duration', 'listingId', 'itemId', 'listingTypeId', 'stockDependenceTypeId', 'status', 'stockCondition', 'shippingProfileId', .
|===


[source%nowrap, php]
[#create]
----

public create($data):array

----







Create a listing

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The listing market data.
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Listing\Market\Models\ListingMarket

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]


Update listing market

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing market.

a|`$data`
|link:http://php.net/array[array^]
a|The listing market data as associative array.
|===


[source%nowrap, php]
[#start]
----

public start($ids, $params = []):array

----







Start listing markets on the designated markets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ids`
|link:http://php.net/array[array^]
a|The IDs of the listing markets that need to be started.

a|`$params`
|link:http://php.net/array[array^]
a|The parameters that should be considered during start. Available values are 'startTime', 'startDistribution'
|===


[source%nowrap, php]
[#verify]
----

public verify($ids):array

----







Verifies listing markets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ids`
|link:http://php.net/array[array^]
a|The IDs of the listing markets that need to be verified.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):void

----







Delete a listing market

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing market.
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[listing_market_events]]
===  Events
[[listing_events_listingmarketbatchcreated]]
==== ListingMarketBatchCreated

An event class fired after multiple new listing markets are created.



===== Namespace

`Plenty\Modules\Listing\Market\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($listingMarkets):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarkets`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getlistingmarkets]
----

public getListingMarkets():array

----







Get the list of ListingMarket instances.


[[listing_events_listingmarketbatchdeleted]]
==== ListingMarketBatchDeleted

An event class fired after multiple listing markets are deleted.



===== Namespace

`Plenty\Modules\Listing\Market\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($listingMarkets):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarkets`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getlistingmarkets]
----

public getListingMarkets():array

----







Get the list of ListingMarket instances.


[[listing_events_listingmarketbatchevent]]
==== ListingMarketBatchEvent

A base event class for all listing market events. Each listing market batch event expects an array of ListingMarket instances.



===== Namespace

`Plenty\Modules\Listing\Market\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($listingMarkets):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarkets`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getlistingmarkets]
----

public getListingMarkets():array

----







Get the list of ListingMarket instances.


[[listing_events_listingmarketbatchupdated]]
==== ListingMarketBatchUpdated

An event class fired after multiple listing markets are updated.



===== Namespace

`Plenty\Modules\Listing\Market\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($listingMarkets):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarkets`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getlistingmarkets]
----

public getListingMarkets():array

----







Get the list of ListingMarket instances.


[[listing_events_listingmarketcreated]]
==== ListingMarketCreated

An event class fired after a new listing market is created.



===== Namespace

`Plenty\Modules\Listing\Market\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($listingMarket):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarket`
|        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
a|
|===


[source%nowrap, php]
[#getlistingmarket]
----

public getListingMarket():Plenty\Modules\Listing\Market\Models\ListingMarket

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]


Get the ListingMarket instance.


[[listing_events_listingmarketdeleted]]
==== ListingMarketDeleted

An event class fired after a new listing market is deleted.



===== Namespace

`Plenty\Modules\Listing\Market\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($listingMarket):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarket`
|        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
a|
|===


[source%nowrap, php]
[#getlistingmarket]
----

public getListingMarket():Plenty\Modules\Listing\Market\Models\ListingMarket

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]


Get the ListingMarket instance.


[[listing_events_listingmarketevent]]
==== ListingMarketEvent

A base event class for all listing market events. Each listing market event expects an ListingMarket instance.



===== Namespace

`Plenty\Modules\Listing\Market\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($listingMarket):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarket`
|        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
a|
|===


[source%nowrap, php]
[#getlistingmarket]
----

public getListingMarket():Plenty\Modules\Listing\Market\Models\ListingMarket

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]


Get the ListingMarket instance.


[[listing_events_listingmarketitemspecificscreated]]
==== ListingMarketItemSpecificsCreated

An event class fired after a new listing market item specifics are created.



===== Namespace

`Plenty\Modules\Listing\Market\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($listingMarket):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarket`
|        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
a|
|===


[source%nowrap, php]
[#getlistingmarket]
----

public getListingMarket():Plenty\Modules\Listing\Market\Models\ListingMarket

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]


Get the ListingMarket instance.


[[listing_events_listingmarketitemspecificsdeleted]]
==== ListingMarketItemSpecificsDeleted

An event class fired after a new listing market item specifics are deleted.



===== Namespace

`Plenty\Modules\Listing\Market\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($listingMarket):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarket`
|        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
a|
|===


[source%nowrap, php]
[#getlistingmarket]
----

public getListingMarket():Plenty\Modules\Listing\Market\Models\ListingMarket

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]


Get the ListingMarket instance.


[[listing_events_listingmarketupdated]]
==== ListingMarketUpdated

An event class fired after a new listing market is updated.



===== Namespace

`Plenty\Modules\Listing\Market\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($listingMarket):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarket`
|        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
a|
|===


[source%nowrap, php]
[#getlistingmarket]
----

public getListingMarket():Plenty\Modules\Listing\Market\Models\ListingMarket

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]


Get the ListingMarket instance.

[[listing_market_models]]
===  Models
[[listing_models_listingmarket]]
==== ListingMarket

The listing market model.



===== Namespace

`Plenty\Modules\Listing\Market\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing market.
|listingId
    |link:http://php.net/int[int^]
    a|The listing ID of the current listing market.
|variationId
    |link:http://php.net/int[int^]
    a|The variation ID for this listing market.
|referrerId
    |link:http://php.net/int[int^]
    a|The ID of the referrer.
|credentialsId
    |link:http://php.net/int[int^]
    a|The credentials ID that this listing market belongs to.
|directoryId
    |link:http://php.net/int[int^]
    a|The directory ID of the listing market.
|enabled
    |link:http://php.net/bool[bool^]
    a|Indicates if the listing market is enabled.
|duration
    |link:http://php.net/string[string^]
    a|The duration of the listing market.
|verified
    |link:http://php.net/string[string^]
    a|Indicates if the listing market has been verified. Possible values are: 'succeeded', 'failed', 'unknown'.
|quantity
    |link:http://php.net/int[int^]
    a|The quantity set for this listing market.
|allVariations
    |link:http://php.net/bool[bool^]
    a|Indicates if all variations should be included.
|createdAt
    |
    a|The date that the listing was created.
|updatedAt
    |
    a|The date that the listing was last updated.
|listing
    |        xref:Listing.adoc#listing_models_listing[`Listing`]
    a|The listing that the listing market belongs to.
|properties
    |
    a|The listing market properties of the listing market. The following properties are available:
<ul>
<li>1 = Shipping profile ID</li>
<li>2 = Order status</li>
<li>3 = Layout template ID</li>
<li>4 = Maximum number of images</li>
<li>5 = Warehouse ID</li>
<li>6 = Basic price in text</li>
<li>7 = Vat value</li>
<li>8 = Vat country ID</li>
<li>9 = Main language</li>
<li>10 = Use item price</li>
<li>11 = Number per lot</li>
<li>12 = Transmit item number type</li>
<li>13 = Relisted external ID</li>
<li>14 = SCO offer</li>
<li>15 = Promotion</li>
<li>16 = UUID</li>
<li>17 = Update error</li>
<li>18 = Has variations</li>
<li>19 = End now</li>
<li>20 = Insert by type</li>
<li>21 = Payment methods</li>
<li>22 = First platform category ID</li>
<li>23 = Second platform category ID</li>
<li>24 = First shop category ID</li>
<li>25 = Second shop category ID</li>
<li>26 = Third shop category ID</li>
<li>27 = Enhancements</li>
<li>100 = eBay parts fitment ID</li>
<li>101 = eBay maximum online listings</li>
<li>102 = eBay private auction</li>
<li>103 = eBay gallery type</li>
<li>104 = eBay gallery duration</li>
<li>105 = eBay transmit MPR</li>
<li>106 = eBay counter type</li>
<li>107 = eBay condition ID</li>
<li>108 = eBay condition description</li>
<li>109 = eBay best offer</li>
<li>110 = eBay best offer decline price</li>
<li>111 = eBay best offer accept price</li>
<li>112 = eBay is eBay Plus</li>
<li>113 = eBay is click & Collect</li>
<li>114 = eBay use EPS</li>
<li>200 = Hood show on shop startpage</li>
<li>201 = Hood shipping discount</li>
<li>202 = Hood delivery days on stock from</li>
<li>203 = Hood delivery days on stock to</li>
<li>204 = Hood delivery days not on stock from</li>
<li>205 = Hood delivery days not on stock to</li>
<li>300 = Ricardo warranty ID</li>
<li>301 = Ricardo delivery ID</li>
<li>302 = Ricardo availability ID</li>
<li>303 = Ricardo delivery cost</li>
<li>304 = Ricardo payment ID</li>
<li>305 = Ricardo price increment</li>
<li>306 = Ricardo item condition ID</li>
<li>307 = Ricardo max relist count</li>
<li>308 = Ricardo is cumulative shipping</li>
<li>309 = Ricardo delivery package size ID</li>
<li>310 = Ricardo use secondary language</li>
<li>311 = Ricardo template ID</li>
<li>312 = Ricardo is relist sold out</li>
</ul>
|itemSpecifics
    |
    a|The listing market item specifics of the listing market.
|prices
    |
    a|The listing market prices of the listing market.
|dates
    |
    a|The listing market dates of the listing market.
|texts
    |
    a|The listing market texts of the listing market.
|infos
    |
    a|The listing market infos of the listing market.
|lister
    |
    a|The listing market lister of the listing market.
|histories
    |
    a|The listing market histories of the listing market.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingmarketdate]]
==== ListingMarketDate

The listing market dates model. Each listing market date has a type.



===== Namespace

`Plenty\Modules\Listing\Market\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing market date.
|listingMarketId
    |link:http://php.net/int[int^]
    a|The ID of the listing market that the date belongs to.
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing market date type. The following types are available:
<ul>
<li>1 = Last price update</li>
<li>2 = Last listing attempt</li>
<li>3 = Start time</li>
<li>4 = End time</li>
<li>5 = Last market update</li>
</ul>
|date
    |        xref:Miscellaneous.adoc#miscellaneous_carbon_carbon[`Carbon`]
    a|The date plus hours, minutes and seconds. The date format must comply with the W3C standard.
|createdAt
    |
    a|The date that the date was created.
|updatedAt
    |
    a|The date that the date was last updated.
|listingMarket
    |        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
    a|The listing market that the date belongs to.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingmarketitemspecific]]
==== ListingMarketItemSpecific

The listing market item specific model.



===== Namespace

`Plenty\Modules\Listing\Market\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing market item specific.
|listingMarketId
    |link:http://php.net/int[int^]
    a|The ID of the listing market.
|name
    |link:http://php.net/string[string^]
    a|The name of the listing market item specific.
|value
    |
    a|The value of the listing market item specific.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingmarketprice]]
==== ListingMarketPrice

The listing market price model.



===== Namespace

`Plenty\Modules\Listing\Market\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing price.
|listingMarketId
    |link:http://php.net/int[int^]
    a|The ID of the listing market.
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing price type.
|value
    |link:http://php.net/float[float^]
    a|The value of the listing market price.
|currency
    |link:http://php.net/string[string^]
    a|The currency of the listing market price.
|listingMarket
    |
    a|The listing market.
|type
    |
    a|The listing price type.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingmarketproperty]]
==== ListingMarketProperty

The listing market properties model. Each listing market property has a type.



===== Namespace

`Plenty\Modules\Listing\Market\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing market property.
|listingMarketId
    |link:http://php.net/int[int^]
    a|The ID of the listing market that the property belongs to.
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing market property type. The following types are available:
<ul>
<li>1 = Shipping profile ID</li>
<li>2 = Order status</li>
<li>3 = Layout template ID</li>
<li>4 = Maximum number of images</li>
<li>5 = Warehouse ID</li>
<li>6 = Basic price in text</li>
<li>7 = Vat value</li>
<li>8 = Vat country ID</li>
<li>9 = Main language</li>
<li>10 = Use item price</li>
<li>11 = Number per lot</li>
<li>12 = Transmit item number type</li>
<li>13 = Relisted external ID</li>
<li>14 = SCO offer</li>
<li>15 = Promotion</li>
<li>16 = UUID</li>
<li>17 = Update error</li>
<li>18 = Has variations</li>
<li>19 = End now</li>
<li>20 = Insert by type</li>
<li>21 = Payment methods</li>
<li>22 = First platform category ID</li>
<li>23 = Second platform category ID</li>
<li>24 = First shop category ID</li>
<li>25 = Second shop category ID</li>
<li>26 = Third shop category ID</li>
<li>27 = Enhancements</li>
<li>100 = eBay parts fitment ID</li>
<li>101 = eBay maximum online listings</li>
<li>102 = eBay private auction</li>
<li>103 = eBay gallery type</li>
<li>104 = eBay gallery duration</li>
<li>105 = eBay transmit MPR</li>
<li>106 = eBay counter type</li>
<li>107 = eBay condition ID</li>
<li>108 = eBay condition description</li>
<li>109 = eBay best offer</li>
<li>110 = eBay best offer decline price</li>
<li>111 = eBay best offer accept price</li>
<li>112 = eBay is eBay Plus</li>
<li>113 = eBay is click & Collect</li>
<li>114 = eBay use EPS</li>
<li>200 = Hood show on shop startpage</li>
<li>201 = Hood shipping discount</li>
<li>202 = Hood delivery days on stock from</li>
<li>203 = Hood delivery days on stock to</li>
<li>204 = Hood delivery days not on stock from</li>
<li>205 = Hood delivery days not on stock to</li>
<li>300 = Ricardo warranty ID</li>
<li>301 = Ricardo delivery ID</li>
<li>302 = Ricardo availability ID</li>
<li>303 = Ricardo delivery cost</li>
<li>304 = Ricardo payment ID</li>
<li>305 = Ricardo price increment</li>
<li>306 = Ricardo item condition ID</li>
<li>307 = Ricardo max relist count</li>
<li>308 = Ricardo is cumulative shipping</li>
<li>309 = Ricardo delivery package size ID</li>
<li>310 = Ricardo use secondary language</li>
<li>311 = Ricardo template ID</li>
<li>312 = Ricardo is relist sold out</li>
</ul>
|value
    |link:http://php.net/string[string^]
    a|The value of the listing market property. The value depends on the type.
|createdAt
    |
    a|The date that the property was created.
|updatedAt
    |
    a|The date that the property was updated last.
|listingMarket
    |        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
    a|The listing market that the property belongs to.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_directory]]
== Directory

[[listing_directory_contracts]]
===  Contracts
[[listing_contracts_listingmarketdirectoryrepositorycontract]]
==== ListingMarketDirectoryRepositoryContract

The contract for the listing market directory repository.



===== Namespace

`Plenty\Modules\Listing\Market\Directory\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Listing\Market\Directory\Models\ListingMarketDirectory

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarketdirectory[`ListingMarketDirectory`]


Get a listing market directory

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing market directory.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarketDirectory instance, one of "children".
|===


[source%nowrap, php]
[#all]
----

public all($with = [], $filters = []):array

----







List all directories

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarketDirectory instances, one of "children".

a|`$filters`
|link:http://php.net/array[array^]
a|Listing market directory filters. Available filters: parentId (if no parentId is given than top level is returned).
|===


[source%nowrap, php]
[#create]
----

public create($data):array

----







Create a listing market directory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The listing market directory data as associative array.
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Listing\Market\Directory\Models\ListingMarketDirectory

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarketdirectory[`ListingMarketDirectory`]


Update listing market directory

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing market directory.

a|`$data`
|link:http://php.net/array[array^]
a|The listing market directory data as associative array.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):void

----







Delete a listing market directory

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing market directory.
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[listing_directory_models]]
===  Models
[[listing_models_listingmarketdirectory]]
==== ListingMarketDirectory

The listing market directory model.



===== Namespace

`Plenty\Modules\Listing\Market\Directory\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing market directory.
|name
    |link:http://php.net/string[string^]
    a|The name of the listing market directory.
|parentId
    |link:http://php.net/int[int^]
    a|The parent ID of the listing market directory.
|level
    |link:http://php.net/int[int^]
    a|The level of the directory.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_history]]
== History

[[listing_history_contracts]]
===  Contracts
[[listing_contracts_listingmarkethistoryrepositorycontract]]
==== ListingMarketHistoryRepositoryContract

The ListingMarketHistoryRepositoryContract is the interface for the listing market history repository. This interface allows you to get a single listing market history or to list several listing market histories.



===== Namespace

`Plenty\Modules\Listing\Market\History\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Listing\Market\History\Models\ListingMarketHistory

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarkethistory[`ListingMarketHistory`]


Get a listing market.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing market.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarket instance, one of "listing", "prices", "dates", "properties", "texts".
|===


[source%nowrap, php]
[#search]
----

public search($page = 1, $itemsPerPage = 50, $with = [], $filters = [], $sort = &quot;&quot;):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List listing market histories

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarketHistory instance, one of "listingMarket", "dates", "properties", "texts".

a|`$filters`
|link:http://php.net/array[array^]
a|The filters that should be applied. The filters that are available: 'listingMarketId', 'variationId', 'allVariations', 'referrerId', 'credentialsId', 'verified', 'duration', 'listingId', 'itemId', 'listingTypeId', 'stockDependenceTypeId', 'status', 'stockCondition', 'updatedAtFrom', 'updatedAtTo , 'textData', 'firstPlatformCategoryId', 'secondPlatformCategoryId', 'firstShopCategoryId', 'secondShopCategoryId', 'thirdShopCategoryId', 'shippingProfileId', 'lastSale', 'isEbayPlus', 'isClickAndCollect'.

a|`$sort`
|link:http://php.net/string[string^]
a|The sorting key that can be applied. These sortings are available: 'endTimeAsc', 'endTimeDesc', 'startTimeAsc', 'startTimeDesc', 'externalListingIdAsc', 'externalListingIdDesc'
|===


[source%nowrap, php]
[#end]
----

public end($ids, $params = []):array

----







End the listing market histories on the designated markets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ids`
|link:http://php.net/array[array^]
a|The IDs of the listing market histories that need to be started.

a|`$params`
|link:http://php.net/array[array^]
a|The parameters that should be considers during end. Available values are 'deleteOnSuccess'
|===


[source%nowrap, php]
[#relist]
----

public relist($ids):void

----







Relist the listing market histories on the designated markets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ids`
|link:http://php.net/array[array^]
a|The IDs of the listing market histories that need to be started.
|===


[source%nowrap, php]
[#update]
----

public update($ids, $options = []):array

----







Update the listing market histories on the designated markets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ids`
|link:http://php.net/array[array^]
a|The IDs of the listing market histories that need to be updated.

a|`$options`
|link:http://php.net/array[array^]
a|The update options that should be considers during update. Available values are:
<ul>
<li>title - Updates the title
<li>subtitle - Updates the subtitle</li></li>
<li>itemSpecifics - Updates the item specifics</li>
<li>category - Updates the platform and shop category</li>
<li>productListingDetails - Updates the product data for the listing</li>
<li>listingEnhancements - Updates the enhancements information</li>
<li>duration - Updates the duration</li>
<li>shipping - Updates the shipping information</li>
<li>description - Updates the description</li>
<li>pictures - Updates the entry pictures</li>
<li>quantityPriceAndVariations - Updates the quantity and price (also for variations)</li>
<li>resetVariations - Reset the variations. The variation from the item are transmitted again</li>
<li>partsFitment - Updates the parts fitment information (only available for eBay)</li>
<li>loyaltyProgram - Updates the listing loyalty program information (only available for eBay Plus) </li>
<li>resetRrp - Reset the recommended retail price information</li>
<li>payment - Updates payment information (only available for Hood)</li>
</ul>
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[listing_history_models]]
===  Models
[[listing_models_listingmarkethistory]]
==== ListingMarketHistory

The listing market history model.



===== Namespace

`Plenty\Modules\Listing\Market\History\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The listing market history ID.
|listingMarketId
    |link:http://php.net/int[int^]
    a|The listing market ID of the current listing market history.
|referrerId
    |link:http://php.net/int[int^]
    a|The referrer ID.
|externalId
    |link:http://php.net/string[string^]
    a|The external ID of the listing market history.
|statusId
    |link:http://php.net/int[int^]
    a|The status ID of the current listing market history. The following properties are available:
<ul>
<li>1 = Active</li>
<li>2 = Ended</li>
<li>3 = Relisted</li>
<li>4 = Hidden</li>
</ul>
|quantity
    |link:http://php.net/int[int^]
    a|The quantity available for sale on the marketplace.
|quantitySold
    |link:http://php.net/int[int^]
    a|The quantity sold currently on the marketplace.
|quantitySoldDelta
    |link:http://php.net/int[int^]
    a|The difference between the sold quantity and orders imported for this listing market history.
|quantityRemain
    |link:http://php.net/int[int^]
    a|The quantity remaining on the marketplace.
|price
    |link:http://php.net/float[float^]
    a|The price offered for this listing market. @see ListingMarketHistoryVariation if the listing market history contains variations.
|currency
    |link:http://php.net/string[string^]
    a|The currency for the price of this listing market.
|sku
    |link:http://php.net/string[string^]
    a|The stock keeping unit of this listing market history.
|createdAt
    |
    a|The date that the entry was created.
|updatedAt
    |
    a|The date that the entry was updated last.
|listingMarket
    |        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
    a|The listing market that the listing market history belongs to.
|variations
    |
    a|The listing market history variations that belong to this listing market history.
|properties
    |
    a|The listing market history properties of the listing market.
|dates
    |
    a|The listing market history dates of the listing market history.
|texts
    |
    a|The listing market history texts of the listing market history.
|status
    |
    a|The listing market history status of the listing market history.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingmarkethistorydate]]
==== ListingMarketHistoryDate

The listing market history dates model. Each listing market history date has a type.



===== Namespace

`Plenty\Modules\Listing\Market\History\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing market history date.
|historyId
    |link:http://php.net/int[int^]
    a|The ID of the listing market history that the date belongs to.
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing date type. The following types are available:
<ul>
<li>Last price update = 1</li>
<li>Last listing attempt = 2</li>
<li>Start time = 3</li>
<li>End time = 4</li>
<li>Last market update = 5</li>
<li>Last sale = 6</li>
</ul>
|date
    |        xref:Miscellaneous.adoc#miscellaneous_carbon_carbon[`Carbon`]
    a|The date plus hours, minutes and seconds. The date format must comply with the W3C standard.
|createdAt
    |
    a|The date that the date was created.
|updatedAt
    |
    a|The date that the date was last updated.
|listingMarket
    |        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
    a|The listing market that the date belongs to.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingmarkethistoryproperty]]
==== ListingMarketHistoryProperty

The listing market properties model. Each listing market property has a type.



===== Namespace

`Plenty\Modules\Listing\Market\History\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing market history property
|historyId
    |link:http://php.net/int[int^]
    a|The ID of the listing market history that the property belongs to
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing market history property type. The following types are available:
<ul>
<li>Relisted external ID = 13</li>
<li>SCO Offer = 14</li>
<li>Promotion = 15</li>
<li>Unique user ID = 16</li>
<li>Update error = 17</li>
<li>Has variations = 18</li>
<li>End now = 19</li>
<li>Insert by type = 20</li>
<li>Is eBayPlus = 117</li>
<li>Is click & collect = 118</li>
</ul>
|value
    |link:http://php.net/string[string^]
    a|The value of the listing market history property. The value depends on the type.
|createdAt
    |
    a|The date that the property was created.
|updatedAt
    |
    a|The date that the property was updated last.
|history
    |        xref:Listing.adoc#listing_models_listingmarkethistory[`ListingMarketHistory`]
    a|The listing market history that the property belongs to.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingmarkethistorytext]]
==== ListingMarketHistoryText

The listing market history text model.



===== Namespace

`Plenty\Modules\Listing\Market\History\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing market history text.
|historyId
    |link:http://php.net/int[int^]
    a|The ID of the listing market history the text belongs to.
|lang
    |link:http://php.net/string[string^]
    a|The language of the listing market text. Available values: 'de', 'en', 'fr', 'it', 'es', 'tr', 'nl', 'pl', 'nn', 'da', 'se', 'cz', 'ru', 'sk', 'cn', 'vn', 'pt', 'bg', 'ro'.
|title
    |link:http://php.net/string[string^]
    a|The title of the listing market text.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingmarkethistoryvariation]]
==== ListingMarketHistoryVariation

The listing market history model.



===== Namespace

`Plenty\Modules\Listing\Market\History\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The listing market history variation ID.
|historyId
    |link:http://php.net/int[int^]
    a|The listing market history ID of the current listing market history variation.
|variationId
    |link:http://php.net/int[int^]
    a|The variation ID.
|attributeName
    |link:http://php.net/string[string^]
    a|The attribute name. This is an serialized array of the attribute-value data.
|sku
    |link:http://php.net/string[string^]
    a|The stock keeping unit of this listing market history variation.
|quantity
    |link:http://php.net/int[int^]
    a|The quantity available for sale on the marketplace.
|quantitySold
    |link:http://php.net/int[int^]
    a|The quantity sold currently on the marketplace.
|quantitySoldDelta
    |link:http://php.net/int[int^]
    a|The difference between the sold quantity and orders imported for this listing market history variation.
|quantityRemain
    |link:http://php.net/int[int^]
    a|The quantity remaining on the marketplace.
|price
    |link:http://php.net/float[float^]
    a|The price offered for this listing market history variation.
|createdAt
    |
    a|The date that the entry was created.
|updatedAt
    |
    a|The date that the entry was updated last.
|history
    |        xref:Listing.adoc#listing_models_listingmarkethistory[`ListingMarketHistory`]
    a|The listing market history variations that belong to this listing market history.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_info]]
== Info

[[listing_info_contracts]]
===  Contracts
[[listing_contracts_listingmarketinforepositorycontract]]
==== ListingMarketInfoRepositoryContract

The ListingMarketInfoRepositoryContract is the interface for the listing market info repository. This interface allows you to get information about one or many listing markets.



===== Namespace

`Plenty\Modules\Listing\Market\Info\Contracts`






===== Methods

[source%nowrap, php]
[#search]
----

public search($page = 1, $itemsPerPage = 50, $with = [], $filters = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List listing market infos by filter options

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarketInfo instance.

a|`$filters`
|link:http://php.net/array[array^]
a|The filters that should be applied. The filters that could be applied: 'id', 'listingMarketId', 'type', 'createdAtFrom', 'createdAtTo', 'code'.
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[listing_info_models]]
===  Models
[[listing_models_listingmarketinfo]]
==== ListingMarketInfo

The listing market info model.



===== Namespace

`Plenty\Modules\Listing\Market\Info\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The listing market info ID.
|listingMarketId
    |link:http://php.net/int[int^]
    a|The listing market ID that the current information belongs to.
|type
    |link:http://php.net/string[string^]
    a|The information type. Possible values: 'warning', 'error', 'info'.
|code
    |link:http://php.net/int[int^]
    a|The information code.
|message
    |link:http://php.net/string[string^]
    a|The information message.
|createdAt
    |
    a|The date that the listing market info was created.
|listingMarket
    |        xref:Listing.adoc#listing_models_listingmarket[`ListingMarket`]
    a|The listing market that the listing market info belongs to.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_itemspecific]]
== ItemSpecific

[[listing_itemspecific_contracts]]
===  Contracts
[[listing_contracts_listingmarketitemspecificrepositorycontract]]
==== ListingMarketItemSpecificRepositoryContract

The contract of the listing market item specific repository



===== Namespace

`Plenty\Modules\Listing\Market\ItemSpecific\Contracts`


[NOTE, caption=]
.Repository can be extended!
====
It is possible to extend this repository with own search criteria.
====




===== Methods

[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Listing\Market\ItemSpecific\Models\ListingMarketItemSpecific

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarketitemspecific[`ListingMarketItemSpecific`]


Gets a ListingMarketItemSpecific.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#search]
----

public search($data, $page = 1, $itemsPerPage = 50):Plenty\Modules\Listing\Market\ItemSpecific\Models\ListingMarketItemSpecific

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarketitemspecific[`ListingMarketItemSpecific`]


Gets all ListingMarketItemSpecifics.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#find]
----

public find($filters = [], $page = 1, $itemsPerPage = 50):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Gets all ListingMarketItemSpecifics.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Listing\Market\ItemSpecific\Models\ListingMarketItemSpecific

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarketitemspecific[`ListingMarketItemSpecific`]


Updates a ListingMarketItemSpecific.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a ListingMarketItemSpecific.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#deletebylistingmarketid]
----

public deleteByListingMarketId($listingMarketId):bool

----







Deletes all ListingMarketItemSpecific entries by listing market id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarketId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[listing_itemspecific_models]]
===  Models
[[listing_models_listingmarketitemspecific]]
==== ListingMarketItemSpecific

The item specific model.



===== Namespace

`Plenty\Modules\Listing\Market\ItemSpecific\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the item specific.
|listingMarketId
    |link:http://php.net/int[int^]
    a|The LMID which belongs to the item specific ID.
|name
    |link:http://php.net/string[string^]
    a|The name of the item specific.
|value
    |link:http://php.net/string[string^]
    a|The value of the item specific.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_text]]
== Text

[[listing_text_contracts]]
===  Contracts
[[listing_contracts_listingmarkettextrepositorycontract]]
==== ListingMarketTextRepositoryContract

The contract for the listing market text repository.



===== Namespace

`Plenty\Modules\Listing\Market\Text\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Listing\Market\Text\Models\ListingMarketText

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarkettext[`ListingMarketText`]


Get a listing market text

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing market text.
|===


[source%nowrap, php]
[#create]
----

public create($listingMarketId, $data):Plenty\Modules\Listing\Market\Text\Models\ListingMarketText

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarkettext[`ListingMarketText`]


Create new listing market text

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarketId`
|link:http://php.net/int[int^]
a|The listing market ID the new market listing text belongs to.

a|`$data`
|link:http://php.net/array[array^]
a|The listing market text data as associative array.
|===


[source%nowrap, php]
[#update]
----

public update($listingMarketId, $lang, $data):Plenty\Modules\Listing\Market\Text\Models\ListingMarketText

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarkettext[`ListingMarketText`]


Update listing market text

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarketId`
|link:http://php.net/int[int^]
a|The listing market ID the new listing market text belongs to.

a|`$lang`
|link:http://php.net/string[string^]
a|The language that should be updated.

a|`$data`
|link:http://php.net/array[array^]
a|The listing market text data as associative array.
|===


[source%nowrap, php]
[#updateorcreate]
----

public updateOrCreate($listingMarketId, $lang, $data):Plenty\Modules\Listing\Market\Text\Models\ListingMarketText

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingmarkettext[`ListingMarketText`]


Update or create listing market text

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listingMarketId`
|link:http://php.net/int[int^]
a|The listing market ID the new listing market text belongs to.

a|`$lang`
|link:http://php.net/string[string^]
a|The language that should be updated.

a|`$data`
|link:http://php.net/array[array^]
a|The listing market text data as associative array.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Delete listing market text

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing market text.
|===


[source%nowrap, php]
[#search]
----

public search($page = 1, $itemsPerPage = 50, $filters = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List listing market text

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$filters`
|link:http://php.net/array[array^]
a|The filters that should be applied: 'id', 'language', 'contains'
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[listing_text_models]]
===  Models
[[listing_models_listingmarkettext]]
==== ListingMarketText

The listing market text model.



===== Namespace

`Plenty\Modules\Listing\Market\Text\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing market text.
|listingMarketId
    |link:http://php.net/int[int^]
    a|The ID of the listing market the text belongs to.
|lang
    |link:http://php.net/string[string^]
    a|The language of the listing market text. Available values: 'de', 'en', 'fr', 'it', 'es', 'tr', 'nl', 'pl', 'nn', 'da', 'se', 'cz', 'ru', 'sk', 'cn', 'vn', 'pt', 'bg', 'ro'.
|title
    |link:http://php.net/string[string^]
    a|The title of the listing market text.
|subtitle
    |link:http://php.net/string[string^]
    a|The subtitle of the listing market text.
|description
    |link:http://php.net/string[string^]
    a|The description of the listing market text.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_optiontemplate]]
== OptionTemplate

[[listing_optiontemplate_contracts]]
===  Contracts
[[listing_contracts_optiontemplaterepositorycontract]]
==== OptionTemplateRepositoryContract

The contract for the listing option template repository.



===== Namespace

`Plenty\Modules\Listing\OptionTemplate\Contracts`






===== Methods

[source%nowrap, php]
[#preview]
----

public preview():array

----







Get a preview list of all listing option templates

[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Listing\OptionTemplate\Models\OptionTemplate

----




====== *Return type:*        xref:Listing.adoc#listing_models_optiontemplate[`OptionTemplate`]


Get option template

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the option template.
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Listing\OptionTemplate\Models\OptionTemplate

----




====== *Return type:*        xref:Listing.adoc#listing_models_optiontemplate[`OptionTemplate`]


Create option template

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The option template data as associative array.
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):void

----







Update option template

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the option template.

a|`$data`
|link:http://php.net/array[array^]
a|The option template data as associative array.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):void

----







Delete option template

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the option template.
|===


[[listing_optiontemplate_models]]
===  Models
[[listing_models_optiontemplate]]
==== OptionTemplate

The option template model.



===== Namespace

`Plenty\Modules\Listing\OptionTemplate\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the option template.
|name
    |link:http://php.net/string[string^]
    a|The name of the option template.
|listing
    |link:http://php.net/array[array^]
    a|The listing options of the option template.
|listingMarket
    |link:http://php.net/array[array^]
    a|The listing market options of the option template.
|marketOptions
    |link:http://php.net/array[array^]
    a|The market options of the option template.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_price]]
== Price

[[listing_price_models]]
===  Models
[[listing_models_listingpricetype]]
==== ListingPriceType

The listing price type model.



===== Namespace

`Plenty\Modules\Listing\Price\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing price type. The following date types are available:
<ul>
<li>1 = Start price</li>
<li>2 = Fixed price</li>
<li>3 = Reserved price</li>
<li>4 = SCO minimum price</li>
<li>5 = Market fee</li>
</ul>
|isErasable
    |link:http://php.net/bool[bool^]
    a|Flag that states if this type can be deleted or not.
|names
    |
    a|The listing price type names.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingpricetypename]]
==== ListingPriceTypeName

The listing price type name model.



===== Namespace

`Plenty\Modules\Listing\Price\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing price type name.
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing price type.
|name
    |link:http://php.net/int[int^]
    a|The name of the listing price type.
|lang
    |link:http://php.net/int[int^]
    a|The language of the listing price type name.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_property]]
== Property

[[listing_property_models]]
===  Models
[[listing_models_listingpropertytype]]
==== ListingPropertyType

The listing properties model. Each listing property has a type.



===== Namespace

`Plenty\Modules\Listing\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing property. The following types are available:
<ul>
<li>1 = Shipping profile ID</li>
<li>2 = Order status</li>
<li>3 = Layout template ID</li>
<li>4 = Maximum number of images</li>
<li>5 = Warehouse ID</li>
<li>6 = Basic price in text</li>
<li>7 = Vat value</li>
<li>8 = Vat country ID</li>
<li>9 = Main language</li>
<li>10 = Use item price</li>
<li>11 = Number per lot</li>
<li>12 = Transmit item number type</li>
<li>13 = Relisted external ID</li>
<li>14 = SCO offer</li>
<li>15 = Promotion</li>
<li>16 = UUID</li>
<li>17 = Update error</li>
<li>18 = Has variations</li>
<li>19 = End now</li>
<li>20 = Insert by type</li>
<li>21 = Payment methods</li>
<li>22 = First platform category ID</li>
<li>23 = Second platform category ID</li>
<li>24 = First shop category ID</li>
<li>25 = Second shop category ID</li>
<li>26 = Third shop category ID</li>
<li>27 = Enhancements</li>
<li>100 = eBay parts fitment ID</li>
<li>101 = eBay maximum online listings</li>
<li>102 = eBay private auction</li>
<li>103 = eBay gallery type</li>
<li>104 = eBay gallery duration</li>
<li>105 = eBay transmit MPR</li>
<li>106 = eBay counter type</li>
<li>107 = eBay condition ID</li>
<li>108 = eBay condition description</li>
<li>109 = eBay best offer</li>
<li>110 = eBay best offer decline price</li>
<li>111 = eBay best offer accept price</li>
<li>112 = eBay is eBay Plus</li>
<li>113 = eBay is click & Collect</li>
<li>114 = eBay use EPS</li>
<li>115 = eBay best offer type</li>
<li>200 = Hood show on shop startpage</li>
<li>201 = Hood shipping discount</li>
<li>202 = Hood delivery days on stock from</li>
<li>203 = Hood delivery days on stock to</li>
<li>204 = Hood delivery days not on stock from</li>
<li>205 = Hood delivery days not on stock to</li>
<li>300 = Ricardo warranty ID</li>
<li>301 = Ricardo delivery ID</li>
<li>302 = Ricardo availability ID</li>
<li>303 = Ricardo delivery cost</li>
<li>304 = Ricardo payment ID</li>
<li>305 = Ricardo price increment</li>
<li>306 = Ricardo item condition ID</li>
<li>307 = Ricardo max relist count</li>
<li>308 = Ricardo is cumulative shipping</li>
<li>309 = Ricardo delivery package size ID</li>
<li>310 = Ricardo use secondary language</li>
<li>311 = Ricardo template ID</li>
<li>312 = Ricardo is relist sold out</li>
</ul>
|isErasable
    |link:http://php.net/bool[bool^]
    a|Flag that indicates if this type can be deleted or not.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingpropertytypename]]
==== ListingPropertyTypeName

The listing property type name model.



===== Namespace

`Plenty\Modules\Listing\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing property type name.
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing property type.
|name
    |link:http://php.net/int[int^]
    a|The name of the listing property type.
|lang
    |link:http://php.net/int[int^]
    a|The language of the listing property type name.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_shippingprofile]]
== ShippingProfile

[[listing_shippingprofile_contracts]]
===  Contracts
[[listing_contracts_shippingprofilerepositorycontract]]
==== ShippingProfileRepositoryContract

The ShippingProfileRepositoryContract is the interface for the listing shipping profile repository. This interface allows you to get a shipping profile.



===== Namespace

`Plenty\Modules\Listing\ShippingProfile\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Listing\ShippingProfile\Models\ShippingProfile

----




====== *Return type:*        xref:Listing.adoc#listing_models_shippingprofile[`ShippingProfile`]


Get a shipping profile

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the shipping profile.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ShippingProfile instance.
|===


[source%nowrap, php]
[#search]
----

public search($page = 1, $itemsPerPage = 50, $with = [], $filters = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Search shipping profiles

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ShippingProfile instance.

a|`$filters`
|link:http://php.net/array[array^]
a|The filters that should be applied. The filters that could be applied: 'id', 'referrerId', 'credentialsId'.
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[listing_shippingprofile_events]]
===  Events
[[listing_events_shippingprofilecreated]]
==== ShippingProfileCreated

An event class fired after a new listing shipping profile is created.



===== Namespace

`Plenty\Modules\Listing\ShippingProfile\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($shippingProfile):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$shippingProfile`
|        xref:Listing.adoc#listing_models_shippingprofile[`ShippingProfile`]
a|
|===


[source%nowrap, php]
[#getshippingprofile]
----

public getShippingProfile():Plenty\Modules\Listing\ShippingProfile\Models\ShippingProfile

----




====== *Return type:*        xref:Listing.adoc#listing_models_shippingprofile[`ShippingProfile`]


Get the ShippingProfile instance.


[[listing_events_shippingprofiledeleted]]
==== ShippingProfileDeleted

An event class fired after a listing shipping profile is deleted.



===== Namespace

`Plenty\Modules\Listing\ShippingProfile\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($shippingProfile):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$shippingProfile`
|        xref:Listing.adoc#listing_models_shippingprofile[`ShippingProfile`]
a|
|===


[source%nowrap, php]
[#getshippingprofile]
----

public getShippingProfile():Plenty\Modules\Listing\ShippingProfile\Models\ShippingProfile

----




====== *Return type:*        xref:Listing.adoc#listing_models_shippingprofile[`ShippingProfile`]


Get the ShippingProfile instance.


[[listing_events_shippingprofileevent]]
==== ShippingProfileEvent

A base event class for all listing shipping profile events. Each shipping profile event expects an ShippingProfile instance.



===== Namespace

`Plenty\Modules\Listing\ShippingProfile\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($shippingProfile):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$shippingProfile`
|        xref:Listing.adoc#listing_models_shippingprofile[`ShippingProfile`]
a|
|===


[source%nowrap, php]
[#getshippingprofile]
----

public getShippingProfile():Plenty\Modules\Listing\ShippingProfile\Models\ShippingProfile

----




====== *Return type:*        xref:Listing.adoc#listing_models_shippingprofile[`ShippingProfile`]


Get the ShippingProfile instance.


[[listing_events_shippingprofileupdated]]
==== ShippingProfileUpdated

An event class fired after a listing shipping profile is updated.



===== Namespace

`Plenty\Modules\Listing\ShippingProfile\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($shippingProfile):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$shippingProfile`
|        xref:Listing.adoc#listing_models_shippingprofile[`ShippingProfile`]
a|
|===


[source%nowrap, php]
[#getshippingprofile]
----

public getShippingProfile():Plenty\Modules\Listing\ShippingProfile\Models\ShippingProfile

----




====== *Return type:*        xref:Listing.adoc#listing_models_shippingprofile[`ShippingProfile`]


Get the ShippingProfile instance.

[[listing_shippingprofile_models]]
===  Models
[[listing_models_shippingprofile]]
==== ShippingProfile

The listing shipping profile model.



===== Namespace

`Plenty\Modules\Listing\ShippingProfile\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The listing shipping profile ID.
|name
    |link:http://php.net/string[string^]
    a|The listing shipping profile name.
|credentialsId
    |link:http://php.net/int[int^]
    a|The credentials ID that this listing shipping profile belongs to.
|referrerId
    |link:http://php.net/int[int^]
    a|The referrer ID.
|createdBy
    |link:http://php.net/string[string^]
    a|Who created the shipping profile. Possible values: 'migration','customer','external'.
|isDefault
    |link:http://php.net/bool[bool^]
    a|Tells if the current listing shipping profile is set as default.
|extendedData
    |link:http://php.net/array[array^]
    a|Extended data that defines the current shipping profile.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_status]]
== Status

[[listing_status_models]]
===  Models
[[listing_models_listingstatus]]
==== ListingStatus

The listing status model.



===== Namespace

`Plenty\Modules\Listing\Status\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing status.
|isErasable
    |link:http://php.net/int[int^]
    a|Flag that indicates if the status can be deleted.
|position
    |link:http://php.net/int[int^]
    a|The position for sorting.
|names
    |
    a|The listing status names.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingstatusname]]
==== ListingStatusName

The listing status name model.



===== Namespace

`Plenty\Modules\Listing\Status\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing status name.
|statusId
    |link:http://php.net/int[int^]
    a|The ID of the listing status.
|name
    |link:http://php.net/string[string^]
    a|The name of the listing status.
|lang
    |link:http://php.net/string[string^]
    a|The language of the listing status name.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_stockdependencetype]]
== StockDependenceType

[[listing_stockdependencetype_contracts]]
===  Contracts
[[listing_contracts_stockdependencetyperepositorycontract]]
==== StockDependenceTypeRepositoryContract

The contract for the listing stock dependence type repository.



===== Namespace

`Plenty\Modules\Listing\StockDependenceType\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Listing\StockDependenceType\Models\StockDependenceType

----




====== *Return type:*        xref:Listing.adoc#listing_models_stockdependencetype[`StockDependenceType`]


Get a listing stock dependence type

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing stock dependence type.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the StockDependenceType instance, available values are: "names".
|===


[source%nowrap, php]
[#all]
----

public all($page = 1, $itemsPerPage = 50, $with = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List listing stock dependence types

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarket instance. The relations available are 'names'.
|===


[[listing_stockdependencetype_models]]
===  Models
[[listing_models_stockdependencetype]]
==== StockDependenceType

The listing stock dependence type model.



===== Namespace

`Plenty\Modules\Listing\StockDependenceType\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing stock dependence type.
|isErasable
    |link:http://php.net/int[int^]
    a|Flag that indicates if the type can be deleted.
|position
    |link:http://php.net/int[int^]
    a|The position for sorting.
|names
    |
    a|The listing stock dependence type names.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_stockdependencetypename]]
==== StockDependenceTypeName

The listing stock dependence type name model.



===== Namespace

`Plenty\Modules\Listing\StockDependenceType\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing stock dependence type name.
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing stock type.
|name
    |link:http://php.net/string[string^]
    a|The name of the listing stock dependence type.
|lang
    |link:http://php.net/string[string^]
    a|The language of the listing stock dependence type name.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[listing_type]]
== Type

[[listing_type_contracts]]
===  Contracts
[[listing_contracts_listingtyperepositorycontract]]
==== ListingTypeRepositoryContract

The contract for the listing type repository.



===== Namespace

`Plenty\Modules\Listing\Type\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Listing\Type\Models\ListingType

----




====== *Return type:*        xref:Listing.adoc#listing_models_listingtype[`ListingType`]


Get a listing type

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the listing type.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the type instance, available values are: "names".
|===


[source%nowrap, php]
[#all]
----

public all($page = 1, $itemsPerPage = 50, $with = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List listing types

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the ListingMarket instance. The relations available are 'names'.
|===


[[listing_type_models]]
===  Models
[[listing_models_listingtype]]
==== ListingType

The listing type model.



===== Namespace

`Plenty\Modules\Listing\Type\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing type.
|isErasable
    |link:http://php.net/int[int^]
    a|Flag that indicates if the type can be deleted.
|position
    |link:http://php.net/int[int^]
    a|The position for sorting.
|names
    |
    a|The listing type names.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[listing_models_listingtypename]]
==== ListingTypeName

The listing type name model.



===== Namespace

`Plenty\Modules\Listing\Type\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the listing type name.
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the listing type.
|name
    |link:http://php.net/string[string^]
    a|The name of the listing type.
|lang
    |link:http://php.net/string[string^]
    a|The language of the listing type name.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

