:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[liveshopping_liveshopping]]
== LiveShopping

[[liveshopping_liveshopping_contracts]]
===  Contracts
[[liveshopping_contracts_liveshoppingrepositorycontract]]
==== LiveShoppingRepositoryContract

Return information about live shopping offers.



===== Namespace

`Plenty\Modules\LiveShopping\Contracts`






===== Methods

[source%nowrap, php]
----

public getLiveShopping($liveShoppingId):void

----







Get live shopping data for specific live shopping ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$liveShoppingId`
|link:http://php.net/int[int^]
a|Live shopping ID for which to retrieve data.
|===


[source%nowrap, php]
----

public getActiveByItemId($itemId):void

----







Get live shopping data for a specific item ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|Item ID for which to retrieve data.
|===


[source%nowrap, php]
----

public getActive($liveShoppingId):void

----







Get live shopping data for a specific live shopping ID and active status.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$liveShoppingId`
|link:http://php.net/int[int^]
a|Live shopping ID for which to retrieve data.
|===


[source%nowrap, php]
----

public getNextActive($liveShoppingId):void

----







Get the next live shopping data for a specific live shopping ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$liveShoppingId`
|link:http://php.net/int[int^]
a|Live shopping ID for which to retrieve data.
|===


[source%nowrap, php]
----

public getLastExpired($liveShoppingId):void

----







Get the last expired live shopping data for a specific live shopping ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$liveShoppingId`
|link:http://php.net/int[int^]
a|Live shopping ID for which to retrieve data.
|===


[source%nowrap, php]
----

public getRecentlyStartedOrExpired($time, $interval):void

----







Get recently started or expired live shopping data.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$time`
|link:http://php.net/int[int^]
a|Unix timestamp to define start time.

a|`$interval`
|link:http://php.net/int[int^]
a|Period time in seconds used to be checked before and after start time.
|===


[source%nowrap, php]
----

public itemHasActiveLiveShopping($itemId):bool

----







Get an active live shopping status for specific item ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|Item ID for which to retrieve active status.
|===


[source%nowrap, php]
----

public increaseRealQuantity($itemId, $increase):void

----







Increase the real sold quantity for specific item ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|Item ID for which to increase real sold quantity.

a|`$increase`
|link:http://php.net/float[float^]
a|Quantity to be increased.
|===


[[liveshopping_liveshopping_models]]
===  Models
[[liveshopping_models_liveshopping]]
==== LiveShopping

The LiveShopping data model.



===== Namespace

`Plenty\Modules\LiveShopping\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|Autoincremented ID
|fromTime
    |link:http://php.net/int[int^]
    a|Unix timestamp for the start time
|toTime
    |link:http://php.net/int[int^]
    a|Unix timestamp for the end time
|itemId
    |link:http://php.net/int[int^]
    a|Specific item ID
|quantitySold
    |link:http://php.net/int[int^]
    a|Declared quantity sold
|quantitySoldReal
    |link:http://php.net/int[int^]
    a|Defacto quantity sold
|quantityMax
    |link:http://php.net/int[int^]
    a|Declared maximal quantity for sale as live shopping
|liveShoppingId
    |link:http://php.net/int[int^]
    a|ID for a specific live shopping slot (1-10)
|link
    |link:http://php.net/int[int^]
    a|Link value
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.

