:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[mail_templates]]
== Templates

[[mail_templates_contracts]]
===  Contracts
[[mail_contracts_mailtemplatewidgetrepositorycontract]]
==== MailTemplateWidgetRepositoryContract

Register mail builder widgets.



===== Namespace

`Plenty\Modules\Mail\Templates\Contracts`






===== Methods

[source%nowrap, php]
[#registerwidget]
----

public registerWidget($widgetClass):void

----







Register a widget to be available in the mail builder.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$widgetClass`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#overridewidget]
----

public overrideWidget($widgetIdentifier, $overrideWidget):void

----







Override a widget class to extend data or settings of the widget.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$widgetIdentifier`
|link:http://php.net/string[string^]
a|The identifier of the original widget to override

a|`$overrideWidget`
|link:http://php.net/string[string^]
a|The class of the new class to get information of the widget from.
|===


[[mail_models]]
== Models

[[mail_models_templates]]
===  Templates
[[mail_templates_mailtemplateattachments]]
==== MailTemplateAttachments

The MailTemplateAttachments model. Stores the relation between
 *     mail templates - static attachments - dynamic attachments



===== Namespace

`Plenty\Modules\Mail\Templates\Models\Templates`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|configId
    |link:http://php.net/int[int^]
    a|plenty_mail_template_base_config.id // mail template id; required
|relationId
    |link:http://php.net/int[int^]
    a|plenty_mail_template_relation_id
|isStaticDoc
    |link:http://php.net/bool[bool^]
    a|The reference type. The following reference types are available; required
<ul>
     <li>0</li> // is dynamic
   <li>1</li> // is static
 </ul>
|documentId
    |link:http://php.net/int[int^]
    a|plenty_documents.id // static attachment document id; optional FK plenty_documents
|dynamicAttachmentId
    |link:http://php.net/string[string^]
    a|// dynamic attachment; optional; FK plenty_dynamic_attachments
|createdAt
    |
    a|The time the attachment was created as unix timestamp
|updatedAt
    |
    a|The time the attachment was last updated as unix timestamp
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

