:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[mail_templates]]
== Templates

[[mail_templates_contracts]]
===  Contracts
[[mail_contracts_mailtemplatewidgetrepositorycontract]]
==== MailTemplateWidgetRepositoryContract

Register mail builder widgets.



===== Namespace

`Plenty\Modules\Mail\Templates\Contracts`






===== Methods

[source%nowrap, php]
[#registerwidget]
----

public registerWidget($widgetClass):void

----







Register a widget to be available in the mail builder.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$widgetClass`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#overridewidget]
----

public overrideWidget($widgetIdentifier, $overrideWidget):void

----







Override a widget class to extend data or settings of the widget.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$widgetIdentifier`
|link:http://php.net/string[string^]
a|The identifier of the original widget to override

a|`$overrideWidget`
|link:http://php.net/string[string^]
a|The class of the new class to get information of the widget from.
|===


[[mail_service]]
== Service

[[mail_service_emailservice]]
===  EmailService
[[mail_emailservice_emailtemplatessendservicecontract]]
==== EmailTemplatesSendServiceContract

The EmailTemplatesSendServiceContract is the interface for the email service.
 * This interface defines methods to list available accounts, get list of templates, get send email history,
 * render a template preview, send a template or send a custom email.



===== Namespace

`Plenty\Modules\Mail\Templates\Contracts\Service\EmailService`






===== Methods

[source%nowrap, php]
[#getaccounts]
----

public getAccounts($filters):array

----







List all email accounts that can be used to send emails (e.g. Webstore or Messenger inboxes)

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|List of filters, see REST API documentation for more information
|===


[source%nowrap, php]
[#gettemplatestree]
----

public getTemplatesTree($sortBy = &quot;id&quot;, $sortOrder = &quot;asc&quot;, $filters = []):Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


List all EmailBuilder templates and folders structured as a nested tree

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sortBy`
|link:http://php.net/string[string^]
a|Sort results by a specific field

a|`$sortOrder`
|link:http://php.net/string[string^]
a|Sort results in ascending or descending order

a|`$filters`
|link:http://php.net/array[array^]
a|Filters to apply to the results
|===


[source%nowrap, php]
[#getemailhistory]
----

public getEmailHistory($filters = []):array

----







List all sent email for a specific entity (e.g order, contact, etc.)

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|Filters to apply to the results, see REST API documentation for more information
|===


[source%nowrap, php]
[#getpreview]
----

public getPreview($templateId, $data = []):array

----







Generates a render preview of a specific template

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$templateId`
|link:http://php.net/int[int^]
a|ID of the template to preview

a|`$data`
|link:http://php.net/array[array^]
a|Array with additional parameters (e.g order ID, receiver email, etc.),
see REST API documentation for more information
|===


[source%nowrap, php]
[#sendemail]
----

public sendEmail($templateId, $data = []):array

----







Renders a template and sends an email to the specified recipients

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$templateId`
|link:http://php.net/int[int^]
a|ID of the template to be sent

a|`$data`
|link:http://php.net/array[array^]
a|Array with additional parameters (e.g order ID, receiver email, etc.),
see REST API documentation for more information
|===


[source%nowrap, php]
[#sendpreview]
----

public sendPreview($data = []):array

----







Sends a direct email to the specified recipients (a preview of a template or any other custom content email)

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|Array with email data (e.g Account ID, from, subject, body, receivers, cc, bcc,
attachments, etc.), see REST API documentation for more information
|===


[[mail_models]]
== Models

[[mail_models_templates]]
===  Templates
[[mail_templates_mailtemplateattachments]]
==== MailTemplateAttachments

The MailTemplateAttachments model. Stores the relation between
 *     mail templates - static attachments



===== Namespace

`Plenty\Modules\Mail\Templates\Models\Templates`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|relationId
    |link:http://php.net/int[int^]
    a|plenty_mail_template_relation_id
|documentId
    |link:http://php.net/int[int^]
    a|plenty_documents.id // static attachment document id; optional FK plenty_documents
|createdAt
    |
    a|The time the attachment was created as unix timestamp
|updatedAt
    |
    a|The time the attachment was last updated as unix timestamp
|configId
    |link:http://php.net/int[int^]
    a|plenty_mail_template_base_config.id // mail template id; required
|isStaticDoc
    |link:http://php.net/bool[bool^]
    a|The reference type. The following reference types are available; required
<ul>
     <li>0</li> // is dynamic
   <li>1</li> // is static
 </ul>
|dynamicAttachmentId
    |link:http://php.net/string[string^]
    a|// dynamic attachment; optional; FK plenty_dynamic_attachments
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

