:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[market_accounts]]
== Accounts

[[market_accounts_contracts]]
===  Contracts
[[market_contracts_marketaccountsrepositorycontract]]
==== MarketAccountsRepositoryContract

The contract for the market accounts repository.



===== Namespace

`Plenty\Modules\Market\Accounts\Contracts`






===== Methods

[source%nowrap, php]
[#getall]
----

public getAll():void

----









[source%nowrap, php]
[#getbyreferrerid]
----

public getByReferrerId($referrerId):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$referrerId`
|
a|
|===


[[market_accounts_models]]
===  Models
[[market_models_account]]
==== Account

The market account model



===== Namespace

`Plenty\Modules\Market\Accounts\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|accountId
    |link:http://php.net/string[string^]
    a|The account id of the market
|label
    |link:http://php.net/string[string^]
    a|The label of the account
|referrerId
    |link:http://php.net/float[float^]
    a|The referrer the account depends to
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_market]]
==== Market

The market account model



===== Namespace

`Plenty\Modules\Market\Accounts\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|accounts
    |link:http://php.net/array[array^]
    a|The label of the account
|referrerId
    |link:http://php.net/float[float^]
    a|The referrer the account depends to
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[market_credentials]]
== Credentials

[[market_credentials_contracts]]
===  Contracts
[[market_contracts_credentialsrepositorycontract]]
==== CredentialsRepositoryContract

The contract for the fitment repository.



===== Namespace

`Plenty\Modules\Market\Credentials\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Market\Credentials\Models\Credentials

----




====== *Return type:*        xref:Market.adoc#market_models_credentials[`Credentials`]


Get credentials

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the credentials.
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Market\Credentials\Models\Credentials

----




====== *Return type:*        xref:Market.adoc#market_models_credentials[`Credentials`]


Create credentials

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The credentials data. The properties that are required to update credentials can be found in the credentials model.
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Market\Credentials\Models\Credentials

----




====== *Return type:*        xref:Market.adoc#market_models_credentials[`Credentials`]


Update credentials

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the credentials.

a|`$data`
|link:http://php.net/array[array^]
a|The credentials data. The properties that are required to update credentials can be found in the credentials model.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):Plenty\Repositories\Models\DeleteResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Delete credentials

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the credentials.
|===


[source%nowrap, php]
[#all]
----

public all($filters = []):array

----







List all credentials

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|Credentials can be filtered by ID, market, status, environment.
|===


[source%nowrap, php]
[#search]
----

public search($filters = [], $page, $itemsPerPage = \Plenty\Modules\Market\Credentials\Models\Credentials::MAX_ITEMS_PER_PAGE):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List credentials

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|Credentials can be filtered by ID, market, status, environment.

a|`$page`
|link:http://php.net/int[int^]
a|Current page of the response.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The requested amount of credentials per result page.
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[market_credentials_models]]
===  Models
[[market_models_credentials]]
==== Credentials

The credentials model



===== Namespace

`Plenty\Modules\Market\Credentials\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the credentials.
|environment
    |link:http://php.net/string[string^]
    a|The environment for the credentials. Possible values: sandbox, production
|status
    |link:http://php.net/string[string^]
    a|The status of the credentials. Possible values: active, inactive, pending
|data
    |link:http://php.net/array[array^]
    a|The data of the credentials.
|market
    |link:http://php.net/string[string^]
    a|The market for the current credentials.
|createdAt
    |
    a|The date that the credentials was created.
|updatedAt
    |
    a|The date that the credentials was updated last.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[market_accountpolicy]]
== AccountPolicy

[[market_accountpolicy_contracts]]
===  Contracts
[[market_contracts_fulfillmentpolicyrepositorycontract]]
==== FulfillmentPolicyRepositoryContract

The contract for the eBay fulfillment policy repository.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $filters = []):Plenty\Modules\Market\Ebay\AccountPolicy\Models\FulfillmentPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_fulfillmentpolicy[`FulfillmentPolicy`]


Get a stored fulfillment policy based on ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|The ID of the policy that we want to get

a|`$filters`
|link:http://php.net/array[array^]
a|A list of filters that are needed to get the corresponding policy. Available: `marketplaceId´, `credentialsId´.
|===



[[market_contracts_paymentpolicyrepositorycontract]]
==== PaymentPolicyRepositoryContract

The contract for the eBay payment policy repository.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $filters = []):Plenty\Modules\Market\Ebay\AccountPolicy\Models\PaymentPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_paymentpolicy[`PaymentPolicy`]


Get a stored payment policy based on ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|The ID of the payment policy.

a|`$filters`
|link:http://php.net/array[array^]
a|A list of filters that are needed to get the corresponding policy. Available: `marketplaceId´, `credentialsId´.
|===



[[market_contracts_returnpolicyrepositorycontract]]
==== ReturnPolicyRepositoryContract

The contract for the eBay return policy repository.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $filters = []):Plenty\Modules\Market\Ebay\AccountPolicy\Models\ReturnPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_returnpolicy[`ReturnPolicy`]


Get a stored return policy based on ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/string[string^]
a|The ID of the policy that we want to get

a|`$filters`
|link:http://php.net/array[array^]
a|A list of filters that are needed to get the corresponding policy. Available: `marketplaceId´, `credentialsId´.
|===


[[market_accountpolicy_events]]
===  Events
[[market_events_fulfillmentpolicycreated]]
==== FulfillmentPolicyCreated

An event class fired after a new fulfillment policy is created.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($fulfillmentPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fulfillmentPolicy`
|        xref:Market.adoc#market_models_fulfillmentpolicy[`FulfillmentPolicy`]
a|
|===


[source%nowrap, php]
[#getfulfillmentpolicy]
----

public getFulfillmentPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\FulfillmentPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_fulfillmentpolicy[`FulfillmentPolicy`]


Get the FulfillmentPolicy instance.


[[market_events_fulfillmentpolicydeleted]]
==== FulfillmentPolicyDeleted

An event class fired after a new fulfillment policy is deleted.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($fulfillmentPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fulfillmentPolicy`
|        xref:Market.adoc#market_models_fulfillmentpolicy[`FulfillmentPolicy`]
a|
|===


[source%nowrap, php]
[#getfulfillmentpolicy]
----

public getFulfillmentPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\FulfillmentPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_fulfillmentpolicy[`FulfillmentPolicy`]


Get the FulfillmentPolicy instance.


[[market_events_fulfillmentpolicyevent]]
==== FulfillmentPolicyEvent

A base event class for all fulfillment policy events. Each fulfillment policy events expects an FulfillmentPolicy model.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($fulfillmentPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fulfillmentPolicy`
|        xref:Market.adoc#market_models_fulfillmentpolicy[`FulfillmentPolicy`]
a|
|===


[source%nowrap, php]
[#getfulfillmentpolicy]
----

public getFulfillmentPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\FulfillmentPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_fulfillmentpolicy[`FulfillmentPolicy`]


Get the FulfillmentPolicy instance.


[[market_events_fulfillmentpolicyupdated]]
==== FulfillmentPolicyUpdated

An event class fired after a new fulfillment policy is updated.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($fulfillmentPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fulfillmentPolicy`
|        xref:Market.adoc#market_models_fulfillmentpolicy[`FulfillmentPolicy`]
a|
|===


[source%nowrap, php]
[#getfulfillmentpolicy]
----

public getFulfillmentPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\FulfillmentPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_fulfillmentpolicy[`FulfillmentPolicy`]


Get the FulfillmentPolicy instance.


[[market_events_paymentpolicycreated]]
==== PaymentPolicyCreated

An event class fired after a new payment policy is created.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($paymentPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentPolicy`
|        xref:Market.adoc#market_models_paymentpolicy[`PaymentPolicy`]
a|
|===


[source%nowrap, php]
[#getpaymentpolicy]
----

public getPaymentPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\PaymentPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_paymentpolicy[`PaymentPolicy`]


Get the PaymentPolicy instance.


[[market_events_paymentpolicydeleted]]
==== PaymentPolicyDeleted

An event class fired after a new payment policy is deleted.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($paymentPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentPolicy`
|        xref:Market.adoc#market_models_paymentpolicy[`PaymentPolicy`]
a|
|===


[source%nowrap, php]
[#getpaymentpolicy]
----

public getPaymentPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\PaymentPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_paymentpolicy[`PaymentPolicy`]


Get the PaymentPolicy instance.


[[market_events_paymentpolicyevent]]
==== PaymentPolicyEvent

A base event class for all payment policy events. Each payment policy events expects an PaymentPolicy model.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($paymentPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentPolicy`
|        xref:Market.adoc#market_models_paymentpolicy[`PaymentPolicy`]
a|
|===


[source%nowrap, php]
[#getpaymentpolicy]
----

public getPaymentPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\PaymentPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_paymentpolicy[`PaymentPolicy`]


Get the PaymentPolicy instance.


[[market_events_paymentpolicyupdated]]
==== PaymentPolicyUpdated

An event class fired after a new payment policy is updated.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($paymentPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentPolicy`
|        xref:Market.adoc#market_models_paymentpolicy[`PaymentPolicy`]
a|
|===


[source%nowrap, php]
[#getpaymentpolicy]
----

public getPaymentPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\PaymentPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_paymentpolicy[`PaymentPolicy`]


Get the PaymentPolicy instance.


[[market_events_returnpolicycreated]]
==== ReturnPolicyCreated

An event class fired after a new return policy is created.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($returnPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$returnPolicy`
|        xref:Market.adoc#market_models_returnpolicy[`ReturnPolicy`]
a|
|===


[source%nowrap, php]
[#getreturnpolicy]
----

public getReturnPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\ReturnPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_returnpolicy[`ReturnPolicy`]


Get the ReturnPolicy instance.


[[market_events_returnpolicydeleted]]
==== ReturnPolicyDeleted

An event class fired after a new return policy is deleted.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($returnPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$returnPolicy`
|        xref:Market.adoc#market_models_returnpolicy[`ReturnPolicy`]
a|
|===


[source%nowrap, php]
[#getreturnpolicy]
----

public getReturnPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\ReturnPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_returnpolicy[`ReturnPolicy`]


Get the ReturnPolicy instance.


[[market_events_returnpolicyevent]]
==== ReturnPolicyEvent

A base event class for all return policy events. Each return policy events expects an ReturnPolicy model.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($returnPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$returnPolicy`
|        xref:Market.adoc#market_models_returnpolicy[`ReturnPolicy`]
a|
|===


[source%nowrap, php]
[#getreturnpolicy]
----

public getReturnPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\ReturnPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_returnpolicy[`ReturnPolicy`]


Get the ReturnPolicy instance.


[[market_events_returnpolicyupdated]]
==== ReturnPolicyUpdated

An event class fired after a new return policy is updated.



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Events`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($returnPolicy):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$returnPolicy`
|        xref:Market.adoc#market_models_returnpolicy[`ReturnPolicy`]
a|
|===


[source%nowrap, php]
[#getreturnpolicy]
----

public getReturnPolicy():Plenty\Modules\Market\Ebay\AccountPolicy\Models\ReturnPolicy

----




====== *Return type:*        xref:Market.adoc#market_models_returnpolicy[`ReturnPolicy`]


Get the ReturnPolicy instance.

[[market_accountpolicy_models]]
===  Models
[[market_models_amounttype]]
==== AmountType

The eBay amount type model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|currency
    |link:http://php.net/string[string^]
    a|The base currency applied to the value field to establish a monetary amount. The currency is represented as a 3-letter ISO4217 currency code. For example, the code for the Canadian Dollar is CAD.
|value
    |link:http://php.net/float[float^]
    a|The value of the monetary amount in the specified currency.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_categorytype]]
==== CategoryType

The eBay category type model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|default
    |link:http://php.net/bool[bool^]
    a|If this value is set to true, it indicates that this policy is the default policy for the associated categoryTypes.name and marketplaceId pair
|name
    |link:http://php.net/string[string^]
    a|The category type to which the policy applies (motor vehicles or non-motor vehicles). Available values: `MOTORS_VEHICLES`, `ALL_EXCLUDING_MOTORS_VEHICLES`
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_deposit]]
==== Deposit

The eBay deposit model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|amount
    |        xref:Market.adoc#market_models_amounttype[`AmountType`]
    a|Deposits are used only with Motors listings and the amount value indicates the initial deposit that a buyer must make to purchase a motor vehicle. Deposits on motor vehicles can only be paid using PayPal, so if you specify a deposit amount, then you must also set the paymetMethodType value to 'PayPal'.
|dueIn
    |        xref:Market.adoc#market_models_timeduration[`TimeDuration`]
    a|Indicates the number of hours the buyer has (after they commit to buy) to make an initial deposit to the seller as a down payment on a motor vehicle.
|paymentMethods
    |        xref:Market.adoc#market_models_paymentmethod[`PaymentMethod`]
    a|A list of accepted payment methods. For deposits (which are applicable to only motor listings), the paymentMethodType must be set to 'PayPal'
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_fulfillmentpolicy]]
==== FulfillmentPolicy

The eBay fulfillment policy model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|fulfillmentPolicyId
    |link:http://php.net/string[string^]
    a|The ID of the fulfillment policy.
|categoryTypes
    |link:http://php.net/array[array^]
    a|The CategoryTypeEnum value to which this policy applies. Used to discern accounts that sell motor vehicles from those that don't. (Currently, each policy can be set to only one categoryTypes value at a time.)
|description
    |link:http://php.net/string[string^]
    a|An optional seller-defined description of the fulfillment policy.
|freightShipping
    |link:http://php.net/bool[bool^]
    a|Set this value to true to indicate the seller offers freight shipping.
|globalShipping
    |link:http://php.net/bool[bool^]
    a|If this value is set to true, it indicates the seller has opted-in to the eBay Global Shipping Program and that they use that service for thier internation shipments.
|handlingTime
    |        xref:Market.adoc#market_models_timeduration[`TimeDuration`]
    a|Specifies the maximum number of business days the seller commits to for preparing and shipping an order after receiving a cleared payment for the order.
|localPickup
    |link:http://php.net/bool[bool^]
    a|If this value is set to true, it indicates the seller offers local pickup of their items.
|marketplaceId
    |link:http://php.net/string[string^]
    a|The ID of the eBay marketplace to which this fulfillment policy applies. If this value is not specified, value defaults to the seller's eBay registration site.
|name
    |link:http://php.net/string[string^]
    a|A user-defined name for this fulfillment policy. Names must be unique for policies assigned to the same marketplace.
|pickupDropOff
    |link:http://php.net/bool[bool^]
    a|If this value is set to true, it indicates the seller offers the "Click and Collect" feature.
|shippingOptions
    |link:http://php.net/array[array^]
    a|A list that defines the seller's shipping configurations for DOMESTIC and INTERNATIONAL order shipments.
|shipToLocations
    |        xref:Market.adoc#market_models_regionset[`RegionSet`]
    a|This object contains the regionIncluded and regionExcluded fields, which indicate the areas to where the seller does and dosen't ship.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_paymentmethod]]
==== PaymentMethod

The eBay payment method model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|brands
    |link:http://php.net/array[array^]
    a|A list of credit card brands accepted by the seller. This field is required if the paymentMethodType is set to CREDIT_CARD.
|paymentMethodType
    |link:http://php.net/string[string^]
    a|The payment method, selected from the supported payment method types..
|recipientAccountReference
    |        xref:Market.adoc#market_models_recipientaccountreference[`RecipientAccountReference`]
    a|Information that is used to identify the recipient's account to which electronic funds are sent. This field is required if the payment method is set to PAYPAL, and the field must contain the email address associated with the PayPal account selected by the seller.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_paymentpolicy]]
==== PaymentPolicy

The eBay payment policy model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|paymentPolicyId
    |link:http://php.net/string[string^]
    a|The ID of the payment policy.
|categoryTypes
    |link:http://php.net/array[array^]
    a|The CategoryTypeEnum value to which this policy applies. The category type discerns whether the policy covers the sale of motor vehicles (via eBay Motors), or the sale of everything except motor vehicles.
|deposit
    |        xref:Market.adoc#market_models_deposit[`Deposit`]
    a|A container that describes the details of a deposit. Used only with motor listings.
|description
    |link:http://php.net/string[string^]
    a|An optional seller-defined description of the payment policy. (Max length: 250)
|fullPaymentDueIn
    |        xref:Market.adoc#market_models_timeduration[`TimeDuration`]
    a|Indicates the number of days that a buyer has to make their full payment to the seller, and close the remaining balance on a motor vehicle transaction. The period starts when the buyer commits to buy.
|immediatePay
    |link:http://php.net/bool[bool^]
    a|Indicate if the payment is due upon receipt or not. (eBay generates a receipt when the buyer agrees to purchase an item)
|marketplaceId
    |link:http://php.net/string[string^]
    a|The ID of the eBay marketplace to which this return policy applies. If this value is not specified, value defaults to the seller's eBay registration site.
|name
    |link:http://php.net/string[string^]
    a|A user-defined name for this payment policy. Names must be unique for policies assigned to the same marketplace. (Max length: 64)
|paymentInstructions
    |link:http://php.net/string[string^]
    a|Allows the seller to give payment instructions to the buyer. These instructions appear on the eBay View Item and Checkout pages.
|paymentMethods
    |        xref:Market.adoc#market_models_paymentmethod[`PaymentMethod`]
    a|A list of the payment methods accepted by the seller. Each payment policy must specify at least one payment method.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_recipientaccountreference]]
==== RecipientAccountReference

The eBay recipient account reference model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|referenceId
    |link:http://php.net/string[string^]
    a|The recipient's reference.
|referenceType
    |link:http://php.net/string[string^]
    a|The reference type of a recipient's account.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_region]]
==== Region

The eBay region model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|regionName
    |link:http://php.net/string[string^]
    a|A string that indicates the name of a region, as defined by eBay. A "region" can be either a 'world region' (e.g., the "Middle East" or "Southeast Asia") or a country, as represented with a two-letter country code.
|regionType
    |link:http://php.net/string[string^]
    a|Available values: `COUNTRY`, `COUNTRY_REGION`, `STATE_OR_PROVINCE`, `WORLD_REGION`, `WORLDWIDE`.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_regionset]]
==== RegionSet

The eBay region set model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|regionExcluded
    |link:http://php.net/array[array^]
    a|A list of one or more regionsName fields that specify the areas to where a seller does not ship. Populate regionExcluded in only the top-level shipToLocations container.
|regionIncluded
    |link:http://php.net/array[array^]
    a|A list of one or more regionsName fields that specify the areas to where a seller ships.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_returnpolicy]]
==== ReturnPolicy

The eBay return policy model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|returnPolicyId
    |link:http://php.net/string[string^]
    a|The ID of the return policy.
|categoryTypes
    |link:http://php.net/array[array^]
    a|For return policies, this field can be set to only `ALL_EXCLUDING_MOTORS_VEHICLES (returns on motor vehicles are not processed through eBay flows.)
|description
    |link:http://php.net/string[string^]
    a|An optional seller-defined description of the return policy.
|extendedHolidayReturnsOffered
    |link:http://php.net/bool[bool^]
    a|If this value is set to true, it indicates the seller offers an Extended Holiday Returns policy for their listings.
|marketplaceId
    |link:http://php.net/string[string^]
    a|The ID of the eBay marketplace to which this return policy applies. If this value is not specified, value defaults to the seller's eBay registration site.
|name
    |link:http://php.net/string[string^]
    a|A user-defined name for this fulfillment policy. Names must be unique for policies assigned to the same marketplace.
|refundMethod
    |link:http://php.net/string[string^]
    a|Indicates the method the seller uses to compensate the buyer for returned items. The return method specified applies only to remorse returns. Available options: `MERCHANDISE_CREDIT`, `MONEY_BACK`.
|restockingFeePercentage
    |link:http://php.net/string[string^]
    a|Sellers who accept returns should include this field if they charge buyers a restocking fee when items are returned.
|returnInstruction
    |link:http://php.net/string[string^]
    a|This optional free-form string field lets the seller provide a detailed explanation of the return policy.
|returnMethod
    |link:http://php.net/string[string^]
    a|This field indicates the method in which the seller handles non-money back return requests for remorse returns. Sellers can specify they either exchange or replace items. Available options: `EXCHANGE`, `REPLACEMENT`.
|returnPeriod
    |        xref:Market.adoc#market_models_timeduration[`TimeDuration`]
    a|This value indicates the length of time the seller accepts returns, the duration of which starts when the buyer receives the item.
|returnsAccepted
    |link:http://php.net/bool[bool^]
    a|Set this value to true to indicate the seller accepts returns.
|returnShippingCostPayer
    |link:http://php.net/string[string^]
    a|The seller uses this value to specify whether the buyer or the seller is responsible for paying return shipping charges. The field can be set to either `BUYER` or `SELLER`.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_shippingoption]]
==== ShippingOption

The eBay shipping option model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|costType
    |link:http://php.net/string[string^]
    a|Defines whether the shipping cost is `FLAT_RATE`, `CALCULATED`, or `NOT_SPECIFIED` (for use with freight shipping and local pickup)
|insuranceFee
    |        xref:Market.adoc#market_models_amounttype[`AmountType`]
    a|Sellers can offer international shipping insurance only when they ship to AU, FR, or IT. This value indicates the cost the buyer must pay to purchase shipping insurance for the items being shipped.
|insuranceOffered
    |link:http://php.net/bool[bool^]
    a|When set to true, it indicates the seller offers shipping insurance.
|optionType
    |link:http://php.net/string[string^]
    a|Use this field to set the ShippingOption element to either `DOMESTIC` or `INTERNATIONAL`
|packageHandlingCost
    |        xref:Market.adoc#market_models_amounttype[`AmountType`]
    a|A fee a seller can add to cover package and handling costs. This fee is in addition to the amount of the selected shipping service and this fee is included in the final shipping service costs in the output.
|rateTableId
    |link:http://php.net/string[string^]
    a|A unique eBay-assigned ID associated with a user-created shipping rate table.
|shippingServices
    |link:http://php.net/array[array^]
    a|Contains a list of shipping services offered for either `DOMESTIC` or `INTERNATIONAL` shipments.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_shippingservice]]
==== ShippingService

The eBay shipping service model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|additionalShippingCost
    |        xref:Market.adoc#market_models_amounttype[`AmountType`]
    a|The cost of shipping each additional item if the same buyer purchases a multiple quantity of the same line item. This field is applicable for policies that cover multiple-quantity, fixed-price listings and is not applicable for policies that apply to single-quantity listings.
|buyerResponsibleForPickup
    |link:http://php.net/bool[bool^]
    a|This field is only applicable to vehicle categories on eBay Motors (US and Canada). If set to true, the buyer is responsible for picking up the vehicle. Otherwise, the seller should specify the vehicle pickup arrangements in the item description.
|buyerResponsibleForShipping
    |link:http://php.net/bool[bool^]
    a|This field is applicable for only items listed in vehicle categories on eBay Motors (US and Canada). If set to true, the buyer is responsible for the shipment of the vehicle. Otherwise, the seller should specify the vehicle shipping arrangements in the item description.
|cashOnDeliveryFee
    |        xref:Market.adoc#market_models_amounttype[`AmountType`]
    a|The value indicates the Cash on Delivery (COD) fee that the seller charges if the buyer uses the CASH_ON_DELIVERY payment method.
|freeShipping
    |link:http://php.net/bool[bool^]
    a|The seller can set this flag to true if they want to offer free shipping to the buyer. This field can only be included and set to 'true' for the first domestic shipping service option specified in the shippingServices container
|shippingCarrierCode
    |link:http://php.net/string[string^]
    a|The shipping carrier, such as 'USPS', 'FedEx', 'UPS', and so on.
|shippingCost
    |        xref:Market.adoc#market_models_amounttype[`AmountType`]
    a|For shipping options that use a FLAT_RATE cost type, the amount is the shipping cost for the selected shipping carrier and service. The amount supplied must exclude any additional shipping charges (such as the seller's handling charges or insurance).
|shippingServiceCode
    |link:http://php.net/string[string^]
    a|The shipping service that the shipping carrier uses to ship an item. For example, an overnight, two-day delivery, or other type of service.
|shipToLocations
    |        xref:Market.adoc#market_models_regionset[`RegionSet`]
    a|This object contains the regionIncluded and regionExcluded fields that define the list of geographical regions that the seller ships to and the list of regions where they do not ship.
|sortOrder
    |link:http://php.net/int[int^]
    a|This integer value controls the order that this shipping service option appears in the View Item and Checkout pages, as related to the other specified shipping service options.
|surcharge
    |        xref:Market.adoc#market_models_amounttype[`AmountType`]
    a|A fee that can be charged to US buyers when they have an item shipped via UPS or FedEx to Alaska, Hawaii or Puerto Rico.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_timeduration]]
==== TimeDuration

The eBay time duration model



===== Namespace

`Plenty\Modules\Market\Ebay\AccountPolicy\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|unit
    |link:http://php.net/string[string^]
    a|A time-measurement unit used to specify a period of time. Available values: `MONTH`, `DAY`, `HOUR`, `CALENDAR_DAY`, `BUSINESS_DAY`, `MINUTE`, `SECOND`, `MILLISECOND`
|value
    |link:http://php.net/string[string^]
    a|An amount of time, as measured by the time-measurement units specified in the unit field.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[market_api]]
== Api

[[market_api_exceptions]]
===  Exceptions
[[market_exceptions_invalidendpointexception]]
==== InvalidEndPointException

InvalidEndPointException.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Exceptions`






===== Methods

[source%nowrap, php]
[#getmessage]
----

public getMessage():void

----









[source%nowrap, php]
[#getcode]
----

public getCode():void

----









[source%nowrap, php]
[#getfile]
----

public getFile():void

----









[source%nowrap, php]
[#getline]
----

public getLine():void

----









[source%nowrap, php]
[#gettrace]
----

public getTrace():void

----









[source%nowrap, php]
[#getprevious]
----

public getPrevious():void

----









[source%nowrap, php]
[#gettraceasstring]
----

public getTraceAsString():void

----










[[market_exceptions_invalidpropertytypeexception]]
==== InvalidPropertyTypeException

InvalidPropertyTypeException.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Exceptions`






===== Methods

[source%nowrap, php]
[#getmessage]
----

public getMessage():void

----









[source%nowrap, php]
[#getcode]
----

public getCode():void

----









[source%nowrap, php]
[#getfile]
----

public getFile():void

----









[source%nowrap, php]
[#getline]
----

public getLine():void

----









[source%nowrap, php]
[#gettrace]
----

public getTrace():void

----









[source%nowrap, php]
[#getprevious]
----

public getPrevious():void

----









[source%nowrap, php]
[#gettraceasstring]
----

public getTraceAsString():void

----










[[market_exceptions_unknownpropertyexception]]
==== UnknownPropertyException

InvalidPropertyTypeException.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Exceptions`






===== Methods

[source%nowrap, php]
[#getmessage]
----

public getMessage():void

----









[source%nowrap, php]
[#getcode]
----

public getCode():void

----









[source%nowrap, php]
[#getfile]
----

public getFile():void

----









[source%nowrap, php]
[#getline]
----

public getLine():void

----









[source%nowrap, php]
[#gettrace]
----

public getTrace():void

----









[source%nowrap, php]
[#getprevious]
----

public getPrevious():void

----









[source%nowrap, php]
[#gettraceasstring]
----

public getTraceAsString():void

----









[[market_api_services]]
===  Services
[[market_services_baserestservice]]
==== BaseRestService

The service for making eBay REST calls.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Services`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($config):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$config`
|link:http://php.net/array[array^]
a|Configuration option values.
|===


[source%nowrap, php]
[#getconfigdefinitions]
----

public static getConfigDefinitions():array

----







Returns definitions for each configuration option that is supported.

[source%nowrap, php]
[#getconfig]
----

public getConfig($option = null, $default = null):void

----







Method to get the service&#039;s configuration.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$option`
|link:http://php.net/string[string^]
a|The name of the option whos value will be returned.

a|`$default`
|
a|
|===


[source%nowrap, php]
[#calloperation]
----

public callOperation($name, $request = null):Plenty\Modules\Market\Ebay\Api\Types\BaseType

----




====== *Return type:*        xref:Market.adoc#market_types_basetype[`BaseType`]


Build API request and send.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The name of the operation.

a|`$request`
|        xref:Market.adoc#market_types_basetype[`BaseType`]
a|Request object containing the request information.
|===


[source%nowrap, php]
[#getebayheaders]
----

public getEbayHeaders():array

----







Derived classes must implement this method that will build the needed eBay http headers.


[[market_services_basewsdlservice]]
==== BaseWsdlService

The service for making eBay WSDL calls.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Services`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($config):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$config`
|link:http://php.net/array[array^]
a|Configuration option values.
|===


[source%nowrap, php]
[#getconfigdefinitions]
----

public static getConfigDefinitions():array

----







Returns definitions for each configuration option that is supported.

[source%nowrap, php]
[#getconfig]
----

public getConfig($option = null, $default = null):void

----







Method to get the service&#039;s configuration.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$option`
|link:http://php.net/string[string^]
a|The name of the option whos value will be returned.

a|`$default`
|
a|
|===


[source%nowrap, php]
[#calloperation]
----

public callOperation($name, $request, $responseClass):Plenty\Modules\Market\Ebay\Api\Types\BaseType

----




====== *Return type:*        xref:Market.adoc#market_types_basetype[`BaseType`]


Build API request and send.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The name of the operation.

a|`$request`
|        xref:Market.adoc#market_types_basetype[`BaseType`]
a|Request object containing the request information.

a|`$responseClass`
|link:http://php.net/string[string^]
a|The name of the PHP class that will be created from the XML response.
|===


[source%nowrap, php]
[#getebayheaders]
----

public getEbayHeaders($operationName):array

----







Derived classes must implement this method that will build the needed eBay http headers.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$operationName`
|link:http://php.net/string[string^]
a|The name of the operation been called.
|===


[[market_api_types]]
===  Types
[[market_types_base64binarytype]]
==== Base64BinaryType

The service for eBay Base64BinaryType.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Types`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|properties
    |
    a|
|xmlNamespaces
    |
    a|
|requestXmlRootElementNames
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($values = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$values`
|link:http://php.net/array[array^]
a|Optional properties and values to assign to the object.
|===


[source%nowrap, php]
[#getparentvalues]
----

public static getParentValues($properties, $values):array

----







Helper function to remove the properties and values that belong to a object&#039;s parent.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$properties`
|link:http://php.net/array[array^]
a|

a|`$values`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#__get]
----

public __get($name):void

----







PHP magic function that is called when getting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__set]
----

public __set($name, $value):void

----







PHP magic function that is called when setting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.

a|`$value`
|
a|Value assigned to the property.
|===


[source%nowrap, php]
[#__isset]
----

public __isset($name):bool

----







PHP magic function that is called to determine if a property is set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__unset]
----

public __unset($name):void

----







PHP magic function that is called to unset a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#torequestxml]
----

public toRequestXml():string

----







Converts the object to a XML request string.

[source%nowrap, php]
[#elementmeta]
----

public elementMeta($elementName):void

----







Returns the meta data for a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$elementName`
|link:http://php.net/string[string^]
a|The element name.
|===


[source%nowrap, php]
[#attachment]
----

public attachment($data = null, $mimeType = &quot;application/octet-stream&quot;):void

----







Method to get or set the object&#039;s attachment. Overrides any existing attachment is setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|If a string it is assumed to be the contents of the attachment. If an array copy its values across.

a|`$mimeType`
|link:http://php.net/string[string^]
a|The MIME type of the attachment that will be used in the request. Defaults to application/octet-stream.
|===


[source%nowrap, php]
[#hasattachment]
----

public hasAttachment():bool

----







Helper method to check if an object has an attachment.

[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Helper method that returns an associative array of the object&#039;s properties and values.

[source%nowrap, php]
[#search]
----

public search($expression):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$expression`
|link:http://php.net/string[string^]
a|A valid JMESPath expression
|===


[source%nowrap, php]
[#setvalues]
----

public setValues($class, $values = []):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$class`
|link:http://php.net/string[string^]
a|The name of the class the properties belong to.

a|`$values`
|link:http://php.net/array[array^]
a|Associative array of property names and their values.
|===



[[market_types_basetype]]
==== BaseType

The service for base type.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Types`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|properties
    |
    a|
|xmlNamespaces
    |
    a|
|requestXmlRootElementNames
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($values = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$values`
|link:http://php.net/array[array^]
a|Can pass an associative array that will set the objects properties.
|===


[source%nowrap, php]
[#__get]
----

public __get($name):void

----







PHP magic function that is called when getting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__set]
----

public __set($name, $value):void

----







PHP magic function that is called when setting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.

a|`$value`
|
a|Value assigned to the property.
|===


[source%nowrap, php]
[#__isset]
----

public __isset($name):bool

----







PHP magic function that is called to determine if a property is set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__unset]
----

public __unset($name):void

----







PHP magic function that is called to unset a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#torequestxml]
----

public toRequestXml():string

----







Converts the object to a XML request string.

[source%nowrap, php]
[#elementmeta]
----

public elementMeta($elementName):void

----







Returns the meta data for a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$elementName`
|link:http://php.net/string[string^]
a|The element name.
|===


[source%nowrap, php]
[#attachment]
----

public attachment($data = null, $mimeType = &quot;application/octet-stream&quot;):void

----







Method to get or set the object&#039;s attachment. Overrides any existing attachment is setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|If a string it is assumed to be the contents of the attachment. If an array copy its values across.

a|`$mimeType`
|link:http://php.net/string[string^]
a|The MIME type of the attachment that will be used in the request. Defaults to application/octet-stream.
|===


[source%nowrap, php]
[#hasattachment]
----

public hasAttachment():bool

----







Helper method to check if an object has an attachment.

[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Helper method that returns an associative array of the object&#039;s properties and values.

[source%nowrap, php]
[#search]
----

public search($expression):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$expression`
|link:http://php.net/string[string^]
a|A valid JMESPath expression
|===


[source%nowrap, php]
[#setvalues]
----

public setValues($class, $values = []):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$class`
|link:http://php.net/string[string^]
a|The name of the class the properties belong to.

a|`$values`
|link:http://php.net/array[array^]
a|Associative array of property names and their values.
|===


[source%nowrap, php]
[#getparentvalues]
----

public static getParentValues($properties, $values):array

----







Helper function to remove the properties and values that belong to a object&#039;s parent.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$properties`
|link:http://php.net/array[array^]
a|

a|`$values`
|link:http://php.net/array[array^]
a|
|===



[[market_types_booleantype]]
==== BooleanType

The service for boolean type.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Types`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|properties
    |
    a|
|xmlNamespaces
    |
    a|
|requestXmlRootElementNames
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($values = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$values`
|link:http://php.net/array[array^]
a|Optional properties and values to assign to the object.
|===


[source%nowrap, php]
[#getparentvalues]
----

public static getParentValues($properties, $values):array

----







Helper function to remove the properties and values that belong to a object&#039;s parent.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$properties`
|link:http://php.net/array[array^]
a|

a|`$values`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#__get]
----

public __get($name):void

----







PHP magic function that is called when getting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__set]
----

public __set($name, $value):void

----







PHP magic function that is called when setting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.

a|`$value`
|
a|Value assigned to the property.
|===


[source%nowrap, php]
[#__isset]
----

public __isset($name):bool

----







PHP magic function that is called to determine if a property is set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__unset]
----

public __unset($name):void

----







PHP magic function that is called to unset a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#torequestxml]
----

public toRequestXml():string

----







Converts the object to a XML request string.

[source%nowrap, php]
[#elementmeta]
----

public elementMeta($elementName):void

----







Returns the meta data for a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$elementName`
|link:http://php.net/string[string^]
a|The element name.
|===


[source%nowrap, php]
[#attachment]
----

public attachment($data = null, $mimeType = &quot;application/octet-stream&quot;):void

----







Method to get or set the object&#039;s attachment. Overrides any existing attachment is setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|If a string it is assumed to be the contents of the attachment. If an array copy its values across.

a|`$mimeType`
|link:http://php.net/string[string^]
a|The MIME type of the attachment that will be used in the request. Defaults to application/octet-stream.
|===


[source%nowrap, php]
[#hasattachment]
----

public hasAttachment():bool

----







Helper method to check if an object has an attachment.

[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Helper method that returns an associative array of the object&#039;s properties and values.

[source%nowrap, php]
[#search]
----

public search($expression):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$expression`
|link:http://php.net/string[string^]
a|A valid JMESPath expression
|===


[source%nowrap, php]
[#setvalues]
----

public setValues($class, $values = []):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$class`
|link:http://php.net/string[string^]
a|The name of the class the properties belong to.

a|`$values`
|link:http://php.net/array[array^]
a|Associative array of property names and their values.
|===



[[market_types_decimaltype]]
==== DecimalType

The service for decimal type.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Types`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|properties
    |
    a|
|xmlNamespaces
    |
    a|
|requestXmlRootElementNames
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($values = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$values`
|link:http://php.net/array[array^]
a|Optional properties and values to assign to the object.
|===


[source%nowrap, php]
[#getparentvalues]
----

public static getParentValues($properties, $values):array

----







Helper function to remove the properties and values that belong to a object&#039;s parent.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$properties`
|link:http://php.net/array[array^]
a|

a|`$values`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#__get]
----

public __get($name):void

----







PHP magic function that is called when getting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__set]
----

public __set($name, $value):void

----







PHP magic function that is called when setting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.

a|`$value`
|
a|Value assigned to the property.
|===


[source%nowrap, php]
[#__isset]
----

public __isset($name):bool

----







PHP magic function that is called to determine if a property is set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__unset]
----

public __unset($name):void

----







PHP magic function that is called to unset a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#torequestxml]
----

public toRequestXml():string

----







Converts the object to a XML request string.

[source%nowrap, php]
[#elementmeta]
----

public elementMeta($elementName):void

----







Returns the meta data for a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$elementName`
|link:http://php.net/string[string^]
a|The element name.
|===


[source%nowrap, php]
[#attachment]
----

public attachment($data = null, $mimeType = &quot;application/octet-stream&quot;):void

----







Method to get or set the object&#039;s attachment. Overrides any existing attachment is setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|If a string it is assumed to be the contents of the attachment. If an array copy its values across.

a|`$mimeType`
|link:http://php.net/string[string^]
a|The MIME type of the attachment that will be used in the request. Defaults to application/octet-stream.
|===


[source%nowrap, php]
[#hasattachment]
----

public hasAttachment():bool

----







Helper method to check if an object has an attachment.

[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Helper method that returns an associative array of the object&#039;s properties and values.

[source%nowrap, php]
[#search]
----

public search($expression):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$expression`
|link:http://php.net/string[string^]
a|A valid JMESPath expression
|===


[source%nowrap, php]
[#setvalues]
----

public setValues($class, $values = []):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$class`
|link:http://php.net/string[string^]
a|The name of the class the properties belong to.

a|`$values`
|link:http://php.net/array[array^]
a|Associative array of property names and their values.
|===



[[market_types_doubletype]]
==== DoubleType

The service for double type.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Types`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|properties
    |
    a|
|xmlNamespaces
    |
    a|
|requestXmlRootElementNames
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($values = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$values`
|link:http://php.net/array[array^]
a|Optional properties and values to assign to the object.
|===


[source%nowrap, php]
[#getparentvalues]
----

public static getParentValues($properties, $values):array

----







Helper function to remove the properties and values that belong to a object&#039;s parent.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$properties`
|link:http://php.net/array[array^]
a|

a|`$values`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#__get]
----

public __get($name):void

----







PHP magic function that is called when getting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__set]
----

public __set($name, $value):void

----







PHP magic function that is called when setting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.

a|`$value`
|
a|Value assigned to the property.
|===


[source%nowrap, php]
[#__isset]
----

public __isset($name):bool

----







PHP magic function that is called to determine if a property is set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__unset]
----

public __unset($name):void

----







PHP magic function that is called to unset a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#torequestxml]
----

public toRequestXml():string

----







Converts the object to a XML request string.

[source%nowrap, php]
[#elementmeta]
----

public elementMeta($elementName):void

----







Returns the meta data for a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$elementName`
|link:http://php.net/string[string^]
a|The element name.
|===


[source%nowrap, php]
[#attachment]
----

public attachment($data = null, $mimeType = &quot;application/octet-stream&quot;):void

----







Method to get or set the object&#039;s attachment. Overrides any existing attachment is setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|If a string it is assumed to be the contents of the attachment. If an array copy its values across.

a|`$mimeType`
|link:http://php.net/string[string^]
a|The MIME type of the attachment that will be used in the request. Defaults to application/octet-stream.
|===


[source%nowrap, php]
[#hasattachment]
----

public hasAttachment():bool

----







Helper method to check if an object has an attachment.

[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Helper method that returns an associative array of the object&#039;s properties and values.

[source%nowrap, php]
[#search]
----

public search($expression):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$expression`
|link:http://php.net/string[string^]
a|A valid JMESPath expression
|===


[source%nowrap, php]
[#setvalues]
----

public setValues($class, $values = []):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$class`
|link:http://php.net/string[string^]
a|The name of the class the properties belong to.

a|`$values`
|link:http://php.net/array[array^]
a|Associative array of property names and their values.
|===



[[market_types_integertype]]
==== IntegerType

The service for integer type.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Types`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|properties
    |
    a|
|xmlNamespaces
    |
    a|
|requestXmlRootElementNames
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($values = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$values`
|link:http://php.net/array[array^]
a|Optional properties and values to assign to the object.
|===


[source%nowrap, php]
[#getparentvalues]
----

public static getParentValues($properties, $values):array

----







Helper function to remove the properties and values that belong to a object&#039;s parent.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$properties`
|link:http://php.net/array[array^]
a|

a|`$values`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#__get]
----

public __get($name):void

----







PHP magic function that is called when getting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__set]
----

public __set($name, $value):void

----







PHP magic function that is called when setting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.

a|`$value`
|
a|Value assigned to the property.
|===


[source%nowrap, php]
[#__isset]
----

public __isset($name):bool

----







PHP magic function that is called to determine if a property is set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__unset]
----

public __unset($name):void

----







PHP magic function that is called to unset a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#torequestxml]
----

public toRequestXml():string

----







Converts the object to a XML request string.

[source%nowrap, php]
[#elementmeta]
----

public elementMeta($elementName):void

----







Returns the meta data for a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$elementName`
|link:http://php.net/string[string^]
a|The element name.
|===


[source%nowrap, php]
[#attachment]
----

public attachment($data = null, $mimeType = &quot;application/octet-stream&quot;):void

----







Method to get or set the object&#039;s attachment. Overrides any existing attachment is setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|If a string it is assumed to be the contents of the attachment. If an array copy its values across.

a|`$mimeType`
|link:http://php.net/string[string^]
a|The MIME type of the attachment that will be used in the request. Defaults to application/octet-stream.
|===


[source%nowrap, php]
[#hasattachment]
----

public hasAttachment():bool

----







Helper method to check if an object has an attachment.

[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Helper method that returns an associative array of the object&#039;s properties and values.

[source%nowrap, php]
[#search]
----

public search($expression):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$expression`
|link:http://php.net/string[string^]
a|A valid JMESPath expression
|===


[source%nowrap, php]
[#setvalues]
----

public setValues($class, $values = []):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$class`
|link:http://php.net/string[string^]
a|The name of the class the properties belong to.

a|`$values`
|link:http://php.net/array[array^]
a|Associative array of property names and their values.
|===



[[market_types_repeatabletype]]
==== RepeatableType

The service for repeatable type.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Types`






===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($class, $property, $expectedType):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$class`
|link:http://php.net/string[string^]
a|The name of the class that the property is a member of.

a|`$property`
|link:http://php.net/string[string^]
a|The name of the property that acts like an array.

a|`$expectedType`
|link:http://php.net/string[string^]
a|The type that values assigned to the array should be.
|===


[source%nowrap, php]
[#offsetexists]
----

public offsetExists($offset):bool

----







Determines if the offset exists in the array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$offset`
|link:http://php.net/int[int^]
a|The array index to check.
|===


[source%nowrap, php]
[#offsetget]
----

public offsetGet($offset):void

----







Returns the value of the given offset.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$offset`
|link:http://php.net/int[int^]
a|The array index.
|===


[source%nowrap, php]
[#offsetset]
----

public offsetSet($offset, $value):void

----







Sets a value for the given offset.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$offset`
|
a|The array index or null to add the value to the end of the array.

a|`$value`
|
a|The value to add.
|===


[source%nowrap, php]
[#offsetunset]
----

public offsetUnset($offset):void

----







Unsets the value of the given offset.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$offset`
|link:http://php.net/int[int^]
a|The array index.
|===


[source%nowrap, php]
[#count]
----

public count():int

----









[source%nowrap, php]
[#current]
----

public current():void

----









[source%nowrap, php]
[#key]
----

public key():int

----









[source%nowrap, php]
[#next]
----

public next():void

----







Move onto the next array index.

[source%nowrap, php]
[#rewind]
----

public rewind():void

----







Reset the array index to the start of the array.

[source%nowrap, php]
[#valid]
----

public valid():bool

----










[[market_types_stringtype]]
==== StringType

The service for string type.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Types`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|properties
    |
    a|
|xmlNamespaces
    |
    a|
|requestXmlRootElementNames
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($values = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$values`
|link:http://php.net/array[array^]
a|Optional properties and values to assign to the object.
|===


[source%nowrap, php]
[#getparentvalues]
----

public static getParentValues($properties, $values):array

----







Helper function to remove the properties and values that belong to a object&#039;s parent.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$properties`
|link:http://php.net/array[array^]
a|

a|`$values`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#__get]
----

public __get($name):void

----







PHP magic function that is called when getting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__set]
----

public __set($name, $value):void

----







PHP magic function that is called when setting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.

a|`$value`
|
a|Value assigned to the property.
|===


[source%nowrap, php]
[#__isset]
----

public __isset($name):bool

----







PHP magic function that is called to determine if a property is set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__unset]
----

public __unset($name):void

----







PHP magic function that is called to unset a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#torequestxml]
----

public toRequestXml():string

----







Converts the object to a XML request string.

[source%nowrap, php]
[#elementmeta]
----

public elementMeta($elementName):void

----







Returns the meta data for a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$elementName`
|link:http://php.net/string[string^]
a|The element name.
|===


[source%nowrap, php]
[#attachment]
----

public attachment($data = null, $mimeType = &quot;application/octet-stream&quot;):void

----







Method to get or set the object&#039;s attachment. Overrides any existing attachment is setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|If a string it is assumed to be the contents of the attachment. If an array copy its values across.

a|`$mimeType`
|link:http://php.net/string[string^]
a|The MIME type of the attachment that will be used in the request. Defaults to application/octet-stream.
|===


[source%nowrap, php]
[#hasattachment]
----

public hasAttachment():bool

----







Helper method to check if an object has an attachment.

[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Helper method that returns an associative array of the object&#039;s properties and values.

[source%nowrap, php]
[#search]
----

public search($expression):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$expression`
|link:http://php.net/string[string^]
a|A valid JMESPath expression
|===


[source%nowrap, php]
[#setvalues]
----

public setValues($class, $values = []):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$class`
|link:http://php.net/string[string^]
a|The name of the class the properties belong to.

a|`$values`
|link:http://php.net/array[array^]
a|Associative array of property names and their values.
|===



[[market_types_tokentype]]
==== TokenType

The service for token type.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Types`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|properties
    |
    a|
|xmlNamespaces
    |
    a|
|requestXmlRootElementNames
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($values = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$values`
|link:http://php.net/array[array^]
a|Optional properties and values to assign to the object.
|===


[source%nowrap, php]
[#getparentvalues]
----

public static getParentValues($properties, $values):array

----







Helper function to remove the properties and values that belong to a object&#039;s parent.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$properties`
|link:http://php.net/array[array^]
a|

a|`$values`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#__get]
----

public __get($name):void

----







PHP magic function that is called when getting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__set]
----

public __set($name, $value):void

----







PHP magic function that is called when setting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.

a|`$value`
|
a|Value assigned to the property.
|===


[source%nowrap, php]
[#__isset]
----

public __isset($name):bool

----







PHP magic function that is called to determine if a property is set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__unset]
----

public __unset($name):void

----







PHP magic function that is called to unset a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#torequestxml]
----

public toRequestXml():string

----







Converts the object to a XML request string.

[source%nowrap, php]
[#elementmeta]
----

public elementMeta($elementName):void

----







Returns the meta data for a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$elementName`
|link:http://php.net/string[string^]
a|The element name.
|===


[source%nowrap, php]
[#attachment]
----

public attachment($data = null, $mimeType = &quot;application/octet-stream&quot;):void

----







Method to get or set the object&#039;s attachment. Overrides any existing attachment is setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|If a string it is assumed to be the contents of the attachment. If an array copy its values across.

a|`$mimeType`
|link:http://php.net/string[string^]
a|The MIME type of the attachment that will be used in the request. Defaults to application/octet-stream.
|===


[source%nowrap, php]
[#hasattachment]
----

public hasAttachment():bool

----







Helper method to check if an object has an attachment.

[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Helper method that returns an associative array of the object&#039;s properties and values.

[source%nowrap, php]
[#search]
----

public search($expression):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$expression`
|link:http://php.net/string[string^]
a|A valid JMESPath expression
|===


[source%nowrap, php]
[#setvalues]
----

public setValues($class, $values = []):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$class`
|link:http://php.net/string[string^]
a|The name of the class the properties belong to.

a|`$values`
|link:http://php.net/array[array^]
a|Associative array of property names and their values.
|===



[[market_types_uritype]]
==== URIType

The service for uri type.



===== Namespace

`Plenty\Modules\Market\Ebay\Api\Types`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|properties
    |
    a|
|xmlNamespaces
    |
    a|
|requestXmlRootElementNames
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($values = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$values`
|link:http://php.net/array[array^]
a|Optional properties and values to assign to the object.
|===


[source%nowrap, php]
[#getparentvalues]
----

public static getParentValues($properties, $values):array

----







Helper function to remove the properties and values that belong to a object&#039;s parent.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$properties`
|link:http://php.net/array[array^]
a|

a|`$values`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#__get]
----

public __get($name):void

----







PHP magic function that is called when getting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__set]
----

public __set($name, $value):void

----







PHP magic function that is called when setting a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.

a|`$value`
|
a|Value assigned to the property.
|===


[source%nowrap, php]
[#__isset]
----

public __isset($name):bool

----







PHP magic function that is called to determine if a property is set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#__unset]
----

public __unset($name):void

----







PHP magic function that is called to unset a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The property name.
|===


[source%nowrap, php]
[#torequestxml]
----

public toRequestXml():string

----







Converts the object to a XML request string.

[source%nowrap, php]
[#elementmeta]
----

public elementMeta($elementName):void

----







Returns the meta data for a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$elementName`
|link:http://php.net/string[string^]
a|The element name.
|===


[source%nowrap, php]
[#attachment]
----

public attachment($data = null, $mimeType = &quot;application/octet-stream&quot;):void

----







Method to get or set the object&#039;s attachment. Overrides any existing attachment is setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|If a string it is assumed to be the contents of the attachment. If an array copy its values across.

a|`$mimeType`
|link:http://php.net/string[string^]
a|The MIME type of the attachment that will be used in the request. Defaults to application/octet-stream.
|===


[source%nowrap, php]
[#hasattachment]
----

public hasAttachment():bool

----







Helper method to check if an object has an attachment.

[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Helper method that returns an associative array of the object&#039;s properties and values.

[source%nowrap, php]
[#search]
----

public search($expression):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$expression`
|link:http://php.net/string[string^]
a|A valid JMESPath expression
|===


[source%nowrap, php]
[#setvalues]
----

public setValues($class, $values = []):void

----







Assign multiple values to an object.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$class`
|link:http://php.net/string[string^]
a|The name of the class the properties belong to.

a|`$values`
|link:http://php.net/array[array^]
a|Associative array of property names and their values.
|===


[[market_auth]]
== Auth

[[market_auth_contracts]]
===  Contracts
[[market_contracts_authservicecontract]]
==== AuthServiceContract

The contract for the eBay authentication service.



===== Namespace

`Plenty\Modules\Market\Ebay\Auth\Contracts`






===== Methods

[source%nowrap, php]
[#refreshtokenbycredentialsid]
----

public refreshTokenByCredentialsId($credentialsId):void

----







Refresh credentials token and update.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$credentialsId`
|link:http://php.net/int[int^]
a|
|===


[[market_category]]
== Category

[[market_category_contracts]]
===  Contracts
[[market_contracts_categoryrepositorycontract]]
==== CategoryRepositoryContract

The contract for the Ebay category repository.



===== Namespace

`Plenty\Modules\Market\Ebay\Category\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id, $filters = [], $with = []):Plenty\Modules\Market\Ebay\Category\Models\Category

----




====== *Return type:*        xref:Market.adoc#market_models_category[`Category`]


Get category

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the category.

a|`$filters`
|link:http://php.net/array[array^]
a|The filters that could be applied: 'marketplaceId'.

a|`$with`
|link:http://php.net/array[array^]
a|The relations that should be loaded: 'path'
|===


[source%nowrap, php]
[#all]
----

public all($filters = [], $with = []):array

----







List all categories

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|Categories can be filtered by ID and marketplace ID. The filters that could be applied: 'marketplaceId', 'categoryId'.

a|`$with`
|link:http://php.net/array[array^]
a|The relations that should be loaded: 'path'
|===


[[market_category_models]]
===  Models
[[market_models_category]]
==== Category

The category model



===== Namespace

`Plenty\Modules\Market\Ebay\Category\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the category.
|parentId
    |link:http://php.net/int[int^]
    a|The parent category ID.
|name
    |link:http://php.net/string[string^]
    a|The name of the category.
|isLeaf
    |link:http://php.net/bool[bool^]
    a|Tells if the category is leaf.
|children
    |link:http://php.net/array[array^]
    a|Child categories.
|path
    |link:http://php.net/array[array^]
    a|The category path.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[market_itemspecific]]
== ItemSpecific

[[market_itemspecific_contracts]]
===  Contracts
[[market_contracts_itemspecificrepositorycontract]]
==== ItemSpecificRepositoryContract

The contract for the Ebay category repository.



===== Namespace

`Plenty\Modules\Market\Ebay\ItemSpecific\Contracts`






===== Methods

[source%nowrap, php]
[#all]
----

public all($filters = []):array

----







List item specifics.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|The filters that could be applied: 'categoryId', 'marketplaceId'.
|===


[[market_itemspecific_models]]
===  Models
[[market_models_itemspecific]]
==== ItemSpecific

The eBay item specific model.



===== Namespace

`Plenty\Modules\Market\Ebay\ItemSpecific\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|name
    |link:http://php.net/string[string^]
    a|A recommended Item Specific name.
|minValues
    |link:http://php.net/int[int^]
    a|Minimum number of values that you can specify for this Item Specific.
|maxValues
    |link:http://php.net/int[int^]
    a|Maximum number of values that you can specify for this Item Specific.
|selectionMode
    |link:http://php.net/string[string^]
    a|Controls whether you can specify your own name and value in listing requests, or if you need to use a name and/or value that eBay has defined.
|valueType
    |link:http://php.net/string[string^]
    a|The data type (e.g., date) that eBay expects the value to adhere to in listing requests. Only returned if the data type is not Text. In some cases, more details about the data type are returned in the `valueFormat` field.
|valueFormat
    |link:http://php.net/string[string^]
    a|The format of the data type (e.g., date format) that eBay expects the item specific's value to adhere to in listing requests. A data type identified by the `valueType` field may have different representations, and `valueFormat` specifies the precise format that is required.
|helpText
    |link:http://php.net/string[string^]
    a|Help-text defines the purpose of the Item Specific. The help text will be shown only when it is available for the particular Item Specific.
|helpUrl
    |link:http://php.net/string[string^]
    a|A page on the eBay Web site with context-specific help tips that provide useful information about this Item Specific. Only returned when an applicable page is available in the system.
|variationPicture
    |link:http://php.net/string[string^]
    a|Indicates whether the name (e.g., Color) can (or must) be used to classify the variation pictures
|variationSpecifics
    |link:http://php.net/string[string^]
    a|Indicates whether the recommended name/value pair can be used as variation attributes in a fixed-price listing call. For example, a given category could disable a name like Brand in variation specifics (if Brand is only allowed in the item specifics at the Item level). The same category could enable a name like Size for variation specifics (in addition to recommending it for item specifics). If not returned, then the name/value can be used for both variation specifics and item specifics.
|values
    |link:http://php.net/array[array^]
    a|The available values.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[market_marketplace]]
== Marketplace

[[market_marketplace_contracts]]
===  Contracts
[[market_contracts_marketplacerepositorycontract]]
==== MarketplaceRepositoryContract

The contract for the Ebay marketplace repository.



===== Namespace

`Plenty\Modules\Market\Ebay\Marketplace\Contracts`






===== Methods

[source%nowrap, php]
[#all]
----

public all($filters = []):array

----







Get the list of all available eBay marketplaces.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|You can pass multiple filters to search only custom marketplaces. Available filters: `referrerId`, `marketplaceId`, `marketId`, `siteId`.
|===


[source%nowrap, php]
[#allebay]
----

public allEbay($filters = []):array

----







Get the list of all available eBay marketplaces.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|You can pass multiple filters to search only custom marketplaces. Available filters: `referrerId`, `marketplaceId`, `marketId`, `siteId`.
|===


[[market_marketplace_helpers]]
===  Helpers
[[market_helpers_marketplacehelper]]
==== MarketplaceHelper

Helper class that allows getting information about an eBay marketplace more easily.



===== Namespace

`Plenty\Modules\Market\Ebay\Marketplace\Helpers`






===== Methods

[source%nowrap, php]
[#get]
----

public get($filters):Plenty\Modules\Market\Ebay\Marketplace\Models\Marketplace

----




====== *Return type:*        xref:Market.adoc#market_models_marketplace[`Marketplace`]


Get marketplace data model based on filters.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getmarketplaceid]
----

public getMarketplaceId($filters):string

----







Get the marketplace ID based on given filters. Possible filters: `marketplaceId`, `referrerId`, `marketId`, `siteId`.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getmarketplaceids]
----

public getMarketplaceIds():array

----







Get all available marketplace IDs.

[source%nowrap, php]
[#getreferrerid]
----

public getReferrerId($filters):string

----







Get the referrer ID based on given filters. Possible filters: `marketplaceId`, `referrerId`, `marketId`, `siteId`.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getreferrerids]
----

public getReferrerIds():array

----







Get all available referrer IDs.

[source%nowrap, php]
[#getsiteid]
----

public getSiteId($filters):string

----







Get the site ID based on given filters. Possible filters: `marketplaceId`, `referrerId`, `marketId`, `siteId`.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getsiteids]
----

public getSiteIds():array

----







Get all available site IDs.

[source%nowrap, php]
[#getmarketid]
----

public getMarketId($filters):string

----







Get the market ID based on given filters. Possible filters: `marketplaceId`, `referrerId`, `marketId`, `siteId`.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getmarketids]
----

public getMarketIds():array

----







Get all available market IDs.

[source%nowrap, php]
[#getcurrency]
----

public getCurrency($filters):string

----







Get the currency based on given filters. Possible filters: `marketplaceId`, `referrerId`, `marketId`, `siteId`.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getshortcut]
----

public getShortcut($filters):string

----







Get the shortcut based on given filters. Possible filters: `marketplaceId`, `referrerId`, `marketId`, `siteId`.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[[market_marketplace_models]]
===  Models
[[market_models_marketplace]]
==== Marketplace

The eBay marketplace model.



===== Namespace

`Plenty\Modules\Market\Ebay\Marketplace\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|siteId
    |link:http://php.net/int[int^]
    a|The ID of the site exactly as eBay specifies it in the docs. This value is/was used in the old eBay SOAP APIs
|marketplaceId
    |link:http://php.net/string[string^]
    a|The ID of the marketplace exactly as eBay specifies it in the docs. This value is used in the new eBay REST APIs. Eg. `EBAY_DE` or `EBAY-DE`
|marketId
    |link:http://php.net/int[int^]
    a|System-Listing wide internal ID for the listing marketplace. This id occurs only in correlation with the listing DB tables.
|referrerId
    |link:http://php.net/float[float^]
    a|System wide internal ID for the marketplace. Use this instead of `marketId` whenever possible!
|shortcut
    |link:http://php.net/string[string^]
    a|The marketplace shortcut name.
|currency
    |link:http://php.net/string[string^]
    a|The currency used for the marketplace
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[market_partsfitment]]
== PartsFitment

[[market_partsfitment_contracts]]
===  Contracts
[[market_contracts_fitmentitempropertyrepositorycontract]]
==== FitmentItemPropertyRepositoryContract

The contract for the fitment item property repository.



===== Namespace

`Plenty\Modules\Market\Ebay\PartsFitment\Contracts`






===== Methods

[source%nowrap, php]
[#find]
----

public find($id):Plenty\Modules\Market\Ebay\PartsFitment\Models\FitmentItemProperty

----




====== *Return type:*        xref:Market.adoc#market_models_fitmentitemproperty[`FitmentItemProperty`]


Returns a fitment item property by an ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the fitment item property that should be found.
|===


[source%nowrap, php]
[#create]
----

public create($data, $id):Plenty\Modules\Market\Ebay\PartsFitment\Models\FitmentItemProperty

----




====== *Return type:*        xref:Market.adoc#market_models_fitmentitemproperty[`FitmentItemProperty`]


Creates a new fitment item property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The fitment item property data as associative array.

a|`$id`
|link:http://php.net/int[int^]
a|The fitment item ID that the current property should belong to.
|===


[source%nowrap, php]
[#update]
----

public update($data, $id):Plenty\Modules\Market\Ebay\PartsFitment\Models\FitmentItem

----




====== *Return type:*        xref:Market.adoc#market_models_fitmentitem[`FitmentItem`]


Updates an existing fitment item property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The fitment item property data to update as associative array.

a|`$id`
|link:http://php.net/int[int^]
a|The ID of the fitment item property that should be updated.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a fitment item property. Returns `true` if the deletion was successful, otherwise `false`.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the fitment item property that should be deleted.
|===



[[market_contracts_fitmentitemrepositorycontract]]
==== FitmentItemRepositoryContract

The contract for the fitment item repository.



===== Namespace

`Plenty\Modules\Market\Ebay\PartsFitment\Contracts`






===== Methods

[source%nowrap, php]
[#find]
----

public find($id):Plenty\Modules\Market\Ebay\PartsFitment\Models\FitmentItem

----




====== *Return type:*        xref:Market.adoc#market_models_fitmentitem[`FitmentItem`]


Returns a fitment item by an ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The id of the fitment item that should be found.
|===


[source%nowrap, php]
[#create]
----

public create($data, $id):Plenty\Modules\Market\Ebay\PartsFitment\Models\FitmentItem

----




====== *Return type:*        xref:Market.adoc#market_models_fitmentitem[`FitmentItem`]


Creates a new fitment item.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The fitment item data as associative array.

a|`$id`
|link:http://php.net/int[int^]
a|The ID of the fitment that the current fitment item belongs to.
|===


[source%nowrap, php]
[#update]
----

public update($data, $id):Plenty\Modules\Market\Ebay\PartsFitment\Models\FitmentItem

----




====== *Return type:*        xref:Market.adoc#market_models_fitmentitem[`FitmentItem`]


Updates an existing fitment item.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The fitment item data to update as associative array.

a|`$id`
|link:http://php.net/int[int^]
a|The ID of the fitment item that should be updated.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a fitment item. Returns `true` if the deletion was successful, otherwise `false`.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the fitment item that should be deleted.
|===



[[market_contracts_fitmentrepositorycontract]]
==== FitmentRepositoryContract

The contract for the fitment repository.



===== Namespace

`Plenty\Modules\Market\Ebay\PartsFitment\Contracts`






===== Methods

[source%nowrap, php]
[#find]
----

public find($id, $with = []):Plenty\Modules\Market\Ebay\PartsFitment\Models\Fitment

----




====== *Return type:*        xref:Market.adoc#market_models_fitment[`Fitment`]


Returns a fitment by an ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the fitment that should be found.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the Fitment instance. The relations available are 'items', 'items.properties'.
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Market\Ebay\PartsFitment\Models\Fitment

----




====== *Return type:*        xref:Market.adoc#market_models_fitment[`Fitment`]


Creates a new fitment.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The fitment data as associative array.
|===


[source%nowrap, php]
[#update]
----

public update($data, $id):Plenty\Modules\Market\Ebay\PartsFitment\Models\Fitment

----




====== *Return type:*        xref:Market.adoc#market_models_fitment[`Fitment`]


Updates an existing fitment.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The fitment data to update as associative array.

a|`$id`
|link:http://php.net/int[int^]
a|The ID of the fitment that should be updated.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):Plenty\Repositories\Models\DeleteResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes a fitment. Returns `true` if the deletion was successful, otherwise `false`.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the fitment that should be deleted.
|===


[source%nowrap, php]
[#search]
----

public search($page = 1, $itemsPerPage = 50, $with = [], $filters = []):array

----







Search fitments

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to load in the Fitment instance. The relations available are 'items', 'items.properties'.

a|`$filters`
|link:http://php.net/array[array^]
a|The filters that could be applied: 'id', 'categoryId', 'marketId', 'name', 'property', 'propertyName', 'propertyValue'.
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[market_partsfitment_models]]
===  Models
[[market_models_fitment]]
==== Fitment

The fitment model. This can contain multiple FitmentItems models.



===== Namespace

`Plenty\Modules\Market\Ebay\PartsFitment\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The id of the fitment.
|marketId
    |link:http://php.net/int[int^]
    a|The id of the market the fitment belongs to.
|name
    |link:http://php.net/string[string^]
    a|The name of the fitment.
|categoryId
    |link:http://php.net/int[int^]
    a|The id of the category the fitment belongs to.
|items
    |link:http://php.net/array[array^]
    a|The list of the items that belong to the fitment.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_fitmentitem]]
==== FitmentItem

The fitment item model. This belongs to one fitment model and can contain multiple FitmentItemProperty models.



===== Namespace

`Plenty\Modules\Market\Ebay\PartsFitment\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The id of the item that belongs to the fitment.
|fitmentId
    |link:http://php.net/int[int^]
    a|The id of the fitment.
|fitment
    |        xref:Market.adoc#market_models_fitment[`Fitment`]
    a|The fitment this fitment item belongs to.
|properties
    |link:http://php.net/array[array^]
    a|A collection of this fitment item properties. Available names are 'Make', 'Model', 'Platform', 'Type', 'Production Period', 'Engine', 'FitmentComments', 'KType'.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[market_models_fitmentitemproperty]]
==== FitmentItemProperty

The fitment item property model. This bleongs to an FitmentItem model.



===== Namespace

`Plenty\Modules\Market\Ebay\PartsFitment\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the fitment item property.
|fitmentItemId
    |link:http://php.net/int[int^]
    a|The ID that the fitment item this property belongs to.
|name
    |link:http://php.net/string[string^]
    a|The name of the property
|value
    |link:http://php.net/string[string^]
    a|The value of the property.
|fitmentItem
    |        xref:Market.adoc#market_models_fitmentitem[`FitmentItem`]
    a|The fitment item this property belongs to.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[market_shopcategory]]
== ShopCategory

[[market_shopcategory_contracts]]
===  Contracts
[[market_contracts_shopcategoryrepositorycontract]]
==== ShopCategoryRepositoryContract

The contract for the eBay shop categories.



===== Namespace

`Plenty\Modules\Market\Ebay\ShopCategory\Contracts`






===== Methods

[source%nowrap, php]
[#all]
----

public all($credentialsId, $viewType = &quot;list&quot;):array

----







Returns a fitment by an ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$credentialsId`
|link:http://php.net/int[int^]
a|The credentials ID for whom we want to load the eBay shop categories.

a|`$viewType`
|link:http://php.net/string[string^]
a|How should the eBay shop categories be returned. Possible values: 'list' or 'tree'. Default is 'list'.
|===


[[market_transaction]]
== Transaction

[[market_transaction_contracts]]
===  Contracts
[[market_contracts_transactionrepositorycontract]]
==== TransactionRepositoryContract

The contract for the ebay transaction repository.



===== Namespace

`Plenty\Modules\Market\Ebay\Transaction\Contracts`






===== Methods

[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Market\Ebay\Transaction\Models\Transaction

----




====== *Return type:*        xref:Market.adoc#market_models_transaction[`Transaction`]


Gets a transaction.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the ebay transaction.
|===


[source%nowrap, php]
[#search]
----

public search($page = 1, $itemsPerPage = 50, $filters = []):array

----







Search ebay transactions

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of entries to be displayed per page. The default number of entries per page is 50.

a|`$filters`
|link:http://php.net/array[array^]
a|The filters that could be applied: 'orderId', 'externalOrderId'.
|===


[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[[market_transaction_models]]
===  Models
[[market_models_transaction]]
==== Transaction

The ebay transaction model.



===== Namespace

`Plenty\Modules\Market\Ebay\Transaction\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the transaction.
|orderId
    |link:http://php.net/int[int^]
    a|The ID of the plentymarkets order.
|market
    |link:http://php.net/string[string^]
    a|The market. Possible values are: 'ebay', 'hood', 'ricardo'
|externalListingId
    |link:http://php.net/string[string^]
    a|The ID of the external listing.
|credentialsId
    |link:http://php.net/string[string^]
    a|The ID of the credentials.
|buyerUserId
    |link:http://php.net/string[string^]
    a|The ID of the ebay buyer.
|feedback
    |link:http://php.net/int[int^]
    a|The feedback.
|transactionId
    |link:http://php.net/string[string^]
    a|The ID of the ebay transaction.
|endTime
    |
    a|The date that the item was bought.
|quantity
    |link:http://php.net/int[int^]
    a|The purchased quantity.
|title
    |link:http://php.net/string[string^]
    a|The title of the purchased item.
|price
    |link:http://php.net/float[float^]
    a|The price of the transaction.
|shippingAddressCountry
    |link:http://php.net/string[string^]
    a|The shipping address country.
|referrerId
    |link:http://php.net/int[int^]
    a|The ID of the order referrer.
|createdAt
    |
    a|The date that the transaction was created.
|notification
    |link:http://php.net/int[int^]
    a|Flag that indicates if the transaction import was by notification.
|orderRowId
    |link:http://php.net/int[int^]
    a|The ID of the order row.
|sku
    |link:http://php.net/string[string^]
    a|The SKU.
|lastUpdate
    |link:http://php.net/int[int^]
    a|The date that the transaction was last updated.
|externalOrderId
    |link:http://php.net/string[string^]
    a|The ID of the external order.
|externalReferenceNo
    |link:http://php.net/string[string^]
    a|The external reference number.
|cancelId
    |link:http://php.net/string[string^]
    a|The ID of the cancellation.
|isEbayPlus
    |link:http://php.net/string[string^]
    a|The transaction is ebay plus. Possible values are: 'YES', 'NO'.
|isClickAndCollect
    |link:http://php.net/string[string^]
    a|The transaction is click and collect. Possible values are: 'YES', 'NO'.
|extendedOrderId
    |link:http://php.net/string[string^]
    a|The extended order ID of eBay.
|importStatus
    |link:http://php.net/string[string^]
    a|The current status of the order. Possible values are: 'NEW', 'IN_PROGRESS' and 'DONE'. Default is 'NEW'.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[market_helper]]
== Helper

[[market_helper_contracts]]
===  Contracts
[[market_contracts_marketaccounthelperrepositorycontract]]
==== MarketAccountHelperRepositoryContract

The contract for the market account helper repository.



===== Namespace

`Plenty\Modules\Market\Helper\Contracts`






===== Methods

[source%nowrap, php]
[#listmarketaccounts]
----

public listMarketAccounts($marketId):array

----







List market accounts

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketId`
|link:http://php.net/float[float^]
a|
|===



[[market_contracts_marketattributehelperrepositorycontract]]
==== MarketAttributeHelperRepositoryContract

The contract for the market attribute helper repository.



===== Namespace

`Plenty\Modules\Market\Helper\Contracts`






===== Methods

[source%nowrap, php]
[#getattributename]
----

public getAttributeName($id, $lang):string

----







Returns the attribute name for the given attribute id

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getattributevaluename]
----

public getAttributeValueName($attributeId, $valueId, $lang):string

----







Returns the attribute value name for the given attribute value id

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$attributeId`
|link:http://php.net/int[int^]
a|

a|`$valueId`
|link:http://php.net/int[int^]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getattributenames]
----

public getAttributeNames($record, $lang = &quot;de&quot;, $delimiter = &quot;,&quot;):string

----







Returns all attribute names for the given language as a string delimited by the given delimiter.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$record`
|        xref:Item.adoc#item_models_record[`Record`]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|

a|`$delimiter`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getattributevaluesetshortfrontendname]
----

public getAttributeValueSetShortFrontendName($record, $lang = &quot;de&quot;, $delimiter = &quot;, &quot;, $attributeNameCombination = []):string

----







Returns the attribute value set short frontend name. Ex.: blue, XL

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$record`
|        xref:Item.adoc#item_models_record[`Record`]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|

a|`$delimiter`
|link:http://php.net/string[string^]
a|

a|`$attributeNameCombination`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getattributenameandvaluecombination]
----

public getAttributeNameAndValueCombination($attributeNames, $attributeValues, $delimiter = &quot;,&quot;):string

----







Returns the combination of attribute names with their attribute values.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$attributeNames`
|link:http://php.net/string[string^]
a|

a|`$attributeValues`
|link:http://php.net/string[string^]
a|

a|`$delimiter`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getvariationnameandattributenameandvaluecombination]
----

public getVariationNameAndAttributeNameAndValueCombination($record, $lang):string

----







Returns the name for a variation with all attribute names and attribute values. Ex.: T-Shirt (Size: L, Color: red)

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$record`
|        xref:Item.adoc#item_models_record[`Record`]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|
|===



[[market_contracts_marketcategoryhelperrepositorycontract]]
==== MarketCategoryHelperRepositoryContract

The contract for the market category helper repository.



===== Namespace

`Plenty\Modules\Market\Helper\Contracts`






===== Methods

[source%nowrap, php]
[#getcategorybranchname]
----

public getCategoryBranchName($branchId, $lang, $plentyId, $separator = &quot;&gt;&quot;):string

----







Returns the category bread crumbs as string for a given branchId, lang and plentyId

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$branchId`
|link:http://php.net/int[int^]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|

a|`$plentyId`
|link:http://php.net/int[int^]
a|

a|`$separator`
|link:http://php.net/string[string^]
a|default
|===



[[market_contracts_marketitemhelperrepositorycontract]]
==== MarketItemHelperRepositoryContract

The contract for the item helper repository.



===== Namespace

`Plenty\Modules\Market\Helper\Contracts`






===== Methods

[source%nowrap, php]
[#getexternalmanufacturername]
----

public getExternalManufacturerName($manufacturerId):string

----







Get the external manufacturer name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$manufacturerId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#generatesku]
----

public generateSku($variationId, $marketId, $accountId, $setLastExportedTimestamp):string

----







Generates or updates the sku

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$variationId`
|link:http://php.net/int[int^]
a|

a|`$marketId`
|link:http://php.net/float[float^]
a|

a|`$accountId`
|link:http://php.net/int[int^]
a|

a|`$setLastExportedTimestamp`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#getavailability]
----

public getAvailability($availabilityId, $lang, $returnAvailabilityName):string

----







Returns the availability name or the availability average days

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$availabilityId`
|link:http://php.net/int[int^]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|

a|`$returnAvailabilityName`
|link:http://php.net/bool[bool^]
a|
|===



[[market_contracts_marketpropertyhelperrepositorycontract]]
==== MarketPropertyHelperRepositoryContract

The contract for the market property helper repository.



===== Namespace

`Plenty\Modules\Market\Helper\Contracts`






===== Methods

[source%nowrap, php]
[#getmarketproperty]
----

public getMarketProperty($referrerId):array

----







Returns a list of the market properties

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$referrerId`
|link:http://php.net/float[float^]
a|
|===


[[market_settings]]
== Settings

[[market_settings_contracts]]
===  Contracts
[[market_contracts_settingsrepositorycontract]]
==== SettingsRepositoryContract

Use this interface to store and retrieve market specific settings.



===== Namespace

`Plenty\Modules\Market\Settings\Contracts`






===== Methods

[source%nowrap, php]
[#search]
----

public search($filters = [], $page, $itemsPerPage = \Plenty\Modules\Market\Settings\Models\Settings::MAX_ITEMS_PER_PAGE):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List settings.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|Settings can be filtered by ID, marketplace ID.

a|`$page`
|link:http://php.net/int[int^]
a|Current page of the response.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The requested amount of settings per result page.
|===


[source%nowrap, php]
[#create]
----

public create($marketplaceId, $type, $settings):Plenty\Modules\Market\Settings\Models\Settings

----




====== *Return type:*        xref:Market.adoc#market_models_settings[`Settings`]


Create market settings.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketplaceId`
|link:http://php.net/string[string^]
a|The marketplace ID that the settings belong to

a|`$type`
|link:http://php.net/string[string^]
a|The type of settings. Possible values: shipping, attribute, category, property.

a|`$settings`
|link:http://php.net/array[array^]
a|The settings that will be saved.
|===


[source%nowrap, php]
[#update]
----

public update($settingsData, $id):void

----







Update one market settings entry.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$settingsData`
|link:http://php.net/array[array^]
a|

a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Market\Settings\Models\Settings

----




====== *Return type:*        xref:Market.adoc#market_models_settings[`Settings`]


Return the settings for a given settings ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The settings id.
|===


[source%nowrap, php]
[#find]
----

public find($marketplaceId, $type = null):array

----







Find settings for a given marketplace ID and type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketplaceId`
|link:http://php.net/string[string^]
a|The marketplace id for which to retrieve the settings

a|`$type`
|link:http://php.net/string[string^]
a|The typo of settings that should be searched for. Possible values: shipping, attribute, category, property.
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Delete a setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#deleteall]
----

public deleteAll($marketplaceId, $type):void

----







Delete all settings for a given type and marketplace ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketplaceId`
|link:http://php.net/string[string^]
a|

a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[[market_settings_factories]]
===  Factories
[[market_factories_settingscorrelationfactory]]
==== SettingsCorrelationFactory

Factory that allows to store correlation between market settings and plentymarkets settings.



===== Namespace

`Plenty\Modules\Market\Settings\Factories`






===== Methods

[source%nowrap, php]
[#type]
----

public type($type):Plenty\Modules\Market\Settings\Factories\SettingsCorrelationFactory

----




====== *Return type:*        xref:Market.adoc#market_factories_settingscorrelationfactory[`SettingsCorrelationFactory`]


Set here the type of relation that should be created.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|The relation type. Possible values: shipping, attribute, category, property
|===


[source%nowrap, php]
[#createrelation]
----

public createRelation($settingsId, $correlationId):void

----







Use this method to create a relation of the chosen type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$settingsId`
|link:http://php.net/int[int^]
a|The id of the market settings we want to create the relation for.

a|`$correlationId`
|link:http://php.net/int[int^]
a|The id of the plentymarkets settings we want to create the relation to.
|===


[source%nowrap, php]
[#createrelationwithparent]
----

public createRelationWithParent($settingsId, $correlationId, $parentSettingsId):void

----







Use this method to create a relation of the chosen type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$settingsId`
|link:http://php.net/int[int^]
a|The id of the market settings we want to create the relation for.

a|`$correlationId`
|link:http://php.net/int[int^]
a|The id of the plentymarkets settings we want to create the relation to.

a|`$parentSettingsId`
|link:http://php.net/int[int^]
a|The id of the parent market settings we want to create the relation to.
|===


[source%nowrap, php]
[#clear]
----

public clear($marketplaceId):void

----







Clear all relations for a given correlation type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketplaceId`
|
a|
|===


[source%nowrap, php]
[#all]
----

public all($marketplaceId):array

----







Get all correlations for a given marketplace ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketplaceId`
|
a|
|===


[source%nowrap, php]
[#getsettingsbycorrelation]
----

public getSettingsByCorrelation($marketplaceId, $correlationId):void

----







Get a specific settings by marketplace id and correlation id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketplaceId`
|
a|

a|`$correlationId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getallsettingsbycorrelation]
----

public getAllSettingsByCorrelation($marketplaceId, $correlationId):void

----







Get a specific settings by marketplace id and correlation id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketplaceId`
|
a|

a|`$correlationId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getsettingsbycorrelationandparent]
----

public getSettingsByCorrelationAndParent($marketplaceId, $correlationId, $parentSettingsId):void

----







Get a specific settings by marketplace id and correlation id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketplaceId`
|
a|

a|`$correlationId`
|link:http://php.net/int[int^]
a|

a|`$parentSettingsId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getsettingsbyparent]
----

public getSettingsByParent($marketplaceId, $parentSettingsId):void

----







List settings by marketplace id and parent settings id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketplaceId`
|
a|

a|`$parentSettingsId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getallsettingsbycorrelationandparent]
----

public getAllSettingsByCorrelationAndParent($marketplaceId, $correlationId, $parentSettingsId):void

----







Get a specific settings by marketplace id and correlation id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$marketplaceId`
|
a|

a|`$correlationId`
|link:http://php.net/int[int^]
a|

a|`$parentSettingsId`
|link:http://php.net/int[int^]
a|
|===


[[market_settings_models]]
===  Models
[[market_models_settings]]
==== Settings

The market settings model.



===== Namespace

`Plenty\Modules\Market\Settings\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the market settings.
|marketplaceId
    |link:http://php.net/int[int^]
    a|The ID of the marketplace.
|type
    |link:http://php.net/string[string^]
    a|The type of the current market settings. Possible values are: attribute, attributeValue, property, category, shipping.
|settings
    |link:http://php.net/array[array^]
    a|The market settings for the current marketplace.
|category
    |link:http://php.net/array[array^]
    a|The category that these market settings are related to.
|parcelServicePreset
    |link:http://php.net/array[array^]
    a|The parcel service preset that these market settings are related to.
|attribute
    |link:http://php.net/array[array^]
    a|The attribute that these market settings are related to.
|property
    |link:http://php.net/array[array^]
    a|The property item that these market settings are related to.
|attributeValue
    |link:http://php.net/array[array^]
    a|The attributeValue that these market settings are related to.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[market_order]]
== Order

[[market_order_events]]
===  Events
[[market_events_beforeneworderitemcreationevent]]
==== BeforeNewOrderItemCreationEvent

Event which signals a new ebay order item before its creation.



===== Namespace

`Plenty\Modules\Market\Ebay\Order\Events`






===== Methods

[source%nowrap, php]
[#getdata]
----

public getData():void

----









[source%nowrap, php]
[#getwarehouseid]
----

public getWarehouseId():void

----









[source%nowrap, php]
[#setwarehouseid]
----

public setWarehouseId($warehouseId):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseId`
|link:http://php.net/int[int^]
a|
|===



[[market_events_orderitemevent]]
==== OrderItemEvent

Generic ebay order item event.



===== Namespace

`Plenty\Modules\Market\Ebay\Order\Events`






===== Methods

[source%nowrap, php]
[#getdata]
----

public getData():void

----









[source%nowrap, php]
[#getwarehouseid]
----

public getWarehouseId():void

----









[source%nowrap, php]
[#setwarehouseid]
----

public setWarehouseId($warehouseId):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseId`
|link:http://php.net/int[int^]
a|
|===


