

[[messenger_messenger]]
== Messenger

[[messenger_messenger_contracts]]
===  Contracts
[[messenger_contracts_messengerrepositorycontract]]
==== MessengerRepositoryContract

The MessengerRepositoryContract is the interface for the messenger repository. This interface defines methods to add and show/list messages.



===== Namespace

`Plenty\Modules\Messenger\Contracts`






===== Methods

[source%nowrap, php]
----

public add($data):Plenty\Modules\Messenger\Models\Message

----

    


====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Creates a new message.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The message data to be loaded
|===


[source%nowrap, php]
----

public show($uuid):void

----

    





Gets a message with all its successors.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID5 of the message
|===


[source%nowrap, php]
----

public list($uuid = null, $successors = true, $amount = self::DEFAULT_MESSAGES_AMOUNT):array

----

    





Lists messages. If no reference UUID5 is given, the method returns the $amount first messages. If $successor is set to FALSE, the messages older than the referenced message will be returned.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$uuid`
a|The reference UUID5 of the message to start from (excluding).
If not set, the uuid of the newest message will be used.

|link:http://php.net/bool[bool^]
a|`$successors`
a|If set to FALSE, the messages older than the referenced message will be returned.

|link:http://php.net/int[int^]
a|`$amount`
a|The amount of messages to list (defaults to 50)
|===


[source%nowrap, php]
----

public getMessages($page = self::DEFAULT_PAGE_OF_MESSAGES, $itemsPerPage = self::DEFAULT_ITEMS_PER_PAGE_OF_MESSAGES):array

----

    





Lists messages.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|The number of the returned page of messages, default is 1 (the first)

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The amount of messages to list (defaults to 50)
|===


[source%nowrap, php]
----

public updateReadBy($readBy, $uuid):void

----

    





Updates the readBy array of the message.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$readBy`
a|The ID of the user who read the message

|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID of the message
|===


[source%nowrap, php]
----

public updateTags($tags, $uuid):void

----

    





Updates the tags of the message.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$tags`
a|Array of tag IDs of the message

|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID of the message
|===


[source%nowrap, php]
----

public updateVisibility($data, $uuid):void

----

    





Updates the visibility of the message. Attributes that are updated are Message.visibility, Message.linkedTo and Message.accessFor.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The message with the data to be updated

|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID of the messages
|===


[source%nowrap, php]
----

public updateControls($data, $uuid):Plenty\Modules\Messenger\Models\Message

----

    


====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Updates the message ui control options in the message meta data and returns the message.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The controls data to be updated.

|link:http://php.net/string[string^]
a|`$uuid`
a|The uuid of the message.
|===


[source%nowrap, php]
----

public setDone($doneAt = null, $uuid):void

----

    





Sets the doneAt date in the message. If $doneAt is NULL, the doneAt date will be reset.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$doneAt`
a|The doneAt date as ISO date string

|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID of the message
|===


[source%nowrap, php]
----

public delete($uuid):int

----

    





Deletes a message stream by the UUID. Returns the count of messages deleted.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID of the message
|===


[source%nowrap, php]
----

public getAttachment($uuid, $filename):Plenty\Modules\Messenger\Models\Attachment

----

    


====== *Return type:*        xref:Messenger.adoc#messenger_models_attachment[`Attachment`]


Gets a message attachment.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID of the message

|link:http://php.net/string[string^]
a|`$filename`
a|The file name of the attachment
|===


[source%nowrap, php]
----

public updateMetaData($uuid, $metaData):Plenty\Modules\Messenger\Models\Message

----

    


====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Updates the meta data of the message.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID of the message

|link:http://php.net/array[array^]
a|`$metaData`
a|The meta data of the message
|===


[source%nowrap, php]
----

public getTotalEntries():int

----

    





Returns total message entries

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[[messenger_messenger_events]]
===  Events
[[messenger_events_messagecreated]]
==== MessageCreated

The event is triggered after a new message was created.



===== Namespace

`Plenty\Modules\Messenger\Events`






===== Methods

[source%nowrap, php]
----

public isFirstMessage():bool

----

    





If TRUE, the message is the first one. Otherwise, it is a reply message.

[source%nowrap, php]
----

public getMessage():Plenty\Modules\Messenger\Models\Message

----

    


====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Get the message.

[[messenger_messenger_models]]
===  Models
[[messenger_models_attachment]]
==== Attachment

The Attachment model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|name
    a|The file name of the attachment
|link:http://php.net/string[string^]
    a|message
    a|The UUID of the message the attachment belongs to
|link:http://php.net/int[int^]
    a|size
    a|The size of the attachment in bytes
|link:http://php.net/string[string^]
    a|contentType
    a|The content type fo the attachment
|link:http://php.net/string[string^]
    a|content
    a|The content of the attachment
|link:http://php.net/string[string^]
    a|createdAt
    a|The createdAt date of the attachment
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[messenger_models_message]]
==== Message

The Message model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|uuid
    a|The UUID5 identifier of the message
|link:http://php.net/string[string^]
    a|plentyIdHash
    a|The plenty ID hash
|link:http://php.net/string[string^]
    a|parentUuid
    a|The UUID5 of the parent message
|link:http://php.net/array[array^]
    a|linkedTo
    a|An array with MessageLinkedTo instances
|        xref:Messenger.adoc#messenger_models_messagefrom[`MessageFrom`]
    a|from
    a|The sender of the message as MessageFrom instance.
|        xref:Messenger.adoc#messenger_models_messageto[`MessageTo`]
    a|to
    a|The user and role IDs and emails receiving the message
|link:http://php.net/bool[bool^]
    a|whispered
    a|Whether the message is whispered (not visible for the contact/order linked to the message) or not
|link:http://php.net/array[array^]
    a|tags
    a|An array with tag IDs assigned to the message
|link:http://php.net/string[string^]
    a|title
    a|The title of the message
|link:http://php.net/string[string^]
    a|preview
    a|The first two lines of the message without any markup
|link:http://php.net/string[string^]
    a|message
    a|The content of the message
|link:http://php.net/int[int^]
    a|attachedFilesCount
    a|The amount of attached files (readonly)
|        xref:Messenger.adoc#messenger_models_messagereferrer[`MessageReferrer`]
    a|referrer
    a|The message referrer
|        xref:Messenger.adoc#messenger_models_messagemetadata[`MessageMetaData`]
    a|metaData
    a|The meta data of the message
|link:http://php.net/string[string^]
    a|doneAt
    a|The date the messages was set to done
|link:http://php.net/string[string^]
    a|createdAt
    a|The creation date of the message
|link:http://php.net/string[string^]
    a|updatedAt
    a|The date of the last update of the message
|link:http://php.net/string[string^]
    a|deletedAt
    a|The date the message was deleted
|link:http://php.net/int[int^]
    a|deletedBy
    a|The ID of the user who deleted the message
|link:http://php.net/array[array^]
    a|attachments
    a|The message attachments
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[messenger_models_messagefrom]]
==== MessageFrom

The MessageFrom model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|type
    a|The type of the from instance (one of {@link MessageTypesService::FROM_TYPE_USER},
{@link MessageTypesService::FROM_TYPE_CONTACT} and {@link MessageTypesService::FROM_TYPE_EMAIL})
|
    a|value
    a|The value of the instance. For type {@link MessageTypesService::FROM_TYPE_EMAIL} it is a string (the email)
and the id of the user or the contact otherwise.
|link:http://php.net/string[string^]
    a|name
    a|An optional name for the instance, e.g. the real name for type {@link MessageTypesService::FROM_TYPE_EMAIL}
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[messenger_models_messagelinkedto]]
==== MessageLinkedTo

The MessageLinkedTo model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|type
    a|The type of the link (one of {@link MessageTypesService::LINKED_TO_TYPE_MESSAGE},
{@link MessageTypesService::LINKED_TO_TYPE_ORDER}, {@link MessageTypesService::LINKED_TO_TYPE_CONTACT}
and {@link MessageTypesService::LINKED_TO_TYPE_PAYMENT})
|
    a|value
    a|The value of the link. For type {@link MessageTypesService::LINKED_TO_TYPE_MESSAGE} it is a string (uuid5)
and an integer otherwise.
|
    a|typeId
    a|This can be the ID of a sub-type (e.g. the order subTypeId). (optional)
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[messenger_models_messagemetadata]]
==== MessageMetaData

The MessageMetaData model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/array[array^]
    a|readBy
    a|The array of users
|link:http://php.net/array[array^]
    a|links
    a|Array with links
|        xref:Messenger.adoc#messenger_models_messagemetadatanotdone[`MessageMetaDataNotDone`]
    a|notDoneByBackend
    a|deactivates the toggle button in the messenger ui (backend) also has optional tooltips (reason for the deactivated toggle)
|        xref:Messenger.adoc#messenger_models_messagemetadatacontrols[`MessageMetaDataControls`]
    a|controls
    a|An object with control options for the ui.
|        xref:Messenger.adoc#messenger_models_messagemetadatatimecapture[`MessageMetaDataTimeCapture`]
    a|timeCapture
    a|An object of the message time capture data
|link:http://php.net/int[int^]
    a|plentyId
    a|the plenty id of the related contact
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[messenger_models_messagemetadatacontrols]]
==== MessageMetaDataControls

The message controls model. Currently supported controls:
 * &lt;ul&gt;
 * &lt;li&gt;&lt;tt&gt;bool replyable&lt;/tt&gt;
 *      Indicates whether or not is allowed to reply to this message stream (default true).
 *      It is a global control and effects only in the parent message of a stream.&lt;/li&gt;
 * &lt;li&gt;&lt;tt&gt;bool attachable&lt;/tt&gt;
 *      Indicates whether or not is allowed to attach files in a message (default true).
 *      It is a global control and effects only in the parent message of a stream.&lt;/li&gt;
 * &lt;li&gt;&lt;tt&gt;bool linksDisabled&lt;/tt&gt;
 *      Indicates whether or not the message links should be disabled (default false).
 *      It is a loacal control and effects every message.&lt;/li&gt;
 * &lt;/ul&gt;



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/bool[bool^]
    a|replyable
    a|Indicates whether or not is allowed to reply to this message stream (default true).
|link:http://php.net/bool[bool^]
    a|attachable
    a|Indicates whether or not is allowed to attach files in a message (default true).
|link:http://php.net/bool[bool^]
    a|linksDisabled
    a|Indicates whether or not the message links should be disabled (default false).
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[messenger_models_messagemetadatanotdone]]
==== MessageMetaDataNotDone

The MessageMetaDataNotDone model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/bool[bool^]
    a|deactivated
    a|Deactivates the toggle button for the UI
|link:http://php.net/array[array^]
    a|tooltips
    a|Tooltips for the UI to show why the toggle is deactivated (if not set, show default values)
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[messenger_models_messagemetadatatimecapture]]
==== MessageMetaDataTimeCapture

The MessageMetaDataTimeCapture model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/bool[bool^]
    a|chargeable
    a|
|link:http://php.net/int[int^]
    a|minutes
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[messenger_models_messagemetalink]]
==== MessageMetaLink

The MessageMetaLink model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|image
    a|An optional image URL for the link
|link:http://php.net/string[string^]
    a|caption
    a|The caption to be shown for the link
|link:http://php.net/string[string^]
    a|url
    a|The link URL
<ul>
    <li>for {@link MessageMetaLink::TYPE_MAILTO} the email</li>
    <li>for {@link MessageMetaLink::TYPE_URL} the complete URL with protocol</li>
    <li>for {@link MessageMetaLink::TYPE_PLUGIN} the relative route to the backend</li>
    <li>not needed for {@link MessageMetaLink::TYPE_REPLY}</li>
</ul>
|link:http://php.net/string[string^]
    a|type
    a|One of the constants:
<ul>
    <li>{@link MessageMetaLink::TYPE_MAILTO}</li>
    <li>{@link MessageMetaLink::TYPE_URL}</li>
    <li>{@link MessageMetaLink::TYPE_PLUGIN}</li>
    <li>{@link MessageMetaLink::TYPE_REPLY}</li>
</ul>
|link:http://php.net/string[string^]
    a|content
    a|The reply content, only needed for type {@link MessageMetaLink::TYPE_REPLY}
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[messenger_models_messagereferrer]]
==== MessageReferrer

The MessageReferrer model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|type
    a|The type of the from instance (one of {@link MessageTypesService::REFERRER_TYPE_SYSTEM},
{@link MessageTypesService::REFERRER_TYPE_BACKEND}, {@link MessageTypesService::REFERRER_TYPE_REST}
and {@link MessageTypesService::REFERRER_TYPE_PLUGIN})
|
    a|value
    a|The value of the instance. It is an integer (the user id) for type
{@link MessageTypesService::REFERRER_TYPE_SYSTEM}, {@link MessageTypesService::REFERRER_TYPE_BACKEND}
and {@link MessageTypesService::REFERRER_TYPE_REST} and a string (the plugin name) for type
{@link MessageTypesService::REFERRER_TYPE_PLUGIN}.
|link:http://php.net/string[string^]
    a|name
    a|An optional name for the instance. For type {@link MessageTypesService::REFERRER_TYPE_PLUGIN} it is
the plugin namespace, the user name otherwise.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[messenger_models_messageto]]
==== MessageTo

The MessageTo model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/array[array^]
    a|user
    a|An array with user IDs of users receiving the message
|link:http://php.net/array[array^]
    a|role
    a|An array with user role IDs of user roles receiving the message
|link:http://php.net/array[array^]
    a|email
    a|An array with emails receiving the message
|link:http://php.net/bool[bool^]
    a|allUsers
    a|Flag indicating that all system users receive the message
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[messenger_messenger_services]]
===  Services
[[messenger_services_messagetypesservice]]
==== MessageTypesService

Types and type validation for several types in the messenger.



===== Namespace

`Plenty\Modules\Messenger\Services`






===== Methods

[source%nowrap, php]
----

public static getValidLinkedToTypes():array

----

    





Gets the valid types for &quot;linked to&quot; references.

[source%nowrap, php]
----

public static isValidLinkedTo($linkType, $linkValue):bool

----

    





Checks whether the given link is valid or not.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$linkType`
a|The link type

|
a|`$linkValue`
a|The link value
|===


[source%nowrap, php]
----

public static getValidFromTypes():array

----

    





Gets the valid types for &quot;from&quot; references.

[source%nowrap, php]
----

public static isValidFrom($fromType, $fromValue):bool

----

    





Checks whether the given from is valid or not.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$fromType`
a|The from type

|
a|`$fromValue`
a|The from value
|===


[source%nowrap, php]
----

public static getValidReferrerTypes():array

----

    





Gets the valid types for &quot;referrer&quot; references.

[source%nowrap, php]
----

public static isValidReferrer($referrerType, $referrerValue, $referrerName = null):bool

----

    





Checks whether the given referrer reference is valid or not.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$referrerType`
a|The reference to be checked

|
a|`$referrerValue`
a|The value of the reference

|link:http://php.net/string[string^]
a|`$referrerName`
a|The name of the reference
|===


[source%nowrap, php]
----

public static getValidToTypes():array

----

    





Gets the valid key types for the &#039;to&#039; array.

[source%nowrap, php]
----

public static isValidTo($toKey):bool

----

    





Checks whether the given key has a valid value for to.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$toKey`
a|The to key
|===



[[messenger_services_messagessearchservice]]
==== MessagesSearchService

Search service for the messenger.



===== Namespace

`Plenty\Modules\Messenger\Services`






===== Methods

[source%nowrap, php]
----

public find($uuid):Plenty\Modules\Messenger\Models\Message

----

    


====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Gets the message with the given uuid.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID of the message
|===


[source%nowrap, php]
----

public findOrFail($uuid):Plenty\Modules\Messenger\Models\Message

----

    


====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Gets the message with the given UUID.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID of the message
|===


[source%nowrap, php]
----

public findMany($uuid):array

----

    





Gets a stream of messages. The given UUID can be the UUID of the first message in the stream or one of the replied messages.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$uuid`
a|The UUID of the message
|===


[source%nowrap, php]
----

public navigate($page = 1, $itemsPerPage = 50):array

----

    





Lists the messages for the given navigation page.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|The page of results to search for

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items to list per page
|===


[source%nowrap, php]
----

public getTotalEntries():int

----

    





Returns total entries

[source%nowrap, php]
----

public toArray():array

----

    







[source%nowrap, php]
----

public process($data):array

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public getFilter():array

----

    







[source%nowrap, php]
----

public getPostFilter():array

----

    







[source%nowrap, php]
----

public getQuery():array

----

    







[source%nowrap, php]
----

public getAggregations():array

----

    







[source%nowrap, php]
----

public getSuggestions():array

----

    







[source%nowrap, php]
----

public getSources():void

----

    







[source%nowrap, php]
----

public addDependenciesToSource($sources):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$sources`
a|
|===


[source%nowrap, php]
----

public getName():void

----

    







[source%nowrap, php]
----

public setName($name):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$name`
a|
|===


[source%nowrap, php]
----

public setIsSourceDisabled($isSourceDisabled):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$isSourceDisabled`
a|
|===


[source%nowrap, php]
----

public addFilter($filter):Plenty\Modules\Cloud\ElasticSearch\Lib\Search

----

    


====== *Return type:*        xref:Cloud.adoc#cloud_lib_search[`Search`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|`$filter`
a|
|===


[source%nowrap, php]
----

public addPostFilter($filter):Plenty\Modules\Cloud\ElasticSearch\Lib\Search

----

    


====== *Return type:*        xref:Cloud.adoc#cloud_lib_search[`Search`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|`$filter`
a|
|===


[source%nowrap, php]
----

public addQuery($query):Plenty\Modules\Cloud\ElasticSearch\Lib\Search

----

    


====== *Return type:*        xref:Cloud.adoc#cloud_lib_search[`Search`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|`$query`
a|
|===


[source%nowrap, php]
----

public addSource($source):Plenty\Modules\Cloud\ElasticSearch\Lib\Search

----

    


====== *Return type:*        xref:Cloud.adoc#cloud_lib_search[`Search`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_source_sourceinterface[`SourceInterface`]
a|`$source`
a|
|===


[source%nowrap, php]
----

public setSorting($sorting):Plenty\Modules\Cloud\ElasticSearch\Lib\Search

----

    


====== *Return type:*        xref:Cloud.adoc#cloud_lib_search[`Search`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_sorting_sortinginterface[`SortingInterface`]
a|`$sorting`
a|
|===


[source%nowrap, php]
----

public addAggregation($aggregation):Plenty\Modules\Cloud\ElasticSearch\Lib\Search

----

    


====== *Return type:*        xref:Cloud.adoc#cloud_lib_search[`Search`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_aggregation_aggregationinterface[`AggregationInterface`]
a|`$aggregation`
a|
|===


[source%nowrap, php]
----

public addSuggestion($suggestion):Plenty\Modules\Cloud\ElasticSearch\Lib\Search

----

    


====== *Return type:*        xref:Cloud.adoc#cloud_lib_search[`Search`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_suggestion_suggestioninterface[`SuggestionInterface`]
a|`$suggestion`
a|
|===


[source%nowrap, php]
----

public setPage($page, $rowsPerPage):Plenty\Modules\Cloud\ElasticSearch\Lib\Search

----

    


====== *Return type:*        xref:Cloud.adoc#cloud_lib_search[`Search`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|

|link:http://php.net/int[int^]
a|`$rowsPerPage`
a|
|===


[source%nowrap, php]
----

public setPagination($pagination):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$pagination`
a|
|===


[source%nowrap, php]
----

public setCollapse($collapse):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_collapse_collapseinterface[`CollapseInterface`]
a|`$collapse`
a|
|===


[source%nowrap, php]
----

public setScoreModifier($scoreModifier):Plenty\Modules\Cloud\ElasticSearch\Lib\Search

----

    


====== *Return type:*        xref:Cloud.adoc#cloud_lib_search[`Search`]




.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_scoremodifier_scoremodifierinterface[`ScoreModifierInterface`]
a|`$scoreModifier`
a|
|===


[source%nowrap, php]
----

public setMaxResultWindow($maxResults = 10000):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$maxResults`
a|
|===


[source%nowrap, php]
----

public setIndex($index):void

----

    







.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$index`
a|
|===


[source%nowrap, php]
----

public isSearchAfter():void

----

    







[source%nowrap, php]
----

public getFilterRaw():void

----

    







[source%nowrap, php]
----

public getQueriesRaw():void

----

    







[source%nowrap, php]
----

public getAggregationsRaw():array

----

    







[source%nowrap, php]
----

public getSorting():void

----

    







[source%nowrap, php]
----

public getScoreModifier():void

----

    







