:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[messenger_messenger]]
== Messenger

[[messenger_messenger_contracts]]
===  Contracts
[[messenger_contracts_messengerrepositorycontract]]
==== MessengerRepositoryContract

The MessengerRepositoryContract is the interface for the messenger repository. This interface defines methods to add and show/list messages.



===== Namespace

`Plenty\Modules\Messenger\Contracts`






===== Methods

[source%nowrap, php]
[#add]
----

public add($data):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Creates a new message.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The message data to be loaded
|===


[source%nowrap, php]
[#show]
----

public show($uuid):void

----







Gets a message with all its successors.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID5 of the message
|===


[source%nowrap, php]
[#list]
----

public list($uuid = null, $successors = true, $amount = self::DEFAULT_MESSAGES_AMOUNT):array

----







Lists messages. If no reference UUID5 is given, the method returns the $amount first messages. If $successor is set to FALSE, the messages older than the referenced message will be returned.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The reference UUID5 of the message to start from (excluding).
If not set, the uuid of the newest message will be used.

a|`$successors`
|link:http://php.net/bool[bool^]
a|If set to FALSE, the messages older than the referenced message will be returned.

a|`$amount`
|link:http://php.net/int[int^]
a|The amount of messages to list (defaults to 50)
|===


[source%nowrap, php]
[#getmessages]
----

public getMessages($page = self::DEFAULT_PAGE_OF_MESSAGES, $itemsPerPage = self::DEFAULT_ITEMS_PER_PAGE_OF_MESSAGES):array

----







Lists messages.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The number of the returned page of messages, default is 1 (the first)

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The amount of messages to list (defaults to 50)
|===


[source%nowrap, php]
[#updatereadby]
----

public updateReadBy($readBy, $uuid):void

----







Updates the readBy array of the message.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$readBy`
|link:http://php.net/int[int^]
a|The ID of the user who read the message

a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#updatetags]
----

public updateTags($tags, $uuid):void

----







Updates the tags of the message.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tags`
|link:http://php.net/array[array^]
a|Array of tag IDs of the message

a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#updatevisibility]
----

public updateVisibility($data, $uuid):void

----







Updates the visibility of the message. Attributes that are updated are Message.visibility, Message.linkedTo and Message.accessFor.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The message with the data to be updated

a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the messages
|===


[source%nowrap, php]
[#updatecontrols]
----

public updateControls($data, $uuid):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Updates the message ui control options in the message meta data and returns the message.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The controls data to be updated.

a|`$uuid`
|link:http://php.net/string[string^]
a|The uuid of the message.
|===


[source%nowrap, php]
[#setdone]
----

public setDone($doneAt = null, $uuid):void

----







Sets the doneAt date in the message. If $doneAt is NULL, the doneAt date will be reset.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$doneAt`
|link:http://php.net/string[string^]
a|The doneAt date as ISO date string

a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#delete]
----

public delete($uuid):int

----







Deletes a message stream by the UUID. Returns the count of messages deleted.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#getattachment]
----

public getAttachment($uuid, $filename):Plenty\Modules\Messenger\Models\Attachment

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_attachment[`Attachment`]


Gets a message attachment.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message

a|`$filename`
|link:http://php.net/string[string^]
a|The file name of the attachment
|===


[source%nowrap, php]
[#updatemetadata]
----

public updateMetaData($uuid, $metaData):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Updates the meta data of the message.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message

a|`$metaData`
|link:http://php.net/array[array^]
a|The meta data of the message
|===


[source%nowrap, php]
[#gettotalentries]
----

public getTotalEntries():int

----







Returns total message entries

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[messenger_messenger_events]]
===  Events
[[messenger_events_messagecreated]]
==== MessageCreated

The event is triggered after a new message was created.



===== Namespace

`Plenty\Modules\Messenger\Events`






===== Methods

[source%nowrap, php]
[#isfirstmessage]
----

public isFirstMessage():bool

----







If TRUE, the message is the first one. Otherwise, it is a reply message.

[source%nowrap, php]
[#getmessage]
----

public getMessage():Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Get the message.

[[messenger_messenger_models]]
===  Models
[[messenger_models_attachment]]
==== Attachment

The Attachment model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|name
    |link:http://php.net/string[string^]
    a|The file name of the attachment
|message
    |link:http://php.net/string[string^]
    a|The UUID of the message the attachment belongs to
|size
    |link:http://php.net/int[int^]
    a|The size of the attachment in bytes
|contentType
    |link:http://php.net/string[string^]
    a|The content type fo the attachment
|content
    |link:http://php.net/string[string^]
    a|The content of the attachment
|createdAt
    |link:http://php.net/string[string^]
    a|The createdAt date of the attachment
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_message]]
==== Message

The Message model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|uuid
    |link:http://php.net/string[string^]
    a|The UUID5 identifier of the message
|plentyIdHash
    |link:http://php.net/string[string^]
    a|The plenty ID hash
|parentUuid
    |link:http://php.net/string[string^]
    a|The UUID5 of the parent message
|linkedTo
    |link:http://php.net/array[array^]
    a|An array with MessageLinkedTo instances
|from
    |        xref:Messenger.adoc#messenger_models_messagefrom[`MessageFrom`]
    a|The sender of the message as MessageFrom instance.
|to
    |        xref:Messenger.adoc#messenger_models_messageto[`MessageTo`]
    a|The user and role IDs and emails receiving the message
|whispered
    |link:http://php.net/bool[bool^]
    a|Whether the message is whispered (not visible for the contact/order linked to the message) or not
|tags
    |link:http://php.net/array[array^]
    a|An array with tag IDs assigned to the message
|title
    |link:http://php.net/string[string^]
    a|The title of the message
|preview
    |link:http://php.net/string[string^]
    a|The first two lines of the message without any markup
|message
    |link:http://php.net/string[string^]
    a|The content of the message
|attachedFilesCount
    |link:http://php.net/int[int^]
    a|The amount of attached files (readonly)
|referrer
    |        xref:Messenger.adoc#messenger_models_messagereferrer[`MessageReferrer`]
    a|The message referrer
|metaData
    |        xref:Messenger.adoc#messenger_models_messagemetadata[`MessageMetaData`]
    a|The meta data of the message
|doneAt
    |link:http://php.net/string[string^]
    a|The date the messages was set to done
|createdAt
    |link:http://php.net/string[string^]
    a|The creation date of the message
|updatedAt
    |link:http://php.net/string[string^]
    a|The date of the last update of the message
|deletedAt
    |link:http://php.net/string[string^]
    a|The date the message was deleted
|deletedBy
    |link:http://php.net/int[int^]
    a|The ID of the user who deleted the message
|attachments
    |link:http://php.net/array[array^]
    a|The message attachments
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagefrom]]
==== MessageFrom

The MessageFrom model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|type
    |link:http://php.net/string[string^]
    a|The type of the from instance (one of {@link MessageTypesService::FROM_TYPE_USER},
{@link MessageTypesService::FROM_TYPE_CONTACT} and {@link MessageTypesService::FROM_TYPE_EMAIL})
|value
    |
    a|The value of the instance. For type {@link MessageTypesService::FROM_TYPE_EMAIL} it is a string (the email)
and the id of the user or the contact otherwise.
|name
    |link:http://php.net/string[string^]
    a|An optional name for the instance, e.g. the real name for type {@link MessageTypesService::FROM_TYPE_EMAIL}
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagelinkedto]]
==== MessageLinkedTo

The MessageLinkedTo model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|type
    |link:http://php.net/string[string^]
    a|The type of the link (one of {@link MessageTypesService::LINKED_TO_TYPE_MESSAGE},
{@link MessageTypesService::LINKED_TO_TYPE_ORDER}, {@link MessageTypesService::LINKED_TO_TYPE_CONTACT}
and {@link MessageTypesService::LINKED_TO_TYPE_PAYMENT})
|value
    |
    a|The value of the link. For type {@link MessageTypesService::LINKED_TO_TYPE_MESSAGE} it is a string (uuid5)
and an integer otherwise.
|typeId
    |
    a|This can be the ID of a sub-type (e.g. the order subTypeId). (optional)
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagemetadata]]
==== MessageMetaData

The MessageMetaData model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|readBy
    |link:http://php.net/array[array^]
    a|The array of users
|links
    |link:http://php.net/array[array^]
    a|Array with links
|notDoneByBackend
    |        xref:Messenger.adoc#messenger_models_messagemetadatanotdone[`MessageMetaDataNotDone`]
    a|deactivates the toggle button in the messenger ui (backend) also has optional tooltips (reason for the deactivated toggle)
|controls
    |        xref:Messenger.adoc#messenger_models_messagemetadatacontrols[`MessageMetaDataControls`]
    a|An object with control options for the ui.
|timeCapture
    |        xref:Messenger.adoc#messenger_models_messagemetadatatimecapture[`MessageMetaDataTimeCapture`]
    a|An object of the message time capture data
|plentyId
    |link:http://php.net/int[int^]
    a|the plenty id of the related contact
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagemetadatacontrols]]
==== MessageMetaDataControls

The message controls model. Currently supported controls:
 * &lt;ul&gt;
 * &lt;li&gt;&lt;tt&gt;bool replyable&lt;/tt&gt;
 *      Indicates whether or not is allowed to reply to this message stream (default true).
 *      It is a global control and effects only in the parent message of a stream.&lt;/li&gt;
 * &lt;li&gt;&lt;tt&gt;bool attachable&lt;/tt&gt;
 *      Indicates whether or not is allowed to attach files in a message (default true).
 *      It is a global control and effects only in the parent message of a stream.&lt;/li&gt;
 * &lt;li&gt;&lt;tt&gt;bool linksDisabled&lt;/tt&gt;
 *      Indicates whether or not the message links should be disabled (default false).
 *      It is a loacal control and effects every message.&lt;/li&gt;
 * &lt;/ul&gt;



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|replyable
    |link:http://php.net/bool[bool^]
    a|Indicates whether or not is allowed to reply to this message stream (default true).
|attachable
    |link:http://php.net/bool[bool^]
    a|Indicates whether or not is allowed to attach files in a message (default true).
|linksDisabled
    |link:http://php.net/bool[bool^]
    a|Indicates whether or not the message links should be disabled (default false).
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagemetadatanotdone]]
==== MessageMetaDataNotDone

The MessageMetaDataNotDone model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|deactivated
    |link:http://php.net/bool[bool^]
    a|Deactivates the toggle button for the UI
|tooltips
    |link:http://php.net/array[array^]
    a|Tooltips for the UI to show why the toggle is deactivated (if not set, show default values)
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagemetadatatimecapture]]
==== MessageMetaDataTimeCapture

The MessageMetaDataTimeCapture model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|chargeable
    |link:http://php.net/bool[bool^]
    a|
|minutes
    |link:http://php.net/int[int^]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagemetalink]]
==== MessageMetaLink

The MessageMetaLink model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|image
    |link:http://php.net/string[string^]
    a|An optional image URL for the link
|caption
    |link:http://php.net/string[string^]
    a|The caption to be shown for the link
|url
    |link:http://php.net/string[string^]
    a|The link URL
<ul>
    <li>for {@link MessageMetaLink::TYPE_MAILTO} the email</li>
    <li>for {@link MessageMetaLink::TYPE_URL} the complete URL with protocol</li>
    <li>for {@link MessageMetaLink::TYPE_PLUGIN} the relative route to the backend</li>
    <li>not needed for {@link MessageMetaLink::TYPE_REPLY}</li>
</ul>
|type
    |link:http://php.net/string[string^]
    a|One of the constants:
<ul>
    <li>{@link MessageMetaLink::TYPE_MAILTO}</li>
    <li>{@link MessageMetaLink::TYPE_URL}</li>
    <li>{@link MessageMetaLink::TYPE_PLUGIN}</li>
    <li>{@link MessageMetaLink::TYPE_REPLY}</li>
</ul>
|content
    |link:http://php.net/string[string^]
    a|The reply content, only needed for type {@link MessageMetaLink::TYPE_REPLY}
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagereferrer]]
==== MessageReferrer

The MessageReferrer model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|type
    |link:http://php.net/string[string^]
    a|The type of the from instance (one of {@link MessageTypesService::REFERRER_TYPE_SYSTEM},
{@link MessageTypesService::REFERRER_TYPE_BACKEND}, {@link MessageTypesService::REFERRER_TYPE_REST}
and {@link MessageTypesService::REFERRER_TYPE_PLUGIN})
|value
    |
    a|The value of the instance. It is an integer (the user id) for type
{@link MessageTypesService::REFERRER_TYPE_SYSTEM}, {@link MessageTypesService::REFERRER_TYPE_BACKEND}
and {@link MessageTypesService::REFERRER_TYPE_REST} and a string (the plugin name) for type
{@link MessageTypesService::REFERRER_TYPE_PLUGIN}.
|name
    |link:http://php.net/string[string^]
    a|An optional name for the instance. For type {@link MessageTypesService::REFERRER_TYPE_PLUGIN} it is
the plugin namespace, the user name otherwise.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messageto]]
==== MessageTo

The MessageTo model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|user
    |link:http://php.net/array[array^]
    a|An array with user IDs of users receiving the message
|role
    |link:http://php.net/array[array^]
    a|An array with user role IDs of user roles receiving the message
|email
    |link:http://php.net/array[array^]
    a|An array with emails receiving the message
|allUsers
    |link:http://php.net/bool[bool^]
    a|Flag indicating that all system users receive the message
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[messenger_messenger_services]]
===  Services
[[messenger_services_messagetypesservice]]
==== MessageTypesService

Types and type validation for several types in the messenger.



===== Namespace

`Plenty\Modules\Messenger\Services`






===== Methods

[source%nowrap, php]
[#getvalidlinkedtotypes]
----

public static getValidLinkedToTypes():array

----







Gets the valid types for &quot;linked to&quot; references.

[source%nowrap, php]
[#isvalidlinkedto]
----

public static isValidLinkedTo($linkType, $linkValue):bool

----







Checks whether the given link is valid or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$linkType`
|link:http://php.net/string[string^]
a|The link type

a|`$linkValue`
|
a|The link value
|===


[source%nowrap, php]
[#getvalidfromtypes]
----

public static getValidFromTypes():array

----







Gets the valid types for &quot;from&quot; references.

[source%nowrap, php]
[#isvalidfrom]
----

public static isValidFrom($fromType, $fromValue):bool

----







Checks whether the given from is valid or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fromType`
|link:http://php.net/string[string^]
a|The from type

a|`$fromValue`
|
a|The from value
|===


[source%nowrap, php]
[#getvalidreferrertypes]
----

public static getValidReferrerTypes():array

----







Gets the valid types for &quot;referrer&quot; references.

[source%nowrap, php]
[#isvalidreferrer]
----

public static isValidReferrer($referrerType, $referrerValue, $referrerName = null):bool

----







Checks whether the given referrer reference is valid or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$referrerType`
|link:http://php.net/string[string^]
a|The reference to be checked

a|`$referrerValue`
|
a|The value of the reference

a|`$referrerName`
|link:http://php.net/string[string^]
a|The name of the reference
|===


[source%nowrap, php]
[#getvalidtotypes]
----

public static getValidToTypes():array

----







Gets the valid key types for the &#039;to&#039; array.

[source%nowrap, php]
[#isvalidto]
----

public static isValidTo($toKey):bool

----







Checks whether the given key has a valid value for to.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$toKey`
|link:http://php.net/string[string^]
a|The to key
|===



[[messenger_services_messagessearchservice]]
==== MessagesSearchService

Search service for the messenger.



===== Namespace

`Plenty\Modules\Messenger\Services`






===== Methods

[source%nowrap, php]
[#find]
----

public find($uuid):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Gets the message with the given uuid.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#findorfail]
----

public findOrFail($uuid):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Gets the message with the given UUID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#findmany]
----

public findMany($uuid):array

----







Gets a stream of messages. The given UUID can be the UUID of the first message in the stream or one of the replied messages.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#navigate]
----

public navigate($page = 1, $itemsPerPage = 50):array

----







Lists the messages for the given navigation page.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page of results to search for

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of items to list per page
|===


[source%nowrap, php]
[#gettotalentries]
----

public getTotalEntries():int

----







Returns total entries

[source%nowrap, php]
[#toarray]
----

public toArray():array

----









[source%nowrap, php]
[#process]
----

public process($data):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilter]
----

public getFilter():array

----









[source%nowrap, php]
[#getpostfilter]
----

public getPostFilter():array

----









[source%nowrap, php]
[#getquery]
----

public getQuery():array

----









[source%nowrap, php]
[#getaggregations]
----

public getAggregations():array

----









[source%nowrap, php]
[#getsuggestions]
----

public getSuggestions():array

----









[source%nowrap, php]
[#getsources]
----

public getSources():void

----









[source%nowrap, php]
[#adddependenciestosource]
----

public addDependenciesToSource($sources):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sources`
|
a|
|===


[source%nowrap, php]
[#getname]
----

public getName():void

----









[source%nowrap, php]
[#setname]
----

public setName($name):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|
a|
|===


[source%nowrap, php]
[#setissourcedisabled]
----

public setIsSourceDisabled($isSourceDisabled):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isSourceDisabled`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#settracktotalhits]
----

public setTrackTotalHits($trackTotalHits):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$trackTotalHits`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#addfilter]
----

public addFilter($filter):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filter`
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|
|===


[source%nowrap, php]
[#addpostfilter]
----

public addPostFilter($filter):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filter`
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|
|===


[source%nowrap, php]
[#addquery]
----

public addQuery($query):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|
|===


[source%nowrap, php]
[#addsource]
----

public addSource($source):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$source`
|        xref:Cloud.adoc#cloud_source_sourceinterface[`SourceInterface`]
a|
|===


[source%nowrap, php]
[#setsorting]
----

public setSorting($sorting):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sorting`
|        xref:Cloud.adoc#cloud_sorting_sortinginterface[`SortingInterface`]
a|
|===


[source%nowrap, php]
[#addaggregation]
----

public addAggregation($aggregation):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$aggregation`
|        xref:Cloud.adoc#cloud_aggregation_aggregationinterface[`AggregationInterface`]
a|
|===


[source%nowrap, php]
[#addsuggestion]
----

public addSuggestion($suggestion):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$suggestion`
|        xref:Cloud.adoc#cloud_suggestion_suggestioninterface[`SuggestionInterface`]
a|
|===


[source%nowrap, php]
[#setpage]
----

public setPage($page, $rowsPerPage):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$rowsPerPage`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#setpagination]
----

public setPagination($pagination):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$pagination`
|
a|
|===


[source%nowrap, php]
[#setcollapse]
----

public setCollapse($collapse):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$collapse`
|        xref:Cloud.adoc#cloud_collapse_collapseinterface[`CollapseInterface`]
a|
|===


[source%nowrap, php]
[#setscoremodifier]
----

public setScoreModifier($scoreModifier):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreModifier`
|        xref:Cloud.adoc#cloud_scoremodifier_scoremodifierinterface[`ScoreModifierInterface`]
a|
|===


[source%nowrap, php]
[#setmaxresultwindow]
----

public setMaxResultWindow($maxResults = 10000):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$maxResults`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#setindex]
----

public setIndex($index):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$index`
|
a|
|===


[source%nowrap, php]
[#issearchafter]
----

public isSearchAfter():void

----









[source%nowrap, php]
[#getfilterraw]
----

public getFilterRaw():void

----









[source%nowrap, php]
[#getqueriesraw]
----

public getQueriesRaw():void

----









[source%nowrap, php]
[#getaggregationsraw]
----

public getAggregationsRaw():array

----









[source%nowrap, php]
[#getsorting]
----

public getSorting():void

----









[source%nowrap, php]
[#getscoremodifier]
----

public getScoreModifier():void

----









