:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[messenger_messenger]]
== Messenger

[[messenger_messenger_contracts]]
===  Contracts
[[messenger_contracts_messengerrepositorycontract]]
==== MessengerRepositoryContract

The MessengerRepositoryContract is the interface for the messenger repository. This interface defines methods to add and show/list messages.



===== Namespace

`Plenty\Modules\Messenger\Contracts`






===== Methods

[source%nowrap, php]
[#add]
----

public add($data):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Creates a new message.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The message data to be loaded
|===


[source%nowrap, php]
[#show]
----

public show($uuid):void

----







Gets a message with all its successors.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID5 of the message
|===


[source%nowrap, php]
[#list]
----

public list($uuid = null, $successors = true, $amount = self::DEFAULT_MESSAGES_AMOUNT):array

----







Lists messages. If no reference UUID5 is given, the method returns the $amount first messages. If $successor is set to FALSE, the messages older than the referenced message will be returned.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The reference UUID5 of the message to start from (excluding).
If not set, the uuid of the newest message will be used.

a|`$successors`
|link:http://php.net/bool[bool^]
a|If set to FALSE, the messages older than the referenced message will be returned.

a|`$amount`
|link:http://php.net/int[int^]
a|The amount of messages to list (defaults to 50)
|===


[source%nowrap, php]
[#listarchivedmessages]
----

public listArchivedMessages($conversationUuid):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Lists messages for an archived conversation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$conversationUuid`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getmessages]
----

public getMessages($page = self::DEFAULT_PAGE_OF_MESSAGES, $itemsPerPage = self::DEFAULT_ITEMS_PER_PAGE_OF_MESSAGES):array

----







Lists messages.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The number of the returned page of messages, default is 1 (the first)

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The amount of messages to list (defaults to 50)
|===


[source%nowrap, php]
[#updatereadby]
----

public updateReadBy($readBy, $uuid):void

----







Updates the readBy array of the message.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$readBy`
|link:http://php.net/int[int^]
a|The ID of the user who read the message

a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#updatetags]
----

public updateTags($tags, $uuid):void

----







Updates the tags of the message.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tags`
|link:http://php.net/array[array^]
a|Array of tag IDs of the message

a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#updatevisibility]
----

public updateVisibility($data, $uuid):void

----







Updates the visibility of the message. Attributes that are updated are Message.visibility, Message.linkedTo and Message.accessFor.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The message with the data to be updated

a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the messages
|===


[source%nowrap, php]
[#updatecontrols]
----

public updateControls($data, $uuid):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Updates the message ui control options in the message meta data and returns the message.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The controls data to be updated.

a|`$uuid`
|link:http://php.net/string[string^]
a|The uuid of the message.
|===


[source%nowrap, php]
[#setdone]
----

public setDone($doneAt = null, $uuid):void

----







Sets the doneAt date in the message. If $doneAt is NULL, the doneAt date will be reset.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$doneAt`
|link:http://php.net/string[string^]
a|The doneAt date as ISO date string

a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#delete]
----

public delete($uuid):int

----







Deletes a message stream by the UUID. Returns the count of messages deleted.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#getattachment]
----

public getAttachment($uuid, $filename):Plenty\Modules\Messenger\Models\Attachment

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_attachment[`Attachment`]


Gets a message attachment.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message

a|`$filename`
|link:http://php.net/string[string^]
a|The file name of the attachment
|===


[source%nowrap, php]
[#getallattachments]
----

public getAllAttachments($uuid):Plenty\Modules\Messenger\Models\Attachment

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_attachment[`Attachment`]


Gets all message attachments as zip.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#updatemetadata]
----

public updateMetaData($uuid, $metaData):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Updates the meta data of the message.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message

a|`$metaData`
|link:http://php.net/array[array^]
a|The meta data of the message
|===


[source%nowrap, php]
[#gettotalentries]
----

public getTotalEntries():int

----







Returns total message entries

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[messenger_messenger_events]]
===  Events
[[messenger_events_messagecreated]]
==== MessageCreated

The event is triggered after a new message was created.



===== Namespace

`Plenty\Modules\Messenger\Events`






===== Methods

[source%nowrap, php]
[#isfirstmessage]
----

public isFirstMessage():bool

----







If TRUE, the message is the first one. Otherwise, it is a reply message.

[source%nowrap, php]
[#broadcastwhen]
----

public broadcastWhen():void

----









[source%nowrap, php]
[#getmessage]
----

public getMessage():Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Get the message.

[[messenger_messenger_models]]
===  Models
[[messenger_models_attachment]]
==== Attachment

The Attachment model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|name
    |link:http://php.net/string[string^]
    a|The file name of the attachment
|message
    |link:http://php.net/string[string^]
    a|The UUID of the message the attachment belongs to
|size
    |link:http://php.net/int[int^]
    a|The size of the attachment in bytes
|contentType
    |link:http://php.net/string[string^]
    a|The content type fo the attachment
|content
    |link:http://php.net/string[string^]
    a|The content of the attachment
|createdAt
    |link:http://php.net/string[string^]
    a|The createdAt date of the attachment
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_message]]
==== Message

The Message model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|uuid
    |link:http://php.net/string[string^]
    a|The UUID5 identifier of the message
|plentyIdHash
    |link:http://php.net/string[string^]
    a|The plenty ID hash
|parentUuid
    |link:http://php.net/string[string^]
    a|The UUID5 of the parent message
|conversationId
    |link:http://php.net/string[string^]
    a|The UUID5 of the conversation
|linkedTo
    |link:http://php.net/array[array^]
    a|An array with MessageLinkedTo instances
|from
    |        xref:Messenger.adoc#messenger_models_messagefrom[`MessageFrom`]
    a|The sender of the message as MessageFrom instance.
|to
    |        xref:Messenger.adoc#messenger_models_messageto[`MessageTo`]
    a|The user and role IDs and emails receiving the message
|whispered
    |link:http://php.net/bool[bool^]
    a|Whether the message is whispered (not visible for the contact/order linked to the message) or not
|tags
    |link:http://php.net/array[array^]
    a|An array with tag IDs assigned to the message
|title
    |link:http://php.net/string[string^]
    a|The title of the message
|preview
    |link:http://php.net/string[string^]
    a|The first two lines of the message without any markup
|message
    |link:http://php.net/string[string^]
    a|The content of the message
|plainMessage
    |link:http://php.net/string[string^]
    a|The content of the message as plain text
|attachedFilesCount
    |link:http://php.net/int[int^]
    a|The amount of attached files (readonly)
|referrer
    |        xref:Messenger.adoc#messenger_models_messagereferrer[`MessageReferrer`]
    a|The message referrer
|metaData
    |        xref:Messenger.adoc#messenger_models_messagemetadata[`MessageMetaData`]
    a|The meta data of the message
|doneAt
    |link:http://php.net/string[string^]
    a|The date the messages was set to done
|createdAt
    |link:http://php.net/string[string^]
    a|The creation date of the message
|updatedAt
    |link:http://php.net/string[string^]
    a|The date of the last update of the message
|deletedAt
    |link:http://php.net/string[string^]
    a|The date the message was deleted
|deletedBy
    |link:http://php.net/int[int^]
    a|The ID of the user who deleted the message
|attachments
    |link:http://php.net/array[array^]
    a|The message attachments
|categoryId
    |link:http://php.net/int[int^]
    a|The categoryID of the message/conversation
|typeId
    |link:http://php.net/int[int^]
    a|The typeID of the conversation
|typePosition
    |link:http://php.net/int[int^]
    a|The typePosition of the typeID
|statusId
    |link:http://php.net/int[int^]
    a|The statusID of the conversation
|statusPosition
    |link:http://php.net/int[int^]
    a|The statusPosition of statusID
|marketplacesMetadata
    |        xref:Messenger.adoc#messenger_models_messagemarketplacesmetadata[`MessageMarketplacesMetaData`]
    a|The marketplace metadata
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagefrom]]
==== MessageFrom

The MessageFrom model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|type
    |link:http://php.net/string[string^]
    a|The type of the from instance (one of {@link MessageTypesService::FROM_TYPE_USER},
{@link MessageTypesService::FROM_TYPE_CONTACT} and {@link MessageTypesService::FROM_TYPE_EMAIL})
|value
    |
    a|The value of the instance. For type {@link MessageTypesService::FROM_TYPE_EMAIL} it is a string (the email)
and the id of the user or the contact otherwise.
|name
    |link:http://php.net/string[string^]
    a|An optional name for the instance, e.g. the real name for type {@link MessageTypesService::FROM_TYPE_EMAIL}
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagelinkedto]]
==== MessageLinkedTo

The MessageLinkedTo model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|type
    |link:http://php.net/string[string^]
    a|The type of the link (one of {@link MessageTypesService::LINKED_TO_TYPE_MESSAGE},
{@link MessageTypesService::LINKED_TO_TYPE_ORDER}, {@link MessageTypesService::LINKED_TO_TYPE_CONTACT}
and {@link MessageTypesService::LINKED_TO_TYPE_PAYMENT})
|value
    |
    a|The value of the link. For type {@link MessageTypesService::LINKED_TO_TYPE_MESSAGE} it is a string (uuid5)
and an integer otherwise.
|typeId
    |
    a|This can be the ID of a sub-type (e.g. the order subTypeId). (optional)
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagemetadata]]
==== MessageMetaData

The MessageMetaData model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|readBy
    |link:http://php.net/array[array^]
    a|The array of users
|links
    |link:http://php.net/array[array^]
    a|Array with links
|notDoneByBackend
    |        xref:Messenger.adoc#messenger_models_messagemetadatanotdone[`MessageMetaDataNotDone`]
    a|deactivates the toggle button in the messenger ui (backend) also has optional tooltips (reason for the deactivated toggle)
|controls
    |        xref:Messenger.adoc#messenger_models_messagemetadatacontrols[`MessageMetaDataControls`]
    a|An object with control options for the ui.
|timeCapture
    |        xref:Messenger.adoc#messenger_models_messagemetadatatimecapture[`MessageMetaDataTimeCapture`]
    a|An object of the message time capture data
|plentyId
    |link:http://php.net/int[int^]
    a|the plenty id of the related contact
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagemetadatacontrols]]
==== MessageMetaDataControls

The message controls model. Currently supported controls:
 * &lt;ul&gt;
 * &lt;li&gt;&lt;tt&gt;bool replyable&lt;/tt&gt;
 *      Indicates whether or not is allowed to reply to this message stream (default true).
 *      It is a global control and effects only in the parent message of a stream.&lt;/li&gt;
 * &lt;li&gt;&lt;tt&gt;bool attachable&lt;/tt&gt;
 *      Indicates whether or not is allowed to attach files in a message (default true).
 *      It is a global control and effects only in the parent message of a stream.&lt;/li&gt;
 * &lt;li&gt;&lt;tt&gt;bool linksDisabled&lt;/tt&gt;
 *      Indicates whether or not the message links should be disabled (default false).
 *      It is a loacal control and effects every message.&lt;/li&gt;
 * &lt;/ul&gt;



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|replyable
    |link:http://php.net/bool[bool^]
    a|Indicates whether or not is allowed to reply to this message stream (default true).
|attachable
    |link:http://php.net/bool[bool^]
    a|Indicates whether or not is allowed to attach files in a message (default true).
|linksDisabled
    |link:http://php.net/bool[bool^]
    a|Indicates whether or not the message links should be disabled (default false).
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagemetadatanotdone]]
==== MessageMetaDataNotDone

The MessageMetaDataNotDone model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|deactivated
    |link:http://php.net/bool[bool^]
    a|Deactivates the toggle button for the UI
|tooltips
    |link:http://php.net/array[array^]
    a|Tooltips for the UI to show why the toggle is deactivated (if not set, show default values)
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagemetadatatimecapture]]
==== MessageMetaDataTimeCapture

The MessageMetaDataTimeCapture model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|chargeable
    |link:http://php.net/bool[bool^]
    a|
|minutes
    |link:http://php.net/int[int^]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagemetalink]]
==== MessageMetaLink

The MessageMetaLink model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|image
    |link:http://php.net/string[string^]
    a|An optional image URL for the link
|caption
    |link:http://php.net/string[string^]
    a|The caption to be shown for the link
|url
    |link:http://php.net/string[string^]
    a|The link URL
<ul>
    <li>for {@link MessageMetaLink::TYPE_MAILTO} the email</li>
    <li>for {@link MessageMetaLink::TYPE_URL} the complete URL with protocol</li>
    <li>for {@link MessageMetaLink::TYPE_PLUGIN} the relative route to the backend</li>
    <li>not needed for {@link MessageMetaLink::TYPE_REPLY}</li>
</ul>
|type
    |link:http://php.net/string[string^]
    a|One of the constants:
<ul>
    <li>{@link MessageMetaLink::TYPE_MAILTO}</li>
    <li>{@link MessageMetaLink::TYPE_URL}</li>
    <li>{@link MessageMetaLink::TYPE_PLUGIN}</li>
    <li>{@link MessageMetaLink::TYPE_REPLY}</li>
</ul>
|content
    |link:http://php.net/string[string^]
    a|The reply content, only needed for type {@link MessageMetaLink::TYPE_REPLY}
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messagereferrer]]
==== MessageReferrer

The MessageReferrer model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|type
    |link:http://php.net/string[string^]
    a|The type of the from instance (one of {@link MessageTypesService::REFERRER_TYPE_SYSTEM},
{@link MessageTypesService::REFERRER_TYPE_BACKEND}, {@link MessageTypesService::REFERRER_TYPE_REST},
{@link MessageTypesService::REFERRER_TYPE_EMAIL} and {@link MessageTypesService::REFERRER_TYPE_PLUGIN})
|value
    |
    a|The value of the instance. It is an integer (the user id) for type
{@link MessageTypesService::REFERRER_TYPE_SYSTEM}, {@link MessageTypesService::REFERRER_TYPE_EMAIL}, {@link MessageTypesService::REFERRER_TYPE_BACKEND}
and {@link MessageTypesService::REFERRER_TYPE_REST} and a string (the plugin name) for type
{@link MessageTypesService::REFERRER_TYPE_PLUGIN}.
|name
    |link:http://php.net/string[string^]
    a|An optional name for the instance. For type {@link MessageTypesService::REFERRER_TYPE_PLUGIN} it is
the plugin namespace, the user name otherwise.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_messageto]]
==== MessageTo

The MessageTo model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|user
    |link:http://php.net/array[array^]
    a|An array with user IDs of users receiving the message
|role
    |link:http://php.net/array[array^]
    a|An array with user role IDs of user roles receiving the message
|email
    |link:http://php.net/array[array^]
    a|An array with emails receiving the message
|allUsers
    |link:http://php.net/bool[bool^]
    a|Flag indicating that all system users receive the message
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[messenger_messenger_services]]
===  Services
[[messenger_services_messagetypesservice]]
==== MessageTypesService

Types and type validation for several types in the messenger.



===== Namespace

`Plenty\Modules\Messenger\Services`






===== Methods

[source%nowrap, php]
[#getvalidlinkedtotypes]
----

public static getValidLinkedToTypes():array

----







Gets the valid types for &quot;linked to&quot; references.

[source%nowrap, php]
[#isvalidlinkedto]
----

public static isValidLinkedTo($linkType, $linkValue):bool

----







Checks whether the given link is valid or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$linkType`
|link:http://php.net/string[string^]
a|The link type

a|`$linkValue`
|
a|The link value
|===


[source%nowrap, php]
[#getvalidfromtypes]
----

public static getValidFromTypes():array

----







Gets the valid types for &quot;from&quot; references.

[source%nowrap, php]
[#isvalidfrom]
----

public static isValidFrom($fromType, $fromValue):bool

----







Checks whether the given from is valid or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fromType`
|link:http://php.net/string[string^]
a|The from type

a|`$fromValue`
|
a|The from value
|===


[source%nowrap, php]
[#getvalidreferrertypes]
----

public static getValidReferrerTypes():array

----







Gets the valid types for &quot;referrer&quot; references.

[source%nowrap, php]
[#isvalidreferrer]
----

public static isValidReferrer($referrerType, $referrerValue, $referrerName = null):bool

----







Checks whether the given referrer reference is valid or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$referrerType`
|link:http://php.net/string[string^]
a|The reference to be checked

a|`$referrerValue`
|
a|The value of the reference

a|`$referrerName`
|link:http://php.net/string[string^]
a|The name of the reference
|===


[source%nowrap, php]
[#getvalidtotypes]
----

public static getValidToTypes():array

----







Gets the valid key types for the &#039;to&#039; array.

[source%nowrap, php]
[#isvalidto]
----

public static isValidTo($toKey):bool

----







Checks whether the given key has a valid value for to.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$toKey`
|link:http://php.net/string[string^]
a|The to key
|===



[[messenger_services_messagessearchservice]]
==== MessagesSearchService

Search service for the messenger.



===== Namespace

`Plenty\Modules\Messenger\Services`






===== Methods

[source%nowrap, php]
[#find]
----

public find($uuid):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Gets the message with the given uuid.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#findorfail]
----

public findOrFail($uuid):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Gets the message with the given UUID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#findmany]
----

public findMany($uuid):array

----







Gets a stream of messages. The given UUID can be the UUID of the first message in the stream or one of the replied messages.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#navigate]
----

public navigate($page = 1, $itemsPerPage = 50):array

----







Lists the messages for the given navigation page.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page of results to search for

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of items to list per page
|===


[source%nowrap, php]
[#gettotalentries]
----

public getTotalEntries():int

----







Returns total entries

[source%nowrap, php]
[#loadmessage]
----

public static loadMessage($path):Plenty\Modules\Messenger\Models\Message

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_message[`Message`]


Get an instance of the model.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$path`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#removetagsandwhitespaces]
----

public static removeTagsAndWhitespaces($message):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$message`
|
a|
|===


[source%nowrap, php]
[#findbyconversationid]
----

public findByConversationId($conversationUuid):array

----







Gets a stream of messages. The given UUID can be the UUID of the first message in the stream or one of the replied messages.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$conversationUuid`
|link:http://php.net/string[string^]
a|The UUID of the message
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----









[source%nowrap, php]
[#process]
----

public process($data):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilter]
----

public getFilter():array

----









[source%nowrap, php]
[#getpostfilter]
----

public getPostFilter():array

----









[source%nowrap, php]
[#getquery]
----

public getQuery():array

----









[source%nowrap, php]
[#getaggregations]
----

public getAggregations():array

----









[source%nowrap, php]
[#getsuggestions]
----

public getSuggestions():array

----









[source%nowrap, php]
[#getsources]
----

public getSources():void

----









[source%nowrap, php]
[#adddependenciestosource]
----

public addDependenciesToSource($sources):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sources`
|
a|
|===


[source%nowrap, php]
[#getname]
----

public getName():void

----









[source%nowrap, php]
[#setname]
----

public setName($name):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|
a|
|===


[source%nowrap, php]
[#setissourcedisabled]
----

public setIsSourceDisabled($isSourceDisabled):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isSourceDisabled`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#settracktotalhits]
----

public setTrackTotalHits($trackTotalHits):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$trackTotalHits`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#addfilter]
----

public addFilter($filter):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filter`
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|
|===


[source%nowrap, php]
[#addpostfilter]
----

public addPostFilter($filter):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filter`
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|
|===


[source%nowrap, php]
[#addquery]
----

public addQuery($query):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|
|===


[source%nowrap, php]
[#addsource]
----

public addSource($source):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$source`
|        xref:Cloud.adoc#cloud_source_sourceinterface[`SourceInterface`]
a|
|===


[source%nowrap, php]
[#setsorting]
----

public setSorting($sorting):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sorting`
|        xref:Cloud.adoc#cloud_sorting_sortinginterface[`SortingInterface`]
a|
|===


[source%nowrap, php]
[#addaggregation]
----

public addAggregation($aggregation):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$aggregation`
|        xref:Cloud.adoc#cloud_aggregation_aggregationinterface[`AggregationInterface`]
a|
|===


[source%nowrap, php]
[#addsuggestion]
----

public addSuggestion($suggestion):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$suggestion`
|        xref:Cloud.adoc#cloud_suggestion_suggestioninterface[`SuggestionInterface`]
a|
|===


[source%nowrap, php]
[#setpage]
----

public setPage($page, $rowsPerPage):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$rowsPerPage`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#setpagination]
----

public setPagination($pagination):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$pagination`
|
a|
|===


[source%nowrap, php]
[#setcollapse]
----

public setCollapse($collapse):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$collapse`
|        xref:Cloud.adoc#cloud_collapse_collapseinterface[`CollapseInterface`]
a|
|===


[source%nowrap, php]
[#setscoremodifier]
----

public setScoreModifier($scoreModifier):Plenty\Modules\Cloud\ElasticSearch\Lib\Search\BaseSearch

----




====== *Return type:*        xref:Cloud.adoc#cloud_search_basesearch[`BaseSearch`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreModifier`
|        xref:Cloud.adoc#cloud_scoremodifier_scoremodifierinterface[`ScoreModifierInterface`]
a|
|===


[source%nowrap, php]
[#setmaxresultwindow]
----

public setMaxResultWindow($maxResults = 10000):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$maxResults`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#setindex]
----

public setIndex($index):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$index`
|
a|
|===


[source%nowrap, php]
[#issearchafter]
----

public isSearchAfter():void

----









[source%nowrap, php]
[#getfilterraw]
----

public getFilterRaw():void

----









[source%nowrap, php]
[#getqueriesraw]
----

public getQueriesRaw():void

----









[source%nowrap, php]
[#getaggregationsraw]
----

public getAggregationsRaw():array

----









[source%nowrap, php]
[#getsorting]
----

public getSorting():void

----









[source%nowrap, php]
[#getscoremodifier]
----

public getScoreModifier():void

----










[[messenger_services_newmessengerstatusservice]]
==== NewMessengerStatusService

New messenger status checker service



===== Namespace

`Plenty\Modules\Messenger\Services`






===== Methods

[source%nowrap, php]
[#isactive]
----

public static isActive():void

----









[[messenger_conversations]]
== Conversations

[[messenger_conversations_contracts]]
===  Contracts
[[messenger_contracts_conversationcategoryrepositorycontract]]
==== ConversationCategoryRepositoryContract

The ConversationCategoryRepositoryContract is the interface for the messenger conversations categories. This interface defines methods to add, update and show categories.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Contracts`






===== Methods

[source%nowrap, php]
[#getcategory]
----

public getCategory($id):Plenty\Modules\Messenger\Conversations\Models\ConversationCategory

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationcategory[`ConversationCategory`]


Retrieves a category based on ID

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|Category ID
|===


[source%nowrap, php]
[#createcategory]
----

public createCategory($categoryData):Plenty\Modules\Messenger\Conversations\Models\ConversationCategory

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationcategory[`ConversationCategory`]


Creates a new category

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$categoryData`
|link:http://php.net/array[array^]
a|Array with category properties
|===


[source%nowrap, php]
[#updatecategory]
----

public updateCategory($id, $data):Plenty\Modules\Messenger\Conversations\Models\ConversationCategory

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationcategory[`ConversationCategory`]


Updates an existing category

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|Category ID

a|`$data`
|link:http://php.net/array[array^]
a|Array with cateogry properties
|===


[source%nowrap, php]
[#updatecategorystatus]
----

public updateCategoryStatus($id, $isEnabled):Plenty\Modules\Messenger\Conversations\Models\ConversationCategory

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationcategory[`ConversationCategory`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$isEnabled`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#listcategories]
----

public listCategories($page, $itemsPerPage, $sortBy, $sortOrder, $filters = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Lists all categories based on provided filters

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|Page number

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|Number of results per page

a|`$sortBy`
|link:http://php.net/string[string^]
a|Sort column (id, position)

a|`$sortOrder`
|link:http://php.net/string[string^]
a|Sort order (asc/desc)

a|`$filters`
|link:http://php.net/array[array^]
a|Array with filters (isDeleted, typeId, id, name)
|===


[source%nowrap, php]
[#deletecategory]
----

public deleteCategory($id):bool

----







Deletes a category (soft delete)

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|Status ID
|===


[source%nowrap, php]
[#batchdeletecategories]
----

public batchDeleteCategories($categoryIds):bool

----







Deletes a batch of categories

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$categoryIds`
|link:http://php.net/array[array^]
a|
|===



[[messenger_contracts_conversationfolderrepositorycontract]]
==== ConversationFolderRepositoryContract

The ConversationFolderRepositoryContract is the interface for the messenger conversations folders. This interface defines methods to add, update and show folders.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Contracts`






===== Methods

[source%nowrap, php]
[#getfolder]
----

public getFolder($uuid):Plenty\Modules\Messenger\Conversations\Models\ConversationFolder

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationfolder[`ConversationFolder`]


Retrieves a folder object based on UUID

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the folder
|===


[source%nowrap, php]
[#createfolder]
----

public createFolder($data):Plenty\Modules\Messenger\Conversations\Models\ConversationFolder

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationfolder[`ConversationFolder`]


Creates a new folder. Important! The userId property will be automatically set based on the current logged in user.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|Array with folder properties
|===


[source%nowrap, php]
[#updatefolder]
----

public updateFolder($uuid, $data):Plenty\Modules\Messenger\Conversations\Models\ConversationFolder

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationfolder[`ConversationFolder`]


Updates an existing folder.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|Folder UUID

a|`$data`
|link:http://php.net/array[array^]
a|Array with folder properties
|===


[source%nowrap, php]
[#listfolders]
----

public listFolders($userId, $page, $itemsPerPage, $sortBy, $sortOrder):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Returns a paginated result with all folders

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$userId`
|link:http://php.net/int[int^]
a|ID of the folder owner

a|`$page`
|link:http://php.net/int[int^]
a|Page number

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|Items per page

a|`$sortBy`
|link:http://php.net/string[string^]
a|Sort column

a|`$sortOrder`
|link:http://php.net/string[string^]
a|Sort order
|===


[source%nowrap, php]
[#deletefolder]
----

public deleteFolder($uuid):bool

----







Deletes a folder

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|The UUID of the deleted folder
|===



[[messenger_contracts_conversationrepositorycontract]]
==== ConversationRepositoryContract

The ConversationRepositoryContract is the interface for the messenger conversations repository. This interface defines methods to add, update and show conversations.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Contracts`






===== Methods

[source%nowrap, php]
[#listconversations]
----

public listConversations($request):array

----







List all conversations and returns a paginated result

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$request`
|link:http://php.net/array[array^]
a|List of filters, page number, items per page and "with" array
|===


[source%nowrap, php]
[#searchconversations]
----

public searchConversations($getFilters, $postFilters):array

----







List all conversations and returns a paginated result

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$getFilters`
|link:http://php.net/array[array^]
a|

a|`$postFilters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#createconversation]
----

public createConversation($data):Plenty\Modules\Messenger\Conversations\Models\Conversation

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversation[`Conversation`]


Creates a new conversation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|Conversation data
|===


[source%nowrap, php]
[#getconversation]
----

public getConversation($uuid5, $with = []):Plenty\Modules\Messenger\Conversations\Models\Conversation

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversation[`Conversation`]


Retrieves a conversation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid5`
|link:http://php.net/string[string^]
a|Conversation UUID

a|`$with`
|link:http://php.net/array[array^]
a|Array with extra relations (possible values: ["messages"])
|===


[source%nowrap, php]
[#updateconversation]
----

public updateConversation($uuid5, $data):Plenty\Modules\Messenger\Conversations\Models\Conversation

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversation[`Conversation`]


Updates a conversation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid5`
|link:http://php.net/string[string^]
a|Conversation UUID

a|`$data`
|link:http://php.net/array[array^]
a|Conversation data. If a property key is missing, the old value will be kept.
|===


[source%nowrap, php]
[#updateclose]
----

public updateClose($uuids, $isClosed):int

----







Sets a batch of conversations closed status

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's

a|`$isClosed`
|link:http://php.net/bool[bool^]
a|Close status (true/false)
|===


[source%nowrap, php]
[#updatetags]
----

public updateTags($uuid, $tagIds):int

----







Update the list of tags for a conversation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|Conversation UUID

a|`$tagIds`
|link:http://php.net/array[array^]
a|Array of tag ID's
|===


[source%nowrap, php]
[#addtags]
----

public addTags($uuids, $tagIds):int

----







Adds to a batch of conversations new tags. The list of tags will be extra added to the existing list of tags for each conversation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's

a|`$tagIds`
|link:http://php.net/array[array^]
a|Array of tag ID's
|===


[source%nowrap, php]
[#updatedeadline]
----

public updateDeadline($uuids, $deadline = null):int

----







Sets deadline for a batch of conversations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's

a|`$deadline`
|link:http://php.net/string[string^]
a|Deadline in format YYYY-MM-DD H:i:s. If null is set, the deadline will be removed
|===


[source%nowrap, php]
[#updatefollowupdate]
----

public updateFollowUpDate($uuids, $followUpDate = null):int

----







Sets follow up date for a batch of conversations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's

a|`$followUpDate`
|link:http://php.net/string[string^]
a|Follow up date in format YYYY-MM-DD H:i:s.
If null is set, the follow up date will be removed
|===


[source%nowrap, php]
[#updateread]
----

public updateRead($uuids, $userId, $read):int

----







Marks a batch of conversations as red/not read by the given user

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's

a|`$userId`
|link:http://php.net/int[int^]
a|ID of the user

a|`$read`
|link:http://php.net/bool[bool^]
a|Read status: true/false
|===


[source%nowrap, php]
[#batchresubmitconversations]
----

public batchResubmitConversations($uuids):int

----







Resubmits all conversations with follow up date today (resets read by array, resets follow up date)

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's
|===


[source%nowrap, php]
[#addsubscribers]
----

public addSubscribers($uuid, $userId):int

----







Subscribes a user to a conversation. A subscribed user will receive notifications related to that conversation (via email or in the admin notifications area)

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|Conversation UUID

a|`$userId`
|link:http://php.net/int[int^]
a|ID of the user
|===


[source%nowrap, php]
[#removesubscribers]
----

public removeSubscribers($uuid, $userId):int

----







Unsubscribes a user from a conversation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid`
|link:http://php.net/string[string^]
a|Conversation UUID

a|`$userId`
|link:http://php.net/int[int^]
a|ID of the user
|===


[source%nowrap, php]
[#deleteconversation]
----

public deleteConversation($uuid5):int

----







Soft deletes a conversation. Conversation will be visible in the trash folder.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuid5`
|link:http://php.net/string[string^]
a|Conversation UUID
|===


[source%nowrap, php]
[#batchdeleteconversations]
----

public batchDeleteConversations($uuids):int

----







Soft deletes a batch of conversations. Conversations will be visible in the trash folder.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/string[string^]
a|List of conversations UUID's separated by comma
|===


[source%nowrap, php]
[#searchreceiver]
----

public searchReceiver($searchTerm, $companyId = null):array

----







Search and returns a list of possible receivers. Search is done by contact name, contact id, order ID, user ID, user name. Search term must have minimum 3 letters

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$searchTerm`
|link:http://php.net/string[string^]
a|The searched term

a|`$companyId`
|link:http://php.net/int[int^]
a|The company ID for witch will make the search
|===


[source%nowrap, php]
[#getinboxes]
----

public getInboxes():array

----







Retrieves the list of configured inboxes. If the inbox is not active it will not be returned in the response.

[source%nowrap, php]
[#updatepriority]
----

public updatePriority($uuids, $priorityId):int

----







Sets priority for a batch of conversations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's

a|`$priorityId`
|link:http://php.net/int[int^]
a|Id of priority (0 - No priority, 1 - Very low, 2 - low, 3 - Medium, 4 - High, 5 - Very high)
|===


[source%nowrap, php]
[#updateconversationstypeandstatus]
----

public updateConversationsTypeAndStatus($conversationsUuids, $typeId, $statusId):bool

----







Sets the type and status for a batch of conversations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$conversationsUuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's

a|`$typeId`
|link:http://php.net/int[int^]
a|Type ID of conversation. If null is set, the conversation type will be removed.

a|`$statusId`
|link:http://php.net/int[int^]
a|Status ID of conversation. If null is set, the conversation status will be removed.
|===


[source%nowrap, php]
[#gettotals]
----

public getTotals():array

----







Returns the total number of unread conversations for current user

[source%nowrap, php]
[#emptytrash]
----

public emptyTrash($days = null):bool

----







Permanently deletes all the messages from trash older than $days (based on deleted at field). If days is null, all messages from trash will be permanently deleted. Emptying of the trash will be done immediately.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$days`
|link:http://php.net/int[int^]
a|Minimum number of days since the conversation was moved to trash
|===


[source%nowrap, php]
[#queueemptytrash]
----

public queueEmptyTrash($days = null):bool

----







Adds the empty trash command to a queue. Emptying of the trash will happen sometime in the future, when the first worker is available to process the queue (less impact on Elastic Search index).

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$days`
|link:http://php.net/int[int^]
a|Minimum number of days since the conversation was moved to trash
|===


[source%nowrap, php]
[#archiveconversations]
----

public archiveConversations($uuids, $isFromUI):int

----







Archives a batch of conversations. Conversations will be visible in archive folder (filter isArchive = true in list conversations)

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's

a|`$isFromUI`
|link:http://php.net/bool[bool^]
a|Flag that specifies if action is triggered from UI. If set to true, the action will be performed immediately. If set to false, the action will be queued (less impact on Elastic Search index)
|===


[source%nowrap, php]
[#restorearchivedconversations]
----

public restoreArchivedConversations($uuids):int

----







Restores a batch of conversations from the archive. The operation is performed immediately.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's
|===


[source%nowrap, php]
[#permanentlydeletearchivedconversations]
----

public permanentlyDeleteArchivedConversations($uuids):int

----







Permanently deletes a batch of conversations from the archive

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's. The operation is performed immediately.
|===


[source%nowrap, php]
[#batchrestoreconversations]
----

public batchRestoreConversations($uuids):int

----







Restores from trash a batch of conversations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's. The operation is performed immediately.
|===


[source%nowrap, php]
[#updatesubscribe]
----

public updateSubscribe($uuids):int

----







Subscribes current user to a batch of conversations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's.
|===


[source%nowrap, php]
[#updateunsubscribe]
----

public updateUnsubscribe($uuids):int

----







Unsubscribes the current user from a batch of conversations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$uuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's.
|===


[source%nowrap, php]
[#automaticallyarchiveconversations]
----

public automaticallyArchiveConversations($days):bool

----







Automatically archives conversations older than $days days. The updatedAt field is taken into consideration when calculating conversation age.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$days`
|link:http://php.net/int[int^]
a|Minimum number of days since the conversation was last updated
|===


[source%nowrap, php]
[#updateconversationsfoldersrelations]
----

public updateConversationsFoldersRelations($conversationsUuids, $foldersUuids):bool

----







Assigns batch of conversation to batch of folders. The list of folders must belong to the current logged in user ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$conversationsUuids`
|link:http://php.net/array[array^]
a|Array of conversations UUID's

a|`$foldersUuids`
|link:http://php.net/array[array^]
a|Array of folders UUID's
|===


[source%nowrap, php]
[#removeconversationfolders]
----

public removeConversationFolders($conversationsUuid, $foldersUuidsToKeep):bool

----







Removes conversation from all folders except the ones passed to array $foldersUuidsToKeep. This operation will be performed only for folders belonging to current logged in user ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$conversationsUuid`
|link:http://php.net/string[string^]
a|Conversation UUID

a|`$foldersUuidsToKeep`
|link:http://php.net/array[array^]
a|Array of folders UUID's to keep. If array is empty, conversation will be removed from all folders
|===


[source%nowrap, php]
[#addtofolders]
----

public addToFolders($conversationsUuids, $foldersUuids):bool

----







Add multiple conversations to multiple folders

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$conversationsUuids`
|link:http://php.net/array[array^]
a|The conversations UUIDs

a|`$foldersUuids`
|link:http://php.net/array[array^]
a|The folders UUIDs
|===


[source%nowrap, php]
[#removefromfolders]
----

public removeFromFolders($conversationsUuids, $foldersUuids):bool

----







Remove multiple conversations from multiple folders

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$conversationsUuids`
|link:http://php.net/array[array^]
a|The conversations UUIDs

a|`$foldersUuids`
|link:http://php.net/array[array^]
a|The folders UUIDs
|===


[source%nowrap, php]
[#gethistorybyconversationuuid]
----

public getHistoryByConversationUUID($UUID):array

----







Retrieves history for a conversation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$UUID`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#removeconversationrelation]
----

public removeConversationRelation($conversationUuid, $type, $value):bool

----







Removes relation from a conversation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$conversationUuid`
|link:http://php.net/string[string^]
a|

a|`$type`
|link:http://php.net/string[string^]
a|

a|`$value`
|link:http://php.net/string[string^]
a|
|===



[[messenger_contracts_conversationrolerepositorycontract]]
==== ConversationRoleRepositoryContract

The ConversationRoleRepositoryContract is the interface for the messenger conversations roles.
 *     This interface defines methods to add, update, delete and show roles.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Contracts`






===== Methods

[source%nowrap, php]
[#getrolebyid]
----

public getRoleById($roleId):Plenty\Modules\Messenger\Conversations\Models\Roles\ConversationRole

----




====== *Return type:*        xref:Messenger.adoc#messenger_roles_conversationrole[`ConversationRole`]


Get role details by role id

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$roleId`
|link:http://php.net/int[int^]
a|ID of the role
|===


[source%nowrap, php]
[#listroles]
----

public listRoles($page = 1, $itemPerPage = 25, $sortBy = &quot;id&quot;, $sortOrder = &quot;asc&quot;, $filters = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Get paginated results for roles

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|Page number

a|`$itemPerPage`
|link:http://php.net/int[int^]
a|Items per page

a|`$sortBy`
|link:http://php.net/string[string^]
a|Column name to be sorted by

a|`$sortOrder`
|link:http://php.net/string[string^]
a|Sort order

a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#updaterole]
----

public updateRole($roleId, $data):Plenty\Modules\Messenger\Conversations\Models\Roles\ConversationRole

----




====== *Return type:*        xref:Messenger.adoc#messenger_roles_conversationrole[`ConversationRole`]


Update a role

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$roleId`
|link:http://php.net/int[int^]
a|The id of the role to be updated

a|`$data`
|link:http://php.net/array[array^]
a|Aray with Role properties to be updated
|===


[source%nowrap, php]
[#deleterole]
----

public deleteRole($roleId):bool

----







Delete a role

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$roleId`
|link:http://php.net/int[int^]
a|The id of the role to be deleted
|===


[source%nowrap, php]
[#createrole]
----

public createRole($data):Plenty\Modules\Messenger\Conversations\Models\Roles\ConversationRole

----




====== *Return type:*        xref:Messenger.adoc#messenger_roles_conversationrole[`ConversationRole`]


Create new role

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#batchdeleteroles]
----

public batchDeleteRoles($roleIds):bool

----







Deletes a batch of roles

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$roleIds`
|link:http://php.net/array[array^]
a|Array with role ID's
|===



[[messenger_contracts_conversationstatusrepositorycontract]]
==== ConversationStatusRepositoryContract

The ConversationStatusRepositoryContract is the interface for the messenger conversations statuses. This interface defines methods to add, update and show statuses.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Contracts`






===== Methods

[source%nowrap, php]
[#getstatus]
----

public getStatus($id):Plenty\Modules\Messenger\Conversations\Models\ConversationStatus

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationstatus[`ConversationStatus`]


Retrieves a status based on ID

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|Status ID
|===


[source%nowrap, php]
[#createstatus]
----

public createStatus($statusData):Plenty\Modules\Messenger\Conversations\Models\ConversationStatus

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationstatus[`ConversationStatus`]


Creates a new status

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$statusData`
|link:http://php.net/array[array^]
a|Array with status properties
|===


[source%nowrap, php]
[#updatestatus]
----

public updateStatus($id, $data):Plenty\Modules\Messenger\Conversations\Models\ConversationStatus

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationstatus[`ConversationStatus`]


Updates an existing status

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|Status ID

a|`$data`
|link:http://php.net/array[array^]
a|Array with status properties
|===


[source%nowrap, php]
[#liststatuses]
----

public listStatuses($page, $itemsPerPage, $sortBy, $sortOrder, $filters = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Lists all statuses based on provided filters

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|Page number

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|Number of results per page

a|`$sortBy`
|link:http://php.net/string[string^]
a|Sort column (id, position)

a|`$sortOrder`
|link:http://php.net/string[string^]
a|Sort order (asc/desc)

a|`$filters`
|link:http://php.net/array[array^]
a|Array with filters (isDeleted, typeId, id, name)
|===


[source%nowrap, php]
[#deletestatus]
----

public deleteStatus($id):bool

----







Deletes a status (soft delete)

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|Status ID
|===


[source%nowrap, php]
[#batchdeletestatuses]
----

public batchDeleteStatuses($statusIds):bool

----







Deletes a batch of statuses

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$statusIds`
|link:http://php.net/array[array^]
a|Array with status ID's
|===



[[messenger_contracts_conversationtyperepositorycontract]]
==== ConversationTypeRepositoryContract

The ConversationTypeRepositoryContract is the interface for the messenger conversations types. This interface defines methods to add, update and show types.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Contracts`






===== Methods

[source%nowrap, php]
[#gettype]
----

public getType($id):Plenty\Modules\Messenger\Conversations\Models\ConversationType

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationtype[`ConversationType`]


Retrieves a type based on ID

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|Type ID
|===


[source%nowrap, php]
[#createtype]
----

public createType($typeData):Plenty\Modules\Messenger\Conversations\Models\ConversationType

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationtype[`ConversationType`]


Creates a new type

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$typeData`
|link:http://php.net/array[array^]
a|Array with type properties
|===


[source%nowrap, php]
[#updatetype]
----

public updateType($id, $typeData):Plenty\Modules\Messenger\Conversations\Models\ConversationType

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_conversationtype[`ConversationType`]


TUpdates an existing type

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|Type ID

a|`$typeData`
|link:http://php.net/array[array^]
a|Array with type properties
|===


[source%nowrap, php]
[#listtypes]
----

public listTypes($page, $itemsPerPage, $sortBy, $sortOrder, $filters = [], $with = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Lists all types based on filters and returns a paginated result

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|Page number

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|Number of results per page

a|`$sortBy`
|link:http://php.net/string[string^]
a|Sort column (id, position)

a|`$sortOrder`
|link:http://php.net/string[string^]
a|Sort order (asc/desc)

a|`$filters`
|link:http://php.net/array[array^]
a|Array with filters (name, isDeleted, id)

a|`$with`
|link:http://php.net/array[array^]
a|(allStatuses ,activeStatuses)
|===


[source%nowrap, php]
[#deletetype]
----

public deleteType($id):bool

----







Deletes a type

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|Type ID
|===


[source%nowrap, php]
[#batchdeletetypes]
----

public batchDeleteTypes($typeIds):bool

----







Deletes a batch of types

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$typeIds`
|link:http://php.net/array[array^]
a|Array of type ID's
|===


[[messenger_conversations_events]]
===  Events
[[messenger_events_deadlinechangeconversationevent]]
==== DeadlineChangeConversationEvent

The event is triggered when the conversation deadline is changed.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Events`






===== Methods

[source%nowrap, php]
[#getconversationuuid]
----

public getConversationUUID():void

----










[[messenger_events_newconversationevent]]
==== NewConversationEvent

The event is triggered when a new conversation is created by a user (via UI or REST API).



===== Namespace

`Plenty\Modules\Messenger\Conversations\Events`






===== Methods

[source%nowrap, php]
[#getconversationuuid]
----

public getConversationUUID():void

----










[[messenger_events_newemailfromcustomerconversationevent]]
==== NewEmailFromCustomerConversationEvent

The event is triggered when a new conversation is created by a customer (received via inbox).



===== Namespace

`Plenty\Modules\Messenger\Conversations\Events`






===== Methods

[source%nowrap, php]
[#getconversationuuid]
----

public getConversationUUID():void

----










[[messenger_events_newreplyconversationevent]]
==== NewReplyConversationEvent

The event is triggered when an user replyes to an existing conversation (via UI or REST API).



===== Namespace

`Plenty\Modules\Messenger\Conversations\Events`






===== Methods

[source%nowrap, php]
[#getconversationuuid]
----

public getConversationUUID():void

----










[[messenger_events_newreplyfromcustomerconversationevent]]
==== NewReplyFromCustomerConversationEvent

The event is triggered when the customer replyes to an existing conversation (reply received via inbox).



===== Namespace

`Plenty\Modules\Messenger\Conversations\Events`






===== Methods

[source%nowrap, php]
[#getconversationuuid]
----

public getConversationUUID():void

----










[[messenger_events_orderaddedtoreceiverlistevent]]
==== OrderAddedToReceiverListEvent

The event is triggered when the order is added to the receiver list of an existing conversation.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Events`






===== Methods

[source%nowrap, php]
[#getconversationuuid]
----

public getConversationUUID():void

----










[[messenger_events_prioritychangeconversationevent]]
==== PriorityChangeConversationEvent

The event is triggered when the conversation priority is changed.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Events`






===== Methods

[source%nowrap, php]
[#getconversationuuid]
----

public getConversationUUID():void

----










[[messenger_events_statuschangeconversationevent]]
==== StatusChangeConversationEvent

The event is triggered when the conversation status is changed.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Events`






===== Methods

[source%nowrap, php]
[#getconversationuuid]
----

public getConversationUUID():void

----










[[messenger_events_tagaddedconversationevent]]
==== TagAddedConversationEvent

The event is triggered when a tag is added to a conversation.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Events`






===== Methods

[source%nowrap, php]
[#getconversationuuid]
----

public getConversationUUID():void

----










[[messenger_events_tagremovedconversationevent]]
==== TagRemovedConversationEvent

The event is triggered when a tag is removed from a conversation.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Events`






===== Methods

[source%nowrap, php]
[#getconversationuuid]
----

public getConversationUUID():void

----









[[messenger_conversations_models]]
===  Models
[[messenger_models_conversation]]
==== Conversation

The Conversation model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|uuid
    |link:http://php.net/string[string^]
    a|The UUID of the conversation
|shortId
    |link:http://php.net/string[string^]
    a|The Short ID of the Conversation
|plentyIdHash
    |link:http://php.net/string[string^]
    a|The plentyIdHash
|plentyId
    |link:http://php.net/int[int^]
    a|The plentyId of the relation contact
|inboxId
    |link:http://php.net/string[string^]
    a|The inboxId from the assistant
|title
    |link:http://php.net/string[string^]
    a|The Title of the Conversation
|conversationRelation
    |link:http://php.net/array[array^]
    a|The relations to other entities
|tagIds
    |link:http://php.net/array[array^]
    a|Array of tag IDs
|isClosed
    |link:http://php.net/bool[bool^]
    a|Boolean that indicates if the conversation is closed
|isDeleted
    |link:http://php.net/bool[bool^]
    a|Boolean that indicates if the conversation is deleted
|referrer
    |        xref:Messenger.adoc#messenger_models_messagereferrer[`MessageReferrer`]
    a|Array of referrers
|readBy
    |link:http://php.net/array[array^]
    a|Array of user ids (int)
|subscribers
    |        xref:Messenger.adoc#messenger_models_conversationsubscribers[`ConversationSubscribers`]
    a|Subscribers of the conversation
|createdAt
    |
    a|Creation Date
|updatedAt
    |
    a|Update Date
|deletedAt
    |
    a|Deletion Date
|deadline
    |
    a|Deadline Date
|followUpDate
    |
    a|FollowUpDate Date
|messages
    |link:http://php.net/array[array^]
    a|Conversation messages
|
    |link:http://php.net/int[int^]
    a|attachmentsCount Attachment messages count
|
    |link:http://php.net/int[int^]
    a|billedMsgCount Conversation billed msg count
|
    |link:http://php.net/int[int^]
    a|billedMinutesCount Conversation billed minutes count
|
    |link:http://php.net/bool[bool^]
    a|validRelation Conversation has the relations validated
|priorityId
    |link:http://php.net/string[string^]
    a|The Priority of the Conversation
|from
    |        xref:Messenger.adoc#messenger_models_conversationfrom[`ConversationFrom`]
    a|Conversation from
|typeId
    |link:http://php.net/int[int^]
    a|ID of conversation type
|typePosition
    |link:http://php.net/int[int^]
    a|Sort order of conversation type
|statusId
    |link:http://php.net/int[int^]
    a|ID of conversation status
|statusPosition
    |link:http://php.net/int[int^]
    a|Sort order of conversation status
|hasWhisperedMessages
    |link:http://php.net/bool[bool^]
    a|Flag that indicates if a conversation contains whispered messages
|messagesTitles
    |link:http://php.net/array[array^]
    a|Array of all message titles
|messagesBodies
    |link:http://php.net/array[array^]
    a|Array with all message bodies stripped of tags
|messagesTags
    |link:http://php.net/array[array^]
    a|Array with all tag ID's from all messages
|messagesReferrers
    |link:http://php.net/array[array^]
    a|Array with all referrers from all messages
|messagesFroms
    |link:http://php.net/array[array^]
    a|Array with all from fields from all messages
|replyTo
    |link:http://php.net/array[array^]
    a|
|messagesPaths
    |link:http://php.net/array[array^]
    a|Array with s3 messages paths
|messagesIds
    |link:http://php.net/array[array^]
    a|Array with all messages UUID's
|isMigratedToEs
    |link:http://php.net/int[int^]
    a|Flag that indicates if the conversation is synced to ES (used during messenger migration to new structure)
|isArchived
    |link:http://php.net/bool[bool^]
    a|Flag that indicates if the conversation is archived
|conversationPreview
    |link:http://php.net/string[string^]
    a|Strip last the message from messagesBodies to 200 characters, used for preview.
|categoryId
    |link:http://php.net/int[int^]
    a|Flag that indicates if the conversation is archived
|linkedFolders
    |link:http://php.net/array[array^]
    a|List of linked folders
|marketplacesMetadata
    |link:http://php.net/array[array^]
    a|marketplaces Meta data
|owners
    |link:http://php.net/array[array^]
    a|Conversation Owners
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationcategory]]
==== ConversationCategory

The ConversationCategory model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|names
    |link:http://php.net/array[array^]
    a|Collection of category names for different languages
|types
    |link:http://php.net/array[array^]
    a|Collection of types that belong to that category
|id
    |link:http://php.net/int[int^]
    a|The ID of the type
|position
    |link:http://php.net/int[int^]
    a|The position of the type (used in sorting)
|userId
    |link:http://php.net/int[int^]
    a|The user ID which performed the last update
|icon
    |link:http://php.net/string[string^]
    a|The icon for messenger tab
|iconType
    |link:http://php.net/string[string^]
    a|The icon type
|isDeleted
    |link:http://php.net/bool[bool^]
    a|Flag that indicates if the type was deleted
|isEnabled
    |link:http://php.net/bool[bool^]
    a|Flag that indicates if the type is enabled
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationcategorynames]]
==== ConversationCategoryNames

The ConversationCategoryNames model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|lang
    |link:http://php.net/string[string^]
    a|The language of the name
|name
    |link:http://php.net/string[string^]
    a|The category name
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationfolder]]
==== ConversationFolder

The Conversation model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|uuid
    |link:http://php.net/string[string^]
    a|The UUID of the folder
|name
    |link:http://php.net/string[string^]
    a|The name of the folder
|userId
    |link:http://php.net/int[int^]
    a|The user ID which is the folder owner
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationfolderproperty]]
==== ConversationFolderProperty

The ConversationFolderProperty model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|userId
    |link:http://php.net/string[string^]
    a|
|foldersUuids
    |link:http://php.net/array[array^]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationfrom]]
==== ConversationFrom

The ConversationFrom model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|type
    |link:http://php.net/string[string^]
    a|The type of the from instance (one of {@link ConversationFrom::FROM_TYPE_USER},
{@link ConversationFrom::FROM_TYPE_CONTACT} and {@link ConversationFrom::FROM_TYPE_EMAIL})
|value
    |
    a|The value of the instance. For type {@link ConversationFrom::FROM_TYPE_EMAIL} it is a string (the email)
and the id of the user or the contact otherwise.
|name
    |link:http://php.net/string[string^]
    a|An optional name for the instance, e.g. the real name for type {@link ConversationFrom::FROM_TYPE_EMAIL}
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationowner]]
==== ConversationOwner

The ConversationOwners model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|roleId
    |link:http://php.net/int[int^]
    a|The id of the role
|ownerId
    |link:http://php.net/int[int^]
    a|The user id value
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationrelation]]
==== ConversationRelation

The ConversationRelation model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|type
    |link:http://php.net/string[string^]
    a|The type of the relation (one of {@link ConversationRelation::RELATION_TYPE_CONTACT}, {@link ConversationRelation::RELATION_TYPE_ORDER},
{@link ConversationRelation::RELATION_TYPE_EMAIL}, {@link ConversationRelation::RELATION_TYPE_PAYMENT})
{@link ConversationRelation::RELATION_TYPE_USER}, {@link ConversationRelation::RELATION_AMAZON_ORDER})
{@link ConversationRelation::RELATION_TYPE_CONTACT_EMAIL}, {@link ConversationRelation::RELATION_TYPE_CONTACT_ID})
{@link ConversationRelation::RELATION_TYPE_CONTACT_NUMBER}, {@link ConversationRelation::RELATION_TYPE_INVOICE_NUMBER})
{@link ConversationRelation::RELATION_TYPE_ORDER_ID}), {@link ConversationRelation::RELATION_ORDER_EXTERNAL_ID})
|value
    |
    a|Array with entity values
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationstatus]]
==== ConversationStatus

The ConversationStatus model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|names
    |link:http://php.net/array[array^]
    a|Collection of status names for different languages
|id
    |link:http://php.net/int[int^]
    a|The ID of the status
|position
    |link:http://php.net/int[int^]
    a|The position of the status (used in sorting)
|userId
    |link:http://php.net/int[int^]
    a|The suer ID which performed the last update
|isDeleted
    |link:http://php.net/bool[bool^]
    a|Flag that indicates if the status was deleted
|
    |link:http://php.net/int[int^]
    a|typeId The ID of the parent type
|
    |link:http://php.net/int[int^]
    a|progress Percentage of progress (0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)
|
    |link:http://php.net/string[string^]
    a|colour Color of the status background (example: #0084ff)
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationstatusnames]]
==== ConversationStatusNames

The ConversationStatusNames model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|lang
    |link:http://php.net/string[string^]
    a|The language of the name
|name
    |link:http://php.net/string[string^]
    a|The name of the status
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationsubscribers]]
==== ConversationSubscribers

The ConversationSubscribers model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|userIds
    |link:http://php.net/array[array^]
    a|The array of userIds subscribed to a message
|roleIds
    |link:http://php.net/array[array^]
    a|The array of roleIds subscribed to a message (not used)
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationtype]]
==== ConversationType

The ConversationType model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|names
    |link:http://php.net/array[array^]
    a|Collection of type names for different languages
|statuses
    |link:http://php.net/array[array^]
    a|Collection of statuses that belong to that type
|id
    |link:http://php.net/int[int^]
    a|The ID of the type
|position
    |link:http://php.net/int[int^]
    a|The position of the type (used in sorting)
|userId
    |link:http://php.net/int[int^]
    a|The suer ID which performed the last update
|isDeleted
    |link:http://php.net/bool[bool^]
    a|Flag that indicates if the type was deleted
|categoryId
    |link:http://php.net/bool[bool^]
    a|The ID of the parent category
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_conversationtypenames]]
==== ConversationTypeNames

The ConversationTypeNames model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|lang
    |link:http://php.net/string[string^]
    a|The language of the name
|name
    |link:http://php.net/string[string^]
    a|The type name
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_searchreceiver]]
==== SearchReceiver

The Conversation model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the entity
|name
    |link:http://php.net/string[string^]
    a|The name of the entity
|email
    |link:http://php.net/string[string^]
    a|The email of the entity
|lang
    |link:http://php.net/string[string^]
    a|The lang of the entity
|externalId
    |link:http://php.net/string[string^]
    a|The external ID of the entity
|type
    |link:http://php.net/string[string^]
    a|The entity type
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[messenger_ebay]]
== Ebay

[[messenger_ebay_contracts]]
===  Contracts
[[messenger_contracts_ebayaccountsrepositorycontract]]
==== EbayAccountsRepositoryContract

The EbayAccountsRepositoryContract is the interface for Merketplaces Ebay EbayAccount



===== Namespace

`Plenty\Modules\Messenger\Conversations\Marketplaces\Ebay\Contracts`






===== Methods

[source%nowrap, php]
[#listebayaccounts]
----

public listEbayAccounts():Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Get all ebay accounts

[source%nowrap, php]
[#getactiveebayaccounts]
----

public getActiveEbayAccounts():Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Get all ebay active accounts

[source%nowrap, php]
[#createebayaccount]
----

public createEbayAccount($data):Plenty\Modules\Messenger\Conversations\Marketplaces\Ebay\Models\EbayAccount

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_ebayaccount[`EbayAccount`]


Create a new Ebay account

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#updateebayaccounts]
----

public updateEbayAccounts($data):Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Update an existing array of Ebay account settings

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deleteebayaccount]
----

public deleteEbayAccount($accountSettingsId):bool

----







Delete an Ebay account (the account will be flagged with deleted=1)
The action will not delete the account

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$accountSettingsId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getebayaccount]
----

public getEbayAccount($accountSettingsId):Plenty\Modules\Messenger\Conversations\Marketplaces\Ebay\Models\EbayAccount

----




====== *Return type:*        xref:Messenger.adoc#messenger_models_ebayaccount[`EbayAccount`]


Get Ebay account details

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$accountSettingsId`
|link:http://php.net/int[int^]
a|
|===


[[messenger_ebay_models]]
===  Models
[[messenger_models_ebayaccount]]
==== EbayAccount

The Ebay Settings model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Marketplaces\Ebay\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The id of the messenger ebay settings account
|ebayAccountId
    |link:http://php.net/int[int^]
    a|The id of the ebay account
|name
    |link:http://php.net/string[string^]
    a|The name of the ebay account
|isEnabled
    |link:http://php.net/bool[bool^]
    a|The status of the messenger ebay settings account
|isDeleted
    |link:http://php.net/bool[bool^]
    a|The deleted status of the messenger ebay settings account
|settings
    |link:http://php.net/array[array^]
    a|The list of settings of the messenger ebay settings account
*
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_marketplacesmetadataebayproperties]]
==== MarketplacesMetaDataEbayProperties

The Ebay properties model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Marketplaces\Ebay\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|ebayCreatedAt
    |link:http://php.net/string[string^]
    a|The creation datetime
|ebaySenderName
    |link:http://php.net/string[string^]
    a|The name of the sender
|ebayMessageId
    |link:http://php.net/string[string^]
    a|The message id
|ebayExternalMessageId
    |link:http://php.net/string[string^]
    a|The external message id
|ebaySellerName
    |link:http://php.net/string[string^]
    a|The name of the seller
|ebayItemId
    |link:http://php.net/string[string^]
    a|The id of the item
|ebayItemEndTime
    |link:http://php.net/string[string^]
    a|The end time of the item
|ebayType
    |link:http://php.net/string[string^]
    a|Ebay message type
|ebayResponseEnabled
    |link:http://php.net/bool[bool^]
    a|Ebay response enabled/disabled
|ebayAccountId
    |link:http://php.net/int[int^]
    a|Ebay account ID
|ebayMessengerAccountId
    |link:http://php.net/int[int^]
    a|Messenger Ebay account ID
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_models_settings]]
==== Settings

The EbayAccount&#039;s settings model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Marketplaces\Ebay\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|markAsRead
    |link:http://php.net/bool[bool^]
    a|Mark the conversation as read
|defaultStatus
    |link:http://php.net/int[int^]
    a|The conversation's default status
|defaultType
    |link:http://php.net/int[int^]
    a|The conversation's default status
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[messenger_marketplaces]]
== Marketplaces

[[messenger_marketplaces_models]]
===  Models
[[messenger_models_messagemarketplacesmetadata]]
==== MessageMarketplacesMetaData

The marketplaces data model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Marketplaces\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|ebayProperties
    |        xref:Messenger.adoc#messenger_models_marketplacesmetadataebayproperties[`MarketplacesMetaDataEbayProperties`]
    a|Ebay properties
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[messenger_models]]
== Models

[[messenger_models_roles]]
===  Roles
[[messenger_roles_conversationrole]]
==== ConversationRole

The ConversationRole model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models\Roles`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|
|position
    |link:http://php.net/int[int^]
    a|
|userId
    |link:http://php.net/int[int^]
    a|
|isDeleted
    |link:http://php.net/bool[bool^]
    a|
|names
    |        xref:Messenger.adoc#messenger_roles_conversationrolenames[`ConversationRoleNames`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[messenger_roles_conversationrolenames]]
==== ConversationRoleNames

The ConversationRoleNames model of the messenger.



===== Namespace

`Plenty\Modules\Messenger\Conversations\Models\Roles`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|lang
    |link:http://php.net/string[string^]
    a|
|name
    |link:http://php.net/string[string^]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[messenger_ticketsystemmigration]]
== TicketSystemMigration

[[messenger_ticketsystemmigration_contracts]]
===  Contracts
[[messenger_contracts_ticketmigrationstatusrepositorycontract]]
==== TicketMigrationStatusRepositoryContract

TicketMigrationRepositoryContract is the interface for the ticketMigrationStatus repository.
 * This interface allows to list, get, create ticketMigrationStatus.



===== Namespace

`Plenty\Modules\Messenger\TicketSystemMigration\Contracts`






===== Methods

[source%nowrap, php]
[#saveticketmigrationstatus]
----

public saveTicketMigrationStatus($data):bool

----







Adds a new ticketMigrationStatus entry

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticketMigrationStatus data as array.
|===


[[messenger_ticketsystemmigration_models]]
===  Models
[[messenger_models_ticketmigrationstatus]]
==== TicketMigrationStatus

The ticket migration status model.



===== Namespace

`Plenty\Modules\Messenger\TicketSystemMigration\Models`

===== Referenceable
id




.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The PK ID
|ticketId
    |link:http://php.net/int[int^]
    a|The ticket ID
|migrationStatus
    |link:http://php.net/int[int^]
    a|The status of the migration that took place:
<ul>
<li> failed </li>
<li> migrated</li>
</ul>
|errorMessage
    |link:http://php.net/string[string^]
    a|The details of the failed migration
|conversationId
    |link:http://php.net/string[string^]
    a|The new conversation Id that the ticket is mapped to
|createdAt
    |
    a|The date the ticket status of the migration was created
|updatedAt
    |
    a|The date the ticket status of the migration was last updated
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

