:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[notifications_notifications]]
== Notifications

[[notifications_notifications_contracts]]
===  Contracts
[[notifications_contracts_notificationsrepositorycontract]]
==== NotificationsRepositoryContract

Plugin Notifications Service



===== Namespace

`Plenty\Modules\Notifications\Contracts`






===== Methods

[source%nowrap, php]
[#addnotification]
----

public addNotification($notificationBuiltWithNotificationBuilder):array

----







Add a Notification in the system

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$notificationBuiltWithNotificationBuilder`
|link:http://php.net/array[array^]
a|An array built with NotificationBuilder::build() method
|===


[source%nowrap, php]
[#fetchnotifications]
----

public fetchNotifications($queryBuiltWithNotificationsQueryBuilder, $page, $itemsPerPage):Plenty\Repositories\Models\UnspecifiedLengthPaginationResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_unspecifiedlengthpaginationresponse[`UnspecifiedLengthPaginationResponse`]


Fetch a list of short/incomplete notifications, containing only the subject. To be used for listing purposes.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$queryBuiltWithNotificationsQueryBuilder`
|link:http://php.net/array[array^]
a|An array built with NotificationsQueryBuilder::build() method

a|`$page`
|link:http://php.net/int[int^]
a|The page number, starting from 1

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of notifications per page
|===


[source%nowrap, php]
[#fetchnotificationsdetails]
----

public fetchNotificationsDetails($notificationsFetchDetailsQuery):array

----







Fetch all the details of a Notification based on its id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$notificationsFetchDetailsQuery`
|link:http://php.net/array[array^]
a|An array built with NotificationsFetchDetailsQueryBuilder::build() method
|===


[source%nowrap, php]
[#acknowledgenotifications]
----

public acknowledgeNotifications($queryBuiltWithNotificationsAcknowledgeQueryBuilder):bool

----







Mark a Notification as acknowledged.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$queryBuiltWithNotificationsAcknowledgeQueryBuilder`
|link:http://php.net/array[array^]
a|An array built with NotificationsAcknowledgeQueryBuilder::build() method
|===


[source%nowrap, php]
[#getnotificationscount]
----

public getNotificationsCount($queryBuiltWithNotificationsQueryBuilder):int

----







Retrieve the current unread Notifications count

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$queryBuiltWithNotificationsQueryBuilder`
|link:http://php.net/array[array^]
a|An array built with NotificationsQueryBuilder::build() method
|===


[[notifications_notifications_models]]
===  Models
[[notifications_models_notification]]
==== Notification

The Notification Model



===== Namespace

`Plenty\Modules\Notifications\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[notifications_models_notificationcontent]]
==== NotificationContent

The Notification Content model



===== Namespace

`Plenty\Modules\Notifications\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[notifications_models_notificationuisettings]]
==== NotificationUISettings

The Notification user interface settings



===== Namespace

`Plenty\Modules\Notifications\Models`






===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

