

[[notifications_notifications]]
== Notifications

[[notifications_notifications_contracts]]
===  Contracts
[[notifications_contracts_notificationsrepositorycontract]]
==== NotificationsRepositoryContract

Plugin Notifications Service



===== Namespace

`Plenty\Modules\Notifications\Contracts`






===== Methods

[source%nowrap, php]
----

public addNotification($notificationBuiltWithNotificationBuilder):array

----

    





Add a Notification in the system

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$notificationBuiltWithNotificationBuilder`
a|An array built with NotificationBuilder::build() method
|===


[source%nowrap, php]
----

public fetchNotifications($queryBuiltWithNotificationsQueryBuilder, $page, $itemsPerPage):Plenty\Repositories\Models\UnspecifiedLengthPaginationResponse

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_unspecifiedlengthpaginationresponse[`UnspecifiedLengthPaginationResponse`]


Fetch a list of short/incomplete notifications, containing only the subject. To be used for listing purposes.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$queryBuiltWithNotificationsQueryBuilder`
a|An array built with NotificationsQueryBuilder::build() method

|link:http://php.net/int[int^]
a|`$page`
a|The page number, starting from 1

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of notifications per page
|===


[source%nowrap, php]
----

public fetchNotificationsDetails($notificationsFetchDetailsQuery):array

----

    





Fetch all the details of a Notification based on its id.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$notificationsFetchDetailsQuery`
a|An array built with NotificationsFetchDetailsQueryBuilder::build() method
|===


[source%nowrap, php]
----

public acknowledgeNotifications($queryBuiltWithNotificationsAcknowledgeQueryBuilder):bool

----

    





Mark a Notification as acknowledged.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$queryBuiltWithNotificationsAcknowledgeQueryBuilder`
a|An array built with NotificationsAcknowledgeQueryBuilder::build() method
|===


[source%nowrap, php]
----

public getNotificationsCount($queryBuiltWithNotificationsQueryBuilder):int

----

    





Retrieve the current unread Notifications count

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$queryBuiltWithNotificationsQueryBuilder`
a|An array built with NotificationsQueryBuilder::build() method
|===


[[notifications_notifications_models]]
===  Models
[[notifications_models_notification]]
==== Notification

The Notification Model



===== Namespace

`Plenty\Modules\Notifications\Models`






===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[notifications_models_notificationcontent]]
==== NotificationContent

The Notification Content model



===== Namespace

`Plenty\Modules\Notifications\Models`






===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

