:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[payment_payment]]
== Payment

[[payment_payment_contracts]]
===  Contracts
[[payment_contracts_paymentcontactrelationrepositorycontract]]
==== PaymentContactRelationRepositoryContract

The PaymentContactRelationRepositoryContract is the interface for the payment contact relation repository. Create and delete relations between payments and contact.



===== Namespace

`Plenty\Modules\Payment\Contracts`






===== Methods

[source%nowrap, php]
[#createcontactrelation]
----

public createContactRelation($payment, $contact):Plenty\Modules\Payment\Models\PaymentContactRelation

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentcontactrelation[`PaymentContactRelation`]


Creates a payment contact relation.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|The ID of the payment

a|`$contact`
|        xref:Account.adoc#account_models_contact[`Contact`]
a|The ID of the contact
|===


[source%nowrap, php]
[#deletecontactrelation]
----

public deleteContactRelation($payment):void

----







Deletes a payment contact relation.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|The ID of the payment
|===



[[payment_contracts_paymentmatcherrepositorycontract]]
==== PaymentMatcherRepositoryContract

The PaymentMatcherRepositoryContract automatically matching payments to an order.



===== Namespace

`Plenty\Modules\Payment\Contracts`






===== Methods

[source%nowrap, php]
[#checkmappayment]
----

public checkMapPayment($mopId, $data):void

----







Checks and save the payment data

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mopId`
|link:http://php.net/int[int^]
a|

a|`$data`
|
a|
|===


[source%nowrap, php]
[#checkmapfindassignpayment]
----

public checkMapFindAssignPayment($mopId, $data):string

----







Checks and assigns payment data.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mopId`
|link:http://php.net/int[int^]
a|

a|`$data`
|
a|
|===


[source%nowrap, php]
[#findassignpayment]
----

public findAssignPayment($payment):void

----







Finds and assigns payment data

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===


[source%nowrap, php]
[#getmatchingratesforpayment]
----

public getMatchingRatesForPayment($paymentId):array

----







Gets the matching of payment data with orders.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getmatchingorassigningratesforpayment]
----

public getMatchingOrAssigningRatesForPayment($paymentId):array

----







Get matching or assigning rate list for a payment

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentId`
|link:http://php.net/int[int^]
a|
|===



[[payment_contracts_paymentorderrelationrepositorycontract]]
==== PaymentOrderRelationRepositoryContract

The PaymentOrderRelationRepositoryContract is the interface for the payment order relation repository. Create and delete relations between payments and orders.



===== Namespace

`Plenty\Modules\Payment\Contracts`






===== Methods

[source%nowrap, php]
[#createorderrelation]
----

public createOrderRelation($payment, $order):Plenty\Modules\Payment\Models\PaymentOrderRelation

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentorderrelation[`PaymentOrderRelation`]


Creates a payment order relation.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|The ID of the payment

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|The ID of the order
|===


[source%nowrap, php]
[#findorderrelation]
----

public findOrderRelation($payment):Plenty\Modules\Payment\Models\PaymentOrderRelation

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentorderrelation[`PaymentOrderRelation`]


Gets the payment order relation.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===


[source%nowrap, php]
[#deleteorderrelation]
----

public deleteOrderRelation($payment):void

----







Deletes a payment order relation.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|The ID of the payment
|===


[source%nowrap, php]
[#createorderrelationwithvalidation]
----

public createOrderRelationWithValidation($paymentId, $orderId, $matchingRate = null, $allowMultiplePaymentsPerOrder = false):Plenty\Modules\Payment\Models\PaymentOrderRelation

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentorderrelation[`PaymentOrderRelation`]


Assign a payment to an order ID if order ID is valid and order ID doesn&#039;t have a payment assigned.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentId`
|link:http://php.net/int[int^]
a|

a|`$orderId`
|link:http://php.net/int[int^]
a|

a|`$matchingRate`
|link:http://php.net/int[int^]
a|

a|`$allowMultiplePaymentsPerOrder`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#createorderrelationbyinvoicenumber]
----

public createOrderRelationByInvoiceNumber($paymentId, $invoiceNumber, $allowMultiplePaymentsPerOrder = false):Plenty\Modules\Payment\Models\PaymentOrderRelation

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentorderrelation[`PaymentOrderRelation`]


Assign a payment to an order if invoice number is valid.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentId`
|link:http://php.net/int[int^]
a|

a|`$invoiceNumber`
|link:http://php.net/string[string^]
a|

a|`$allowMultiplePaymentsPerOrder`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#autoassignpayments]
----

public autoAssignPayments($paymentIds):array

----







Bulk auto assign payments

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentIds`
|link:http://php.net/array[array^]
a|
|===



[[payment_contracts_paymentpropertyrepositorycontract]]
==== PaymentPropertyRepositoryContract

The PaymentPropertyRepositoryContract is the interface for the payment property repository. List, get, create and update payment properties.



===== Namespace

`Plenty\Modules\Payment\Contracts`






===== Methods

[source%nowrap, php]
[#all]
----

public all():array

----







Lists properties.

[source%nowrap, php]
[#findbypropertyid]
----

public findByPropertyId($propertyId):array

----







Gets a property. The ID of the payment property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|The ID of the payment property
|===


[source%nowrap, php]
[#allbypaymentid]
----

public allByPaymentId($paymentId):array

----







Lists properties of a payment. The ID of the payment must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentId`
|link:http://php.net/int[int^]
a|The ID of the payment
|===


[source%nowrap, php]
[#allbytypeid]
----

public allByTypeId($typeId):array

----







Lists properties of a property type. The ID of the property type must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$typeId`
|link:http://php.net/int[int^]
a|The ID of the payment property type. The following property types are available:
<ul>
    <li>Transaction ID = 1</li>
    <li>Reference ID = 2</li>
    <li>Booking text = 3</li>
    <li>Transaction password = 4</li>
    <li>Transaction code = 5</li>
    <li>Authorisation ID = 6</li>
    <li>Capture ID = 7</li>
    <li>Refund ID = 8</li>
    <li>Credit note ID = 9</li>
    <li>Order reference = 10</li>
    <li>Name of the sender = 11</li>
    <li>Email of the sender = 12</li>
    <li>The sender's sort code = 13</li>
    <li>The sender's bank name = 14</li>
    <li>The sender's bank account number = 15</li>
    <li>The holder of the bank account = 16</li>
    <li>The country of the sender's bank account = 17</li>
    <li>The sender's IBAN = 18</li>
    <li>The sender's BIC = 19</li>
    <li>Name of the recipient = 20</li>
    <li>The recipient's bank account = 21</li>
    <li>Reference text of the payment = 22</li>
    <li>Payment origin = 23</li>
    <li>Shipping address ID = 24</li>
    <li>Invoice address ID = 25</li>
    <li>Item buyer = 26</li>
    <li>Item number = 27</li>
    <li>Item transaction ID = 28</li>
    <li>External transaction type = 29</li>
    <li>External transaction status = 30</li>
</ul>
|===


[source%nowrap, php]
[#findbycreateddateinterval]
----

public findByCreatedDateInterval($startDate, $endDate):array

----







Lists properties by creation date. The start and the end of the date range must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$startDate`
|link:http://php.net/string[string^]
a|The start date of the date range for the date of creation of the property

a|`$endDate`
|link:http://php.net/string[string^]
a|The end date of the date range for the date of creation of the property
|===


[source%nowrap, php]
[#createproperty]
----

public createProperty($data):Plenty\Modules\Payment\Models\PaymentProperty

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentproperty[`PaymentProperty`]


Creates a payment property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#changeproperty]
----

public changeProperty($data):Plenty\Modules\Payment\Models\PaymentProperty

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentproperty[`PaymentProperty`]


Updates a payment property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|        xref:Payment.adoc#payment_models_paymentproperty[`PaymentProperty`]
a|
|===



[[payment_contracts_paymentpropertytypenamerepositorycontract]]
==== PaymentPropertyTypeNameRepositoryContract

The PaymentPropertyTypeNameRepositoryContract is the interface for the repository of payment property type names. List, get, create and update payment property names.



===== Namespace

`Plenty\Modules\Payment\Contracts`






===== Methods

[source%nowrap, php]
[#alltypenames]
----

public allTypeNames($lang):array

----







Lists payment property type names. The language of the property type names must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|The language of the payment property type name
|===


[source%nowrap, php]
[#findbynameid]
----

public findByNameId($nameId):array

----







Finds a payment property type name. The ID of the payment property type name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$nameId`
|link:http://php.net/int[int^]
a|The ID of the payment property type name
|===


[source%nowrap, php]
[#createtypename]
----

public createTypeName($data):Plenty\Modules\Payment\Models\PaymentPropertyTypeName

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentpropertytypename[`PaymentPropertyTypeName`]


Creates a payment property type name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#changeproperty]
----

public changeProperty($data):array

----







Updates a payment property type name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===



[[payment_contracts_paymentpropertytyperepositorycontract]]
==== PaymentPropertyTypeRepositoryContract

The PaymentPropertyTypeRepositoryContract is the interface for the payment property type repository. List, get, create and update payment properties.



===== Namespace

`Plenty\Modules\Payment\Contracts`






===== Methods

[source%nowrap, php]
[#alltypes]
----

public allTypes($lang):array

----







Lists payment property types. The language of the property type must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|The language of the payment property type
|===


[source%nowrap, php]
[#findtypesbyid]
----

public findTypesById($id, $lang):array

----







Gets a payment property type. The ID of the property type must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the payment property type. The following property types are available:
<ul>
    <li>Transaction ID = 1</li>
    <li>Reference ID = 2</li>
    <li>Booking text = 3</li>
    <li>Transaction password = 4</li>
    <li>Transaction code = 5</li>
    <li>Authorisation ID = 6</li>
    <li>Capture ID = 7</li>
    <li>Refund ID = 8</li>
    <li>Credit note ID = 9</li>
    <li>Order reference = 10</li>
    <li>Name of the sender = 11</li>
    <li>Email of the sender = 12</li>
    <li>The sender's sort code = 13</li>
    <li>The sender's bank name = 14</li>
    <li>The sender's bank account number = 15</li>
    <li>The holder of the bank account = 16</li>
    <li>The country of the sender's bank account = 17</li>
    <li>The sender's IBAN = 18</li>
    <li>The sender's BIC = 19</li>
    <li>Name of the recipient = 20</li>
    <li>The recipient's bank account = 21</li>
    <li>Reference text of the payment = 22</li>
    <li>Payment origin = 23</li>
    <li>Shipping address ID = 24</li>
    <li>Invoice address ID = 25</li>
    <li>Item buyer = 26</li>
    <li>Item number = 27</li>
    <li>Item transaction ID = 28</li>
    <li>External transaction type = 29</li>
    <li>External transaction status = 30</li>
</ul>

a|`$lang`
|link:http://php.net/string[string^]
a|The language of the payment property type
|===


[source%nowrap, php]
[#createtype]
----

public createType($data):Plenty\Modules\Payment\Models\PaymentPropertyType

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentpropertytype[`PaymentPropertyType`]


Creates a payment property type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#changeproperty]
----

public changeProperty($data):Plenty\Modules\Payment\Models\PaymentPropertyType

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentpropertytype[`PaymentPropertyType`]


Updates a payment property type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===



[[payment_contracts_paymentrepositorycontract]]
==== PaymentRepositoryContract

The PaymentRepositoryContract is the interface for the payment repository. List, get, create and update payments. Payments can come into plentymarkets automatically or can be booked manually. Existing payments can be filtered by payment method, by ID, by payment status, by transaction type, by order or by date. Existing payments can also be updated.



===== Namespace

`Plenty\Modules\Payment\Contracts`






===== Methods

[source%nowrap, php]
[#getall]
----

public getAll($itemsPerPage = 50, $page = 1):array

----







Lists payments.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of items to list per page

a|`$page`
|link:http://php.net/int[int^]
a|The page of results to search for
|===


[source%nowrap, php]
[#search]
----

public search($page = 1, $itemsPerPage = \Plenty\Modules\Payment\Models\Payment::MAX_ITEMS_PER_PAGE, $with = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Searches for a list of payments.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The shown page. Default value is 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The items shown per page. Default value is 50.

a|`$with`
|link:http://php.net/array[array^]
a|The relations to be loaded.
|===


[source%nowrap, php]
[#getpaymentbyid]
----

public getPaymentById($paymentId):Plenty\Modules\Payment\Models\Payment

----




====== *Return type:*        xref:Payment.adoc#payment_models_payment[`Payment`]


Gets a payment. The ID of the payment must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentId`
|link:http://php.net/int[int^]
a|The ID of the payment
|===


[source%nowrap, php]
[#getpaymentsbymethodid]
----

public getPaymentsByMethodId($methodId, $itemsPerPage = 50, $page = 1):array

----







Lists payments of a payment method. The ID of the payment method must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$methodId`
|link:http://php.net/int[int^]
a|The ID of the payment method

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of items to list per page

a|`$page`
|link:http://php.net/int[int^]
a|The page of results to search for
|===


[source%nowrap, php]
[#getpaymentsbystatusid]
----

public getPaymentsByStatusId($statusId, $itemsPerPage = 50, $page = 1):array

----







Lists payments of a payment status. The ID of the payment status must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$statusId`
|link:http://php.net/int[int^]
a|The ID of the payment status

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of items to list per page

a|`$page`
|link:http://php.net/int[int^]
a|The page of results to search for
|===


[source%nowrap, php]
[#getpaymentsbytransactiontype]
----

public getPaymentsByTransactionType($transactionType, $itemsPerPage = 50, $page = 1):array

----







Lists payments of a transaction type. The transaction type must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$transactionType`
|link:http://php.net/int[int^]
a|The transaction type of the payment

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of items to list per page

a|`$page`
|link:http://php.net/int[int^]
a|The page of results to search for
|===


[source%nowrap, php]
[#getpaymentsbyorderid]
----

public getPaymentsByOrderId($orderId):array

----







Lists payments of an order. The ID of the order must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order
|===


[source%nowrap, php]
[#getpaymentsbyimportdateinterval]
----

public getPaymentsByImportDateInterval($startDate, $endDate, $itemsPerPage = 50, $page = 1):array

----







Lists payments by import date. The start and the end of the date range must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$startDate`
|link:http://php.net/string[string^]
a|The start date of the date range for the import date of the payment

a|`$endDate`
|link:http://php.net/string[string^]
a|The end date of the date range for the import date of the payment

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of items to list per page

a|`$page`
|link:http://php.net/int[int^]
a|The page of results to search for
|===


[source%nowrap, php]
[#getpaymentsbyentrydateinterval]
----

public getPaymentsByEntryDateInterval($startDate, $endDate, $itemsPerPage = 50, $page = 1):array

----







Lists payments by entry date. The start and the end of the date range must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$startDate`
|link:http://php.net/string[string^]
a|The start date of the date range for the entry date of the payment

a|`$endDate`
|link:http://php.net/string[string^]
a|The end date of the date range for the entry date of the payment

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of items to list per page

a|`$page`
|link:http://php.net/int[int^]
a|The page of results to search for
|===


[source%nowrap, php]
[#getpaymentsbypropertytypeandvalue]
----

public getPaymentsByPropertyTypeAndValue($propertyTypeId, $propertyValue = &quot;&quot;, $itemsPerPage = 50, $page = 1):void

----







Lists payments by payment property type and value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyTypeId`
|link:http://php.net/int[int^]
a|The property type

a|`$propertyValue`
|
a|The property value

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of items to list per page

a|`$page`
|link:http://php.net/int[int^]
a|The page of results to search for
|===


[source%nowrap, php]
[#createpayment]
----

public createPayment($data):Plenty\Modules\Payment\Models\Payment

----




====== *Return type:*        xref:Payment.adoc#payment_models_payment[`Payment`]


Creates a payment.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#updatepayment]
----

public updatePayment($data):Plenty\Modules\Payment\Models\Payment

----




====== *Return type:*        xref:Payment.adoc#payment_models_payment[`Payment`]


Updates a payment.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#getstatusconstants]
----

public getStatusConstants():array

----









[source%nowrap, php]
[#getoriginconstants]
----

public getOriginConstants():array

----









[source%nowrap, php]
[#deletepayment]
----

public deletePayment($paymentId):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#splitandassignpayment]
----

public splitAndAssignPayment($paymentId, $orderIds):bool

----







Split and assign a payment to given order IDs

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentId`
|link:http://php.net/int[int^]
a|

a|`$orderIds`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deletepayments]
----

public deletePayments($paymentIds):array

----







Bulk delete payments.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentIds`
|link:http://php.net/array[array^]
a|An array containing payment ids. Eg: [ids => [1, 2, 3]]
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[payment_payment_exceptions]]
===  Exceptions
[[payment_exceptions_paymentmatcherexception]]
==== PaymentMatcherException

Class PaymentMatcherException



===== Namespace

`Plenty\Modules\Payment\Exceptions`





[[payment_payment_models]]
===  Models
[[payment_models_payment]]
==== Payment

The payment model representing a received payment by a payment service provider.



===== Namespace

`Plenty\Modules\Payment\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the payment
|amount
    |link:http://php.net/float[float^]
    a|The amount of the payment
|exchangeRatio
    |link:http://php.net/float[float^]
    a|The exchange rate. Exchange rates are used if the default currency saved in plentymarkets differs from the currency of the order.
|parentId
    |link:http://php.net/int[int^]
    a|The ID of the parent payment
|deleted
    |link:http://php.net/int[int^]
    a|A deleted payment. Deleted payments have the value 1 and are not displayed in the plentymarkets back end.
|unaccountable
    |link:http://php.net/int[int^]
    a|An unassigned payment. Unassigned payments have the value 1.
|currency
    |link:http://php.net/string[string^]
    a|The currency of the payment in ISO 4217 code.
|type
    |link:http://php.net/string[string^]
    a|The payment type. Available types are credit and debit.
|hash
    |link:http://php.net/string[string^]
    a|The hash code of the payment. The hash code consists of 32 characters and is automatically generated.
|origin
    |link:http://php.net/int[int^]
    a|The origin of the payment. The following origins are available:
<ul>
    <li>Undefined = 0</li>
    <li>System = 1</li>
    <li>Manually = 2</li>
    <li>SOAP = 3</li>
    <li>Import = 4</li>
    <li>Split payment = 5</li>
    <li>Plugin = 6</li>
    <li>POS = 7</li>
</ul>
|receivedAt
    |link:http://php.net/string[string^]
    a|The time the payment was received
|importedAt
    |link:http://php.net/string[string^]
    a|The time the payment was imported
|status
    |link:http://php.net/int[int^]
    a|The <a href="https://developers.plentymarkets.com/en-gb/developers/main/rest-api-guides/getting-started.html#_payment_status_ids"  target="_blank">status</a> of the payment
|transactionType
    |link:http://php.net/int[int^]
    a|The transaction type of the payment. The following transaction types are available:
<ul>
    <li>Interim transaction report = 1</li>
    <li>Booked payment = 2</li>
    <li>Split payment = 3</li>
</ul>
|mopId
    |link:http://php.net/int[int^]
    a|The ID of the payment method
|parent
    |        xref:Payment.adoc#payment_models_payment[`Payment`]
    a|The parent payment
|children
    |
    a|
|method
    |        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]
    a|The payment method
|order
    |        xref:Payment.adoc#payment_models_paymentorderrelation[`PaymentOrderRelation`]
    a|
|contact
    |        xref:Payment.adoc#payment_models_paymentcontactrelation[`PaymentContactRelation`]
    a|
|histories
    |link:http://php.net/array[array^]
    a|The payment history
|properties
    |link:http://php.net/array[array^]
    a|The properties of the payment
|regenerateHash
    |link:http://php.net/bool[bool^]
    a|If $regenerateHash is true, regenerate the payment hash value. Default is false.
|updateOrderPaymentStatus
    |link:http://php.net/bool[bool^]
    a|If $updateOrderPaymentStatus is true, update the order payment status. Default is false.
|isSystemCurrency
    |link:http://php.net/bool[bool^]
    a|If $isSystemCurrency is false, the value will be converted to the standard currency with the provided exchange rate. If $isSystemCurrency is true, the value is not converted. Default is true.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[payment_models_paymentcontactrelation]]
==== PaymentContactRelation

The payment contact relation model



===== Namespace

`Plenty\Modules\Payment\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the payment order relation
|paymentId
    |link:http://php.net/int[int^]
    a|The ID of the payment
|contactId
    |link:http://php.net/int[int^]
    a|The ID of the contact
|assignedAt
    |link:http://php.net/string[string^]
    a|The time the payment contact relation was assigned
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[payment_models_paymentorderrelation]]
==== PaymentOrderRelation

The payment order relation model



===== Namespace

`Plenty\Modules\Payment\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the payment order relation
|paymentId
    |link:http://php.net/int[int^]
    a|The ID of the payment
|orderId
    |link:http://php.net/int[int^]
    a|The ID of the order
|assignedAt
    |link:http://php.net/string[string^]
    a|The time the payment order relation was assigned
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[payment_models_paymentproperty]]
==== PaymentProperty

The payment property model



===== Namespace

`Plenty\Modules\Payment\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the payment property
|paymentId
    |link:http://php.net/int[int^]
    a|The ID of the payment
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the property type. The following property types are available:
<ul>
    <li>Transaction ID = 1</li>
    <li>Reference ID = 2</li>
    <li>Booking text = 3</li>
    <li>Transaction password = 4</li>
    <li>Transaction code = 5</li>
    <li>Authorisation ID = 6</li>
    <li>Capture ID = 7</li>
    <li>Refund ID = 8</li>
    <li>Credit note ID = 9</li>
    <li>Order reference = 10</li>
    <li>Name of the sender = 11</li>
    <li>Email of the sender = 12</li>
    <li>The sender's sort code = 13</li>
    <li>The sender's bank name = 14</li>
    <li>The sender's bank account number = 15</li>
    <li>The holder of the bank account = 16</li>
    <li>The country of the sender's bank account = 17</li>
    <li>The sender's IBAN = 18</li>
    <li>The sender's BIC = 19</li>
    <li>Name of the recipient = 20</li>
    <li>The recipient's bank account = 21</li>
    <li>Reference text of the payment = 22</li>
    <li>Payment origin = 23</li>
    <li>Shipping address ID = 24</li>
    <li>Invoice address ID = 25</li>
    <li>Item buyer = 26</li>
    <li>Item number = 27</li>
    <li>Item transaction ID = 28</li>
    <li>External transaction type = 29</li>
    <li>External transaction status = 30</li>
    <li>The receiver's IBAN = 31</li>
    <li>The receiver's BIC = 32</li>
    <li>Transaction fee = 33</li>
    <li>Transaction lifespan = 34</li>
    <li>Matching rate = 36</li>
</ul>
|value
    |link:http://php.net/string[string^]
    a|The value of the property type
|payment
    |        xref:Payment.adoc#payment_models_payment[`Payment`]
    a|
|type
    |        xref:Payment.adoc#payment_models_paymentpropertytype[`PaymentPropertyType`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[payment_models_paymentpropertytype]]
==== PaymentPropertyType

The payment property type model



===== Namespace

`Plenty\Modules\Payment\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property type
|erasable
    |link:http://php.net/int[int^]
    a|Specifies whether the property type can be deleted. Property types that can be deleted have the value 1. Default property types cannot be deleted.
|position
    |link:http://php.net/int[int^]
    a|The position number of the property type
|name
    |        xref:Payment.adoc#payment_models_paymentpropertytypename[`PaymentPropertyTypeName`]
    a|The name of the property type
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[payment_models_paymentpropertytypename]]
==== PaymentPropertyTypeName

The payment property type name model



===== Namespace

`Plenty\Modules\Payment\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the name of the property type
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the property type
|lang
    |link:http://php.net/string[string^]
    a|The language of the name of the property type
|name
    |link:http://php.net/string[string^]
    a|The name of the property type
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[payment_events]]
== Events

[[payment_events_checkout]]
===  Checkout
[[payment_checkout_executepayment]]
==== ExecutePayment

The event is triggered when a payment is executed.



===== Namespace

`Plenty\Modules\Payment\Events\Checkout`






===== Methods

[source%nowrap, php]
[#setorderid]
----

public setOrderId($orderId):Plenty\Modules\Payment\Events\Checkout\ExecutePayment

----




====== *Return type:*        xref:Payment.adoc#payment_checkout_executepayment[`ExecutePayment`]


Updates the ID of the order in the checkout. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order
|===


[source%nowrap, php]
[#getorderid]
----

public getOrderId():int

----







Gets the ID of the order.

[source%nowrap, php]
[#setmop]
----

public setMop($mop):Plenty\Modules\Payment\Events\Checkout\ExecutePayment

----




====== *Return type:*        xref:Payment.adoc#payment_checkout_executepayment[`ExecutePayment`]


Updates the ID of the payment method. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mop`
|link:http://php.net/int[int^]
a|The ID of the payment method
|===


[source%nowrap, php]
[#getmop]
----

public getMop():int

----







Gets the ID of the payment method.

[source%nowrap, php]
[#settype]
----

public setType($type):Plenty\Modules\Payment\Events\Checkout\ExecutePayment

----




====== *Return type:*        xref:Payment.adoc#payment_checkout_executepayment[`ExecutePayment`]


Updates the content type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|The <a href="https://developers.plentymarkets.com/dev-doc/payment-plugins#payment-prepare-payment">content type</a> of the payment plugin
|===


[source%nowrap, php]
[#gettype]
----

public getType():string

----







Gets the content type.

[source%nowrap, php]
[#setvalue]
----

public setValue($value):Plenty\Modules\Payment\Events\Checkout\ExecutePayment

----




====== *Return type:*        xref:Payment.adoc#payment_checkout_executepayment[`ExecutePayment`]


Updates the value of the content type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$value`
|link:http://php.net/string[string^]
a|The value of the content type
|===


[source%nowrap, php]
[#getvalue]
----

public getValue():string

----







Gets the value of the content type.


[[payment_checkout_getpaymentmethodcontent]]
==== GetPaymentMethodContent

The event is triggered after the payment method is selected in the checkout.



===== Namespace

`Plenty\Modules\Payment\Events\Checkout`






===== Methods

[source%nowrap, php]
[#setmop]
----

public setMop($mop):Plenty\Modules\Payment\Events\Checkout\GetPaymentMethodContent

----




====== *Return type:*        xref:Payment.adoc#payment_checkout_getpaymentmethodcontent[`GetPaymentMethodContent`]


Updates the ID of the payment method. The ID must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mop`
|link:http://php.net/int[int^]
a|The ID of the payment method
|===


[source%nowrap, php]
[#getmop]
----

public getMop():int

----







Gets the ID of the payment method.

[source%nowrap, php]
[#settype]
----

public setType($type):Plenty\Modules\Payment\Events\Checkout\GetPaymentMethodContent

----




====== *Return type:*        xref:Payment.adoc#payment_checkout_getpaymentmethodcontent[`GetPaymentMethodContent`]


Updates the content type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|The <a href="https://developers.plentymarkets.com/dev-doc/payment-plugins#payment-prepare-payment">content type</a> of the payment plugin
|===


[source%nowrap, php]
[#gettype]
----

public getType():string

----







Gets the content type.

[source%nowrap, php]
[#setvalue]
----

public setValue($value):Plenty\Modules\Payment\Events\Checkout\GetPaymentMethodContent

----




====== *Return type:*        xref:Payment.adoc#payment_checkout_getpaymentmethodcontent[`GetPaymentMethodContent`]


Updates the value of the content type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$value`
|link:http://php.net/string[string^]
a|The value of the content type
|===


[source%nowrap, php]
[#getvalue]
----

public getValue():string

----







Gets the value of the content type.

[source%nowrap, php]
[#setparams]
----

public setParams($params):Plenty\Modules\Payment\Events\Checkout\GetPaymentMethodContent

----




====== *Return type:*        xref:Payment.adoc#payment_checkout_getpaymentmethodcontent[`GetPaymentMethodContent`]


Updates the parameters. The parameters must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$params`
|
a|The parameters
|===


[source%nowrap, php]
[#getparams]
----

public getParams():void

----







Gets the parameters.

[[payment_history]]
== History

[[payment_history_contracts]]
===  Contracts
[[payment_contracts_paymenthistoryrepositorycontract]]
==== PaymentHistoryRepositoryContract

The PaymentHistoryRepositoryContract is the interface for the payment history repository. Get and create the payment history.



===== Namespace

`Plenty\Modules\Payment\History\Contracts`






===== Methods

[source%nowrap, php]
[#getbypaymentid]
----

public getByPaymentId($paymentId, $typeId):array

----







Gets the payment history for a payment. The ID of the payment and the ID of the payment type must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentId`
|link:http://php.net/int[int^]
a|The ID of the payment

a|`$typeId`
|link:http://php.net/int[int^]
a|The ID of the history type. The following types are available:
<ul>
    <li>Created = 1</li>
    <li>Status updated = 2</li>
    <li>Assigned = 3</li>
    <li>Detached = 4</li>
    <li>Deleted = 5</li>
    <li>Updated = 6</li>
</ul>
|===


[source%nowrap, php]
[#getbyorderid]
----

public getByOrderId($orderId):void

----







Get payment history by order ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#createhistory]
----

public createHistory($data):Plenty\Modules\Payment\History\Models\PaymentHistory

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymenthistory[`PaymentHistory`]


Creates the payment history.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[[payment_history_models]]
===  Models
[[payment_models_paymenthistory]]
==== PaymentHistory

The payment history model



===== Namespace

`Plenty\Modules\Payment\History\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the payment history
|paymentId
    |link:http://php.net/int[int^]
    a|The ID of the payment
|typeId
    |link:http://php.net/int[int^]
    a|The ID of the history type. The following types are available:
<ul>
    <li>Created = 1</li>
    <li>Status updated = 2</li>
    <li>Assigned = 3</li>
    <li>Detached = 4</li>
    <li>Deleted = 5</li>
    <li>Updated = 6</li>
</ul>
|value
    |link:http://php.net/string[string^]
    a|The value of the payment history
|user
    |link:http://php.net/string[string^]
    a|The user who initiated the action
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[payment_matcherrules]]
== MatcherRules

[[payment_matcherrules_contracts]]
===  Contracts
[[payment_contracts_paymentmatcherrulescontainercontract]]
==== PaymentMatcherRulesContainerContract

Payment Matcher Rules Container Service



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Contracts`






===== Methods

[source%nowrap, php]
[#registerrule]
----

public registerRule($ruleClass, $mopIds = []):void

----







Register a specific rule class, either for specific methods of payment, or, lacking the second param, for all

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ruleClass`
|link:http://php.net/string[string^]
a|

a|`$mopIds`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getregisteredrules]
----

public getRegisteredRules($mopId):array

----







Gets all registered rules that apply to a specific method of payment
If the payment method doesn&#039;t have any specificity, the rule set that applies generically is returned

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mopId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#excluderuleformethods]
----

public excludeRuleForMethods($ruleClass, $mopIds):void

----







Excludes the specified rule from the method&#039;s ruleset.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ruleClass`
|link:http://php.net/string[string^]
a|

a|`$mopIds`
|link:http://php.net/array[array^]
a|
|===


[[payment_matcherrules_rules]]
===  Rules
[[payment_rules_checkmatchedorderinvoiceamount]]
==== CheckMatchedOrderInvoiceAmount

Invoice Amount Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchalreadyoverpaid]]
==== MatchAlreadyOverpaid

Already Overpaid Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchamount]]
==== MatchAmount

Amount Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchcustomeremail]]
==== MatchCustomerEmail

Customer E-Mail Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchcustomerid]]
==== MatchCustomerId

Customer ID Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchcustomername]]
==== MatchCustomerName

Customer Name Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchdeutschepost]]
==== MatchDeutschePost

Deutsche Post Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchebayname]]
==== MatchEbayName

Ebay Name Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchebaytransactionid]]
==== MatchEbayTransactionId

Ebay Transaction ID Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchebayuniquepaymentid]]
==== MatchEbayUniquePaymentId

Ebay Unique Payment ID Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchexternalorderid]]
==== MatchExternalOrderId

External Order ID Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchinvoicenumber]]
==== MatchInvoiceNumber

Invoice Number Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchorderid]]
==== MatchOrderId

Order ID Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchpackagenum]]
==== MatchPackageNum

Package Number Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchpaymentbeforeentrydate]]
==== MatchPaymentBeforeEntryDate

Payment Before Entry Date Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===



[[payment_rules_matchpaymenttransactionid]]
==== MatchPaymentTransactionId

Payment Transaction ID Payment Matcher Rule



===== Namespace

`Plenty\Modules\Payment\MatcherRules\Rules`






===== Methods

[source%nowrap, php]
[#canscore]
----

public canScore($payment, $matchScore, $scoringLog):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$matchScore`
|link:http://php.net/int[int^]
a|

a|`$scoringLog`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#score]
----

public score($payment, $order):float

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|

a|`$order`
|        xref:Order.adoc#order_models_order[`Order`]
a|
|===


[source%nowrap, php]
[#getscoreup]
----

public getScoreUp():int

----









[source%nowrap, php]
[#setscoreup]
----

public setScoreUp($scoreUp):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreUp`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getscoredown]
----

public getScoreDown():void

----









[source%nowrap, php]
[#setscoredown]
----

public setScoreDown($scoreDown):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$scoreDown`
|
a|
|===


[source%nowrap, php]
[#calculatematchingcondition]
----

public calculateMatchingCondition($payment):int

----







calculate the matching condition used in 2 rules - amount and email

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$payment`
|        xref:Payment.adoc#payment_models_payment[`Payment`]
a|
|===


[[payment_method]]
== Method

[[payment_method_contracts]]
===  Contracts
[[payment_contracts_paymentmethodcontainer]]
==== PaymentMethodContainer

The payment method container



===== Namespace

`Plenty\Modules\Payment\Method\Contracts`






===== Methods

[source%nowrap, php]
[#register]
----

public register($paymentKey, $paymentMethodServiceClass, $rebuildEventClassesList):void

----







Registers a payment method

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentKey`
|link:http://php.net/string[string^]
a|The unique key of a payment plugin

a|`$paymentMethodServiceClass`
|
a|The class of the payment method. This class contains information of the payment plugin, such as the name and whether the payment method is active.

a|`$rebuildEventClassesList`
|link:http://php.net/array[array^]
a|A list of events. It is checked again for the list of events whether the payment method is active.
|===


[source%nowrap, php]
[#isregistered]
----

public isRegistered($paymentKey):bool

----







Checks registered payment method

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentKey`
|link:http://php.net/string[string^]
a|
|===



[[payment_contracts_paymentmethodrepositorycontract]]
==== PaymentMethodRepositoryContract

The PaymentMethodRepositoryContract is the interface for the payment method repository. List, get, create and update payment methods.



===== Namespace

`Plenty\Modules\Payment\Method\Contracts`






===== Methods

[source%nowrap, php]
[#all]
----

public all():array

----







Lists payment methods.

[source%nowrap, php]
[#allforplugin]
----

public allForPlugin($pluginKey):array

----







Lists payment methods for a plugin key. The plugin key must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$pluginKey`
|link:http://php.net/string[string^]
a|The plugin key
|===


[source%nowrap, php]
[#allpluginpaymentmethods]
----

public allPluginPaymentMethods():array

----







Get all plugin payment methods.

[source%nowrap, php]
[#alloldpaymentmethods]
----

public allOldPaymentMethods():array

----







Get all old payment methods.

[source%nowrap, php]
[#findbypaymentmethodid]
----

public findByPaymentMethodId($paymentMethodId):Plenty\Modules\Payment\Method\Models\PaymentMethod

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]


Gets a payment method. The ID of the payment method must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodId`
|link:http://php.net/int[int^]
a|The ID of the payment method
|===


[source%nowrap, php]
[#findbypluginandpaymentkey]
----

public findByPluginAndPaymentKey($pluginKey, $paymentKey):Plenty\Modules\Payment\Method\Models\PaymentMethod

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]


Gets a payment method. The plugin and the payment key must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$pluginKey`
|link:http://php.net/string[string^]
a|

a|`$paymentKey`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getpreviewlist]
----

public getPreviewList($language = null):array

----







Get an array with all payment methods with the ID as key and the name as value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$language`
|link:http://php.net/string[string^]
a|The names will be returned in this language.
|===


[source%nowrap, php]
[#createpaymentmethod]
----

public createPaymentMethod($paymentMethodData):Plenty\Modules\Payment\Method\Models\PaymentMethod

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]


Creates a payment method.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodData`
|
a|
|===


[source%nowrap, php]
[#updatename]
----

public updateName($paymentMethodData):Plenty\Modules\Payment\Method\Models\PaymentMethod

----




====== *Return type:*        xref:Payment.adoc#payment_models_paymentmethod[`PaymentMethod`]


Updates the payment method name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$paymentMethodData`
|
a|
|===


[source%nowrap, php]
[#preparepaymentmethod]
----

public preparePaymentMethod($mop):array

----







Prepares a payment method. The ID of the payment method must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mop`
|link:http://php.net/int[int^]
a|The ID of the payment method
|===


[source%nowrap, php]
[#executepayment]
----

public executePayment($mop, $orderId):array

----







Executes a payment. The ID of the payment method and the ID of the order must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mop`
|link:http://php.net/int[int^]
a|The ID of the payment method

a|`$orderId`
|link:http://php.net/int[int^]
a|The ID of the order
|===


[source%nowrap, php]
[#listbackendsearchable]
----

public listBackendSearchable($lang):array

----







List all payment methods which are searchable for the backend

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#listbackendactive]
----

public listBackendActive($lang):array

----







List all payment methods which are active for the backend

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#listbackendicon]
----

public listBackendIcon():array

----







List all payment methods backend icon

[source%nowrap, php]
[#listcanhandlesubscriptions]
----

public listCanHandleSubscriptions($lang):array

----







List all payment methods which can handle subscriptions

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#listallactive]
----

public listAllActive($lang):array

----







List all payment methods which are active

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#backendsearchablepaymentmethods]
----

public backendSearchablePaymentMethods():array

----









[source%nowrap, php]
[#backendactivepaymentmethods]
----

public backendActivePaymentMethods():array

----










[[payment_contracts_paymentmethodservice]]
==== PaymentMethodService

Deprecated: The payment method service



===== Namespace

`Plenty\Modules\Payment\Method\Contracts`






===== Methods

[source%nowrap, php]
[#isbackendsearchable]
----

public isBackendSearchable():bool

----







Is this payment method searchable in the backend?

[source%nowrap, php]
[#isbackendactive]
----

public isBackendActive():bool

----







Is this payment method active in the backend?

[source%nowrap, php]
[#getbackendname]
----

public getBackendName($lang):string

----







Get the backend name of the payment method

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#canhandlesubscriptions]
----

public canHandleSubscriptions():bool

----







Can this payment method handle subscriptions?

[[payment_method_models]]
===  Models
[[payment_models_paymentmethod]]
==== PaymentMethod

The payment method model



===== Namespace

`Plenty\Modules\Payment\Method\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the payment method
|pluginKey
    |link:http://php.net/string[string^]
    a|The plugin key of the payment method
|paymentKey
    |link:http://php.net/string[string^]
    a|The payment key of the payment method
|name
    |link:http://php.net/string[string^]
    a|The name of the payment method
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[payment_method_services]]
===  Services
[[payment_services_paymentmethodbaseservice]]
==== PaymentMethodBaseService

The payment method service



===== Namespace

`Plenty\Modules\Payment\Method\Services`






===== Methods

[source%nowrap, php]
[#isactive]
----

public isActive():bool

----







Determine if the payment method is active for the frontend

[source%nowrap, php]
[#getname]
----

public getName($lang = &quot;&quot;):string

----







Return the frontend name of the payment method according to the language

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getfee]
----

public getFee():float

----







Return an additional payment fee for the payment method

[source%nowrap, php]
[#geticon]
----

public getIcon($lang = &quot;&quot;):string

----







Return the frontend icon of the payment method according to the language

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getdescription]
----

public getDescription($lang = &quot;&quot;):string

----







Return the frontend description of the payment method according to the language

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getsourceurl]
----

public getSourceUrl($lang = &quot;&quot;):string

----







Return an url with additional information shown in the frontend about the payment method according to the language

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#isswitchableto]
----

public isSwitchableTo():bool

----







Check if it is allowed to switch to this payment method after the order is placed

[source%nowrap, php]
[#isswitchablefrom]
----

public isSwitchableFrom():bool

----







Check if it is allowed to switch from this payment method after the order is placed

[source%nowrap, php]
[#isbackendsearchable]
----

public isBackendSearchable():bool

----







Is this payment method searchable in the backend?

[source%nowrap, php]
[#isbackendactive]
----

public isBackendActive():bool

----







Is this payment method active in the backend to used for existing orders?

[source%nowrap, php]
[#getbackendname]
----

public getBackendName($lang = &quot;&quot;):string

----







Get the backend name of the payment method according to the language

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#canhandlesubscriptions]
----

public canHandleSubscriptions():bool

----







Can this payment method handle subscriptions?

[source%nowrap, php]
[#getbackendicon]
----

public getBackendIcon():string

----







Return the icon for the backend, shown in the payments ui

[[payment_methodname]]
== MethodName

[[payment_methodname_models]]
===  Models
[[payment_models_paymentmethodname]]
==== PaymentMethodName

The payment method name model



===== Namespace

`Plenty\Modules\Payment\MethodName\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|paymentMethodId
    |link:http://php.net/int[int^]
    a|
|lang
    |link:http://php.net/string[string^]
    a|
|name
    |link:http://php.net/string[string^]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

