

[[plentymarketplace_plentymarketplace]]
== PlentyMarketplace

[[plentymarketplace_plentymarketplace_contracts]]
===  Contracts
[[plentymarketplace_contracts_marketplacepurchaseinformationcontract]]
==== MarketplacePurchaseInformationContract

Get information about purchases on marketplace.



===== Namespace

`Plenty\Modules\PlentyMarketplace\Contracts`






===== Methods

[source%nowrap, php]
----

public isPaid($pluginName):bool

----

    





Takes the Name of a plugin and returns true if the plugin has been paid for.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$pluginName`
a|The plugin name. Must be exactly as provided in the plugin.json.
|===



[[plentymarketplace_contracts_subscriptioninformationservicecontract]]
==== SubscriptionInformationServiceContract

Get information about plugin subscriptions. Only suitable for subscription plugins.



===== Namespace

`Plenty\Modules\PlentyMarketplace\Contracts`






===== Methods

[source%nowrap, php]
----

public isPaid($pluginName):bool

----

    





Takes the Name of a subscription plugin and returns true if the subscription has been paid for
in the current payment period on the current system.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$pluginName`
a|The plugin name. Must be exactly as provided in the plugin.json.
|===


[source%nowrap, php]
----

public getSubscriptionInfo($pluginName):Plenty\Modules\PlentyMarketplace\Models\SubscriptionOrderInformation

----

    


====== *Return type:*        xref:Plentymarketplace.adoc#plentymarketplace_models_subscriptionorderinformation[`SubscriptionOrderInformation`]


Takes the Name of a subscription plugin and returns information about the subscription.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$pluginName`
a|The plugin name. Must be exactly as provided in the plugin.json.
|===


[[plentymarketplace_plentymarketplace_models]]
===  Models
[[plentymarketplace_models_subscriptionchildorderinformation]]
==== SubscriptionChildOrderInformation

Eloquent model representing a SubscriptionChildOrderInformation.



===== Namespace

`Plenty\Modules\PlentyMarketplace\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|paymentStatus
    a|
|link:http://php.net/array[array^]
    a|paymentInformation
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[plentymarketplace_models_subscriptionchildpaymentinformation]]
==== SubscriptionChildPaymentInformation

Eloquent model representing a SubscriptionChildPaymentInformation.



===== Namespace

`Plenty\Modules\PlentyMarketplace\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/float[float^]
    a|amount
    a|The amount of the payment
|link:http://php.net/int[int^]
    a|status
    a|The <a href="https://developers.plentymarkets.com/rest-doc/introduction#payment-statuses"  target="_blank">status</a> of the payment
|link:http://php.net/int[int^]
    a|unaccountable
    a|An unassigned payment. Unassigned payments have the value 1.
|link:http://php.net/string[string^]
    a|currency
    a|The currency of the payment in ISO 4217 code.
|link:http://php.net/string[string^]
    a|receivedAt
    a|The time the payment was received
|link:http://php.net/string[string^]
    a|importedAt
    a|The time the payment was imported
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[plentymarketplace_models_subscriptionorderinformation]]
==== SubscriptionOrderInformation

Eloquent model representing a SubscriptionOrderInformation.



===== Namespace

`Plenty\Modules\PlentyMarketplace\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/bool[bool^]
    a|isPaid
    a|
|link:http://php.net/string[string^]
    a|intervalType
    a|
|link:http://php.net/string[string^]
    a|intervalValue
    a|
|link:http://php.net/string[string^]
    a|startDate
    a|
|link:http://php.net/string[string^]
    a|subscriptionLastRun
    a|
|link:http://php.net/string[string^]
    a|subscriptionNextRun
    a|
|link:http://php.net/array[array^]
    a|childOrders
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

