:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[property_property]]
== Property

[[property_property_contracts]]
===  Contracts
[[property_contracts_propertyamazonrepositorycontract]]
==== PropertyAmazonRepositoryContract

This interface allows you to get, create, update and delete property amazons.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertyAmazonRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getpropertyamazon]
----

public getPropertyAmazon($propertyAmazonId):Plenty\Modules\Property\Models\PropertyAmazon

----




====== *Return type:*        xref:Property.adoc#property_models_propertyamazon[`PropertyAmazon`]


Gets a property amazon. The ID of the property amazon must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyAmazonId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#listpropertyamazons]
----

public listPropertyAmazons($with = [], $filters = []):array

----







List property amazons

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$with`
|link:http://php.net/array[array^]
a|

a|`$filters`
|link:http://php.net/array[array^]
a|The filter available is:
<ol><li>propertyId</li></ol>
|===


[source%nowrap, php]
[#createpropertyamazon]
----

public createPropertyAmazon($data):Plenty\Modules\Property\Models\PropertyAmazon

----




====== *Return type:*        xref:Property.adoc#property_models_propertyamazon[`PropertyAmazon`]


Creates one or multiple property amazon

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updatepropertyamazon]
----

public updatePropertyAmazon($data):Plenty\Modules\Property\Models\PropertyAmazon

----




====== *Return type:*        xref:Property.adoc#property_models_propertyamazon[`PropertyAmazon`]


Updates one or multiple property amazon.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deletepropertyamazon]
----

public deletePropertyAmazon($propertyAmazonId):void

----







Deletes a property amazon. The ID of property amazon must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyAmazonId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyavailabilityrepositorycontract]]
==== PropertyAvailabilityRepositoryContract

Get, create, update and delete property availability.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use Property V2 Repositories instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getavailability]
----

public getAvailability($availabilityId):Plenty\Modules\Property\Models\PropertyAvailability

----




====== *Return type:*        xref:Property.adoc#property_models_propertyavailability[`PropertyAvailability`]


Gets an availability. The ID of the availability must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$availabilityId`
|link:http://php.net/int[int^]
a|The ID of the availability
|===


[source%nowrap, php]
[#listavailabilities]
----

public listAvailabilities():array

----







Lists availabilities

[source%nowrap, php]
[#createavailability]
----

public createAvailability($data):Plenty\Modules\Property\Models\PropertyAvailability

----




====== *Return type:*        xref:Property.adoc#property_models_propertyavailability[`PropertyAvailability`]


Creates an availability

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updateavailability]
----

public updateAvailability($availabilityId, $data):Plenty\Modules\Property\Models\PropertyAvailability

----




====== *Return type:*        xref:Property.adoc#property_models_propertyavailability[`PropertyAvailability`]


Updates an availability. The ID of availability must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$availabilityId`
|link:http://php.net/int[int^]
a|The ID of the availability

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#deleteavailability]
----

public deleteAvailability($availabilityId):array

----







Deletes an availability. The ID of availability must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$availabilityId`
|link:http://php.net/int[int^]
a|The ID of the availability
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertygroupnamerepositorycontract]]
==== PropertyGroupNameRepositoryContract

This interface allows you to get, list, create, update and delete property group names.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertyGroupNameRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getgroupname]
----

public getGroupName($groupNameId):Plenty\Modules\Property\Models\PropertyGroupName

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupname[`PropertyGroupName`]


Gets a group name. The ID of the group name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupNameId`
|link:http://php.net/int[int^]
a|The ID of the group name
|===


[source%nowrap, php]
[#listgroupnames]
----

public listGroupNames():array

----







Lists group names

[source%nowrap, php]
[#creategroupname]
----

public createGroupName($data):Plenty\Modules\Property\Models\PropertyGroupName

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupname[`PropertyGroupName`]


Creates a group name

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updategroupname]
----

public updateGroupName($groupNameId, $data):Plenty\Modules\Property\Models\PropertyGroupName

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupname[`PropertyGroupName`]


Updates a group name. The ID of the group name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupNameId`
|link:http://php.net/int[int^]
a|The ID of the group name

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#deletegroupname]
----

public deleteGroupName($groupNameId):array

----







Deletes a group name. The ID of group name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupNameId`
|link:http://php.net/int[int^]
a|The ID of the group name
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertygroupoptionrepositorycontract]]
==== PropertyGroupOptionRepositoryContract

This interface allows you to get, create, update and delete property group options.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertyGroupOptionRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getgroupoption]
----

public getGroupOption($groupOptionId):Plenty\Modules\Property\Models\PropertyGroupOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupoption[`PropertyGroupOption`]


Get a group option. The ID of the group option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupOptionId`
|link:http://php.net/int[int^]
a|The ID of the group option
|===


[source%nowrap, php]
[#listgroupoptions]
----

public listGroupOptions():array

----







List group options

[source%nowrap, php]
[#creategroupoption]
----

public createGroupOption($data):Plenty\Modules\Property\Models\PropertyGroupOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupoption[`PropertyGroupOption`]


Creates a group option

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updategroupoption]
----

public updateGroupOption($groupOptionId, $data):Plenty\Modules\Property\Models\PropertyGroupOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupoption[`PropertyGroupOption`]


Updates a group option. The ID of group option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupOptionId`
|link:http://php.net/int[int^]
a|The ID of the group option

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#deletegroupoption]
----

public deleteGroupOption($groupOptionId):array

----







Deletes a group option. The ID of group option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupOptionId`
|link:http://php.net/int[int^]
a|The ID of the group option
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertygrouprelationrepositorycontract]]
==== PropertyGroupRelationRepositoryContract

This interface allows you to link or unlink properties with a property group.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertyGroupRelationRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#link]
----

public link($propertyId, $propertyGroupId):bool

----







Links a property to a property group.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|

a|`$propertyGroupId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#unlink]
----

public unlink($propertyId, $propertyGroupId):bool

----







Unlinks a property to a property group.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|

a|`$propertyGroupId`
|link:http://php.net/int[int^]
a|
|===



[[property_contracts_propertygrouprepositorycontract]]
==== PropertyGroupRepositoryContract

This interface allows you to get, list, create, update and delete property groups. Property groups help to structure properties.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertyGroupRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getgroup]
----

public getGroup($groupId):Plenty\Modules\Property\Models\PropertyGroup

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroup[`PropertyGroup`]


Gets a property group. The ID of the group must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupId`
|link:http://php.net/int[int^]
a|The ID of the group
|===


[source%nowrap, php]
[#listgroups]
----

public listGroups($page = 1, $itemsPerPage = 50, $with = [], $filters = [], $paginate = 1):array

----







Lists property groups

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1. See also $paginate.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of groups to be displayed per page. The default number of groups per page is 50. See also $paginate.

a|`$with`
|link:http://php.net/array[array^]
a|The relations available are:
<ol><li>properties,</li>
    <li>options and</li>
    <li>names.</li></ol>

a|`$filters`
|link:http://php.net/array[array^]
a|The filters allow to reduce the results listed. The following filters are currently availablle:
<ol><li>ID</li>
    <li>name</li>
    <li>lang</li>
    <li>optionIdentifier</li>
    <li>groupType</li>
    <li>surchargeType/li></ol>

a|`$paginate`
|link:http://php.net/int[int^]
a|Defines whether or not the result will be a paginated result or a list with all results. If 1 is given for the parameter, the result will be paginated.
|===


[source%nowrap, php]
[#creategroup]
----

public createGroup($data):Plenty\Modules\Property\Models\PropertyGroup

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroup[`PropertyGroup`]


Creates a property group

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updategroup]
----

public updateGroup($groupId, $data):Plenty\Modules\Property\Models\PropertyGroup

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroup[`PropertyGroup`]


Updates a property group. The ID of group must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupId`
|link:http://php.net/int[int^]
a|The ID of the group

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#deletegroup]
----

public deleteGroup($groupId):array

----







Deletes a property group. The ID of group must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupId`
|link:http://php.net/int[int^]
a|The ID of the group
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertymarketrepositorycontract]]
==== PropertyMarketRepositoryContract

This interface allows you to get, list, create, update and delete property markets.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use Property V2 Repositories instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getpropertymarket]
----

public getPropertyMarket($propertyMarketId):Plenty\Modules\Property\Models\PropertyMarket

----




====== *Return type:*        xref:Property.adoc#property_models_propertymarket[`PropertyMarket`]


Gets a property market. The ID of the property market must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyMarketId`
|link:http://php.net/int[int^]
a|The ID of the property market
|===


[source%nowrap, php]
[#listpropertymarkets]
----

public listPropertyMarkets():array

----







Lists property markets

[source%nowrap, php]
[#createpropertymarket]
----

public createPropertyMarket($data):Plenty\Modules\Property\Models\PropertyMarket

----




====== *Return type:*        xref:Property.adoc#property_models_propertymarket[`PropertyMarket`]


Creates a property market

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updatepropertymarket]
----

public updatePropertyMarket($propertyMarketId, $data):Plenty\Modules\Property\Models\PropertyMarket

----




====== *Return type:*        xref:Property.adoc#property_models_propertymarket[`PropertyMarket`]


Updates a property market. The ID of property market must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyMarketId`
|link:http://php.net/int[int^]
a|The ID of the property market

a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#deletepropertymarket]
----

public deletePropertyMarket($propertyMarketId):array

----







Deletes a property market. The ID of property market must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyMarketId`
|link:http://php.net/int[int^]
a|The ID of the property market
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertynamerepositorycontract]]
==== PropertyNameRepositoryContract

This interface allows you to get, list, create, update and delete property names.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertyNameRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getname]
----

public getName($nameId):Plenty\Modules\Property\Models\PropertyName

----




====== *Return type:*        xref:Property.adoc#property_models_propertyname[`PropertyName`]


Gets a property name. The ID of the property name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$nameId`
|link:http://php.net/int[int^]
a|The ID of the name
|===


[source%nowrap, php]
[#listnames]
----

public listNames($filters = []):array

----







Lists property names

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#createname]
----

public createName($data):Plenty\Modules\Property\Models\PropertyName

----




====== *Return type:*        xref:Property.adoc#property_models_propertyname[`PropertyName`]


Creates a property name

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updatename]
----

public updateName($nameId, $data):Plenty\Modules\Property\Models\PropertyName

----




====== *Return type:*        xref:Property.adoc#property_models_propertyname[`PropertyName`]


Updates a property name. The ID of property name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$nameId`
|link:http://php.net/int[int^]
a|The ID of the name

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deletename]
----

public deleteName($nameId):array

----







Deletes a property name. The ID of property name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$nameId`
|link:http://php.net/int[int^]
a|The ID of the name
|===


[source%nowrap, php]
[#getpropertybyname]
----

public getPropertyByName($name):Plenty\Modules\Property\Models\PropertyName

----




====== *Return type:*        xref:Property.adoc#property_models_propertyname[`PropertyName`]


Get a property name by name

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyoptionrepositorycontract]]
==== PropertyOptionRepositoryContract

This interface allows you to get, list, create, update and delete property options.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertyOptionRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getpropertyoption]
----

public getPropertyOption($propertyOptionId):Plenty\Modules\Property\Models\PropertyOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertyoption[`PropertyOption`]


Gets a property option. The ID of the property option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyOptionId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#listpropertyoptions]
----

public listPropertyOptions():array

----







List property options

[source%nowrap, php]
[#createpropertyoption]
----

public createPropertyOption($data):Plenty\Modules\Property\Models\PropertyOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertyoption[`PropertyOption`]


Creates a property option

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#createpropertyoptions]
----

public createPropertyOptions($data):array

----







Creates property options

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updatepropertyoption]
----

public updatePropertyOption($propertyOptionId, $data):Plenty\Modules\Property\Models\PropertyOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertyoption[`PropertyOption`]


Updates a property option. The ID of property option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyOptionId`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deletepropertyoption]
----

public deletePropertyOption($propertyOptionId):array

----







Deletes a property option. The ID of property option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyOptionId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#deletepropertyoptions]
----

public deletePropertyOptions($optionIds):array

----







Delete one or more property options.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$optionIds`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyrelationmarkuprepositorycontract]]
==== PropertyRelationMarkupRepositoryContract

This interface allows you to get, list, create, update and delete property relation markups.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use Property V2 Repositories instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getrelationmarkup]
----

public getRelationMarkup($relationMarkupId):Plenty\Modules\Property\Models\PropertyRelationMarkup

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationmarkup[`PropertyRelationMarkup`]


Get a property relation markup. The ID of the property relation markup must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationMarkupId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#listrelationmarkups]
----

public listRelationMarkups():array

----







List property relation markups

[source%nowrap, php]
[#createrelationmarkup]
----

public createRelationMarkup($data):Plenty\Modules\Property\Models\PropertyRelationMarkup

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationmarkup[`PropertyRelationMarkup`]


Creates a property relation markup

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updaterelationmarkup]
----

public updateRelationMarkup($relationMarkupId, $data):Plenty\Modules\Property\Models\PropertyRelationMarkup

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationmarkup[`PropertyRelationMarkup`]


Updates a property relation markup. The ID of property relation markup must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationMarkupId`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deleterelationmarkup]
----

public deleteRelationMarkup($relationMarkupId):void

----







Deletes a property relation markup. The ID of property relation markup must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationMarkupId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyrelationrepositorycontract]]
==== PropertyRelationRepositoryContract

This interface allows you to get, create, update and delete property relations.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertyRelationRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getrelation]
----

public getRelation($relationId):Plenty\Modules\Property\Models\PropertyRelation

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelation[`PropertyRelation`]


Gets a property relation. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#listrelations]
----

public listRelations($filters = [], $page = 1, $itemsPerPage = 50, $paginate, $sorting = []):array

----







List property relations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|

a|`$paginate`
|link:http://php.net/int[int^]
a|

a|`$sorting`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#createrelation]
----

public createRelation($data):Plenty\Modules\Property\Models\PropertyRelation

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelation[`PropertyRelation`]


Creates a property relation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updaterelation]
----

public updateRelation($relationId, $data):Plenty\Modules\Property\Models\PropertyRelation

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelation[`PropertyRelation`]


Updates a property relation. The ID of property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationId`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deleterelation]
----

public deleteRelation($relationId):void

----







Deletes a property relation. The ID of property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#savepropertyrelationfile]
----

public savePropertyRelationFile($relationId, $data, $file = &quot;&quot;):string

----







Save property relation file to S3

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationId`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|

a|`$file`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyrelationvaluerepositorycontract]]
==== PropertyRelationValueRepositoryContract

This interface allows you to get, create, update and delete property relation values.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertyRelationValueRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getpropertyrelationvalue]
----

public getPropertyRelationValue($propertyRelationValueId):Plenty\Modules\Property\Models\PropertyRelationValue

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationvalue[`PropertyRelationValue`]


Gets an property relation value. The ID of the property relation value must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyRelationValueId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#listpropertyrelationvalues]
----

public listPropertyRelationValues():array

----







List property relation values

[source%nowrap, php]
[#createpropertyrelationvalue]
----

public createPropertyRelationValue($data):Plenty\Modules\Property\Models\PropertyRelationValue

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationvalue[`PropertyRelationValue`]


Creates an property relation value

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updatepropertyrelationvalue]
----

public updatePropertyRelationValue($propertyRelationValueId, $data):Plenty\Modules\Property\Models\PropertyRelationValue

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationvalue[`PropertyRelationValue`]


Updates a property relation value. The ID of property relation value must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyRelationValueId`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#updatepropertyrelationvalues]
----

public updatePropertyRelationValues($data):Plenty\Modules\Property\Models\PropertyRelationValue

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationvalue[`PropertyRelationValue`]


Update multiple property relation values

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deletepropertyrelationvalue]
----

public deletePropertyRelationValue($propertyRelationValueId):void

----







Delete a property relation value

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyRelationValueId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#deleterelationsbyrelationid]
----

public deleteRelationsByRelationId($relationId):void

----







Delete all property relation values of a specified property relation.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyrepositorycontract]]
==== PropertyRepositoryContract

This interface allows you to get, create, update and delete properties.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertyRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getproperty]
----

public getProperty($propertyId, $with = []):Plenty\Modules\Property\Models\Property

----




====== *Return type:*        xref:Property.adoc#property_models_property[`Property`]


Gets a property. The ID of the property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|The id of the property

a|`$with`
|link:http://php.net/array[array^]
a|The relations available are:
<ol><li>availibilities</li>
    <li>relation</li>
    <li>selections</li>
    <li>names</li>
    <li>options</li>
    <li>markets</li>
    <li>groups</li></ol>
|===


[source%nowrap, php]
[#listproperties]
----

public listProperties($page = 1, $itemsPerPage = 50, $with = [], $filters = [], $paginate = 1, $orderBy = []):array

----







Lists properties

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1. See also $paginate.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of properties to be displayed per page. The default number of properties per page is 50. See also $paginate.

a|`$with`
|link:http://php.net/array[array^]
a|The relations available are:
<ol><li>availibilities</li>
    <li>relation</li>
    <li>selections</li>
    <li>names</li>
    <li>options</li>
    <li>markets</li>
    <li>groups</li></ol>

a|`$filters`
|link:http://php.net/array[array^]
a|The following filters are available:
<ol><li>id</li>
    <li>cast</li>
    <li>position</li>
    <li>name</li>
    <li>lang</li>
    <li>group</li></ol>

a|`$paginate`
|link:http://php.net/int[int^]
a|Defines whether or not the result will be a paginated result or a list with all results. If 1 is given for the parameter, the result will be paginated.

a|`$orderBy`
|link:http://php.net/array[array^]
a|The order after which the result is sorted
|===


[source%nowrap, php]
[#createproperty]
----

public createProperty($data):Plenty\Modules\Property\Models\Property

----




====== *Return type:*        xref:Property.adoc#property_models_property[`Property`]


Creates a property

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updateproperty]
----

public updateProperty($propertyId, $data):Plenty\Modules\Property\Models\Property

----




====== *Return type:*        xref:Property.adoc#property_models_property[`Property`]


Updates a property. The ID of property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deleteproperty]
----

public deleteProperty($propertyId):void

----







Deletes a property. The ID of property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyselectionrepositorycontract]]
==== PropertySelectionRepositoryContract

This interface allows you to get, create, update and delete property selections.

[WARNING]
.Deprecated! [small]#(since 2021-06-24)#
====

Please use \Plenty\Modules\Property\V2\Repositories\PropertySelectionRepository instead

====


===== Namespace

`Plenty\Modules\Property\Contracts`






===== Methods

[source%nowrap, php]
[#getpropertyselection]
----

public getPropertySelection($propertySelectionId):Plenty\Modules\Property\Models\PropertySelection

----




====== *Return type:*        xref:Property.adoc#property_models_propertyselection[`PropertySelection`]


Gets a property selection. The ID of the property selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertySelectionId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#listpropertyselections]
----

public listPropertySelections($page = 1, $itemsPerPage = 50, $with = [], $filters = []):array

----







List property selections

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1. See also $paginate.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of property selections to be displayed per page. The default number of selections per page is 50. See also $paginate.

a|`$with`
|link:http://php.net/array[array^]
a|The relations available are:
<ol><li>property</li>
    <li>relation</li></ol>

a|`$filters`
|link:http://php.net/array[array^]
a|The filter available is:
<ol><li>porpertyId</li></ol>
|===


[source%nowrap, php]
[#createpropertyselection]
----

public createPropertySelection($data):Plenty\Modules\Property\Models\PropertySelection

----




====== *Return type:*        xref:Property.adoc#property_models_propertyselection[`PropertySelection`]


Creates a property selection

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updatepropertyselection]
----

public updatePropertySelection($propertySelectionId, $data):Plenty\Modules\Property\Models\PropertySelection

----




====== *Return type:*        xref:Property.adoc#property_models_propertyselection[`PropertySelection`]


Updates a property selection. The ID of property selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertySelectionId`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deletepropertyselection]
----

public deletePropertySelection($propertySelectionId):void

----







Deletes a property selection. The ID of property selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertySelectionId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[property_property_models]]
===  Models
[[property_models_property]]
==== Property

Deprecated. Use V2 instead.The property model. Properties allow to further describe items, categories etc. A property can have one name per language. The property names have an own model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property
|cast
    |link:http://php.net/string[string^]
    a|The cast of the property (array values: 'empty','int','float','selection','shortText','longText','date','file')
|position
    |link:http://php.net/int[int^]
    a|The position of the property
|createdAt
    |
    a|The date when the property was created
|updatedAt
    |
    a|The date when the property was last updated
|names
    |        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|
|options
    |        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|
|relation
    |        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|
|amazons
    |        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|
|selections
    |        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|
|groups
    |        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyamazon]]
==== PropertyAmazon

Deprecated. Use V2 instead.The property amazon model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property amazon
|propertyId
    |link:http://php.net/int[int^]
    a|The ID of the property
|platform
    |link:http://php.net/string[string^]
    a|The platform of the property amazon
|category
    |link:http://php.net/string[string^]
    a|The category of the property amazon
|field
    |link:http://php.net/string[string^]
    a|The field of the property amazon
|createdAt
    |
    a|The date when the property name was created
|updatedAt
    |
    a|The date when the property name was last updated
|propertyRelation
    |        xref:Property.adoc#property_models_property[`Property`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyavailability]]
==== PropertyAvailability

Deprecated. Use V2 instead. The property availability model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property availability
|propertyId
    |link:http://php.net/int[int^]
    a|The ID of the property
|type
    |link:http://php.net/string[string^]
    a|The type of the property availability
|value
    |link:http://php.net/float[float^]
    a|The value of the property availability
|createdAt
    |
    a|The date when the property availability was created
|updatedAt
    |
    a|The date when the property availability was last updated
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertygroup]]
==== PropertyGroup

Deprecated. Use V2 instead.The property group model. A property group allows to group several properties together and helps to structure properties. Property groups can have different names per language. The property group names have an own model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property group
|position
    |link:http://php.net/int[int^]
    a|The position of the property group
|createdAt
    |
    a|The date when the property group was created
|updatedAt
    |
    a|The date when the property group was last updated
|options
    |
    a|The group options
|names
    |
    a|The group names
|properties
    |
    a|The properties the group belongs to
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertygroupname]]
==== PropertyGroupName

Deprecated. Use V2 instead.The property group name model. A property group can have several names. One name per language. Each name has a unique ID.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property group name
|propertyGroupId
    |link:http://php.net/int[int^]
    a|The ID of the property group
|lang
    |link:http://php.net/string[string^]
    a|The language of the property group name as ISO 639-1 language code, e.g. en for English
|name
    |link:http://php.net/string[string^]
    a|The name of the property group
|description
    |link:http://php.net/string[string^]
    a|The description of the property group
|createdAt
    |
    a|The date when the property group name was created
|updatedAt
    |
    a|The date when the property group name was last updated
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertygroupoption]]
==== PropertyGroupOption

Deprecated. Use V2 instead.The property group option model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property group option
|propertyGroupId
    |link:http://php.net/int[int^]
    a|The ID of the property group
|groupOptionIdentifier
    |link:http://php.net/string[string^]
    a|The identifier of the property group option
|value
    |link:http://php.net/string[string^]
    a|The value of the property group option
|createdAt
    |
    a|The date when the property group option was created
|updatedAt
    |
    a|The date when the property group option was last updated
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertygrouprelation]]
==== PropertyGroupRelation

Deprecated. Use V2 instead.The property group relation model. The model shows which property is related to which property group.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|propertyId
    |link:http://php.net/int[int^]
    a|The ID of the property
|propertyGroupId
    |link:http://php.net/int[int^]
    a|The ID of the property group
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertymarket]]
==== PropertyMarket

Deprecated. Use V2 instead.The property market model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property market
|propertyId
    |link:http://php.net/int[int^]
    a|The ID of the property
|referrerId
    |link:http://php.net/float[float^]
    a|The ID of the referrer
|referrerSubId
    |link:http://php.net/int[int^]
    a|The ID of the sub referrer
|value
    |link:http://php.net/string[string^]
    a|The value of the property market
|createdAt
    |
    a|The date when the property market was created
|updatedAt
    |
    a|The date when the property market was last updated
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyname]]
==== PropertyName

Deprecated. Use V2 instead.The property name model. A property can have several names. One name per language. Each name has a unique ID.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property name
|propertyId
    |link:http://php.net/int[int^]
    a|The ID of the property
|lang
    |link:http://php.net/string[string^]
    a|The language of the property name as ISO 639-1 language code, e.g. en for English
|name
    |link:http://php.net/string[string^]
    a|The name of the property
|description
    |link:http://php.net/string[string^]
    a|The description of the property
|createdAt
    |
    a|The date when the property name was created
|updatedAt
    |
    a|The date when the property name was last updated
|propertyRelation
    |        xref:Property.adoc#property_models_property[`Property`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyoption]]
==== PropertyOption

Deprecated. Use V2 instead.The property option model. Property options allow to add further specification to a property. Each property option can have several values. The porperty option values have an own model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property option
|propertyId
    |link:http://php.net/int[int^]
    a|The ID of the property
|typeOptionIdentifier
    |link:http://php.net/string[string^]
    a|The identifier of the type option
|createdAt
    |
    a|The date when the property option was created
|updatedAt
    |
    a|The date when the property option was last updated
|propertyOptionValues
    |        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyoptionvalue]]
==== PropertyOptionValue

Deprecated. Use V2 instead.The property option value model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property option value
|optionId
    |link:http://php.net/int[int^]
    a|The ID of the property option
|value
    |link:http://php.net/string[string^]
    a|The value of the property option
|createdAt
    |
    a|The date when the property option value was created
|updatedAt
    |
    a|The date when the property option value was last updated
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyrelation]]
==== PropertyRelation

Deprecated. Use V2 instead.The property relation model allows to relate a property e.g. to a variation or other targets.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property relation
|propertyId
    |link:http://php.net/int[int^]
    a|The ID of the property
|relationTypeIdentifier
    |link:http://php.net/string[string^]
    a|The identifier of the property relation
|relationTargetId
    |link:http://php.net/int[int^]
    a|The ID of the target of the relation
|selectionRelationId
    |link:http://php.net/int[int^]
    a|The ID of the selection relation
|groupId
    |link:http://php.net/int[int^]
    a|The ID of the property group
|markup
    |link:http://php.net/float[float^]
    a|The mark up of the property relation
|createdAt
    |
    a|The date when the property was created
|updatedAt
    |
    a|The date when the property was last updated
|relationValues
    |        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]
    a|
|propertyRelation
    |        xref:Property.adoc#property_models_property[`Property`]
    a|
|group
    |        xref:Property.adoc#property_models_propertygroup[`PropertyGroup`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyrelationmarkup]]
==== PropertyRelationMarkup

Deprecated. Use V2 instead.The property relation markup model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property relation markup
|propertyRelationId
    |link:http://php.net/int[int^]
    a|The ID of the property relation
|variationSalesPriceId
    |link:http://php.net/int[int^]
    a|The variation sales price id of the property relation markup
|markup
    |link:http://php.net/float[float^]
    a|The markup of the property relation markup
|createdAt
    |
    a|The date when the property was created
|updatedAt
    |
    a|The date when the property was last updated
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyrelationvalue]]
==== PropertyRelationValue

Deprecated. Use V2 instead.The property relation value model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property relation value
|propertyRelationId
    |link:http://php.net/int[int^]
    a|The ID of the property relation
|lang
    |link:http://php.net/string[string^]
    a|The language of the property relation value
|value
    |link:http://php.net/string[string^]
    a|The value of the property relation
|description
    |link:http://php.net/string[string^]
    a|The description of the property relation value
|createdAt
    |
    a|The date when the property relation value was created
|updatedAt
    |
    a|The date when the property relation value was last updated
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyselection]]
==== PropertySelection

Deprecated. Use V2 instead.The property selection model.



===== Namespace

`Plenty\Modules\Property\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property selection
|propertyId
    |link:http://php.net/int[int^]
    a|The ID of the property
|position
    |link:http://php.net/int[int^]
    a|The position of the property selection
|createdAt
    |
    a|The date when the property selection was created
|updatedAt
    |
    a|The date when the property selection was last updated
|relation
    |        xref:Property.adoc#property_models_propertyrelation[`PropertyRelation`]
    a|
|allRelations
    |link:http://php.net/array[array^]
    a|
|property
    |        xref:Property.adoc#property_models_property[`Property`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[property_v2]]
== V2

[[property_v2_contracts]]
===  Contracts
[[property_contracts_propertyamazonrepositorycontract]]
==== PropertyAmazonRepositoryContract

This interface allows you to get, create, update and delete property amazons.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#search]
----

public search($with = [], $perPage = 50, $page = 1):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$with`
|link:http://php.net/array[array^]
a|

a|`$perPage`
|link:http://php.net/int[int^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#findbypropertyid]
----

public findByPropertyId($propertyId):void

----







Gets a list of property amazon. The ID of the property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\PropertyAmazon

----




====== *Return type:*        xref:Property.adoc#property_models_propertyamazon[`PropertyAmazon`]


Gets a property amazon. The ID of the property amazon must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertyAmazon

----




====== *Return type:*        xref:Property.adoc#property_models_propertyamazon[`PropertyAmazon`]


Updates a property amazon. The ID of the property amazon must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertyAmazon

----




====== *Return type:*        xref:Property.adoc#property_models_propertyamazon[`PropertyAmazon`]


Creates a property amazon.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property amazon. The ID of the property amazon must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertygroupnamerepositorycontract]]
==== PropertyGroupNameRepositoryContract

This interface allows you to get, create, update and delete property group names.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#findbygroupid]
----

public findByGroupId($groupId):void

----







Gets a list of property group names. The ID of the property group must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Property\V2\Models\PropertyGroupName

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupname[`PropertyGroupName`]


Gets a property group name. The ID of the property group name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertyGroupName

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupname[`PropertyGroupName`]


Updates a property group name. The ID of the property group name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertyGroupName

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupname[`PropertyGroupName`]


Creates a property group name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property group name. The ID of the property group name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertygroupoptionrepositorycontract]]
==== PropertyGroupOptionRepositoryContract

This interface allows you to get, create, update and delete property group options.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#findbygroupid]
----

public findByGroupId($groupId):void

----







Gets a list of property group options. The ID of the property group must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$groupId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Property\V2\Models\PropertyGroupOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupoption[`PropertyGroupOption`]


Gets a property group option. The ID of the property group option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertyGroupOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupoption[`PropertyGroupOption`]


Updates a property group option. The ID of the property group option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertyGroupOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroupoption[`PropertyGroupOption`]


Creates a property group option.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property group option. The ID of the property group option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertygrouprelationrepositorycontract]]
==== PropertyGroupRelationRepositoryContract

This interface allows you to get, create and delete property group relations.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#search]
----

public search($with = [], $perPage = 50, $page = 1, $sorting = []):void

----







Gets a list of property group relations.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$with`
|link:http://php.net/array[array^]
a|

a|`$perPage`
|link:http://php.net/int[int^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$sorting`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#count]
----

public count():int

----







Count the property group relations.

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\PropertyGroupRelation

----




====== *Return type:*        xref:Property.adoc#property_models_propertygrouprelation[`PropertyGroupRelation`]


Gets a property group relation. The ID of the property group relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertyGroupRelation

----




====== *Return type:*        xref:Property.adoc#property_models_propertygrouprelation[`PropertyGroupRelation`]


Creates a property group relation.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property group relation. The ID of the property group relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#findone]
----

public findOne($propertyId, $groupId):Plenty\Modules\Property\V2\Models\PropertyGroupRelation

----




====== *Return type:*        xref:Property.adoc#property_models_propertygrouprelation[`PropertyGroupRelation`]


Gets a property group relation. The property ID and the group ID of the property group relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|The property ID of the property group relation

a|`$groupId`
|link:http://php.net/int[int^]
a|The group ID of the property group relation
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertygrouprepositorycontract]]
==== PropertyGroupRepositoryContract

This interface allows you to get, create, update and delete property groups.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#search]
----

public search($with = [], $perPage = 50, $page = 1, $sorting = []):void

----







Gets a list of property groups. Filter can be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$with`
|link:http://php.net/array[array^]
a|

a|`$perPage`
|link:http://php.net/int[int^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$sorting`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#count]
----

public count():int

----







Count the property groups.

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\PropertyGroup

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroup[`PropertyGroup`]


Gets a property group. The ID of the property group must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertyGroup

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroup[`PropertyGroup`]


Updates a property group. The ID of the property group must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertyGroup

----




====== *Return type:*        xref:Property.adoc#property_models_propertygroup[`PropertyGroup`]


Creates a property group.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property group. The ID of the property group must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertynamerepositorycontract]]
==== PropertyNameRepositoryContract

This interface allows you to get, create, update and delete property names.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#findbypropertyid]
----

public findByPropertyId($propertyId):void

----







Gets a list of property names. The ID of the property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Property\V2\Models\PropertyName

----




====== *Return type:*        xref:Property.adoc#property_models_propertyname[`PropertyName`]


Gets a property name. The ID of the property name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertyName

----




====== *Return type:*        xref:Property.adoc#property_models_propertyname[`PropertyName`]


Updates a property name. The ID of the property name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertyName

----




====== *Return type:*        xref:Property.adoc#property_models_propertyname[`PropertyName`]


Creates a property name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property name. The ID of the property name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyoptionrepositorycontract]]
==== PropertyOptionRepositoryContract

This interface allows you to get, create, update and delete property options.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#searchbypropertyid]
----

public searchByPropertyId($propertyId, $with = []):void

----







Gets a list of property options. The ID of the property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Property\V2\Models\PropertyOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertyoption[`PropertyOption`]


Gets a property option. The ID of the property option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertyOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertyoption[`PropertyOption`]


Updates a property option. The ID of the property option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertyOption

----




====== *Return type:*        xref:Property.adoc#property_models_propertyoption[`PropertyOption`]


Creates a property option.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property option. The ID of the property option must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyrelationrepositorycontract]]
==== PropertyRelationRepositoryContract

This interface allows you to get, create, update and delete property relations.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#search]
----

public search($with = [], $perPage = 50, $page = 1, $sorting = []):void

----







Gets a list of property relation. Filter can be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$with`
|link:http://php.net/array[array^]
a|

a|`$perPage`
|link:http://php.net/int[int^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$sorting`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#count]
----

public count():int

----







Count the property relations.

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\PropertyRelation

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelation[`PropertyRelation`]


Gets a property relation. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertyRelation

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelation[`PropertyRelation`]


Updates a property relation. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertyRelation

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelation[`PropertyRelation`]


Creates a property relation.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#createbulk]
----

public createBulk($data):void

----







Creates a list of property relations.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#updatebulk]
----

public updateBulk($data):void

----







Updates a list of property relations.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property relation. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyrelationselectionrepositorycontract]]
==== PropertyRelationSelectionRepositoryContract

This interface allows you to get, create, update and delete property relation selections.T hey are used for linked properties of the type `selection` and `multiSelection`.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#findbypropertyrelationid]
----

public findByPropertyRelationId($propertyRelationId, $with = []):void

----







Gets a list of property relation selections. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyRelationId`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\PropertyRelationSelection

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationselection[`PropertyRelationSelection`]


Gets a property relation selection. The ID of the property relation selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertyRelationSelection

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationselection[`PropertyRelationSelection`]


Updates a property relation selection. The ID of the property relation selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertyRelationSelection

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationselection[`PropertyRelationSelection`]


Creates a property relation selection.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property relation selection. The ID of the property relation selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyrelationvaluerepositorycontract]]
==== PropertyRelationValueRepositoryContract

This interface allows you to get, create, update and delete property relation values. They are used for linked properties of the type `html` and `text`.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#findbypropertyrelationid]
----

public findByPropertyRelationId($propertyRelationId, $with = []):void

----







Gets a list of property relation values. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyRelationId`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\PropertyRelationValue

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationvalue[`PropertyRelationValue`]


Gets a property relation value. The ID of the property relation value must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertyRelationValue

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationvalue[`PropertyRelationValue`]


Updates a property relation value. The ID of the property relation value must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertyRelationValue

----




====== *Return type:*        xref:Property.adoc#property_models_propertyrelationvalue[`PropertyRelationValue`]


Creates a property relation value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property relation value. The ID of the property relation value must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyrepositorycontract]]
==== PropertyRepositoryContract

This interface allows you to get, create, update and delete properties.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#search]
----

public search($with = [], $perPage = 50, $page = 1, $sorting = []):void

----







Gets a list of properties. Filter can be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$with`
|link:http://php.net/array[array^]
a|

a|`$perPage`
|link:http://php.net/int[int^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$sorting`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#count]
----

public count():int

----







Count the properties.

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\Property

----




====== *Return type:*        xref:Property.adoc#property_models_property[`Property`]


Gets a property. The ID of the property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\Property

----




====== *Return type:*        xref:Property.adoc#property_models_property[`Property`]


Updates a property. The ID of the property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\Property

----




====== *Return type:*        xref:Property.adoc#property_models_property[`Property`]


Creates a property.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property. The ID of the property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_contracts_propertyselectionnamerepositorycontract]]
==== PropertySelectionNameRepositoryContract

This interface allows you to get, create, update and delete property selection names.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#findbyselectionid]
----

public findBySelectionId($selectionId):void

----







Gets a list of property selection names. The ID of the property selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$selectionId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id):Plenty\Modules\Property\V2\Models\PropertySelectionName

----




====== *Return type:*        xref:Property.adoc#property_models_propertyselectionname[`PropertySelectionName`]


Gets a property selection name. The ID of the property selection name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertySelectionName

----




====== *Return type:*        xref:Property.adoc#property_models_propertyselectionname[`PropertySelectionName`]


Updates a property selection name. The ID of the property selection name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertySelectionName

----




====== *Return type:*        xref:Property.adoc#property_models_propertyselectionname[`PropertySelectionName`]


Create a property selection name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property selection name. The ID of the property selection name must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===



[[property_contracts_propertyselectionrepositorycontract]]
==== PropertySelectionRepositoryContract

This interface allows you to get, create, update and delete property selections.



===== Namespace

`Plenty\Modules\Property\V2\Contracts`






===== Methods

[source%nowrap, php]
[#searchbypropertyid]
----

public searchByPropertyId($propertyId, $with = [], $perPage = 50, $page = 1, $sorting = []):void

----







Gets a list of property selections. The ID of the property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|

a|`$perPage`
|link:http://php.net/int[int^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$sorting`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#countbypropertyid]
----

public countByPropertyId($propertyId):int

----







Count the property selections. The ID of the property must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\PropertySelection

----




====== *Return type:*        xref:Property.adoc#property_models_propertyselection[`PropertySelection`]


Gets a property selection. The ID of the property selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\PropertySelection

----




====== *Return type:*        xref:Property.adoc#property_models_propertyselection[`PropertySelection`]


Updates a property selection. The ID of the property selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\PropertySelection

----




====== *Return type:*        xref:Property.adoc#property_models_propertyselection[`PropertySelection`]


Creates a property selection.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property selection. The ID of the property selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[[property_v2_models]]
===  Models
[[property_models_property]]
==== Property

The property model. Properties allow to further describe items, customers etc.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property
|cast
    |link:http://php.net/string[string^]
    a|The cast of the property (array values: 'empty','int','float','string','selection','text','html','date','file')
|type
    |link:http://php.net/string[string^]
    a|The type of the property (e.g. 'item' or 'contact')
|position
    |link:http://php.net/int[int^]
    a|The position of the property
|createdAt
    |
    a|The date when the property was created
|updatedAt
    |
    a|The date when the property was last updated
|amazon
    |link:http://php.net/array[array^]
    a|Property amazon
|names
    |
    a|Property names
|groups
    |
    a|Property Groups
|options
    |
    a|Property Options
|selections
    |
    a|Property selections
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyamazon]]
==== PropertyAmazon

The property amazon model.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property amazon
|propertyId
    |link:http://php.net/int[int^]
    a|The property ID of the property amazon
|platform
    |link:http://php.net/string[string^]
    a|The platform of the property amazon
|category
    |link:http://php.net/string[string^]
    a|The category of the property amazon
|field
    |link:http://php.net/string[string^]
    a|The field of the property amazon
|createdAt
    |
    a|The date when the property amazon was created
|updatedAt
    |
    a|The date when the property amazon was last updated
|property
    |        xref:Property.adoc#property_models_property[`Property`]
    a|The associated property
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertygroup]]
==== PropertyGroup

The property group model.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property group
|position
    |link:http://php.net/int[int^]
    a|The position of the property group
|createdAt
    |
    a|The date when the property group was created
|updatedAt
    |
    a|The date when the property group was last updated
|names
    |
    a|The property group names of the property group
|options
    |
    a|The property group options of the property group
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertygroupname]]
==== PropertyGroupName

The property group name model.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property group name
|groupId
    |link:http://php.net/int[int^]
    a|The property group ID of the property group
|lang
    |link:http://php.net/string[string^]
    a|The language of the property group name as ISO 639-1 language code, e.g. en for English
|name
    |link:http://php.net/string[string^]
    a|The name of the property group
|description
    |link:http://php.net/string[string^]
    a|The description of the property group
|createdAt
    |
    a|The date when the property group name was created
|updatedAt
    |
    a|The date when the property group name was last updated
|group
    |        xref:Property.adoc#property_models_propertygroup[`PropertyGroup`]
    a|The associated property group
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertygroupoption]]
==== PropertyGroupOption

The property group option model.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property group option
|groupId
    |link:http://php.net/int[int^]
    a|The property group ID of the property group
|type
    |link:http://php.net/string[string^]
    a|The identifier of the property group option
|value
    |link:http://php.net/string[string^]
    a|The value of the property group option
|createdAt
    |
    a|The date when the property group option was created
|updatedAt
    |
    a|The date when the property group option was last updated
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertygrouprelation]]
==== PropertyGroupRelation

The property group relation model. The model shows which property is related to which property group.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property group relation
|propertyId
    |link:http://php.net/int[int^]
    a|The ID of the property
|groupId
    |link:http://php.net/int[int^]
    a|The ID of the property group
|group
    |        xref:Property.adoc#property_models_propertygroup[`PropertyGroup`]
    a|The associated property group
|property
    |        xref:Property.adoc#property_models_property[`Property`]
    a|The associated property
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyname]]
==== PropertyName

The property name model. A property can have several names. One name per language. Each name has a unique ID.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property name
|propertyId
    |link:http://php.net/int[int^]
    a|The property ID of the property name
|lang
    |link:http://php.net/string[string^]
    a|The language of the property name as ISO 639-1 language code, e.g. en for English
|name
    |link:http://php.net/string[string^]
    a|The name of the property name
|description
    |link:http://php.net/string[string^]
    a|The description of the property name
|createdAt
    |
    a|The date when the property name was created
|updatedAt
    |
    a|The date when the property name was last updated
|property
    |        xref:Property.adoc#property_models_property[`Property`]
    a|The associated property
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyoption]]
==== PropertyOption

The property option model.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property option
|propertyId
    |link:http://php.net/int[int^]
    a|The property ID of the property option
|type
    |link:http://php.net/string[string^]
    a|The identifier type of the option
|value
    |link:http://php.net/string[string^]
    a|The value of the option
|createdAt
    |
    a|The date when the property option was created
|updatedAt
    |
    a|The date when the property option was last updated
|property
    |        xref:Property.adoc#property_models_property[`Property`]
    a|The associated property
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyrelation]]
==== PropertyRelation

The property relation model.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property relation
|propertyId
    |link:http://php.net/int[int^]
    a|The property ID of the property relation
|type
    |link:http://php.net/string[string^]
    a|The type of the property relation
|targetId
    |link:http://php.net/int[int^]
    a|The ID of the target of the property relation
|groupId
    |link:http://php.net/int[int^]
    a|The property group ID of the property relation
|markup
    |link:http://php.net/float[float^]
    a|The mark up of the property relation
|value
    |link:http://php.net/string[string^]
    a|The value of the property relation for properties of the following type: int, float, date and file.
|createdAt
    |
    a|The date when the property was created
|updatedAt
    |
    a|The date when the property was last updated
|property
    |        xref:Property.adoc#property_models_property[`Property`]
    a|The associated property
|group
    |        xref:Property.adoc#property_models_propertygroup[`PropertyGroup`]
    a|The associated property group
|values
    |link:http://php.net/array[array^]
    a|The property relation values of the property relation. Includes properties of the types short and long text.
|selectionValues
    |link:http://php.net/array[array^]
    a|The property relation values of the property relation. Includes properties of the types selection and multi selection.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyrelationselection]]
==== PropertyRelationSelection

The property relation selection value model. Contains linked values for selections and multi selections.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property relation selection value
|relationId
    |link:http://php.net/int[int^]
    a|The relation ID of the property relation selection value
|selectionId
    |link:http://php.net/int[int^]
    a|The selection ID of the property relation selection value
|createdAt
    |
    a|The date when the property relation value was created
|updatedAt
    |
    a|The date when the property relation value was last updated
|relation
    |        xref:Property.adoc#property_models_propertyrelation[`PropertyRelation`]
    a|The associated property relation
|selection
    |        xref:Property.adoc#property_models_propertyselection[`PropertySelection`]
    a|The associated property selection
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyrelationvalue]]
==== PropertyRelationValue

The property relation value model. Includes the values in different languages for properties of the type short text and long text.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property relation value
|relationId
    |link:http://php.net/int[int^]
    a|The ID of the property relation
|lang
    |link:http://php.net/string[string^]
    a|The language of the property relation value
|value
    |link:http://php.net/string[string^]
    a|The value of the property relation
|description
    |link:http://php.net/string[string^]
    a|The description of the property relation value
|createdAt
    |
    a|The date when the property relation value was created
|updatedAt
    |
    a|The date when the property relation value was last updated
|relation
    |        xref:Property.adoc#property_models_propertyrelation[`PropertyRelation`]
    a|The associated property relation
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyselection]]
==== PropertySelection

The property selection model.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property selection
|propertyId
    |link:http://php.net/int[int^]
    a|The property ID of the property selection
|position
    |link:http://php.net/int[int^]
    a|The position of the property selection
|createdAt
    |
    a|he date when the property selection was created
|updatedAt
    |
    a|The date when the property selection was last updated
|property
    |        xref:Property.adoc#property_models_property[`Property`]
    a|The associated property
|names
    |
    a|The names of the property selection
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_models_propertyselectionname]]
==== PropertySelectionName

The property selection name model.



===== Namespace

`Plenty\Modules\Property\V2\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property selection name
|selectionId
    |link:http://php.net/int[int^]
    a|The selection ID of the property selection name
|lang
    |link:http://php.net/string[string^]
    a|The language of the property selection name
|name
    |link:http://php.net/string[string^]
    a|The name of the property selection name
|description
    |link:http://php.net/string[string^]
    a|The description of the property selection name
|createdAt
    |
    a|The date when the property selection name was created
|updatedAt
    |
    a|The date when the property selection name was last updated
|selection
    |        xref:Property.adoc#property_models_propertyselection[`PropertySelection`]
    a|The associated property selection
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[property_contracts]]
== Contracts

[[property_contracts_uuid]]
===  UUID
[[property_uuid_propertyrelationrepositorycontract]]
==== PropertyRelationRepositoryContract

This interface allows you to get, create, update and delete property relations.



===== Namespace

`Plenty\Modules\Property\V2\Contracts\UUID`






===== Methods

[source%nowrap, php]
[#search]
----

public search($with = [], $perPage = 50, $page = 1, $sorting = []):void

----







Gets a list of property relation. Filter can be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$with`
|link:http://php.net/array[array^]
a|

a|`$perPage`
|link:http://php.net/int[int^]
a|

a|`$page`
|link:http://php.net/int[int^]
a|

a|`$sorting`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#count]
----

public count():int

----







Count the property relations.

[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\UUID\PropertyRelation

----




====== *Return type:*        xref:Property.adoc#property_uuid_propertyrelation[`PropertyRelation`]


Gets a property relation. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\UUID\PropertyRelation

----




====== *Return type:*        xref:Property.adoc#property_uuid_propertyrelation[`PropertyRelation`]


Updates a property relation. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\UUID\PropertyRelation

----




====== *Return type:*        xref:Property.adoc#property_uuid_propertyrelation[`PropertyRelation`]


Creates a property relation.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#createbulk]
----

public createBulk($data):void

----







Creates a list of property relations.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#updatebulk]
----

public updateBulk($data):void

----







Updates a list of property relations.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property relation. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_uuid_propertyrelationselectionrepositorycontract]]
==== PropertyRelationSelectionRepositoryContract

This interface allows you to get, create, update and delete property relation selections.T hey are used for linked properties of the type `selection` and `multiSelection`.



===== Namespace

`Plenty\Modules\Property\V2\Contracts\UUID`






===== Methods

[source%nowrap, php]
[#findbypropertyrelationid]
----

public findByPropertyRelationId($propertyRelationId, $with = []):void

----







Gets a list of property relation selections. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyRelationId`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\UUID\PropertyRelationSelection

----




====== *Return type:*        xref:Property.adoc#property_uuid_propertyrelationselection[`PropertyRelationSelection`]


Gets a property relation selection. The ID of the property relation selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\UUID\PropertyRelationSelection

----




====== *Return type:*        xref:Property.adoc#property_uuid_propertyrelationselection[`PropertyRelationSelection`]


Updates a property relation selection. The ID of the property relation selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\UUID\PropertyRelationSelection

----




====== *Return type:*        xref:Property.adoc#property_uuid_propertyrelationselection[`PropertyRelationSelection`]


Creates a property relation selection.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property relation selection. The ID of the property relation selection must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[property_uuid_propertyrelationvaluerepositorycontract]]
==== PropertyRelationValueRepositoryContract

This interface allows you to get, create, update and delete property relation values. They are used for linked properties of the type `html` and `text`.



===== Namespace

`Plenty\Modules\Property\V2\Contracts\UUID`






===== Methods

[source%nowrap, php]
[#findbypropertyrelationid]
----

public findByPropertyRelationId($propertyRelationId, $with = []):void

----







Gets a list of property relation values. The ID of the property relation must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyRelationId`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#get]
----

public get($id, $with = []):Plenty\Modules\Property\V2\Models\UUID\PropertyRelationValue

----




====== *Return type:*        xref:Property.adoc#property_uuid_propertyrelationvalue[`PropertyRelationValue`]


Gets a property relation value. The ID of the property relation value must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#update]
----

public update($id, $data):Plenty\Modules\Property\V2\Models\UUID\PropertyRelationValue

----




====== *Return type:*        xref:Property.adoc#property_uuid_propertyrelationvalue[`PropertyRelationValue`]


Updates a property relation value. The ID of the property relation value must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public create($data):Plenty\Modules\Property\V2\Models\UUID\PropertyRelationValue

----




====== *Return type:*        xref:Property.adoc#property_uuid_propertyrelationvalue[`PropertyRelationValue`]


Creates a property relation value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#delete]
----

public delete($id):bool

----







Deletes a property relation value. The ID of the property relation value must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[property_models]]
== Models

[[property_models_uuid]]
===  UUID
[[property_uuid_propertyrelation]]
==== PropertyRelation

The property uuid relation model.



===== Namespace

`Plenty\Modules\Property\V2\Models\UUID`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property relation
|propertyId
    |link:http://php.net/int[int^]
    a|The property ID of the property relation
|type
    |link:http://php.net/string[string^]
    a|The type of the property relation
|targetId
    |link:http://php.net/string[string^]
    a|The ID of the target of the property relation
|groupId
    |link:http://php.net/int[int^]
    a|The property group ID of the property relation
|markup
    |link:http://php.net/float[float^]
    a|The mark up of the property relation
|value
    |link:http://php.net/string[string^]
    a|The value of the property relation for properties of the following type: int, float, date and file.
|createdAt
    |
    a|The date when the property was created
|updatedAt
    |
    a|The date when the property was last updated
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_uuid_propertyrelationselection]]
==== PropertyRelationSelection

The property uuid relation selection value model. Contains linked values for selections and multi selections.



===== Namespace

`Plenty\Modules\Property\V2\Models\UUID`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property relation selection value
|relationId
    |link:http://php.net/int[int^]
    a|The relation ID of the property relation selection value
|selectionId
    |link:http://php.net/int[int^]
    a|The selection ID of the property relation selection value
|createdAt
    |
    a|The date when the property relation value was created
|updatedAt
    |
    a|The date when the property relation value was last updated
|relation
    |        xref:Property.adoc#property_uuid_propertyrelation[`PropertyRelation`]
    a|The associated property uuid relation
|selection
    |        xref:Property.adoc#property_models_propertyselection[`PropertySelection`]
    a|The associated property selection
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[property_uuid_propertyrelationvalue]]
==== PropertyRelationValue

The property uuid relation value model. Includes the values in different languages for properties of the type short text and long text.



===== Namespace

`Plenty\Modules\Property\V2\Models\UUID`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the property relation value
|relationId
    |link:http://php.net/int[int^]
    a|The ID of the property relation
|lang
    |link:http://php.net/string[string^]
    a|The language of the property relation value
|value
    |link:http://php.net/string[string^]
    a|The value of the property relation
|description
    |link:http://php.net/string[string^]
    a|The description of the property relation value
|createdAt
    |
    a|The date when the property relation value was created
|updatedAt
    |
    a|The date when the property relation value was last updated
|relation
    |        xref:Property.adoc#property_uuid_propertyrelation[`PropertyRelation`]
    a|The associated property uuid relation
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

