:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[shopbuilder_shopbuilder]]
== ShopBuilder

[[shopbuilder_shopbuilder_contracts]]
===  Contracts
[[shopbuilder_contracts_contentlinkrepositorycontract]]
==== ContentLinkRepositoryContract

Get, create, delete, and update links between shopBuilder contents and layout containers depending on plugin sets and languages.



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
[#getcontentlinks]
----

public getContentLinks($pluginSetId):array

----







Get all content links for a plugin set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$pluginSetId`
|link:http://php.net/int[int^]
a|The ID of the plugin set to get content links for.
|===


[source%nowrap, php]
[#getcontentlink]
----

public getContentLink($contentLinkId):Plenty\Modules\ShopBuilder\Models\ContentLink

----




====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_contentlink[`ContentLink`]


Get a single connection between a content and a layout container.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$contentLinkId`
|link:http://php.net/int[int^]
a|The ID of the content link to get.
|===


[source%nowrap, php]
[#createcontentlink]
----

public createContentLink($data):Plenty\Modules\ShopBuilder\Models\ContentLink

----




====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_contentlink[`ContentLink`]


Create a link between a content and a layout container for a specified plugin set and a language.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|Content link data to create instance with.
|===


[source%nowrap, php]
[#updatecontentlink]
----

public updateContentLink($contentLinkId, $data):Plenty\Modules\ShopBuilder\Models\ContentLink

----




====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_contentlink[`ContentLink`]


Update a link between a content and a layout container.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$contentLinkId`
|link:http://php.net/int[int^]
a|ID of the content link.

a|`$data`
|link:http://php.net/array[array^]
a|Data to assign to the content link.
|===


[source%nowrap, php]
[#deletecontentlink]
----

public deleteContentLink($contentLinkId):void

----







Unlink a content from a layout container. The content itself will remain.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$contentLinkId`
|link:http://php.net/int[int^]
a|The ID of the content link to remove.
|===


[source%nowrap, php]
[#getcontentlinksforcontainer]
----

public getContentLinksForContainer($containerName, $pluginSetId = null, $lang = null, $contentType = null, $filterResults = true):void

----







Get all content links for a specific layout container.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$containerName`
|link:http://php.net/string[string^]
a|The name of the layout container for which to get content links.

a|`$pluginSetId`
|link:http://php.net/int[int^]
a|An ID of a plugin set for which to get content links. Active plugin set will be used by default.

a|`$lang`
|link:http://php.net/string[string^]
a|The language for which to get content links. Current language will be gotten from session if not defined.

a|`$contentType`
|link:http://php.net/string[string^]
a|Type of the content to get.

a|`$filterResults`
|link:http://php.net/bool[bool^]
a|
|===



[[shopbuilder_contracts_contentpreset]]
==== ContentPreset

Contract for content presets. Presets can provide a predefined set of widgets when creating new contents in the shopBuilder.



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
[#getwidgets]
----

public getWidgets():void

----







Get the widget configurations of the presets to be assigned to the created content.


[[shopbuilder_contracts_contentrepositorycontract]]
==== ContentRepositoryContract

Get, create, delete, und update shopBuilder contents.



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
[#getcontents]
----

public getContents():array

----







Get all contents with all their widget data.

[source%nowrap, php]
[#searchcontents]
----

public searchContents($itemsPerPage = 20, $page = 1, $params = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Search for contents. Search params are queried conjunctively while values for each params are queried disjunctively:

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|Maximum number of items to be returned on each page

a|`$page`
|link:http://php.net/int[int^]
a|Current page

a|`$params`
|link:http://php.net/array[array^]
a|Search parameters
|===


[source%nowrap, php]
[#getcontent]
----

public getContent($contentId, $pluginSetId, $frontendLanguage = null, $versionId = &quot;&quot;):Plenty\Modules\ShopBuilder\Models\Content

----




====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_content[`Content`]


Get a single content.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$contentId`
|link:http://php.net/int[int^]
a|ID of the content to get information for.

a|`$pluginSetId`
|link:http://php.net/int[int^]
a|The plugin set ID to be used for rendering widgets.

a|`$frontendLanguage`
|link:http://php.net/string[string^]
a|The language to be used for rendering the widgets.

a|`$versionId`
|link:http://php.net/string[string^]
a|The version of the content.
|===


[source%nowrap, php]
[#listcontentversions]
----

public listContentVersions($contentId, $itemsPerPage = 20, $versionIdMarker = &quot;&quot;):void

----







Get a list of versions of the specified content.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$contentId`
|link:http://php.net/int[int^]
a|ID of the content to get versions for.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|Number of versions to be displayed at a page.

a|`$versionIdMarker`
|link:http://php.net/string[string^]
a|ID of a version to get subsequent versions from.
|===


[source%nowrap, php]
[#restorecontentversion]
----

public restoreContentVersion($contentId, $versionId, $pluginSetId, $frontendLanguage = null):void

----







Restore a content to a specific version.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$contentId`
|link:http://php.net/int[int^]
a|ID of the content to restore.

a|`$versionId`
|link:http://php.net/string[string^]
a|ID of the version to restore the content to.

a|`$pluginSetId`
|link:http://php.net/int[int^]
a|

a|`$frontendLanguage`
|
a|
|===


[source%nowrap, php]
[#createcontent]
----

public createContent($pluginSetId, $data, $frontendLanguage = null):Plenty\Modules\ShopBuilder\Models\Content

----




====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_content[`Content`]


Create new content. New content will not be linked to any layout container.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$pluginSetId`
|link:http://php.net/int[int^]
a|The plugin set to be used to render the content. The raw content data do not depend on a plugin set.

a|`$data`
|
a|The raw content data.

a|`$frontendLanguage`
|link:http://php.net/string[string^]
a|The language to be used for rendering the widgets.
|===


[source%nowrap, php]
[#updatecontent]
----

public updateContent($pluginSetId, $contentId, $data, $frontendLanguage = null):Plenty\Modules\ShopBuilder\Models\Content

----




====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_content[`Content`]


Update content. Metadata, such as the user defined name of the content, will be stored separately to the data of the widgets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$pluginSetId`
|link:http://php.net/int[int^]
a|The plugin set to be used to render the content. The raw content data do not depend on a plugin set.

a|`$contentId`
|link:http://php.net/int[int^]
a|The ID of the content to be updated.

a|`$data`
|
a|The raw data of the content.

a|`$frontendLanguage`
|link:http://php.net/string[string^]
a|The language to be used for rendering the widgets.
|===


[source%nowrap, php]
[#deletecontent]
----

public deleteContent($pluginSetId, $contentId):void

----







Delete content. Any connections to layout containers will be removed, too.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$pluginSetId`
|link:http://php.net/int[int^]
a|The plugin set to be used to render the content. The raw content data do not depend on a plugin set.

a|`$contentId`
|link:http://php.net/int[int^]
a|The ID of the content to be deleted.
|===


[source%nowrap, php]
[#duplicatecontent]
----

public duplicateContent($contentId, $targetPluginSetId, $language, $containerName, $contentName):Plenty\Modules\ShopBuilder\Models\Content

----




====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_content[`Content`]


Duplicate a content and its link.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$contentId`
|link:http://php.net/int[int^]
a|The ID of the content to be duplicated.

a|`$targetPluginSetId`
|link:http://php.net/int[int^]
a|ID of the plugin set to link the duplicated content to.

a|`$language`
|link:http://php.net/string[string^]
a|Language to link the duplicated content to.

a|`$containerName`
|link:http://php.net/string[string^]
a|Name of the layout container to link the duplicated content to.

a|`$contentName`
|link:http://php.net/string[string^]
a|Name of the duplicated content.
|===


[source%nowrap, php]
[#rebuildcontents]
----

public rebuildContents($containerName = null, $pluginSetId):int

----







Rebuild all contents linked to the current plugin set.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$containerName`
|link:http://php.net/string[string^]
a|Name of the layout container to rebuild contents for.

a|`$pluginSetId`
|link:http://php.net/int[int^]
a|ID of the plugin set to rebuild contents for.
|===



[[shopbuilder_contracts_contentwidgetrepositorycontract]]
==== ContentWidgetRepositoryContract

Register shopBuilder widgets.



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
[#registerwidget]
----

public registerWidget($widgetClass):void

----







Register a widget to be available in the shopBuilder.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$widgetClass`
|link:http://php.net/string[string^]
a|Widget class to be registered to the shopBuilder. Should implement the Widget interface.
|===


[source%nowrap, php]
[#overridewidget]
----

public overrideWidget($widgetIdentifier, $overrideWidget):void

----







Override a widget class to extend data or settings of the widget.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$widgetIdentifier`
|link:http://php.net/string[string^]
a|The identifier of the original widget to override.

a|`$overrideWidget`
|link:http://php.net/string[string^]
a|The class of the new class to get information of the widget from.
|===



[[shopbuilder_contracts_dynamicwidget]]
==== DynamicWidget

Contract for widgets with dynamic settings



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
[#getdata]
----

public getData():array

----







Get base data of the widget. Each widget should define at least an
identifier and a label to be displayed in the builder. In total the following information can be provided:
&lt;ul&gt;
 &lt;li&gt;identifier: A unique identifier of the widget. This is used to identify widgets when loading widgets of a content in the builder.&lt;/li&gt;
 &lt;li&gt;label: The label of the widget to be displayed in the list of available widgets in the builder.&lt;/li&gt;
 &lt;li&gt;previewImageURL: The url of the preview image to be displayed in the list of available widgets in the builder.&lt;/li&gt;
 &lt;li&gt;type: The type of the widget. This is used to restrict possible locations of the widgets using the allowedNestingTypes.&lt;/li&gt;
 &lt;li&gt;categories: A list of category keys defined in the list of categories to be displayed in the list of available widgets. If no correspondig category exists, the widget will be located in a generic category.&lt;/li&gt;
 &lt;li&gt;position: The position of the widget in the list of available widgets&lt;/li&gt;
 &lt;li&gt;maxPerPage: Restrict the amount of times the widget can be placed on a single content.&lt;/li&gt;
 &lt;li&gt;allowedNestingTypes: A list of widget types that are allowed to be placed in child dropzones of the widget.&lt;/li&gt;
 &lt;li&gt;deprecated: set to true to hide the widget in the list of available widgets. Existing deprecated widgets can still be edited but not added anymore.&lt;/li&gt;
&lt;/ul&gt;

[source%nowrap, php]
[#getsettings]
----

public getSettings():array

----







Get the settings of the widgets. Settings are displayed in a terra-form when the widget is selected in the builder.

[source%nowrap, php]
[#getpreview]
----

public getPreview($widgetSettings = [], $children = []):string

----







Render the template of the widget twice to get the final markup to be displayed in the preview of the builder.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$widgetSettings`
|link:http://php.net/array[array^]
a|

a|`$children`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#render]
----

public render($widgetSettings = [], $children = []):string

----







Render the template of the widget.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$widgetSettings`
|link:http://php.net/array[array^]
a|

a|`$children`
|link:http://php.net/array[array^]
a|
|===



[[shopbuilder_contracts_globalsettingshandler]]
==== GlobalSettingsHandler

Contract for classes handling global settings for the ShopBuilder. Handler classes can be registered in the shopBuilder.json of a plugin.



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
[#readsettings]
----

public readSettings():void

----







Read values of global settings.

[source%nowrap, php]
[#writesettings]
----

public writeSettings($values):void

----







Store values of global settings.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$values`
|
a|Setting values for the global settings defined by this handler.
|===



[[shopbuilder_contracts_widget]]
==== Widget

Contract for content widgets



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
[#getpreview]
----

public getPreview($widgetSettings = [], $children = []):string

----







Render the template of the widget twice to get the final markup to be displayed in the preview of the builder.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$widgetSettings`
|link:http://php.net/array[array^]
a|

a|`$children`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#render]
----

public render($widgetSettings = [], $children = []):string

----







Render the template of the widget.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$widgetSettings`
|link:http://php.net/array[array^]
a|

a|`$children`
|link:http://php.net/array[array^]
a|
|===


[[shopbuilder_shopbuilder_factories]]
===  Factories
[[shopbuilder_factories_widgetsettingsfactory]]
==== WidgetSettingsFactory

Factory to generate widget settings



===== Namespace

`Plenty\Modules\ShopBuilder\Factories`






===== Methods

[source%nowrap, php]
[#inherit]
----

public static inherit($parentWidgetClass):Plenty\Modules\ContentBuilder\Factories\WidgetSettingsFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_factories_widgetsettingsfactory[`WidgetSettingsFactory`]


Create a new factory instance and initialize values from given widget class.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$parentWidgetClass`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):Plenty\Modules\ContentBuilder\Factories\WidgetSettingsFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_factories_widgetsettingsfactory[`WidgetSettingsFactory`]


Create a new factory instance with initial values.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#createsetting]
----

public createSetting($key, $settingsFactory = &quot;&quot;, $args = []):void

----







Create a generic widget settings entry.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The key of the new settings entry. If key already exists, previous entry will be overridden.

a|`$settingsFactory`
|link:http://php.net/string[string^]
a|Class name of the settings factory to add an instance of

a|`$args`
|link:http://php.net/array[array^]
a|Arguments to be passed to the factory constructor method
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Generate settings data from all registered factories

[source%nowrap, php]
[#withpointer]
----

public withPointer($key):Plenty\Modules\ContentBuilder\Factories\WidgetSettingsFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_factories_widgetsettingsfactory[`WidgetSettingsFactory`]


Set a settings key to insert new settings after.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#addsetting]
----

public addSetting($key, $setting):void

----







Insert a new settings factory at the current pointer.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|

a|`$setting`
|
a|
|===


[[shopbuilder_shopbuilder_helper]]
===  Helper
[[shopbuilder_helper_mappablesettingshandler]]
==== MappableSettingsHandler

Helper to map global configurations to plugin configs.



===== Namespace

`Plenty\Modules\ShopBuilder\Helper`






[[shopbuilder_helper_shopbuilderrequest]]
==== ShopBuilderRequest

Get information about the current request made from the shop builder preview.



===== Namespace

`Plenty\Modules\ShopBuilder\Helper`






===== Methods

[source%nowrap, php]
[#isshopbuilder]
----

public isShopBuilder():bool

----







Determine if the current request is made from the shop builder preview or while rendering a widget via REST.

[source%nowrap, php]
[#getpreviewcontenttype]
----

public getPreviewContentType():string

----







Get the type of the previewed shop builder content.

[source%nowrap, php]
[#getpreviewuri]
----

public getPreviewUri():void

----







Get uri of the current preview. This might be used when rendering widgets via REST
to know the context where the widget will be placed into after rendering.

[source%nowrap, php]
[#getmaincontenttype]
----

public getMainContentType():string

----







Get the content type of the currently displayed main content.

[source%nowrap, php]
[#setmaincontenttype]
----

public setMainContentType($mainContentType):void

----







Set the type of the currently displayed item content
This will be used to determine the corresponding header/footer contents which are linked to a specific type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mainContentType`
|link:http://php.net/string[string^]
a|Possible values:
<ul>
 <li>content</li>
 <li>checkout</li>
 <li>myaccount</li>
 <li>singleitem</li>
 <li>categoryitem</li>
 <li>itemsearch</li>
 <li>itemset</li>
</ul>
|===


[source%nowrap, php]
[#getmaincontainername]
----

public getMainContainerName():string

----







Get the container name where the main content will be loaded into.

[source%nowrap, php]
[#setmaincontainername]
----

public setMainContainerName($mainContainerName):void

----







Set the container name where the main content will be loaded into.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mainContainerName`
|link:http://php.net/string[string^]
a|Name of the layout container.
|===


[source%nowrap, php]
[#setmaincategory]
----

public setMainCategory($mainCategory):void

----







Set the id of the currently displayed category.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mainCategory`
|
a|Id of the currently displayed category.
|===


[[shopbuilder_shopbuilder_models]]
===  Models
[[shopbuilder_models_content]]
==== Content

Content created by the shop builder. May be linked to layout containers.



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the content
|dataProviderName
    |link:http://php.net/string[string^]
    a|The name of the data provider
|createdAt
    |
    a|The date when the content was created
|updatedAt
    |
    a|The date when the content was last updated
|type
    |link:http://php.net/string[string^]
    a|The type of the content
|widgets
    |
    a|The configured widgets of the content. This attribute is deprecated. Use $dropzones instead.
|dropzones
    |link:http://php.net/array[array^]
    a|Dropzones of the content
|link
    |        xref:Shopbuilder.adoc#shopbuilder_models_contentlink[`ContentLink`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[shopbuilder_models_contentlink]]
==== ContentLink

Links a content from the shop builder to a layout container of the frontend plugin.



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the content link
|contentId
    |link:http://php.net/int[int^]
    a|The ID of the content
|containerName
    |link:http://php.net/string[string^]
    a|The name of the container
|pluginSetId
    |link:http://php.net/int[int^]
    a|The Id of the plugin set
|language
    |link:http://php.net/string[string^]
    a|The language where the content is linked to.
|active
    |link:http://php.net/bool[bool^]
    a|Indicates if the link is active and the content should be visible for the frontend.
|relatedContentType
    |link:http://php.net/string[string^]
    a|The content type the content is linked to
|relatedContainerName
    |link:http://php.net/string[string^]
    a|The container name the content is linked to
|inherit
    |link:http://php.net/bool[bool^]
    a|Indicates if this content should be inherited to child contents.
|invalid
    |link:http://php.net/bool[bool^]
    a|Indicate if the content is invalid and should be regenerated on next request.
|createdAt
    |
    a|The date when the content was created
|updatedAt
    |
    a|The date when the content was last updated
|content
    |        xref:Shopbuilder.adoc#shopbuilder_models_content[`Content`]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[shopbuilder_models_contentpage]]
==== ContentPage

A content page provided by a frontend plugin.



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|identifier
    |link:http://php.net/string[string^]
    a|The identifier of the content page
|caption
    |link:http://php.net/string[string^]
    a|Translation key to read the caption from
|dropzones
    |link:http://php.net/array[array^]
    a|Available dropzones of this page to put contents into.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[shopbuilder_models_contentpagedropzone]]
==== ContentPageDropzone

Layout container of a content page where to display link contents generated by the shop builder.



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|container
    |link:http://php.net/string[string^]
    a|The container where dropped contents should be linked to.
|type
    |link:http://php.net/string[string^]
    a|The type of contents which can be linked to this dropzone.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[shopbuilder_models_contentwidget]]
==== ContentWidget

Content widget provided by a frontend plugin



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|identifier
    |link:http://php.net/string[string^]
    a|The identifier of the content widget
|widgetClass
    |link:http://php.net/string[string^]
    a|The class of the content widget
|label
    |link:http://php.net/string[string^]
    a|The label of the content widget
|tooltip
    |link:http://php.net/string[string^]
    a|The tooltip of the content widget
|previewImageURL
    |link:http://php.net/string[string^]
    a|The preview image the content widget
|type
    |link:http://php.net/string[string^]
    a|The type of the widget
|maxPerPage
    |link:http://php.net/int[int^]
    a|Maximum occurrences per content of the widget
|categories
    |link:http://php.net/array[array^]
    a|List of categories
|allowedNestingTypes
    |link:http://php.net/array[array^]
    a|Allowed types to be nested inside this widget
|settings
    |
    a|The settings of the content widget
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[shopbuilder_models_contentwidgetpreview]]
==== ContentWidgetPreview

The rendered preview of a content widget



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|identifier
    |link:http://php.net/string[string^]
    a|
|content
    |link:http://php.net/string[string^]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[shopbuilder_shopbuilder_providers]]
===  Providers
[[shopbuilder_providers_datafieldprovider]]
==== DataFieldProvider

Base class for data field providers.



===== Namespace

`Plenty\Modules\ShopBuilder\Providers`






===== Methods

[source%nowrap, php]
[#register]
----

public register():void

----







Register data fields and child providers.

[source%nowrap, php]
[#addfield]
----

public addField($identifier, $label, $expression, $isBlockElement = false, $isDeprecated = false):void

----







Register a new data field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$identifier`
|link:http://php.net/string[string^]
a|Unique identifier of the data field

a|`$label`
|link:http://php.net/string[string^]
a|The label of the field

a|`$expression`
|link:http://php.net/string[string^]
a|The twig expression to be inserted by this field

a|`$isBlockElement`
|link:http://php.net/bool[bool^]
a|Set to true to handle the element as a block element

a|`$isDeprecated`
|link:http://php.net/bool[bool^]
a|Deprecated flag for fields
|===


[source%nowrap, php]
[#addchildprovider]
----

public addChildProvider($label, $childProviderClass, $params = [], $identifier = &quot;&quot;):void

----







Register a nested provider containing a list of child data fields.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$label`
|link:http://php.net/string[string^]
a|The label of the group

a|`$childProviderClass`
|link:http://php.net/string[string^]
a|The class name of the nested data fields provider.

a|`$params`
|link:http://php.net/array[array^]
a|Additional parameters to be passed to provider constructor method.

a|`$identifier`
|link:http://php.net/string[string^]
a|Data field identifier, class name will be used if empty
|===


[source%nowrap, php]
[#addsearchkeywords]
----

public addSearchKeywords($identifier, $keywords = []):void

----







Assign keywords to a field to be respected during search.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$identifier`
|link:http://php.net/string[string^]
a|The identifier of the field to assign keywords to.

a|`$keywords`
|link:http://php.net/array[array^]
a|A list of keywords. Each keyword may contain a translation key. A single keyword could be a comma separated list of words.
|===


[[shopbuilder_factories]]
== Factories

[[shopbuilder_factories_settings]]
===  Settings
[[shopbuilder_settings_basesettingfactory]]
==== BaseSettingFactory

Common factory to generate properties of a widget setting definition.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|data
    |
    a|
|===


===== Methods

[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_categorysettingfactory]]
==== CategorySettingFactory

Factory to define a category picker in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withdisplayresetbutton]
----

public withDisplayResetButton($displayResetButton):Plenty\Modules\ContentBuilder\Factories\Settings\CategorySettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_categorysettingfactory[`CategorySettingFactory`]


Display or hide a button to reset the current selection.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$displayResetButton`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withdisplaysearch]
----

public withDisplaySearch($displaySearch):Plenty\Modules\ContentBuilder\Factories\Settings\CategorySettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_categorysettingfactory[`CategorySettingFactory`]


Display or hide an input to search for categories with.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$displaySearch`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withshowfullselectionpath]
----

public withShowFullSelectionPath($showFullSelectionPath):Plenty\Modules\ContentBuilder\Factories\Settings\CategorySettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_categorysettingfactory[`CategorySettingFactory`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$showFullSelectionPath`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_checkboxgroupsettingfactory]]
==== CheckboxGroupSettingFactory

Factory to define a checkbox group in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withcollapsed]
----

public withCollapsed($collapsed):Plenty\Modules\ContentBuilder\Factories\Settings\CheckboxGroupSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_checkboxgroupsettingfactory[`CheckboxGroupSettingFactory`]


Collapse or expand the group by default. The group can be toggled by the user.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$collapsed`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withcheckboxvalues]
----

public withCheckboxValues($checkboxValues):Plenty\Modules\ContentBuilder\Factories\Settings\CheckboxGroupSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_checkboxgroupsettingfactory[`CheckboxGroupSettingFactory`]


Set available checkboxes of the group.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$checkboxValues`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\CheckboxGroupSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_checkboxgroupsettingfactory[`CheckboxGroupSettingFactory`]


Set the default value of the group. This should be an array of values.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_checkboxsettingfactory]]
==== CheckboxSettingFactory

Factory to define a checkbox in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withicon]
----

public withIcon($icon):Plenty\Modules\ContentBuilder\Factories\Settings\CheckboxSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_checkboxsettingfactory[`CheckboxSettingFactory`]


Set the icon of the checkbox.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$icon`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_containersettingfactory]]
==== ContainerSettingFactory

Factory to define a container for nested settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#create]
----

public static create($data = []):Plenty\Modules\ContentBuilder\Factories\Settings\ContainerSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_containersettingfactory[`ContainerSettingFactory`]


Create a new factory instance with initial value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all children as a native array

[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===



[[shopbuilder_settings_datesettingfactory]]
==== DateSettingFactory

Factory to define a date picker in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withcalendartop]
----

public withCalendarTop($isCalendarTop):Plenty\Modules\ContentBuilder\Factories\Settings\DateSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_datesettingfactory[`DateSettingFactory`]


Display the popup containing the calendar above or below the input field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isCalendarTop`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withdisplaydateformat]
----

public withDisplayDateFormat($format):Plenty\Modules\ContentBuilder\Factories\Settings\DateSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_datesettingfactory[`DateSettingFactory`]


Set the date format to apply to the input field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$format`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_doublesettingfactory]]
==== DoubleSettingFactory

Factory to define a number input in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withpriceinput]
----

public withPriceInput($isPriceInput):Plenty\Modules\ContentBuilder\Factories\Settings\DoubleSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_doublesettingfactory[`DoubleSettingFactory`]


Define if input expects a monetary value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isPriceInput`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withdecimalcount]
----

public withDecimalCount($decimalCount):Plenty\Modules\ContentBuilder\Factories\Settings\DoubleSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_doublesettingfactory[`DoubleSettingFactory`]


Set the number of decimal places for the input.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$decimalCount`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_filesettingfactory]]
==== FileSettingFactory

Factory to define a file input in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withshowpreview]
----

public withShowPreview($showPreview):Plenty\Modules\ContentBuilder\Factories\Settings\FileSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_filesettingfactory[`FileSettingFactory`]


Display the preview of the selected file.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$showPreview`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withallowedextensions]
----

public withAllowedExtensions($allowedExtensions):Plenty\Modules\ContentBuilder\Factories\Settings\FileSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_filesettingfactory[`FileSettingFactory`]


Restrict allowed file extensions.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$allowedExtensions`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#withfoldersallowed]
----

public withFoldersAllowed($foldersAllowed):Plenty\Modules\ContentBuilder\Factories\Settings\FileSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_filesettingfactory[`FileSettingFactory`]


Set to true if the user should be allowed to create new folders.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$foldersAllowed`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_radiogroupsettingfactory]]
==== RadioGroupSettingFactory

Factory to define a group of radio buttons in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withradiovalues]
----

public withRadioValues($radioValues):Plenty\Modules\ContentBuilder\Factories\Settings\RadioGroupSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_radiogroupsettingfactory[`RadioGroupSettingFactory`]


Set the available radio buttons in this group.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$radioValues`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_selectsettingfactory]]
==== SelectSettingFactory

Factory to define a selection input in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withopenontop]
----

public withOpenOnTop($openOnTop):Plenty\Modules\ContentBuilder\Factories\Settings\SelectSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_selectsettingfactory[`SelectSettingFactory`]


Set to true to open selection values above the input field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$openOnTop`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withlistboxvalues]
----

public withListBoxValues($listBoxValues):Plenty\Modules\ContentBuilder\Factories\Settings\SelectSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_selectsettingfactory[`SelectSettingFactory`]


Set available selection values.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listBoxValues`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_slidersettingfactory]]
==== SliderSettingFactory

Factory to define a slider in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withmin]
----

public withMin($min):Plenty\Modules\ContentBuilder\Factories\Settings\SliderSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_slidersettingfactory[`SliderSettingFactory`]


Set the minimum value of the slider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#withmax]
----

public withMax($max):Plenty\Modules\ContentBuilder\Factories\Settings\SliderSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_slidersettingfactory[`SliderSettingFactory`]


Set the maximum value of the slider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$max`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#withinterval]
----

public withInterval($interval):Plenty\Modules\ContentBuilder\Factories\Settings\SliderSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_slidersettingfactory[`SliderSettingFactory`]


Set the interval between the values of the slider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$interval`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#withprecision]
----

public withPrecision($precision):Plenty\Modules\ContentBuilder\Factories\Settings\SliderSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_slidersettingfactory[`SliderSettingFactory`]


Set the number of decimal places of the value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$precision`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#withshowminmax]
----

public withShowMinMax($showMinMax):Plenty\Modules\ContentBuilder\Factories\Settings\SliderSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_slidersettingfactory[`SliderSettingFactory`]


Set to true to display the minimum and maximum values at each end of the slider.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$showMinMax`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withshowticks]
----

public withShowTicks($showTicks):Plenty\Modules\ContentBuilder\Factories\Settings\SliderSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_slidersettingfactory[`SliderSettingFactory`]


Set to true to display ticks on each value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$showTicks`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_suggestionsettingfactory]]
==== SuggestionSettingFactory

Factory to define an input with suggestions in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withlistboxvalues]
----

public withListBoxValues($listBoxValues):Plenty\Modules\ContentBuilder\Factories\Settings\SuggestionSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_suggestionsettingfactory[`SuggestionSettingFactory`]


Set available values.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$listBoxValues`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_textsettingfactory]]
==== TextSettingFactory

Factory to define a text input in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withpassword]
----

public withPassword($isPassword):Plenty\Modules\ContentBuilder\Factories\Settings\TextSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_textsettingfactory[`TextSettingFactory`]


Set to true if the input field should be handled as a password input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isPassword`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withreadonly]
----

public withReadonly($isReadonly):Plenty\Modules\ContentBuilder\Factories\Settings\TextSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_textsettingfactory[`TextSettingFactory`]


Set to true if input field should be readonly.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isReadonly`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_textareasettingfactory]]
==== TextareaSettingFactory

Factory to define a textarea in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withfixedheight]
----

public withFixedHeight($isFixedHeight):Plenty\Modules\ContentBuilder\Factories\Settings\TextareaSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_textareasettingfactory[`TextareaSettingFactory`]


Set to true if the height should be fixed.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isFixedHeight`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withmaxrows]
----

public withMaxRows($maxRows):Plenty\Modules\ContentBuilder\Factories\Settings\TextareaSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_textareasettingfactory[`TextareaSettingFactory`]


Set the maximum number of rows for the textarea.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$maxRows`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_urlsettingfactory]]
==== UrlSettingFactory

Factory to define an url picker in the widget settings.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#withinternallinks]
----

public withInternalLinks($internalLinks):Plenty\Modules\ShopBuilder\Factories\Settings\UrlSettingFactory

----




====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_settings_urlsettingfactory[`UrlSettingFactory`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$internalLinks`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#create]
----

public static create($data = []):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#withtype]
----

public withType($type):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the type of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdefaultvalue]
----

public withDefaultValue($defaultValue):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the default value for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$defaultValue`
|
a|The default value
|===


[source%nowrap, php]
[#withcondition]
----

public withCondition($condition):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a condition if the setting should be visible or not.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$condition`
|link:http://php.net/string[string^]
a|Condition if the related form element should be visible or not.
|===


[source%nowrap, php]
[#withname]
----

public withName($name):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set the name of the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The label of the setting
|===


[source%nowrap, php]
[#withoption]
----

public withOption($key, $value):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set an option for the setting.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The option key

a|`$value`
|
a|The option value
|===


[source%nowrap, php]
[#withtooltip]
----

public withTooltip($tooltip):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Set a tooltip text for this input

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltip`
|link:http://php.net/string[string^]
a|An additional description of the setting
|===


[source%nowrap, php]
[#withtooltipplacement]
----

public withTooltipPlacement($tooltipPlacement):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Define the tooltip placement. Possible values are &#039;bottom&#039;, &#039;top&#039;, &#039;left&#039; or &#039;right&#039;, default is &#039;top&#039;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tooltipPlacement`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withlist]
----

public withList($min, $max):Plenty\Modules\ContentBuilder\Factories\Settings\BaseSettingFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_basesettingfactory[`BaseSettingFactory`]


Determines whether the declaration is used to render a list of the specified form field.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$min`
|link:http://php.net/int[int^]
a|Minimum number of entries.

a|`$max`
|link:http://php.net/int[int^]
a|Maximum number of entries.
If not set or smaller than 0, unlimited entries might be added by the user.
|===


[source%nowrap, php]
[#toarray]
----

public toArray():array

----







Get all data as array


[[shopbuilder_settings_valuelistfactory]]
==== ValueListFactory

Create a list of values to be used by settings with multiple predefined values.



===== Namespace

`Plenty\Modules\ShopBuilder\Factories\Settings`






===== Methods

[source%nowrap, php]
[#make]
----

public static make():Plenty\Modules\ContentBuilder\Factories\Settings\ValueListFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_valuelistfactory[`ValueListFactory`]


Create a new factory instance.

[source%nowrap, php]
[#addentry]
----

public addEntry($value, $caption):Plenty\Modules\ContentBuilder\Factories\Settings\ValueListFactory

----




====== *Return type:*        xref:Contentbuilder.adoc#contentbuilder_settings_valuelistfactory[`ValueListFactory`]


Add an entry to the list of values

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$value`
|
a|

a|`$caption`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#toarray]
----

public toArray():void

----







Get all values.

