

[[shopbuilder_shopbuilder]]
== ShopBuilder

[[shopbuilder_shopbuilder_contracts]]
===  Contracts
[[shopbuilder_contracts_contentlinkrepositorycontract]]
==== ContentLinkRepositoryContract

Get, create, delete and update links between shop builder contents and layout containers.



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
----

public getContentLinks($pluginSetId):array

----

    





Get all linked contents for a plugin set

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$pluginSetId`
a|
|===


[source%nowrap, php]
----

public getContentLink($contentLinkId):Plenty\Modules\ShopBuilder\Models\ContentLink

----

    


====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_contentlink[`ContentLink`]


Get a single connection between a content and a layout container

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentLinkId`
a|
|===


[source%nowrap, php]
----

public createContentLink($data):Plenty\Modules\ShopBuilder\Models\ContentLink

----

    


====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_contentlink[`ContentLink`]


Link a content to a layout container

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$data`
a|
|===


[source%nowrap, php]
----

public updateContentLink($contentLinkId, $data):Plenty\Modules\ShopBuilder\Models\ContentLink

----

    


====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_contentlink[`ContentLink`]


Update a link between a content and a layout container

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentLinkId`
a|

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public deleteContentLink($contentLinkId):void

----

    





Unlink a content from a layout container. The content itself will remain

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentLinkId`
a|
|===


[source%nowrap, php]
----

public getContentLinksForContainer($containerName, $pluginSetId = null, $lang = null, $contentType = null, $filterResults = true):void

----

    





Get all content links for a specific layout container.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$containerName`
a|The name of the layout container to get content links for.

|link:http://php.net/int[int^]
a|`$pluginSetId`
a|An id of a plugin set to get content links for. Active plugin set will be used by default.

|link:http://php.net/string[string^]
a|`$lang`
a|The language to get content links for. Current language will be get from session if not defined.

|link:http://php.net/string[string^]
a|`$contentType`
a|Type of the content to get

|link:http://php.net/bool[bool^]
a|`$filterResults`
a|
|===



[[shopbuilder_contracts_contentpreset]]
==== ContentPreset

Contract for content presets



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
----

public getWidgets():void

----

    





Get the widget configurations of the presets to be assigned to the created content.


[[shopbuilder_contracts_contentrepositorycontract]]
==== ContentRepositoryContract

Get, create, delete und update shop builder contents.



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
----

public getContents():array

----

    





Get all contents to be edited in the shop builder.

[source%nowrap, php]
----

public searchContents($itemsPerPage = 20, $page = 1, $params = []):Plenty\Repositories\Models\PaginatedResult

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Search for contents

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|Maximum number of items to be returned on each page

|link:http://php.net/int[int^]
a|`$page`
a|Current page

|link:http://php.net/array[array^]
a|`$params`
a|Search parameters
|===


[source%nowrap, php]
----

public getContent($contentId, $pluginSetId, $frontendLanguage = null, $versionId = &quot;&quot;):Plenty\Modules\ShopBuilder\Models\Content

----

    


====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_content[`Content`]


Get a single content.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentId`
a|Id of the content to get information for

|link:http://php.net/int[int^]
a|`$pluginSetId`
a|Plugin set id to be used for rendering widgets.

|link:http://php.net/string[string^]
a|`$frontendLanguage`
a|The language to be used for rendering the widgets.

|link:http://php.net/string[string^]
a|`$versionId`
a|The version of the content
|===


[source%nowrap, php]
----

public listContentVersions($contentId, $itemsPerPage = 20, $versionIdMarker = &quot;&quot;):void

----

    





Get a list of Versions of the specified content.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentId`
a|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|

|link:http://php.net/string[string^]
a|`$versionIdMarker`
a|
|===


[source%nowrap, php]
----

public restoreContentVersion($contentId, $versionId, $pluginSetId, $frontendLanguage = null):void

----

    





Restore a specific content version

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentId`
a|

|link:http://php.net/string[string^]
a|`$versionId`
a|

|link:http://php.net/int[int^]
a|`$pluginSetId`
a|

|
a|`$frontendLanguage`
a|
|===


[source%nowrap, php]
----

public createContent($pluginSetId, $data, $frontendLanguage = null):Plenty\Modules\ShopBuilder\Models\Content

----

    


====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_content[`Content`]


Create new content. New content will not be linked to any layout container.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$pluginSetId`
a|The plugin set to be used to render the content. The raw content data are not depending on a plugin set.

|
a|`$data`
a|The raw content data.

|link:http://php.net/string[string^]
a|`$frontendLanguage`
a|The language to be used for rendering the widgets.
|===


[source%nowrap, php]
----

public updateContent($pluginSetId, $contentId, $data, $frontendLanguage = null):Plenty\Modules\ShopBuilder\Models\Content

----

    


====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_content[`Content`]


Update content.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$pluginSetId`
a|The plugin set to be used to render the content. The raw content data are not depending on a plugin set.

|link:http://php.net/int[int^]
a|`$contentId`
a|The id of the content to be updated.

|
a|`$data`
a|The raw data of the content.

|link:http://php.net/string[string^]
a|`$frontendLanguage`
a|The language to be used for rendering the widgets.
|===


[source%nowrap, php]
----

public deleteContent($pluginSetId, $contentId):void

----

    





Delete content. Any connections to layout containers will be removed too.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$pluginSetId`
a|The plugin set to be used to render the content. The raw content data are not depending on a plugin set.

|link:http://php.net/int[int^]
a|`$contentId`
a|The id of the content to be deleted.
|===


[source%nowrap, php]
----

public duplicateContent($contentId, $targetPluginSetId, $language, $containerName, $contentName):Plenty\Modules\ShopBuilder\Models\Content

----

    


====== *Return type:*        xref:Shopbuilder.adoc#shopbuilder_models_content[`Content`]


Duplicate a content and its link

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contentId`
a|

|link:http://php.net/int[int^]
a|`$targetPluginSetId`
a|

|link:http://php.net/string[string^]
a|`$language`
a|

|link:http://php.net/string[string^]
a|`$containerName`
a|

|link:http://php.net/string[string^]
a|`$contentName`
a|
|===


[source%nowrap, php]
----

public rebuildContents($containerName = null, $pluginSetId = null):int

----

    





Rebuild all contents linked to the current plugin set.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$containerName`
a|Name of the layout container to rebuild contents for.

|link:http://php.net/int[int^]
a|`$pluginSetId`
a|Id of the plugin set to rebuild contents for.
|===



[[shopbuilder_contracts_contentwidgetrepositorycontract]]
==== ContentWidgetRepositoryContract

Register shop builder widgets.



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
----

public registerWidget($widgetClass):void

----

    





Register a widget to be available in the shop builder.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$widgetClass`
a|
|===


[source%nowrap, php]
----

public overrideWidget($widgetIdentifier, $overrideWidget):void

----

    





Override a widget class to extend data or settings of the widget.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$widgetIdentifier`
a|The identifier of the original widget to override

|link:http://php.net/string[string^]
a|`$overrideWidget`
a|The class of the new class to get information of the widget from.
|===



[[shopbuilder_contracts_dynamicwidget]]
==== DynamicWidget

Contract for widgets with dynamic settings



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
----

public getData():array

----

    





Get basic information about the widget. Possible fields are
- identifier
- label
- previewImageURL
- type
- categories
- position

[source%nowrap, php]
----

public getSettings():array

----

    





Return the structure of the settings for the widget

[source%nowrap, php]
----

public getPreview($widgetSettings = [], $children = []):string

----

    





Get the html representation of the widget

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$widgetSettings`
a|

|link:http://php.net/array[array^]
a|`$children`
a|
|===


[source%nowrap, php]
----

public render($widgetSettings = [], $children = []):string

----

    





Render the widget

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$widgetSettings`
a|

|link:http://php.net/array[array^]
a|`$children`
a|
|===



[[shopbuilder_contracts_globalsettingshandler]]
==== GlobalSettingsHandler

Contract for classes handling global settings for the ShopBuilder.



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
----

public readSettings():void

----

    





Read values of global settings.

[source%nowrap, php]
----

public writeSettings($values):void

----

    





Store values of global settings.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$values`
a|
|===



[[shopbuilder_contracts_widget]]
==== Widget

Contract for content widgets



===== Namespace

`Plenty\Modules\ShopBuilder\Contracts`






===== Methods

[source%nowrap, php]
----

public getPreview($widgetSettings = [], $children = []):string

----

    





Get the html representation of the widget

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$widgetSettings`
a|

|link:http://php.net/array[array^]
a|`$children`
a|
|===


[source%nowrap, php]
----

public render($widgetSettings = [], $children = []):string

----

    





Render the widget

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$widgetSettings`
a|

|link:http://php.net/array[array^]
a|`$children`
a|
|===


[[shopbuilder_shopbuilder_helper]]
===  Helper
[[shopbuilder_helper_mappablesettingshandler]]
==== MappableSettingsHandler

Helper to map global configurations to plugin configs.



===== Namespace

`Plenty\Modules\ShopBuilder\Helper`






[[shopbuilder_helper_shopbuilderrequest]]
==== ShopBuilderRequest

Get information about the current request made from the shop builder preview.



===== Namespace

`Plenty\Modules\ShopBuilder\Helper`






===== Methods

[source%nowrap, php]
----

public isShopBuilder():bool

----

    





Determine if the current request is made from the shop builder preview or while rendering a widget via REST.

[source%nowrap, php]
----

public getPreviewContentType():string

----

    





Get the type of the previewed shop builder content.

[source%nowrap, php]
----

public getPreviewUri():void

----

    





Get uri of the current preview. This might be used when rendering widgets via REST
to know the context where the widget will be placed into after rendering.

[source%nowrap, php]
----

public getMainContentType():string

----

    





Get the content type of the currently displayed main content.

[source%nowrap, php]
----

public setMainContentType($mainContentType):void

----

    





Set the type of the currently displayed item content
This will be used to determine the corresponding header/footer contents which are linked to a specific type.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$mainContentType`
a|Possible values:
<ul>
 <li>content</li>
 <li>checkout</li>
 <li>myaccount</li>
 <li>singleitem</li>
 <li>categoryitem</li>
 <li>itemsearch</li>
 <li>itemset</li>
</ul>
|===


[source%nowrap, php]
----

public getMainContainerName():string

----

    





Get the container name where the main content will be loaded into.

[source%nowrap, php]
----

public setMainContainerName($mainContainerName):void

----

    





Set the container name where the main content will be loaded into.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$mainContainerName`
a|Name of the layout container.
|===


[source%nowrap, php]
----

public setMainCategory($mainCategory):void

----

    





Set the id of the currently displayed category.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|
a|`$mainCategory`
a|Id of the currently displayed category.
|===


[[shopbuilder_shopbuilder_models]]
===  Models
[[shopbuilder_models_content]]
==== Content

Content created by the shop builder. May be linked to layout containers.



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the content
|link:http://php.net/string[string^]
    a|dataProviderName
    a|The name of the data provider
|
    a|createdAt
    a|The date when the content was created
|
    a|updatedAt
    a|The date when the content was last updated
|link:http://php.net/string[string^]
    a|type
    a|The type of the content
|
    a|widgets
    a|The configured widgets of the content. This attribute is deprecated. Use $dropzones instead.
|link:http://php.net/array[array^]
    a|dropzones
    a|Dropzones of the content
|        xref:Shopbuilder.adoc#shopbuilder_models_contentlink[`ContentLink`]
    a|link
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[shopbuilder_models_contentlink]]
==== ContentLink

Links a content from the shop builder to a layout container of the frontend plugin.



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the content link
|link:http://php.net/int[int^]
    a|contentId
    a|The ID of the content
|link:http://php.net/string[string^]
    a|containerName
    a|The name of the container
|link:http://php.net/int[int^]
    a|pluginSetId
    a|The Id of the plugin set
|link:http://php.net/string[string^]
    a|language
    a|The language where the content is linked to.
|link:http://php.net/bool[bool^]
    a|active
    a|Indicates if the link is active and the content should be visible for the frontend.
|link:http://php.net/string[string^]
    a|relatedContentType
    a|The content type the content is linked to
|link:http://php.net/string[string^]
    a|relatedContainerName
    a|The container name the content is linked to
|link:http://php.net/bool[bool^]
    a|inherit
    a|Indicates if this content should be inherited to child contents.
|
    a|createdAt
    a|The date when the content was created
|
    a|updatedAt
    a|The date when the content was last updated
|        xref:Shopbuilder.adoc#shopbuilder_models_content[`Content`]
    a|content
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[shopbuilder_models_contentpage]]
==== ContentPage

A content page provided by a frontend plugin.



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|identifier
    a|The identifier of the content page
|link:http://php.net/string[string^]
    a|caption
    a|Translation key to read the caption from
|link:http://php.net/array[array^]
    a|dropzones
    a|Available dropzones of this page to put contents into.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[shopbuilder_models_contentpagedropzone]]
==== ContentPageDropzone

Layout container of a content page where to display link contents generated by the shop builder.



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|container
    a|The container where dropped contents should be linked to.
|link:http://php.net/string[string^]
    a|type
    a|The type of contents which can be linked to this dropzone.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[shopbuilder_models_contentwidget]]
==== ContentWidget

Content widget provided by a frontend plugin



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|identifier
    a|The identifier of the content widget
|link:http://php.net/string[string^]
    a|widgetClass
    a|The class of the content widget
|link:http://php.net/string[string^]
    a|label
    a|The label of the content widget
|link:http://php.net/string[string^]
    a|tooltip
    a|The tooltip of the content widget
|link:http://php.net/string[string^]
    a|previewImageURL
    a|The preview image the content widget
|link:http://php.net/string[string^]
    a|type
    a|The type of the widget
|link:http://php.net/int[int^]
    a|maxPerPage
    a|Maximum occurrences per content of the widget
|link:http://php.net/array[array^]
    a|categories
    a|List of categories
|link:http://php.net/array[array^]
    a|allowedNestingTypes
    a|Allowed types to be nested inside this widget
|
    a|settings
    a|The settings of the content widget
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[shopbuilder_models_contentwidgetpreview]]
==== ContentWidgetPreview

The rendered preview of a content widget



===== Namespace

`Plenty\Modules\ShopBuilder\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|identifier
    a|
|link:http://php.net/string[string^]
    a|content
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[shopbuilder_shopbuilder_providers]]
===  Providers
[[shopbuilder_providers_datafieldprovider]]
==== DataFieldProvider

Base class for data field providers.



===== Namespace

`Plenty\Modules\ShopBuilder\Providers`






===== Methods

[source%nowrap, php]
----

public register():void

----

    







[source%nowrap, php]
----

public addField($identifier, $label, $expression):void

----

    





Register a new data field.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$identifier`
a|

|link:http://php.net/string[string^]
a|`$label`
a|The label of the field

|link:http://php.net/string[string^]
a|`$expression`
a|The twig expression to be inserted by this field
|===


[source%nowrap, php]
----

public addChildProvider($label, $childProviderClass, $params = []):void

----

    





Register a nested provider containing a list of child data fields.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$label`
a|The label of the group

|link:http://php.net/string[string^]
a|`$childProviderClass`
a|The class name of the nested data fields provider.

|link:http://php.net/array[array^]
a|`$params`
a|Additional parameters to be passed to provider constructor method.
|===


[source%nowrap, php]
----

public addSearchKeywords($identifier, $keywords = []):void

----

    





Assign keywords to a field to be respected during search.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$identifier`
a|The identifier of the field to assign keywords to.

|link:http://php.net/array[array^]
a|`$keywords`
a|A list of keywords. Each keyword may contain a translation key. A single keyword could be a comma separated list of words.
|===


