:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[stockmanagement_stock]]
= Stock

[[stockmanagement_stock_contracts]]
== Contracts
[[stockmanagement_contracts_stockrepositorycontract]]
=== StockRepositoryContract

The StockRepositoryContract is the interface for the stock repository. This interface allows you to find, create and update stock. Stock is assigned to one variation and is stored in warehouses.



==== Namespace

`Plenty\Modules\StockManagement\Stock\Contracts`






==== Methods

[source%nowrap, php]
----

public listStockByWarehouseId($warehouseId, $columns = [], $page = 1, $itemsPerPage = 50):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List stock of a warehouse

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|The ID of the warehouse

|link:http://php.net/array[array^]
a|`$columns`
a|The properties to be loaded

|link:http://php.net/int[int^]
a|`$page`
a|The requested page

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items per page
|===


[source%nowrap, php]
----

public listStock($columns = [], $page = 1, $itemsPerPage = 50):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List stock

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$columns`
a|The properties to be loaded

|link:http://php.net/int[int^]
a|`$page`
a|The requested page

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items per page
|===


[source%nowrap, php]
----

public listStockByWarehouseType($type, $columns = [], $page = 1, $itemsPerPage = 50):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List stock by warehouse type

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$type`
a|The type of the warehouse. Currently only 'sales' is supported.

|link:http://php.net/array[array^]
a|`$columns`
a|The properties to be loaded

|link:http://php.net/int[int^]
a|`$page`
a|The requested page

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items per page
|===


[source%nowrap, php]
----

public correctStock($warehouseId, $data):void

----

    





Corrects stock. The ID of the warehouse has to be provided.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|The ID of the warehouse.

|link:http://php.net/array[array^]
a|`$data`
a|The request data.
|===


[source%nowrap, php]
----

public bookIncomingItems($warehouseId, $data):void

----

    





Book incoming stock

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|The ID of the warehouse

|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public bookOutgoingItems($warehouseId, $data):void

----

    





Book outgoing stock

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|The ID of the warehouse

|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public redistributeStock($data):void

----

    





Redistribute stock

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public listStockMovements($warehouseId, $columns = [], $page = 1, $itemsPerPage = 50):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List stock movements

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|The ID of the warehouse

|link:http://php.net/array[array^]
a|`$columns`
a|The properties to be loaded

|link:http://php.net/int[int^]
a|`$page`
a|The requested page

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items per page
|===


[source%nowrap, php]
----

public unpackVariation($warehouseId, $variationStockIntake, $variationStockCorrection):Plenty\Modules\StockManagement\Warehouse\Models\Warehouse

----

    


===== *Return type:*        xref:Stockmanagement.adoc#stockmanagement_models_warehouse[`Warehouse`]


Unpack variation

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|The ID of the warehouse

|link:http://php.net/array[array^]
a|`$variationStockIntake`
a|

|link:http://php.net/array[array^]
a|`$variationStockCorrection`
a|
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[stockmanagement_contracts_stockstoragelocationrepositorycontract]]
=== StockStorageLocationRepositoryContract

The StockStorageLocationRepositoryContract is the interface for the stock storage location repository. This interface allows you to list the stock of all storage locations of a warehouse or to list all storage locations of a variation and the stock stored at these locations.



==== Namespace

`Plenty\Modules\StockManagement\Stock\Contracts`






==== Methods

[source%nowrap, php]
----

public listStockStorageLocationsByWarehouseId($warehouseId, $columns = [], $page = 1, $itemsPerPage = 50, $with = []):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List stock of all storage locations of a warehouse

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|The ID of the warehouse

|link:http://php.net/array[array^]
a|`$columns`
a|The properties to be loaded

|link:http://php.net/int[int^]
a|`$page`
a|The requested page

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items per page

|link:http://php.net/array[array^]
a|`$with`
a|The relations to load in the StockStorageLocationInstance, possible is: storageLocation
|===


[source%nowrap, php]
----

public listStockStorageLocationsByVariationId($variationId, $columns = [], $page = 1, $itemsPerPage = 50, $with = [], $sortBy = &quot;id&quot;, $sortOrder = &quot;asc&quot;):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


List stock of a variation per storage location

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$variationId`
a|The ID of the variation.

|link:http://php.net/array[array^]
a|`$columns`
a|The properties to be loaded

|link:http://php.net/int[int^]
a|`$page`
a|The requested page

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|The number of items per page

|link:http://php.net/array[array^]
a|`$with`
a|The relations to load in the StockStorageLocationInstance, possible is: storageLocation

|link:http://php.net/string[string^]
a|`$sortBy`
a|[optional]

|link:http://php.net/string[string^]
a|`$sortOrder`
a|[optional, default=asc]
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[[stockmanagement_stock_models]]
== Models
[[stockmanagement_models_stock]]
=== Stock

The stock model. There are 4 different stock terms used in plentymarkets. The physical stock, the net stock, the reserved stock and the stock reserved for listings.



==== Namespace

`Plenty\Modules\StockManagement\Stock\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|itemId
    a|The ID of the item
|link:http://php.net/int[int^]
    a|variationId
    a|The ID of the variation
|link:http://php.net/int[int^]
    a|warehouseId
    a|The ID of the warehouse
|link:http://php.net/float[float^]
    a|stockPhysical
    a|The physical stock
|link:http://php.net/float[float^]
    a|reservedStock
    a|The reserved stock
|link:http://php.net/float[float^]
    a|reservedEbay
    a|The stock reserved for ebay
|link:http://php.net/float[float^]
    a|reorderDelta
    a|The reorder delta
|link:http://php.net/float[float^]
    a|stockNet
    a|The net stock
|link:http://php.net/int[int^]
    a|reordered
    a|The reordered quantity of a variation
|link:http://php.net/int[int^]
    a|warehousePriority
    a|The priority of the warehouse
|link:http://php.net/float[float^]
    a|reservedBundle
    a|Reserved bundle
|link:http://php.net/float[float^]
    a|averagePurchasePrice
    a|The average purchase price
|
    a|updatedAt
    a|The time the stock was last updated
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[stockmanagement_models_stockbatchbestbeforedate]]
=== StockBatchBestBeforeDate

The stock batch best before date model contains all information about the batch and best before date.



==== Namespace

`Plenty\Modules\StockManagement\Stock\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    a|batch
    a|
|link:http://php.net/string[string^]
    a|bestBeforeDate
    a|
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[stockmanagement_models_stockstoragelocation]]
=== StockStorageLocation

The stock storage location model contains all information about the stock that is stored at one storage location.



==== Namespace

`Plenty\Modules\StockManagement\Stock\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|itemId
    a|The ID of the item
|link:http://php.net/int[int^]
    a|variationId
    a|The ID of the variation
|link:http://php.net/int[int^]
    a|storageLocationId
    a|The ID of the storage location.
|link:http://php.net/int[int^]
    a|warehouseId
    a|The ID of the warehouse that the storage location is in
|link:http://php.net/float[float^]
    a|quantity
    a|The quantity stored at the storage location
|link:http://php.net/string[string^]
    a|bestBeforeDate
    a|The best before date
|link:http://php.net/string[string^]
    a|batch
    a|The batch
|
    a|updatedAt
    a|The day and time the stock was last updated
|        xref:Stockmanagement.adoc#stockmanagement_models_storagelocation[`StorageLocation`]
    a|storageLocation
    a|Deprecated! Use warehouseLocation instead
|        xref:Warehouse.adoc#warehouse_models_warehouselocation[`WarehouseLocation`]
    a|warehouseLocation
    a|The warehouse location of the item
|        xref:Item.adoc#item_models_variation[`Variation`]
    a|variation
    a|The variation of the item
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[stockmanagement_warehouse]]
= Warehouse

[[stockmanagement_warehouse_contracts]]
== Contracts
[[stockmanagement_contracts_warehouserepositorycontract]]
=== WarehouseRepositoryContract

The WarehouseRepositoryContract is the interface for the warehouse repository. This interface allows you to either get one warehouse by specifying the id or to list all warehouses.



==== Namespace

`Plenty\Modules\StockManagement\Warehouse\Contracts`






==== Methods

[source%nowrap, php]
----

public findById($warehouseId, $with = []):Plenty\Modules\StockManagement\Warehouse\Models\Warehouse

----

    


===== *Return type:*        xref:Stockmanagement.adoc#stockmanagement_models_warehouse[`Warehouse`]


Get a warehouse

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|The id of the warehouse.

|link:http://php.net/array[array^]
a|`$with`
a|The relations to load in the warehouse instance. repairWarehouse is the only relation currently available.
|===


[source%nowrap, php]
----

public all($with = [], $columns = []):array

----

    





List warehouses

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$with`
a|The relations to load in the warehouse instance. repairWarehouse is the only relation currently available.

|link:http://php.net/array[array^]
a|`$columns`
a|The columns to load in the response
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\StockManagement\Warehouse\Models\Warehouse

----

    


===== *Return type:*        xref:Stockmanagement.adoc#stockmanagement_models_warehouse[`Warehouse`]


Create a warehouse

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data.
|===


[[stockmanagement_warehouse_models]]
== Models
[[stockmanagement_models_warehouse]]
=== Warehouse

The warehouse model in plentymarkets represents actual warehouses. Every warehouse is identified by an Id. Furthermore a warehouse is described by a name and is always associated with an address. This address may not only contain a physical address information like a street, a house number, a postal code and a town, but also an email address, a telephone number or a fax number.



==== Namespace

`Plenty\Modules\StockManagement\Warehouse\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The id of the warehouse
|link:http://php.net/string[string^]
    a|name
    a|The name of the warehouse
|link:http://php.net/string[string^]
    a|note
    a|A note for this warehouse
|link:http://php.net/int[int^]
    a|typeId
    a|The id of the warehouse type. The following types are available:
<ul>
    <li>0 = Sales warehouse</li>
    <li>1 = Repair warehouse</li>
    <li>4 = Storage warehouse</li>
    <li>5 = Transit warehouse</li>
    <li>6 = Distribution warehouse</li>
    <li>7 = Other</li>
</ul>
|link:http://php.net/array[array^]
    a|allocationReferrerIds
    a|Allocation Referrer Ids by automatic warehouse detection
|link:http://php.net/int[int^]
    a|onStockAvailability
    a|Displayed availability of a variation if stock is available
|link:http://php.net/int[int^]
    a|outOfStockAvailability
    a|Displayed availability of a variation if no stock is available
|link:http://php.net/bool[bool^]
    a|splitByShippingProfile
    a|Flag that indicates if for this warehouse orders are split by shipping profiles or not. <ul><li>True = Orders are split by shipping profiles</li> <li>False = Orders will not be split by shipping profiles</li></ul>
|link:http://php.net/string[string^]
    a|storageLocationType
    a|The storage location type. The following types are available: <ul><li>none</li> <li>small</li><li>medium</li> <li>large</li> <li>europallet</li></ul>
|link:http://php.net/int[int^]
    a|storageLocationZone
    a|The zone that the storage location is in
|link:http://php.net/int[int^]
    a|repairWarehouseId
    a|The id of the associated repair warehouse
|link:http://php.net/bool[bool^]
    a|isInventoryModeActive
    a|Flag that indicates if the inventory mode for this warehouse is active or not. <ul><li>True = active</li> <li>False = inactive</li></ul>
|link:http://php.net/string[string^]
    a|logisticsType
    a|The id of the logistics type of the warehouse. The logistics type states which service provider fulfills the storage and shipping. The following logistics types are available:
<ul>
<li>own</li>
<li>amazon</li>
<li>dhlFulfillment</li>
</ul>
|        xref:Account.adoc#account_models_address[`Address`]
    a|address
    a|The address that the warehouse is located at
|        xref:Stockmanagement.adoc#stockmanagement_models_warehouse[`Warehouse`]
    a|repairWarehouse
    a|All information about the repair warehouse if a repair warehouse is linked to the sales warehouse
|link:http://php.net/string[string^]
    a|updatedAt
    a|The updated at timestamp of the warehouse
|link:http://php.net/string[string^]
    a|createdAt
    a|The created at timestamp of the warehouse
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

[[stockmanagement_management]]
= Management

[[stockmanagement_management_contracts]]
== Contracts
[[stockmanagement_contracts_rackmanagementrepositorycontract]]
=== RackManagementRepositoryContract

The RackManagementRepositoryContract is the interface for the rack management repository. This interface provides the functionality to manage the warehouse configuration for racks. Racks can be retrieved, created or updated here.

[WARNING]
.Deprecated! [small]#(since 2018-03)#
====

Please use Plenty\Modules\Warehouse\Contracts\WarehouseLocationDimensionRepositoryContract instead

====


==== Namespace

`Plenty\Modules\StockManagement\Warehouse\Management\Contracts`






==== Methods

[source%nowrap, php]
----

public getRackById($rackId, $columns = [], $with = []):Plenty\Modules\StockManagement\Warehouse\Management\Models\Rack

----

    


===== *Return type:*        xref:Stockmanagement.adoc#stockmanagement_models_rack[`Rack`]


Find a rack by id.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$rackId`
a|The id of the rack.

|link:http://php.net/array[array^]
a|`$columns`
a|The attributes to be loaded.

|link:http://php.net/array[array^]
a|`$with`
a|The relations to be loaded. Possible values are 'warehouse', 'shelves' and 'storageLocations'.
|===


[source%nowrap, php]
----

public findRacks($page = 1, $itemsPerPage = 50, $columns = [], $with = []):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Find racks. The results can be filtered by warehouse id.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|The requested page.

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|Number of items per page.

|link:http://php.net/array[array^]
a|`$columns`
a|The attributes to be loaded.

|link:http://php.net/array[array^]
a|`$with`
a|The relations to be loaded. Possible values are 'warehouse', 'shelves' and 'storageLocations'.
|===


[source%nowrap, php]
----

public createRack($data, $warehouseId):Plenty\Modules\StockManagement\Warehouse\Management\Models\Rack

----

    


===== *Return type:*        xref:Stockmanagement.adoc#stockmanagement_models_rack[`Rack`]


Create a new rack.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The data to create a new rack.

|link:http://php.net/int[int^]
a|`$warehouseId`
a|The id of the warehouse the rack shall belong to.
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[stockmanagement_contracts_shelfmanagementrepositorycontract]]
=== ShelfManagementRepositoryContract

The ShelfManagementRepositoryContract is the interface for the shelf management repository. This interface provides the functionality to manage the warehouse configuration for shelves. Shelves can be retrieved, created or updated here.

[WARNING]
.Deprecated! [small]#(since 2018-03)#
====

Please use Plenty\Modules\Warehouse\Contracts\WarehouseLocationDimensionRepositoryContract instead

====


==== Namespace

`Plenty\Modules\StockManagement\Warehouse\Management\Contracts`






==== Methods

[source%nowrap, php]
----

public getShelfById($shelfId, $columns = [], $with = []):Plenty\Modules\StockManagement\Warehouse\Management\Models\Shelf

----

    


===== *Return type:*        xref:Stockmanagement.adoc#stockmanagement_models_shelf[`Shelf`]


Find a shelf by id.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$shelfId`
a|The id of the shelf.

|link:http://php.net/array[array^]
a|`$columns`
a|The attributes to be loaded.

|link:http://php.net/array[array^]
a|`$with`
a|The relations to be loaded. Possible values are 'warehouse', 'rack' and 'storageLocations'.
|===


[source%nowrap, php]
----

public findShelves($page = 1, $itemsPerPage = 50, $columns = [], $with = []):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Find shelves. The results can be filtered by warehouse id and rack id.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|The requested page.

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|Number of items per page.

|link:http://php.net/array[array^]
a|`$columns`
a|The attributes to be loaded.

|link:http://php.net/array[array^]
a|`$with`
a|The relations to be loaded. Possible values are 'warehouse', 'rack' and 'storageLocations'.
|===


[source%nowrap, php]
----

public createShelf($data, $warehouseId, $rackId):Plenty\Modules\StockManagement\Warehouse\Management\Models\Shelf

----

    


===== *Return type:*        xref:Stockmanagement.adoc#stockmanagement_models_shelf[`Shelf`]


Create a new shelf.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The data to create a new shelf.

|link:http://php.net/int[int^]
a|`$warehouseId`
a|The id of the warehouse the shelf shall belong to.

|link:http://php.net/int[int^]
a|`$rackId`
a|The id of the rack the shelf shall belong to.
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[stockmanagement_contracts_storagelocationmanagementrepositorycontract]]
=== StorageLocationManagementRepositoryContract

The StorageLocationManagementRepositoryContract is the interface for the storage location management repository. This interface provides the functionality to manage the warehouse configuration for storage locations. Storage locations can be retrieved, created or updated here.

[WARNING]
.Deprecated! [small]#(since 2018-03)#
====

Please use Plenty\Modules\Warehouse\Contracts\WarehouseLocationRepositoryContract instead

====


==== Namespace

`Plenty\Modules\StockManagement\Warehouse\Management\Contracts`






==== Methods

[source%nowrap, php]
----

public getStorageLocationById($storageLocationId, $columns = [], $with = []):Plenty\Modules\StockManagement\Warehouse\Management\Models\StorageLocation

----

    


===== *Return type:*        xref:Stockmanagement.adoc#stockmanagement_models_storagelocation[`StorageLocation`]


Find a storage location by id.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$storageLocationId`
a|The id of the storage location.

|link:http://php.net/array[array^]
a|`$columns`
a|The attributes to be loaded.

|link:http://php.net/array[array^]
a|`$with`
a|The relations to be loaded. Possible values are 'warehouse', 'rack' and 'shelf'.
|===


[source%nowrap, php]
----

public findStorageLocations($page = 1, $itemsPerPage = 50, $columns = [], $with = []):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Find storage locations. The results can be filtered by warehouse id, rack id and shelf id.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|The requested page.

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|Number of items per page.

|link:http://php.net/array[array^]
a|`$columns`
a|The attributes to be loaded.

|link:http://php.net/array[array^]
a|`$with`
a|The relations to be loaded. Possible values are 'warehouse', 'rack' and 'shelf'.
|===


[source%nowrap, php]
----

public createStorageLocation($data, $warehouseId, $rackId, $shelfId):Plenty\Modules\StockManagement\Warehouse\Management\Models\StorageLocation

----

    


===== *Return type:*        xref:Stockmanagement.adoc#stockmanagement_models_storagelocation[`StorageLocation`]


Create a new storage location.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The data to create a new storage location.

|link:http://php.net/int[int^]
a|`$warehouseId`
a|The id of the warehouse the storage location shall belong to.

|link:http://php.net/int[int^]
a|`$rackId`
a|The id of the rack the storage location shall belong to.

|link:http://php.net/int[int^]
a|`$shelfId`
a|The id of the shelf the storage location shall belong to.
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[[stockmanagement_management_models]]
== Models
[[stockmanagement_models_rack]]
=== Rack

The storage rack model



==== Namespace

`Plenty\Modules\StockManagement\Warehouse\Management\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The id of the rack.
|link:http://php.net/int[int^]
    a|name
    a|The name of the rack.
|link:http://php.net/int[int^]
    a|position
    a|The position of the rack.
|link:http://php.net/int[int^]
    a|warehouseId
    a|The id of the warehouse the rack belongs to.
|link:http://php.net/int[int^]
    a|zone
    a|The zone of the rack. Numbers between 1 and 20 are valid.
|        xref:Stockmanagement.adoc#stockmanagement_models_warehouse[`Warehouse`]
    a|warehouse
    a|The warehouse this rack belongs to.
|
    a|shelves
    a|The shelves that belong to this rack.
|
    a|storageLocations
    a|The storage locations that belong to this rack.
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[stockmanagement_models_shelf]]
=== Shelf

The storage shelf model



==== Namespace

`Plenty\Modules\StockManagement\Warehouse\Management\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The id of the shelf.
|link:http://php.net/int[int^]
    a|rackId
    a|The id of the rack the shelf belongs to.
|link:http://php.net/string[string^]
    a|name
    a|The name of the shelf.
|link:http://php.net/int[int^]
    a|level
    a|The level of the shelf. Numbers between 1 and 25 are valid.
|        xref:Stockmanagement.adoc#stockmanagement_models_rack[`Rack`]
    a|rack
    a|The rack this shelf belongs to.
|
    a|storageLocations
    a|The storage locations of this shelf.
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[stockmanagement_models_storagelocation]]
=== StorageLocation

The storage location model



==== Namespace

`Plenty\Modules\StockManagement\Warehouse\Management\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The id of the storage location.
|link:http://php.net/int[int^]
    a|warehouseId
    a|The id of the warehouse the storage location belongs to.
|link:http://php.net/int[int^]
    a|rackId
    a|The id of the rack the storage location belongs to.
|link:http://php.net/int[int^]
    a|shelfId
    a|The id of the shelf the storage location belongs to.
|link:http://php.net/string[string^]
    a|name
    a|The name of the storage location.
|link:http://php.net/int[int^]
    a|type
    a|The type of the storage location. Valid strings are: 'small', 'medium', 'large', 'europallet'.
|link:http://php.net/int[int^]
    a|position
    a|The position of the storage location.
|        xref:Stockmanagement.adoc#stockmanagement_models_warehouse[`Warehouse`]
    a|warehouse
    a|The warehouse this storage location belongs to.
|        xref:Stockmanagement.adoc#stockmanagement_models_rack[`Rack`]
    a|rack
    a|The rack this storage location belongs to.
|        xref:Stockmanagement.adoc#stockmanagement_models_shelf[`Shelf`]
    a|shelf
    a|The shelf this storage location belongs to.
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

