:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[tag_tag]]
== Tag

[[tag_tag_contracts]]
===  Contracts
[[tag_contracts_tagavailabilityrepositorycontract]]
==== TagAvailabilityRepositoryContract

The TagAvailabilityRepositoryContract is the interface for the tag availability repository. This interface allows to update and create tag availabilities.



===== Namespace

`Plenty\Modules\Tag\Contracts`






===== Methods

[source%nowrap, php]
----

public update($data, $tagId, $availabilityType):Plenty\Modules\Tag\Models\TagAvailability

----




====== *Return type:*        xref:Tag.adoc#tag_models_tagavailability[`TagAvailability`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The availability data. The properties that are required to update an tag can be found in the TagAvailability model.

a|`$tagId`
|link:http://php.net/int[int^]
a|The ID of the tag

a|`$availabilityType`
|link:http://php.net/string[string^]
a|The type of the availability. The following types are available.
<ul>
<li>blog</li>
<li>category</li>
<li>content_page</li>
<li>variation</li>
<li>ticket</li>
</ul>
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\Tag\Models\TagAvailability

----




====== *Return type:*        xref:Tag.adoc#tag_models_tagavailability[`TagAvailability`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The availability data. The properties that are required to update an tag can be found in the TagAvailability model.
|===


[source%nowrap, php]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.


[[tag_contracts_tagnamerepositorycontract]]
==== TagNameRepositoryContract

The TagNameRepositoryContract is the interface for the tag name repository. This interface allows to update, create and list tag names.



===== Namespace

`Plenty\Modules\Tag\Contracts`






===== Methods

[source%nowrap, php]
----

public update($data, $tagId, $lang):Plenty\Modules\Tag\Models\TagName

----




====== *Return type:*        xref:Tag.adoc#tag_models_tagname[`TagName`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The name data. The properties that are required to update an name can be found in the TagName model.

a|`$tagId`
|link:http://php.net/int[int^]
a|The ID of the tag

a|`$lang`
|link:http://php.net/string[string^]
a|The language of the name
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\Tag\Models\TagName

----




====== *Return type:*        xref:Tag.adoc#tag_models_tagname[`TagName`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The name data. The properties that are required to update an name can be found in the TagName model.
|===


[source%nowrap, php]
----

public findByName($name, $lang):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The name of the tag

a|`$lang`
|link:http://php.net/string[string^]
a|The language of the name
|===


[source%nowrap, php]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.


[[tag_contracts_tagrelationshiprepositorycontract]]
==== TagRelationshipRepositoryContract

The TagRelationshipRepositoryContract is the interface for the tag relationship repository. This interface allows to update, create, delete and list tag relationships.



===== Namespace

`Plenty\Modules\Tag\Contracts`






===== Methods

[source%nowrap, php]
----

public update($data, $tagId, $availabilityType, $relationshipValue):Plenty\Modules\Tag\Models\TagRelationship

----




====== *Return type:*        xref:Tag.adoc#tag_models_tagrelationship[`TagRelationship`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The relationship data. The properties that are required to update a relationship can be found in the TagRelationship model.

a|`$tagId`
|link:http://php.net/int[int^]
a|The ID of the tag

a|`$availabilityType`
|link:http://php.net/string[string^]
a|The type of the availability. The following types are available:
<ul>
<li>category</li>
<li>variation</li>
<li>ticket</li>
</ul>

a|`$relationshipValue`
|link:http://php.net/int[int^]
a|The value of the relationship. This value is the ID of the data set the tag is linked to, e.g. item ID 1234.
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\Tag\Models\TagRelationship

----




====== *Return type:*        xref:Tag.adoc#tag_models_tagrelationship[`TagRelationship`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The relationship data. The properties that are required to update a relationship can be found in the TagRelationship model.
|===


[source%nowrap, php]
----

public deleteRelation($relationshipValue, $tagId):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationshipValue`
|link:http://php.net/int[int^]
a|The value of the relationship. This value is the ID of the data set the tag is linked to, e.g. item ID 1234.

a|`$tagId`
|link:http://php.net/int[int^]
a|The ID of the tag
|===


[source%nowrap, php]
----

public deleteOneRelation($relationshipValue, $relationshipType, $tagId):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationshipValue`
|link:http://php.net/int[int^]
a|The value of the relationship. This value is the ID of the data set the tag is linked to, e.g. item ID 1234.

a|`$relationshipType`
|link:http://php.net/string[string^]
a|The type of the relationship, i.e. <b>category</b>, <b>item</b> or <b>ticket</b>

a|`$tagId`
|link:http://php.net/int[int^]
a|The ID of the tag
|===


[source%nowrap, php]
----

public deleteOneRelationByUUID($relationshipUUID, $relationshipType, $tagId):int

----







Delete a tag relationship by the uuid5 value.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationshipUUID`
|link:http://php.net/string[string^]
a|The uuid5 value of the relationship.

a|`$relationshipType`
|link:http://php.net/string[string^]
a|The type of the relationship, i.e. <b>board</b>

a|`$tagId`
|link:http://php.net/int[int^]
a|The ID of the tag
|===


[source%nowrap, php]
----

public findByValueId($valueId):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$valueId`
|link:http://php.net/int[int^]
a|The value of the relationship. This value is the ID of the data set the tag is linked to, e.g. item ID 1234.
|===


[source%nowrap, php]
----

public findByTagId($tagId):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tagId`
|link:http://php.net/int[int^]
a|The ID of the tag
|===


[source%nowrap, php]
----

public findRelationship($tagId, $relationshipValue, $relationshipType):Plenty\Modules\Tag\Models\TagRelationship

----




====== *Return type:*        xref:Tag.adoc#tag_models_tagrelationship[`TagRelationship`]


Gets a specific tag relationship or returns null.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tagId`
|link:http://php.net/int[int^]
a|The ID of the tag

a|`$relationshipValue`
|link:http://php.net/int[int^]
a|The value of the relationship

a|`$relationshipType`
|link:http://php.net/string[string^]
a|The type of the relationship
|===


[source%nowrap, php]
----

public delete($relationshipValue, $relationshipType):Plenty\Repositories\Models\DeleteResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes tag links by reference value and relationship type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationshipValue`
|link:http://php.net/int[int^]
a|The value of the relationship

a|`$relationshipType`
|link:http://php.net/string[string^]
a|The type of the relationship
|===


[source%nowrap, php]
----

public deleteByUUID($relationshipValue, $relationshipType):Plenty\Repositories\Models\DeleteResponse

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_deleteresponse[`DeleteResponse`]


Deletes tag links by uuid5 reference value and relationship type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationshipValue`
|link:http://php.net/string[string^]
a|The value of the relationship

a|`$relationshipType`
|link:http://php.net/string[string^]
a|The type of the relationship
|===


[source%nowrap, php]
----

public deleteBulk($data):Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Deletes a list of tag relationships. The tag ID, tag type and relation value must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The array containing the data.
|===


[source%nowrap, php]
----

public listRelationships($with = []):Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Returns all tag relationships.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$with`
|link:http://php.net/array[array^]
a|An array with child instances to be loaded
|===


[source%nowrap, php]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----







Clears the filter array.


[[tag_contracts_tagrepositorycontract]]
==== TagRepositoryContract

The TagRepositoryContract is the interface for the tag repository. This interface allows to create, update and delete tags.



===== Namespace

`Plenty\Modules\Tag\Contracts`






===== Methods

[source%nowrap, php]
----

public create($name):Plenty\Modules\Tag\Models\Tag

----




====== *Return type:*        xref:Tag.adoc#tag_models_tag[`Tag`]


Creates a new tag.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The name of the tag
|===


[source%nowrap, php]
----

public update($data, $tagId):Plenty\Modules\Tag\Models\Tag

----




====== *Return type:*        xref:Tag.adoc#tag_models_tag[`Tag`]


Updates a tag.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The tag data. The properties that are required to update a tag can be found in the Tag model.

a|`$tagId`
|link:http://php.net/int[int^]
a|The ID of the tag
|===


[source%nowrap, php]
----

public delete($tagId):void

----







Deletes a tag by the given tag ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tagId`
|link:http://php.net/int[int^]
a|The ID of the tag
|===


[source%nowrap, php]
----

public getTagByName($name):Plenty\Modules\Tag\Models\Tag

----




====== *Return type:*        xref:Tag.adoc#tag_models_tag[`Tag`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The name of the tag
|===


[source%nowrap, php]
----

public getTagsByIds($ids):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ids`
|link:http://php.net/array[array^]
a|The IDs of the tags
|===


[source%nowrap, php]
----

public getTagById($id, $with = []):Plenty\Modules\Tag\Models\Tag

----




====== *Return type:*        xref:Tag.adoc#tag_models_tag[`Tag`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$id`
|link:http://php.net/int[int^]
a|The ID of the tag

a|`$with`
|link:http://php.net/array[array^]
a|An array with child instances to be loaded
|===


[source%nowrap, php]
----

public getTagsByAvailability($availabilityType):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$availabilityType`
|link:http://php.net/string[string^]
a|The type of the availability. The following types are available.
<ul>
<li>blog</li>
<li>category</li>
<li>content_page</li>
<li>variation</li>
<li>ticket</li>
<li>board</li>
</ul>
|===


[source%nowrap, php]
----

public getTagsByRelationship($relationshipType, $value, $isUUID = false):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$relationshipType`
|link:http://php.net/string[string^]
a|The relationship type

a|`$value`
|
a|The relationship value (string if UUID, otherwise int)

a|`$isUUID`
|link:http://php.net/bool[bool^]
a|Indicates whether the value is a UUID5 or not.
|===


[source%nowrap, php]
----

public listTags($with = []):Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Returns all tags.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$with`
|link:http://php.net/array[array^]
a|An array with child instances to be loaded
|===


[source%nowrap, php]
----

public createTag($data):Plenty\Modules\Tag\Models\Tag

----




====== *Return type:*        xref:Tag.adoc#tag_models_tag[`Tag`]


Creates a new tag.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The data as associative array
|===


[source%nowrap, php]
----

public createBulk($data):array

----







Creates up to 50 new tags.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The data as associative array
|===


[source%nowrap, php]
----

public updateBulk($data):array

----







Updates up to 50 tags.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The data as associative array
|===


[source%nowrap, php]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----







Clears the filter array.

[[tag_tag_models]]
===  Models
[[tag_models_tag]]
==== Tag

The Tag model



===== Namespace

`Plenty\Modules\Tag\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The tag ID
|tagName
    |link:http://php.net/string[string^]
    a|The name of the tag
|color
    |link:http://php.net/string[string^]
    a|The color for the tag
|availabilities
    |link:http://php.net/array[array^]
    a|The availabilities of the tag.
|names
    |link:http://php.net/array[array^]
    a|The names of the tag.
|relationships
    |link:http://php.net/array[array^]
    a|The relationships of the tag.
|clients
    |link:http://php.net/array[array^]
    a|The clients of the tag.
|updatedAt
    |link:http://php.net/string[string^]
    a|The updated at timestamp of the tag.
|createdAt
    |link:http://php.net/string[string^]
    a|The created at timestamp of the tag.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[tag_models_tagavailability]]
==== TagAvailability

The tag availability model.



===== Namespace

`Plenty\Modules\Tag\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|tagId
    |link:http://php.net/int[int^]
    a|The Tag ID of the tag
|tagType
    |link:http://php.net/string[string^]
    a|The type of the tag. The following types are available.
<ul>
<li>blog</li>
<li>category</li>
<li>content_page</li>
<li>variation</li>
<li>ticket</li>
<li>board</li>
<li>order</li>
</ul>
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[tag_models_tagclient]]
==== TagClient

The tag client model.



===== Namespace

`Plenty\Modules\Tag\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The id of the relation
|tagId
    |link:http://php.net/int[int^]
    a|The Tag ID of the tag
|plentyId
    |link:http://php.net/int[int^]
    a|The PlentyId of the client
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[tag_models_tagname]]
==== TagName

The tag name model.



===== Namespace

`Plenty\Modules\Tag\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The name ID of the tag
|tagId
    |link:http://php.net/int[int^]
    a|The tag ID
|tagLang
    |link:http://php.net/string[string^]
    a|The lang of the tag name.
|tagName
    |link:http://php.net/string[string^]
    a|The name of the tag.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[tag_models_tagrelationship]]
==== TagRelationship

The tag relationship model.



===== Namespace

`Plenty\Modules\Tag\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|tagId
    |link:http://php.net/int[int^]
    a|The ID of the tag
|tagType
    |link:http://php.net/string[string^]
    a|The type of tag.
|relationshipValue
    |link:http://php.net/int[int^]
    a|The ID of the data record for which a tag relationship is created
|relationshipUUID5
    |link:http://php.net/string[string^]
    a|The ID of the data record for which a tag relationship is created. For models with uuid5 as primary key
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.

