:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[ticket_ticket]]
== Ticket

[[ticket_ticket_contracts]]
===  Contracts
[[ticket_contracts_ticketmessagerepositorycontract]]
==== TicketMessageRepositoryContract

The TicketMessageRepositoryContract is the interface for the ticket message repository. This interface allows to get one particular ticket message, list all ticket messages and list public and internal ticket messages.



===== Namespace

`Plenty\Modules\Ticket\Contracts`






===== Methods

[source%nowrap, php]
----

public get($ticketMessageId):Plenty\Modules\Ticket\Models\TicketMessage

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticketmessage[`TicketMessage`]


Gets the ticket message by the given ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ticketMessageId`
|link:http://php.net/int[int^]
a|The ID of the ticket message
|===


[source%nowrap, php]
----

public list($ticketId):void

----







Lists all ticket messages of a ticket.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ticketId`
|link:http://php.net/int[int^]
a|The ID of the ticket
|===


[source%nowrap, php]
----

public listInternal($ticketId):void

----







Lists all internal ticket messages of a ticket.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ticketId`
|link:http://php.net/int[int^]
a|The ticket ID.
|===


[source%nowrap, php]
----

public listPublic($ticketId):void

----







Lists all public ticket messages of a ticket

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ticketId`
|link:http://php.net/int[int^]
a|The ID of the ticket
|===



[[ticket_contracts_ticketrepositorycontract]]
==== TicketRepositoryContract

The TicketRepositoryContract is the interface for the ticket repository. This interface allows to list tickets by filters.



===== Namespace

`Plenty\Modules\Ticket\Contracts`






===== Methods

[source%nowrap, php]
----

public createTicket($data):Plenty\Modules\Ticket\Models\Ticket

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticket[`Ticket`]


Creates a new ticket.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket data as associative array
|===


[source%nowrap, php]
----

public searchTickets($filter, $page = 1, $itemsPerPage = 50):array

----







List tickets by filter options.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filter`
|link:http://php.net/array[array^]
a|The filter

a|`$page`
|link:http://php.net/int[int^]
a|The page to get. The default page that will be returned is page 1.

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|The number of tickets to be displayed per page. The default number of tickets per page is 50.
|===


[source%nowrap, php]
----

public deleteTicket($ticketId):void

----







Deletes a ticket by the ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ticketId`
|link:http://php.net/int[int^]
a|The ID of the ticket
|===


[source%nowrap, php]
----

public createMessage($data, $ticketId):Plenty\Modules\Ticket\Models\TicketMessage

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticketmessage[`TicketMessage`]


Creates a message for a ticket.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The message data as associative array

a|`$ticketId`
|link:http://php.net/int[int^]
a|The ID of the ticket
|===


[source%nowrap, php]
----

public updateTicket($data, $ticketId):Plenty\Modules\Ticket\Models\Ticket

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticket[`Ticket`]


Updates an existing ticket with given data.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The updating data as associative array

a|`$ticketId`
|link:http://php.net/int[int^]
a|The ID of the ticket
|===


[source%nowrap, php]
----

public findById($ticketId, $with = []):Plenty\Modules\Ticket\Models\Ticket

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticket[`Ticket`]


Gets a ticket by the ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$ticketId`
|link:http://php.net/int[int^]
a|The ID of the ticket

a|`$with`
|link:http://php.net/array[array^]
a|The relations to be loaded with the ticket. Possible values are 'order' and 'contact'.
|===


[source%nowrap, php]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.


[[ticket_contracts_ticketrolenamerepositorycontract]]
==== TicketRoleNameRepositoryContract

The TicketRoleNameRepositoryContract is the interface for the ticket role name repository. This interface allows to update, create and list ticket role names.



===== Namespace

`Plenty\Modules\Ticket\Contracts`






===== Methods

[source%nowrap, php]
----

public update($data, $ticketRoleNameId):Plenty\Modules\Ticket\Models\TicketRoleName

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticketrolename[`TicketRoleName`]


Updates an existing ticket role name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket role name data as associative array

a|`$ticketRoleNameId`
|link:http://php.net/int[int^]
a|The ID of the ticket role name
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\Ticket\Models\TicketRoleName

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticketrolename[`TicketRoleName`]


Creates a ticket role name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket role name data as associative array
|===


[source%nowrap, php]
----

public findByName($name, $lang):array

----







Lists the ticket roles by the name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The name of the ticket role

a|`$lang`
|link:http://php.net/string[string^]
a|The language of the ticket role
|===


[source%nowrap, php]
----

public findByLang($lang):array

----







Lists the ticket roles by the language.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|The language of the ticket role
|===



[[ticket_contracts_ticketrolerepositorycontract]]
==== TicketRoleRepositoryContract

The TicketRoleRepositoryContract is the interface for the ticket role repository. This interface allows to update and create ticket roles.



===== Namespace

`Plenty\Modules\Ticket\Contracts`






===== Methods

[source%nowrap, php]
----

public update($data, $ticketRoleId):Plenty\Modules\Ticket\Models\TicketRole

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticketrole[`TicketRole`]


Update an existing ticket role.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket role data as associative array

a|`$ticketRoleId`
|link:http://php.net/int[int^]
a|The ID of the ticket role
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\Ticket\Models\TicketRole

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticketrole[`TicketRole`]


Creates a ticket role.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket role data as associative array
|===



[[ticket_contracts_ticketstatusnamerepositorycontract]]
==== TicketStatusNameRepositoryContract

The TicketStatusNameRepositoryContract is the interface for the ticket status names. This interface allows to update, create and list ticket status names.



===== Namespace

`Plenty\Modules\Ticket\Contracts`






===== Methods

[source%nowrap, php]
----

public update($data, $ticketStatusNameId):Plenty\Modules\Ticket\Models\TicketStatusName

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticketstatusname[`TicketStatusName`]


Updates the ticket status name by the given ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket status name data as associative array

a|`$ticketStatusNameId`
|link:http://php.net/int[int^]
a|The ID of the ticket status name
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\Ticket\Models\TicketStatusName

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticketstatusname[`TicketStatusName`]


Creates a ticket status name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket status name data as associative array
|===


[source%nowrap, php]
----

public findByName($name, $lang):array

----







Gets the ticket status name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The name of the ticket status

a|`$lang`
|link:http://php.net/string[string^]
a|The language of the ticket status name
|===


[source%nowrap, php]
----

public statusNameList($lang):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|The language of the ticket status name
|===


[source%nowrap, php]
----

public statusNameListWithTypeId($lang):array

----







Lists the ticket status names with type ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|The language of the ticket status name
|===



[[ticket_contracts_ticketstatusrepositorycontract]]
==== TicketStatusRepositoryContract

The TicketStatusRepositoryContract is the interface for the ticket status repository. This interface allows to update, create and list ticket statuses.



===== Namespace

`Plenty\Modules\Ticket\Contracts`






===== Methods

[source%nowrap, php]
----

public update($data, $ticketStatusId):Plenty\Modules\Ticket\Models\TicketStatus

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticketstatus[`TicketStatus`]


Updates an existing ticket status.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket status data as associative array

a|`$ticketStatusId`
|link:http://php.net/int[int^]
a|The ID of the ticket status
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\Ticket\Models\TicketStatus

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_ticketstatus[`TicketStatus`]


Creates a ticket status.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket status data as associative array
|===


[source%nowrap, php]
----

public findByTypeId($typeId):array

----







Lists the ticket statuses by the type ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$typeId`
|link:http://php.net/int[int^]
a|The ID of the type
|===



[[ticket_contracts_tickettypenamerepositorycontract]]
==== TicketTypeNameRepositoryContract

The TicketTypeNameRepositoryContract is the interface for the ticket type name repository. This interface allows to update, create and list ticket type names.



===== Namespace

`Plenty\Modules\Ticket\Contracts`






===== Methods

[source%nowrap, php]
----

public update($data, $ticketTypeNameId):Plenty\Modules\Ticket\Models\TicketTypeName

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_tickettypename[`TicketTypeName`]


Updates an existing ticket type name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket type name data as associative array

a|`$ticketTypeNameId`
|link:http://php.net/int[int^]
a|The ID of the ticket type name
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\Ticket\Models\TicketTypeName

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_tickettypename[`TicketTypeName`]


Creates a ticket type name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket type name data as associative array
|===


[source%nowrap, php]
----

public findByName($name, $lang):array

----







Lists the ticket types by the name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$name`
|link:http://php.net/string[string^]
a|The name of the ticket type

a|`$lang`
|link:http://php.net/string[string^]
a|The language of the ticket type
|===


[source%nowrap, php]
----

public typeNameList($lang):array

----







Lists the ticket types by the language.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|The language of the ticket type
|===



[[ticket_contracts_tickettyperepositorycontract]]
==== TicketTypeRepositoryContract

The TicketTypeRepositoryContract is the interface for the ticket type repository. This interface allows to update and create ticket types.



===== Namespace

`Plenty\Modules\Ticket\Contracts`






===== Methods

[source%nowrap, php]
----

public update($data, $ticketTypeId):Plenty\Modules\Ticket\Models\TicketType

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_tickettype[`TicketType`]


Updates the ticket type by the given ID.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket type data as associative array

a|`$ticketTypeId`
|link:http://php.net/int[int^]
a|The ID of the ticket type
|===


[source%nowrap, php]
----

public create($data):Plenty\Modules\Ticket\Models\TicketType

----




====== *Return type:*        xref:Ticket.adoc#ticket_models_tickettype[`TicketType`]


Creates a ticket type.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The ticket type data as associative array
|===


[[ticket_ticket_models]]
===  Models
[[ticket_models_ticket]]
==== Ticket

The ticket model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the ticket
|typeId
    |link:http://php.net/int[int^]
    a|The type ID of the ticket
|priorityId
    |link:http://php.net/int[int^]
    a|The priority ID of the ticket
|parentTicketId
    |link:http://php.net/int[int^]
    a|The ID of the parent ticket
|statusId
    |link:http://php.net/int[int^]
    a|The status ID of the ticket
|confidential
    |link:http://php.net/array[array^]
    a|The confidential value. Displays 1 if the ticket is confidential. Displays 0 if the ticket is not confidential.
|contactId
    |link:http://php.net/int[int^]
    a|The ID of the contact that is linked with the ticket
|orderId
    |link:http://php.net/int[int^]
    a|The ID of the order linked with the ticket
|createdAt
    |link:http://php.net/string[string^]
    a|The time the ticket was created as unix timestamp or carbon object
|updatedAt
    |link:http://php.net/string[string^]
    a|The time the ticket was last updated as unix timestamp or carbon object
|contactLastUpdateAt
    |link:http://php.net/string[string^]
    a|The time the contact was last updated
|deadlineAt
    |link:http://php.net/string[string^]
    a|The date of the ticket deadline
|finishedAt
    |link:http://php.net/string[string^]
    a|The date the ticket is solved and displays 100 percent in the progress bar
|title
    |link:http://php.net/string[string^]
    a|The title of the ticket
|progress
    |link:http://php.net/int[int^]
    a|The progress of the ticket in percent
|plentyId
    |link:http://php.net/int[int^]
    a|The ID of the client (store)
|source
    |link:http://php.net/array[array^]
    a|The source of the ticket. Possible values are 'frontend', 'backend', 'ebay' and 'email'.
|documentsCount
    |link:http://php.net/int[int^]
    a|The number of documents that are attached to the ticket
|hasDocuments
    |link:http://php.net/int[int^]
    a|Displays 1 if the ticket has one or more documents. Displays 0 if the ticket has no document.
|childrenCount
    |link:http://php.net/int[int^]
    a|The number of child tickets
|resubmissionAt
    |link:http://php.net/string[string^]
    a|The date the ticket should be resubmitted
|parseData
    |link:http://php.net/string[string^]
    a|The ParseData from the ticket
|contact
    |        xref:Account.adoc#account_models_contact[`Contact`]
    a|The contact instance linked with the ticket
|order
    |        xref:Order.adoc#order_models_order[`Order`]
    a|The order instance linked with the ticket
|owners
    |link:http://php.net/array[array^]
    a|The owners of the ticket. It is a combination of the user ID and the role ID.
|messages
    |link:http://php.net/array[array^]
    a|The messages of the ticket
|documents
    |link:http://php.net/array[array^]
    a|The docuemts of the ticket
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketdocument]]
==== TicketDocument

The ticket document model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the ticket document
|ticketId
    |link:http://php.net/int[int^]
    a|TheID of the ticket
|userId
    |link:http://php.net/int[int^]
    a|The ID of the user
|type
    |link:http://php.net/string[string^]
    a|The type the document
|name
    |link:http://php.net/string[string^]
    a|The name (path) of the document storage location
|internal
    |link:http://php.net/int[int^]
    a|/TODO what is this for?
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketmessage]]
==== TicketMessage

The ticket message model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the message
|ticketId
    |link:http://php.net/int[int^]
    a|The ticket ID the message belongs to
|userId
    |link:http://php.net/int[int^]
    a|The user of the message
|createdAt
    |link:http://php.net/string[string^]
    a|The time the ticket message was created as unix timestamp or carbon object
|text
    |link:http://php.net/string[string^]
    a|The content of the message
|type
    |link:http://php.net/array[array^]
    a|The type of the message. Two types are available:
<ul>
<li>message (visible for the customer)</li>
<li>comment (not visible for the customer)</li>
</ul>
|source
    |link:http://php.net/array[array^]
    a|The origin of the message. The following sources are available by default and cannot be deleted.
<ul>
<li>backend</li>
<li>frontend</li>
<li>ebay</li>
<li>email</li>
</ul>
|topicId
    |link:http://php.net/int[int^]
    a|The ID of the topic the message is assigned to
|ticket
    |        xref:Ticket.adoc#ticket_models_ticket[`Ticket`]
    a|The corresponding ticket instance.
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketmessagetopic]]
==== TicketMessageTopic

The ticket message topic model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The id of the message
|position
    |link:http://php.net/int[int^]
    a|The position of the topic
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketmessagetopicname]]
==== TicketMessageTopicName

The ticket message topic name model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the message
|topicId
    |link:http://php.net/int[int^]
    a|The ID of the topic
|lang
    |link:http://php.net/string[string^]
    a|The language of the topic
|name
    |link:http://php.net/string[string^]
    a|The name of the topic
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketowner]]
==== TicketOwner

The ticket owner model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|ticketId
    |link:http://php.net/int[int^]
    a|The ID of the ticket
|userId
    |link:http://php.net/int[int^]
    a|The user ID of the owner
|roleId
    |link:http://php.net/int[int^]
    a|The role ID of the owner
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketrole]]
==== TicketRole

The ticket role model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the role
|position
    |link:http://php.net/int[int^]
    a|The position of the role
|names
    |link:http://php.net/array[array^]
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketrolename]]
==== TicketRoleName

The ticket role name model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the role name
|roleId
    |link:http://php.net/int[int^]
    a|The ID of the role
|lang
    |link:http://php.net/int[int^]
    a|The language of the role
|name
    |link:http://php.net/string[string^]
    a|The name of the role
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketstatus]]
==== TicketStatus

The ticket status model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the status
|typeId
    |link:http://php.net/int[int^]
    a|The type ID of the status
|position
    |link:http://php.net/int[int^]
    a|The position of the status
|statusGroupId
    |link:http://php.net/int[int^]
    a|The status group ID of the status
|names
    |link:http://php.net/array[array^]
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketstatusgroup]]
==== TicketStatusGroup

The ticket status group model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the status group
|position
    |link:http://php.net/int[int^]
    a|The position of the status group
|color
    |link:http://php.net/string[string^]
    a|The color of the status group
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketstatusgroupname]]
==== TicketStatusGroupName

The ticket status group name model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the ticket
|lang
    |link:http://php.net/int[int^]
    a|The language of the status group
|name
    |link:http://php.net/string[string^]
    a|The name of the status group
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_ticketstatusname]]
==== TicketStatusName

The ticket status name model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the status name
|statusId
    |link:http://php.net/int[int^]
    a|The status ID of the status name
|lang
    |link:http://php.net/string[string^]
    a|The language of the status name
|name
    |link:http://php.net/string[string^]
    a|The name of the status
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_tickettype]]
==== TicketType

The ticket type model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the role
|position
    |link:http://php.net/int[int^]
    a|The position of the role
|names
    |link:http://php.net/array[array^]
    a|
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.


[[ticket_models_tickettypename]]
==== TicketTypeName

The ticket type name model.



===== Namespace

`Plenty\Modules\Ticket\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the role name
|typeId
    |link:http://php.net/int[int^]
    a|The type id of the role name
|lang
    |link:http://php.net/string[string^]
    a|The language of the role name
|name
    |link:http://php.net/string[string^]
    a|The name of the role
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----







Returns this model as an array.

