:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[warehouse_warehouse]]
== Warehouse

[[warehouse_warehouse_contracts]]
===  Contracts
[[warehouse_contracts_warehouselocationdimensionrepositorycontract]]
==== WarehouseLocationDimensionRepositoryContract

Get, create, update and delete warehouse location dimensions



===== Namespace

`Plenty\Modules\Warehouse\Contracts`






===== Methods

[source%nowrap, php]
[#getwarehouselocationdimension]
----

public getWarehouseLocationDimension($warehouseLocationDimension, $with = []):Plenty\Modules\Warehouse\Models\WarehouseLocationDimension

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationdimension[`WarehouseLocationDimension`]


Get a warehouse location dimension

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationDimension`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#listwarehouselocationdimension]
----

public listWarehouseLocationDimension($warehouseId):Plenty\Modules\Warehouse\Models\WarehouseLocationDimension

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationdimension[`WarehouseLocationDimension`]


Get all warehouse location dimensions

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#createmultiplewarehouselocationdimension]
----

public createMultipleWarehouseLocationDimension($data):array

----







Create multiple warehouse location dimensions

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#createwarehouselocationdimension]
----

public createWarehouseLocationDimension($data):Plenty\Modules\Warehouse\Models\WarehouseLocationDimension

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationdimension[`WarehouseLocationDimension`]


Create a warehouse location dimension

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updatewarehouselocationdimension]
----

public updateWarehouseLocationDimension($warehouseLocationDimension, $data):Plenty\Modules\Warehouse\Models\WarehouseLocationDimension

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationdimension[`WarehouseLocationDimension`]


Update a warehouse location dimension

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationDimension`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deletewarehouselocationdimension]
----

public deleteWarehouseLocationDimension($warehouseLocationDimension):void

----







Delete a warehouse location dimension

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationDimension`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[warehouse_contracts_warehouselocationinventoryrepositorycontract]]
==== WarehouseLocationInventoryRepositoryContract

Get, create, update and delete warehouse locations



===== Namespace

`Plenty\Modules\Warehouse\Contracts`






===== Methods

[source%nowrap, php]
[#getwarehouselocationinventory]
----

public getWarehouseLocationInventory($warehouseLocationInventory):Plenty\Modules\Warehouse\Models\WarehouseLocationInventory

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationinventory[`WarehouseLocationInventory`]


Get a warehouse location inventory

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationInventory`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getwarehouselocationinventorylist]
----

public getWarehouseLocationInventoryList($page = 1, $itemsPerPage = 50, $paginate = 1, $filters = [], $warehouseLocationId = null, $with = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Get a warehouse location inventory

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|

a|`$paginate`
|link:http://php.net/int[int^]
a|

a|`$filters`
|link:http://php.net/array[array^]
a|

a|`$warehouseLocationId`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#createwarehouselocationinventory]
----

public createWarehouseLocationInventory($data):Plenty\Modules\Warehouse\Models\WarehouseLocationInventory

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationinventory[`WarehouseLocationInventory`]


Create a warehouse location inventory

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[warehouse_contracts_warehouselocationlevelrepositorycontract]]
==== WarehouseLocationLevelRepositoryContract

Get, create, update and delete warehouse location levels



===== Namespace

`Plenty\Modules\Warehouse\Contracts`






===== Methods

[source%nowrap, php]
[#getwarehouselocationlevel]
----

public getWarehouseLocationLevel($warehouseLocationLevel):Plenty\Modules\Warehouse\Models\WarehouseLocationLevel

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]


Get a warehouse location level

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationLevel`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getwarehouselocationlevelbyname]
----

public getWarehouseLocationLevelByName($warehouseLocationLevelName, $dimensionId, $parentId):Plenty\Modules\Warehouse\Models\WarehouseLocationLevel

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]


Get a warehouse location level

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationLevelName`
|link:http://php.net/string[string^]
a|

a|`$dimensionId`
|link:http://php.net/int[int^]
a|

a|`$parentId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getwarehouselocationlevelonlybyname]
----

public getWarehouseLocationLevelOnlyByName($warehouseLocationLevelName):Plenty\Modules\Warehouse\Models\WarehouseLocationLevel

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]


Get a warehouse location level only by name.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationLevelName`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#listwarehouselocationlevels]
----

public listWarehouseLocationLevels($filters = [], $warehouseId = null):array

----







Get a list of warehouse location levels

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|

a|`$warehouseId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#createwarehouselocationlevel]
----

public createWarehouseLocationLevel($data, $apiMode = false):Plenty\Modules\Warehouse\Models\WarehouseLocationLevel

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]


Create a warehouse location level

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data

a|`$apiMode`
|link:http://php.net/bool[bool^]
a|If the location is created using a route
|===


[source%nowrap, php]
[#updatewarehouselocationlevel]
----

public updateWarehouseLocationLevel($warehouseLocationLevel, $data):Plenty\Modules\Warehouse\Models\WarehouseLocationLevel

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]


Update a warehouse location level

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationLevel`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#deletewarehouselocationlevel]
----

public deleteWarehouseLocationLevel($warehouseLocationLevel):void

----







Delete a warehouse location level

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationLevel`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getwarehousestructure]
----

public getWarehouseStructure($warehouseId, $data = []):void

----







Get a warehouse structure.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseId`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#movewarehouselocationlevelposition]
----

public moveWarehouseLocationLevelPosition($data):void

----







Move a warehouse location level position

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#getwarehousestructuremoving]
----

public getWarehouseStructureMoving($warehouseId, $data):void

----







Get a warehouse structure moving.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseId`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.


[[warehouse_contracts_warehouselocationrepositorycontract]]
==== WarehouseLocationRepositoryContract

Get, create, update and delete warehouse locations



===== Namespace

`Plenty\Modules\Warehouse\Contracts`






===== Methods

[source%nowrap, php]
[#getwarehouselocation]
----

public getWarehouseLocation($warehouseLocation, $with = []):Plenty\Modules\Warehouse\Models\WarehouseLocation

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocation[`WarehouseLocation`]


Get a warehouse location

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocation`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#listwarehouselocations]
----

public listWarehouseLocations($page = 1, $itemsPerPage = 50, $paginate = 1, $filters = [], $warehouseId = null, $with = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Get all warehouse locations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|

a|`$paginate`
|link:http://php.net/int[int^]
a|

a|`$filters`
|link:http://php.net/array[array^]
a|

a|`$warehouseId`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#listwarehouselocationsbylevelid]
----

public listWarehouseLocationsByLevelId($warehouseId, $levelId):void

----







List warehouse locations by levelId

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseId`
|link:http://php.net/int[int^]
a|

a|`$levelId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getwarehouselocationbylabel]
----

public getWarehouseLocationByLabel($label):Plenty\Modules\Warehouse\Models\WarehouseLocation

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocation[`WarehouseLocation`]


Get first warehouse location matching the given label
Gets the first warehouse location matching the given label. The label must be specified.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$label`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#createwarehouselocation]
----

public createWarehouseLocation($data):Plenty\Modules\Warehouse\Models\WarehouseLocation

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocation[`WarehouseLocation`]


Create a warehouse location

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#updatewarehouselocation]
----

public updateWarehouseLocation($warehouseLocation, $data):Plenty\Modules\Warehouse\Models\WarehouseLocation

----




====== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocation[`WarehouseLocation`]


Update a warehouse location

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocation`
|link:http://php.net/int[int^]
a|

a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#updatestoragelocations]
----

public updateStorageLocations($data):void

----







Updates several Storage Locations in a single DB Transaction
with the data provided

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|
a|
|===


[source%nowrap, php]
[#deletewarehouselocation]
----

public deleteWarehouseLocation($warehouseLocation):void

----







Delete a warehouse location

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocation`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#deletemultiplewarehouselocations]
----

public deleteMultipleWarehouseLocations($warehouseLocationIds):void

----







Delete multiple warehouse locations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationIds`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#executegroupfunction]
----

public executeGroupFunction($data):array

----







Edit the purpose and status for a group of storage locations

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#generatewarehouselocationlabel]
----

public generateWarehouseLocationLabel($warehouseId, $warehouseLocationIds):array

----







Generate warehouse location labels

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseId`
|link:http://php.net/int[int^]
a|

a|`$warehouseLocationIds`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#movewarehouselocationposition]
----

public moveWarehouseLocationPosition($data):void

----







Move a warehouse location position

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$data`
|link:http://php.net/array[array^]
a|The request data
|===


[source%nowrap, php]
[#listwarehouselocationstock]
----

public listWarehouseLocationStock($page = 1, $itemsPerPage = 50, $paginate = 1, $filters = [], $warehouseLocationId = null, $with = []):Plenty\Repositories\Models\PaginatedResult

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Get all warehouse locations stock

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|

a|`$paginate`
|link:http://php.net/int[int^]
a|

a|`$filters`
|link:http://php.net/array[array^]
a|

a|`$warehouseLocationId`
|link:http://php.net/int[int^]
a|

a|`$with`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getwarehouselocationavailability]
----

public getWarehouseLocationAvailability($warehouseLocationId):array

----







Get availability for storage location

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$warehouseLocationId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#clearcriteria]
----

public clearCriteria():void

----







Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
[#applycriteriafromfilters]
----

public applyCriteriaFromFilters():void

----







Applies criteria classes to the current repository.

[source%nowrap, php]
[#setfilters]
----

public setFilters($filters = []):void

----







Sets the filter array.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filters`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfilters]
----

public getFilters():void

----







Returns the filter array.

[source%nowrap, php]
[#getconditions]
----

public getConditions():void

----







Returns a collection of parsed filters as Condition object

[source%nowrap, php]
[#clearfilters]
----

public clearFilters():void

----







Clears the filter array.

[[warehouse_warehouse_models]]
===  Models
[[warehouse_models_warehouselocation]]
==== WarehouseLocation

The warehouse location model.



===== Namespace

`Plenty\Modules\Warehouse\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the warehouse location
|levelId
    |link:http://php.net/int[int^]
    a|The level ID of the warehouse location
|label
    |link:http://php.net/string[string^]
    a|The label of the warehouse location
|purposeKey
    |link:http://php.net/string[string^]
    a|The purpose key of the warehouse location
|statusKey
    |link:http://php.net/string[string^]
    a|The status key of the warehouse location
|position
    |link:http://php.net/int[int^]
    a|The position of the warehouse location
|fullLabel
    |link:http://php.net/string[string^]
    a|The label with level path name
|type
    |link:http://php.net/string[string^]
    a|The type of the warehouse location (array values: 'small','medium','large','europallet')
|notes
    |link:http://php.net/string[string^]
    a|The notes of the warehouse location
|createdAt
    |
    a|The date when the warehouse location was created
|updatedAt
    |
    a|The date when the warehouse location was last updated
|warehouseLocationLevel
    |        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]
    a|The level from warehouse location.
|lastFinishedInventory
    |        xref:Warehouse.adoc#warehouse_models_warehouselocationinventory[`WarehouseLocationInventory`]
    a|The last finished warehouse location inventory.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[warehouse_models_warehouselocationdimension]]
==== WarehouseLocationDimension

The warehouse location dimension model.



===== Namespace

`Plenty\Modules\Warehouse\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the warehouse location dimension
|parentId
    |link:http://php.net/int[int^]
    a|The parent ID of the warehouse location dimension
|warehouseId
    |link:http://php.net/int[int^]
    a|The warehouse ID of the warehouse location dimension
|level
    |link:http://php.net/int[int^]
    a|The level of the warehouse location dimension
|name
    |link:http://php.net/string[string^]
    a|The name of the warehouse location dimension
|shortcut
    |link:http://php.net/string[string^]
    a|The shortcut of the warehouse location dimension
|separator
    |link:http://php.net/string[string^]
    a|The separator of the warehouse location dimension
|displayInName
    |link:http://php.net/int[int^]
    a|If true, the dimension prefix will be shown in the storage location name
|isActiveForPickupPath
    |link:http://php.net/int[int^]
    a|Active flag for pickup path of the warehouse location dimension
|createdAt
    |
    a|Date when the warehouse location dimension was created
|updatedAt
    |
    a|Date when the warehouse location dimension was last updated
|warehouseLocationLevel
    |link:http://php.net/array[array^]
    a|The linked warehouse location level
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[warehouse_models_warehouselocationinventory]]
==== WarehouseLocationInventory

The warehouse location inventory model.



===== Namespace

`Plenty\Modules\Warehouse\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the warehouse location
|userId
    |link:http://php.net/int[int^]
    a|The user ID of the warehouse location
|user_id
    |link:http://php.net/int[int^]
    a|deprecated - use userID instead
|status
    |link:http://php.net/int[int^]
    a|The status of the warehouse location inventory
|warehouseLocationId
    |link:http://php.net/int[int^]
    a|The  warehouse location ID
|warehouse_location
    |link:http://php.net/int[int^]
    a|deprecated - use WarehouseLocationId
|createdAt
    |
    a|The date when the warehouse location inventory was created
|updatedAt
    |
    a|The date when the warehouse location inventory was last updated
|warehouseLocation
    |        xref:Warehouse.adoc#warehouse_models_warehouselocation[`WarehouseLocation`]
    a|The warehouse location.
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[warehouse_models_warehouselocationlevel]]
==== WarehouseLocationLevel

The warehouse location level model.



===== Namespace

`Plenty\Modules\Warehouse\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|id
    |link:http://php.net/int[int^]
    a|The ID of the warehouse location level
|parentId
    |link:http://php.net/int[int^]
    a|The parent ID of the warehouse location level
|dimensionId
    |link:http://php.net/int[int^]
    a|The warehouse location dimension id of the warehouse location level
|position
    |link:http://php.net/int[int^]
    a|The position of the warehouse location level
|name
    |link:http://php.net/string[string^]
    a|The name of the warehouse location level
|type
    |link:http://php.net/string[string^]
    a|The type of the warehouse location ['small','medium','large','europallet']
|pathName
    |link:http://php.net/string[string^]
    a|The complete path name from the level
|createdAt
    |
    a|The date when the warehouse location level was created
|updatedAt
    |
    a|The date when the warehouse location level was last updated
|parent
    |        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]
    a|The parent warehouse location level if existing
|children
    |link:http://php.net/array[array^]
    a|The children warehouse location level if existing
|warehouseLocation
    |link:http://php.net/array[array^]
    a|The linked warehouse location
|warehouseLocationDimension
    |        xref:Warehouse.adoc#warehouse_models_warehouselocationdimension[`WarehouseLocationDimension`]
    a|The linked warehouse location dimension
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

