:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[warehouse_warehouse]]
= Warehouse

[[warehouse_warehouse_contracts]]
== Contracts
[[warehouse_contracts_warehouselocationdimensionrepositorycontract]]
=== WarehouseLocationDimensionRepositoryContract

Get, create, update and delete warehouse location dimensions



==== Namespace

`Plenty\Modules\Warehouse\Contracts`






==== Methods

[source%nowrap, php]
----

public getWarehouseLocationDimension($warehouseLocationDimension, $with = []):Plenty\Modules\Warehouse\Models\WarehouseLocationDimension

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationdimension[`WarehouseLocationDimension`]


Get a warehouse location dimension

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseLocationDimension`
a|

|link:http://php.net/array[array^]
a|`$with`
a|
|===


[source%nowrap, php]
----

public listWarehouseLocationDimension($warehouseId):Plenty\Modules\Warehouse\Models\WarehouseLocationDimension

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationdimension[`WarehouseLocationDimension`]


Get all warehouse location dimensions

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|
|===


[source%nowrap, php]
----

public createMultipleWarehouseLocationDimension($data):array

----

    





Create multiple warehouse location dimensions

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public createWarehouseLocationDimension($data):Plenty\Modules\Warehouse\Models\WarehouseLocationDimension

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationdimension[`WarehouseLocationDimension`]


Create a warehouse location dimension

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public updateWarehouseLocationDimension($warehouseLocationDimension, $data):Plenty\Modules\Warehouse\Models\WarehouseLocationDimension

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationdimension[`WarehouseLocationDimension`]


Update a warehouse location dimension

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseLocationDimension`
a|

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public deleteWarehouseLocationDimension($warehouseLocationDimension):void

----

    





Delete a warehouse location dimension

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseLocationDimension`
a|
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[warehouse_contracts_warehouselocationlevelrepositorycontract]]
=== WarehouseLocationLevelRepositoryContract

Get, create, update and delete warehouse location levels



==== Namespace

`Plenty\Modules\Warehouse\Contracts`






==== Methods

[source%nowrap, php]
----

public getWarehouseLocationLevel($warehouseLocationLevel):Plenty\Modules\Warehouse\Models\WarehouseLocationLevel

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]


Get a warehouse location level

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseLocationLevel`
a|
|===


[source%nowrap, php]
----

public getWarehouseLocationLevelByName($warehouseLocationLevelName, $dimensionId, $parentId):Plenty\Modules\Warehouse\Models\WarehouseLocationLevel

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]


Get a warehouse location level

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$warehouseLocationLevelName`
a|

|link:http://php.net/int[int^]
a|`$dimensionId`
a|

|link:http://php.net/int[int^]
a|`$parentId`
a|
|===


[source%nowrap, php]
----

public getWarehouseLocationLevelOnlyByName($warehouseLocationLevelName):Plenty\Modules\Warehouse\Models\WarehouseLocationLevel

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]


Get a warehouse location level only by name.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$warehouseLocationLevelName`
a|
|===


[source%nowrap, php]
----

public listWarehouseLocationLevels($filters = [], $warehouseId = null):array

----

    





Get a list of warehouse location levels

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|

|link:http://php.net/int[int^]
a|`$warehouseId`
a|
|===


[source%nowrap, php]
----

public createWarehouseLocationLevel($data, $apiMode = false):Plenty\Modules\Warehouse\Models\WarehouseLocationLevel

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]


Create a warehouse location level

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data

|link:http://php.net/bool[bool^]
a|`$apiMode`
a|If the location is created using a route
|===


[source%nowrap, php]
----

public updateWarehouseLocationLevel($warehouseLocationLevel, $data):Plenty\Modules\Warehouse\Models\WarehouseLocationLevel

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]


Update a warehouse location level

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseLocationLevel`
a|

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public deleteWarehouseLocationLevel($warehouseLocationLevel):void

----

    





Delete a warehouse location level

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseLocationLevel`
a|
|===


[source%nowrap, php]
----

public getWarehouseStructure($warehouseId, $data = []):void

----

    





Get a warehouse structure.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public moveWarehouseLocationLevelPosition($data):void

----

    





Move a warehouse location level position

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public getWarehouseStructureMoving($warehouseId, $data):void

----

    





Get a warehouse structure moving.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.


[[warehouse_contracts_warehouselocationrepositorycontract]]
=== WarehouseLocationRepositoryContract

Get, create, update and delete warehouse locations



==== Namespace

`Plenty\Modules\Warehouse\Contracts`






==== Methods

[source%nowrap, php]
----

public getWarehouseLocation($warehouseLocation):Plenty\Modules\Warehouse\Models\WarehouseLocation

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocation[`WarehouseLocation`]


Get a warehouse location

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseLocation`
a|
|===


[source%nowrap, php]
----

public listWarehouseLocations($page = 1, $itemsPerPage = 50, $paginate = 1, $filters = [], $warehouseId = null, $with = []):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Get all warehouse locations

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|

|link:http://php.net/int[int^]
a|`$paginate`
a|

|link:http://php.net/array[array^]
a|`$filters`
a|

|link:http://php.net/int[int^]
a|`$warehouseId`
a|

|link:http://php.net/array[array^]
a|`$with`
a|
|===


[source%nowrap, php]
----

public listWarehouseLocationsByLevelId($warehouseId, $levelId):void

----

    





List warehouse locations by levelId

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|

|link:http://php.net/int[int^]
a|`$levelId`
a|
|===


[source%nowrap, php]
----

public getWarehouseLocationByLabel($label):Plenty\Modules\Warehouse\Models\WarehouseLocation

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocation[`WarehouseLocation`]


Get first warehouse location matching the given label
Gets the first warehouse location matching the given label. The label must be specified.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$label`
a|
|===


[source%nowrap, php]
----

public createWarehouseLocation($data):Plenty\Modules\Warehouse\Models\WarehouseLocation

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocation[`WarehouseLocation`]


Create a warehouse location

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public updateWarehouseLocation($warehouseLocation, $data):Plenty\Modules\Warehouse\Models\WarehouseLocation

----

    


===== *Return type:*        xref:Warehouse.adoc#warehouse_models_warehouselocation[`WarehouseLocation`]


Update a warehouse location

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseLocation`
a|

|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public deleteWarehouseLocation($warehouseLocation):void

----

    





Delete a warehouse location

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseLocation`
a|
|===


[source%nowrap, php]
----

public deleteMultipleWarehouseLocations($warehouseLocationIds):void

----

    





Delete multiple warehouse locations

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$warehouseLocationIds`
a|
|===


[source%nowrap, php]
----

public executeGroupFunction($data):array

----

    





Edit the purpose and status for a group of storage locations

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|
|===


[source%nowrap, php]
----

public generateWarehouseLocationLabel($warehouseId, $warehouseLocationIds):array

----

    





Generate warehouse location labels

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseId`
a|

|link:http://php.net/array[array^]
a|`$warehouseLocationIds`
a|
|===


[source%nowrap, php]
----

public moveWarehouseLocationPosition($data):void

----

    





Move a warehouse location position

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$data`
a|The request data
|===


[source%nowrap, php]
----

public listWarehouseLocationStock($page = 1, $itemsPerPage = 50, $paginate = 1, $filters = [], $warehouseLocationId = null, $with = []):Plenty\Repositories\Models\PaginatedResult

----

    


===== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]


Get all warehouse locations stock

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
a|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
a|

|link:http://php.net/int[int^]
a|`$paginate`
a|

|link:http://php.net/array[array^]
a|`$filters`
a|

|link:http://php.net/int[int^]
a|`$warehouseLocationId`
a|

|link:http://php.net/array[array^]
a|`$with`
a|
|===


[source%nowrap, php]
----

public getWarehouseLocationAvailability($warehouseLocationId):array

----

    





Get availability for storage location

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$warehouseLocationId`
a|
|===


[source%nowrap, php]
----

public clearCriteria():void

----

    





Resets all Criteria filters by creating a new instance of the builder object.

[source%nowrap, php]
----

public applyCriteriaFromFilters():void

----

    





Applies criteria classes to the current repository.

[source%nowrap, php]
----

public setFilters($filters = []):void

----

    





Sets the filter array.

.*Parameters*
[cols="10%,30%,60%"]
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$filters`
a|
|===


[source%nowrap, php]
----

public getFilters():void

----

    





Returns the filter array.

[source%nowrap, php]
----

public getConditions():void

----

    





Returns a collection of parsed filters as Condition object

[source%nowrap, php]
----

public clearFilters():void

----

    





Clears the filter array.

[[warehouse_warehouse_models]]
== Models
[[warehouse_models_warehouselocation]]
=== WarehouseLocation

The warehouse location model.



==== Namespace

`Plenty\Modules\Warehouse\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the warehouse location
|link:http://php.net/int[int^]
    a|levelId
    a|The level ID of the warehouse location
|link:http://php.net/string[string^]
    a|label
    a|The label of the warehouse location
|link:http://php.net/string[string^]
    a|purposeKey
    a|The purpose key of the warehouse location
|link:http://php.net/string[string^]
    a|statusKey
    a|The status key of the warehouse location
|link:http://php.net/int[int^]
    a|position
    a|The position of the warehouse location
|link:http://php.net/string[string^]
    a|fullLabel
    a|The label with level path name
|link:http://php.net/string[string^]
    a|type
    a|The type of the warehouse location (array values: 'small','medium','large','europallet')
|link:http://php.net/string[string^]
    a|notes
    a|The notes of the warehouse location
|
    a|createdAt
    a|The date when the warehouse location was created
|
    a|updatedAt
    a|The date when the warehouse location was last updated
|        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]
    a|warehouseLocationLevel
    a|The level from warehouse location.
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[warehouse_models_warehouselocationdimension]]
=== WarehouseLocationDimension

The warehouse location dimension model.



==== Namespace

`Plenty\Modules\Warehouse\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the warehouse location dimension
|link:http://php.net/int[int^]
    a|parentId
    a|The parent ID of the warehouse location dimension
|link:http://php.net/int[int^]
    a|warehouseId
    a|The warehouse ID of the warehouse location dimension
|link:http://php.net/int[int^]
    a|level
    a|The level of the warehouse location dimension
|link:http://php.net/string[string^]
    a|name
    a|The name of the warehouse location dimension
|link:http://php.net/string[string^]
    a|shortcut
    a|The shortcut of the warehouse location dimension
|link:http://php.net/string[string^]
    a|separator
    a|The separator of the warehouse location dimension
|link:http://php.net/int[int^]
    a|displayInName
    a|If true, the dimension prefix will be shown in the storage location name
|link:http://php.net/int[int^]
    a|isActiveForPickupPath
    a|Active flag for pickup path of the warehouse location dimension
|
    a|createdAt
    a|Date when the warehouse location dimension was created
|
    a|updatedAt
    a|Date when the warehouse location dimension was last updated
|link:http://php.net/array[array^]
    a|warehouseLocationLevel
    a|The linked warehouse location level
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.


[[warehouse_models_warehouselocationlevel]]
=== WarehouseLocationLevel

The warehouse location level model.



==== Namespace

`Plenty\Modules\Warehouse\Models`





.Properties
[cols="10%,30%,60%"]
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    a|id
    a|The ID of the warehouse location level
|link:http://php.net/int[int^]
    a|parentId
    a|The parent ID of the warehouse location level
|link:http://php.net/int[int^]
    a|dimensionId
    a|The warehouse location dimension id of the warehouse location level
|link:http://php.net/int[int^]
    a|position
    a|The position of the warehouse location level
|link:http://php.net/string[string^]
    a|name
    a|The name of the warehouse location level
|link:http://php.net/string[string^]
    a|type
    a|The type of the warehouse location ['small','medium','large','europallet']
|link:http://php.net/string[string^]
    a|pathName
    a|The complete path name from the level
|
    a|createdAt
    a|The date when the warehouse location level was created
|
    a|updatedAt
    a|The date when the warehouse location level was last updated
|        xref:Warehouse.adoc#warehouse_models_warehouselocationlevel[`WarehouseLocationLevel`]
    a|parent
    a|The parent warehouse location level if existing
|link:http://php.net/array[array^]
    a|children
    a|The children warehouse location level if existing
|link:http://php.net/array[array^]
    a|warehouseLocation
    a|The linked warehouse location
|        xref:Warehouse.adoc#warehouse_models_warehouselocationdimension[`WarehouseLocationDimension`]
    a|warehouseLocationDimension
    a|The linked warehouse location dimension
|===


==== Methods

[source%nowrap, php]
----

public toArray()

----

    





Returns this model as an array.

