:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[webshop_consent]]
== Consent

[[webshop_consent_contracts]]
===  Contracts
[[webshop_contracts_consentrepositorycontract]]
==== ConsentRepositoryContract

Repository to register consents and check for users response.



===== Namespace

`Plenty\Modules\Webshop\Consent\Contracts`






===== Methods

[source%nowrap, php]
[#registerconsentgroup]
----

public registerConsentGroup($key, $label, $options = []):void

----







Register a new group of consents.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|Unique identifier of the group

a|`$label`
|link:http://php.net/string[string^]
a|Displayed label of the group

a|`$options`
|
a|Additional options of the group. Available options are:
<ul>
  <li><b>necessary:boolean</b> True if the group is necessary and could not be declined</li>
  <li><b>description:string</b> Description of the group.</li>
  <li><b>position:number</b> The position of the group</li>
</ul>
Alternatively provide a function which returns all options. This will be resolved if registered consent groups are requested.
|===


[source%nowrap, php]
[#registerconsent]
----

public registerConsent($key, $label, $options = []):void

----







Register a new consent.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|Unique identifier of the consent.

a|`$label`
|link:http://php.net/string[string^]
a|Displayed label of the consent.

a|`$options`
|
a|Additional options of the consent. Available options are:
<ul>
    <li><b>necessary:boolean</b> True of the consent is necessary and could not be declined</li>
    <li><b>description:string</b> Description of the consent</li>
    <li><b>provider:string</b> The provider of the cookie</li>
    <li><b>lifespan:string</b> Lifespan of the cookie</li>
    <li><b>policyUrl:string</b> URL to external privacy policy</li>
    <li><b>group:string</b> Identifier of an consent group</li>
    <li><b>position:number</b> The position of the consent in the group</li>
    <li><b>isOptOut:boolean</b> Select the consent by default. The user needs to decline the consent explicitly.</li>
    <li><b>cookieNames:array</b> Names of cookies which will be set. These cookies will not be blocked after the user confirmed the consent.</li>
</ul>
Alternatively provide a function which returns all options. This will be resolved if registered consents are requested.
|===


[source%nowrap, php]
[#getconsentgroups]
----

public getConsentGroups():Illuminate\Support\Collection

----




====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_support_collection[`Collection`]


Get all consent groups including all consents.

[source%nowrap, php]
[#hasresponse]
----

public hasResponse():bool

----







Check if the user has already responded the consents.

[source%nowrap, php]
[#setresponse]
----

public setResponse($key, $isConsented = false):void

----







Set the response for a consent or a group of consents.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The key of the consent group and the consent, e.g. "group.consent"
Use "*" as consent key to check if all entries of a group has a response, e.g. "group.*"

a|`$isConsented`
|link:http://php.net/bool[bool^]
a|True if the user has accepted the consent or the group of consents
|===


[source%nowrap, php]
[#isconsented]
----

public isConsented($key):bool

----







Check if the user has consented.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The key of the consent group and the consent, e.g. "group.consent"
Use "*" as consent key to check if all entries of a group has a response, e.g. "group.*"
|===


[[webshop_contactform]]
== ContactForm

[[webshop_contactform_contracts]]
===  Contracts
[[webshop_contracts_contactformfilerepositorycontract]]
==== ContactFormFileRepositoryContract

Repository to upload files from the online store contact form and retrieve them



===== Namespace

`Plenty\Modules\Webshop\ContactForm\Contracts`






===== Methods

[source%nowrap, php]
[#uploadfiles]
----

public uploadFiles($fileData):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fileData`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#getfile]
----

public getFile($fileName):Plenty\Modules\Cloud\Storage\Models\StorageObject

----




====== *Return type:*        xref:Cloud.adoc#cloud_models_storageobject[`StorageObject`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fileName`
|link:http://php.net/string[string^]
a|
|===


[[webshop_webshop]]
== Webshop

[[webshop_webshop_contracts]]
===  Contracts
[[webshop_contracts_checkoutrepositorycontract]]
==== CheckoutRepositoryContract

Repository to get and set checkout data



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
[#getcurrency]
----

public getCurrency():string

----







Get the currently used currency.

[source%nowrap, php]
[#setcurrency]
----

public setCurrency($currency):void

----







Set the currency.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$currency`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getshippingcountryid]
----

public getShippingCountryId():int

----







Get the id of the current shipping country. Default to the configured country id from the webstore configuration.


[[webshop_contracts_contactrepositorycontract]]
==== ContactRepositoryContract

Repository to get and set contact information for the webshop



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
[#getcontactid]
----

public getContactId():int

----







Get the ID of the logged in contact or 0 for guests

[source%nowrap, php]
[#getcontact]
----

public getContact():Plenty\Modules\Account\Contact\Models\Contact

----




====== *Return type:*        xref:Account.adoc#account_models_contact[`Contact`]


Get the logged in contact

[source%nowrap, php]
[#getcontactclassid]
----

public getContactClassId():int

----







Get the contact class ID of the logged in contact

[source%nowrap, php]
[#getcontactclassdata]
----

public getContactClassData($contactClassId):array

----







Get the contact class data for the provided contact class ID

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$contactClassId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getdefaultcontactclassid]
----

public getDefaultContactClassId():int

----







Get the default contact class ID of the webstore

[source%nowrap, php]
[#shownetprices]
----

public showNetPrices():bool

----







Get Information if net prices should be shown


[[webshop_contracts_giftcardrepositorycontract]]
==== GiftCardRepositoryContract

Repository to get information about gift cards and corresponding order items



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
[#hasgiftcardpdf]
----

public hasGiftCardPdf($orderId, $orderItemId, $campaignCodeOrderId):bool

----







Checks if a gift card document has already been created for this order item

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderId`
|link:http://php.net/int[int^]
a|

a|`$orderItemId`
|link:http://php.net/int[int^]
a|

a|`$campaignCodeOrderId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getgiftcardinformation]
----

public getGiftCardInformation($orderItemId):array

----







Get Information about the gift card

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderItemId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#isreturnable]
----

public isReturnable($orderItemId):bool

----







Return true if its not a gift card or the codes are not redeemed

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderItemId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#getreturnquantity]
----

public getReturnQuantity($orderItemId):int

----







Returnable quantity for giftCard

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderItemId`
|link:http://php.net/int[int^]
a|
|===



[[webshop_contracts_localizationrepositorycontract]]
==== LocalizationRepositoryContract

Repository for webshop localization information



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
[#getlanguage]
----

public getLanguage():string

----







Get the currently used language of the webshop visitor

[source%nowrap, php]
[#getlocale]
----

public getLocale():string

----







Get the current locale

[source%nowrap, php]
[#getlanguagecode]
----

public getLanguageCode($countryCode = null):string

----







Get a ISO language code by given country code.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$countryCode`
|link:http://php.net/string[string^]
a|
|===



[[webshop_contracts_sessionstoragerepositorycontract]]
==== SessionStorageRepositoryContract

Repository for webshop session information



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
[#setsessionvalue]
----

public setSessionValue($key, $value):void

----







Set a value to a given key in the session

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The key from session

a|`$value`
|
a|The value will set to given key
|===


[source%nowrap, php]
[#getsessionvalue]
----

public getSessionValue($key):void

----







Get a value from the session by a given key

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The key to read from the session
|===


[source%nowrap, php]
[#getcustomer]
----

public getCustomer():Plenty\Modules\Frontend\Session\Storage\Models\Customer

----




====== *Return type:*        xref:Frontend.adoc#frontend_models_customer[`Customer`]


Get the customer session model

[source%nowrap, php]
[#getorder]
----

public getOrder():Plenty\Modules\Frontend\Session\Storage\Models\Order

----




====== *Return type:*        xref:Frontend.adoc#frontend_models_order[`Order`]


Get the order session model


[[webshop_contracts_urlbuilderrepositorycontract]]
==== UrlBuilderRepositoryContract

Generate url for items, variations and categories considering all affecting configurations.



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
[#builditemurl]
----

public buildItemUrl($itemId, $lang = null):Plenty\Modules\Webshop\Helpers\UrlQuery

----




====== *Return type:*        xref:Webshop.adoc#webshop_helpers_urlquery[`UrlQuery`]


Build item url. Generate and write url to item data if not defined yet.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|Id of the item to generate url for.

a|`$lang`
|link:http://php.net/string[string^]
a|Language to generate the url in. Defaults to current language from session.
|===


[source%nowrap, php]
[#buildcategoryurl]
----

public buildCategoryUrl($categoryId, $lang = null, $webstoreId = null):Plenty\Modules\Webshop\Helpers\UrlQuery

----




====== *Return type:*        xref:Webshop.adoc#webshop_helpers_urlquery[`UrlQuery`]


Build category url by recursively prepending url names of parent categories.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$categoryId`
|link:http://php.net/int[int^]
a|Id of the category to get url for.

a|`$lang`
|link:http://php.net/string[string^]
a|Language to generate the url in. Defaults to current language from session.

a|`$webstoreId`
|link:http://php.net/int[int^]
a|Webstore to get url names for. Defaults to current webstore id.
|===


[source%nowrap, php]
[#fillitemurl]
----

public fillItemUrl($itemData):void

----







Store item data of loaded items to be reused when generating item or variation urls.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemData`
|link:http://php.net/array[array^]
a|Item data object returned from search request.
|===


[source%nowrap, php]
[#buildvariationurl]
----

public buildVariationUrl($itemId, $variationId, $lang = null):Plenty\Modules\Webshop\Helpers\UrlQuery

----




====== *Return type:*        xref:Webshop.adoc#webshop_helpers_urlquery[`UrlQuery`]


Build variation url. Variation urls equal to item urls with the variation id appended.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|Id of the item to generate url for.

a|`$variationId`
|link:http://php.net/int[int^]
a|Id of the variation to generate url for.

a|`$lang`
|link:http://php.net/string[string^]
a|Language to generate the url in. Defaults to current language from session.
|===


[source%nowrap, php]
[#getsuffix]
----

public getSuffix($itemId, $variationId, $withVariationId = true):string

----







Get the suffix to be appended to item or variation urls.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|item id to be used in the suffix.

a|`$variationId`
|link:http://php.net/int[int^]
a|variation id to be used in the suffix. Will be ignored when using Callisto urls.

a|`$withVariationId`
|link:http://php.net/bool[bool^]
a|Set if the variation id should be included in the suffix. Not considered when using Callisto urls.
|===



[[webshop_contracts_webstoreconfigurationrepositorycontract]]
==== WebstoreConfigurationRepositoryContract

Repository for webstore information



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
[#getwebstoreconfiguration]
----

public getWebstoreConfiguration():Plenty\Modules\System\Models\WebstoreConfiguration

----




====== *Return type:*        xref:System.adoc#system_models_webstoreconfiguration[`WebstoreConfiguration`]


Get the webstore configuration

[source%nowrap, php]
[#getactivelanguagelist]
----

public getActiveLanguageList():array

----







Get the activate languages of the webstore

[source%nowrap, php]
[#getdefaultshippingcountryid]
----

public getDefaultShippingCountryId():int

----







Get the default shipping-country-Id of the webstore

[source%nowrap, php]
[#setfaviconfromwebspace]
----

public setFaviconFromWebspace($plentyId, $faviconUrl):string

----







Copy a favicon from the frontend webspace to the internal storage to be available at the frontend domain.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$plentyId`
|link:http://php.net/int[int^]
a|plentyId of the client to upload the favicon for.

a|`$faviconUrl`
|link:http://php.net/string[string^]
a|Url of the favicon file in the frontend webspace
|===


[[webshop_webshop_events]]
===  Events
[[webshop_events_afterbasketitemtoorderitem]]
==== AfterBasketItemToOrderItem

Event for receiving or manupulating the order item



===== Namespace

`Plenty\Modules\Webshop\Events`






===== Methods

[source%nowrap, php]
[#getorderitem]
----

public getOrderItem():array

----







Get order item data generated from the basket item.

[source%nowrap, php]
[#getbasketitem]
----

public getBasketItem():array

----







Get basket item data used to generate the order item from.


[[webshop_events_validatevatnumber]]
==== ValidateVatNumber

Event to trigger validation of a vat number while creating new addresses. Failed validation will throw an exception.



===== Namespace

`Plenty\Modules\Webshop\Events`






===== Methods

[source%nowrap, php]
[#getvatnumber]
----

public getVatNumber():string

----







Get the vat number to validate.

[[webshop_webshop_helpers]]
===  Helpers
[[webshop_helpers_baseprice]]
==== BasePrice

Helper class for base price information.



===== Namespace

`Plenty\Modules\Webshop\Helpers`






===== Methods

[source%nowrap, php]
[#getformattedbaseprice]
----

public getFormattedBasePrice($variationId, $price, $currency, $language = null):string

----







Return a formatted string with base price information.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$variationId`
|link:http://php.net/int[int^]
a|

a|`$price`
|link:http://php.net/float[float^]
a|

a|`$currency`
|link:http://php.net/string[string^]
a|

a|`$language`
|link:http://php.net/string[string^]
a|
|===



[[webshop_helpers_numberformatter]]
==== NumberFormatter

Helper class for number formatting



===== Namespace

`Plenty\Modules\Webshop\Helpers`






===== Methods

[source%nowrap, php]
[#formatdecimal]
----

public formatDecimal($value, $decimal_places = -1):string

----







Format the given value to decimal

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$value`
|link:http://php.net/float[float^]
a|

a|`$decimal_places`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#formatmonetary]
----

public formatMonetary($value, $currencyISO):string

----







Format the given value to currency

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$value`
|
a|

a|`$currencyISO`
|
a|
|===



[[webshop_helpers_pluginconfig]]
==== PluginConfig

Helper to get plugin configuration values. Provides several methods to read configuration values and cast them into required type.



===== Namespace

`Plenty\Modules\Webshop\Helpers`






===== Methods

[source%nowrap, php]
[#load]
----

public load():void

----







Initially load configuration values into member variables.

[source%nowrap, php]
[#getpluginname]
----

public getPluginName():string

----







Return the name of the plugin to get the configuration values for.

[source%nowrap, php]
[#getmultiselectvalue]
----

public getMultiSelectValue($key, $possibleValues = [], $default = []):array

----







Get values of a multiselect configuration.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The key of the configuration to read.

a|`$possibleValues`
|link:http://php.net/array[array^]
a|List of possible configuration values. Will be returned if the configuration value is "all"

a|`$default`
|link:http://php.net/array[array^]
a|A default value to return if the configuration is not set yet.
|===


[source%nowrap, php]
[#gettextvalue]
----

public getTextValue($key, $default = &quot;&quot;, $transformDefault = &quot;&quot;):string

----







Get the value of a text configuration.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The key of the configuration to read.

a|`$default`
|link:http://php.net/string[string^]
a|A default value to return if the configuration is not set yet.

a|`$transformDefault`
|link:http://php.net/string[string^]
a|A value to be interpreted as a default value.
Use this if you have defined a value in your config.json that should be handled as default value.
|===


[source%nowrap, php]
[#getintegervalue]
----

public getIntegerValue($key, $default):int

----







Get the value of an integer configuration.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The key of the configuration to read.

a|`$default`
|link:http://php.net/int[int^]
a|A default value to return if the configuration is not set yet.
|===


[source%nowrap, php]
[#getbooleanvalue]
----

public getBooleanValue($key, $default = false):bool

----







Get the value of a boolean configuration.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The key of the configuration to read.

a|`$default`
|link:http://php.net/bool[bool^]
a|A default value to return if the configuration is not set yet.
|===


[source%nowrap, php]
[#getconfigvalue]
----

public getConfigValue($key, $default = null):void

----







Get a configuration value without any cast.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|The key of the configuration to read.

a|`$default`
|
a|A default value to return if the configuration is not set yet.
|===



[[webshop_helpers_unitutils]]
==== UnitUtils

Convert plentymarkets unit keys into common unit codes.



===== Namespace

`Plenty\Modules\Webshop\Helpers`






===== Methods

[source%nowrap, php]
[#gethtml4unit]
----

public static getHTML4Unit($unit = &quot;SMM&quot;):string

----







Return common code for a unit (&#039;m&#039;,&#039;cm&#039; &#039;mm&#039;).

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$unit`
|link:http://php.net/string[string^]
a|The internal unit key.
|===



[[webshop_helpers_urlquery]]
==== UrlQuery

Helper to generate and manipulate urls to be used in the webshop.



===== Namespace

`Plenty\Modules\Webshop\Helpers`






===== Methods

[source%nowrap, php]
[#create]
----

public static create($path = null, $lang = null):Plenty\Modules\Webshop\Helpers\UrlQuery

----




====== *Return type:*        xref:Webshop.adoc#webshop_helpers_urlquery[`UrlQuery`]


Create a new instance.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$path`
|link:http://php.net/string[string^]
a|The path of the url.

a|`$lang`
|link:http://php.net/string[string^]
a|The language of the generated url. Will be included automatically if it is different to the default language.
|===


[source%nowrap, php]
[#shouldappendtrailingslash]
----

public static shouldAppendTrailingSlash():bool

----







Check if a trailing slash should be appended to urls.

[source%nowrap, php]
[#append]
----

public append($suffix):Plenty\Modules\Webshop\Helpers

----




====== *Return type:*        xref:Webshop.adoc#webshop_webshop_helpers[`Helpers`]


Append a string to the path the url without checking for slashes.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$suffix`
|link:http://php.net/string[string^]
a|String to append to the path.
|===


[source%nowrap, php]
[#join]
----

public join($path):Plenty\Modules\Webshop\Helpers

----




====== *Return type:*        xref:Webshop.adoc#webshop_webshop_helpers[`Helpers`]


Append a new path to the existing one. Ensure having a slash as glue between existing path and the new segment.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$path`
|link:http://php.net/string[string^]
a|The new path to append.
|===


[source%nowrap, php]
[#toabsoluteurl]
----

public toAbsoluteUrl($includeLanguage = false):string

----







Return the absolute url by prepending the HTTPS domain of the current client.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$includeLanguage`
|link:http://php.net/bool[bool^]
a|If true it will include the language at the beginning of the path.
|===


[source%nowrap, php]
[#torelativeurl]
----

public toRelativeUrl($includeLanguage = false):string

----







Return the path as a relative url.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$includeLanguage`
|link:http://php.net/bool[bool^]
a|If true it will include the language at the beginning of the path.
|===


[source%nowrap, php]
[#getpath]
----

public getPath($includeLanguage = false):string

----







Return the path. This equals the relative url without a leading slash.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$includeLanguage`
|link:http://php.net/bool[bool^]
a|If true it will include the language at the beginning of the path.
|===


[source%nowrap, php]
[#equals]
----

public equals($path):bool

----







Compare current path to a string independent of a trailing slash.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$path`
|link:http://php.net/string[string^]
a|String to compare the current path to.
|===


[[webshop_webshop_hooks]]
===  Hooks
[[webshop_hooks_checkvatnumber]]
==== CheckVatNumber

Hook to execute validation of vat numbers. Can be triggered by emitting ValidateVatNumber while creating new addresses.



===== Namespace

`Plenty\Modules\Webshop\Hooks`






===== Methods

[source%nowrap, php]
[#handle]
----

public handle($vatNumberEvent):void

----







Validate the given vat number

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$vatNumberEvent`
|        xref:Webshop.adoc#webshop_events_validatevatnumber[`ValidateVatNumber`]
a|Event emitted while creating new addresses.
|===


[[webshop_itemsearch]]
== ItemSearch

[[webshop_itemsearch_contracts]]
===  Contracts
[[webshop_contracts_facetextension]]
==== FacetExtension

Interface to add custom facets.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Contracts`






===== Methods

[source%nowrap, php]
[#getaggregation]
----

public getAggregation():Plenty\Modules\Cloud\ElasticSearch\Lib\Search\Aggregation\AggregationInterface

----




====== *Return type:*        xref:Cloud.adoc#cloud_aggregation_aggregationinterface[`AggregationInterface`]


Get the aggregation to apply the facet to the search results.

[source%nowrap, php]
[#mergeintofacetslist]
----

public mergeIntoFacetsList($result):array

----







Merge facet data into list of facets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$result`
|
a|Facet data
|===


[source%nowrap, php]
[#extractfilterparams]
----

public extractFilterParams($filtersList):void

----







Extract search filters from filter paramters to be applied to the search request.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filtersList`
|
a|List of value ids for this facet. Possible values can be set by mergeIntoFacetsList()
|===


[[webshop_itemsearch_extensions]]
===  Extensions
[[webshop_extensions_itemsearchextension]]
==== ItemSearchExtension

Extend the search result by additional data or mutate raw data in search results.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Extensions`





[[webshop_itemsearch_factories]]
===  Factories
[[webshop_factories_basesearchfactory]]
==== BaseSearchFactory

Base factory to prepare and build search requests on variation data interface



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Factories`






===== Methods

[source%nowrap, php]
[#inherit]
----

public inherit($inheritedProperties = []):Plenty\Modules\Webshop\ItemSearch\Factories\BaseSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_basesearchfactory[`BaseSearchFactory`]


Create a new factory instance based on properties of an existing factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$inheritedProperties`
|link:http://php.net/array[array^]
a|List of properties to inherit or null to inherit all properties.
|===


[source%nowrap, php]
[#withmutator]
----

public withMutator($mutator, $excludeDependencies = false, $position = 1000):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add a mutator to transform search results.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mutator`
|        xref:Cloud.adoc#cloud_mutator_mutatorinterface[`MutatorInterface`]
a|The mutator itself

a|`$excludeDependencies`
|link:http://php.net/bool[bool^]
a|Set to true to remove required data from the results after applying the mutator.
Fields will only be removed if they are not requested by the result fields of the search request.

a|`$position`
|link:http://php.net/int[int^]
a|Position of the mutator. Mutators are executed in the order of their positions.
|===


[source%nowrap, php]
[#createfilter]
----

public createFilter($filterClass, $params = []):void

----







Add a filter. Will create a new instance of the filter class if not already created.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filterClass`
|link:http://php.net/string[string^]
a|

a|`$params`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#withfilter]
----

public withFilter($filter):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add a filter. Will override existing filter instances.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filter`
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|
|===


[source%nowrap, php]
[#withresultfields]
----

public withResultFields($fields):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set fields to be contained in search result.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fields`
|
a|Reference to a json file to load fields from or a list of field names.
|===


[source%nowrap, php]
[#getresultfields]
----

public getResultFields():array

----







Get the requested result fields for this search request.

[source%nowrap, php]
[#hasresultfield]
----

public hasResultField($field):bool

----







Check if result field is already included in the source of the search.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$field`
|link:http://php.net/string[string^]
a|The field to search for in result fields
|===


[source%nowrap, php]
[#getadditionalresultfields]
----

public getAdditionalResultFields():array

----







Get additional result fields required by webshop mutators.

[source%nowrap, php]
[#withextension]
----

public withExtension($extensionClass, $extensionParams = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add an extension.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$extensionClass`
|link:http://php.net/string[string^]
a|Extension class to add.

a|`$extensionParams`
|link:http://php.net/array[array^]
a|Additional parameters to pass to extensions constructor
|===


[source%nowrap, php]
[#getextensions]
----

public getExtensions():array

----







Get all registered extensions

[source%nowrap, php]
[#getmutators]
----

public getMutators():array

----







Get all registered mutators

[source%nowrap, php]
[#withaggregation]
----

public withAggregation($aggregation):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add an aggregation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$aggregation`
|        xref:Cloud.adoc#cloud_aggregation_aggregationinterface[`AggregationInterface`]
a|
|===


[source%nowrap, php]
[#withsuggestion]
----

public withSuggestion($suggestion):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add a suggestion

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$suggestion`
|        xref:Cloud.adoc#cloud_suggestion_suggestioninterface[`SuggestionInterface`]
a|
|===


[source%nowrap, php]
[#setpage]
----

public setPage($page, $itemsPerPage):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set pagination parameters.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#sortby]
----

public sortBy($field, $order = \Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory::SORTING_ORDER_DESC):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add sorting parameters

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$field`
|link:http://php.net/string[string^]
a|The field to order by

a|`$order`
|link:http://php.net/string[string^]
a|Direction to order results. Possible values: 'asc' or 'desc'
|===


[source%nowrap, php]
[#sortbymultiple]
----

public sortByMultiple($sortingList):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add multiple sorting parameters

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sortingList`
|link:http://php.net/array[array^]
a|List of sorting parameters. Each entry should have a 'field' and an 'order' property.
|===


[source%nowrap, php]
[#setorder]
----

public setOrder($idList):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set the order of the search results by ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$idList`
|link:http://php.net/array[array^]
a|List of variation ids. Search results will be sorted in the same order.
|===


[source%nowrap, php]
[#groupby]
----

public groupBy($field, $sortings = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Group results by field

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$field`
|link:http://php.net/string[string^]
a|The field to group properties by.

a|`$sortings`
|link:http://php.net/array[array^]
a|List of sort criteria. Might contain string
|===



[[webshop_factories_facetsearchfactory]]
==== FacetSearchFactory

Prepare and build search requests to query facets



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Factories`






===== Methods

[source%nowrap, php]
[#create]
----

public static create($facets):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Create a factory instance depending on a given set of facet values.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$facets`
|
a|List of active facet values. If string is given, it will be exploded by ',' to a list of values.
|===


[source%nowrap, php]
[#withminimumcount]
----

public withMinimumCount():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Register extension to filter facets by minimum hit count.

[source%nowrap, php]
[#default]
----

public static default($options = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Get the default configuration of a search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options
<ul>
 <li><b>quantities</b> Quantities of the variations in the basket. This will be considered while calculating graduated prices</li>
 <li><b>setPriceOnly</b> Set to true to only consider prices for item sets</li>
</ul>
|===


[source%nowrap, php]
[#setadminpreview]
----

public setAdminPreview($isAdminPreview):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set preview mode for the search request.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isAdminPreview`
|link:http://php.net/bool[bool^]
a|Set to true to enable preview.
|===


[source%nowrap, php]
[#isactive]
----

public isActive():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter active variations

[source%nowrap, php]
[#isinactive]
----

public isInactive():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter inactive variations

[source%nowrap, php]
[#hasitemid]
----

public hasItemId($itemId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variation by a single item id

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|Item id to filter by.
|===


[source%nowrap, php]
[#hasitemids]
----

public hasItemIds($itemIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by multiple item ids

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemIds`
|link:http://php.net/array[array^]
a|List of item ids to filter by.
|===


[source%nowrap, php]
[#hasvariationid]
----

public hasVariationId($variationId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variation by a single variation id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$variationId`
|link:http://php.net/int[int^]
a|The variation id to filter by.
|===


[source%nowrap, php]
[#hasvariationids]
----

public hasVariationIds($variationIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by multiple variation ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$variationIds`
|link:http://php.net/array[array^]
a|List of variation ids to filter by.
|===


[source%nowrap, php]
[#hasatleastoneavailability]
----

public hasAtLeastOneAvailability($availabilityIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by multiple availability ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$availabilityIds`
|link:http://php.net/array[array^]
a|List of availability ids to filter by.
|===


[source%nowrap, php]
[#hassupplier]
----

public hasSupplier($supplierId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by multiple availability ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$supplierId`
|link:http://php.net/int[int^]
a|The supplier id to filter by.
|===


[source%nowrap, php]
[#hasmanufacturer]
----

public hasManufacturer($manufacturerId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter manufacturers by id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$manufacturerId`
|link:http://php.net/int[int^]
a|To filter by manufacturer
|===


[source%nowrap, php]
[#haseachproperty]
----

public hasEachProperty($propertyIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by multiple property ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyIds`
|link:http://php.net/array[array^]
a|The property ids to filter by.
|===


[source%nowrap, php]
[#ismain]
----

public isMain():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter only main variations

[source%nowrap, php]
[#ischild]
----

public isChild():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter only child variations

[source%nowrap, php]
[#ishiddenincategorylist]
----

public isHiddenInCategoryList($isHidden = true):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter by visibility in category list.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isHidden`
|link:http://php.net/bool[bool^]
a|Visibility in category list to filter by.
|===


[source%nowrap, php]
[#issalable]
----

public isSalable():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by isSalable flag

[source%nowrap, php]
[#isvisibleforclient]
----

public isVisibleForClient($clientId = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by visibility for client

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$clientId`
|link:http://php.net/int[int^]
a|The client id to filter by. If null, default client id from config will be used.
|===


[source%nowrap, php]
[#hasnameinlanguage]
----

public hasNameInLanguage($type = &quot;hasAnyNameInLanguage&quot;, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations having texts in a given language.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|The text field to filter by ('hasAny', 'hasName1', 'hasName2', 'hasName3')

a|`$lang`
|link:http://php.net/string[string^]
a|The language to filter by. If null, language defined in session will be used.
|===


[source%nowrap, php]
[#isincategory]
----

public isInCategory($categoryId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations contained in a category.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$categoryId`
|link:http://php.net/int[int^]
a|A category id to filter variations by.
|===


[source%nowrap, php]
[#hasatleastoneprice]
----

public hasAtLeastOnePrice($priceIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations having at least on price.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$priceIds`
|link:http://php.net/array[array^]
a|List of price ids to filter variations by
|===


[source%nowrap, php]
[#haspriceforcustomer]
----

public hasPriceForCustomer():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations having at least one price accessible by current customer.

[source%nowrap, php]
[#haspriceinrange]
----

public hasPriceInRange($priceMin, $priceMax):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$priceMin`
|link:http://php.net/float[float^]
a|

a|`$priceMax`
|link:http://php.net/float[float^]
a|
|===


[source%nowrap, php]
[#hastag]
----

public hasTag($tagId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tagId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#hasanytag]
----

public hasAnyTag($tagIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tagIds`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#groupbytemplateconfig]
----

public groupByTemplateConfig():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Group results depending on a config value.

[source%nowrap, php]
[#iscrosssellingitem]
----

public isCrossSellingItem($itemId, $relation):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations having a cross selling relation to a given item.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|Item id to filter cross selling items for

a|`$relation`
|link:http://php.net/string[string^]
a|The relation of cross selling items.
|===


[source%nowrap, php]
[#hasfacets]
----

public hasFacets($facetValues, $clientId = null, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by facets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$facetValues`
|
a|List of facet values. If string is given, it will be exploded by ';'

a|`$clientId`
|link:http://php.net/int[int^]
a|Client id to filter facets by. If null, default client id from config will be used.

a|`$lang`
|link:http://php.net/string[string^]
a|Language to filter facets by. If null, active language from session will be used.
|===


[source%nowrap, php]
[#hassearchstring]
----

public hasSearchString($query, $lang = null, $a = &quot;&quot;, $b = &quot;&quot;):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by given search string.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|link:http://php.net/string[string^]
a|The search string to filter variations by

a|`$lang`
|link:http://php.net/string[string^]
a|The language to apply search on. If null, default language from session will be used

a|`$a`
|link:http://php.net/string[string^]
a|The item search operator should be "or" or "and"

a|`$b`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#hasnamestring]
----

public hasNameString($query, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by searching names

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|link:http://php.net/string[string^]
a|The search string

a|`$lang`
|link:http://php.net/string[string^]
a|Language to apply search on. If null, default language from session will be used.
|===


[source%nowrap, php]
[#withlanguage]
----

public withLanguage($lang = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Only request given language.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|Language to get texts for. If null, default language from session will be used.
|===


[source%nowrap, php]
[#withimages]
----

public withImages($clientId = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Include images in result

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$clientId`
|link:http://php.net/int[int^]
a|The client id to get images for. If null, default client id from config will be used.
|===


[source%nowrap, php]
[#withvariationattributemap]
----

public withVariationAttributeMap($itemId, $initialVariationId, $afterKey = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Includes VariationAttributeMap for variation select

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|

a|`$initialVariationId`
|link:http://php.net/int[int^]
a|

a|`$afterKey`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#withpropertygroups]
----

public withPropertyGroups($displaySettings = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$displaySettings`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#withorderpropertyselectionvalues]
----

public withOrderPropertySelectionValues():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withvariationproperties]
----

public withVariationProperties():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withurls]
----

public withUrls():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Append URLs to result.

[source%nowrap, php]
[#withprices]
----

public withPrices($quantities = [], $setPriceOnly = false):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Append prices to result.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$quantities`
|link:http://php.net/array[array^]
a|

a|`$setPriceOnly`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withcurrentcategory]
----

public withCurrentCategory():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set result as current category

[source%nowrap, php]
[#withdefaultimage]
----

public withDefaultImage():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Append default item image if images are requested by result fields and item does not have any image

[source%nowrap, php]
[#withbundlecomponents]
----

public withBundleComponents():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add bundle component variations.

[source%nowrap, php]
[#withsetcomponents]
----

public withSetComponents():void

----







Add set component variations to item set entries.

[source%nowrap, php]
[#withlinktocontent]
----

public withLinkToContent():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withgroupedattributevalues]
----

public withGroupedAttributeValues():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withreducedresults]
----

public withReducedResults():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withavailability]
----

public withAvailability():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withtags]
----

public withTags():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withcategories]
----

public withCategories():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withsuggestions]
----

public withSuggestions($query = &quot;&quot;, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|link:http://php.net/string[string^]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdidyoumeansuggestions]
----

public withDidYouMeanSuggestions($query):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withsalablevariationcount]
----

public withSalableVariationCount():Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]




[source%nowrap, php]
[#inherit]
----

public inherit($inheritedProperties = []):Plenty\Modules\Webshop\ItemSearch\Factories\BaseSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_basesearchfactory[`BaseSearchFactory`]


Create a new factory instance based on properties of an existing factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$inheritedProperties`
|link:http://php.net/array[array^]
a|List of properties to inherit or null to inherit all properties.
|===


[source%nowrap, php]
[#withmutator]
----

public withMutator($mutator, $excludeDependencies = false, $position = 1000):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add a mutator to transform search results.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mutator`
|        xref:Cloud.adoc#cloud_mutator_mutatorinterface[`MutatorInterface`]
a|The mutator itself

a|`$excludeDependencies`
|link:http://php.net/bool[bool^]
a|Set to true to remove required data from the results after applying the mutator.
Fields will only be removed if they are not requested by the result fields of the search request.

a|`$position`
|link:http://php.net/int[int^]
a|Position of the mutator. Mutators are executed in the order of their positions.
|===


[source%nowrap, php]
[#createfilter]
----

public createFilter($filterClass, $params = []):void

----







Add a filter. Will create a new instance of the filter class if not already created.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filterClass`
|link:http://php.net/string[string^]
a|

a|`$params`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#withfilter]
----

public withFilter($filter):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add a filter. Will override existing filter instances.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filter`
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|
|===


[source%nowrap, php]
[#withresultfields]
----

public withResultFields($fields):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set fields to be contained in search result.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fields`
|
a|Reference to a json file to load fields from or a list of field names.
|===


[source%nowrap, php]
[#getresultfields]
----

public getResultFields():array

----







Get the requested result fields for this search request.

[source%nowrap, php]
[#hasresultfield]
----

public hasResultField($field):bool

----







Check if result field is already included in the source of the search.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$field`
|link:http://php.net/string[string^]
a|The field to search for in result fields
|===


[source%nowrap, php]
[#getadditionalresultfields]
----

public getAdditionalResultFields():array

----







Get additional result fields required by webshop mutators.

[source%nowrap, php]
[#withextension]
----

public withExtension($extensionClass, $extensionParams = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add an extension.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$extensionClass`
|link:http://php.net/string[string^]
a|Extension class to add.

a|`$extensionParams`
|link:http://php.net/array[array^]
a|Additional parameters to pass to extensions constructor
|===


[source%nowrap, php]
[#getextensions]
----

public getExtensions():array

----







Get all registered extensions

[source%nowrap, php]
[#getmutators]
----

public getMutators():array

----







Get all registered mutators

[source%nowrap, php]
[#withaggregation]
----

public withAggregation($aggregation):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add an aggregation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$aggregation`
|        xref:Cloud.adoc#cloud_aggregation_aggregationinterface[`AggregationInterface`]
a|
|===


[source%nowrap, php]
[#withsuggestion]
----

public withSuggestion($suggestion):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add a suggestion

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$suggestion`
|        xref:Cloud.adoc#cloud_suggestion_suggestioninterface[`SuggestionInterface`]
a|
|===


[source%nowrap, php]
[#setpage]
----

public setPage($page, $itemsPerPage):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set pagination parameters.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#sortby]
----

public sortBy($field, $order = \Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory::SORTING_ORDER_DESC):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add sorting parameters

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$field`
|link:http://php.net/string[string^]
a|The field to order by

a|`$order`
|link:http://php.net/string[string^]
a|Direction to order results. Possible values: 'asc' or 'desc'
|===


[source%nowrap, php]
[#sortbymultiple]
----

public sortByMultiple($sortingList):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add multiple sorting parameters

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sortingList`
|link:http://php.net/array[array^]
a|List of sorting parameters. Each entry should have a 'field' and an 'order' property.
|===


[source%nowrap, php]
[#setorder]
----

public setOrder($idList):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set the order of the search results by ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$idList`
|link:http://php.net/array[array^]
a|List of variation ids. Search results will be sorted in the same order.
|===


[source%nowrap, php]
[#groupby]
----

public groupBy($field, $sortings = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Group results by field

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$field`
|link:http://php.net/string[string^]
a|The field to group properties by.

a|`$sortings`
|link:http://php.net/array[array^]
a|List of sort criteria. Might contain string
|===



[[webshop_factories_variationsearchfactory]]
==== VariationSearchFactory

Prepare and build search requests to query variations



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Factories`






===== Methods

[source%nowrap, php]
[#default]
----

public static default($options = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Get the default configuration of a search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options
<ul>
 <li><b>quantities</b> Quantities of the variations in the basket. This will be considered while calculating graduated prices</li>
 <li><b>setPriceOnly</b> Set to true to only consider prices for item sets</li>
</ul>
|===


[source%nowrap, php]
[#setadminpreview]
----

public setAdminPreview($isAdminPreview):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set preview mode for the search request.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isAdminPreview`
|link:http://php.net/bool[bool^]
a|Set to true to enable preview.
|===


[source%nowrap, php]
[#isactive]
----

public isActive():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter active variations

[source%nowrap, php]
[#isinactive]
----

public isInactive():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter inactive variations

[source%nowrap, php]
[#hasitemid]
----

public hasItemId($itemId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variation by a single item id

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|Item id to filter by.
|===


[source%nowrap, php]
[#hasitemids]
----

public hasItemIds($itemIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by multiple item ids

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemIds`
|link:http://php.net/array[array^]
a|List of item ids to filter by.
|===


[source%nowrap, php]
[#hasvariationid]
----

public hasVariationId($variationId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variation by a single variation id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$variationId`
|link:http://php.net/int[int^]
a|The variation id to filter by.
|===


[source%nowrap, php]
[#hasvariationids]
----

public hasVariationIds($variationIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by multiple variation ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$variationIds`
|link:http://php.net/array[array^]
a|List of variation ids to filter by.
|===


[source%nowrap, php]
[#hasatleastoneavailability]
----

public hasAtLeastOneAvailability($availabilityIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by multiple availability ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$availabilityIds`
|link:http://php.net/array[array^]
a|List of availability ids to filter by.
|===


[source%nowrap, php]
[#hassupplier]
----

public hasSupplier($supplierId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by multiple availability ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$supplierId`
|link:http://php.net/int[int^]
a|The supplier id to filter by.
|===


[source%nowrap, php]
[#hasmanufacturer]
----

public hasManufacturer($manufacturerId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter manufacturers by id.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$manufacturerId`
|link:http://php.net/int[int^]
a|To filter by manufacturer
|===


[source%nowrap, php]
[#haseachproperty]
----

public hasEachProperty($propertyIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by multiple property ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$propertyIds`
|link:http://php.net/array[array^]
a|The property ids to filter by.
|===


[source%nowrap, php]
[#ismain]
----

public isMain():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter only main variations

[source%nowrap, php]
[#ischild]
----

public isChild():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter only child variations

[source%nowrap, php]
[#ishiddenincategorylist]
----

public isHiddenInCategoryList($isHidden = true):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter by visibility in category list.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$isHidden`
|link:http://php.net/bool[bool^]
a|Visibility in category list to filter by.
|===


[source%nowrap, php]
[#issalable]
----

public isSalable():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by isSalable flag

[source%nowrap, php]
[#isvisibleforclient]
----

public isVisibleForClient($clientId = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by visibility for client

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$clientId`
|link:http://php.net/int[int^]
a|The client id to filter by. If null, default client id from config will be used.
|===


[source%nowrap, php]
[#hasnameinlanguage]
----

public hasNameInLanguage($type = &quot;hasAnyNameInLanguage&quot;, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations having texts in a given language.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$type`
|link:http://php.net/string[string^]
a|The text field to filter by ('hasAny', 'hasName1', 'hasName2', 'hasName3')

a|`$lang`
|link:http://php.net/string[string^]
a|The language to filter by. If null, language defined in session will be used.
|===


[source%nowrap, php]
[#isincategory]
----

public isInCategory($categoryId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations contained in a category.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$categoryId`
|link:http://php.net/int[int^]
a|A category id to filter variations by.
|===


[source%nowrap, php]
[#hasatleastoneprice]
----

public hasAtLeastOnePrice($priceIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations having at least on price.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$priceIds`
|link:http://php.net/array[array^]
a|List of price ids to filter variations by
|===


[source%nowrap, php]
[#haspriceforcustomer]
----

public hasPriceForCustomer():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations having at least one price accessible by current customer.

[source%nowrap, php]
[#haspriceinrange]
----

public hasPriceInRange($priceMin, $priceMax):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$priceMin`
|link:http://php.net/float[float^]
a|

a|`$priceMax`
|link:http://php.net/float[float^]
a|
|===


[source%nowrap, php]
[#hastag]
----

public hasTag($tagId):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tagId`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#hasanytag]
----

public hasAnyTag($tagIds):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$tagIds`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#groupbytemplateconfig]
----

public groupByTemplateConfig():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Group results depending on a config value.

[source%nowrap, php]
[#iscrosssellingitem]
----

public isCrossSellingItem($itemId, $relation):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations having a cross selling relation to a given item.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|Item id to filter cross selling items for

a|`$relation`
|link:http://php.net/string[string^]
a|The relation of cross selling items.
|===


[source%nowrap, php]
[#hasfacets]
----

public hasFacets($facetValues, $clientId = null, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by facets.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$facetValues`
|
a|List of facet values. If string is given, it will be exploded by ';'

a|`$clientId`
|link:http://php.net/int[int^]
a|Client id to filter facets by. If null, default client id from config will be used.

a|`$lang`
|link:http://php.net/string[string^]
a|Language to filter facets by. If null, active language from session will be used.
|===


[source%nowrap, php]
[#hassearchstring]
----

public hasSearchString($query, $lang = null, $a = &quot;&quot;, $b = &quot;&quot;):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by given search string.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|link:http://php.net/string[string^]
a|The search string to filter variations by

a|`$lang`
|link:http://php.net/string[string^]
a|The language to apply search on. If null, default language from session will be used

a|`$a`
|link:http://php.net/string[string^]
a|The item search operator should be "or" or "and"

a|`$b`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#hasnamestring]
----

public hasNameString($query, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Filter variations by searching names

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|link:http://php.net/string[string^]
a|The search string

a|`$lang`
|link:http://php.net/string[string^]
a|Language to apply search on. If null, default language from session will be used.
|===


[source%nowrap, php]
[#withlanguage]
----

public withLanguage($lang = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Only request given language.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|Language to get texts for. If null, default language from session will be used.
|===


[source%nowrap, php]
[#withimages]
----

public withImages($clientId = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Include images in result

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$clientId`
|link:http://php.net/int[int^]
a|The client id to get images for. If null, default client id from config will be used.
|===


[source%nowrap, php]
[#withvariationattributemap]
----

public withVariationAttributeMap($itemId, $initialVariationId, $afterKey = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Includes VariationAttributeMap for variation select

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$itemId`
|link:http://php.net/int[int^]
a|

a|`$initialVariationId`
|link:http://php.net/int[int^]
a|

a|`$afterKey`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#withpropertygroups]
----

public withPropertyGroups($displaySettings = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$displaySettings`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#withorderpropertyselectionvalues]
----

public withOrderPropertySelectionValues():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withvariationproperties]
----

public withVariationProperties():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withurls]
----

public withUrls():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Append URLs to result.

[source%nowrap, php]
[#withprices]
----

public withPrices($quantities = [], $setPriceOnly = false):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Append prices to result.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$quantities`
|link:http://php.net/array[array^]
a|

a|`$setPriceOnly`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#withcurrentcategory]
----

public withCurrentCategory():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set result as current category

[source%nowrap, php]
[#withdefaultimage]
----

public withDefaultImage():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Append default item image if images are requested by result fields and item does not have any image

[source%nowrap, php]
[#withbundlecomponents]
----

public withBundleComponents():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add bundle component variations.

[source%nowrap, php]
[#withsetcomponents]
----

public withSetComponents():void

----







Add set component variations to item set entries.

[source%nowrap, php]
[#withlinktocontent]
----

public withLinkToContent():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withgroupedattributevalues]
----

public withGroupedAttributeValues():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withreducedresults]
----

public withReducedResults():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withavailability]
----

public withAvailability():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withtags]
----

public withTags():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withcategories]
----

public withCategories():Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




[source%nowrap, php]
[#withsuggestions]
----

public withSuggestions($query = &quot;&quot;, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|link:http://php.net/string[string^]
a|

a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withdidyoumeansuggestions]
----

public withDidYouMeanSuggestions($query):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]




.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$query`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#withsalablevariationcount]
----

public withSalableVariationCount():Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]




[source%nowrap, php]
[#inherit]
----

public inherit($inheritedProperties = []):Plenty\Modules\Webshop\ItemSearch\Factories\BaseSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_basesearchfactory[`BaseSearchFactory`]


Create a new factory instance based on properties of an existing factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$inheritedProperties`
|link:http://php.net/array[array^]
a|List of properties to inherit or null to inherit all properties.
|===


[source%nowrap, php]
[#withmutator]
----

public withMutator($mutator, $excludeDependencies = false, $position = 1000):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add a mutator to transform search results.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$mutator`
|        xref:Cloud.adoc#cloud_mutator_mutatorinterface[`MutatorInterface`]
a|The mutator itself

a|`$excludeDependencies`
|link:http://php.net/bool[bool^]
a|Set to true to remove required data from the results after applying the mutator.
Fields will only be removed if they are not requested by the result fields of the search request.

a|`$position`
|link:http://php.net/int[int^]
a|Position of the mutator. Mutators are executed in the order of their positions.
|===


[source%nowrap, php]
[#createfilter]
----

public createFilter($filterClass, $params = []):void

----







Add a filter. Will create a new instance of the filter class if not already created.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filterClass`
|link:http://php.net/string[string^]
a|

a|`$params`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#withfilter]
----

public withFilter($filter):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add a filter. Will override existing filter instances.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$filter`
|        xref:Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|
|===


[source%nowrap, php]
[#withresultfields]
----

public withResultFields($fields):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set fields to be contained in search result.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$fields`
|
a|Reference to a json file to load fields from or a list of field names.
|===


[source%nowrap, php]
[#getresultfields]
----

public getResultFields():array

----







Get the requested result fields for this search request.

[source%nowrap, php]
[#hasresultfield]
----

public hasResultField($field):bool

----







Check if result field is already included in the source of the search.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$field`
|link:http://php.net/string[string^]
a|The field to search for in result fields
|===


[source%nowrap, php]
[#getadditionalresultfields]
----

public getAdditionalResultFields():array

----







Get additional result fields required by webshop mutators.

[source%nowrap, php]
[#withextension]
----

public withExtension($extensionClass, $extensionParams = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add an extension.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$extensionClass`
|link:http://php.net/string[string^]
a|Extension class to add.

a|`$extensionParams`
|link:http://php.net/array[array^]
a|Additional parameters to pass to extensions constructor
|===


[source%nowrap, php]
[#getextensions]
----

public getExtensions():array

----







Get all registered extensions

[source%nowrap, php]
[#getmutators]
----

public getMutators():array

----







Get all registered mutators

[source%nowrap, php]
[#withaggregation]
----

public withAggregation($aggregation):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add an aggregation

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$aggregation`
|        xref:Cloud.adoc#cloud_aggregation_aggregationinterface[`AggregationInterface`]
a|
|===


[source%nowrap, php]
[#withsuggestion]
----

public withSuggestion($suggestion):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add a suggestion

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$suggestion`
|        xref:Cloud.adoc#cloud_suggestion_suggestioninterface[`SuggestionInterface`]
a|
|===


[source%nowrap, php]
[#setpage]
----

public setPage($page, $itemsPerPage):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set pagination parameters.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$page`
|link:http://php.net/int[int^]
a|

a|`$itemsPerPage`
|link:http://php.net/int[int^]
a|
|===


[source%nowrap, php]
[#sortby]
----

public sortBy($field, $order = \Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory::SORTING_ORDER_DESC):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add sorting parameters

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$field`
|link:http://php.net/string[string^]
a|The field to order by

a|`$order`
|link:http://php.net/string[string^]
a|Direction to order results. Possible values: 'asc' or 'desc'
|===


[source%nowrap, php]
[#sortbymultiple]
----

public sortByMultiple($sortingList):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Add multiple sorting parameters

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sortingList`
|link:http://php.net/array[array^]
a|List of sorting parameters. Each entry should have a 'field' and an 'order' property.
|===


[source%nowrap, php]
[#setorder]
----

public setOrder($idList):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Set the order of the search results by ids.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$idList`
|link:http://php.net/array[array^]
a|List of variation ids. Search results will be sorted in the same order.
|===


[source%nowrap, php]
[#groupby]
----

public groupBy($field, $sortings = []):Plenty\Modules\Webshop\ItemSearch\Factories

----




====== *Return type:*        xref:Webshop.adoc#webshop_itemsearch_factories[`Factories`]


Group results by field

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$field`
|link:http://php.net/string[string^]
a|The field to group properties by.

a|`$sortings`
|link:http://php.net/array[array^]
a|List of sort criteria. Might contain string
|===


[[webshop_itemsearch_helpers]]
===  Helpers
[[webshop_helpers_facetextensioncontainer]]
==== FacetExtensionContainer

Container to collect facet extensions



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Helpers`






===== Methods

[source%nowrap, php]
[#getfacetextensions]
----

public getFacetExtensions():array

----







Get all registered facet extensions.

[source%nowrap, php]
[#addfacetextension]
----

public addFacetExtension($facetExtension):void

----







Add an extension to provide a custom facet.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$facetExtension`
|        xref:Webshop.adoc#webshop_contracts_facetextension[`FacetExtension`]
a|The extension describing the facet behavior
|===



[[webshop_helpers_resultfieldtemplate]]
==== ResultFieldTemplate

Collect templates to read required result fields for several views from.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Helpers`






===== Methods

[source%nowrap, php]
[#get]
----

public static get($template):string

----







Get the path to result fields file from a plugin

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$template`
|link:http://php.net/string[string^]
a|The key of the template to get the path for.
|===


[source%nowrap, php]
[#load]
----

public static load($template):array

----







Load result fields from a template file. Result field templates can be registered from a plugin.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$template`
|link:http://php.net/string[string^]
a|The key of the template to load file contents for.
|===


[source%nowrap, php]
[#settemplate]
----

public setTemplate($event, $template, $overwriteExistingData = true):void

----







Set the path of a template to read result fields from.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$event`
|link:http://php.net/string[string^]
a|The event to set the template for.

a|`$template`
|link:http://php.net/string[string^]
a|Path to the template to read result fields from.

a|`$overwriteExistingData`
|link:http://php.net/bool[bool^]
a|Option to overwrite existing data
|===


[source%nowrap, php]
[#settemplates]
----

public setTemplates($templateMap, $overwriteExistingData = true):void

----







Set multiple templates to read result fields from.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$templateMap`
|link:http://php.net/array[array^]
a|

a|`$overwriteExistingData`
|link:http://php.net/bool[bool^]
a|
|===


[source%nowrap, php]
[#requirefields]
----

public requireFields($event, $field = null):void

----







Add required fields to variation search requests.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$event`
|
a|A single template event to set required fields for
or a map between template events and list of required fields

a|`$field`
|
a|If first parameter describes a single template event
this parameter may contain a single result field or a list of field to require.
|===



[[webshop_helpers_sortinghelper]]
==== SortingHelper

Helper class to convert sorting configuration values into internal sorting paramters used by variation data interface.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Helpers`






===== Methods

[source%nowrap, php]
[#getsorting]
----

public getSorting($sortingConfig = null, $isCategory = true):array

----







Get sorting values from plugin configuration

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sortingConfig`
|link:http://php.net/string[string^]
a|The configuration value from the plugin. Contains a sorting field and a sorting order joined by an '_', e.g. 'item.id_asc'<br>
Possible sorting fields:
<ul>
 <li>item.id</li>
 <li>texts.name1</li>
 <li>texts.name2</li>
 <li>texts.name3</li>
 <li>variation.createdAt</li>
 <li>variation.updatedAt</li>
 <li>variation.id</li>
 <li>variation.number</li>
 <li>variation.availability.averageDays</li>
 <li>variation.position</li>
 <li>item.manufacturer.externalName</li>>
 <li>item.manufacturer.position</li>>
 <li>stock.net</li>
 <li>sorting.price.avg</li>
 <li>item.random</li>
 <li>item.feedbackDecimal</li>
</ul>

a|`$isCategory`
|link:http://php.net/bool[bool^]
a|Get default sorting configuration for category or for search
|===


[source%nowrap, php]
[#getcategorysorting]
----

public getCategorySorting($sortingConfig = null):array

----







Get sorting values for categories from config

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sortingConfig`
|link:http://php.net/string[string^]
a|The configuration value
|===


[source%nowrap, php]
[#getsearchsorting]
----

public getSearchSorting($sortingConfig = null):array

----







Get sorting values for searches from config

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sortingConfig`
|link:http://php.net/string[string^]
a|The configuration value
|===


[source%nowrap, php]
[#getuseditemname]
----

public getUsedItemName():string

----







Get the result field for the name to be displayed in the webshop.

[source%nowrap, php]
[#splitpathandorder]
----

public splitPathAndOrder($sorting):array

----







Explode configuration entries containing the field to sort by and the sorting order joined by an &#039;_&#039;.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sorting`
|link:http://php.net/string[string^]
a|Sorting configuration value, e.g. text.name_asc
|===


[source%nowrap, php]
[#maptoinnersorting]
----

public mapToInnerSorting($sorting):string

----







Map (outer) sorting from item list to (inner) sorting to be applied on grouped variations of one item.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$sorting`
|link:http://php.net/string[string^]
a|The sorting of the item list to get the inner sorting value for.
|===


[source%nowrap, php]
[#islanguagesupported]
----

public static isLanguageSupported($lang):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#islanguageactivated]
----

public static isLanguageActivated($lang):bool

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getm10lbylanguage]
----

public static getM10lByLanguage($lang, $fallback = &quot;en&quot;):string

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|

a|`$fallback`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#getlanguagebym10l]
----

public static getLanguageByM10l($lang, $fallback = &quot;english&quot;):string

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$lang`
|link:http://php.net/string[string^]
a|

a|`$fallback`
|link:http://php.net/string[string^]
a|
|===



[[webshop_helpers_variationpropertyconverter]]
==== VariationPropertyConverter

Service for mapping between variation order properties and old properties



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Helpers`






===== Methods

[source%nowrap, php]
[#convertorderproperties]
----

public convertOrderProperties($document):array

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$document`
|link:http://php.net/array[array^]
a|
|===


[source%nowrap, php]
[#convertvariationpropertyorderitems]
----

public convertVariationPropertyOrderItems($orderItems):void

----









.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$orderItems`
|
a|
|===


[[webshop_itemsearch_searchpresets]]
===  SearchPresets
[[webshop_searchpresets_basketitems]]
==== BasketItems

Query basket items.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>variationIds</b> Ids of basket items to get data for</li>
 <li><b>quantities</b> Quantity of each item to be considered when searching prices</li>
 <li><b>language</b> Required items to have a name configured in this language</li>
</ul>
|===



[[webshop_searchpresets_categoryitems]]
==== CategoryItems

Query items for a single category



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>categoryId</b> Category id to get variations for</li>
 <li><b>facets</b> Active facets to filter variations by</li>
 <li><b>sorting</b> Configuration value from plugin config</li>
 <li><b>page</b> Current page</li>
 <li><b>itemsPerPage</b> Number of items per page</li>
 <li><b>priceMin</b> Minimum price of the variations</li>
 <li><b>priceMax</b> Maximum price of the variations</li>
</ul>
|===



[[webshop_searchpresets_crosssellingitems]]
==== CrossSellingItems

Query cross selling items related to single item.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>itemId</b> Id of the item to get cross selling items for</li>
 <li><b>relation</b> The relation to consider when getting cross selling items. Default: 'Similar'</li>
 <li><b>sorting</b> Sorting of the returned items</li>
</ul>
|===



[[webshop_searchpresets_facets]]
==== Facets

Query facets for the item search of the webstore.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\FacetSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_facetsearchfactory[`FacetSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>facets</b> Values of active facets.</li>
 <li><b>categoryId</b> Category Id to filter variations by.</li>
 <li><b>query</b> Search string to get variations by.</li>
 <li><b>autocomplete</b> Flag indicating if autocomplete search should be used (boolean). Will only be used if 'query' is defined.</li>
</ul>
|===



[[webshop_searchpresets_liveshoppingitems]]
==== LiveShoppingItems

Query live shopping items.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>itemId</b> Id of an item to be queried</li>
 <li><b>itemIds</b> List of item ids to be queried</li>
 <li><b>sorting</b> Sorting of returned item</li>
 <li><b>resultFields</b> List of result fields to be used when querying items. Will use ResultField template for list items if not defined.</li>
</ul>
|===



[[webshop_searchpresets_manufactureritems]]
==== ManufacturerItems

Query items by manufacturer.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>manufacturerId</b> Id of the manufacturer to query items for.</li>
 <li><b>sorting</b> Sorting of items</li>
 <li><b>itemsPerPage</b> Number of items per page</li>
 <li><b>page</b> Current page of results</li>
</ul>
|===



[[webshop_searchpresets_searchitems]]
==== SearchItems

Query items from the item search of the webstore.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>query</b> The search string</li>
 <li><b>facets</b> Facet values of active facets</li>
 <li><b>sorting</b> Configuration value from plugin config</li>
 <li><b>page</b> The current page</li>
 <li><b>itemsPerPage</b> Number of items per page</li>
 <li><b>priceMin</b> Minimum price of the variations</li>
 <li><b>priceMax</b> Maximum price of the variations</li>
 <li><b>autocomplete</b> Flag indicating if autocompletion should be used</li>
</ul>
|===



[[webshop_searchpresets_searchpreset]]
==== SearchPreset

Define a preset of search request parameters to be reused for common search requests.
 * 



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):void

----







Get the search factory from the preset.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|
|===



[[webshop_searchpresets_searchsuggestions]]
==== SearchSuggestions

Query items to display search suggestions



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>sorting</b> Sorting of items</li>
 <li><b>query</b> Search query to get suggestions for</li>
</ul>
|===



[[webshop_searchpresets_singleitem]]
==== SingleItem

Get item to be displayed on single item pages



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>itemId</b> Item id to get</li>
 <li><b>variationId</b> Variation id to get. If not defined, plugin configuration will be considered if main or child variation should be displayed.</li>
 <li><b>setCategory</b> Flag indicating if item should be set as current item to be displayed in breadcrumbs</li>
</ul>
|===



[[webshop_searchpresets_tagitems]]
==== TagItems

Query items by tag id.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>tagIds</b> List of tag ids to query items by</li>
 <li><b>priceMin</b> Minimum price to filter items by</li>
 <li><b>priceMax</b> Maximum price to filter items by</li>
</ul>
|===



[[webshop_searchpresets_variationattributemap]]
==== VariationAttributeMap

Append list of all variations for attribute selection in item views



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options
<ul>
 <li><b>itemId</b> Id of the to get variations and attributes for</li>
 <li><b>variationId</b> Id of a variation that is selected by default. Attribute values for this variation will be included on first page surely.</li>
 <li><b>afterKey</b> This might be provided from previous search requests to enable pagination of variation entries</li>
</ul>
|===



[[webshop_searchpresets_variationlist]]
==== VariationList

Search for variation lists



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
[#getsearchfactory]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory

----




====== *Return type:*        xref:Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]


Get preset search factory.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$options`
|link:http://php.net/array[array^]
a|Available options:
<ul>
 <li><b>variationIds</b> List of variations to receive</li>
 <li><b>sorting</b> Configuration value to get sorting for</li>
 <li><b>sortingField</b> Field to sort items by. Will be appended to sorting list if sorting configuration is defined.</li>
 <li><b>sortingOrder</b> Order to sort items with ('asc', 'desc')</li>
 <li><b>page</b> The current page</li>
 <li><b>itemsPerPage</b> Number of items per page</li>
 <li><b>excludeFromCache</b> Set to true if results should not be linked to response</li>
</ul>
|===


[[webshop_itemsearch_services]]
===  Services
[[webshop_services_itemsearchservice]]
==== ItemSearchService

Execute item searches using the variation data interface



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Services`






===== Methods

[source%nowrap, php]
[#getresults]
----

public getResults($searches):array

----







Execute multiple item searches at once. Results will be mapped to the same keys as used in the given associative array of search factories.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$searches`
|
a|Associative array of search factories to execute. Result of each search request will be mapped to the key defined in this array.
|===


[source%nowrap, php]
[#getresult]
----

public getResult($searchFactory):array

----







Get result of a single search request.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$searchFactory`
|
a|The factory to get results for.
|===


[[webshop_order]]
== Order

[[webshop_order_contracts]]
===  Contracts
[[webshop_contracts_orderrepositorycontract]]
==== OrderRepositoryContract

Create orders from the webshop



===== Namespace

`Plenty\Modules\Webshop\Order\Contracts`






===== Methods

[source%nowrap, php]
[#placeorder]
----

public placeOrder():Plenty\Modules\Order\Models\Order

----




====== *Return type:*        xref:Order.adoc#order_models_order[`Order`]


Generate order data from current basket and place the order.

[source%nowrap, php]
[#createreturnorder]
----

public createReturnOrder($returnOrderData, $orderId = null):Plenty\Modules\Order\Models\Order

----




====== *Return type:*        xref:Order.adoc#order_models_order[`Order`]


Create a return order for some items of an existing order.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$returnOrderData`
|link:http://php.net/array[array^]
a|Data to create the return order with.

a|`$orderId`
|link:http://php.net/int[int^]
a|Id of the original order
|===


[[webshop_seo]]
== Seo

[[webshop_seo_contracts]]
===  Contracts
[[webshop_contracts_robotsrepositorycontract]]
==== RobotsRepositoryContract

Repository to read or write content of the robots.txt



===== Namespace

`Plenty\Modules\Webshop\Seo\Contracts`






===== Methods

[source%nowrap, php]
[#findbywebstoreid]
----

public findByWebstoreId($webstoreId):Plenty\Modules\Webshop\Seo\Models\Robots

----




====== *Return type:*        xref:Webshop.adoc#webshop_models_robots[`Robots`]


Get the content of the robots.txt for a single webstore.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$webstoreId`
|link:http://php.net/int[int^]
a|Id of the webstore to get the robots.txt for.
|===


[source%nowrap, php]
[#updatebywebstoreid]
----

public updateByWebstoreId($webstoreId, $data):Plenty\Modules\Webshop\Seo\Models\Robots

----




====== *Return type:*        xref:Webshop.adoc#webshop_models_robots[`Robots`]


Update the content of the robots.txt of a single webstore.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$webstoreId`
|link:http://php.net/int[int^]
a|Id of the webstore to update the robots.txt for.

a|`$data`
|link:http://php.net/string[string^]
a|Content of the robots.txt
|===



[[webshop_contracts_sitemapconfigurationrepositorycontract]]
==== SitemapConfigurationRepositoryContract

Repository for sitemap configuration



===== Namespace

`Plenty\Modules\Webshop\Seo\Contracts`






===== Methods

[source%nowrap, php]
[#findbywebstoreid]
----

public findByWebstoreId($webstoreId):Plenty\Modules\Webshop\Seo\Models\SitemapConfiguration

----




====== *Return type:*        xref:Webshop.adoc#webshop_models_sitemapconfiguration[`SitemapConfiguration`]


Get the sitemap configuration of a single webstore.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$webstoreId`
|link:http://php.net/int[int^]
a|Id of the webstore to get sitemap configuration for.
|===


[source%nowrap, php]
[#updatebywebstoreid]
----

public updateByWebstoreId($webstoreId, $data = []):Plenty\Modules\Webshop\Seo\Models\SitemapConfiguration

----




====== *Return type:*        xref:Webshop.adoc#webshop_models_sitemapconfiguration[`SitemapConfiguration`]


Update the sitemap configuration of a single webstore.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$webstoreId`
|link:http://php.net/int[int^]
a|Id of the webstore to get sitemap configuration for.

a|`$data`
|link:http://php.net/array[array^]
a|Sitemap configuration data
|===


[[webshop_seo_models]]
===  Models
[[webshop_models_robots]]
==== Robots

Model for the configured content of the robots.txt



===== Namespace

`Plenty\Modules\Webshop\Seo\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|value
    |link:http://php.net/string[string^]
    a|Content of the robots.txt file
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.


[[webshop_models_sitemapconfiguration]]
==== SitemapConfiguration

The sitemap configuration model



===== Namespace

`Plenty\Modules\Webshop\Seo\Models`





.Properties
[cols="3,1,6"]
|===
|Name |Type |Description

|contentCategory
    |link:http://php.net/int[int^]
    a|
|itemCategory
    |link:http://php.net/int[int^]
    a|
|item
    |link:http://php.net/int[int^]
    a|
|blog
    |link:http://php.net/int[int^]
    a|
|===


===== Methods

[source%nowrap, php]
[#toarray]
----

public toArray()

----







Returns this model as an array.

[[webshop_template]]
== Template

[[webshop_template_contracts]]
===  Contracts
[[webshop_contracts_templateconfigrepositorycontract]]
==== TemplateConfigRepositoryContract

Set configuration values from the plugin to be considered in internal functions.



===== Namespace

`Plenty\Modules\Webshop\Template\Contracts`






===== Methods

[source%nowrap, php]
[#registerconfigvalue]
----

public registerConfigValue($key, $value):Plenty\Modules\Webshop\Template\Contracts\TemplateConfigRepositoryContract

----




====== *Return type:*        xref:Webshop.adoc#webshop_contracts_templateconfigrepositorycontract[`TemplateConfigRepositoryContract`]


Register an internal configuration. Available configuration keys are:
&lt;ul&gt;
 &lt;li&gt;&lt;b&gt;currency.format&lt;/b&gt; Format to display the currency in monetary values.&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sort.defaultSorting&lt;/b&gt; Default item sorting criteria&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sort.defaultSortingSearch&lt;/b&gt; Default sorting criteria when searching for items&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.prioritySearch1&lt;/b&gt; First sorting criteria when searching for items&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.prioritySearch2&lt;/b&gt; Second sorting criteria when searching for items&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.prioritySearch3&lt;/b&gt; Third sorting criteria when searching for items&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.priorityCategory1&lt;/b&gt; First sorting criteria when searching for items of a category&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.priorityCategory2&lt;/b&gt; Second sorting criteria when searching for items of a category&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.priorityCategory3&lt;/b&gt; Third sorting criteria when searching for items of a category&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.dynamicInherit&lt;/b&gt; Set to true to adopts sorting criteria from item search options to grouping of variations&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.dynamicPrio1&lt;/b&gt; First sorting criteria when grouping variations in item search results&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.dynamicPrio2&lt;/b&gt; Second sorting criteria when grouping variations in item search results&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;item.name&lt;/b&gt; Set which item name should be used in the webshop.&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;item.displayName&lt;/b&gt; Define if the item name, the variation name or both names should be displayed in the webshop.&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;global.enableOldUrlPattern&lt;/b&gt; Item urls will be served with prefix &quot;a-{itemId}&quot; when enabled&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;language.activeLanguages&lt;/b&gt; List of languages that are enabled for the webshop&lt;/li&gt;
&lt;/ul&gt;

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$key`
|link:http://php.net/string[string^]
a|Configuration key to set value for

a|`$value`
|
a|Configuration value to set
|===


[[webshop_template_providers]]
===  Providers
[[webshop_providers_templateserviceprovider]]
==== TemplateServiceProvider

Service provider for template plugins



===== Namespace

`Plenty\Modules\Webshop\Template\Providers`






===== Methods

[source%nowrap, php]
[#overridetemplate]
----

public overrideTemplate($original, $override):void

----







Override a twig template. The new template will be used when the overridden template is going to be rendered.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$original`
|link:http://php.net/string[string^]
a|

a|`$override`
|link:http://php.net/string[string^]
a|
|===


[source%nowrap, php]
[#addtemplatealias]
----

public addTemplateAlias($original, $alias):void

----







Add an alias for a template. Rendering the template will also check for overrides of the alias template.

.*Parameters*
[cols="3,1,6"]
|===
|Name |Type |Description
a|`$original`
|link:http://php.net/string[string^]
a|

a|`$alias`
|link:http://php.net/string[string^]
a|
|===


