:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
= Plentymarkets interface documentation


[[webshop_consent]]
== Consent

[[webshop_consent_contracts]]
===  Contracts
[[webshop_contracts_consentrepositorycontract]]
==== ConsentRepositoryContract

Repository to register consents and check for users response.



===== Namespace

`Plenty\Modules\Webshop\Consent\Contracts`






===== Methods

[source%nowrap, php]
----

public registerConsentGroup($key, $label, $options = []):void // <1>

----


    
Register a new group of consents.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|Unique identifier of the group

|link:http://php.net/string[string^]
a|`$label`
|Displayed label of the group

|link:http://php.net/array[array^]
a|`$options`
|Additional options of the group. Available options are:
<ul>
  <li><b>necessary:boolean</b> True if the group is necessary and could not be declined</li>
  <li><b>description:string</b> Description of the group.</li>
  <li><b>position:number</b> The position of the group</li>
</ul>
|===


[source%nowrap, php]
----

public registerConsent($key, $label, $options = []):void // <1>

----


    
Register a new consent.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|Unique identifier of the consent.

|link:http://php.net/string[string^]
a|`$label`
|Displayed label of the consent.

|link:http://php.net/array[array^]
a|`$options`
|Additional options of the consent. Available options are:
<ul>
    <li><b>necessary:boolean</b> True of the consent is necessary and could not be declined</li>
    <li><b>description:string</b> Description of the consent</li>
    <li><b>provider:string</b> The provider of the cookie</li>
    <li><b>lifespan:string</b> Lifespan of the cookie</li>
    <li><b>policyUrl:string</b> URL to external privacy policy</li>
    <li><b>group:string</b> Identifier of an consent group</li>
    <li><b>position:number</b> The position of the consent in the group</li>
    <li><b>isOptOut:boolean</b> Select the consent by default. The user needs to decline the consent explicitly.</li>
    <li><b>cookieNames:array</b> Names of cookies which will be set. These cookies will not be blocked after the user confirmed the consent.</li>
</ul>
|===


[source%nowrap, php]
----

public getConsentGroups():Illuminate\Support\Collection // <1>

----


    
Get all consent groups including all consents.


===== Return type
    
<1>         xref:Miscellaneous.adoc#miscellaneous_support_collection[Collection]
    

[source%nowrap, php]
----

public hasResponse():bool // <1>

----


    
Check if the user has already responded the consents.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public setResponse($key, $isConsented = false):void // <1>

----


    
Set the response for a consent or a group of consents.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|The key of the consent group and the consent, e.g. "group.consent"
Use "*" as consent key to check if all entries of a group has a response, e.g. "group.*"

|link:http://php.net/bool[bool^]
a|`$isConsented`
|True if the user has accepted the consent or the group of consents
|===


[source%nowrap, php]
----

public isConsented($key):bool // <1>

----


    
Check if the user has consented.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|The key of the consent group and the consent, e.g. "group.consent"
Use "*" as consent key to check if all entries of a group has a response, e.g. "group.*"
|===


[[webshop_webshop]]
== Webshop

[[webshop_webshop_contracts]]
===  Contracts
[[webshop_contracts_checkoutrepositorycontract]]
==== CheckoutRepositoryContract

Repository to get and set checkout data



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
----

public getCurrency():string // <1>

----


    
Get the currently used currency.


===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public setCurrency($currency):void // <1>

----


    
Set the currency.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$currency`
|
|===


[source%nowrap, php]
----

public getShippingCountryId():int // <1>

----


    
Get the id of the current shipping country. Default to the configured country id from the webstore configuration.


===== Return type
    
<1> link:http://php.net/int[int^]
    


[[webshop_contracts_contactrepositorycontract]]
==== ContactRepositoryContract

Repository to get and set contact information for the webshop



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
----

public getContactId():int // <1>

----


    
Get the ID of the logged in contact or 0 for guests


===== Return type
    
<1> link:http://php.net/int[int^]
    

[source%nowrap, php]
----

public getContact():Plenty\Modules\Account\Contact\Models\Contact // <1>

----


    
Get the logged in contact


===== Return type
    
<1>         xref:Account.adoc#account_models_contact[Contact]
    

[source%nowrap, php]
----

public getContactClassId():int // <1>

----


    
Get the contact class ID of the logged in contact


===== Return type
    
<1> link:http://php.net/int[int^]
    

[source%nowrap, php]
----

public getContactClassData($contactClassId):array // <1>

----


    
Get the contact class data for the provided contact class ID


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$contactClassId`
|
|===


[source%nowrap, php]
----

public getDefaultContactClassId():int // <1>

----


    
Get the default contact class ID of the webstore


===== Return type
    
<1> link:http://php.net/int[int^]
    

[source%nowrap, php]
----

public showNetPrices():bool // <1>

----


    
Get Information if net prices should be shown


===== Return type
    
<1> link:http://php.net/bool[bool^]
    


[[webshop_contracts_giftcardrepositorycontract]]
==== GiftCardRepositoryContract

Repository to get information about gift cards and corresponding order items



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
----

public hasGiftCardPdf($orderId, $orderItemId, $campaignCodeOrderId):bool // <1>

----


    
Checks if a gift card document has already been created for this order item


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderId`
|

|link:http://php.net/int[int^]
a|`$orderItemId`
|

|link:http://php.net/int[int^]
a|`$campaignCodeOrderId`
|
|===


[source%nowrap, php]
----

public getGiftCardInformation($orderItemId):array // <1>

----


    
Get Information about the gift card


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderItemId`
|
|===


[source%nowrap, php]
----

public isReturnable($orderItemId):bool // <1>

----


    
Return true if its not a gift card or the codes are not redeemed


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderItemId`
|
|===


[source%nowrap, php]
----

public getReturnQuantity($orderItemId):int // <1>

----


    
Returnable quantity for giftCard


===== Return type
    
<1> link:http://php.net/int[int^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$orderItemId`
|
|===



[[webshop_contracts_localizationrepositorycontract]]
==== LocalizationRepositoryContract

Repository for webshop localization information



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
----

public getLanguage():string // <1>

----


    
Get the currently used language of the webshop visitor


===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getLocale():string // <1>

----


    
Get the current locale


===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getLanguageCode($countryCode = null):string // <1>

----


    
Get a ISO language code by given country code.


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$countryCode`
|
|===



[[webshop_contracts_sessionstoragerepositorycontract]]
==== SessionStorageRepositoryContract

Repository for webshop session information



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
----

public setSessionValue($key, $value):void // <1>

----


    
Set a value to a given key in the session


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|The key from session

|
a|`$value`
|The value will set to given key
|===


[source%nowrap, php]
----

public getSessionValue($key):void // <1>

----


    
Get a value from the session by a given key


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|The key to read from the session
|===


[source%nowrap, php]
----

public getCustomer():Plenty\Modules\Frontend\Session\Storage\Models\Customer // <1>

----


    
Get the customer session model


===== Return type
    
<1>         xref:Frontend.adoc#frontend_models_customer[Customer]
    

[source%nowrap, php]
----

public getOrder():Plenty\Modules\Frontend\Session\Storage\Models\Order // <1>

----


    
Get the order session model


===== Return type
    
<1>         xref:Frontend.adoc#frontend_models_order[Order]
    


[[webshop_contracts_urlbuilderrepositorycontract]]
==== UrlBuilderRepositoryContract

Generate url for items, variations and categories considering all affecting configurations.



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
----

public buildItemUrl($itemId, $lang = null):Plenty\Modules\Webshop\Helpers\UrlQuery // <1>

----


    
Build item url. Generate and write url to item data if not defined yet.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_helpers_urlquery[UrlQuery]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
|Id of the item to generate url for.

|link:http://php.net/string[string^]
a|`$lang`
|Language to generate the url in. Defaults to current language from session.
|===


[source%nowrap, php]
----

public buildCategoryUrl($categoryId, $lang = null, $webstoreId = null):Plenty\Modules\Webshop\Helpers\UrlQuery // <1>

----


    
Build category url by recursively prepending url names of parent categories.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_helpers_urlquery[UrlQuery]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
|Id of the category to get url for.

|link:http://php.net/string[string^]
a|`$lang`
|Language to generate the url in. Defaults to current language from session.

|link:http://php.net/int[int^]
a|`$webstoreId`
|Webstore to get url names for. Defaults to current webstore id.
|===


[source%nowrap, php]
----

public fillItemUrl($itemData):void // <1>

----


    
Store item data of loaded items to be reused when generating item or variation urls.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$itemData`
|Item data object returned from search request.
|===


[source%nowrap, php]
----

public buildVariationUrl($itemId, $variationId, $lang = null):Plenty\Modules\Webshop\Helpers\UrlQuery // <1>

----


    
Build variation url. Variation urls equal to item urls with the variation id appended.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_helpers_urlquery[UrlQuery]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
|Id of the item to generate url for.

|link:http://php.net/int[int^]
a|`$variationId`
|Id of the variation to generate url for.

|link:http://php.net/string[string^]
a|`$lang`
|Language to generate the url in. Defaults to current language from session.
|===


[source%nowrap, php]
----

public getSuffix($itemId, $variationId, $withVariationId = true):string // <1>

----


    
Get the suffix to be appended to item or variation urls.


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
|item id to be used in the suffix.

|link:http://php.net/int[int^]
a|`$variationId`
|variation id to be used in the suffix. Will be ignored when using Callisto urls.

|link:http://php.net/bool[bool^]
a|`$withVariationId`
|Set if the variation id should be included in the suffix. Not considered when using Callisto urls.
|===



[[webshop_contracts_webstoreconfigurationrepositorycontract]]
==== WebstoreConfigurationRepositoryContract

Repository for webstore information



===== Namespace

`Plenty\Modules\Webshop\Contracts`






===== Methods

[source%nowrap, php]
----

public getWebstoreConfiguration():Plenty\Modules\System\Models\WebstoreConfiguration // <1>

----


    
Get the webstore configuration


===== Return type
    
<1>         xref:System.adoc#system_models_webstoreconfiguration[WebstoreConfiguration]
    

[source%nowrap, php]
----

public getActiveLanguageList():array // <1>

----


    
Get the activate languages of the webstore


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getDefaultShippingCountryId():int // <1>

----


    
Get the default shipping-country-Id of the webstore


===== Return type
    
<1> link:http://php.net/int[int^]
    

[[webshop_webshop_events]]
===  Events
[[webshop_events_afterbasketitemtoorderitem]]
==== AfterBasketItemToOrderItem

Event for receiving or manupulating the order item



===== Namespace

`Plenty\Modules\Webshop\Events`






===== Methods

[source%nowrap, php]
----

public getOrderItem():array // <1>

----


    
Get order item data generated from the basket item.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getBasketItem():array // <1>

----


    
Get basket item data used to generate the order item from.


===== Return type
    
<1> link:http://php.net/array[array^]
    


[[webshop_events_validatevatnumber]]
==== ValidateVatNumber

Event to trigger validation of a vat number while creating new addresses. Failed validation will throw an exception.



===== Namespace

`Plenty\Modules\Webshop\Events`






===== Methods

[source%nowrap, php]
----

public getVatNumber():string // <1>

----


    
Get the vat number to validate.


===== Return type
    
<1> link:http://php.net/string[string^]
    

[[webshop_webshop_helpers]]
===  Helpers
[[webshop_helpers_numberformatter]]
==== NumberFormatter

Helper class for number formatting



===== Namespace

`Plenty\Modules\Webshop\Helpers`






===== Methods

[source%nowrap, php]
----

public formatDecimal($value, $decimal_places = -1):string // <1>

----


    
Format the given value to decimal


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/float[float^]
a|`$value`
|

|link:http://php.net/int[int^]
a|`$decimal_places`
|
|===


[source%nowrap, php]
----

public formatMonetary($value, $currencyISO):string // <1>

----


    
Format the given value to currency


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$value`
|

|
a|`$currencyISO`
|
|===



[[webshop_helpers_pluginconfig]]
==== PluginConfig

Helper to get plugin configuration values. Provides several methods to read configuration values and cast them into required type.



===== Namespace

`Plenty\Modules\Webshop\Helpers`






===== Methods

[source%nowrap, php]
----

public load():void // <1>

----


    
Initially load configuration values into member variables.


===== Return type
    
<1> 
    

[source%nowrap, php]
----

public getPluginName():string // <1>

----


    
Return the name of the plugin to get the configuration values for.


===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public getMultiSelectValue($key, $possibleValues = [], $default = []):array // <1>

----


    
Get values of a multiselect configuration.


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|The key of the configuration to read.

|link:http://php.net/array[array^]
a|`$possibleValues`
|List of possible configuration values. Will be returned if the configuration value is "all"

|link:http://php.net/array[array^]
a|`$default`
|A default value to return if the configuration is not set yet.
|===


[source%nowrap, php]
----

public getTextValue($key, $default = &quot;&quot;, $transformDefault = &quot;&quot;):string // <1>

----


    
Get the value of a text configuration.


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|The key of the configuration to read.

|link:http://php.net/string[string^]
a|`$default`
|A default value to return if the configuration is not set yet.

|link:http://php.net/string[string^]
a|`$transformDefault`
|A value to be interpreted as a default value.
Use this if you have defined a value in your config.json that should be handled as default value.
|===


[source%nowrap, php]
----

public getIntegerValue($key, $default):int // <1>

----


    
Get the value of an integer configuration.


===== Return type
    
<1> link:http://php.net/int[int^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|The key of the configuration to read.

|link:http://php.net/int[int^]
a|`$default`
|A default value to return if the configuration is not set yet.
|===


[source%nowrap, php]
----

public getBooleanValue($key, $default = false):bool // <1>

----


    
Get the value of a boolean configuration.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|The key of the configuration to read.

|link:http://php.net/bool[bool^]
a|`$default`
|A default value to return if the configuration is not set yet.
|===


[source%nowrap, php]
----

public getConfigValue($key, $default = null):void // <1>

----


    
Get a configuration value without any cast.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|The key of the configuration to read.

|
a|`$default`
|A default value to return if the configuration is not set yet.
|===



[[webshop_helpers_unitutils]]
==== UnitUtils

Convert plentymarkets unit keys into common unit codes.



===== Namespace

`Plenty\Modules\Webshop\Helpers`






===== Methods

[source%nowrap, php]
----

public static getHTML4Unit($unit = &quot;SMM&quot;):string // <1>

----


    
Return common code for a unit (&#039;m&#039;,&#039;cm&#039; &#039;mm&#039;).


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$unit`
|The internal unit key.
|===



[[webshop_helpers_urlquery]]
==== UrlQuery

Helper to generate and manipulate urls to be used in the webshop.



===== Namespace

`Plenty\Modules\Webshop\Helpers`






===== Methods

[source%nowrap, php]
----

public static create($path = null, $lang = null):Plenty\Modules\Webshop\Helpers\UrlQuery // <1>

----


    
Create a new instance.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_helpers_urlquery[UrlQuery]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$path`
|The path of the url.

|link:http://php.net/string[string^]
a|`$lang`
|The language of the generated url. Will be included automatically if it is different to the default language.
|===


[source%nowrap, php]
----

public static shouldAppendTrailingSlash():bool // <1>

----


    
Check if a trailing slash should be appended to urls.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

[source%nowrap, php]
----

public append($suffix):Plenty\Modules\Webshop\Helpers // <1>

----


    
Append a string to the path the url without checking for slashes.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_webshop_helpers[Helpers]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$suffix`
|String to append to the path.
|===


[source%nowrap, php]
----

public join($path):Plenty\Modules\Webshop\Helpers // <1>

----


    
Append a new path to the existing one. Ensure having a slash as glue between existing path and the new segment.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_webshop_helpers[Helpers]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$path`
|The new path to append.
|===


[source%nowrap, php]
----

public toAbsoluteUrl($includeLanguage = false):string // <1>

----


    
Return the absolute url by prepending the HTTPS domain of the current client.


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$includeLanguage`
|If true it will include the language at the beginning of the path.
|===


[source%nowrap, php]
----

public toRelativeUrl($includeLanguage = false):string // <1>

----


    
Return the path as a relative url.


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$includeLanguage`
|If true it will include the language at the beginning of the path.
|===


[source%nowrap, php]
----

public getPath($includeLanguage = false):string // <1>

----


    
Return the path. This equals the relative url without a leading slash.


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$includeLanguage`
|If true it will include the language at the beginning of the path.
|===


[source%nowrap, php]
----

public equals($path):bool // <1>

----


    
Compare current path to a string independent of a trailing slash.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$path`
|String to compare the current path to.
|===


[[webshop_webshop_hooks]]
===  Hooks
[[webshop_hooks_checkvatnumber]]
==== CheckVatNumber

Hook to execute validation of vat numbers. Can be triggered by emitting ValidateVatNumber while creating new addresses.



===== Namespace

`Plenty\Modules\Webshop\Hooks`






===== Methods

[source%nowrap, php]
----

public handle($vatNumberEvent):void // <1>

----


    
Validate the given vat number


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Webshop.adoc#webshop_events_validatevatnumber[ValidateVatNumber]
a|`$vatNumberEvent`
|Event emitted while creating new addresses.
|===


[[webshop_itemsearch]]
== ItemSearch

[[webshop_itemsearch_contracts]]
===  Contracts
[[webshop_contracts_facetextension]]
==== FacetExtension

Interface to add custom facets.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Contracts`






===== Methods

[source%nowrap, php]
----

public getAggregation():Plenty\Modules\Cloud\ElasticSearch\Lib\Search\Aggregation\AggregationInterface // <1>

----


    
Get the aggregation to apply the facet to the search results.


===== Return type
    
<1>         xref:Cloud.adoc#cloud_aggregation_aggregationinterface[AggregationInterface]
    

[source%nowrap, php]
----

public mergeIntoFacetsList($result):array // <1>

----


    
Merge facet data into list of facets.


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$result`
|Facet data
|===


[source%nowrap, php]
----

public extractFilterParams($filtersList):void // <1>

----


    
Extract search filters from filter paramters to be applied to the search request.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$filtersList`
|List of value ids for this facet. Possible values can be set by mergeIntoFacetsList()
|===


[[webshop_itemsearch_extensions]]
===  Extensions
[[webshop_extensions_itemsearchextension]]
==== ItemSearchExtension

Extend the search result by additional data or mutate raw data in search results.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Extensions`





[[webshop_itemsearch_factories]]
===  Factories
[[webshop_factories_basesearchfactory]]
==== BaseSearchFactory

Base factory to prepare and build search requests on variation data interface



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Factories`






===== Methods

[source%nowrap, php]
----

public inherit($inheritedProperties = []):Plenty\Modules\Webshop\ItemSearch\Factories\BaseSearchFactory // <1>

----


    
Create a new factory instance based on properties of an existing factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_basesearchfactory[BaseSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$inheritedProperties`
|List of properties to inherit or null to inherit all properties.
|===


[source%nowrap, php]
----

public withMutator($mutator, $excludeDependencies = false, $position = 1000):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add a mutator to transform search results.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_mutator_mutatorinterface[MutatorInterface]
a|`$mutator`
|The mutator itself

|link:http://php.net/bool[bool^]
a|`$excludeDependencies`
|Set to true to remove required data from the results after applying the mutator.
Fields will only be removed if they are not requested by the result fields of the search request.

|link:http://php.net/int[int^]
a|`$position`
|Position of the mutator. Mutators are executed in the order of their positions.
|===


[source%nowrap, php]
----

public createFilter($filterClass, $params = []):void // <1>

----


    
Add a filter. Will create a new instance of the filter class if not already created.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$filterClass`
|

|link:http://php.net/array[array^]
a|`$params`
|
|===


[source%nowrap, php]
----

public withFilter($filter):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add a filter. Will override existing filter instances.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_type_typeinterface[TypeInterface]
a|`$filter`
|
|===


[source%nowrap, php]
----

public withResultFields($fields):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set fields to be contained in search result.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$fields`
|Reference to a json file to load fields from or a list of field names.
|===


[source%nowrap, php]
----

public getResultFields():array // <1>

----


    
Get the requested result fields for this search request.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public hasResultField($field):bool // <1>

----


    
Check if result field is already included in the source of the search.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|The field to search for in result fields
|===


[source%nowrap, php]
----

public getAdditionalResultFields():array // <1>

----


    
Get additional result fields required by webshop mutators.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public withExtension($extensionClass, $extensionParams = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add an extension.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$extensionClass`
|Extension class to add.

|link:http://php.net/array[array^]
a|`$extensionParams`
|Additional parameters to pass to extensions constructor
|===


[source%nowrap, php]
----

public getExtensions():array // <1>

----


    
Get all registered extensions


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getMutators():array // <1>

----


    
Get all registered mutators


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public withAggregation($aggregation):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add an aggregation


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_aggregation_aggregationinterface[AggregationInterface]
a|`$aggregation`
|
|===


[source%nowrap, php]
----

public withSuggestion($suggestion):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add a suggestion


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_suggestion_suggestioninterface[SuggestionInterface]
a|`$suggestion`
|
|===


[source%nowrap, php]
----

public setPage($page, $itemsPerPage):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set pagination parameters.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
|
|===


[source%nowrap, php]
----

public sortBy($field, $order = \Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory::SORTING_ORDER_DESC):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add sorting parameters


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|The field to order by

|link:http://php.net/string[string^]
a|`$order`
|Direction to order results. Possible values: 'asc' or 'desc'
|===


[source%nowrap, php]
----

public sortByMultiple($sortingList):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add multiple sorting parameters


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$sortingList`
|List of sorting parameters. Each entry should have a 'field' and an 'order' property.
|===


[source%nowrap, php]
----

public setOrder($idList):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set the order of the search results by ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$idList`
|List of variation ids. Search results will be sorted in the same order.
|===


[source%nowrap, php]
----

public groupBy($field, $sortings = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Group results by field


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|The field to group properties by.

|link:http://php.net/array[array^]
a|`$sortings`
|List of sort criteria. Might contain string
|===



[[webshop_factories_facetsearchfactory]]
==== FacetSearchFactory

Prepare and build search requests to query facets



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Factories`






===== Methods

[source%nowrap, php]
----

public static create($facets):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Create a factory instance depending on a given set of facet values.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$facets`
|List of active facet values. If string is given, it will be exploded by ',' to a list of values.
|===


[source%nowrap, php]
----

public withMinimumCount():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Register extension to filter facets by minimum hit count.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public static default($options = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Get the default configuration of a search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options
<ul>
 <li><b>quantities</b> Quantities of the variations in the basket. This will be considered while calculating graduated prices</li>
 <li><b>setPriceOnly</b> Set to true to only consider prices for item sets</li>
</ul>
|===


[source%nowrap, php]
----

public setAdminPreview($isAdminPreview):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set preview mode for the search request.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$isAdminPreview`
|Set to true to enable preview.
|===


[source%nowrap, php]
----

public isActive():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter active variations


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public isInactive():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter inactive variations


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public hasItemId($itemId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variation by a single item id


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
|Item id to filter by.
|===


[source%nowrap, php]
----

public hasItemIds($itemIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by multiple item ids


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$itemIds`
|List of item ids to filter by.
|===


[source%nowrap, php]
----

public hasVariationId($variationId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variation by a single variation id.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$variationId`
|The variation id to filter by.
|===


[source%nowrap, php]
----

public hasVariationIds($variationIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by multiple variation ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$variationIds`
|List of variation ids to filter by.
|===


[source%nowrap, php]
----

public hasAtLeastOneAvailability($availabilityIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by multiple availability ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$availabilityIds`
|List of availability ids to filter by.
|===


[source%nowrap, php]
----

public hasSupplier($supplierId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by multiple availability ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$supplierId`
|The supplier id to filter by.
|===


[source%nowrap, php]
----

public hasManufacturer($manufacturerId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter manufacturers by id.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$manufacturerId`
|To filter by manufacturer
|===


[source%nowrap, php]
----

public hasEachProperty($propertyIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by multiple property ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$propertyIds`
|The property ids to filter by.
|===


[source%nowrap, php]
----

public isMain():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter only main variations


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public isChild():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter only child variations


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public isHiddenInCategoryList($isHidden = true):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter by visibility in category list.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$isHidden`
|Visibility in category list to filter by.
|===


[source%nowrap, php]
----

public isSalable():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by isSalable flag


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public isVisibleForClient($clientId = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by visibility for client


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$clientId`
|The client id to filter by. If null, default client id from config will be used.
|===


[source%nowrap, php]
----

public hasNameInLanguage($type = &quot;hasAnyNameInLanguage&quot;, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations having texts in a given language.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$type`
|The text field to filter by ('hasAny', 'hasName1', 'hasName2', 'hasName3')

|link:http://php.net/string[string^]
a|`$lang`
|The language to filter by. If null, language defined in session will be used.
|===


[source%nowrap, php]
----

public isInCategory($categoryId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations contained in a category.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
|A category id to filter variations by.
|===


[source%nowrap, php]
----

public hasAtLeastOnePrice($priceIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations having at least on price.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$priceIds`
|List of price ids to filter variations by
|===


[source%nowrap, php]
----

public hasPriceForCustomer():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations having at least one price accessible by current customer.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public hasPriceInRange($priceMin, $priceMax):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/float[float^]
a|`$priceMin`
|

|link:http://php.net/float[float^]
a|`$priceMax`
|
|===


[source%nowrap, php]
----

public hasTag($tagId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$tagId`
|
|===


[source%nowrap, php]
----

public hasAnyTag($tagIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$tagIds`
|
|===


[source%nowrap, php]
----

public groupByTemplateConfig():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Group results depending on a config value.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public isCrossSellingItem($itemId, $relation):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations having a cross selling relation to a given item.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
|Item id to filter cross selling items for

|link:http://php.net/string[string^]
a|`$relation`
|The relation of cross selling items.
|===


[source%nowrap, php]
----

public hasFacets($facetValues, $clientId = null, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by facets.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$facetValues`
|List of facet values. If string is given, it will be exploded by ';'

|link:http://php.net/int[int^]
a|`$clientId`
|Client id to filter facets by. If null, default client id from config will be used.

|link:http://php.net/string[string^]
a|`$lang`
|Language to filter facets by. If null, active language from session will be used.
|===


[source%nowrap, php]
----

public hasSearchString($query, $lang = null, $a = &quot;&quot;, $b = &quot;&quot;):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by given search string.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$query`
|The search string to filter variations by

|link:http://php.net/string[string^]
a|`$lang`
|The language to apply search on. If null, default language from session will be used

|link:http://php.net/string[string^]
a|`$a`
|

|link:http://php.net/string[string^]
a|`$b`
|
|===


[source%nowrap, php]
----

public hasNameString($query, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by searching names


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$query`
|The search string

|link:http://php.net/string[string^]
a|`$lang`
|Language to apply search on. If null, default language from session will be used.
|===


[source%nowrap, php]
----

public withLanguage($lang = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Only request given language.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$lang`
|Language to get texts for. If null, default language from session will be used.
|===


[source%nowrap, php]
----

public withImages($clientId = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Include images in result


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$clientId`
|The client id to get images for. If null, default client id from config will be used.
|===


[source%nowrap, php]
----

public withVariationAttributeMap($itemId, $initialVariationId, $afterKey = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Includes VariationAttributeMap for variation select


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
|

|link:http://php.net/int[int^]
a|`$initialVariationId`
|

|link:http://php.net/array[array^]
a|`$afterKey`
|
|===


[source%nowrap, php]
----

public withPropertyGroups($displaySettings = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$displaySettings`
|
|===


[source%nowrap, php]
----

public withOrderPropertySelectionValues():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withVariationProperties():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withUrls():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Append URLs to result.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withPrices($quantities = [], $setPriceOnly = false):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Append prices to result.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$quantities`
|

|link:http://php.net/bool[bool^]
a|`$setPriceOnly`
|
|===


[source%nowrap, php]
----

public withCurrentCategory():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set result as current category


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withDefaultImage():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Append default item image if images are requested by result fields and item does not have any image


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withBundleComponents():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add bundle component variations.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withSetComponents():void // <1>

----


    
Add set component variations to item set entries.


===== Return type
    
<1> 
    

[source%nowrap, php]
----

public withLinkToContent():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withGroupedAttributeValues():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withReducedResults():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withAvailability():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withTags():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withCategories():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withSuggestions($query = &quot;&quot;, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$query`
|

|link:http://php.net/string[string^]
a|`$lang`
|
|===


[source%nowrap, php]
----

public withDidYouMeanSuggestions($query):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$query`
|
|===


[source%nowrap, php]
----

public withSalableVariationCount():Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

[source%nowrap, php]
----

public inherit($inheritedProperties = []):Plenty\Modules\Webshop\ItemSearch\Factories\BaseSearchFactory // <1>

----


    
Create a new factory instance based on properties of an existing factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_basesearchfactory[BaseSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$inheritedProperties`
|List of properties to inherit or null to inherit all properties.
|===


[source%nowrap, php]
----

public withMutator($mutator, $excludeDependencies = false, $position = 1000):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add a mutator to transform search results.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_mutator_mutatorinterface[MutatorInterface]
a|`$mutator`
|The mutator itself

|link:http://php.net/bool[bool^]
a|`$excludeDependencies`
|Set to true to remove required data from the results after applying the mutator.
Fields will only be removed if they are not requested by the result fields of the search request.

|link:http://php.net/int[int^]
a|`$position`
|Position of the mutator. Mutators are executed in the order of their positions.
|===


[source%nowrap, php]
----

public createFilter($filterClass, $params = []):void // <1>

----


    
Add a filter. Will create a new instance of the filter class if not already created.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$filterClass`
|

|link:http://php.net/array[array^]
a|`$params`
|
|===


[source%nowrap, php]
----

public withFilter($filter):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add a filter. Will override existing filter instances.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_type_typeinterface[TypeInterface]
a|`$filter`
|
|===


[source%nowrap, php]
----

public withResultFields($fields):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set fields to be contained in search result.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$fields`
|Reference to a json file to load fields from or a list of field names.
|===


[source%nowrap, php]
----

public getResultFields():array // <1>

----


    
Get the requested result fields for this search request.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public hasResultField($field):bool // <1>

----


    
Check if result field is already included in the source of the search.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|The field to search for in result fields
|===


[source%nowrap, php]
----

public getAdditionalResultFields():array // <1>

----


    
Get additional result fields required by webshop mutators.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public withExtension($extensionClass, $extensionParams = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add an extension.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$extensionClass`
|Extension class to add.

|link:http://php.net/array[array^]
a|`$extensionParams`
|Additional parameters to pass to extensions constructor
|===


[source%nowrap, php]
----

public getExtensions():array // <1>

----


    
Get all registered extensions


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getMutators():array // <1>

----


    
Get all registered mutators


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public withAggregation($aggregation):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add an aggregation


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_aggregation_aggregationinterface[AggregationInterface]
a|`$aggregation`
|
|===


[source%nowrap, php]
----

public withSuggestion($suggestion):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add a suggestion


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_suggestion_suggestioninterface[SuggestionInterface]
a|`$suggestion`
|
|===


[source%nowrap, php]
----

public setPage($page, $itemsPerPage):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set pagination parameters.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
|
|===


[source%nowrap, php]
----

public sortBy($field, $order = \Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory::SORTING_ORDER_DESC):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add sorting parameters


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|The field to order by

|link:http://php.net/string[string^]
a|`$order`
|Direction to order results. Possible values: 'asc' or 'desc'
|===


[source%nowrap, php]
----

public sortByMultiple($sortingList):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add multiple sorting parameters


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$sortingList`
|List of sorting parameters. Each entry should have a 'field' and an 'order' property.
|===


[source%nowrap, php]
----

public setOrder($idList):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set the order of the search results by ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$idList`
|List of variation ids. Search results will be sorted in the same order.
|===


[source%nowrap, php]
----

public groupBy($field, $sortings = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Group results by field


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|The field to group properties by.

|link:http://php.net/array[array^]
a|`$sortings`
|List of sort criteria. Might contain string
|===



[[webshop_factories_variationsearchfactory]]
==== VariationSearchFactory

Prepare and build search requests to query variations



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Factories`






===== Methods

[source%nowrap, php]
----

public static default($options = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Get the default configuration of a search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options
<ul>
 <li><b>quantities</b> Quantities of the variations in the basket. This will be considered while calculating graduated prices</li>
 <li><b>setPriceOnly</b> Set to true to only consider prices for item sets</li>
</ul>
|===


[source%nowrap, php]
----

public setAdminPreview($isAdminPreview):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set preview mode for the search request.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$isAdminPreview`
|Set to true to enable preview.
|===


[source%nowrap, php]
----

public isActive():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter active variations


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public isInactive():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter inactive variations


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public hasItemId($itemId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variation by a single item id


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
|Item id to filter by.
|===


[source%nowrap, php]
----

public hasItemIds($itemIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by multiple item ids


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$itemIds`
|List of item ids to filter by.
|===


[source%nowrap, php]
----

public hasVariationId($variationId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variation by a single variation id.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$variationId`
|The variation id to filter by.
|===


[source%nowrap, php]
----

public hasVariationIds($variationIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by multiple variation ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$variationIds`
|List of variation ids to filter by.
|===


[source%nowrap, php]
----

public hasAtLeastOneAvailability($availabilityIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by multiple availability ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$availabilityIds`
|List of availability ids to filter by.
|===


[source%nowrap, php]
----

public hasSupplier($supplierId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by multiple availability ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$supplierId`
|The supplier id to filter by.
|===


[source%nowrap, php]
----

public hasManufacturer($manufacturerId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter manufacturers by id.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$manufacturerId`
|To filter by manufacturer
|===


[source%nowrap, php]
----

public hasEachProperty($propertyIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by multiple property ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$propertyIds`
|The property ids to filter by.
|===


[source%nowrap, php]
----

public isMain():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter only main variations


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public isChild():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter only child variations


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public isHiddenInCategoryList($isHidden = true):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter by visibility in category list.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$isHidden`
|Visibility in category list to filter by.
|===


[source%nowrap, php]
----

public isSalable():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by isSalable flag


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public isVisibleForClient($clientId = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by visibility for client


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$clientId`
|The client id to filter by. If null, default client id from config will be used.
|===


[source%nowrap, php]
----

public hasNameInLanguage($type = &quot;hasAnyNameInLanguage&quot;, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations having texts in a given language.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$type`
|The text field to filter by ('hasAny', 'hasName1', 'hasName2', 'hasName3')

|link:http://php.net/string[string^]
a|`$lang`
|The language to filter by. If null, language defined in session will be used.
|===


[source%nowrap, php]
----

public isInCategory($categoryId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations contained in a category.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$categoryId`
|A category id to filter variations by.
|===


[source%nowrap, php]
----

public hasAtLeastOnePrice($priceIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations having at least on price.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$priceIds`
|List of price ids to filter variations by
|===


[source%nowrap, php]
----

public hasPriceForCustomer():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations having at least one price accessible by current customer.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public hasPriceInRange($priceMin, $priceMax):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/float[float^]
a|`$priceMin`
|

|link:http://php.net/float[float^]
a|`$priceMax`
|
|===


[source%nowrap, php]
----

public hasTag($tagId):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$tagId`
|
|===


[source%nowrap, php]
----

public hasAnyTag($tagIds):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$tagIds`
|
|===


[source%nowrap, php]
----

public groupByTemplateConfig():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Group results depending on a config value.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public isCrossSellingItem($itemId, $relation):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations having a cross selling relation to a given item.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
|Item id to filter cross selling items for

|link:http://php.net/string[string^]
a|`$relation`
|The relation of cross selling items.
|===


[source%nowrap, php]
----

public hasFacets($facetValues, $clientId = null, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by facets.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$facetValues`
|List of facet values. If string is given, it will be exploded by ';'

|link:http://php.net/int[int^]
a|`$clientId`
|Client id to filter facets by. If null, default client id from config will be used.

|link:http://php.net/string[string^]
a|`$lang`
|Language to filter facets by. If null, active language from session will be used.
|===


[source%nowrap, php]
----

public hasSearchString($query, $lang = null, $a = &quot;&quot;, $b = &quot;&quot;):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by given search string.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$query`
|The search string to filter variations by

|link:http://php.net/string[string^]
a|`$lang`
|The language to apply search on. If null, default language from session will be used

|link:http://php.net/string[string^]
a|`$a`
|

|link:http://php.net/string[string^]
a|`$b`
|
|===


[source%nowrap, php]
----

public hasNameString($query, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Filter variations by searching names


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$query`
|The search string

|link:http://php.net/string[string^]
a|`$lang`
|Language to apply search on. If null, default language from session will be used.
|===


[source%nowrap, php]
----

public withLanguage($lang = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Only request given language.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$lang`
|Language to get texts for. If null, default language from session will be used.
|===


[source%nowrap, php]
----

public withImages($clientId = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Include images in result


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$clientId`
|The client id to get images for. If null, default client id from config will be used.
|===


[source%nowrap, php]
----

public withVariationAttributeMap($itemId, $initialVariationId, $afterKey = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Includes VariationAttributeMap for variation select


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$itemId`
|

|link:http://php.net/int[int^]
a|`$initialVariationId`
|

|link:http://php.net/array[array^]
a|`$afterKey`
|
|===


[source%nowrap, php]
----

public withPropertyGroups($displaySettings = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$displaySettings`
|
|===


[source%nowrap, php]
----

public withOrderPropertySelectionValues():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withVariationProperties():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withUrls():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Append URLs to result.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withPrices($quantities = [], $setPriceOnly = false):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Append prices to result.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$quantities`
|

|link:http://php.net/bool[bool^]
a|`$setPriceOnly`
|
|===


[source%nowrap, php]
----

public withCurrentCategory():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set result as current category


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withDefaultImage():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Append default item image if images are requested by result fields and item does not have any image


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withBundleComponents():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add bundle component variations.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withSetComponents():void // <1>

----


    
Add set component variations to item set entries.


===== Return type
    
<1> 
    

[source%nowrap, php]
----

public withLinkToContent():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withGroupedAttributeValues():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withReducedResults():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withAvailability():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withTags():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withCategories():Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

[source%nowrap, php]
----

public withSuggestions($query = &quot;&quot;, $lang = null):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$query`
|

|link:http://php.net/string[string^]
a|`$lang`
|
|===


[source%nowrap, php]
----

public withDidYouMeanSuggestions($query):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$query`
|
|===


[source%nowrap, php]
----

public withSalableVariationCount():Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    



===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

[source%nowrap, php]
----

public inherit($inheritedProperties = []):Plenty\Modules\Webshop\ItemSearch\Factories\BaseSearchFactory // <1>

----


    
Create a new factory instance based on properties of an existing factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_basesearchfactory[BaseSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$inheritedProperties`
|List of properties to inherit or null to inherit all properties.
|===


[source%nowrap, php]
----

public withMutator($mutator, $excludeDependencies = false, $position = 1000):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add a mutator to transform search results.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_mutator_mutatorinterface[MutatorInterface]
a|`$mutator`
|The mutator itself

|link:http://php.net/bool[bool^]
a|`$excludeDependencies`
|Set to true to remove required data from the results after applying the mutator.
Fields will only be removed if they are not requested by the result fields of the search request.

|link:http://php.net/int[int^]
a|`$position`
|Position of the mutator. Mutators are executed in the order of their positions.
|===


[source%nowrap, php]
----

public createFilter($filterClass, $params = []):void // <1>

----


    
Add a filter. Will create a new instance of the filter class if not already created.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$filterClass`
|

|link:http://php.net/array[array^]
a|`$params`
|
|===


[source%nowrap, php]
----

public withFilter($filter):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add a filter. Will override existing filter instances.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_type_typeinterface[TypeInterface]
a|`$filter`
|
|===


[source%nowrap, php]
----

public withResultFields($fields):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set fields to be contained in search result.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$fields`
|Reference to a json file to load fields from or a list of field names.
|===


[source%nowrap, php]
----

public getResultFields():array // <1>

----


    
Get the requested result fields for this search request.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public hasResultField($field):bool // <1>

----


    
Check if result field is already included in the source of the search.


===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|The field to search for in result fields
|===


[source%nowrap, php]
----

public getAdditionalResultFields():array // <1>

----


    
Get additional result fields required by webshop mutators.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public withExtension($extensionClass, $extensionParams = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add an extension.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$extensionClass`
|Extension class to add.

|link:http://php.net/array[array^]
a|`$extensionParams`
|Additional parameters to pass to extensions constructor
|===


[source%nowrap, php]
----

public getExtensions():array // <1>

----


    
Get all registered extensions


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public getMutators():array // <1>

----


    
Get all registered mutators


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public withAggregation($aggregation):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add an aggregation


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_aggregation_aggregationinterface[AggregationInterface]
a|`$aggregation`
|
|===


[source%nowrap, php]
----

public withSuggestion($suggestion):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add a suggestion


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Cloud.adoc#cloud_suggestion_suggestioninterface[SuggestionInterface]
a|`$suggestion`
|
|===


[source%nowrap, php]
----

public setPage($page, $itemsPerPage):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set pagination parameters.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$page`
|

|link:http://php.net/int[int^]
a|`$itemsPerPage`
|
|===


[source%nowrap, php]
----

public sortBy($field, $order = \Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory::SORTING_ORDER_DESC):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add sorting parameters


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|The field to order by

|link:http://php.net/string[string^]
a|`$order`
|Direction to order results. Possible values: 'asc' or 'desc'
|===


[source%nowrap, php]
----

public sortByMultiple($sortingList):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Add multiple sorting parameters


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$sortingList`
|List of sorting parameters. Each entry should have a 'field' and an 'order' property.
|===


[source%nowrap, php]
----

public setOrder($idList):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Set the order of the search results by ids.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$idList`
|List of variation ids. Search results will be sorted in the same order.
|===


[source%nowrap, php]
----

public groupBy($field, $sortings = []):Plenty\Modules\Webshop\ItemSearch\Factories // <1>

----


    
Group results by field


===== Return type
    
<1>         xref:Webshop.adoc#webshop_itemsearch_factories[Factories]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$field`
|The field to group properties by.

|link:http://php.net/array[array^]
a|`$sortings`
|List of sort criteria. Might contain string
|===


[[webshop_itemsearch_helpers]]
===  Helpers
[[webshop_helpers_facetextensioncontainer]]
==== FacetExtensionContainer

Container to collect facet extensions



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Helpers`






===== Methods

[source%nowrap, php]
----

public getFacetExtensions():array // <1>

----


    
Get all registered facet extensions.


===== Return type
    
<1> link:http://php.net/array[array^]
    

[source%nowrap, php]
----

public addFacetExtension($facetExtension):void // <1>

----


    
Add an extension to provide a custom facet.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|        xref:Webshop.adoc#webshop_contracts_facetextension[FacetExtension]
a|`$facetExtension`
|The extension describing the facet behavior
|===



[[webshop_helpers_resultfieldtemplate]]
==== ResultFieldTemplate

Collect templates to read required result fields for several views from.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Helpers`






===== Methods

[source%nowrap, php]
----

public static get($template):string // <1>

----


    
Get the path to result fields file from a plugin


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$template`
|The key of the template to get the path for.
|===


[source%nowrap, php]
----

public static load($template):array // <1>

----


    
Load result fields from a template file. Result field templates can be registered from a plugin.


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$template`
|The key of the template to load file contents for.
|===


[source%nowrap, php]
----

public setTemplate($event, $template, $overwriteExistingData = true):void // <1>

----


    
Set the path of a template to read result fields from.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$event`
|The event to set the template for.

|link:http://php.net/string[string^]
a|`$template`
|Path to the template to read result fields from.

|link:http://php.net/bool[bool^]
a|`$overwriteExistingData`
|Option to overwrite existing data
|===


[source%nowrap, php]
----

public setTemplates($templateMap, $overwriteExistingData = true):void // <1>

----


    
Set multiple templates to read result fields from.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$templateMap`
|

|link:http://php.net/bool[bool^]
a|`$overwriteExistingData`
|
|===


[source%nowrap, php]
----

public requireFields($event, $field = null):void // <1>

----


    
Add required fields to variation search requests.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$event`
|A single template event to set required fields for
or a map between template events and list of required fields

|
a|`$field`
|If first parameter describes a single template event
this parameter may contain a single result field or a list of field to require.
|===



[[webshop_helpers_sortinghelper]]
==== SortingHelper

Helper class to convert sorting configuration values into internal sorting paramters used by variation data interface.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Helpers`






===== Methods

[source%nowrap, php]
----

public getSorting($sortingConfig = null, $isCategory = true):array // <1>

----


    
Get sorting values from plugin configuration


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sortingConfig`
|The configuration value from the plugin. Contains a sorting field and a sorting order joined by an '_', e.g. 'item.id_asc'<br>
Possible sorting fields:
<ul>
 <li>item.id</li>
 <li>texts.name1</li>
 <li>texts.name2</li>
 <li>texts.name3</li>
 <li>variation.createdAt</li>
 <li>variation.updatedAt</li>
 <li>variation.id</li>
 <li>variation.number</li>
 <li>variation.availability.averageDays</li>
 <li>variation.position</li>
 <li>item.manufacturer.externalName</li>>
 <li>item.manufacturer.position</li>>
 <li>stock.net</li>
 <li>sorting.price.avg</li>
 <li>item.random</li>
 <li>item.feedbackDecimal</li>
</ul>

|link:http://php.net/bool[bool^]
a|`$isCategory`
|Get default sorting configuration for category or for search
|===


[source%nowrap, php]
----

public getCategorySorting($sortingConfig = null):array // <1>

----


    
Get sorting values for categories from config


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sortingConfig`
|The configuration value
|===


[source%nowrap, php]
----

public getSearchSorting($sortingConfig = null):array // <1>

----


    
Get sorting values for searches from config


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sortingConfig`
|The configuration value
|===


[source%nowrap, php]
----

public getUsedItemName():string // <1>

----


    
Get the result field for the name to be displayed in the webshop.


===== Return type
    
<1> link:http://php.net/string[string^]
    

[source%nowrap, php]
----

public splitPathAndOrder($sorting):array // <1>

----


    
Explode configuration entries containing the field to sort by and the sorting order joined by an &#039;_&#039;.


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sorting`
|Sorting configuration value, e.g. text.name_asc
|===


[source%nowrap, php]
----

public mapToInnerSorting($sorting):string // <1>

----


    
Map (outer) sorting from item list to (inner) sorting to be applied on grouped variations of one item.


===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$sorting`
|The sorting of the item list to get the inner sorting value for.
|===


[source%nowrap, php]
----

public static isLanguageSupported($lang):bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$lang`
|
|===


[source%nowrap, php]
----

public static isLanguageActivated($lang):bool // <1>

----


    



===== Return type
    
<1> link:http://php.net/bool[bool^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$lang`
|
|===


[source%nowrap, php]
----

public static getM10lByLanguage($lang, $fallback = &quot;en&quot;):string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$lang`
|

|link:http://php.net/string[string^]
a|`$fallback`
|
|===


[source%nowrap, php]
----

public static getLanguageByM10l($lang, $fallback = &quot;english&quot;):string // <1>

----


    



===== Return type
    
<1> link:http://php.net/string[string^]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$lang`
|

|link:http://php.net/string[string^]
a|`$fallback`
|
|===


[[webshop_itemsearch_searchpresets]]
===  SearchPresets
[[webshop_searchpresets_basketitems]]
==== BasketItems

Query basket items.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>variationIds</b> Ids of basket items to get data for</li>
 <li><b>quantities</b> Quantity of each item to be considered when searching prices</li>
 <li><b>language</b> Required items to have a name configured in this language</li>
</ul>
|===



[[webshop_searchpresets_categoryitems]]
==== CategoryItems

Query items for a single category



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>categoryId</b> Category id to get variations for</li>
 <li><b>facets</b> Active facets to filter variations by</li>
 <li><b>sorting</b> Configuration value from plugin config</li>
 <li><b>page</b> Current page</li>
 <li><b>itemsPerPage</b> Number of items per page</li>
 <li><b>priceMin</b> Minimum price of the variations</li>
 <li><b>priceMax</b> Maximum price of the variations</li>
</ul>
|===



[[webshop_searchpresets_crosssellingitems]]
==== CrossSellingItems

Query cross selling items related to single item.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>itemId</b> Id of the item to get cross selling items for</li>
 <li><b>relation</b> The relation to consider when getting cross selling items. Default: 'Similar'</li>
 <li><b>sorting</b> Sorting of the returned items</li>
</ul>
|===



[[webshop_searchpresets_facets]]
==== Facets

Query facets for the item search of the webstore.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\FacetSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_facetsearchfactory[FacetSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>facets</b> Values of active facets.</li>
 <li><b>categoryId</b> Category Id to filter variations by.</li>
 <li><b>query</b> Search string to get variations by.</li>
 <li><b>autocomplete</b> Flag indicating if autocomplete search should be used (boolean). Will only be used if 'query' is defined.</li>
</ul>
|===



[[webshop_searchpresets_liveshoppingitems]]
==== LiveShoppingItems

Query live shopping items.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>itemId</b> Id of an item to be queried</li>
 <li><b>itemIds</b> List of item ids to be queried</li>
 <li><b>sorting</b> Sorting of returned item</li>
 <li><b>resultFields</b> List of result fields to be used when querying items. Will use ResultField template for list items if not defined.</li>
</ul>
|===



[[webshop_searchpresets_manufactureritems]]
==== ManufacturerItems

Query items by manufacturer.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>manufacturerId</b> Id of the manufacturer to query items for.</li>
 <li><b>sorting</b> Sorting of items</li>
 <li><b>itemsPerPage</b> Number of items per page</li>
 <li><b>page</b> Current page of results</li>
</ul>
|===



[[webshop_searchpresets_searchitems]]
==== SearchItems

Query items from the item search of the webstore.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>query</b> The search string</li>
 <li><b>facets</b> Facet values of active facets</li>
 <li><b>sorting</b> Configuration value from plugin config</li>
 <li><b>page</b> The current page</li>
 <li><b>itemsPerPage</b> Number of items per page</li>
 <li><b>priceMin</b> Minimum price of the variations</li>
 <li><b>priceMax</b> Maximum price of the variations</li>
 <li><b>autocomplete</b> Flag indicating if autocompletion should be used</li>
</ul>
|===



[[webshop_searchpresets_searchpreset]]
==== SearchPreset

Define a preset of search request parameters to be reused for common search requests.
 * 



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):void // <1>

----


    
Get the search factory from the preset.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|
|===



[[webshop_searchpresets_searchsuggestions]]
==== SearchSuggestions

Query items to display search suggestions



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>sorting</b> Sorting of items</li>
 <li><b>query</b> Search query to get suggestions for</li>
</ul>
|===



[[webshop_searchpresets_singleitem]]
==== SingleItem

Get item to be displayed on single item pages



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>itemId</b> Item id to get</li>
 <li><b>variationId</b> Variation id to get. If not defined, plugin configuration will be considered if main or child variation should be displayed.</li>
 <li><b>setCategory</b> Flag indicating if item should be set as current item to be displayed in breadcrumbs</li>
</ul>
|===



[[webshop_searchpresets_tagitems]]
==== TagItems

Query items by tag id.



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>tagIds</b> List of tag ids to query items by</li>
 <li><b>priceMin</b> Minimum price to filter items by</li>
 <li><b>priceMax</b> Maximum price to filter items by</li>
</ul>
|===



[[webshop_searchpresets_variationattributemap]]
==== VariationAttributeMap

Append list of all variations for attribute selection in item views



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options
<ul>
 <li><b>itemId</b> Id of the to get variations and attributes for</li>
 <li><b>variationId</b> Id of a variation that is selected by default. Attribute values for this variation will be included on first page surely.</li>
 <li><b>afterKey</b> This might be provided from previous search requests to enable pagination of variation entries</li>
</ul>
|===



[[webshop_searchpresets_variationlist]]
==== VariationList

Search for variation lists



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\SearchPresets`






===== Methods

[source%nowrap, php]
----

public static getSearchFactory($options):Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory // <1>

----


    
Get preset search factory.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_factories_variationsearchfactory[VariationSearchFactory]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|Available options:
<ul>
 <li><b>variationIds</b> List of variations to receive</li>
 <li><b>sorting</b> Configuration value to get sorting for</li>
 <li><b>sortingField</b> Field to sort items by. Will be appended to sorting list if sorting configuration is defined.</li>
 <li><b>sortingOrder</b> Order to sort items with ('asc', 'desc')</li>
 <li><b>page</b> The current page</li>
 <li><b>itemsPerPage</b> Number of items per page</li>
 <li><b>excludeFromCache</b> Set to true if results should not be linked to response</li>
</ul>
|===


[[webshop_itemsearch_services]]
===  Services
[[webshop_services_itemsearchservice]]
==== ItemSearchService

Execute item searches using the variation data interface



===== Namespace

`Plenty\Modules\Webshop\ItemSearch\Services`






===== Methods

[source%nowrap, php]
----

public getResults($searches):array // <1>

----


    
Execute multiple item searches at once. Results will be mapped to the same keys as used in the given associative array of search factories.


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$searches`
|Associative array of search factories to execute. Result of each search request will be mapped to the key defined in this array.
|===


[source%nowrap, php]
----

public getResult($searchFactory):array // <1>

----


    
Get result of a single search request.


===== Return type
    
<1> link:http://php.net/array[array^]
    

.*Parameters*
|===
|Type |Name |Description
|
a|`$searchFactory`
|The factory to get results for.
|===


[[webshop_order]]
== Order

[[webshop_order_contracts]]
===  Contracts
[[webshop_contracts_orderrepositorycontract]]
==== OrderRepositoryContract

Create orders from the webshop



===== Namespace

`Plenty\Modules\Webshop\Order\Contracts`






===== Methods

[source%nowrap, php]
----

public placeOrder():Plenty\Modules\Order\Models\Order // <1>

----


    
Generate order data from current basket and place the order.


===== Return type
    
<1>         xref:Order.adoc#order_models_order[Order]
    

[source%nowrap, php]
----

public createReturnOrder($returnOrderData, $orderId = null):Plenty\Modules\Order\Models\Order // <1>

----


    
Create a return order for some items of an existing order.


===== Return type
    
<1>         xref:Order.adoc#order_models_order[Order]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$returnOrderData`
|Data to create the return order with.

|link:http://php.net/int[int^]
a|`$orderId`
|Id of the original order
|===


[[webshop_seo]]
== Seo

[[webshop_seo_contracts]]
===  Contracts
[[webshop_contracts_robotsrepositorycontract]]
==== RobotsRepositoryContract

Repository to read or write content of the robots.txt



===== Namespace

`Plenty\Modules\Webshop\Seo\Contracts`






===== Methods

[source%nowrap, php]
----

public findByWebstoreId($webstoreId):Plenty\Modules\Webshop\Seo\Models\Robots // <1>

----


    
Get the content of the robots.txt for a single webstore.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_models_robots[Robots]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$webstoreId`
|Id of the webstore to get the robots.txt for.
|===


[source%nowrap, php]
----

public updateByWebstoreId($webstoreId, $data):Plenty\Modules\Webshop\Seo\Models\Robots // <1>

----


    
Update the content of the robots.txt of a single webstore.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_models_robots[Robots]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$webstoreId`
|Id of the webstore to update the robots.txt for.

|link:http://php.net/string[string^]
a|`$data`
|Content of the robots.txt
|===



[[webshop_contracts_sitemapconfigurationrepositorycontract]]
==== SitemapConfigurationRepositoryContract

Repository for sitemap configuration



===== Namespace

`Plenty\Modules\Webshop\Seo\Contracts`






===== Methods

[source%nowrap, php]
----

public findByWebstoreId($webstoreId):Plenty\Modules\Webshop\Seo\Models\SitemapConfiguration // <1>

----


    
Get the sitemap configuration of a single webstore.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_models_sitemapconfiguration[SitemapConfiguration]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$webstoreId`
|Id of the webstore to get sitemap configuration for.
|===


[source%nowrap, php]
----

public updateByWebstoreId($webstoreId, $data = []):Plenty\Modules\Webshop\Seo\Models\SitemapConfiguration // <1>

----


    
Update the sitemap configuration of a single webstore.


===== Return type
    
<1>         xref:Webshop.adoc#webshop_models_sitemapconfiguration[SitemapConfiguration]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$webstoreId`
|Id of the webstore to get sitemap configuration for.

|link:http://php.net/array[array^]
a|`$data`
|Sitemap configuration data
|===


[[webshop_seo_models]]
===  Models
[[webshop_models_robots]]
==== Robots

Model for the configured content of the robots.txt



===== Namespace

`Plenty\Modules\Webshop\Seo\Models`





.Properties
|===
|Type |Name |Description

|link:http://php.net/string[string^]
    |value
    |Content of the robots.txt file
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----


    
Returns this model as an array.




[[webshop_models_sitemapconfiguration]]
==== SitemapConfiguration

The sitemap configuration model



===== Namespace

`Plenty\Modules\Webshop\Seo\Models`





.Properties
|===
|Type |Name |Description

|link:http://php.net/int[int^]
    |contentCategory
    |
|link:http://php.net/int[int^]
    |itemCategory
    |
|link:http://php.net/int[int^]
    |item
    |
|link:http://php.net/int[int^]
    |blog
    |
|===


===== Methods

[source%nowrap, php]
----

public toArray()

----


    
Returns this model as an array.



[[webshop_template]]
== Template

[[webshop_template_contracts]]
===  Contracts
[[webshop_contracts_templateconfigrepositorycontract]]
==== TemplateConfigRepositoryContract

Set configuration values from the plugin to be considered in internal functions.



===== Namespace

`Plenty\Modules\Webshop\Template\Contracts`






===== Methods

[source%nowrap, php]
----

public registerConfigValue($key, $value):Plenty\Modules\Webshop\Template\Contracts\TemplateConfigRepositoryContract // <1>

----


    
Register an internal configuration. Available configuration keys are:
&lt;ul&gt;
 &lt;li&gt;&lt;b&gt;currency.format&lt;/b&gt; Format to display the currency in monetary values.&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sort.defaultSorting&lt;/b&gt; Default item sorting criteria&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sort.defaultSortingSearch&lt;/b&gt; Default sorting criteria when searching for items&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.prioritySearch1&lt;/b&gt; First sorting criteria when searching for items&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.prioritySearch2&lt;/b&gt; Second sorting criteria when searching for items&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.prioritySearch3&lt;/b&gt; Third sorting criteria when searching for items&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.priorityCategory1&lt;/b&gt; First sorting criteria when searching for items of a category&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.priorityCategory2&lt;/b&gt; Second sorting criteria when searching for items of a category&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.priorityCategory3&lt;/b&gt; Third sorting criteria when searching for items of a category&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.dynamicInherit&lt;/b&gt; Set to true to adopts sorting criteria from item search options to grouping of variations&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.dynamicPrio1&lt;/b&gt; First sorting criteria when grouping variations in item search results&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;sorting.dynamicPrio2&lt;/b&gt; Second sorting criteria when grouping variations in item search results&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;item.name&lt;/b&gt; Set which item name should be used in the webshop.&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;item.displayName&lt;/b&gt; Define if the item name, the variation name or both names should be displayed in the webshop.&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;global.enableOldUrlPattern&lt;/b&gt; Item urls will be served with prefix &quot;a-{itemId}&quot; when enabled&lt;/li&gt;
 &lt;li&gt;&lt;b&gt;language.activeLanguages&lt;/b&gt; List of languages that are enabled for the webshop&lt;/li&gt;
&lt;/ul&gt;


===== Return type
    
<1>         xref:Webshop.adoc#webshop_contracts_templateconfigrepositorycontract[TemplateConfigRepositoryContract]
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|Configuration key to set value for

|
a|`$value`
|Configuration value to set
|===


[[webshop_template_providers]]
===  Providers
[[webshop_providers_templateserviceprovider]]
==== TemplateServiceProvider

Service provider for template plugins



===== Namespace

`Plenty\Modules\Webshop\Template\Providers`






===== Methods

[source%nowrap, php]
----

public overrideTemplate($original, $override):void // <1>

----


    
Override a twig template. The new template will be used when the overridden template is going to be rendered.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$original`
|

|link:http://php.net/string[string^]
a|`$override`
|
|===


[source%nowrap, php]
----

public addTemplateAlias($original, $alias):void // <1>

----


    
Add an alias for a template. Rendering the template will also check for overrides of the alias template.


===== Return type
    
<1> 
    

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$original`
|

|link:http://php.net/string[string^]
a|`$alias`
|
|===


